openshift/hypershift

hypershift-operator/controllers/hostedcluster_controller.go
Currently when deleting a hostedCluster it won't delete any owned nodePool causing a race between CAPI deleting the underlying machineSets and the nodePool CR wanting to recreate them.
=> Add support for hostedCluster to delete all nodePools

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
When deleting a hostedCluster we want to garbage collect all nodePools referencing that cluster
=> Fetch nodePool by clusterName

README.md, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, test/e2e/quick_start_test.go
Rename to a known predictable name so it can be tooling like autoscaling can be coonfigured to consume it ahead of time
=> Rename target cluster kubeconfig

api/v1alpha1/nodepool_types.go, api/v1alpha1/zz_generated.deepcopy.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
This fixes patch operations against the type where .autoScaling=null.
Depends on https://github.com/openshift/hypershift/pull/28
=> Make the optional NodePool.AutoScaling field a pointer

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/manifests/autoscaler/manifests.go, test/e2e/quick_start_test.go
The client used by CAPI machine controller expects the kubeconfig to follow this naming convention
https://github.com/kubernetes-sigs/cluster-api/blob/5c85a0a01ee44ecf7c8a3c3fdc867a88af87d73c/util/secret/secret.go#L29-L33
=> Rename kubeconfig for target cluster

hypershift-operator/controllers/hostedcluster/manifests/autoscaler/manifests.go
This was mistakenly changed here https://github.com/openshift/hypershift/pull/40/files#diff-53eadb56aff39c25c42ea90aef35d6ff05c80c37aab763211f8d9c1306553177R59
=> Set back right target kubeconfig key for autoscaling

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/manifests/clusterapi/manifests.go, hypershift-operator/controllers/hostedcluster/manifests/controlplaneoperator/manifests.go
follow on to #47 for https://issues.redhat.com/browse/HOSTEDCP-85
Breaking out namespace scoped rules from `ClusterRoles` into `Roles`
Topic for discussion:
For now, we only create per-guest `ClusterRoleBindings`, not `ClusterRoles` i.e. the` ClusterRoles` are shared among the `ClusterRoleBindings`.  Do we want per-guest `ClusterRoles` as well?
=> hypershift-operator: minimize ClusterRole use

docs/api.md
Proposal for changes to the API to support BYO infra for hypershift on AWS
So we need infra information to satisfy these requirements:
1. Know where to place the machines, with the proper subnet, instance profile, and security groups.
- Question for this ... do we always want to have a default nodepool generated from the HostedCluster? or are we going to eventually require you to create those resources separately?
2. Create a cloud configuration file so that the in-tree AWS provider in the KCM can manage load balancers, pvs. 
3. Setup the openvpn config so that machine IPs can be routed through the VPN.
=> API changes for BYO AWS infra

Makefile, cmd/install/assets/assets.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_externalinfraclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
This patch introduces a new `api` make target which should be run whenever code
in the `openshift.io/hypershift/api` package changes. It regenerates things like
deepcopy boilerplate and CRD manifest files. Overall this means binary builds
are faster as we don't run controller-gen unnecessarily.
There's also a hack to work around controller-gen's behavior that prepends the
CRD YAML with document separators which break deserialization. The hack makes it
so we can live with the raw output of controller-gen without post-processing it
without dealing with additional shell work.
In a followup we should introduce a step to the `verify` target which detects
missed `api` executions for PRs.
=> build: optimize code generation

.gitignore
I extract the kubeconfig for my guest cluster into my hypershift directory often and have added it to a commit a few times.
Not sure if this would help anyone else, but it would help me :)
=> workflow: ignore kubeconfig file

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/manifests/controlplaneoperator/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/util/util.go
This drops machineSets in favour of machineDeployments as the scalable resources for nodePools.
It also polish the nodePool controller and add a watcher on the underlying scalable resource.
This is a first step towards enabling rolling upgrades for compute nodes.
=> Introduce machineDeployments

Makefile, cmd/install/assets/hypershift-operator/hypershift.openshift.io_externalinfraclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
This patch fixes an api generation regression introduced by https://github.com/openshift/hypershift/pull/60
which causes the new thirdparty package contents to be processed by the
code generation tooling. The codegen tools should only be applied to the
hypershift api package itself, not things in thirdparty.
=> Makefile: fix api generation target

Makefile, vendor/modules.txt
Update the verify target to ensure that the usual fmt/vet/codegen
operations don't result in any git diffs. This is intended to help
catch missed updates in pull requests.
Fixes #68
Fixes #69
=> Makefile: improve the verify target

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/render/kube_apiserver.go, control-plane-operator/controllers/hostedcontrolplane/render/manifests.go
Start to untangle the components from one another by extracting the
kube-apiserver manifests into its own template rendering context
and input parameter structure. This is one small step towards managing
the component discretely as its own operand.
=> Extract kube-apiserver manifests

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Fixes the guest cluster ingress proxy.  The HCP does not exist in the same namespace as the IngressController and, if the Owner does not exist in the same namespace as the resource, garbage collection immediately removes the resource.
=> HCP: remove IngressController OwnerRef

HACKING.md, test/e2e/e2e_suite_test.go, test/e2e/quick_start_test.go
The test process should handle graceful shutdown in response to a
SIGTERM or SIGINT. To achieve this, provide each Test* function access
to a global test context.Context which will be closed upon receipt
of SIGINT or SIGTERM on the main test thread. This gives test functions
an opportunity to execute deferred calls.
=> e2e: plumb a cancellable context through the e2e code

api/v1alpha1/hostedcluster_types.go, api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
Improves readability on CLI for `HostedCluster` and `NodePool`
```
$ oc get hostedclusters -A
NAMESPACE   NAME        VERSION   READY   KUBECONFIG
clusters    tugboat-1   4.7.0     true    tugboat-1-admin-kubeconfig
$ oc get nodepools -A
NAMESPACE   NAME        CLUSTER     NODECOUNT   AUTOSCALING
clusters    tugboat-1   tugboat-1   2           False
```
=> Additional print columns for CLI

.gitignore, cmd/create/create.go, cmd/kubeconfig/create.go, go.mod, vendor/modules.txt
This commit introduces a `create kubeconfig` command to the CLI which renders a
kubeconfig with a context for every HostedCluster resource. The kubeconfig for
each cluster is based on the secret referenced by the status of the
HostedCluster.
This is a helper meant to be incorporated into other CLI workflows.
=> cli: Add a `create kubeconfig` command to help working with control planes

cmd/infra/aws/create.go
Fixes nil pointer when calling `hypershift create cluster` where that command invokes create infra but is unable to pass a log.
We can find a cleaner solution for log passing later.
=> Hack logging to work where create infra is composed

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/render/types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/manifests/controlplaneoperator/manifests.go, hypershift-operator/controllers/hostedcluster/manifests/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
This makes it possible for machines to get a kubernetes cluster tag that
matches the rest of the infra for the cluster:
kubernetes.io/cluster/[infra-name]=owned
Renaming the CAPI cluster also required renaming the kubeconfig secret to access the cluster. Instead of having the control plane operator know about the CAPI requirements, it now creates a secret named `admin-kubeconfig` with a key of `kubeconfig`. The hosted cluster controller copies this secret to the appropriate name/key required by CAPI.
=> Use InfraID as CAPI cluster name

HACKING.md, README.md, api/fixtures/example.go, cmd/cluster/create.go, control-plane-operator/controllers/hostedcontrolplane/assets/ignition-configs/99-worker-ssh.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/manifests/controlplaneoperator/manifests.go
SSH public key isn't actually a requirement for creating a control plane or node
pools. Make the field optional to reduce the prerequisite list for users. In the
future we should consider removing SSH key from HostedControlPlane entirely as
this is probably a property of NodePool.
=> Remove HostedCluster SSH public key requirement

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
A matching bug in the bootstrap pod upgrade behavior causes a race which leads
to the bootstrap pod sometimes being deleted during a rollout. When the delete
code wins the race, rollout hangs. When the delete code loses the race,
everything works normally.
Fix the matching bug to make the deletion behavior work consistently as
intended.
=> Fix upgrade race that stalls rollouts

README.md, cmd/cluster/create.go, cmd/cluster/destroy.go, cmd/cluster/log.go, cmd/destroy/destroy.go, cmd/infra/aws/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/ec2.go, cmd/infra/aws/ec2_sg.go, cmd/infra/aws/iam.go
The `create cluster` command can automatically create infrastructure. This commit adds
a `destroy cluster` command that knows how to delete the hostedcluster, wait for that
to finish, and then destroy the infrastructure.
=> Add a `destroy cluster` command which can delete infrastructure

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
Remove the unused hostedcluster.status.ready field and clean up
printer column metadata.
=> Remove unused hostedcluster ready field

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
This commit implements another missing piece of the HostedCluster version API to
track the completion time of rollouts. The HostedControlPlane is responsible for
tracking the transition time of its image rollouts and now reflects that on its
status using a new LastReleaseImageTransitionTime field. That transition time is
then mirrored to the HostedCluster during version the status calculation when
updating history entries.
=> Implement version history completion time

HACKING.md, cmd/cluster/create.go, cmd/cluster/destroy.go, cmd/infra/aws/create.go, test/e2e/control_plane_upgrade_test.go, test/e2e/e2e_suite_test.go, test/e2e/helpers.go, test/e2e/quick_start_test.go
This commit expands the e2e coverage by incorporating the CLI workflows for
creating and destroying infrastructure for a cluster. This will provide
meaningful coverage for the documented workflows as well as make the tests
function totally independently, allowing for test clusters that don't share
infrastructure.
=> Expand e2e to exercise CLI infrastructure workflow

README.md, cmd/cluster/create.go, cmd/cluster/destroy.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/iam.go, test/e2e/control_plane_upgrade_test.go, test/e2e/quick_start_test.go
This commit makes the `create cluster` command generate IAM unique to the
cluster by default. The defaulting before this commit led to situations where
clusters in the same account (local development, CI, etc.) could be broken by CI
or developer activities inadvertantly deleting the shared profile.
A safer default is to share no infra per cluster, including IAM. The option to
provide a profile for sharing is still supported, just no longer the default.
=> Make create cluster generate IAM by default

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/manifests/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
Before this commit, control planes were created in a namespace named
the same as the HostedCluster, which is not unique in space. This commit
improves the situation by making the control plane namespace a function
of the HostedCluster namespace and name.
=> Place control planes in unique namespaces

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Fix a broken namespace reference which causes delete to hang by preventing
the HCP controller from finding control plane resources.
=> Fix namespace ref causing HCP deletion to hang

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Change the HostedControlPlane LastReleaseImageTransitionTime field to be a
pointer because the field is optional and has no default value when the resource
is created. This fixes a brief status update error that occurs when first
syncing where no zero value is provided.
=> Make HostedControlPlane image transition time field a pointer

cmd/infra/aws/destroy_iam.go
destroy iam should not throw an error when resources have already been deleted
=> Fixes for destroy iam when resources don't exist

cmd/cluster/dump.go, cmd/dump/dump.go, main.go, test/e2e/control_plane_upgrade_test.go, test/e2e/e2e_suite_test.go, test/e2e/helpers.go, test/e2e/quick_start_test.go
Creates a new command `dump cluster` that outputs relevant resource yamls and pod logs for a given HostedCluster.
Invokes the command from e2e before destroying a cluster.
=> Dump cluster resources in e2e

docs/api.md
This change adds options for the cluster autoscaler to the api doc.
These additions mirror the options that are currently exposed on
OpenShift through the ClusterAutoscaler resource with the addition of
the `ExtraArgs` field to allow arbitrary flags on the autoscaler.
Also cleanup the references to "Autoscaler" and "Autoscaling" to be
inline with upstream capitalization.
This PR is in support of [HOSTEDCP-82](https://issues.redhat.com/browse/HOSTEDCP-82)
=> API changes for cluster autoscaling options

api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hypershift-operator/controllers/nodepool/nodepool_controller.go
This introduce node autorepair in the nodePool API by managing opinionated MHCs.
The configuration is intentionally narrowed down to a bool. Once this is tested in a realistic scenario and we gather feedback we can reconsider exposing more config for flexibility in the nodePool API if we need to.
Follow up:
- Refactor nodePool controller to align with hostedCluster controller patterns.
=> Add support for nodePools autorepair

Dockerfile, api/fixtures/example.go
When using the render path for creating openshift clusters the hostedcluster resource has 
```
status:
conditions: null
```
Which causes kube unable to apply it
```
error: error validating "/Users/krglosse@us.ibm.com/gopath/src/github.ibm.com/alchemy-containers/kodieshandyscripts/render": error validating data: ValidationError(HostedCluster.status.conditions): invalid type for io.openshift.hypershift.v1alpha1.HostedCluster.status.conditions: got "string", expected "array"; if you choose to ignore these errors, turn validation off with --validate=false
```
By explicitly putting in an empty status condition it will template as:
```
status:
conditions: []
```
instead. Allowing Kube to apply it.
=> Use non-deprecated registry for base go image and explicitly define empty array for status conditions on cluster create

hypershift-operator/controllers/machineconfigserver/machineconfigserver_controller.go, hypershift-operator/controllers/machineconfigserver/manifests.go, hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
Refactor the nodePool controller to match common patterns:
- Manifest generation and reconciliation for managed resources.
- Drop explicit requeueing in favour of watching managed resources.
=> Refactor nodePool controller

hack/container-run.sh
This change adds a script for running make commands encapsulated in a
container. It will attempt to use podman or docker, and an openshift
golang release image. This should make it easier for people without the
proper go lang toolchain to run most of the make targets.
=> add container-run.sh to hack folder

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Fixes bug where the privileged scc is deleted and recreated everytime a hosted cluster is removed.
=> move to using cluster role to eliminate removal of privileged scc on cluster delete

cmd/cluster/create.go
The flag is only required when not specifying infra.json
Can be determined at runtime
=> Make basedomain flag not required

cmd/cluster/create.go, cmd/infra/aws/create.go, cmd/infra/aws/util.go
This commit tries to improve the failed stack creation handling by:
1. Preserving failed stacks by default unless otherwise specified by the `--delete-infra-on-failure` flag
2. Dumping stack events on failure so that specific resource creation failures can be identified without going to AWS
=> cli: Improve failed stack creation handling

api/fixtures/example.go, cmd/cluster/create.go, cmd/cluster/destroy.go, cmd/infra/aws/cloudformation/cluster.yaml, cmd/infra/aws/create.go, test/e2e/control_plane_upgrade_test.go, test/e2e/helpers.go, test/e2e/quick_start_test.go
Before this commit, the admin's AWS credentials passed to `create cluster` were
copied into the guest cluster for use by each credentials context. The AWS
credentials passed to `create cluster` are assumed to be super-privileged and
not intended to be leaked into guest clusters.
Now, when creating a new cluster, OCP is given credentials for users created
specifically for that cluster as part of infra creation.
This is another step towards IAM isolation by introducing new policies for each
HostedCluster credentials context (KubeCloudControllerCreds and
NodePoolManagementCreds) and creating new users associated with each of those
policies. The CloudFormation template takes care of creating the policies and
users and exposes the credentials as outputs.
=> Use bespoke, narrowly scoped AWS users for guest clusters

cmd/infra/aws/create.go, cmd/infra/aws/destroy.go
@ironcladlou 
This is the fix for an issue that results in ELBs and SGs not being cleaned up and stack deletion failing in regions other than `us-east-1`.
=> create unique AWS client config for route53

cmd/cluster/create.go, cmd/cluster/destroy.go
Allow the user to specify the kubeconfig with a flag, defaulting to
the KUBECONFIG environment variable.
=> cli: add a --kubeconfig flag

cmd/cluster/create.go, cmd/cluster/destroy.go
This reverts commit 2b1920278fc7cc53597dff0f167a3e5866ceb468.
We need to refactor client handling to fix this properly, and e2e
is broken due to an empty kubeconfig right now. So revert the
problematic fix and we can try again later.
=> Revert "cli: add a --kubeconfig flag"

cmd/infra/aws/create.go, cmd/infra/aws/destroy.go, cmd/infra/aws/util.go
Consolidate AWS session and config handling and introduce a default
AWS SDK retry mechanism to hopefully help smooth out transient throttling
errors we often see in CI. Efficiacy of retries using the SDK seems to
vary by service, so we need to try this and observe how well it works in
the real world.
=> cli: Try to improve AWS client retry handling

cmd/cluster/create.go, cmd/cluster/destroy.go, cmd/cluster/dump.go, cmd/install/install.go, cmd/kubeconfig/create.go, cmd/nodepool/create.go, cmd/util/client.go
Uses a common function to create a Kubernetes client in CLI and increases Burst and QPS for client config.
Gets rid of logs like:
```
I0420 16:48:16.574910 1636022 request.go:655] Throttling request took 1.001307884s, request: GET:https://api.cewong-dev.hypershift.cesarwong.com:6443/apis/flowcontrol.apiserver.k8s.io/v1beta1?timeout=32s
```
=> Use common client function for CLI

cmd/cluster/create.go
Ensures that the content of existing secrets with the same name are overwritten with whatever is getting created.
=> Switch to server-side Apply on cluster create

api/fixtures/example.go, cmd/cluster/create.go, cmd/cluster/destroy.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/iam.go
Before this commit, the admin's AWS credentials passed to create cluster were
copied into the guest cluster for use by each credentials context. The AWS
credentials passed to create cluster are assumed to be super-privileged and
not intended to be leaked into guest clusters.
Now, when creating a new cluster, OCP is given credentials for users created
specifically for that cluster as part of infra creation.
This is another step towards IAM isolation by introducing new policies for each
HostedCluster credentials context (KubeCloudControllerCreds and
NodePoolManagementCreds) and creating new users associated with each of those
policies. The CloudFormation template takes care of creating the policies and
users and exposes the credentials as outputs.
Reimplementation of …
=> iam: Create IAM users with policies to inject into clusters

cmd/cluster/create.go, cmd/cluster/destroy.go, cmd/infra/aws/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/util/util.go, test/e2e/control_plane_upgrade_test.go, test/e2e/e2e_suite_test.go, test/e2e/helpers.go, test/e2e/quick_start_test.go
This commit cleans up the AWS client handling throughout the CLI. From a given
entrypoint, AWS clients are now created exactly once and shared amongst all
components.
* Enables all the `create` and `destroy` commands to accept preallocated client
instances from the caller.
* Lifts all client creation up to the nearest entrypoint of each usage context
and injects them downwards from there.
* Consolidates all session and config creation into a single utilty package.
* Sets some new defaults for the SDK's built-in retry logic.
Further work should be done to tweak the SDK's built-in retry facilities, and
that can now be done centrally to start with and individual services can be
further tweaked as issues are identified.
=> cli: Add AWS Go SDK client retry handling tweaks

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, docs/api.md
This change makes autoscaling an optional field for hostedcluster
resources. Also updates docs and generated files.
=> add optional tag and omitempty to autoscaling field

control-plane-operator/controllers/hostedcontrolplane/assets/registry/cluster-imageregistry-config.yaml
Currently `image-registry` operator in the guest cluster is `Degraded` with
```
Unable to apply resources: unable to sync storage configuration: exactly one storage type should be configured at the same time, got 2: [EmptyDir S3]
```
This is indeed the case
```
$ oc get configs.imageregistry.operator.openshift.io cluster -oyaml
...
storage:
emptyDir: {}
s3:
virtualHostedStyle: false
```
This PR removes our `emptyDir` storage block from the registry config and allows `image-registry-operator` to manage its own cloud provider based storage.
After this PR
```
$ oc get configs.imageregistry.operator.openshift.io cluster -oyaml
...
storage:
managementState: Managed
s3:
bucket: sjenning-dev-image-registry-us-west-1-siwglyeeqksfjhengjdgrlbq
encrypt: true
region: us-west-1
virtualHostedStyle: …
```
=> use image-registry managed s3 storage

cmd/infra/aws/create.go, cmd/infra/aws/route53.go
Route53 API calls to look up and manipulate zones often fail with throttling
issues in chaotic environments like the CI account. This commit adds explicit
retry/backoff handling for critical operations during infrastructure creation so
that transient errors don't fail the entire infrastructure creation attempt.
=> cli: Add explicit retry/backoff handling to route53 calls

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/manifests.go, control-plane-operator/controllers/hostedcontrolplane/resources.go, hypershift-operator/controllers/machineconfigserver/machineconfigserver_controller.go, hypershift-operator/controllers/machineconfigserver/manifests.go, hypershift-operator/controllers/machineconfigserver/resources.go
Moves all control plane services to be reconciled versus just created
Reviewer assistance:
Main path to trace:
**hostedControlPlane_controller.go**
ensureInfrastructure -> reconcileKubeAPIServerServiceNodePortResources -> reconcileKubeAPIServerServiceLoadBalancer
ensureInfrastructure -> reconcileKubeAPIServerServiceLoadBalancerResources -> reconcileKubeAPIServerServiceLoadBalancer
ensureInfrastructure -> reconcileVPNServerServiceNodePortResources -> reconcileVPNServerServiceNodePort
ensureInfrastructure -> reconcileVPNServerServiceLoadBalancerResources -> reconcileVPNServerServiceLoadBalancer
ensureInfrastructure -> reconcileOauthServiceNodePortResources -> reconcileOauthServiceNodePort
ensureInfrastructure -> reconcileOauthServerServiceRouteResources -> reconcileOauthServiceClusterIP, …
=> Reconcile all control plane services

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Fix bug in https://github.com/openshift/hypershift/pull/180 that break KAS -> Node network communication when using a VPN Service of type NodePort
=> CPO: use nodeport for external openvpn port

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, hypershift-operator/controllers/externalinfracluster/externalinfracluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Introduce a `None` platform type which will allow for a provider agnostic
control plane. There's more work to do (some AWS stuff like CAPI is still
deployed) but this is enough to get started.
=> Initial API support for provider agnostic control planes

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
Just added this to see what everyone thinks
Current looks like this:
```
NAME       VERSION   KUBECONFIG                        AVAILABLE 
example3                                               False        
```
Proposed:
While the cluster is coming up
```
NAME       VERSION   KUBECONFIG                        PROGRESS    AVAILABLE   REASON
example3   4.7.7                                       Partial     False       HostedClusterIsNotAvailable
```
When it's completed
```
NAME       VERSION   KUBECONFIG                        PROGRESS    AVAILABLE   REASON
example3   4.7.7     example3-admin-kubeconfig         Completed   True        HostedClusterIsAvailable
```
=> Add progress and reason to hostedcluster printable columns

hypershift-operator/controllers/machineconfigserver/machineconfigserver_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/main.go
Before this patch, the node pool and machine config server controllers could
block forever during failed release image lookups, preventing further
reconcilation including deletion handling. The result is an invalid pull secret
for the specified image would prevent the cluster from ever finalizing.
This patch introduces fixed timeouts for the pod-based release image lookups and
also moves the lookup after deletion handling so that deletes will always be
handled.
=> Prevent release image lookup failures from blocking deletion

test/e2e/quick_start_test.go
Before this commit, if the e2e test failed to created the HostedCluster
resource, infrastructure could be leaked/orphaned. Now the create/destroy
options are provided with additional options which enable the destroy command to
tear down infrastructure even if the HostedCluster doesn't exist. This increases
the chance we'll cleanly destroy all infrastructure when test failures occur.
=> e2e: Improve cluster destroy reliability

control-plane-operator/controllers/hostedcontrolplane/assets/apiserver-haproxy/kube-apiserver-proxy.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/cluster-version-operator/cluster-version-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/kube-controller-manager/kube-controller-manager-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/kube-scheduler/kube-scheduler-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/oauth-apiserver/oauth-apiserver-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/oauth-openshift/oauth-server-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/openshift-apiserver/openshift-apiserver-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/openshift-controller-manager/cluster-policy-controller-deployment.yaml
This is a followup to #199 (73ddc4) to ensure pods and deployments
that don't specify a service account still use the pull secret provided
on the HostedCluster spec. This is to enable the use of private image
repositories for release images.
=> Fix more private release image repository issues

control-plane-operator/controllers/hostedcontrolplane/assets/openshift-controller-manager/openshift-controller-manager-deployment.yaml
Adds the release image pull secret reference to the OpenShift controller
manager deployment so that it works when using a private release image.
=> Add missing pull secret to deployment

api/fixtures/example.go, api/v1alpha1/hostedcluster_types.go, cmd/cluster/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, test/e2e/helpers.go, test/e2e/quick_start_test.go
This PR removes the `initialComputeReplicas` field from the `HostedCluster` resource.
We've been talking about this for a while and this creates a clean conceptual break between the `HostedCluster` and the Nodes that join the `HostedControlPlane`.
`hypershift create cluster` has been modified to directly create the `NodePool` when `--node-pool-replicas` flag is greater than 0. This maintains the old behavior.
=> Remove initialComputeReplicas from HostedCluster

api/fixtures/example.go, api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, cmd/nodepool/create.go, hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
This PR allows for the creation of baremetal workers
Remaining issues:
- cluster-api still deploys. `capa-controller-manager` stuck in `ContainerCreating` due to
`MountVolume.SetUp failed for volume "credentials" : secret "node-provider-creds" not found`
- `cluster-autoscaler` runs but continuous error in the logs `E0430 04:42:36.855542       1 reflector.go:138] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: machinedeployments.cluster.x-k8s.io is forbidden: User "system:serviceaccount:clusters-example:cluster-autoscaler" cannot list resource "machinedeployments" in API group "cluster.x-k8s.io" at the cluster scope`
example HostedCluster
```
apiVersion: hypershift.openshift.io/v1alpha1
kind: …
```
=> Allow baremetal workers with Platform None

control-plane-operator/controllers/hostedcontrolplane/assets/apiserver-haproxy/kube-apiserver-proxy.yaml
Static pods are not allowed to reference secrets.
The present behavior is that the kubelet is able to fetch the static pod image using the pull secret we lay down on the host in `/var/lib/kubelet/config.json`.
By referencing a secret, we launch the haproxy pod on the host, but the kubelet is rejected from mirroring the pod back to the API server.
```
"Failed creating a mirror pod for ... is forbidden: a mirror pod may not reference secrets"
```
=> haproxy static pod cannot reference a pull secret

api/fixtures/example.go, api/v1alpha1/hostedcluster_types.go, cmd/cluster/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/iam.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_machineconfigservers.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/cluster-bootstrap/service-account-issuer-discovery-clusterrolebinding.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/kube-apiserver/config.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/manifests.go
The idea here is to eliminate the publicly readable s3 bucket and its contents from the infrastructure requirements.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery
`ServiceAccountIssuerDiscovery` went beta (default enabled) in 1.20 and GA in 1.21
A new `Route` to the KAS endpoint (not suitable for API call) will be used for exposing the OIDC discovery endpoint.
```
...
services:
- service: OIDC
servicePublishingStrategy:
type: Route
...
```
The OIDC Route can be disabled by setting the `servicePublishingStrategy.type` to `None`.
The combination of `issuerURL` and service account `SigningKey` on the HC spec makes a flexible API for both automated and externally managed OIDC setups.
The biggest point of contention is …
=> Allow KAS-provided or externally managed OIDC service account issuer discovery

cmd/cluster/create.go, cmd/cluster/destroy.go, cmd/util/client.go
This PR adds a label based on `hypershift-cli-` + `InfraID` for uniqueness on `cluster create` command
```
kind: Secret
metadata:
creationTimestamp: "2021-05-06T17:33:19Z"
labels:
createdby: hypershift-cli-sc45-trf25
```
and deletes the secrets on `cluster destroy` command
```
INFO[0079] Deleted role policy                           policy=sc42-hfvlp-worker-policy role=sc42-hfvlp-worker-role
INFO[0079] Deleted role                                  role=sc42-hfvlp-worker-role
INFO[0079] Deleting Secrets                              namespace=clusters
INFO[0079] Successfully destroyed cluster and infrastructure  infraID=sc42-hfvlp name=sc42 namespace=clusters
```
=> Simple CLI tracking and cleanup of generated secrets in clusters namespace

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
The hypershift-operator generates an admin kubeconfig secret in the
hostedcluster namespace for interfacing with the hosted control plane.
Before this commit, deleting the hostedcluster orphaned that secret, which
users don't manage. This commit introduces an owner reference from the secret
to the hostedcluster so that when the hostedcluster is deleted, so is the
secret. Otherwise this is basically a resource leak.
=> hypershift-operator: Ensure owner refs on controller-generated secret

cmd/cluster/destroy.go
Before this commit, running `destroy cluster` with no infra ID argument silently
failed to clean up CLI-created secrets because the code was using un-defaulted
input which in this case is an empty value.
This commit fixes the code to use the post-validation/defaulting infra ID value.
=> cli: Fix secret cleanup when no infra ID is specified

test/e2e/control_plane_upgrade_test.go
https://github.com/openshift/hypershift/pull/250 broke the test
build. This commit fixes it.
=> e2e: fix broken build

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Before this PR we were setting hcp.Spec.Kubeconfig to satisfy capi controllers naming expectations, i.e https://github.com/kubernetes-sigs/cluster-api/blob/5c85a0a01ee44ecf7c8a3c3fdc867a88af87d73c/util/secret/secret.go#L29-L33. This secret is bubbled up to the HC CR and presented as the end user consumable and therefore it uses the public facing API Server.
This PR does two things:
- Drop the opinionated naming convention from hcp.Spec.Kubeconfig so it lets it use defaults to create the public facing API server kubeconfig secret.
- Hardcode and generate the CAPI naming compliant kubeconfig secret with the internal network API server. This secret has the same kubeconfig than service-network-admin-kubeconfig.
This results in one additional kubeconfig secret.
=> Let CAPI use internal network kubeconfig

cmd/cluster/create.go, cmd/infra/aws/create_iam.go
Before this commit, the OIDC discovery phase of `create infra` would
fail immediately upon any error to get the cluster ingress config.
This patch improves robustness by making the lookup retry until the
context is cancelled, which should make the command more likely to
succeed in the face of transient error conditions.
=> cli: Make OIDC discovery retry until cancelled

api/fixtures/example.go, cmd/cluster/create.go
This commit adds an optional `--annotations` flag to the `create cluster`
command which allows the user to provide annotations which will be
added to the hostedcluster. The flag can be passed multiple times to
add many annotations.
This is useful for things like associating a CI-generated cluster with
its CI metadata (Prow URLs, etc.)
=> cli: Support user-provided hostedcluster annotations

Makefile
When building the entire project, include the e2e binary as well to
ensure it compiles.
=> Add e2e to the default build target

control-plane-operator/main.go
Use an image that contains https://github.com/openshift/etcd-operator/pull/1
This allows etcd to run in the latest CI version of OCP 4.8
=> Temporarily change etcd operator image to one that works

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
When deploying with platform "None", SigningKey is not required, and
IssuerURL can use a default value.
=> Makes SigningKey and IssuerURL optional

control-plane-operator/controllers/hostedcontrolplane/assets/apiserver-haproxy/haproxy.cfg, control-plane-operator/controllers/hostedcontrolplane/assets/apiserver-haproxy/kube-apiserver-proxy.yaml
- Adds logging of connections processed by haproxy
- Adds health checks to log when connectivity fails to an apiserver. Health check queries /health route
- Specifies a directory for haproxy config which allows for additional haproxy confs to be placed in the directory and a merge of them will be done to have the final haproxy conf. Allows for additional endpoints through haproxy (IBM sends registry traffic through haproxy in certain private only configurations)
=> update haproxy with logging and ability to specify multiple configs

control-plane-operator/controllers/hostedcontrolplane/config/network.go, control-plane-operator/controllers/hostedcontrolplane/etcd/params.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/config.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/vpn/clientconfig.go, control-plane-operator/controllers/hostedcontrolplane/vpn/deployment.go, control-plane-operator/controllers/hostedcontrolplane/vpn/params.go, control-plane-operator/controllers/hostedcontrolplane/vpn/serverconfig.go, control-plane-operator/controllers/hostedcontrolplane/vpn/service.go, control-plane-operator/controllers/hostedcontrolplane/vpn/serviceacct.go, control-plane-operator/controllers/hostedcontrolplane/vpn/workerdeployment.go
For individual reconcile functions, it is not clear to see what
parameters are required for each to do their job. This change modifies
reconcile functions for KCM, Etcd and VPN to explicitly pass parameters
for reconciliation.
=> Make recocile functions stateless (kcm, etcd, vpn)

examples/cluster-logging/README.md, examples/cluster-logging/manifests/eo-namespace.yaml, examples/cluster-logging/manifests/eo-operator-group.yaml, examples/cluster-logging/manifests/eo-subscription.yaml, examples/cluster-logging/manifests/ol-namespace.yaml, examples/cluster-logging/manifests/ol-operator-group.yaml, examples/cluster-logging/manifests/ol-subscription.yaml, examples/cluster-logging/operator/cluster-logging.yaml, examples/user-workload-monitoring/README.md, examples/user-workload-monitoring/manifests/user-workload-monitoring-config.yaml
Adds two sets of documentation.
1. integration with mgmt cluster logging to view control plane logs across namespaces
2. integration with mgmt cluster user workload monitoring to view metrics of hosted control plane machinery
I assume we can grow each set of documentation over time.
=> Sample integrations with mgmt cluster services

version/version.go
The previous URL for looking up OCP images was deprecated and is now
defunct, causing image lookup failures. This commit fixes the URL to
point at the new location for OCP amd64 release metadata and should
fix image lookups.
=> Fix broken OCP release image API URL

control-plane-operator/controllers/hostedcontrolplane/assets/olm/catalog-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/olm-operator-deployment.yaml
error seen in a 4.6 management cluster:
```
2021-06-08T21:31:38.365Z	ERROR	controller-runtime.manager.controller.hostedcontrolplane	Reconciler error	{"reconciler group": "hypershift.openshift.io", "reconciler kind": "HostedControlPlane", "name": "tyler11", "namespace": "master-tyler11", "error": "failed to ensure control plane: failed to apply some manifests: [failed to apply manifest user-manifests-bootstrapper-pod.yaml: pods \"manifests-bootstrapper\" is forbidden: error looking up service account master-tyler11/user-manifests-bootstrapper: serviceaccount \"user-manifests-bootstrapper\" not found, failed to apply manifest catalog-operator-deployment.yaml: failed to create typed patch object: .spec.template.spec.containers[name=\"catalog-operator\"].ports: element 0: associative list …
```
=> fix olm deployment

cmd/cluster/create.go
Before this commit, if the release image couldn't be discovered and
no --release-image flag was provided, the CLI would blindly continue
creating cluster infra and an invalid HostedCluster resource.
This commit fixes validation so that if release image discovery fails,
the command fails fast and requires user input for thr release image.
=> cli: fix release image validation

api/fixtures/example.go, cmd/cluster/create.go
Before this commit, `create cluster` didn't create a NodePool if the
desired node pool replicas value is zero. However, a NodePool with
zero replicas is a valid and sometimes useful state.
This commit changes `create cluster` to always create a NodePool even
if the value is zero. To skip creating a NodePool entirely, use a replica
value of -1 instead.
=> cli: always create a NodePool with the desired replicas

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
The hypershift operator uses thirdparty i.e upstream tooling for autoscaling (cluster autoscaler) and cluster/machine lifecycle (CAPI).
A particular version of these images must be tied to a particular Hypershift release version.
This PR ensure all third party image references are pinned to a particular tag.
Eventually this images be mirrored will be pulled from an internal registry.
=> Pin version for third party release images

cmd/infra/aws/destroy.go, cmd/infra/aws/destroy_iam.go
Before this change, a warning message from the destroy command would
print something like:
```
msg="WARNING: error during destroy, will retry" error="[{},{},{}]"
```
With this PR, the actual error message is printed out
=> Fix warning error in infra/iam destroy output

Dockerfile
`make` was changed to build the e2e test binary after we broke it once and realized that e2e binary build was not covered by CI.
However, we do not need the e2e binary in the image builds for hypershift
This PR switches to a make target that doesn't build e2e.
@ironcladlou @enxebre
=> skip e2e binary during image builds

control-plane-operator/controllers/hostedcontrolplane/assets/cluster-bootstrap/cluster-default-ingress-controller.yaml
The ingress resource is different then the one listed in ROKS toolkit today:
https://github.com/openshift/ibm-roks-toolkit/blob/master/assets/cluster-bootstrap/cluster-ingresscontrollers-02-config.yaml#L10
Note that at least currently that is always set to External in IBM ROKS clusters. This ensures ibmcloud deployments are aligned with those values (ingress controller crashes otherwise)
Does not result in changes to other providers
=> ensure ingress matches ibmcloud's current status in ROKS toolkit

api/v1alpha1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
The a34f1881abe0730c0736ee4f8dee7d05eb0eece9 commit introduces an Unmanaged etcd
management type and incorporates the health of the unmanaged etcd configuration
into hostedcluster availability condition computation. However, the approach in
that commit violates the single source of truth invariant for hostedcluster
availability calculation, which makes it too easy to introduce bugs which cause
condition flapping or other inconsistencies.
This commit refactors the status handling to be consistent with the rest of the
controller by:
- Introducing a new condition type "UnmanagedEtcdAvailable" which is used to
track the status of unmanaged etcd which can be composed into more coarse
grained availability checks
- Updating the hostedcluster availability calculation to take into account the
new …
=> Fix hostedcluster availability calculation relative to unmanaged etcd

api/v1alpha1/nodepool_types.go, control-plane-operator/controllers/hostedcontrolplane/assets/machine-config-server/machine-config-server-secret.yaml, control-plane-operator/controllers/hostedcontrolplane/render/manifests.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/ignitionserver/manifests.go, hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, ignition-server/controllers/cache.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/main.go
Initially we were running long living MCS per NodePool each of them exposed in a different endpoint.
openshift#269 enabled us to have one single ignition endpoint per cluster which was proxying requests to long living MCS.
openshift#275 secured the proxy server with a token and https.
Now this PR changes the proxy to be a server on its own which uses ephemeral MCS to generate payload for each NodePool and stores it in memory.
The process is as follows:
- For a new target version a NodePool generates a token Secret. A token Secret is by contractual convention:
```
// type: Secret
//   metadata:
//   annotations:
//     hypershift.io/ignition-config: "true"
//   data:
//     token: <authz token>
//     release: <release image string>
```
- The Ignition server runs a native Kubernetes …
=> ign server

control-plane-operator/controllers/hostedcontrolplane/assets/cluster-bootstrap/cluster-infrastructure-02-config.yaml
our automated testing uses travis build numbers and without the quotes this fails. An example travis build number is `52872630`
=> ensure infrastructureName quoted

api/v1alpha1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
this will be useful for debugging the current state of pki reconciliation logic in addition to allowing providers to bring their own certs in special situations where the default behavior of cert generation in hypershift is not sufficient
=> add annotation that will disable pki reconciliation

control-plane-operator/controllers/hostedcontrolplane/assets/user-manifests-bootstrapper/user-manifests-bootstrapper-pod.yaml
by default it runs as anyuid without an explicit nonroot security context
```
Tylers-MacBook-Pro:hypershift tylerlisowski$ kubectl get pods -n master-tyler12 manifests-bootstrapper -o yaml
apiVersion: v1
kind: Pod
metadata:
annotations:
cni.projectcalico.org/podIP: ""
cni.projectcalico.org/podIPs: ""
k8s.v1.cni.cncf.io/network-status: |-
[{
"name": "",
"ips": [
"172.30.64.135"
],
"default": true,
"dns": {}
}]
k8s.v1.cni.cncf.io/networks-status: |-
[{
"name": "",
"ips": [
"172.30.64.135"
],
"default": true,
"dns": {}
}]
openshift.io/scc: anyuid
creationTimestamp: "2021-07-01T15:07:20Z"
managedFields:
- apiVersion: v1
fieldsType: FieldsV1
fieldsV1:
f:spec:
f:containers:
k:{"name":"bootstrapper"}:
.: {}
f:args: {}
f:command: {}
f:image: {}
f:imagePullPolicy: {}
f:name: {}
f:volumeMounts: …
```
=> fix manifest bootstrapper to be nonroot 

control-plane-operator/controllers/hostedcontrolplane/assets/olm/catalog-certified.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/catalog-community.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/catalog-redhat-marketplace.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/catalog-redhat-operators.deployment.yaml
In my cluster all of these are failing due to ImagePullBackoff
```
redhat-marketplace-catalog-ccff47f6d-6nq82        0/1     ImagePullBackOff    0          7h42m
redhat-operators-catalog-6458cc5698-7f95v         0/1     ImagePullBackOff    0          7h42m
community-operators-catalog-bcdf6945-xcd2q        0/1     ImagePullBackOff    0          7h42m
certified-operators-catalog-566d4b7f97-xmvqh      0/1     ImagePullBackOff    0          7h42m
```
All do to failing to pull `registry.redhat.io/invalid:tag`
It's causing testing to fail. Is there anyway we could disable for now and enable when they are ready?
=> update images to have proper tags initally.

test/e2e/e2e_test.go
Add an e2e flag `e2e.upgrade-tests-enabled` which allows configuring
whether upgrade tests are executed. This facilitates a transition to
a CI config where upgrade tests are actually executed.
=> e2e: make upgrade test enablement configurable

test/e2e/scenarios/control_plane_upgrade.go, test/e2e/util/util.go
Improve the upgrade test by ensuring that nodes and operators remain
available before and after an upgrade.
=> e2e: Improve upgrade test assertions

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, test/e2e/scenarios/control_plane_upgrade.go, test/e2e/scenarios/create_cluster.go, test/e2e/util/util.go
Before this commit, the version of the hostedcluster's release image was
persisted exactly once for the life of the hostedcluster, causing the version to
be misreported following a rollout to a new release image.
The root cause of the problem is a bug in the control plane operator which
causes the hostedcontrolplane controller to only ever update the version on
status if it was never set before.
This commit fixes the problem by ensuring the version on hostedcontrolplane
status is updated atomically along with the corresponding release image driving
the rollout.
This commit also introduces expanded e2e test coverage for upgrades to perform
deeper inspections of the cluster operator and hosted cluster versions to assert
the versions eventually converge following an upgrade.
Note: The …
=> Fix version reporting in control plane upgrades and add e2e tests

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/pki/ingress.go
What this does: Adds a new PKI serving cert for the openshift oauth
server. By default, it duplicates the content of the ingress cert.
Why is it needed: For ROKS in which their own certs are generated, the
oauth serving cert should not be synced into the guest cluster like we
do with the ingress cert. This allows them to generate separate certs
for each. The reason we use the same cert by default as the ingress cert
is that the console validates its connection to the oauth server using
the default ingress cert. There is no setting on the console to use a
different cert.
=> Create a separate oauth server serving cert

api/v1alpha1/nodepool_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go, ignition-server/controllers/tokensecret_controller.go
This is to satisfy the following FR:
FR: Machine Config should be configurable in a NodePool resource day 1.
FR: Machine Config should support Re-create rolling upgrades day 2.
Machine config is exposed through a list of ConfigMaps in NodePools with the following contractual convention:
```
type: ConfigMap
data:
config: |-
```
Each ConfigMap is meant to contain a MachineConfig CR though not validation for this is included in this PR.
Any machine config change is rolled out according to the NodePool upgrade type and strategy in hand with a release image change at any point in time.
Changes to this ConfigMaps result in a new Token generation, see openshift#303.
A token Secret has now an additional key: `config`.
=> Expose MachineConfig in NodePools

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ocm/serviceca.go
Fixes a bug introduced with the refactoring of the openshift controller manager where the service CA for the openshift controller manager is not getting reconciled
=> Fix reconciliation of openshift controller manager service ca manifest

control-plane-operator/controllers/hostedcontrolplane/assets/apiserver-haproxy/kube-apiserver-proxy.yaml
The port addition prevents the corner case where if a user tries to schedule a HostPort pod/daemonset and it adding conflicting ip table rules that will intercept all traffic from the apiserver pod, bringing down the node.
=> add resource requests and enhance livliness probe to issue https request

control-plane-operator/controllers/hostedcontrolplane/assets/registry/cluster-imageregistry-config.yaml
@csrwng 
https://github.com/openshift/hypershift/pull/187 removed the emptyDir storage for image registry config so that the registry operator would configure storage appropriate for the platform.
However, for platform `None`, image-registry just deploys in a degraded state.
This PR configures emptyDir storage when for platform `None`.  After this PR, guest cluster deployment on baremetal workers works OOTB.
=> default to emptyDir image registry storage for platform None

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/main.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/main.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go, ignition-server/main.go, releaseinfo/cached_provider.go, releaseinfo/pod_provider.go, releaseinfo/releaseinfo.go, releaseinfo/static_provider.go
Currently the releaseinfo provider interface only takes an image name to
lookup release info. However, we should be using the pull secret that
was provided for that release to pull the image. This commit adds a
pull secret parameter to the provider lookup function and updates the
implementation of pod provider to use the pull secret.
=> Add pull secret to release info provider interface

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go, control-plane-operator/controllers/hostedcontrolplane/config/deployment.go, control-plane-operator/controllers/hostedcontrolplane/etcd/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, control-plane-operator/controllers/hostedcontrolplane/ocm/params.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go
Before this commit, control plane component pods were scheduled arbitrarily
according to the default scheduling behavior. However, there's a need to limit
the impact of cross-node issues and optimize the communications paths between
component by making a best-effort attempt to colocate critical control plane
pods when possible.
This commit adds preferred pod affinity rules to to critical component pods to
enable colocation out of the box.
=> Prefer to colocate control plane components by default

control-plane-operator/controllers/hostedcontrolplane/assets/hosted-cluster-config-operator/cp-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/catalog-certified.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/catalog-community.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/catalog-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/catalog-redhat-marketplace.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/catalog-redhat-operators.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/olm-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/packageserver-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This takes a sample from a standard sized cluster 
(3 RHCOS nodes running all default scheduled workload of a 4.8 cluster)
and uses the live values from it in a steady state (after running for multiple hours) for the resource requests of components.
It also closes gaps on the liveliness probes/readiness probes of all critical components.
Net changes:
Adjust resource requests based on actual usage of a standard sized OCP 4.8 cluster
Ensure all critical components have livliness/readiness probes
=> proper probes and resource requests for all components 

api/v1alpha1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
This is necessary for compliance reasons on the IBM Cloud side: no images can be pulled from registries outside of IBM Cloud's official regional registries
=> ensure cluster autoscaler and cluster-api manager images can be configured

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go, control-plane-operator/controllers/hostedcontrolplane/config/deployment.go, control-plane-operator/controllers/hostedcontrolplane/config/deployment_test.go, control-plane-operator/controllers/hostedcontrolplane/etcd/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, control-plane-operator/controllers/hostedcontrolplane/ocm/params.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go
Adds tolerations and soft affinity rules to control plane workloads to
enable isolation of nodes dedicated to running control planes in general
or workloads for a specific cluster.
=> Enable isolation of Hypershift Control Plane workloads

cmd/cluster/create.go, test/e2e/e2e_test.go
Hypershift control plane currently does not support the 4.9 release.
Until we can support more than one minor release with core Hypershift,
we will fix the release we use to the latest 4.8 release.
=> Hardcode cli/e2e to the latest 4.8 release

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go, control-plane-operator/controllers/hostedcontrolplane/cvo/params.go, control-plane-operator/controllers/hostedcontrolplane/etcd/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, control-plane-operator/controllers/hostedcontrolplane/ocm/params.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go
- Multi-zone spread anti-affinity rules are only applied to deployments
that are running in HA mode. If only a single pod is running for the
deployment, having an anti-affinity rule means that when the
deployment is rolled out, the second pod cannot be scheduled with the
rest of the control plane. This results in scattered pods after a
restart.
- Configures konnectivity agent with colocation and control plane
isolation affinity rules and tolerations.
- Configures colocation for openshift apiserver
- Configures control plane isolation for CVO
=> Control plane pod scheduling fixes

control-plane-operator/controllers/hostedcontrolplane/manifests/imagecontentsource.go, control-plane-operator/controllers/hostedcontrolplane/render/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go
This drops the pod bash hack in favour of putting the logic to fetch the core ignition config in the NodePool controller.
This makes the process and validation consistent fo any config, custom and core.
=> Move core ign config into NodeNool controller

control-plane-operator/controllers/hostedcontrolplane/manifests/imagecontentsource.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
conforms to @enxebre new format for configs
Fixes bug where machine configs were looked up across all namespaces (needs to be scoped to control plane resource)
Updates tests to account for regressions in that case going forward
=> update config key to properly create core config

api/fixtures/example.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/manifests/infra.go
Add a Route ServicePublishingStrategy for Konnectivity and switches to use it by default.
The APIServer is the only service remaining that requires an LB.
@derekwaynecarr @csrwng
=> add Route ServicePublishingStrategy for Konnectivity

control-plane-operator/controllers/hostedcontrolplane/pki/mcs.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/ignitionserver/manifests.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go
To enable tls for downloading ignition this creates a headless service for the mcs that the ign server can reach through https. The additional domains for the certs are also removed as they are not needed.Drop toleration from mcs pod
Complements of Sanjeev (picked up after he want on parental leave):
Ports this pr: https://github.com/openshift/hypershift/pull/457
With the additional comments
=> machine config payload downloads over HTTPS/TLS

ignition-server/controllers/machineconfigserver_ignitionprovider.go
Note: It does not include the "individual cluster" level taint for now. Mainly when that taint is added it's really meant for housing hot kube-apiservers/etcds. This taint is useful however as most of the nodes in the management cluster will have this taint and without the toleration: there will be a limited number of workers that can actually hold the mcs pods.
=> add cluster toleration to mcs pod to allow it to schedule on nodes that hold control plane components.

api/fixtures/example.go, api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/cluster/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/iam.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/pki/sa.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
I was wandering around the HC spec today and I'm not sure that we need `signingKey` anymore.
Originally we needed to do this because we needed the CA that signed that key to be known at OIDC provider creation time.  However, since then, we switched to a `reencrypt` Route for the OIDC provider so we only need the thumbprint of the ingress CA, which we discover automatically at IAM create time.
We do not support NodePort publishing type on the OIDC service anymore so... I don't think we need this.
@csrwng @derekwaynecarr
=> remove signingKey field from HostedCluster

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Signed-off-by: Hanqiu Zhang <hanzhang@redhat.com>
Tests:
=> set default infrastructuretopology to ha

control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go
This should be done because APIServices do process some pretty important apis. Currently if anything goes wrong with the one agent there's no failover or attempt to use a different connection path. With multiple agents running there will be multiple redundant communication paths for traffic to flow for kube-apiserver -> openshift-apiserver or other control plane apiservices
=> ensure control plane konnectivity agent deployment ha for traffic failover

control-plane-operator/controllers/hostedcontrolplane/assets/ignition-configs/20-apiserver-haproxy.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/ignition-configs/30-fips.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/ignition-configs/99-worker-ssh.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go
The script to run mco in bootstrap mode uses 'exec' to call the mco
binary. The exec causes the mco process to take over the main container
process and when it exits, the container dies without executing the rest
of the script which swaps master/worker configs.
This PR fixes that problem and properly labels core machine configs with
the worker pool instead of the master pool.
=> Fix mco/mcs script bug that renders master ignition

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
To pick https://github.com/kubernetes-sigs/cluster-api/pull/5110 in capi and use capa 0.7.0 release image.
Will drop this when plumbing these images through our pipeline.
Fixes https://github.com/openshift/hypershift/issues/471
=> Update capi/capa images

api/fixtures/example.go, cmd/cluster/create.go, test/e2e/e2e_test.go, test/e2e/scenarios/autorepair.go
The test creates a cluster with autorepair turned on for the nodepool,
waits for it to be running, then terminates one of the machines
corresponding to a node. It waits for the machine to be replaced by
the machine healthchecker.
=> Add autorepair e2e test

Makefile, cmd/cluster/create.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go
@ironcladlou @csrwng 
adds `--control-plane-operator-image` flag to `create cluster` and removes the `--operator-image` flag from the hypershift operator
=> Allow CPO image override from create cluster

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/oauth.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go, control-plane-operator/controllers/hostedcontrolplane/pki/openshift.go
@csrwng 
Fixes the issue with non-cert-based authentication failing on `main` in 4.9.
Cause of the breakage is this change in OCP https://github.com/openshift/enhancements/blob/ce4d303db807622687159eb9d3248285a003fabb/enhancements/authentication/configuring-webhook-token-authenticators.md
=> Wire up the authentication-token-webhook-config for the KAS

api/fixtures/example.go, cmd/cluster/create.go
Simplifies scripting for creating SingleReplica or HighlyAvailable permutations.
=> Add flags to hypershift create cluster for availability policy

hypershift-operator/controllers/nodepool/manifests.go
Fixing the following error when nodePool.Spec.Platform.AWS.RootVolume == nil:
```
2021-09-21T19:37:40.118Z	ERROR	controller-runtime.manager.controller.nodepool	Reconciler error	{"reconciler group": "hypershift.openshift.io", "reconciler kind": "NodePool", "name": "han-hosted-4", "namespace": "clusters", "error": "failed to reconcile AWSMachineTemplate: error creating new AWSMachineTemplate: AWSMachineTemplate.infrastructure.cluster.x-k8s.io \"han-hosted-4-7fc38b31\" is invalid: spec.template.spec.rootVolume.size: Invalid value: 0: spec.template.spec.rootVolume.size in body should be greater than or equal to 8"}
```
Updates:
- always set default volume size
=> set default volume size when nodepool root volume is empty

test/e2e/e2e_test.go, test/e2e/scenarios/autorepair.go, test/e2e/scenarios/autoscaling.go, test/e2e/scenarios/control_plane_upgrade.go, test/e2e/scenarios/create_cluster.go
The flag is needed for 4.8 e2e tests to specify an image under test for
e2e tests in that branch.
=> Add control plane operator image flag to e2e

control-plane-operator/controllers/hostedcontrolplane/assets/ignition-configs/99-worker-ssh.yaml, control-plane-operator/controllers/hostedcontrolplane/render/manifests.go, control-plane-operator/controllers/hostedcontrolplane/render/manifests_test.go, control-plane-operator/controllers/hostedcontrolplane/render/testdata/zz_fixture_TestIgnitionConfigRendering_Multiple_ssh_keysignition-config-20-apiserver-haproxy.yaml, control-plane-operator/controllers/hostedcontrolplane/render/testdata/zz_fixture_TestIgnitionConfigRendering_Multiple_ssh_keysignition-config-30-fips.yaml, control-plane-operator/controllers/hostedcontrolplane/render/testdata/zz_fixture_TestIgnitionConfigRendering_Multiple_ssh_keysignition-config-99-worker-ssh.yaml, control-plane-operator/controllers/hostedcontrolplane/render/testdata/zz_fixture_TestIgnitionConfigRendering_No_ssh_keyignition-config-20-apiserver-haproxy.yaml, control-plane-operator/controllers/hostedcontrolplane/render/testdata/zz_fixture_TestIgnitionConfigRendering_No_ssh_keyignition-config-30-fips.yaml, control-plane-operator/controllers/hostedcontrolplane/render/testdata/zz_fixture_TestIgnitionConfigRendering_No_ssh_keyignition-config-99-worker-ssh.yaml, control-plane-operator/controllers/hostedcontrolplane/render/testdata/zz_fixture_TestIgnitionConfigRendering_Single_ssh_keyignition-config-20-apiserver-haproxy.yaml, control-plane-operator/controllers/hostedcontrolplane/render/testdata/zz_fixture_TestIgnitionConfigRendering_Single_ssh_keyignition-config-30-fips.yaml, control-plane-operator/controllers/hostedcontrolplane/render/testdata/zz_fixture_TestIgnitionConfigRendering_Single_ssh_keyignition-config-99-worker-ssh.yaml
Fixes the indent when multiple ssh keys are passed. Sample generated
configmap:
```
$ k get configmap ignition-config-99-worker-ssh -ojson|jq .data.config -r
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
name: 99-worker-ssh
labels:
machineconfiguration.openshift.io/role: worker
spec:
config:
ignition:
version: 2.2.0
passwd:
users:
- name: core
sshAuthorizedKeys:
- |-
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHBgwMTqA8AFS3UhHUXkYZ7pkWnGdFqB18uz/5Ai0mT0qgN1aY4kiGruI2uDgiTu1s3ypBrPr8Zg8Vqurrvr4p+BM0lfWQyslG+Q/UecYy0g6qAs9NriT2iWLlCUb9oFJ8Um30Lmj5I00DjnxjEDAY+nTijJvOK0fd+0HYwKmAWYLEDrGNXxW1EVoKmYoO0+Xp3p+K2xJ/7KIiKMyLVcYs5qbNHkTgywjsIW7DLhEkLIRXeubjwV1YHgsxg+8v4jCHYCrabRtG/gMLCQ7+CFST6IxwTKQB1u7U+2zjRpafOLJf/DHCGiQavqVDEZ36xYYvs67hlf3Fs3fwK4VJ0cuh Alvaro Aleman …
```
=> Fix ignition config template when multiple ssh keys are passed

api/v1alpha1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/portieries.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This pr allows the option to utilize portieries to verify image signatures of all in cluster images. Portieries downstream repo is here:
https://github.com/IBM/portieris
It runs a validating webhook that when new deployments/pods/etc enter the system the images in the deployment are verified that they are signed by known trusted providers. There's support for whitelisting images that are known not to be signed and other capabilities.
=> portieries support to verify image signatures of images in cluster

cmd/cluster/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/ec2.go, cmd/infra/aws/iam.go, test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go
This change adds an additionalTag setting to the create cluster and
create AWS IAM commands and plugs it into the e2e tests. This allows us
to identify resources created by test clusters and subsequently clean
them up automatically.
Ref https://issues.redhat.com/browse/HOSTEDCP-228
/cc @csrwng
=> Create cluster and IAM: Add AdditionalTags setting

cmd/cluster/create.go
=> Avoid OCP release image lookup on non-cluster create commands

api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hypershift-operator/controllers/nodepool/nodepool_controller.go
Before this commit if a NodePool was deleted before having the nodePoolAnnotationCurrentConfigVersion annotation then the token and userdata Secrets would be leaked as the value of this annotation was used as part of a naming convention to create and find the secrets.
This PR let the NodePool controller fetch the secrets that are annotated with the nodePoolAnnotation instead which eliminates any possible race.
=> Fix nodepool deletion

api/v1alpha1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/portieries.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
portieries support to verify image signatures of images in cluster (important for ibm compliance posture)
=> [release-4.8] Portieris enablement

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/controllers/tokensecret_controller_test.go, ignition-server/main.go
This PR enables the token Secret controller to automatically delete token Secrets generated by the NodePool controller when the ttl is met by a secret.
The token Secret controller controller uses now a finalizer to ensure a token is removed from the payload cache when the token Secret is removed.
When that happens the NodePool controller reconciles and create a new token Secret.
Then it reconciles the userData Secret in place with the new generated token so new machines can join the cluster successfully. Therefore the userdata Secret is mutable.
Ref https://issues.redhat.com/browse/HOSTEDCP-209
=> Add support for ign serve token rotation

go.mod, test/e2e/e2e_test.go, test/e2e/podtimingcontroller/podtimingcontroller.go, vendor/modules.txt
This change adds a simple controller that will collect all pod phase
changes and write a json document with them into artifacts. This allows
us to observe changes in there over time.
Sample data produced by this (from an e2e run that didn't finish because I am impatient):
<details>
{
"e2e-clusters-rkfc5-example-p88l6/capa-controller-manager-c57dd776f-j7clr/78dc18cf-b397-424b-8688-88e2f4fb8276": [
{
"name": "Pending",
"observerdAt": "2021-09-21T20:14:50Z"
},
{
"name": "Running",
"observerdAt": "2021-09-21T20:14:53Z"
}
],
"e2e-clusters-rkfc5-example-p88l6/catalog-operator-57bd7c5c58-4p8fm/872136f6-ae53-4c48-976a-0c1afcfa16df": [
{
"name": "Pending",
"observerdAt": "2021-09-21T20:15:21Z"
},
{
"name": "Running",
"observerdAt": "2021-09-21T20:15:25Z"
}
], …
=> E2E: Collect pod phase change timings

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/olm.go, control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go
- RELEASE_VERSION was not getting set in the packageserver deployment
env vars
- Guest cluster manifests had the wrong prefix (user-data instead of
user-manifests)
=> OLM refactor follow up

test/e2e/util/util.go
Recent measurement shows that the HostedCluster dump itself takes about 6 min. Re-enabling this while we investigate why guest cluster dump is slow.
=> Re-enable hosted cluster dump in e2e

cmd/cluster/destroy.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/errors.go, cmd/infra/aws/route53.go
I accidentelly specified an invalid credentials file to the `destroy
cluster` command which resulted in being stuck in `Destroying
infrastructure` for four minutes and then telling me there was an error
loading the file and that it will retry. Looking at the code, this
happens because:
* We use `RetryUntil` which always waits Interval time before starting
* In the DNS zone cleanup we always retry all errors with an exponential
backoff starting with one second, a 1.5 factor and 10 tries - For both
public and private zone
This change fixes that by adding a function to check for credential load
errors and not retry them anywhere. It also replaces the wait.RetryUntil
with wait.RetryImmediateUntil to prevent the initial wait which we don't
need.
=> Destroy cluster: Better deal with invalid credentials file

cmd/consolelogs/aws/getlogs.go, cmd/consolelogs/aws/logging.go, cmd/consolelogs/logs.go, main.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/util/util.go
- Adds a command to the hypershift command to get console logs from machines belonging to a cluster:
`hypershift console-logs aws --aws-creds AWSCREDSFILE --output-dir OUTPUTDIR --name NAMEOFCLUSTER --namespace NAMESPACE`
- Updates e2e to invoke the console logs command when nodes fail to join the cluster.
=> Guest cluster machine console logs

test/e2e/podtimingcontroller/podtimingcontroller.go
When building this I incorrectly assumed that phase==Running means the
pod is ready. This is not the case, a crashlooping pod for example will
be in the Running phase. What indicates readyness is the corresponding
condition, so track that instead.
=> Podtimingcontroller: Track readyness condition

api/v1alpha1/hostedcluster_types.go, api/v1alpha1/nodepool_types.go
This change marks immutable fields in our external api with +immutable.
The marker doesn't have any practical effect. Dealing with someone
updating such a field is left as a future TODO.
Ref https://issues.redhat.com/browse/HOSTEDCP-217
We can derive all the current statuses of these fields from elsewhere (mostly hosted controlplane). This allows for a followup where we use a controller to either set a condition if someone updates these or reset them.
=> API: Mark immutable fields with +immutable

test/e2e/util/util.go
It has a NPD bug, so we need to except it for now.
=> E2E Ensure no crashing pods: Add exception for capa cm

test/hack/nodeport-ip-aws/README.md, test/hack/nodeport-ip-aws/setup.sh, test/hack/nodeport-ip-aws/teardown.sh
Scripts to setup a bastion machine with a public IP that can forward
nodeports to a management cluster.
=> Testing: scripts to setup nodeport public IP

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/pki/oauth.go, control-plane-operator/controllers/hostedcontrolplane/pki/oauth_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, test/hack/nodeport-ip-aws/setup.sh, test/hack/nodeport-ip-aws/teardown.sh
Fixes the script that sets up a nodeport ip bastion and PKI generation to take into consideration external numeric IPs
=> Fixes for nodeport publishing strategy

control-plane-operator/controllers/hostedcontrolplane/common/manifests.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go, support/upsert/loopdetector.go
Ensures that the hosted cluster's pull secret is used by the default service account in a control plane namespace and 
fixes error in mco bootstrap init container. See individual commit messages.
=> Fixes for 4.10 compatibility

cmd/kubeconfig/create.go
It should be possible to call `create kubeconfig` without
a name parameter. This should result in a kubeconfig that has contexts
for all hostedclusters in the management cluster.
=> create kubeconfig: allow name not to be specified

test/e2e/util/journals.go
The dumpJournals function should avoid calling the dump script when no
machines exist for the given hosted cluster.
=> Skip running journal dump script if there are no workers found

control-plane-operator/controllers/hostedcontrolplane/etcd/params.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/etcd.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This commit introduces a pod disruption budget for etcd which behaves
as follows:
- For SingleReplica clusters, tolerate 100% disruption.
- For HighlyAvailable clusters, tolerate disruption of a minority of
etcd members.
This ensures the HA invariant is preserved during potentially disruptive
management cluster scenarios, e.g.prohibiting a node upgrade that would
induce loss of quorum (and thus control plane API disruption).
=> Implement pod disruption budget for etcd

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/pdb.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go
This commit adds a pod disruption budget to the kube api server that
ensures a minimum of 1 replica when the control plane is running in
a highly available configuration.
=> Add pod disruption budget to kube apiserver

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_apiserver.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go, control-plane-operator/controllers/hostedcontrolplane/oapi/pdb.go
This commit adds a pod disruption budget to the openshift apiserver
so that a minimum of 1 replica is maintained when the control plane
is configured to be highly available.
=> Add openshift apiserver pod disruption budget

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_oauth_apiserver.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
This commit adds a pod disruption budget to the openshift oauth apiserver
so that a minimum of 1 replica is maintained when the control plane
is configured to be highly available.
=> Add openshift oauth apiserver pod disruption budget

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This PR is in service to AWS private cluster support.
This introduces two controllers into the CPO that watch the two private-related services in the HCP (`kube-apiserver-private` in the HCP namespace and `router-$hcpNamesace` in the `openshift-ingress` namespace) and creates `AWSEndpointService` resources once they have load balancers allocated.
=> Add controllers to watch private services and create AWSEndpointService resources

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, support/upsert/upsert.go, test/e2e/util/util.go
This commit replaces calls to controller-runtime's `CreateOrUpdate`
function with `CreateOrUpdateProvider` calls which were missed by
the original refactor in https://github.com/openshift/hypershift/pull/543.
=> Replace upstream CreateOrUpdate calls with internal utility

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/oauth.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, control-plane-operator/controllers/hostedcontrolplane/oauth/pdb.go
This commit adds a pod disruption budget to the oauth server
so that a minimum of 1 replica is maintained when the control plane
is configured to be highly available.
=> Add pod disruption budget to oauth server

Makefile
This and a follow-up in o/release allows us to atomically change the
hypershift code and install command. This is needed to be able to add
mandatory flags, like the upcoming aws-oidc-in-bucket work will do.
/cc @csrwng
=> Add ci-install-hypershift Maketarget

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
The logs are currently super spammy, reduce the log level to what is the
default in self-hosted OCP.
=> Kube-apiserver: Reduce v level from five to two

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
The binary location changed in the new image, the pod fails with
CreateContainerError: stat /cluster-autoscaler: no such file or directory
=> Fix clusterautoscaler command

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, hosted-cluster-config-operator/controllers/kubeletservingca/setup.go, hosted-cluster-config-operator/controllers/kubeletservingca/syncer.go, hosted-cluster-config-operator/main.go, hosted-cluster-config-operator/operator/config.go
We currently put the root ca into the kubelet serving ca configmap which
is incorrect, as kubelet serving certs are signed by the KCM using the
cluster signer CA.
This fixes prometheus scraping of Kubelet endpoints which in turn means
we have data in the metrics api which fixes the HPA and the related
conformance test.
/cc @csrwng
=> Fix the kubelet serving ca, its cluster signer not root

control-plane-operator/controllers/hostedcontrolplane/assets/cluster-bootstrap/ingress-to-route-controller-clusterrole.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/cluster-bootstrap/ingress-to-route-controller-clusterrolebinding.yaml
The controller wasn't allowed to create rotues, hence it didn't work.
This fixes the `The HAProxy router should serve routes that were created from an ingress`
conformance test.
Ref: https://issues.redhat.com/browse/HOSTEDCP-257
/cc @csrwng
=> Add missing rbac for ingress-to-route controller

control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go
Adds CLI flags for availability prober and socks5 proxy images. This
make it easier to run the control plane operator locally because it
allows replacing one image while keeping the others stable.
=> Add explicit flags for auxiliary images

control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/pdb.go, control-plane-operator/controllers/hostedcontrolplane/manifests/etcd.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go, control-plane-operator/controllers/hostedcontrolplane/manifests/oauth.go, control-plane-operator/controllers/hostedcontrolplane/manifests/olm.go, control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_apiserver.go, control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_oauth_apiserver.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/pdb.go, control-plane-operator/controllers/hostedcontrolplane/oauth/pdb.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-certified-rollout.cronjob.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-community-rollout.cronjob.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-marketplace-rollout.cronjob.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-operators-rollout.cronjob.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go, support/upsert/upsert.go
This PR transitions to using beta versions of resources that GAed in kube 1.21+. The current plan is we will continue to use these versions until we can bring all management clusters to 1.21+ (currently at 1.20). Then, once all at 1.21+ we will switch from using the beta apis to using the GA apis. 
This allows hypershift to run in kube 1.20 clusters
We will switch to the GA version when all management clusters are at 1.21+ OR 4.8_openshift+. This is noted in the TODOs
=> move to using beta resources for pdb and cronjobs

control-plane-operator/controllers/hostedcontrolplane/assets/cluster-bootstrap/apiserver.openshift.io_apirequestcount-crd.yaml, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
We didn't create the apirequestcounts CRD, which made the corresponding
controller in the kube-apiserver error and the
`[sig-arch][Late] clients should not use APIs that are removed in upcoming releases [Suite:openshift/conformance/parallel]"`
conformance test fail.
https://issues.redhat.com/browse/HOSTEDCP-257
/cc @csrwng
=> Create apireqiestcounts CRD

control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go, ignition-server/main.go, support/releaseinfo/registry_mirror_provider.go
This provides the ability for the hypershift components that schedule images into a cluster to do "image mirroring" without relying on cri-o's capabilities. This allows hypershift to run in non-crio environments (only supported use case of this so far is internal IBM ROKS offering). The registry override contains source registry strings as keys and destination registry strings as values. Before applying an image the image is scanned for source registry strings and if so they are replaced with the destination registry.
It is controlled through a command line flag in the hypershift-operator and rolls downstream to components from there.
Example with hypershift operator with parameter
```
- apiVersion: apps/v1
kind: Deployment
metadata:
creationTimestamp: null
name: operator
namespace: …
```
=> add registry override support to support image mirroring translation in non-crio environments

cmd/cluster/aws/create.go, cmd/cluster/none/create.go
Set the generated infraID properly on AWS cluster create in the
hostedcluster resource.
Further avoid infraID collisions for the none provider by also appending a random string there.
Fixes an issue which I introduced in #630. As a consequence destroying an AWS cluster fails via the hypershift commandline.
=> Properly override AWS infraID if not specified on cluster create

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
infraID is assumed to be required by AWS and a core primitive which the code takes as a source of truth.
Seems fair to make it required for consistency and UX even though some platforms might not make that heavy use of it.
=> Mark infraID as required

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/platform/aws/controller.go, hypershift-operator/main.go
This PR does a number of things in service to validating the `HostedCluster` spec is compatible with with the `hypershift-operator` configuration.
There is a new condition `SupportedHostedCluster` that reflects the result of this validation.
There are new/renamed flags on `hypershift install`: `private-platform` new, `aws-private-creds` renamed from `aws-creds`, `aws-private-region` renamed from `aws-region`.  Hopefully this makes it more clear that the information provided is used for private cluster support.  `private-platform` can be `None` (default) or `AWS`.  If `AWS` is set, `aws-private-creds` and `aws-creds` are required.
`aws-region` flag is removed from `hypershift-operator` and `private-platform` flag is added.  AWS region is now set via an env var.  This allows the AWS SDK to …
=> Add SupportedHostedCluster condition HostedCluster

OWNERS
Add a placeholder component to OWNERS so that release processes can
work immediately while we work on getting a more appropriate BugZilla
component.
=> Add bz component to OWNERS

api/v1alpha1/doc.go, api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/api-doc-gen/config.json, docs/api-doc-gen/templates/pkg.tpl, docs/api-doc-gen/templates/type.tpl, docs/content/reference/api.md, docs/mkdocs.yml
This commit updates API documentation on the Go types and also improves
the generated API documentation to include only the public types, as well
as other minor small fixes for readability.
Note that the `+gencopy` comments added to the API types are to work around
an issue[1] in the upstream docs generation code which doesn't yet understand
the `+kubebuilder:object:root` tag. This is necessary to make the generator
understand which types are "public" (e.g. HostedCluster and NodePool).
[1] https://github.com/ahmetb/gen-crd-api-reference-docs/pull/26
=> Improve API reference docs

cmd/cluster/core/destroy.go
Removing unneeded elses in `GetCluster` as follow up to https://github.com/openshift/hypershift/pull/666#discussion_r746944554
=> cleanup GetCluster

Makefile, README.md, api/fixtures/example.go, api/v1alpha1/hostedcluster_types.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/iam.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/infra.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go
This change makes hypershift store the OIDC documents in a S3 bucket
rather than serving them from a dedicated ingress pointing to the
kube-apiserver. This is needed for two reasons:
1. Private clusters should not be publicly accessible
2. Tests (and probably more) assume that the serving cert of the
endpoint serving these documents is either publicly trusted or signed
by the guest clusters root ca
This implies that a hypershift setup that should manage AWS clusters
must be configured with a pre-existing S3 bucket and credentials to
write and delete objects in that bucket.
In detail, the following things were changed:
* Hypershift install got optional arguments for a OIDC bucket and region
* Hypershift install will always create a configmap with the data from
these arguments in the …
=> AWS: Store the OIDC documents in a S3 bucket

control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go
Previously: when debugging konnectivity I believed this was necessary with the redumentary haproxy solution we were using. Now that we have moved to the SOCKS proxy I no longer think host network is necessary for the daemonset. This is a more secure solution since the ports aren't exposed on the node and helps prevent network conflicts with other host network pods
=> remove need for hostnetwork from konnectivity agent daemonset

control-plane-operator/controllers/hostedcontrolplane/cloud/aws/providerconfig.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/util/cloudprovidercreds.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, token-minter/main.go
The KAS needs to cloud provider creds as it communicates with the cloud
provider for admitting them. Updating the KAS was forgotten when
refactoring the code to use STS. As cluster creation will fail if the
KAS has an initcontainer that requires the KAS to be running, the
token-minter was changed to be a sidecar instead of an initcontainer.
Also, the corresponding code was refactored to be shared between the KAS
and the KCM to avoid this kind of mistake in the future and de-duplicate
it.
=> AWS: Fix volumes by passing cloud provider creds to KAS

control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
this will fix:
https://github.com/openshift/hypershift/issues/681
Currently: most sample operator image imports fail because there is a race condition between konnectivity starting up and the samples operator rolling out the samples. Once the samples fail: it takes multiple days to rereconcile all of the tags across the failures and during that time oc new-app is not available for use.
By not proxying well known registries: this allows the openshift-apiserver to process well known registry imports without having to proxy through konnectivity. This removes the race condition
=> do not proxy well known registries for samples operator

Dockerfile
Needed for the 4.8 CI that runs `hypershift install` in this image and
indirects it from o/release to o/hypershift through a maketarget.
=> Add make to the promoted hypershift image

control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go
pr showing the changes with a konnectivity image that has the latest sync of master is here
https://github.com/openshift/hypershift/pull/680
Depends on this konnectivity community sync PR:
https://github.com/openshift/apiserver-network-proxy/pull/7
Details:
Once community is synced: grpc connection health checking and keepalived parameters are exposed for configuration in konnectivity. By default these are extremely high values (for example keepalive time is an hour and it takes two probes before determining a connection is dead meaning it can take up to 2 hours to determine a HTTP2 connection is dead.)This can lead to failures like we have been seeing in our environment 
This pr sets those parameters to run the checks every 30 seconds both server and client side (which should be in sync) …
=> reduce keepalive timeouts to ensure it is lower than oses tcp_keepalive timeout value

Dockerfile
We actually need the source code to get the Maketarget so we are using
the e2e image instead, which mans the hypershift image doesn't need
make.
This reverts commit f3c7bf45e40c60d7f4faf7882b6daeac8161b535.
/hold
So this doesn't merge before https://github.com/openshift/release/pull/23669
=> Revert "Add make to the promoted hypershift image"

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
Currently, the KAS has a 30 seconds TerminationGracePeriodSeconds but
its shutdown sequence takes 90 seconds, where it still takes requests
for the first 30 seconds and finishes responding to them for the next 60
seconds. This is to ensure that client requests created during a rollout
still get a response.
The current setting means that the kubelet just kills the KAS after 30
seconds, interrupting this sequence. Bump TerminationGracePeriodSeconds
to 95 seconds to allow the shutdown sequence to finish. This is visible
in the KAS log where we now see `[graceful-termination] apiserver is
exiting` in the very end after deleting a pod.
The shutdown sequence of the KAS is described in more detail here:
https://github.com/openshift/installer/blob/master/docs/dev/kube-apiserver-health-check.md
=> Allow the KAS to finish its graceful shutdown

hosted-cluster-config-operator/controllers/clusteroperator/reconcile.go
Fixes the 'ClusterOperators should define at least one namespace in their
lists of related objects' conformance test.
/cc @csrwng
=> operator-lifecycle-manager-packageserver: Add namespace to related objects

api/fixtures/example.go, api/v1alpha1/endpointservice_types.go, api/v1alpha1/hostedcluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/cluster/aws/create.go, cmd/cluster/core/destroy.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/iam.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_awsendpointservices.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift_operator.go, control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/main.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/manifests.go, hypershift-operator/controllers/platform/aws/controller.go, token-minter/main.go
Included in this PR:
* Controller that creates AWS Endpoint once the AWS Endpoint Service is created by the `hypershift-operator`
* `create aws iam` phase now creates a Role for the CPO
* `token-minter` sidecar added the CPO to create a serviceaccount token the CPO can use to create AWS Endpoints
* `token-minter` now allows the secret name and namespace to be passed and will wait up to 2m (5s check interval) for the secret to exist and read the kubeconfig from it
**API IMPACT**
New `ControlPlaneOperatorCreds` to plumb through the created Role for CPO
**DEPLOY TIME IMPACT**
The NLBs must be in `Active` state before the Endpoint Service can be created.  This takes about 2m30s.  The subsequent `CreateVpcEndpoint` creation call is synchronous and takes about 30s to return.  Total time to …
=> Add AWSEndpointService controller to CPO

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
Before this PR MachineDeployments with nil replicas i.e brand new MachineDeployments were temporary defaulted to 1 when a brand new NodePool replicas was nil. The immediate next call to setMachineDeploymentReplicas was reconciling to the right MachineDeployments replicas in this scenario i.e 0.
This PR ensures the MachineDeployment replicas remains 0 all the time in the scenario above.
=> Default MachineDeployment replicas to 0 if they are nil

hosted-cluster-config-operator/controllers/resources/manifests/rbac.go, hosted-cluster-config-operator/controllers/resources/rbac/reconcile.go, hosted-cluster-config-operator/controllers/resources/resources.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
We don't need it anymore as we publish these to S3. This fixes the
`[sig-auth][Feature:OpenShiftAuthorization] The default cluster RBAC policy should have correct RBAC rules`
conformance test.
/cc @csrwng
=> Get rid of the anonymous auth rule for the OIDC

support/releaseinfo/deserialize_test.go, support/releaseinfo/fixtures/4.10-image-references.json, support/releaseinfo/fixtures/4.10-installer-coreos-bootimages.yaml, support/releaseinfo/fixtures/fixtures.go, support/releaseinfo/releaseinfo.go, support/releaseinfo/releaseinfo_test.go
With recent PR into the installer included the [PowerVS](https://www.ibm.com/in-en/products/power-virtual-server) images into the rhcos.json file, this enhancement will allow us to use the powervs image in the IBM Cloud ppc64le support
Installer PR: https://github.com/openshift/installer/pull/5377
=> Read PowerVS images from the release stream

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ingress/ingresscontroller.go, hosted-cluster-config-operator/controllers/resources/ingress/params.go, hosted-cluster-config-operator/controllers/resources/ingress/reconcile.go, hosted-cluster-config-operator/controllers/resources/manifests/ingress.go, hosted-cluster-config-operator/controllers/resources/resources.go, hosted-cluster-config-operator/controllers/resources/resources_test.go, support/globalconfig/dns.go, support/globalconfig/infrastructure.go, support/globalconfig/ingress.go
Removes code that creates user-manifest configmaps for the default
ingress controller and adds code to the hosted cluster config
operator to reconcile the resources directly with the guest cluster.
=> Replace default ingress controller bootstrap manifests

hypershift-operator/controllers/hostedcluster/createorupdate_annotation_enforcer.go, hypershift-operator/controllers/hostedcluster/createorupdate_annotation_enforcer_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go, support/upsert/upsert.go
The hypershift operator creates a number of resources per hostedcluster
and changes to these trigger a reconciliation of the corresponding
hostedcluster. The mapping is done through an annotation.
Unfortunately, we do not set the annotation in many cases which means
that external changes do not get corrected by the Hypershift operator.
This change makes us automically insert the annotation. It went through
several rounds before I was happy with the result:
1. Wrap the client and just check and error: This works but requires to
update a massive amount of code to insert the annotation everywhere
and plug the required info through
2. Wrap the client to automatically insert the annotation: This mostly
works, but if someone ever removes the annotaiton, we will not re-add
it because …
=> Hypershift operator: Ensure created objects are annotated to trigger reconciliation

README.md
The `create cluster` command now defaults to 0 replicas. Adds a flag to
the sample `create cluster` command to specify the number of replicas to
create and fixes the text that says 2 replicas are created by default.
=> Update README to reflect default 0 replicas

cmd/bastion/aws/logging.go, cmd/cluster/aws/log.go, cmd/cluster/core/log.go, cmd/cluster/none/log.go, cmd/consolelogs/aws/logging.go, cmd/infra/aws/logging.go, cmd/util/log.go
JSON-Encoding makes sense for long-running components but not for a CLI
that is only ever invoked by a human. Also changes the time encoding to
be RFC3339 instead of unix epoch.
/cc @csrwng
=> Hypershift CLI: Dont use json-encoding for logs

hosted-cluster-config-operator/controllers/clusteroperator/setup.go, hosted-cluster-config-operator/controllers/clusterversion/setup.go, hosted-cluster-config-operator/controllers/cmca/setup.go, hosted-cluster-config-operator/controllers/kubeadminpwd/setup.go, hosted-cluster-config-operator/controllers/openshiftapiservermonitor/setup.go, hosted-cluster-config-operator/controllers/resources/resources.go, hosted-cluster-config-operator/main.go, hosted-cluster-config-operator/operator/config.go, hosted-cluster-config-operator/operator/labelenforcer.go, hosted-cluster-config-operator/operator/labelenforcer_test.go
What:
This PR refactors the configuration code of the
hosted-cluster-config-operator to make it easier to access configuration
parameters from controllers.
Why:
As we move more code to be handled by the resources controller, we will
need additional parameters passed to the hosted-cluster-config-operator.
Before this PR, this required the same field to be added in multiple
places.
=> Refactor hosted cluster config operator start code

control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go, support/upsert/upsert.go
We currently use an api reader which results in an actual api request
whenwever we need to get an object. This change makes us use the
default cache-backed client again. There are now a couple of conflict
errors in the log, but as that results in a retry it is not a
correctness issue.
Ref https://issues.redhat.com/browse/HOSTEDCP-154
=> Use a cache-backed client to reduce number of api requests

api/v1alpha1/endpointservice_types.go, api/v1alpha1/hostedcluster_types.go, cmd/infra/aws/create.go, cmd/infra/aws/iam.go, cmd/infra/aws/route53.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_awsendpointservices.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, control-plane-operator/controllers/awsprivatelink/route53.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/platform/aws/controller.go
`create infra aws` creates a `$name.hypershift.local` private DNS zone attached to the guest VPC.
CPO creates records in this zone for `api.$name.hypershift.local` and `*.apps.$name.hypershift.local` that point to the apiserver and ingress Endpoints respectively.
`destroy infra aws` removes the DNS zone
`AWSEndpointService` type changed to include new `status` fields: `DNSName` and `DNSZoneID` primarily for tracking for removal because the HCP might already be deleted by then.  Also nice from a UX/debuggability standpoint.
=> Add private DNS zone and CPO record management for AWS private clusters

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/oauth/route.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Needs https://github.com/openshift/hypershift/pull/710 and https://github.com/openshift/hypershift/pull/720 first, but this PR is the endgame; full private cluster support
/hold
=> Use VPC endpoint for controlPlaneEndpoint with private clusters

cmd/cluster/aws/create.go
This flag is already marked `MarkPersistentFlagRequired`, so removing this duplicate check.
https://github.com/openshift/hypershift/blob/931d53d86c6608831ad8f94fe35ca249716ab2c2/cmd/cluster/cluster.go#L49
=> Remove redundant MarkFlagRequired check

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/manifests/konnectivity.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/pki/konnectivity.go, hosted-cluster-config-operator/controllers/resources/konnectivity/params.go, hosted-cluster-config-operator/controllers/resources/konnectivity/reconcile.go, hosted-cluster-config-operator/controllers/resources/manifests/konnectivity.go, hosted-cluster-config-operator/controllers/resources/manifests/pullsecret.go, hosted-cluster-config-operator/controllers/resources/resources.go, hosted-cluster-config-operator/controllers/resources/resources_test.go, hosted-cluster-config-operator/main.go, hosted-cluster-config-operator/operator/config.go
This commit replaces the user manifests for the Konnectivity agent
applied by the manifest bootstrapper pod with reconciliation code in
the hosted cluster config operator. This enables continuous
reconciliation of the agent and is part of the effort to remove the
manifest bootstrapper pod.
=> Replace Konnectivity Agent user manifests

CONTRIBUTING.md, docs/content/developers/how-to/contributing.md, docs/content/developers/how-to/onboard-a-platform.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws_test.go, hypershift-operator/controllers/hostedcluster/internal/platform/ibmcloud/ibmcloud.go, hypershift-operator/controllers/hostedcluster/internal/platform/none/none.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go, hypershift-operator/controllers/manifests/clusterapi/manifests.go, hypershift-operator/controllers/manifests/controlplaneoperator/manifests.go, hypershift-operator/controllers/manifests/manifests.go
This is a first step towards a more sustainable model for the code base to extend to multiple platforms.
It creates an interface to be implemented for each platform to handle the HostedController needs.
It add docs for extend support to other platforms.
As a follow up if this model proves to be satisfactory we can extend the interface to support the NodePool controller and handle infra machines lifecycle. Furthermore, we could at some point consider this to be an adhoc platform controller which communicates with the core one through conditions there fore enabling out of tree platform implementations.
=> Create platform interface for HostedCluster controller.

cmd/cluster/core/create.go
Below code is talking to kubernetes cluster even if `--render` option is specified, it's not really required if `--render` is present, hence reducing the scope for client creation within the block where it is making the apply calls.
=> Avoid talking to kubernetes cluster if --render specified

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, support/util/cloudprovidercreds.go, token-minter/main.go
I think this should fix the observed `ExpiredTokenException` issue.  The default expiration set by the KAS when `ExpirationSeconds` isn't explicitly set on the request is 3600 seconds, which aligns with the expiration of the underlying STS token.
This is what is done elsewhere in OCP
https://github.com/openshift/cluster-ingress-operator/blob/3f35d0c05831e465d314ef75bd102967a5369545/manifests/02-deployment.yaml#L109-L116
Results
```
projected:
defaultMode: 420
sources:
- serviceAccountToken:
audience: openshift
expirationSeconds: 3600
path: token
```
With the added code to renew the token, this should work.
=> token-minter renews token before expiration

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/common/manifests.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/manifests.go
Before this PR, end users of Hypershift had no way to find the kubeadmin
password for their HostedCluster apart from looking inside the control
plane namespace.
This PR adds code to copy the kubeadmin password secret from the control
plane namespace to the HostedCluster's namespace and adds a field in the
status of the HostedCluster that references the password secret.
=> Expose kubeadmin password in HostedCluster status

cmd/install/assets/assets.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/ibmcloud/ibmcloud.go, support/globalconfig/infrastructure.go
the repo does not yet have a v1beta1 version. We need to keep it v1alpha4 for now
Fixes:
- Properly sets the infrastructureRef for IBM Cloud clusters. Previously it was inaccurately getting set to v1beta1
- Properly reconciles the IBMCloud infrastructure references so all downstream components roll out in the cluster appropriately
=> set ibmcloud capi components to proper v1alpha4 version and properly reconcile infrastructure resource for ibmcloud

hypershift-operator/controllers/hostedcluster/internal/platform/ibmcloud/ibmcloud.go
This is return a valid ibmcluster object instead of nil
=> Return a valid ibmcluster object

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws_test.go, hypershift-operator/controllers/hostedcluster/internal/platform/ibmcloud/ibmcloud.go, hypershift-operator/controllers/hostedcluster/internal/platform/none/none.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go
Update ReconcileCAPIInfraCR to receive createOrUpdate as a parameter.
Reorganise interface funcs signature parameters consistently.
=> Use createOrUpdate in ReconcileCAPIInfraCR

docs/content/developers/how-to/contributing.md
The b5aa26e0c8a0f69431fd727a21a749ebeaa3193d commit introduced a symlink
into the docs content, which breaks the local preview `make serve-containerized`
target (which throws file not found errors trying to deal with the link).
This commit replaces the symlink with an actual file to fix the regression.
We should consider having CONTRIBUTING.md just link to the docs page instead
of symlinking it.
=> Replace contributors symlink with actual file

api/fixtures/example.go, cmd/cluster/aws/create.go, cmd/cluster/core/create.go
Help UX for private clusters when using `create cluster aws`.  Current procedure is to use `--render` and edit the yaml manually.
=> Add endpoint-access flag for create cluster aws

control-plane-operator/main.go, docs/content/developers/how-to/develop-in-cluster.md, hack/publish-ocp.sh, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/util/deployment.go, hypershift-operator/main.go, ignition-server/main.go
This commit adds some development workflow improvements:
- Simplify development workflows by introducing better defaults to the
hypershift-operator, control-plane-operator, and ignition-server which eliminate
the need to document or use many flags which are relevant only in rare debugging
contexts. The documentation has been updated to reflect these changes.
- Tweak the `public-ocp.sh` script to always use the public registry endpoint,
fixing a flake where sometimes the script would erroneously produce the internal
registry name as output.
- Update the in-cluster developer workflow docs to describe required OIDC
hypershift-operator flags which weren't documented before.
- Mirror the `hypershift.openshift.io/debug-deployments` annotation to
HostedControlPlane resources for future use (e.g. …
=> Simplify and clarify development workflows with better defaulting

control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go, control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This PR adds liveness and readiness checks to hypershift components: control-plane-operator, cluster-api, kube-scheduler.
For control-plane-operator healthz & readyz probes were added.
For cluster-api and kube-scheduler their existing probes are used.
Corresponding issue: https://github.com/openshift/hypershift/issues/408
=> Liveness & readiness probes for control-plane-operator, cluster-api, kube-scheduler

cmd/install/assets/hypershift_operator.go
Currently, the `aws-private-creds` passed to hypershift-operator must be IAM user creds because there is no token projected into the hypershift-operator pod.
This PR adds that token.
This isn't the best from UX because the `aws-private-creds` will need to specify the `web_identity_token_file` to be the bespoke path of the projected token at `/var/run/secrets/openshift/serviceaccount/token`.  But it does allow for Role-based creds for AWS private cluster functions i.e. creating the Endpoint Services.
=> Add projected token to hypershift-operator for Role based access

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
This error is currently always emitted, even though it is not an actual
error but just means that we are blocked by waiting for those configs
which are expected to take some time. Use a retryAfter to avoid logging
error messages.
/cc @enxebre
=> Avoid "core ingition config has not been created yet" error during startup

control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
Without this, the import fails with an error like
```
Internal error occurred: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:e44074f21e0cca6464e50cb6ff934747e0bd11162ea01d522433a1a1ae116103:
Get "https://quayio-production-s3.s3.amazonaws.com/sha256/b0/b0e2957fede15fffb1b12987d8f6068953739aac8775983c45f6ecfaecb91473?Signature=GF5mIHG057nJUTbxy%2FfHhE4TF%2FM%3D&Expires=1638555529&AWSAccessKeyId=AKIAI5LUAQGPZRPNKSJA":
EOF'
```
as it tries to route that over the socks5 proxy which does DNS resolving
but can only do that for kubernetes services. And even if was able to
resolve, it wouldn't be able to route.
TBH I am not sure why this now started to happen, maybe quay started to
return direct download links to S3 rather than proxying requests?
We allowlist all of aws in the no_proxy env …
=> Fix openshift/tools:latest imagestream import

availability-prober/main.go, control-plane-operator/main.go, hosted-cluster-config-operator/main.go, hypershift-operator/main.go, ignition-server/main.go, support/upsert/loopdetector.go, test/e2e/e2e_test.go
As the latter is extremely hard to parse by humans.
=> Log: Use RFC3339 timestamps rather than unix epoch

konnectivity-socks5-proxy/main.go
In 868bb057c4119b76ec3b4100ea88d55664c92715 I made the proxy close the
bodies it receives. This broke the proxy entirely, as closing the body
effectively discards any remaining data in there, but the data is the
response for the actual client which gets read by the proxy and then
forwarded.
This changes makes the openshift-apiserver again able to talk to the registry which in turn fixes a bunch of e2e tests.
=> Fix konnektivity-socks5-proxy

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
Currently, we flap back and forth between different nodepool configs
that differ only in the user-data secret name. This happens because that
secret has a suffix that is the hash of it's configs. Those configs in
turn are assembled from a list of configmaps, but that list wasn't
sorted. Sort the list, be happy.
=> Prevent flapping of nodepool config

docs/content/how-to/deploy-aws-private-clusters.md, docs/mkdocs.yml
This commit cleans up and revises the private cluster howto guide. The
architectural content has been removed and will be placed elsewhere
(perhaps in the reference section).
=> docs: Update private cluster howto

cmd/cluster/aws/create.go, cmd/nodepool/create.go
While the 16 gig might be enough for a node to get into ready status, it
will very quickly get filled. Change this to use the same default as
self-hosted openshift. This will also improve the conformance test runs,
as we regularly have flakes there because all nodes are tainted because
of disk-pressure.
=> Default root-volume-size to 120 instead of 16 gig

Dockerfile.control-plane
Add a discrete Dockerfile for a control plane image containing only
those binaries which should be incorporated into the OCP payload.
=> Add a control plane operator Dockerfile

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go, support/globalconfig/infrastructure.go
Since #719 None platform is broken, this aims to restore the functionality added in #630
WIP pending further testing
=> Fix issues with None platform

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/oauth/route.go
Web console does not work for `Private` or `PublicAndPrivate` clusters because users, not on the guest VPC, are redirected to the oauth route which is currently private.
=> Make oauth route always public

control-plane-operator/main.go
The namespace is `openshift-ingress-operator` not `openshift-ingress-controller`.
Use a reference to avoid this kind of mistake and clarify the
dependency.
=> CPO: Fix cache selector for ingresscontroller namespace

test/e2e/util/util.go
In recent e2e runs, the autoscaler is frequently restarting due to it
losing a leader and timing out when communicating with the kube
apiserver. This change temporarily adds an exception to the crashing
pods test until we can find a fix for it.
=> Add autoscaler exception to pod crash test

api/fixtures/example.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, test/e2e/e2e_test.go
This is needed for nested Hypershift, as the service cidr of the guest
cluster must not overlap with the one of the management cluster,
otherwise the KAS can not reach the services that run in the management
cluster.
Needed for https://github.com/openshift/release/pull/24556
=> Create cluster: Add flags for service and pod CIDR

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This PR adds liveness & readiness checks to cluster-autoscaler.
Corresponding issue: https://github.com/openshift/hypershift/issues/408
Current cluster-autoscaler image does not have special health probe listeners, but it does have /metrics endpoint so this PR uses that endpoint for health checks.
=> Liveness & readyness probes for cluster-autoscaler

cmd/infra/aws/destroy.go, cmd/infra/aws/route53.go
We currently require the name of the cluster, otherwise we don't clean
up the private route 53 zones. This is because they do not directly have
tags associated and can not be filtered by tags, so we filter by name
instead. This change makes us filter by VPC instead, which works withour
requiring the name.
Ref https://issues.redhat.com/browse/HOSTEDCP-287
=> Infra destroy: Do not require cluster name for route 53 cleanup.

cmd/cluster/aws/create.go, cmd/cluster/core/create.go, cmd/cluster/none/create.go
I just spend an hour debugging why I am getting some weird patch error
when trying to create a cluster until I realized it is because a cluster
of that name already exists. Error out when this happens, as create
cluster is not idempotent at all.
=> CMD: Error out when hostedcluster already exists

cmd/cluster/cluster.go, cmd/cluster/core/create.go
The main usecase I have in mind for this is CI cluster creation, where
we currently use a bunch of `oc` invocations to figure this out, but I
imagine its generally useful.
=> Create cluster: Add --wait option

control-plane-operator/controllers/hostedcontrolplane/pki/cert.go, control-plane-operator/controllers/hostedcontrolplane/pki/cert_test.go, control-plane-operator/controllers/hostedcontrolplane/pki/sa.go, control-plane-operator/controllers/hostedcontrolplane/pki/util.go, go.mod, support/certs/tls.go, support/certs/tls_test.go, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go, vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go, vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go, vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go, vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go, vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go, vendor/golang.org/x/xerrors/LICENSE, vendor/golang.org/x/xerrors/PATENTS, vendor/golang.org/x/xerrors/README, vendor/golang.org/x/xerrors/adaptor.go, vendor/golang.org/x/xerrors/codereview.cfg, vendor/golang.org/x/xerrors/doc.go, vendor/golang.org/x/xerrors/errors.go, vendor/golang.org/x/xerrors/fmt.go, vendor/golang.org/x/xerrors/format.go, vendor/golang.org/x/xerrors/frame.go, vendor/golang.org/x/xerrors/internal/internal.go, vendor/golang.org/x/xerrors/wrap.go, vendor/modules.txt
Currently, we only check if a secret has the right entries for a
certificate and key but we never check on the content of those entries.
This means that for example if a certificate expires or its config
changes in any other way, we will not re-create it.
This change:
* Adds some code to verify a certificate and key against a config
* Uses this when reconciling certificates
* Cleans up the support/certs and
hontrol-plane-operator/controllers/hostedcontrolplane/pki packages to
not export methods that are not used in other packages
Ref https://issues.redhat.com/browse/HOSTEDCP-99
=> PKI: Properly reconcile certificates and keys

api/v1alpha1/hostedcluster_types.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/iam.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, docs/content/reference/api.md
This is a new component that was added in the 4.10 cycle.
Ref: https://github.com/openshift/cloud-network-config-controller/pull/6
=> AWS: Create role for cloud-network-config-controller

control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go
This will ensure issued worker certs for kubelet have a duration that is compliant with fs cloud controls. The maximum allowed time is 2 years which is 17520 hours.
=> update cert duration to match maximum time allowed by fs cloud controls (2 years)

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Ref https://issues.redhat.com/browse/HOSTEDCP-175
/cc @csrwng
=> Cluster deletion: Wait until NS is gone so new cluster of same name doesn't error initially

control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-collect-profiles.cronjob.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/olm-collect-profiles.go
add distributed cronjob schedule to olm-collect-metrics cronjob to prevent management cluster scheduling overload at specific intervals.
Uses same scheduling algorithm used for other cronjobs
=> add distributed cronjob schedule to olm-collect-metrics cronjob

cmd/version/version.go
As of https://github.com/openshift/release/pull/24928, hypershift images
are promoted into the `ocp` registry namespace (which is private) and mirrored
to quay (which is public). This commit updates old references to point at the
new location.
=> Update hypershift image references to new location

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
This support appears to be added in the following commits for 4.10:
https://github.com/openshift/machine-config-operator/commit/eb0afb8374b097d4971021b1b00c0f471a8a5892
https://github.com/openshift/machine-config-operator/commit/a282006d2d3b245c2f5cdf444a4dea45d1b27585#diff-ee4889f36bd8b3bb13f51dd15721cbc3f0eae1cf4d6bb8635dec6de843e78c4d
It would as of now though fail in release-4.9 and release-4.8 (meaning the user would have to be aware that it is only allowed starting in release 4.10. Or the commits could be backported.
=> allow kubelet configs and container runtime configs to be specified now that mco bootstrapping supports it

control-plane-operator/hostedclusterconfigoperator/cmd.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/clusteroperators.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/oapi/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/operator/config.go, control-plane-operator/main.go, support/globalconfig/imagecontentsource.go, support/upsert/upsert.go
Before this commit, the CPO was not passing the enable-ci-debug-output
flag to the hosted cluster config operator, so we were not detecting
update loops in CI. There were a few items causing update loops.
This PR enables loop dection for the hosted cluster config operator and
fixes resources that were causing update loops.
=> Fix update loops in hosted cluster config operator

Dockerfile.control-plane, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go
This commit adds support for deploying the control-plane-operator from an OCP
payload. To enable this, the hypershift-operator has been updated to inspect the
release specified by a HostedCluster and, if a `hypershift` image is present in
the release metadata, that image will be used for the control-plane-operator.
Otherwise all the prior lookup behavior remains the same, so the code should be
compatible with all existing use cases and should work transparently when an OCP
payload containing hypershift is specified.
This commit also fixes the token minter, availability prober, and the socks
proxy deployments to ensure the are deployed by default from the hypershift
image instead of the control-plane-operator's image, as those components are
versioned independently of the control plane. A …
=> Add support for control plane operator deployed from an OCP payload

ignition-server/controllers/cache.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/controllers/tokensecret_controller_test.go, ignition-server/main.go
Before this commit, the token controller used finalizers on ignition payload
secrets to ensure the token controller's internal cache could be purged upon
deleting the underlying secret for the token/payload. This causes the ignition
server process to race with namespace termination to clean up the finalizer.
When the ignition server process loses the race, the ignition secrets can remain
orphaned in the control plane namespace with finalizers that will never be
removed, resulting in HostedClusters being stuck deleting.
This commit eliminates the race by removing the use of finalizers entirely on
the ignition payload secrets. Instead of relying on a finalizer to do internal
cleanup, the token cache now internally tracks the secret name from which a
given token is derived. With that …
=> Fix control plane teardown race with token secret finalization

cmd/infra/aws/route53.go
For public zones, the wildcard entry name was wrong, it has the cluster
name as a component and that can not be derived from the zone name.
For private zones, it was needlessly complicated, the wildcard entry is
simply '*.apps.' + zoneNameWithTrailingDotStripped.
zoneNameWithTrailingDotStripped is the same as clusterName + "." +
baseDomain, but by directly using the zone name it will work even if the
basedomain argument is incorrect.
=> Fix route53 wildcard entry cleanup

Dockerfile.control-plane
This commit labels the control plane image for inclusion into the official
OCP payload image. As of this commit, the control plane image will be shipped
with OCP 4.10+ as an OpenShift component.
=> Add control plane image to the OCP payload

api/v1alpha1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go
This commit adds support for overriding CAPI provider images per
HostedCluster via annotations for consistency with the other components
which already support overrides. Adds overrides for kubevirt, agent, and AWS.
=> Add missing CAPI provider image overrides

docs/content/contribute/develop-in-cluster.md
Before this commit, the in-cluster development docs used an `oc registry login`
command which could sometimes log the user in to the cluster's internal instead
of external registry if the prior steps to enable the external registry hadn't
yet completed.
This commit updates the login command to make sure the registry login always
targets the external registry route.
=> docs: Minor update to in-cluster development registry login steps

cmd/cluster/aws/create.go, cmd/nodepool/create.go, hypershift-operator/controllers/nodepool/manifests.go, test/e2e/e2e_test.go
no longer makes sense to use gp2. See https://github.com/openshift/installer/pull/5239
for motivations.
=> replace default usage of gp2 with gp3

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go, control-plane-operator/controllers/hostedcontrolplane/configoperator/params.go, control-plane-operator/controllers/hostedcontrolplane/cvo/params.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ignition/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/params_test.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, control-plane-operator/controllers/hostedcontrolplane/ocm/params.go, control-plane-operator/controllers/hostedcontrolplane/olm/params.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, support/capabilities/management_cluster_capabilities.go, support/capabilities/management_cluster_capabilities_test.go, support/config/constants.go, support/config/deployment.go
Supersedes: #777 
Issue: #566 
Addresses PR comments:
- https://github.com/openshift/hypershift/pull/777#discussion_r782495269
- https://github.com/openshift/hypershift/pull/777#discussion_r782495803
- https://github.com/openshift/hypershift/pull/777#discussion_r782495972
- https://github.com/openshift/hypershift/pull/777#discussion_r782497553
Other enhancements:
- Moved `1001` uid value to config constant
- Simplified setting `r.SetDefaultSecurityContext`
=> feat: Set default security context user for vanilla kube

Makefile
This commit updates the `make verify` step to incorporate API docs
generation verification by ensuring changes to API types or manual
edits to the generated file will cause presubmit build failures.
=> Add generated API docs to `make verify` target

api/v1alpha1/nodepool_types.go, cmd/cluster/aws/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, cmd/nodepool/create.go, docs/content/reference/api.md, test/e2e/e2e_test.go
There is no reason to ever use m4 over m5. m4's are
more expensive because it's legacy hardware. m5 is cheaper
and better.
=> replace m4.large default with m5.large

cmd/cluster/core/create.go
We changed the create command to Create the HostedCluster rather than
ServerSide applying it to make sure it errors if a HostedCluster of that
name already exists.
Unfortunately, the deserializer clears the TypeMeta field when doing
anything other than the serverside apply, so the code that looked at the
object kind after the Create to find the HostedCluster will never find
anything. Fix it by storing the HostedCluster before doing the Create
call.
=> Crate cluster: Fix --wait panicing with a NPD

hypershift-operator/controllers/nodepool/agent.go, hypershift-operator/controllers/nodepool/aws.go, hypershift-operator/controllers/nodepool/aws_test.go, hypershift-operator/controllers/nodepool/kubevirt.go, hypershift-operator/controllers/nodepool/kubevirt_test.go, hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
This unifies the code to reconcile platform machine templates.
Move AWS code into its own file.
Additionally this changes existing behaviour to update existing templates in-place rather than creating a new one and rotate.
Initially rotation was used to not preclude us from leveraging MachineDeployments rollback ability. This seems unlikey so this PR drops that behaviour which also solves the problem of having to clean up old Machine templates.
=> Refactor code to reconcile Machine templates

cmd/cluster/agent/create.go, cmd/cluster/aws/create.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/cluster/kubevirt/create.go, cmd/cluster/none/create.go
When adding the `--wait` option to the hypershift create cluster command, if something went wrong, the command will stuck forever.
This PR adds the `--timeout` option, so the user can limit the time the command is running.
=> Add the `--timeout` to the hypershift create cli

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go, control-plane-operator/controllers/hostedcontrolplane/manifests/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go
This change moves the Ingress Operator into the management cluster in
order to speed up cluster creation. I did two testruns with this, in the
first it took 698 seconds, in the second 642 seconds to create a
cluster. This is about two minutes faster than the fastest run we
currently have from CI (14.2 minutes/852 seconds).
POC because while this works, it would need some more polishing before we can merge it if that is what we want.
Pro arguments:
* Quicker startup
Con arguments:
* Slightly increased resource consumption (The operator requests 10m CPU and 56Mi memory and uses 3m CPU and 64Mi memory in my test)
* The added complexity of the code in this PR
=> Move Ingress Operator into management cluster to speed up creation

control-plane-operator/controllers/hostedcontrolplane/kas/service.go
NLBs allow the source IP to pass through to the KAS pod so we can allow access based on source CIDR block in the `NetworkPolicy`
=> Use NLB for public KAS service type LoadBalancer

api/v1alpha1/hostedcluster_types.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This commit adds a `ClusterVersionSucceeding` condition to HostedCluster which
tracks the `Failing` condition of the hosted cluster's `ClusterVersion`
resource. This condition provides additional context about the health of the
hosted cluster in the steady state and during release version rollouts. During a
rollout, information about individual operator rollout status will be surfaced
through this new condition.
=> Add a ClusterVersionSucceeding condition to HostedCluster

control-plane-operator/controllers/hostedcontrolplane/scheduler/deployment.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go
In 4.10, the scheduler uses a secure port for its healthz endpoint and
it changed the default port that it listens on.
In this change we specify the secure port and use that same port for
liveness and readiness probes.
=> Fix kube scheduler health/liveness probes

cmd/log/log.go, cmd/nodepool/aws/create.go, cmd/nodepool/core/create.go, cmd/nodepool/create.go, cmd/nodepool/kubevirt/create.go, docs/content/getting-started.md
Change the NodePool CLI to be platform aware
This change is done as part of the multy platform support,
to allow the CLI to provide platform specific UX where needed
=> Change NodePool CLI to have platform sub command

cmd/cluster/aws/dump.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/util/client.go, test/e2e/util/scheme.go, test/e2e/util/util.go
This commit fixes various e2e issues, and makes the full test suite work again
(i.e. the periodics).
* Before this commit, the periodic setup code was deploying the "previous"
release version passed to the e2e options and then waiting for the "latest"
version, causing rollouts to block forever. This is now fixed and made more
clear by having the global test setup default clusters to using the "latest"
release, and code which wants to do an upgrade must explicitly set options to
deploy the "previous" release.
* The TestAWSCreateCluster test has been deleted as everything it was doing is
covered (and more extensively) by TestUpgradeControlPlane.
* Minor fix: before this commit when e2e namespace teardown times out, artifacts
were being dumped even when no artifacts directory was specified. …
=> e2e: Fix periodic tests

cmd/install/assets/hypershift_operator.go, cmd/install/install.go
The `Deployment` generated by `hypershift install` includes OIDC bucket and
region information directly as container args. Having those fields in a configmap/secret
makes the generated `Deployment` reusable as the config information can be
supplied by external processes.
This patch modifies the generated s3 credentials secret `hypershift-operator-oidc-provider-s3-credentials`
to include the OIDC bucket name and region and sources them into the operator
deployment as ENV vars, so they can be interpolated into the container args.
This way, the deployment generated by `hypershift install` does not contain
OIDC configuration data directly but offloads that to the secret.
If `--oidc-storage-provider-s3-*` parameter are supplied to `hypershift install`,
the `Deployment` will change like this …
=> Add OIDC bucket and region to s3-credentials secret

cmd/cluster/aws/dump.go
Fixes stdout/stderr output capture from `oc adm` which was broken
due to inadvertant stream reassignment on the exec.Cmd.
=> e2e: Fix cluster dump issues

hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go
This is in line with the AWS provider.  Without this the cluster.InfrastructureRef is missing the Kind and APIVersion, and therefore CAPI has trouble reconciling.
=> Missing GroupVersion on AgentCluster

cmd/cluster/agent/create.go, cmd/cluster/aws/create.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/cluster/kubevirt/create.go, cmd/cluster/none/create.go
Before this commit, the --timeout flag to `create cluster` didn't work
due to some bug with its stateful approach which I haven't debugged.
Instead, this commit just refactors the timeout handling to simply be
stateless and propagate a timeout context from each command's Run()
method which is trivial enough to just duplicate wherever needed.
=> Fix CLI --timeout flag

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Currently machine-approver only has a metrics endpoint (no healthz) and no healthchecks on the pod. We need health probes to ensure the program is still functioning for monitoring and availability reasons.
This adds probes to the deployment to ensure it is monitored over time. Later prs if other probes come available can be made to adjust the endpoint being probed.
Details for probe are here:
https://github.com/openshift/cluster-machine-approver/blob/master/pkg/metrics/metrics.go#L13
=> add probes to machine-approver to ensure it is functioning

cmd/cluster/core/dump.go, cmd/dump/dump.go, test/e2e/util/cluster/aws/cluster.go, test/e2e/util/util.go
Moved the AWS implementation of cmd/dump to be generic and added
the resourced needed by the agent platform.
=> Generic dump command plus agent support

cmd/install/assets/hypershift_operator.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/networkpolicy/manifests.go
Seals up HO to HCP service network communication after https://github.com/openshift/hypershift/pull/849
=> Add NetworkPolicies to HCP to block inter-namespace communication

test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/util/cluster/kubevirt/cluster.go, test/e2e/util/kubevirt.go, test/e2e/util/scheme.go, test/e2e/util/util.go
This functional e2e test is very basic and is primarily meant as an entrypoint for us to begin fleshing out more advanced validation in the future. At the moment, we simply need a test case that we can wire up to Openshift CI to validate that a hosted cluster actually boots KubeVirt VMs successfully.
At the moment this test does the following.
- Posts a HostedCluster using the kubevirt provider
- Verifies the NodePool gets created as expected
- Verifies the KubeVirt Machines come online (meaning that the VMs boot, that's it)
- Verifies the KubeVirtCluster is ready
Unlike the AWS create cluster test, access to the guest cluster is not being exercised yet, and we aren't even verifying that the HostCluster reaches a completed state. This verification for the KubeVirt provider will come in …
=> kubevirt provider e2e create cluster test

cmd/version/version.go, docs/content/getting-started.md
As of https://github.com/openshift/release/pull/25398, the operator
image has changed, and the prior reference now refers to the control
plane operator shipped with OCP. This commit fixes the reference.
Also includes a minor docs update.
Fixes #803
=> Update hypershift image reference

cmd/cluster/core/dump.go
We don't install these CRDs through hypershift install, so the
corresponding apis dont exist which makes `ocm adm inspect` always
error. This doesn't fail the `dump` command but is confusing and blocks
the way for actually checking the success of the `oc` invocation.
/cc @ironcladlou
=> Dump: Don't dump agent-specific resources when there is no agent NS

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/oapi/config.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, support/globalconfig/ingress.go
Builds on Cesar's PR:
https://github.com/openshift/hypershift/pull/806
and fixes the remaining areas that need to properly account for subdomains. This is necessary to get IBMCloud deployments functional again.
=> use globalconfig when specified (fixes ibmcloud deployments)

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, support/capabilities/fake/fake.go, support/capabilities/management_cluster_capabilities.go, support/capabilities/management_cluster_capabilities_test.go, support/releaseinfo/fake/fake.go, support/releaseinfo/registry_mirror_provider.go, support/releaseinfo/releaseinfo.go
This change add a test to the hypershift operator that verifies that it
watches all object types it creates. It works by:
* Running a Reconcile() for a hostedcluter per supported platform
* Using a fakeclient that trackes what objecttypes get created
* Factoring out the set of types that are being watched
* Compaing the set of objects that are getting created with the ones
that are being watched
Additionally, some changes where needed to allow unittesting this:
* The ReleaseProvider was defined as interface but then asserted to a
concrete type because the interface lacked didn't expose
RegistryOverrides. Use a new interface that includes those so we can
use a fake implementation in tests
* The capabilites were configured through a struct that didn't export
the map of supported …
=> Hypershift operator: Add missing watches and unittest correct watches

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
This is required due to changes introduced in https://github.com/openshift/hypershift/pull/887
that added a watch for Route without checking the management cluster capabilities
That cause issues in tests that don't use OCP as management cluster (e.g. AgentPlatform)
=> Add routev1.Route to hostedcluster_controller managedResources based on Routes capability

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
This PR https://github.com/openshift/hypershift/pull/787 intoduced a behaviour to prevent us reconciling the secret with user/pass for the guest cluster when the oauth config is set. However the boolean value passed through the reconciling function is wrongly inverted. This PR fixes it by seeting explicitOauthConfig as true when .OAuth != nil
=> Set explicitOauthConfig as true when .OAuth is not nil

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Release 4.8 does not support cluster profiles and therefore does not support moving the ingress operator to the management cluster. This removes that reconciliation logic and continues to use the in cluster ingress operator
Fixes #
Duplicate deployment in release-4.8
**Checklist**
=> disable management cluster ingress operator in incompatible release-4.8

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
https://github.com/openshift/hypershift/pull/787 intoduced a behaviour to prevent us reconciling the secret with user/pass for the guest cluster when the oauth config is set.
https://github.com/openshift/hypershift/pull/907 fixed a bug in the former PR.
This PR improves the unit test coverage to use the same real global config pointed in the docs as an example.
=> Improve TestReconcileKubeadminPassword unit test to use real config

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
some providers like None and currently IBM Cloud UPI (Satellite) do not have explicit machine template types. 
This PR changes that so the default is if something is not explicitly defined an empty list is returned which will allow a graceful skip of the machineTemplate deletion logic instead of a stopping cleanup of the nodepools.
Current code stops here:
https://github.com/openshift/hypershift/blob/767e7abff226c8559935a13b1287d377072e1633/hypershift-operator/controllers/nodepool/nodepool_controller.go#L150
Fixes regression found in IBMCloud regression tests
**Checklist**
=> fix machineTemplate deletion logic to prevent panics in the hypershift operator (fixes IBMCloud deploys)

api/v1alpha1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go, control-plane-operator/controllers/hostedcontrolplane/configoperator/params.go, control-plane-operator/controllers/hostedcontrolplane/cvo/params.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, control-plane-operator/controllers/hostedcontrolplane/ocm/params.go, control-plane-operator/controllers/hostedcontrolplane/olm/params.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go, support/config/deployment.go, support/config/deployment_test.go
Currently there is no way to tie the deployments in the master-control plane to a given release. Obviously in the normal happy path: we assume over time things will reconcile and match the normal desired state of the cluster. There are also a few statuses that look at the operator versions in the cluster.
However: in a managed cloud offering: the internals of a user cluster can be in various states based on how they are operating the cluster including unhealthy states that might block the rollout of some downstream components (like monitoring operator) but not the managed control-plane side.
This pr adds an annotation that holds the release image a deployment was reconciled with. We can then look at a given deployment (like the kube-apiserver) and …
=> add release image annotation support for extra metadata that can tie downstream deployments to a given release image

cmd/infra/aws/destroy_iam.go, cmd/infra/aws/iam.go
It is the controller and not the operator that interacts with AWS, and
that uses a different SA. This change fixes dynamic provisioning of
volumes in AWS with a current 4.10 OCP.
=> Fix serviceaccount name for AWS CSI controller

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
Before this commit, KAS was allowed to launch in parallel with etcd, leading to
a race between the KAS etcd client timeout and etcd initialization. When KAS
loses the race, the KAS container restarts, incurring a backoff/startup time
penalty and tripping the crashing pod detector in the e2e suite.
This commit improves startup reliability by adding an init container to KAS
which waits for the etcd client service name to resolve (via `nslookup`) to
prevent useless restarts when etcd isn't ready yet.
**Checklist**
=> kas: wait for etcd client service name before allowing startup

control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/params.go
this adds the release image annotation to the konnectivity agent deployment to provide the ability to track it's rollout in relation to a release image
Fixes #
**Checklist**
=> add release annotation to konnectivity agent deployment

docs/content/how-to/distribute-hosted-cluster-workloads.md, docs/mkdocs.yml
This introduces high level docs for a management cluster operator to leverage `hypershift.openshift.io/control-plane: true` and `hypershift.openshift.io/cluster: ${HostedControlPlane Namespace}` to implement a Hosted Cluster workload distribution strategy.
Fixes #
**Checklist**
=> Add basic docs for Hosted Cluster workload distribution

cmd/bastion/aws/create.go, cmd/bastion/aws/destroy.go, cmd/consolelogs/aws/getlogs.go, cmd/infra/aws/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/util/util.go, hypershift-operator/main.go, test/e2e/autorepair_test.go, test/e2e/util/dump/journals.go
This allows the hypershift CLI infra AWS to work with key and secretKey credential values, when integrated into controllers or other environments where the credentials file may not be available.
This is to address issue: #859 
This adds AWSKey and AWSSecretKey to the options we use for infra.aws.create and infra.aws.create_iam.  The same was added to the destroy.  This allows someone consuming the Go functions to include the credentials, but leaves the secret definition, access to the impelmenter
=> Add new awsconfig creds

cmd/bastion/aws/create.go, cmd/bastion/aws/destroy.go, cmd/cluster/agent/create.go, cmd/cluster/agent/destroy.go, cmd/cluster/aws/create.go, cmd/cluster/aws/destroy.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/cluster/core/dump.go, cmd/cluster/kubevirt/create.go, cmd/cluster/kubevirt/destroy.go, cmd/cluster/none/create.go, cmd/cluster/none/destroy.go, cmd/consolelogs/aws/getlogs.go, cmd/create/create.go, cmd/destroy/destroy.go, cmd/infra/aws/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy.go, cmd/infra/aws/destroy_iam.go, cmd/install/install.go, cmd/kubeconfig/create.go, cmd/nodepool/aws/create.go, cmd/nodepool/kubevirt/create.go, main.go
Refactor the CLI to use the same context. Replace the `Run` function by `RunE` to return errors from the cmd implementation, instead of `exit(1)` from unexpected locations, the command abortion will be done from one place at the root command.
=> Refactor context usage in the CLI, to reduce code duplication

Dockerfile
This PR reduces the number of the image layers by using a single `COPY` Dockerfile command instead of a command per executable. 
**Checklist**
=> Reduce the number of the docker image layers

cmd/cluster/core/create.go
**What this PR does / why we need it:**
The validation that there is no cluster exist with this name
in the namespace (done before cluster creation) is wrong
Before this change, the "Cluster already exists" error was returned in case Get HostedCluster
returned error, which is not `NotFound` error
This fix change the validation to be as following:
1. validate HostedCluster `namespace/name` doesn't exists, if it does
exists return error with relevant description
=> Fix HostedCluster doesn't exist validation

availability-prober/main.go, control-plane-operator/hostedclusterconfigoperator/cmd.go, control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/main.go, ignition-server/main.go, support/upsert/loopdetector.go, test/e2e/e2e_test.go
Before this commit, a Zap logging misconfiguration caused the RFC3339 timestamp
format option to be ignored because of the option being applied to the default
encoder instead of the user-supplied encoder being passed to `zap.New()`. As a
result, JSON logs were emitted with the EpochTimeEncoder.
This commit fixes all the logging configurations so that JSON logs use RFC3339
timestamps.
**Checklist**
=> Make JSON logging output in RFC3339 format

cmd/log/log.go, cmd/nodepool/aws/create.go, cmd/nodepool/create.go, cmd/nodepool/kubevirt/create.go
Fix three issues added in PR #832:
* Fix Global flags to use PersistentFlag insead Flag
* Change all objects to be passed as pointers in order to have command values passed
* In cmd/log the way passing keysAndValues parameter
Fixes #921
**Checklist**
=> Fix NodePool CLI

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/networkpolicy/manifests.go
When services are of publishing type `NodePort`, current network policies do not allow ingress to OAuthServer, Ignition, and Konnectivity services.  This PR adds NetworkPolicies that allow ingress from anywhere and are only created if the service publishing type is NodePort for the service.
Fixes #925 
**Checklist**
=> Add NetworkPolicies for NodePort services

api/fixtures/example.go, api/fixtures/example_aws.go
Currently, the provider has to implement an `AsObjects` interface that
returns a slice of objects. The only implementation of this interface is
for AWS which is assiged to a variable of the interface type, which
forces a type assertion two lines later.
All of this is needlessly complicated, we can simply pass a slice of
client objects from the provider-specific part into the genreric part
instead.
Fixes #
**Checklist**
=> CLI: Simplify provider-specific kube resources

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/ibmcloud/ibmcloud.go, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt_test.go
We currently require the type meta on the infra CR to be set correctly
which isn't done by default. Infer it instead to simplify implementing
new providers and remove one possible source of errors.
/assign @enxebre 
Fixes #
**Checklist**
=> Automatically infer infra cr GVK

hypershift-operator/main.go
This makes the Hypershift operator populate the OIDC configmap in the
kube-public namespace which allows the `install` command to skip that
which in turn means its `--render` functionality can be extended to use
a pre-existing secret.
Fixes #
**Checklist**
=>  Hypershift operator: Ensure the oidc configmap

hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent_test.go
"Cloud Credentials" for the Agent platform are given as RBAC CRs which enable the capi provider to watch and bind agents from a specific namespace. With current naming if the hostedControlPlane namespace happens to be the same than hostedCluster.Spec.Platform.Agent.AgentNamespace RBAC naming might clash.
This PR sets RBAC naming for Agent platform consistent with other references and add unit tests.
Fixes #934
**Checklist**
=> Rename creds rbac CRs for agent platform

control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
There is a race condition without leader election for the control plane operator when two instances are active at a given moment of time. It can lead to them simultaneous modifying deployments and resulting them in unexpected states (sometimes a merge of the data between the two versions of the operator). This pr enables leader election for the component by default to eliminate this reace condition
Fixes # Race condition that can result in unexpected cluster states
**Checklist**
=> enable leader election for control plane operator to prevent race conditions on upgrades

api/fixtures/example.go, cmd/cluster/aws/create.go, cmd/cluster/core/create.go, cmd/infra/aws/create.go, cmd/infra/aws/ec2.go, test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/util/fixture.go
Enable multi-zone infra support for guest cluster so we can start testing multizone guest clusters in CI.
Note: This does not enable the functionality e2e.  Just the infra creation.
Fixes #
**Checklist**
=> Add multi-zone support to create infra aws

docs/content/how-to/restart-control-plane-components.md, docs/mkdocs.yml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This pr ensures all components respect the restart annotation. This is critical to support ca rotation because ignition server needs to reload the server certs after rotation which currently is not occuring. Additionally: it is opertionally expected from an ibm perspective that all components get restarted on a master refresh operation. This is an agreement we provide to customers that needs to be honored and is good operationally for all providers. There will be other situations in the future where an on demand restart is beneficial.
Fixes # Necessary to enable to support CA …
=> ensure all components respect the restart annotation.

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
There's an bug in CAPI AWS provider which prevent Machines from targeting subnets ids which are not present on the infra CR.
This PR is a workaround by keeping the infra CR subnets in sync with what is required by NodePools.
This should be dropped once https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2864 gets merged.
ref https://issues.redhat.com/browse/HOSTEDCP-278
**Checklist**
=> Reconcile AWS infra CR with NodePool subnets

test/e2e/create_cluster_test.go
The expected node pool name in the kubevirt test was changed to include AWS zone, where there is no AWS zone in kubevirt cluster, an so the test is fails because it can't find the node pool with the wrong name.
This PR reverts the naming change in the kubevirt test.
Fixes #
**Checklist**
=> fix the node pool name in the kubevirt 2e2 test

hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
https://github.com/openshift/hypershift/pull/948 introduced a hot reconcile loop due to fighting between `reconcileAWSCluster` and `reconcileAWSSubnets`.  Should allow `reconcileAWSSubnets` to set the `Subnets`.
https://github.com/openshift/hypershift/blob/91493d704cd498bb3eaaabd434901cb3c4d4982c/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go#L3765
Fixes #
**Checklist**
=> Fix hot reconcile on AWSCluster

cmd/nodepool/agent/create.go, cmd/nodepool/aws/create.go, cmd/nodepool/core/create.go, cmd/nodepool/create.go, cmd/nodepool/kubevirt/create.go
Since changed the NodePool to be platform aware (PR #832)
In order to create NodePool for specific platform, the platform must implement specific sub command
Therfore add the subcommands Agent platform, although the NodePool platformSpec is empty for those platforms
**Checklist**
=> Add Agent platform type under NodePool cmd

control-plane-operator/controllers/hostedcontrolplane/olm/assets/packageserver-deployment.yaml
We currently only give it 30 seconds before we kill it, this appears to
not be enough.
Fixes #
**Checklist**
=> Packageserver: Give more leeway in liveness probe

cmd/install/install_render.go, hack/app-sre/saas_template.yaml
**What this PR does / why we need it**
The current template generation code wrongly quotes the int typed field
`.spec.replicas` of the operator deployment. the resulting template can not processesd.
`.spec.replicas` needs to be an int32 so having a quotes placeholder in
the openshift template is invalid. instead an the double curly bracket
syntax needs to be used to indicate that a value should be treated as
unquoted in the resulting manifests.
Signed-off-by: Gerd Oberlechner <goberlec@redhat.com>
=> fix replica param quoting in openshift-template generation

api/fixtures/example.go
Since PR #944 NodePool is not created for None and Agent platforms
Add Default case to the switch/case to handle those platforms
**Checklist**
=> Fix issue of NodePool not created for Agent and None platforms

Makefile, cmd/install/assets/hypershift_operator.go, cmd/install/assets/hypershift_operator_test.go, cmd/install/install.go, cmd/install/install_render_test.go, cmd/install/install_test.go, hypershift-operator/main.go
A previous pr regressed the standard behavior where oidc mounts/config were not added to the hypershift operator unless specified. PR is: https://github.com/openshift/hypershift/pull/949. This PR returns to the old behavior and adds unit tests to ensure this path is not broken in the future
Fixes # Regression in None AWS install path
**Checklist**
=> only add oidc mounts and arguments when they are specified

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
An invalid error is getting returned in the hosted-cluster-config-operator when the kubeadminPasswordSecret is not found. This secret will not exist in clusters with explicit oauth configurations specified and should not return an error when not found.
Fixes # Fixes invalid error being thown during reconcilation
**Checklist**
=> remove invalid error return when KubeadminPasswordSecret not found.

Makefile, test/e2e/control_plane_upgrade_test.go, test/e2e/e2e_test.go, test/e2e/util/util.go
Add e2e support for multizone guest clusters via a new `--e2e.aws-zones` flag
Depends on https://github.com/openshift/hypershift/pull/951
Fixes #
**Checklist**
=> e2e: add AWS multizone support

control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-certified.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-community.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-marketplace.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-operators.deployment.yaml
https://github.com/openshift/hypershift/pull/966 is causing `TestOLM` to fail in the periodics.
Revert until we have a root cause.
`TestOLM` is failing in the periodics after this commit.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-e2e-aws-periodic/1489569576726302720
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-e2e-aws-periodic/1489660131149877248
```
olm_test.go:201: 
csv never installed
Unexpected error:
<*errors.errorString | 0xc000098050>: {
s: "timed out waiting for the condition",
}
timed out waiting for the condition
occurred
``` …
=> Partial revert "bump 4.9 refs to 4.10"

control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-certified.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-community.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-marketplace.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-operators.deployment.yaml
The static manifests were locked into v4.10 earlier when they should be adjusted to match the release payload. Adjusting to match release-4.8
Fixes # Proper version match of images
**Checklist**
- [ X ] Subject and description added to both, commit and PR.
=> Release 4.8 olm images

Makefile
Currently, the only make target we have for generating files is `verify`.  However, this returns non-zero if there is an update.
This PR adds a new `update` target that runs all the targets that can update files and doesn't return an error if there is an update.
After this PR, `update` is for generating file updates and `verify` ensures generated files are up-to-date and also runs code checking targets which do not generate code.
Fixes #
**Checklist**
=> add update target to Makefile

test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/olm_test.go
Tests run in e2e-all are not passing because they weren't modified with multi-zone awareness.
Fixes #
**Checklist**
=> support multizone in e2e-all tests

hack/ci/install-cnv.sh
To make the E2E kubevirt provider tests more readable, this PR adds a script to replace the embedded script in the test configuration at openshift/release repository.
**Checklist**
=> Add a Script to install OpenShift Virtualization on a CI cluster

api/v1alpha1/endpointservice_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_awsendpointservices.yaml, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/platform/aws/controller.go
https://github.com/openshift/hypershift/pull/951 accidentally worked due to the `NodePool` being updated after the creation of the `AWSEndpointServices`, however, reconciliation of `.spec.subnetIDs` on `AWSEndpointServices` currently happens on a controller that doesn't watch `AWSEndpointServices`.
This moves the reconciliation of `subnetIDs` to the `AWSEndpointServiceReconciler` and adds a `NodePool` watch to that controller.
The mapping of `NodePools` <-> `AWSEndpointServices` is a little fragile.  I'm open to suggestions.
Fixes #
**Checklist**
=> move subnetID reconcilation for AWSEndpointServices

docs/content/how-to/agent-platform.md, docs/mkdocs.yml
Add documentation for using the agent platform
Fixes #[MGMT-8469](https://issues.redhat.com/browse/MGMT-8469)
**Checklist**
=> Add agent platform to docs

hypershift-operator/main.go
HCO components switched to `Leases` in https://github.com/openshift/hypershift/pull/935.  The RBAC permissions to use `leases` was added to the `hypershift-operator` `Role` in https://github.com/openshift/hypershift/pull/366, but `LeaderElectionResourceLock` was not changed in for the `hypershift-operator` `Manager`.
Fixes #
**Checklist**
=> use leases for hypershift-operator leader election

hypershift-operator/controllers/hostedcluster/createorupdate_annotation_enforcer.go, hypershift-operator/controllers/hostedcluster/createorupdate_annotation_enforcer_test.go
When running multiple clusters, annotating cluster scoped resources results in hot reconcile loop.
Fixes #
**Checklist**
=> skip annotating cluster scoped resources

hypershift-operator/main.go
We don't currently use leader election, which means that if the operator
image gets updated, we have two concurrent operators running that race
with each other, leading to a lot of back-and-forth updates to the
deployments created for a hostedcluster:
```
$ k get pod
NAME                                              READY   STATUS              RESTARTS      AGE
capi-provider-6b845f68d7-28clq                    0/2     Terminating         0             10m
capi-provider-6b845f68d7-28dzq                    0/2     Terminating         0             11m
capi-provider-6b845f68d7-2zljk                    0/2     Terminating         0             11m
capi-provider-6b845f68d7-2zrgg                    0/2     Terminating         0             10m
capi-provider-6b845f68d7-45qj4 …
```
=> Hypershift operator: Enable leader election by default

cmd/install/assets/recordingrules/hypershift.yaml, hack/app-sre/saas_template.yaml
The Prometheus recording rules do not work with more than one HostedCluster.  This PR fixes them.
Fixes #
**Checklist**
=> fix recording rules to work with multiple HostedClusters

control-plane-operator/hostedclusterconfigoperator/operator/config.go, control-plane-operator/main.go, hypershift-operator/main.go
* Standardize `Lease` names.
* Increase leader elect tunable defaults from (2, 10, 15) to (15, 40, 60).  This will reduce steady-state PUTs from 30/m to 4/m per manager with leader election enabled of which we have 3.
* Remove the `enable-leader-election` flags from the CPO and HO.  I couldn't think of a reason why we would need these.
Fixes #
**Checklist**
=> increase leader elect durations

api/fixtures/example.go, api/fixtures/example_aws.go, cmd/cluster/aws/create.go, cmd/cluster/core/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/iam.go, control-plane-operator/controllers/hostedcontrolplane/kas/aws_kms.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/main.go
[CLI: encrypt etcd by default](https://github.com/openshift/hypershift/commit/a2aba330d83a2a621d28f959385f2da0ae555d4d)
Adds flag `--aws-kms-key` to both `create iam aws` and
`create cluster aws` commands to allow specifying an existing KMS key to
use in encrypting etcd secrets. If this flag is specified, an IAM role
is created that allows the kms encryption plugin to use the key for
encryption/decryption.
If no KMS key is specified, a 32-byte AESCBC key is generated and
configured as the default encryption method.
[Set the default AWS KMS provider image](https://github.com/openshift/hypershift/commit/2349ab0003b2638df9dfb20396ebc3db48df4b21)
The AWS KMS provider is now built by CI under the hypershift
organization. This sets up the image built by …
=> Enable etcd encryption by default, support STS creds for AWS KMS provider

cmd/cluster/core/dump.go, test/e2e/util/dump/dump.go, test/e2e/util/fixture.go, test/e2e/util/util.go
We really want this to be able to debug e2e runs that fail due to
clusteroperators not becoming ready. I tried this locally, and it
consistently takes ~90 seconds to do a dump (n=3) which seems
reasonable. To be sure, I also added a log that will show how long it
took in CI.
Fixes #
**Checklist**
=> Re-Enable guest cluster dump in e2e

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/ibmcloud/ibmcloud.go, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go, hypershift-operator/controllers/hostedcluster/internal/platform/none/none.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go
The AWS capi provider currently always errors for some time during
startup when a new cluster is created, because there is no token,
because the KAS is not up yet so the token minter sidecar can't mint
one. This change makes us use the availability prober init container to
avoid going into backoff due to this.
Using the availability prober required two new things to be available to
the provider:
* The HCP in case it uses a non-default apiserver port
* The Availability prober image
For the first, the existing provider interface was extended, as we only
have construct the hcp right before calling CAPIProviderDeploymentSpec.
For the static availability prober image we avoid extending the
interface for every provider for something that is only needed by AWS by
passing it into the provider at …
=> AWS: Use availability prober in capi provider

test/e2e/control_plane_upgrade_test.go
Upgrade test fails occasionally with a restart of the `kube-apiserver`.  The KAS only tries to resolve the etcd name for 15s before failing, resulting in a container-level restart, which causes e2e to fail.  If single replica etcd goes down between the init container that verifies the etcd DNS can resolve and when the KAS starts, we can see this flake.
Switching to an HA control plane will allow etcd to say available during the upgrade and avoid this issue.  This also verifies that our upgrades function in an HC control plane, which we currently do not test.
Fixes #
**Checklist**
=> e2e: make upgrade test HC HighlyAvailable

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/ibmcloud/ibmcloud.go, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go, hypershift-operator/controllers/hostedcluster/internal/platform/none/none.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go
It is only used by AWS and unlikely to be used by something else in the
future. Pass it on to the AWS provider during initialization rather than
making it part of the platform interface.
Fixes #
**Checklist**
=> Move the tokenMinterImage arg out of the platform interface

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
https://github.com/openshift/hypershift/pull/583 introduced two direct calls to `Create` rather than `CreateOrUpdate`.  The result in about half the mutating calls from the CPOs in CI being 409 Conflict on these two resources: secret `pprof-cert` and configmap `olm-collect-profiles`.  
This PR switches to `CreateOrUpdate` to avoid these calls and reduce the CPO mutating call volume by roughly 50%.
Fixes #
**Checklist**
=> use CreateOrUpdate for OLM collect profiles resources

hypershift-operator/controllers/hostedcluster/internal/platform/ibmcloud/ibmcloud.go, hypershift-operator/controllers/hostedcluster/internal/platform/ibmcloud/ibmcloud_test.go
Currently, CAPI clusters are getting deployed for Classic and VPC clusters despite not being operational for those providerTypes yet. This PR stops that so testing of the general system in these environments in IBMCloud can be performed and operations behave appropriately (as is delete operations are getting blocked because nothing is removing the CAPI cluster). It also provides unit tests for when someone does look to add a CAPI system to one of these environments (ensures they modify the unit tests and add more based on what changes they are introducing.)
Fixes # N/A …
=> ensure no capi cluster is created for ibmcloud platformTypes Classic and VPC

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, control-plane-operator/main.go
CPO currently doesn't cache `services` due to a single service we care about outside the HCP namespace, namely the service for the private ingress we create when the `endpointAccess` is `PublicAndPrivate` or `Private`.
This reworks the code to use a separate client in that single case so we can cache services in the HCP namespace.
Fixes #
**Checklist**
=> enable CPO caching for services

cmd/install/install.go
This commit adds a validation which ensures the `--oidc-storage-provider-s3-bucket-name`
flag does not contain dots (.), because such buckets will have invalid certificates that
cause the OIDC provider setup to fail in ways that are hard to diagnose.
See: https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
**Checklist**
=> install: reject bucket names containing dots to prevent HTTPS errors

docs/content/how-to/kubevirt-platform.md, docs/mkdocs.yml
In order to have more platform stability and test ability, add this quick
start guide to allow external users to use it
This is added as a second platform after AWS platform quick start guide
Fixes #961 
**Checklist**
=> Add Kubevirt platform quick start docs

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
Currently we have high number of DELETE 404s on HostedCluster deletion.
This PR refactors the delete path to avoid DELETEs on non-existent resources.
Fixes #
**Checklist**
=> refactor delete to avoid 404s

Makefile, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, hack/app-sre/saas_template.yaml
introduce RBAC artifact generation for hypershift admin personas / services
those artifacts are generated when the `--enable-admin-rbac-generation` flag
is provided during `hypershift install`
persona: hypershift-client
used by a client leveraging hypershift as a service to create hosted clusters
* hypershift-client ClusterRole
full permissions on the hostedcluster and nodepool CRs
* hypershift-client ServiceAccount
* hypershift-client ClusterRoleBinding
binds the hypershift-client ClusterRole to hypershift-client SA and Group Ref
the groups itself must be provided by other means
persona: hypershift-readers
used by admins to investigate hosted clusters and the hypershift operator.
* hypershift-readers ClusterRole
same permission subjects as the …
=> RBAC manifest creation for Hosted Cluster admin personas

cmd/cluster/core/dump.go
This commit adds Node resources to the `dump` command.
**Checklist**
=> cli: include Node resources in cluster dump

cmd/install/assets/recordingrules/hypershift.yaml, hack/app-sre/saas_template.yaml
During upgrades, there are two CPO pods.  Because our recording rules currently sum them we can't separate them for dashboard viewing or budget enforcement.
This PR maintains the pod separation.
Fixes #
**Checklist**
=> include pod in CPO recording rules for multiple CPOs on upgrades

control-plane-operator/controllers/hostedapicache/cache.go, control-plane-operator/controllers/hostedapicache/cache_controller.go
Before this change, the HostedAPICache controller was creating a cache
with the RESTMapper from the management cluster. This caused an error
initializing the cache if a ClusterVersion resource did not exist in the
management cluster but did exist in the guest cluster.
This commit replaces the code to create the cache directly with code to
create a controller-runtime cluster and then gets the cache from it.
This results in the proper RESTMapper (from the guest cluster) being
used for the cache.
**Checklist**
=> Fix RESTMapper used by HosteAPICache in Control Plane Operator

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
This makes us set up secrets for the various operators on Azure that
need to interact with it. The implementation follows the same approach
as the cloud credentials operator, namely just copy one reference secret
around.
Ref https://issues.redhat.com/browse/HOSTEDCP-242
Fixes #
**Checklist**
=> Azure: Create credentials secrets for in-cluster clusteroperators

hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
The periodic jobs currently create 7 HCs at once.  This puts the worker nodes in the test cluster under CPU contention.  The CAPI manager currently runs with no resource request, which results in the kubelet placing it in the `BestEffort` QoS cgroup that gets almost no CPU when there is contention.  When this happens, the CAPI manager is not able to respond to requests on its healthz endpoint and the liveness probe failure causes it to restart.  This, in turn, causes the overall job to fail.
The PR sets resource requests for this container so that it gets a larger share of CPU when the node is under contention.
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a …
=> add resource requests to CAPI manager container

api/fixtures/example.go, cmd/nodepool/kubevirt/create.go
Unlike vanilla KubeVirt installs, Kubevirt installed by CNV defaults to using the masquerade network interface binding. That binding uses NAT with the pod network which makes all the KubeVirt hypershift tenant nodes look like they have the same IP address. The result is a non-functional cluster.
We didn't notice this at first because we were testing locally with a setup similar to minikube+kubevirt. Once we transitioned to testing OCP+CNV the issue was obvious.
=> Default to using bridge binding for kubevirt platform VMs

hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go
Adds cluster role for agent provide. It is needed due to ACM changes that blocks clusterdeployment creation in case we don't have specific cluster rile
Fixes #
https://bugzilla.redhat.com/show_bug.cgi?id=2057060
**Checklist**
=> MGMTBUGSM-108: Adding clusterrole for agent provider

test/e2e/util/util.go
I set the CPO read budget to tight initially and it caused a periodic to fail
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-e2e-aws-periodic/1496817236092915712
Fixes #
**Checklist**
=> e2e: raise CPO read budget

control-plane-operator/main.go
Before this commit, the context cancellation handling in the control-plane-operator entrypoint had an `os.Exit()` call which races with deferred shutdown behavior, leading to the orphaning of the lease hold and causing a long delay upon restart waiting for the lease to expire.
This commit removes the `os.Exit()` call so the lease is returned on exit, so that subsequent restarts will not have to wait to regain the lease.
**Checklist**
=> Fix CPO shutdown to prevent leak of lease hold

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/controlplaneoperator/manifests.go
- Removes CPO's ClusterRole/ClusterRoleBinding
- Updates CPO's securitycontext from explicit to use default
- Adjusts CPO's existing Role
- Creates additional Role/RoleBinding for ingress service reads
- Creates additional Role/RoleBinding for ingress operator ingresscontroller crud
- Conditionally activates awsprivatelink controllers based on Route capability
Fixes #1026 
**Checklist**
**Note**
Have verified that control plane is able to get rolled out with these changes.
```
NAME                                                 READY   STATUS      RESTARTS   AGE …
```
=> fix(cpo): Reduce CPO cluster permissions

.ko.yaml
Before this commit, `ko` v1.0.0 fails because of an outdated reference to the now deleted hosted-cluster-config-operator binary in `ko.yaml`. This commit removes the bad entry and fixes the tool.
**Checklist**
=> Remove outdated binary from ko.yaml

api/v1alpha1/hostedcluster_types.go, cmd/cluster/agent/create.go, cmd/cluster/aws/create.go, cmd/cluster/azure/create.go, cmd/cluster/core/create.go, cmd/cluster/kubevirt/create.go, cmd/cluster/none/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/infraid/infraid.go
The infraID is expected to be always set inside the cluster
infrastructure, despite not beeing needed by all platforms. Default it
in the hostedcluster reconciler.
Ref https://issues.redhat.com/browse/HOSTEDCP-280
Fixes #
**Checklist**
=> Hypershift operator: Default the infraID

cmd/bastion/aws/create.go, cmd/bastion/aws/destroy.go, cmd/consolelogs/aws/getlogs.go, cmd/infra/aws/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/util/util.go, control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, hypershift-operator/controllers/platform/aws/controller.go, hypershift-operator/main.go, test/e2e/autorepair_test.go, test/e2e/util/dump/journals.go
We currently create an aws config with a SharedCredentials credentials
provider. This provider unfortunately only supports shared crdentials
that have a static credential and no other setting.
The only code in the AWS sdk that supports the full set of settings for
a shared credentials file is part of the session package, which means
the shared credentials file has to be set up as part of the session.
Additionally, the region must also be set in the session and not the
config, because otherwise that region will be used for all aws services,
even the ones that are global. This in turn breaks authentication
methods that need to contact STS, as that is not a global service. …
=> AWS: Support all properties of shared credentials files

control-plane-operator/controllers/hostedcontrolplane/cloud/azure/azure.go, control-plane-operator/controllers/hostedcontrolplane/cloud/config.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/manifests/azure.go
This is the last piece after which Azure should be generally working as expected: It adds the cloud provider configs to KCM and KAS.
Azure is a bit special here, in that it uses the cloud-config to configure credentials rather than having a distinct way of doing that. We already have a cloudconfig for nodes, which uses the instance identity for authentication. This can't work for KAS and KCM, so we create a second cloudconfig that holds the literal credentials and use that.
Since it holds credentials, we put this cloud-config into a secret rather than a configmap.
Ref https://issues.redhat.com/browse/HOSTEDCP-242
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be …
=> Azure: Add cloudconfigs to KCM and KAS

hypershift-operator/controllers/nodepool/nodepool_controller.go, ignition-server/README.md, ignition-server/controllers/cache.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/controllers/tokensecret_controller_test.go
Before this PR:
The ignition-server/tokensecret-controller would delete the token Secret after a UUID ttl expired eventhough it was containing same the version/config.
After this PR:
The token Secret is the same for the whole NodePool lifetime as far as the version/config pair does not change.
The ignition-server/tokensecret-controller manages token ID rotation by periodically creating a new tokenID for the existing Secret and persisting it in the cache.
This has some positive consequences:
- Rotation happens every time a token ID is beyond half of its ttl enabling an overlapping period of ttl/2 at max with the old token ID.
Overlapping fixes racing scenarios where a Machine is created with a userdata pointing to a tokenID that gets expired right …
=> Update ignition token rotation flow

test/e2e/util/util.go
The budget query for CPO read/mutate/delete-404 doesn't filter by `app=control-plane-operator` and thus sums activity from other components as well.
Fixes #
**Checklist**
=> e2e: fix CPO budget queries

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, support/capabilities/fake/fake.go
This makes us validate that the azure cloud credential secret is valid
and use it as an input to the ValidConfiguration condition. If this
condition is `false`, the hypershift operator will not reconcile a
cluster.
/cc @enxebre 
Fixes #
**Checklist**
=> Azure: Validate cloud credential secret is valid

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
The NodePool controller assumes infraID as contractual info (particularly uses it for naming generation). This https://github.com/openshift/hypershift/pull/1055 introduced a race so MachineDepoyment could be created without the infraID in the name.
This PR let the NodePool controller wait until th infraID is set in the HC API.
Fixes https://github.com/openshift/hypershift/issues/1059
**Checklist**
=> Let NodePool controller wait if infraID is empty

control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
Init containers must tolerate being rerun.
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#pod-restart-reasons
In the case, that the files already exist in the emptyDir, the OASTrustAnchorGenerator init container fails because the destination files are read-only.
Forcing the `cp` fixes this.
Fixes #
**Checklist**
=> force copy in openshift-apiserver trust anchor init container script

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
We already have routes in the `managedResources` list, if they are
supported:
https://github.com/openshift/hypershift/blob/e9580eea83351e81edb79e10cf6631d06afbb944/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go#L225-L228
Fixes #
**Checklist**
=> HO: Remove redundant watch for routes

api/v1alpha1/nodepool_types.go, cmd/install/assets/cluster-api-provider-agent/capi-provider.agent-install.openshift.io_agentmachines.yaml, cmd/install/assets/cluster-api-provider-agent/capi-provider.agent-install.openshift.io_agentmachinetemplates.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/content/how-to/agent-platform.md, docs/content/reference/api.md, go.mod, go.sum, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/agent.go, vendor/github.com/openshift/cluster-api-provider-agent/api/v1alpha1/agentmachine_types.go, vendor/modules.txt
Users can already choose Agents according to labels.  While minimum
CPU/RAM is helpful, there are lots of other helpful properties, like
maximum CPU/RAM, disks, networks, GPUs, etc.  Rather than including them
all in the Spec, users should manually add labels as they desire.  In
the future, we will create an auto-labeling mechanism for Agents.
Fixes #[MGMT-9423](https://issues.redhat.com/browse/MGMT-9423)
**Checklist**
=> Remove choosing Agents by minimum CPU and RAM

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
Because of the multi az work we are appending the az to NodePool names generated by the cli, which resulted in a long enough name to uncover a bug in the function that generates the name of the MD
Fixes https://github.com/openshift/hypershift/issues/1059
**Checklist**
=> Fix getname func

test/e2e/util/util.go
Catalog rollout pods can be scheduled on the HCP by OLM during the testing process and they do not have resource request.  These pods are outside our direct control.  This PR excludes them from the check.
Caused this failure
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-e2e-aws-periodic/1497994977861439488
Fixes #
**Checklist**
=> e2e: exclude catalog rollout pods is EnsureHCPContainersHaveResourceRequests

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This adds a new deleteIfNeeded that takes an arbitrary object, will try
to get it and only if that was successful and the object doesn't have a
deletionTimestamp yet it will be deleted. Any IsNotFound error along the
way is swallowed. All existing places where we had typed code for this
are updated to use the new func.
/cc @sjenning 
Fixes #
**Checklist**
=> Factor out repeated code from delete-if-not-deleted code

.ko.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/rbac.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
This commit adds a ServiceMonitor to the control plane kube-apiserver
component, secured with TLS using a client certificate generates specifically
for this purpose scoped to the `system:monitoring` cluster role. This enables
end users to aggregate control plane API server metrics.
**Checklist**
=> Enable ServiceMonitor support for kube-apiserver

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/configoperator.go, control-plane-operator/hostedclusterconfigoperator/cmd.go, control-plane-operator/hostedclusterconfigoperator/configmetrics/configmetrics.go, control-plane-operator/hostedclusterconfigoperator/operator/config.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/controlplaneoperator/manifests.go
This change makes the hosted cluster config operator emit a couple of
metrics that are usually generated by the apiserver operator. It also
adds a podmonitor for the HCCO, because so far we haven't been scraping
its metrics.
Ref https://issues.redhat.com/browse/HOSTEDCP-294
Fixes #
**Checklist**
=> Produce config metrics for telemetry

api/fixtures/example.go, docs/content/how-to/create-azure-cluster.md
This easens interoperability. There doesn't seem to be an official
format we could be using. The type is copied to avoid depending on the
installer.
Fixes #
**Checklist**
=> Azure: Use same credentials file format as installer

api/fixtures/example.go, cmd/cluster/core/create.go, cmd/cluster/kubevirt/create.go, test/e2e/e2e_test.go
Add service-publishing-strategy new flag in order to allow changing the cluster service expose type
Supported options: NodePool (Select a random node to expose service access through), Ingress (Use LoadBalancer and Route to expose services)
Default value: Ingress
**Checklist**
=> Kubevirt platform: Add service-publishing-strategy flag

test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/util/fixture.go, test/e2e/util/util.go
Before this commit, API budget assertions were executed inline with main test
code while the cluster under test was still alive. Because of this, the
Prometheus queries could not account for metrics which occur only during
teardown.
This commit improves the accounting by moving the API budget assertions into the
test fixture so that the check happens uniformly following cluster teardown in
the fixture code itself. Test authors should no longer call `EnsureAPIBudget`
directly unless there's a special case.
**Checklist**
=> e2e: fix API budget assertions

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/service.go, control-plane-operator/controllers/hostedcontrolplane/kcm/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kcm.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, control-plane-operator/controllers/hostedcontrolplane/pki/kcm.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/rbac.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
This commit adds ServiceMonitor support to kube-controller-manager. It also
cleans up the ServiceMonitor support for kube-apiserver to remove an unnecessary
certificate mount, fix the cert usage parameter, and refactor the code to be
uniform with other PKI logic.
The ServiceMonitor has relabelling rules that mirror those provided by OCP.
**Checklist**
=> Add ServiceMonitor support to KCM

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_apiserver.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/service.go, control-plane-operator/controllers/hostedcontrolplane/oapi/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/pki/openshift.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/rbac.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
This commit adds a ServiceMonitor to the OpenShift API server component,
using the same label rules present by default in OCP.
**Checklist**
=> Add ServiceMonitor support for OpenShift API server

cmd/infra/azure/create.go
The storage account is in the resource group so its name doesn't really
matter for cleanup. It has however some limitations wrt format, it must
be max 24 characters long and lower alphanumeric. This broke when we
added defaulting for the infraids, which also introduced a new format
that is too long and contains hyphens. This leads to failure:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/26666/rehearse-26666-periodic-ci-openshift-hypershift-main-periodics-e2e-conformance-azure/1499088629878755328#1:build-log.txt%3A79
What we do here matches what the installer does:
https://github.com/openshift/installer/blob/8fca1ade5b096d9b2cd312c4599881d099439288/data/data/azure/vnet/main.tf#L23 …
=> Azure: Use random string rather than infraID as storage account name

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/deployment.go, control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/ocm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/deployment.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/config/deployment.go, support/util/containers.go
- Preserve and honor container resource specs for:
- cluster-policy-controller
- cluster-version-operator
- kube-controller-manager
- openshift-apiserver
- oauth-apiserver
- oauth-server
- openshift-controller-manager
- kube-scheduler
- control-plane-operator
- Move `findContainer()` to `utils.FindContainer()` shared containers lib
- Create `DeploymentConfig.SetContainerResourcesIfPresent()` method
Fixes #1067
**Checklist**
=> feat: Preserve container resources for control plane components

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/kcm/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_cm.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/ocm/config.go, control-plane-operator/controllers/hostedcontrolplane/ocm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/ocm/params.go, control-plane-operator/controllers/hostedcontrolplane/ocm/service.go, control-plane-operator/controllers/hostedcontrolplane/ocm/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, control-plane-operator/controllers/hostedcontrolplane/pki/kcm.go, control-plane-operator/controllers/hostedcontrolplane/pki/openshift.go, control-plane-operator/controllers/hostedcontrolplane/pki/sa.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/rbac.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
This commit adds ServiceMonitor support to the openshift-controller-manager
component, using the same label rules as OCP. It also refactors the existing
ServiceMonitor code so that they all share a single client certificate bound to
the `system:monitoring` role in the guest cluster. This was done to prevent
unnecessary secret and certificate sprawl.
**Checklist**
=> Add ServiceMonitor support for openshift-controller-manager

cmd/bastion/aws/create.go, cmd/bastion/aws/destroy.go, cmd/cluster/aws/create.go, cmd/cluster/core/create.go, cmd/cluster/core/destroy.go, cmd/cluster/core/dump.go, cmd/consolelogs/aws/getlogs.go, cmd/infra/aws/create_iam.go, cmd/install/install.go, cmd/kubeconfig/create.go, cmd/nodepool/core/create.go, cmd/util/client.go, test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/chaos_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/olm_test.go, test/e2e/util/client.go, test/e2e/util/dump/journals.go, test/setup/main.go
This commit purges all identified direct calls to `os.Exit()` outside the
context of entrypoints and very specific deliberate uses. Before this commit,
some of these calls (e.g. to get a client or destroy a cluster) could cause e.g.
an e2e run to immediately terminate without cleaning up when signalled at a
point where the signal coincides with one of the code paths leading to
`os.Exit()`.
=> Purge all non-entrypoint calls to `os.Exit()`

cmd/cluster/azure/create.go, control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, support/capabilities/fake/fake.go, support/capabilities/management_cluster_capabilities.go
Azureclusters have a bug that results in LB services with port 6443
always failing to provision a LB. Work around it by checking the
platform of the management cluster and if its azure, use a different
port.
Fixes #
**Checklist**
=> Azure: Work around a bug that lb services with port 6443 don't work

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/deployment.go
The cluster policy controller should not have the service account token mounted as it does not need to talk to the management clusters api server
Fixes #
**Checklist**
=> don't mount service account token for cluster-policy controller

cmd/cluster/kubevirt/create.go
When creating a hosted cluster with the hypershift cli, the base-domain option is ignored for the kubevirt platform. If a base domain is set like this, ```hypershift create cluster ... --base-domain <foo> ```, then it should be configured on the hosted cluster object when kubevirt is in use.
=> Enable --base-domain cli option with kubevirt provider

cmd/infra/azure/create.go, cmd/infra/azure/destroy.go
* This allows Go functions to call the Run method without having a local credentialsFile
* Optionally allow the input Options to contain the osServicePrincipal information as an azure fixture.
* If credentials fixture is not passed in the options, default to looking for the credentialsFile
* Support options for Azure destroy as well
Signed-off-by: Joshua Packer <jpacker@redhat.com>
Fixes #
**Checklist**
=> Add support for azure.Credentials

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/olm.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-metrics-service.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-collect-profiles.cronjob.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-metrics-service.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go
This commit adds ServiceMonitor support to the OLM and OLM catalog
operators. The metrics label configuration is the same as OCP for
those components.
=> Add ServiceMonitor support to OLM components

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/cvo.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/pki/cvo.go
This commit adds ServiceMonitor support to the CVO. The label config
follows OCP.
=> Add ServiceMonitor support to CVO

api/v1alpha1/nodepool_types.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, ignition-server/README.md, ignition-server/controllers/tokensecret_controller.go, ignition-server/controllers/tokensecret_controller_test.go
This pr enhances how ignition tokens are cleaned on nodepool upgrades. Previously on an upgrade: all ignition tokens were revoked as soon as the config was updated. The problem with this approach is outlined in issue: https://github.com/openshift/hypershift/issues/1020. To summarize: immediate revocation does not account for in flight provisions that were executed with the old token. This means these in flight operations would fail. This is a problem for consumers of the offering that should be addressed: provisions should never have the potential to fail. To fix this: when an upgrade occurs: old tokens are marked for expiration. The expiration time is based on the amount of time necessary to allow all in flight provisions to complete (new provisions will use the updated token). After …
=> add token expiration support to prevent nodepool upgrades from killing in flight provisions.

control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
This PR adds readiness probes to two HA deployments: konnectivity-server and openshift-oauth-apiserver.
Issue: https://github.com/openshift/hypershift/issues/408#issuecomment-1057410802
Implementation details:
- konnectivity-server has :2041/readyz endpoint but it can not be used for the probe - :2041/healthz is used instead.
- openshift-oauth-apiserver already has readiness probe but due to a bug it does not work - the bug is fixed now. The same kind of bug is also fixed for resource request.
**Checklist**
=> Add missing readiness probes on HA deployments

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go
Updates default secret mode from 420 to 416 for all hypershift mounted secrets
Fixes #1031 
**Checklist**
=> Updated secret permissions to 416

cmd/infra/azure/create.go
It uses fmt.Printf rather than the normal logger, has a typo and misses
a trailing newline, resulting in a logline that looks something like
this:
```
Using credentilas: /home/alvaro/.azure/osServicePrincipal.json2022-03-09T11:52:34-05:00	INFO	Successfuly created resourceGroup	{"name": "alvaro-test-alvaro-test-rsdlw"}
```
Fix that.
/cc @jnpacker 
Fixes #
**Checklist**
=> Azure: Fix credentials log

api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, cmd/nodepool/azure/create.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/azure.go, hypershift-operator/controllers/nodepool/azure_test.go
This was never fully implemented. In order to fix it, the bootImageId
was moved from the nodepool to the cluster, because it is unique per
cluster and never changes. Otherwise if there is no nodepool, we are
unable to find it.
Fixes #
**Checklist**
=> Fix create nodepool azure command

control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, support/globalconfig/dns.go, support/globalconfig/dns_test.go
Currently the DNS CRD instance is not getting set properly in IBM Cloud deployments. It is using the default value that I believe is fine for the AWS/upstream openshift dedicated use cases where the cluster name is added after the base domain in the spec. However: that is not the case in IBM Cloud where the specified base domain is the base domain of the cluster (should not have the cluster preprended to it. We specify this through the DNS config already but hypershift is not respecting it and is always using the default value. In addition: Hypershift is currently missing the redirect standard OCP and ROKS deploys offer to the console from the master API endpoint. This enables that functionality by setting ConsolePublicURL appropriately.
Example currently in hypershift:
```
apiVersion: …
```
=> fix dns crd reconciliation for ibm cloud or providers that provide a subdomain

cmd/install/install.go, hack/app-sre/saas_template.yaml, hypershift-operator/main.go
When we moved this into the hypershift operator, the goal was to not
require credentials in the `install render` command. We don't get the
region and bucketname from credentials though, they are always passed in
so there is no reason why it can't be in the install command.
Having it there fixes some races where cluster creation fails because
the configmap does not exist yet because the operator didn't start yet.
Fixes #
**Checklist**
=> Move oidc configmap management back into install command

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
There are some build-related conformance tests[0] that currently extract
the apiserver url from the `oc status` command using a regeex that
termiantes on `443` which doesn't work when using port 6444. Work around
by defaulting to port 7443 instead.
[0]: https://github.com/openshift/origin/pull/26901
Fixes #
**Checklist**
=> Azure: Use an apiserver port that ends with 443 to make conformance tests happy

cmd/infra/azure/create.go
Presumambly due to eventual consistency on Azure, the role assignment
always needs some retries. Do not log an error for each retry, as that
looks like something went wrong which is not the case.
Fixes #
**Checklist**
=> Azure: Stop logging errors during role assignment retry

api/fixtures/example.go, api/v1alpha1/nodepool_types.go, cmd/cluster/azure/create.go, cmd/cluster/core/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, cmd/nodepool/azure/create.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/azure.go
This adds multi-az support to Azure, which is rather simple as the only
thing required is a config option on the nodepool. Not all locations
support AZs, so it is optional.
Ref https://issues.redhat.com/browse/HOSTEDCP-322
/cc @enxebre 
Fixes #
**Checklist**
=> Azure: Add multi-AZ support

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
Currently the ingress operator fails to properly perform canary health checks in the guest cluster if it does not have direct network access to the ingress subdomain in the guest cluster. This is not a guarentee to have since the management
cluster and guest cluster can run in a split network environment. This pr introduces the socks proxy which will allow the ingress operator to proxy these canary healthcheck https requests through konnectivity and ultimately into the guest cluster. This will allow the healthchecks to properly be executed in all environments and prevent Degragaded status reports on the ingress resource which can lead to customer concerns/tickets. Fixes: https://github.com/openshift/hypershift/issues/1130
Relevant logs:
```
2022-03-10T03:40:37.559Z	ERROR …
```
=> add konnectivity proxy sidecar to ingress-operator to ensure it can properly perform in cluster canary healthchecks

cmd/infra/azure/create.go
Right now, additional nodepools don't work because the location the HPO
expects for the image is not where the `create infra azure` command puts
it. This fixes that.
Fixes #
**Checklist**
=> Azure: Fix image name to match what HPO expects

control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
So it is possible to retrieve logs even when the SDN doesn't work, which
is helpful for debugging. The healthcheck address was changed to
localhost to avoid exposing a port.
Relevant slack discussion: https://coreos.slack.com/archives/C01C8502FMM/p1640019194217000
Fixes #
**Checklist**
=> Run the konnektivity agent DS with hostnetwork

cmd/install/assets/hypershift_operator.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-rollout.role.yaml, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Currently the control-plane-operator can escalate it's privileges as documented in this link: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#privilege-escalation-prevention-and-bootstrapping. This is due to the fact the control plane operator has escalate and bind privileges implicitly included due to the wildcard in the verb section. That means they can go and edit the rbac that gets assigned to it and increase it's scope. That ability should not be allowed and instead any necessary rbac should be explicitly granted to the control-plane-operator through the hypershift operator
Without these changes: RBAC is effectively useless on these operators as if you get access to the service account token you can just edit the RBAC roles and grant yourself or others additional …
=> prevent privilege esclation by explicitly not allowing the escalate and bind verbs with rbac on the control plane operator

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent_test.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go, hypershift-operator/controllers/hostedcluster/internal/platform/ibmcloud/ibmcloud.go, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go, hypershift-operator/controllers/hostedcluster/internal/platform/none/none.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go, hypershift-operator/controllers/util/util.go
Create role and rolebinding in agent namespace for each hostedcluster that wants to use this namespace
Cleanup the role and rolebinding in agent namespace upon hostedcluster deletion
Fixes #
**Checklist**
=> Agent: each hostedcluster provider should have it's own role and role binding in the agent namespace

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml
This PR should allow hypershift operator to grant RBAC permissions to the cpai-provider-agent so it can access agents
This used to work until https://github.com/openshift/hypershift/pull/1136
Note that we plan to remove the role in the agent namespace from hypershift management, but until we do (require changes in docs tests and code) this PR should allow the capi-provider-agent to keep working. 
https://issues.redhat.com/browse/MGMT-9635
**Checklist**
=> Alow hypershift operator to grant RBAC permissions to the cpai-provider-agent

api/fixtures/example.go, api/fixtures/example_agent.go, cmd/cluster/agent/create.go, docs/content/how-to/agent/create-agent-cluster.md, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent_test.go
Remove the role allowing capi-provider-agent to list agents on another namespace from hypershift management
Create the role during cluster create agent instead
Fixes # https://issues.redhat.com/browse/MGMT-9633
**Checklist**
=> Remove capi-provider-agent role from hypershift management

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go, support/images/envvars.go
Adds an image-refs flag to the install command that accepts an imagestream
YAML file that contains tags for images used by the HyperShift operator.
The images are then specified as environment variables on the hypershift
operator and propagated to the appropriate components.
Per-HostedCluster annotations still oveerride any operator-level environment
variables.
Fixes [HOSTEDCP-339](https://issues.redhat.com/browse/HOSTEDCP-339)
**Checklist**
=> Allow overriding images at the hypershift operator level

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/packageserver-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go, control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go, control-plane-operator/controllers/hostedcontrolplane/olm/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/olm/catalogs.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/olm/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Adds support for OLM catalog placement API for HostedCluster and HostedControlPlane. This will toggle the placement of OLM catalogs to be deployed on management cluster or guest cluster.
Fixes #1075
**Checklist**
=> feat(cpo): Support OLM catalog placement

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift_operator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/oauth/service.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/clusteroperators.go, control-plane-operator/main.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, support/events/message.go, support/events/message_test.go, vendor/k8s.io/apimachinery/pkg/util/duration/duration.go, vendor/modules.txt
Improves the reporting of HostedCluster status by surfacing
error conditions that can typically result from cloud provider errors.
- Adds a message column to the output of `oc get hostedclusters`
- Uses events to provide better status messages for the provisioning of
load balancer services and pvcs.
- Adds events as resources to watch in the CPO.
- Surfaces the more detailed messages in the Available condition of the
HostedCluster resource.
Because of limitations with status reporting from cloud providers, this
change is delegating implementation of part of our API (status conditions)
to component events which are not guaranteed to be emitted reliably and
are not persistent past the event's TTL. However, we still want to
experiment with the use of …
=> Surface cloud error conditions for HostedCluster resources

api/fixtures/example.go, api/v1alpha1/hostedcluster_types.go, cmd/cluster/aws/create.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift_operator.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, test/e2e/e2e_test.go
e2e support for external-dns and DNS indirection to HCP endpoints.
There is a new `--e2e.external-dns-domain` flag to support this.
Also has a separate commit for fixing remaining nits from #1145 
Fixes #
**Checklist**
=> e2e: support dns indirection

control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile_test.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/registry/registry.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, hack/ci/install-cnv.sh, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/globalconfig/infrastructure.go, test/e2e/create_cluster_test.go, test/e2e/util/kubevirt.go
Previously, Clusters using the KubeVirt platform would get stuck at a partial install. This was primarily due ingress routing failures which prevented console from working and also prevented guest cluster API access.
Our ingress issues are mostly resolved by switching from HostNetwork to NodePort for the guest cluster
s default ingress. Before this change, when we used HostNetwork for ingress, we didn't have a way to accurately select which VMs were running the HA proxy instances when routing default ingress traffic. This made it difficult to target the correct VMs when routing traffic. NodePort allows us to target all VMs when routing traffic.
By switching to NodePort for ingress and exposing the cluster API using routes and a LB ( #1032) we now have the ability to completely install an …
=> Switching KubeVirt platform's default ingress to NodePort

support/events/message_test.go
Fixes events message unit test
Events by reason are added to a map and their resulting order is unpredictable. Sorting result and expected removes differences in order
**Checklist**
=> Fix events message unit test flake

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This adds a label to the resource created in the hostedcluster namespace to allow for label queries on resources created in that namespace. The idea is to be able to have a query using label selectors to get all resources in the centralized hostedcluster namespace associated with a an individual hostedcluster. This is the one piece that is created in that namespace that the user does not have control over specifying labels on. This adds a label that can be utilized for the selector.
Fixes #
**Checklist**
=> add clusterid label to admin kubeconfig secret

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
The test is currently extremely slow and takes about 20 minutes with
`-race -count=25`. Improve that by pre-creating the secret that holds
the bcrypt hash of the kubeadm password, which makes the reconciliation
skip the calculation of said hash and brings the runtime with above
parameters down to ~20 seconds.
Needed for https://github.com/openshift/hypershift/pull/1166
Fixes #
**Checklist**
=> Resources: Improve runtime of test

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/proxy/reconciler.go, hypershift-operator/main.go, konnectivity-socks5-proxy/http_proxy.go, konnectivity-socks5-proxy/main.go, support/proxy/proxy.go, support/proxy/proxy_test.go, vendor/golang.org/x/net/internal/socks/client.go, vendor/golang.org/x/net/internal/socks/socks.go, vendor/golang.org/x/net/proxy/dial.go, vendor/golang.org/x/net/proxy/direct.go, vendor/golang.org/x/net/proxy/per_host.go, vendor/golang.org/x/net/proxy/proxy.go, vendor/golang.org/x/net/proxy/socks5.go, vendor/modules.txt
This change adds proxy support. It adds a small controler into the
hypershift operator that makes it update its own deployement
based on the proxy resource in the cluster. It further extends the
hypershift operator to pass on its proxy env vars onto the capi provider
and the CPO and the CPO to pass them on to the KAS, KCM and HCCO and
ignition server.
Lastly, the konnektivity-socks5-proxy is extended to not route a
hardcoded list of cloudprovider domains into konnektivity but use its
own proxy configuration for that (if any).
Ref https://issues.redhat.com/browse/HOSTEDCP-331 …
=> Add proxy support

Makefile
Periodics were broken by https://github.com/openshift/release/pull/27079 because the hypershift install step configures hypershift with private cluster support in some tests and not in others.
Unify the make targets so that hypershift is always installed with private cluster support.
Fixes #
**Checklist**
=> Unify hypershift install make targets

.ko.yaml
Before this commit, images built with `ko` used a base image that included
no debugging/userland tools. This commit updates the base image to use the
"debug" variant of the base image which is nominally larger but includes
a busybox userland, which is far more useful by default for a low cost.
=> dev: specify a more useful `ko` base image

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Productized images will require the cluster's pull secret to be pulled
from the registry.
This commit updates the reconciliation of service accounts to include
the pull secret if they don't already do so.
Fixes #
**Checklist**
=> Ensure that all control plane pods use the cluster's pull secret

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go
Remove CAPI-provider-agent ClusterRole from hypershift Agent platform
Alow hypershift operator to grant RBAC permissions for clusterdeployments and agentClusterInstalls to the cpai-provider-agent
Fixes # https://issues.redhat.com/browse/MGMT-9591, https://issues.redhat.com/browse/MGMT-9674
**Checklist**
=> Remove CAPI-provider-agent ClusterRole from hypershift Agent platform

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
This increase the workers for the hostedcluster operator to 10 (from 1)
and for the nodepool controller to 30 (also from 1). Otherwise the
workers become a bottleneck if more than one hostedcluster is changed at
a time.
Both the 10 workers and the 30 workers are relatively arbitrary chosen,
these numbers might need revisiting in the future or even warrant a
config option.
Fixes #
**Checklist**
=> Hypershift-operator: Increase worker count

api/v1alpha1/hosted_controlplane.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
Previous versions of control plane operators have no knowledge of new
fields added to the HostedControlPlane resource. In order to maintain
backwards compatibility we cannot add any required fields to the
HostedControlPlane type.
This change makes the `clusterID` field optional to maintain
compatibility with previous control-plane-operators.
**Checklist**
=> Make clusterID optional in HostedControlPlane clusterID

control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go
This is another source of flakes in the periodics: `olm-operator` and `catalog-operator` container restarts.
This happens because the availability prober blocks main container start until the guest KAS is up, but does not check if the CRDs that OLM components will watch are also installed.  Thus the container starts but the component is unable to establish watches on the CRDs until they are installed into the guest cluster by the CVO.  During this time, the liveness probe is failing.  If the watches can not be established within 30s (failureThreshold: 30, period: 10), the container is killed and restarted, resulting in a test failure.
This PR does two things to prevent this:
- `availability-prober` init container now waits for one of the OLM CRDs to be available before allowing the main …
=> Fix OLM container restart flakes in CI

test/e2e/util/util.go
Periodic is failing with budgets still being to tight and enabling private clusters increased API calls
Fixes #
**Checklist**
=> e2e: adjust budgets

api/v1alpha1/hostedcluster_types.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This commit introduces a new `OIDCConfigurationInvalid` condition for
HostedCluster. If OIDC documents cannot be reconciled for a cluster,
`OIDCConfigurationInvalid=True`, otherwise `OIDCConfigurationInvalid` is
removed. The message associated with the condition tries to provide some more
helpful context about what might be wrong to help the user correct the issue.
More error interpretation can be added in the future.
=> Introduce `OIDCConfigurationInvalid` condition for OIDC setup validation

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
This seems to make the apiserver unable to reach anything over
konnektivity. Not completely sure why this happens, probably because it
ends up having the proxy ip address for everything (that is
speculation).
Just skip setting any proxy env vars, the few requests the KAS does can
go through the guest cluster.
Fixes #
**Checklist**
=> KAS: Never set proxy

Dockerfile, Makefile, availability-prober/availability_prober.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/kas/aws_kms.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/packageserver-deployment.yaml, control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go, hypershift-operator/main.go, ignition-server/main.go, konnectivity-socks5-proxy/http_proxy.go, konnectivity-socks5-proxy/main.go, support/util/cloudprovidercreds.go, support/util/containers.go, token-minter/tokenminter.go
This makes them part of the payload and thus avoids rotating most of the
controlplane when the hypershift operator gets updated.
Ref https://github.com/openshift/hypershift/issues/1156
This will break running with a CPO from release-4.10, I will submit a forwarding PR for that once this merges.
/cc @relyt0925 @csrwng 
Fixes https://github.com/openshift/hypershift/issues/1156
Fixes #
**Checklist**
=> Converge helper binaries and ignition-server into CPO binary

.ko.yaml, docs/content/contribute/develop-in-cluster.md
This commit removes outdated binary entries from `ko.yaml` for those
which have been collapsed into `control-plane-operator` and updates
the in-cluster ignition server developer documentation to reflect
those changes.
=> Fix `ko` entries and update ignition-server dev docs

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go
Still seeing CI flakes where informer caches timeout on their watches for types the CVO has not yet installed
Fixes #
**Checklist**
=> add required-api to availablity prober for OLM and HCCO

.gitleaks.toml, control-plane-operator/controllers/hostedcontrolplane/pki/ca.go, control-plane-operator/controllers/hostedcontrolplane/pki/cert_test.go, control-plane-operator/controllers/hostedcontrolplane/pki/sa.go, control-plane-operator/controllers/hostedcontrolplane/pki/util.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/certs/tls.go, support/certs/tls_test.go
This reverts https://github.com/openshift/hypershift/pull/1167
The console stopped working after this with `ERR_SSL_VERSION_OR_CIPHER_MISMATCH`.  Root cause is yet unknown but we need to get back to working.  We should also stay aligned with standalone OCP on this.
Fixes #
**Checklist**
=> Revert "PKI: Use ECDSA keys by default"

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This is completely expected during deletion, logging it at error level
makes it look like an issue, which it is not.
Fixes #
**Checklist**
=> HO: Don't report NotFund for hostedcluster as error

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
The KAS needs the proxy settings to communicate with the cloud provider.
However, the egress transport it uses wraps another transport that
respects proxy settings which is why we need to excempt pod and service
CIDR of the guest cluster to not break Konnektivity.
I also tried to stop using the egress config and use the
konnektivity-socks5-proxy, but that breaks SPDY connections (exec,
port-forward).
I manually verified that all of exec, logs, apiservices and conformance tests that require the KAS to connect to the cloudprovider work. 
/cc @csrwng 
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, …
=> KAS: Set proxy, but exempt pod and service CIDR

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, hypershift-operator/controllers/platform/aws/controller.go
AWSEndpointService related reconciliations make AWS calls which can delay for an arbitrary amount of time.
~~In general, we should should not have controllers with the default `MaxConcurrentReconciles` of `1` unless we are certain the reconcile can be done in a short and relatively constant time.~~
Expansion on #1181 
Fixes #
**Checklist**
=> sync MaxConcurrentReconciles across all controllers

cmd/install/assets/hypershift_operator.go
Without the registry, external-dns from different management clusters with stomp each other's record.  In order to avoid this we need to enable the TXT record based registry.  However, we can't create a TXT record with the same name as a CNAME.  We also need a unique TXT owner id so each instance of external-dns in each management cluster can identify the records it should sync.
This PR enables the registry and sets a `-external-dns` suffix to be added to TXT record to avoid conflict with the CNAME records created for Routes.  It also sets the TXT owner-id to a generated UUID to identify a particular external-dns instance operating in a shared public zone.
Required before https://github.com/openshift/hypershift/pull/1163 …
=> enable external-dns registry

control-plane-operator/hostedclusterconfigoperator/controllers/resources/registry/registry.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
In its current state, the hosted cluster config operator overwrites any
changes made by the guest cluster admin to the registry configuration.
This prevents changes like enabling a route or increasing the number of
replicas.
This commit limits what we change to things we need to change and leave
everything else as is.
**Checklist**
=> Registry configuration: reconcile only what we need to changes

control-plane-operator/hostedclusterconfigoperator/controllers/resources/network/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/network/reconcile_test.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/operator/config.go
This solves an issue we've been seeing in our e2e tests where the KubeVirt platform's console ingress occasionally fails.
Nested OpenShiftSDN requires unique vxlan ports for the nested layers or else connectivity breaks at the nested layer. This impacts the KubeVirt Hypershift platform because the KubeVirt VMs are running in OpenShiftSDN in the management cluster, and there's another layer of OpenShiftSDN running within the KubeVirt VM worker nodes themselves.
To work around this, when the KubeVirt platform is in use and the OpenShiftSDN network type is being used, we set a unique vxlan port that's different than the default 4789. I picked 9879 for the nested vxlan because it's an unregistered port in the IANA user range. In the future we can consider making this port configurable if we …
=> Unique OpenShift vxlan port for KubeVirt Platform

api/fixtures/example.go, api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift_operator.go, cmd/install/assets/hypershift_operator_test.go, cmd/install/install.go, control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/mcs/params.go, control-plane-operator/controllers/hostedcontrolplane/mcs/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/pki.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/controlplaneoperator/manifests.go, support/util/volumes.go
This adds initial support for a new HostedCluster API `additionalTrustBundle` which allows user provided CA certs to be provided, similar to the [standalone installer](https://github.com/openshift/installer/blob/master/docs/user/customization.md#platform-customization)
This is useful when you want to use a local container registry that uses a self-signed cert - this is a common scenario for developing on-prem scenarios, particularly disconnected and ipv6 where access to an upstream registry is not possible.
The expected usage is to reference a local object reference, e.g `ConfigMap` in the `clusters` namespace:
```
spec:
additionalTrustBundle:
name: user-ca-bundle
```
If the management cluster already contains such a ConfigMap, it may be copied from the `openshift-config` namespace, e.g: …
=> Add support for AdditionalTrustBundle

control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/params.go
This PR enables to load apiserver-network-proxy image from OCP release payload only if its available. if image is not available in the OCP release image, its uses default override method.
What this PR does / why we need it:
apiserver-network-proxy image is available in ocp 4.11 reelase iamge. so we can read it from payload.
fixes # https://issues.redhat.com/browse/HOSTEDCP-301
=> read apiserver-network-proxy image from ocp payload

docs/content/how-to/kubevirt/create-kubevirt-cluster.md
This PR adds documenting outlining how to get ingress to work properly the Hypershift KubeVirt platform.
I lay out two options here.
- Option 1: Re-use the mgmt cluster's DNS/Ingress by making hypershift kubevirt cluster a subdomain of the mgmt cluster
- Option 2: Create a new LoadBalancer and DNS entry which routes to the hypershift kubevirt cluster.
It's possible we might consider automating option 1 in the future as the default for users as the default behavior when no base domain is configured, but we're still investigating if option 1 is viable for production. Option 2 gives users more control, but requires that they have the ability to create a LoadBalancer and the ability to configure DNS.
=> Document KubeVirt Platform Ingress Setup

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/util/deployment.go, support/releaseinfo/fake/fake.go
These components watch both management cluster (Machine scalable resources) and guest cluster.
Originally we were pinning the images to a version that would cross any HostedCluster.
This PR let us pick them from each particular payload resulting in some benefits:
- Each hostedCluster runs the component version that was tested with that particular kube/ocp version
- No additional work needed to productise the images as they com from the payload.
Since CAPI CRDs should be backward compatible, having different controller versions shouldn't cause an issue.
Once the CAPI image is in the payload we can do the same for it.
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might …
=> Get autoscaler/machine-approver images from the payload

test/e2e/util/util.go
Before this commit, calls to `WaitForConditionsOnHostedControlPlane()` could
fail a test if an API lookup fails even though that lookup is recoverable and
retried automatically. This made the test flaky.
This commit fixes the code so that these retriable errors are logged but do
not fail the test.
This commit also moves a log message which was intended to emit during retries
but was instead placed at the exit point.
=> e2e: Don't fail test on transient recoverable API lookup

control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-collect-profiles.cronjob.yaml, test/e2e/control_plane_upgrade_test.go, test/e2e/util/util.go
The olm cronjob had a prioryClass of openshift-user-critical which has a
priority that is above all other controlplane components in the
management cluster. Downgrade it to the standard
hypershift-control-plane and add an e2e test that verifies that no pod
has a priority higher than the etcd priority.
Fixes https://github.com/openshift/hypershift/issues/1223
Fixes #
**Checklist**
=> Fix priority class for olm cronjob and verify priorityclasses in e2e

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
We are getting 404 delete on this `ClusterRoleBinding` because of rapid reconciliation of HostedClusters during their deletion.
I think that this will fix it in a hacky way, plus there is no need to wait for the deletion of this resource.
Fixes #
**Checklist**
=> Do not wait on capi clusterrolebinding delete

api/fixtures/example.go, cmd/cluster/aws/create.go, cmd/cluster/core/create.go, cmd/infra/aws/create.go, cmd/infra/aws/destroy.go, cmd/infra/aws/ec2.go, control-plane-operator/controllers/hostedcontrolplane/mcs/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, support/globalconfig/proxy.go
This change:
* Adds a new --enable-proxy flag to the create aws infra command
which will create a http proxy instance if set
* It will also cause a proxy config pointing to said instance to be
added to the HostedCluster
* Extends the globalconfig package to optionally be able to set the
status of a proxy config, including additional no_proxy hosts
* Makes the nodepool controllers userdata secret generation consider a
proxy config if preset
* Makes the ignition config rendering use a proxy config with status
set, as otherwise the proxy config will be ignored
* Makes the aws infra destroy command also  clean up instances to not
get blocked by the proxy instance …
=> Add support to set up a http proxy for guest clusters

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/oauth/route.go, control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/config/constants.go, support/util/route.go, support/util/route_test.go
When using a long name for a cluster namespace, the routes that the
control plane operator creates is invalid because a segment of the
domain name has a length > 63 chars.
This commit sets the host name for routes to ensure that the resulting
host name is valid. Modification of the route hostname only happens when
the resulting hostname will be invalid. The name is shortened by
trimming the original name and appending a hash of the entire name,
resulting in repeatable and distinct names every time the name is
shortened.
Fixes # [HOSTEDCP-371](https://issues.redhat.com/browse/HOSTEDCP-371)
**Checklist**
=> Create valid route names with long namespace names

api/v1alpha1/nodepool_types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
This PR signal invalid cluster config in a HC condition. It also do the same for NodePools and refactors to narrow down the reconcileUserdata signature and let it only use what it takes.
ref https://issues.redhat.com/browse/HOSTEDCP-380
**Checklist**
=> Signal parsing config failure in a condition

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/config.go
This is enabled by default in 4.11/kube 1.23 which breaks a bunch of
networking tests that want to create privileged pods which the default
`Restricted` policty doesn't allow.
Do the same as the kas-operator and disable it.
Fixes #
**Checklist**
=> Disable PodSecurity admission in 4.11 as it breaks conformance

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This change ensures the following five services have `imagePullPolicies` set to `IfNotPresent` for better tolerance of networking outages:
```
cluster-api 
control-plane-operator
hosted-cluster-config-operator
konnectivity-agent
konnectivity-server
```
Issue - https://github.com/openshift/hypershift/issues/1182
**Checklist**
=> ensure imagePullPolicies are IfNotPresent for some deployments

cmd/infra/aws/destroy.go
In the case where the nodepool didn't create any instances this
list can be empty on destroy, which causes an error like:
missing required field, TerminateInstancesInput.InstanceIds
This causes the destroy to get stuck, so instead handle the
case where the list is empty.
=> AWS infra destroy, handle empty instanceIDs

Dockerfile, Dockerfile.control-plane, control-plane-operator/main.go, go.mod, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go, hypershift-operator/main.go, support/util/imagemetadata.go
Adds symlinks in HyperShift operator image for previously standalone
utilities and enables the control plane operator to invoke the right
command based on the symlink it was invoked with.
Checks whether the CPO for a given cluster includes subcommands for
utilities by checking the labels on the CPO image, and only uses the
CPO image for utilities if it does include the labels.
**Checklist**
=> Make HyperShift operator compatible with previous CPOs without utilities

hypershift-operator/controllers/util/deployment.go, hypershift-operator/controllers/util/deployment_test.go
The release image annotation should also be added to the pod template annotation so it is reflected on the pods that are scheduled from the deployment. This is necessary from a monitoring perspective and for detection in IBM Cloud's deployment process to ensure rollouts complete on a release image update
Fixes #
**Checklist**
=> ensure release image annotation added to deployment template metadata  to enable proper detection in IBM Cloud deployment process

Makefile, api/v1alpha1/hostedcluster_webhook.go, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, hack/app-sre/saas_template.yaml, hypershift-operator/main.go
This PR adds a validating webhook to the `hypershift-operator` for the `HostedCluster` type
This allows enforcement of immutable fields on the `HostedCluster` spec.
Creation of the `ValidatingWebhookConfiguration` can be disabled on the `hypershift install` CLI with the `--disable-webhook` flag.
Fixes #
**Checklist**
=> Add validating webhook for HostedClusters

control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/oauth.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/oauth/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/oauth/reconcile_test.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
This adds rbac that allows authenticated users to fetch the oauth-serving-cert configmap. This is necessary for the oauth proxies in the openshift-monitoring namespace to work and allow users access to the prometheus/grafana/alertmanager dashboards.
Without it accessing prometheus dashboard directly fails with
Fixes #
**Checklist**
=> reconcile oauth serving cert rbac to allow oauth proxies in the openshift-monitoring namespace to work

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/controlplaneoperator/manifests.go
Adds a service account signing key to the HostedCluster spec. If specified,
we skip reconciling discovery documents to an S3 bucket.
This allows consumers of our API to generate their own signing key and
place OIDC discovery documents wherever they like.
Fixes # [HOSTEDCP-374](https://issues.redhat.com//browse/HOSTEDCP-374)
**Checklist**
=> Expose a service account signing key in the API

cmd/cluster/core/create.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, test/e2e/e2e_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/util/util.go
This commit adds an e2e test which exercises a simple NodePool upgrade
using a SingleReplica cluster.
=> e2e: Add a nodepool upgrade test

hypershift-operator/main.go
HostedCluster `spec.infraID` can be defaulted by the HO if not set at create time.
Also incorporated feedback from https://github.com/openshift/hypershift/pull/1262#issuecomment-1097136978
Fixes #
**Checklist**
=> exclude InfraID from immutability check

control-plane-operator/controllers/hostedcontrolplane/kas/aws_kms.go
When we switched utilities to be subcommands of control-plane-operator
the flag format changed to require `--` instead of `-`. We missed
changing the token minter container that gets added when using AWS KMS
etcd encryption. This change fixes that.
Fixes # [HOSTEDCP-385](https://issues.redhat.com//browse/HOSTEDCP-385)
**Checklist**
=> Use '--' for flags in kms token minter container

control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/params.go
The konnektivity DS already runs with hostnetwork in order to be up even
if CNI doesn't come up. It currently ends up not being scheduled in that
situation though, because it doesn't tolerate the not-ready taint.
Make it tolerate all tains, as this is very helpful especially when CNI
doesn't come up.
Fixes #
**Checklist**
=> konnectivity ds: Tolerate all taints

test/e2e/util/util.go
After https://github.com/openshift/hypershift/pull/1257 and https://github.com/openshift/hypershift/pull/1260, we need to update the e2e budgets for the shared hypershift-operator across tests.
Fixes #
**Checklist**
=> e2e: update HO budgets

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go
When using Calico and upgrading from 4.10 to 4.11 where the CNO runs in
the control plane, we need to make sure we remove the in-cluster CNO
deployment and RBAC.
**Checklist**
=> Add cleanup manifest for existing CNO

support/globalconfig/infrastructure.go
The machine-config-operator had some left over logic from the old KubeVirt IPI effort that broke the KubeVirt Hypershift platform. This caused us to have to temporarily report the `None` platform on the infrastructure object. Otherwise we'd get a bunch of coredns and other networking related changes layered in that are no longer relevant for kubevirt+hypershift.
I updated the mco [here](https://github.com/openshift/machine-config-operator/pull/3084) to strip out the old KubeVirt IPI logic but leave the KubeVirt platform intact. Now we can remove the weird workaround where we used `none`. This is important because it's needed for us to begin integrating logic into the cso for the kubevirt-csi driver install.
=> Begin using KubeVirt as the infrastructure platform instead of None

api/v1alpha1/nodepool_types.go, hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/inplace_test.go, hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
Adds inplace upgrade logic to the nodepool controller that will,
upon seeing a new machineconfig or release image, do the following:
- create a upgrade namespace
- create a configmap, which contains the new rendered config fetched
from the ignition server endpoint
- create pods to perform the upgrade, and write necessary annotations
- delete the pods and update nodepool status when done
This commit should be in a state that is ci-testable, with the caveat
that the MCD image used is being built from an external quay location.
The TODOs are as following:
- Create CI for Hypershift and MCO repos
- Add drain logic to the controller
- Add disruptionless updates (and consider cert rotation)
- Delete manifests (currently only pods are deleted)
- Honour maxUnavailable
- Harden logic for multiple …
=> inplace upgrade: add initial upgrade logic

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator_test.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/util/public.go, support/util/public_test.go
The CNO currently never proxies the apisever address. In case of public
Hypershift clusters it needs to do that though, so configure it
accordingly.
Basically integrates https://github.com/openshift/cluster-network-operator/pull/1381
Fixes #
**Checklist**
=> Configure the CNO to proxy the apiserver for public clusters

api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
Drop TODO for supporting container runtime and kubelet config in NodePool MachineConfigs since This is supported now https://github.com/openshift/machine-config-operator/blob/1af0a6f96fc7c0f44230293ac026a96acb0da512/pkg/controller/bootstrap/bootstrap.go\#L117-L119.
Fixes #
**Checklist**
=> Drop outdated TODO for machine configs

control-plane-operator/controllers/hostedcontrolplane/kas/config.go
Explicitly disable PodSecurity for 4.10 to be inline with OCP KAS config.
https://github.com/openshift/cluster-kube-apiserver-operator/blob/release-4.10/bindata/assets/config/defaultconfig.yaml#L46
N/A
**Checklist**
=> feat(cpo): Disable PodSecurity for 4.10

cmd/cluster/core/destroy.go, test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/chaos_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/util/fixture.go
This change makes the platform used during e2e tests configurable
(defaulting to AWS for compatibility) and adds additional flags so they
can be executed against Azure.
Ref https://issues.redhat.com/browse/HOSTEDCP-243
Fixes #
**Checklist**
=> Allow running e2e tests for azure

hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
Noticed this when working on
https://issues.redhat.com/browse/HOSTEDCP-243
Fixes #
**Checklist**
=> Add missing resource requests for Azure CAPI provider

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Currently, Azure 4.11 clusters never get ready because the storage driver doesn't get ready because the CSI driver pods don't start because their cloud secret is missing, see e.G. here: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-e2e-conformance-azure/1517382725126852608
This fixes that
Fixes #
**Checklist**
=> Azure: Add missing csi driver secret

control-plane-operator/hostedclusterconfigoperator/controllers/resources/network/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/network/reconcile_test.go, test/e2e/create_cluster_test.go
The KubeVirt Hypershift platform is running worker nodes as VMs hosted in an infra OCP cluster. When both the infra and tenant OCP clusters use OVNKubernetes, we have an environment where an OVN network is "nested" inside an OVN network.
By default, the geneve port used for the nested tenant cluster's OVN network will collide with the same port used by the infra cluster's OVN network. This collision causes traffic issues within the tenant clusters.
To account for this, we use a different geneve port for KubeVirt platform hosted clusters. This is similar in concept to what we had to do for vxlan ports when OpenshiftSDN is in use.
=> Update KubeVirt platform to work with OVNKubernetes

control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/ignitionserver/manifests.go, ignition-server/cmd/run_local_ignitionprovider.go, ignition-server/cmd/start.go, ignition-server/controllers/cache.go, ignition-server/controllers/local_ignitionprovider.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/main.go, support/releaseinfo/registryclient/client.go, test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/chaos_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go
Before this commit, ignition payloads for nodepools were generated by
orchestrating MCO components using pods. This was a performance problem because
ignition server restarts (e.g. during upgrades) resulted in thundering herds of
ignition payload generation pods, limiting overall cluster capacity.
This commit refactors ignition payload generation away from pods and to a
mechanism that extracts MCO binaries (and supporting files) from release
payloads so they can be forked as subprocesses of the ignition server
controller, removing all pod scheduling overhead. This change should be
completely transparent to the end user and is a drop-in replacement for the old
implementation.
The current implementation has the following limitations:
* Extracted …
=> Use forked processes instead of pods to generate ignition payload

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Currently there is a race condition in IBMCloud deployments where if hypershift initializes the registry config before the managed service operation has a chance to properly initialize the registry config: It will result in a bad initial config that will cause the cluster-image-registry operator to crash and lead to tickets. For IBMCloud deployments: the initialization of this config should be delegated to the managed service to do the initalization so this does not occur. From there: the user can edit however they like in line with upstream openshift
Fixes #
**Checklist**
=> disable reconcile of registry config in IBMCloud deployments

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/params_test.go
Currently the KubeAPIServerParams are constructed with the API Server
address from the HCP status. This modifies reconciliation to use the
InfraStatus to obtain the API Server address.
Fixes #
**Checklist**
=>  Use apiserver host/port from InfraStatus in reconciling Kube API Server

test/e2e/create_cluster_test.go, test/e2e/e2e_test.go
We're encountering some issues with flaky tests on the kubevirt platform. There are two issues here that this PR addresses.
1. We need the ability to alter the guest memory used for the worker nodes in the prow configs. We're seeing in 4.11 that some of the default OCP components can't start on the worker nodes due to lack of memory. This is addressed by the new `e2e.kubevirt-node-memory` e2e test cli option
2. Running OVNKubernetes as the network overlay in the worker nodes is flaky at the moment. I'm investigating this, but for now I think we should switch back to the e2e default which uses the SDN.
=> Reduce KubeVirt e2e test flakiness

Makefile, cmd/install/assets/hypershift_operator.go, cmd/install/assets/hypershift_operator_test.go, cmd/install/install.go, cmd/install/install_render.go, cmd/install/install_test.go, hack/app-sre/saas_template.yaml
Add `hypershift install` options `--aws-private-secret` and `--aws-private-secret-key` to specify an existing Kubernetes secret and key name for the AWS shared credentials file. The existing `--aws-private-creds` flag (which creates the secret on the user's behalf) is unaffected. These options are helpful in scenarios when the secret is provided by other means. Also, when the installation template is rendered to a file, it should not contain secrets.
The template generated by `hypershift install render --template` was changed to provide parameters for those CLI options, namely `AWS_PRIVATE_REGION`, `AWS_PRIVATE_CREDS_SECRET` and `AWS_PRIVATE_CREDS_SECRET_KEY`.
A similar change has been implemented for the OIDC bucket credentials secret in …
=> install: enable user provided AWS credentials secret

api/fixtures/example.go, api/v1alpha1/nodepool_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, cmd/nodepool/core/create.go, docs/content/how-to/agent/create-agent-cluster.md, docs/content/how-to/none/create-none-cluster.md, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/aws_test.go, hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/kubevirt_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, test/e2e/autoscaling_test.go, test/e2e/create_cluster_test.go, test/e2e/util/util.go
Every other kube api that manages identical things uses a field named
replicas to denote the number of replicas, rather than $thingCount.
Stick to that convention.
This change is limited to the Hypershift operator, so it won't break
compatibility with an older CPO.
Fixes #
**Checklist**
=> Rename nodepool.spec.nodeCount to replicas

cmd/install/assets/recordingrules/hypershift.yaml, hack/app-sre/saas_template.yaml, test/e2e/util/util.go
Before this commit, the `ign_server_payload_generation_seconds` metric was not
being accounted for in the e2e metrics budget assertions, which led to us
failing to detect a possible performance regression on AWS with the new ignition
payload generation implementation.
This commit adds a recording rule for `ign_server_payload_generation_seconds`
(to ensure the metric is exported), and also implements a budget check in the
e2e fixture. For now, the budget is a p90 expectation of 45 seconds for payload
generation, which is very probably conservative. We've observed an intermittent
8 minute value in one known e2e test case that hasn't yet been reproduced. We
should adjust the histogram bucket and budget once we have more data around the
implementation's real world performance.
Hopefully this …
=> Export `ign_server_payload_generation_seconds` metric and add e2e budget

test/e2e/util/util.go
This should help find issues in kubeconfig generation and name resolution failures/delays
Fixes #
**Checklist**
=> e2e: log the error when failing to connect to the guest KAS

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Exposes the OAuth URL to clients of the HostedCluster API. This URL
is used in configuring identity providers such as Github that require
an OAuth callback URL.
**Checklist**
=> Add OAuthURL to HostedCluster status

hypershift-operator/main.go, hypershift-operator/main_test.go, vendor/modules.txt, vendor/sigs.k8s.io/controller-runtime/pkg/cache/informertest/fake_cache.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/doc.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/testing.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/unconventionallisttypecrd.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/util.go
Currently, tests on an Azure management cluster always fail when the
webhook is enabled, because it rejects the apiserver port defaulting
request.
/assign @sjenning 
Fixes #
**Checklist**
=> Fix webhook to allow apiserver port defaulting and add tests

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
CPO will get starved under CPU contention with 1m of CPU.  Additionally, CI metrics show the CPO uses ~80Mi of memory, not 44Mi.
Fixes #
**Checklist**
=> adjust CPO resource requests

hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/inplace_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, ignition-server/controllers/tokensecret_controller.go, test/e2e/nodepool_upgrade_test.go, test/e2e/util/util.go
Enables e2e test for in place upgrades https://github.com/openshift/hypershift/pull/1258 so any follow up will be test driven.
As part of getting the test green this PR moves from querying the ign server to store the payload in the secret token so it can be consumed by the in place upgrade process. Otherwiswe the ign server is not reachable form the NodePool controller in private topologies.
ref https://issues.redhat.com/browse/HOSTEDCP-402
Follow ups:
https://issues.redhat.com/browse/HOSTEDCP-417
https://issues.redhat.com/browse/HOSTEDCP-403 …
=> Add test for NodePools in place upgrades

hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go, hypershift-operator/main.go
This give us the ability to:
Scope different webhooks to packages/files so the main does not grow indefinitely.
Reusing controller runtime interface.
Drop unnecessary existing logic in main.
Give a consistent way to share validation logic from controllers which does not necessarily need to be exported.
i.e Sustainable code structure.
Since we want to implement the CR outside the the API package we create a mock Webhook struct for HostedCluster.
Fixes #
**Checklist**
=> Change webhook to implement webhook.CustomValidator

control-plane-operator/controllers/hostedapicache/cache.go
Fixes panic at https://github.com/openshift/hypershift/blob/aa2c387cc511ca83b6c7b4af120928b32f5eb654/control-plane-operator/controllers/hostedapicache/cache.go#L193
`h.cache` is nil because `destroy()` was called on it from `controller.secret`
CPO logs
```
{"level":"info","ts":"2022-05-05T09:58:23-05:00","logger":"hosted-api-cache","msg":"rebuilt api cache"}
{"level":"info","ts":"2022-05-05T09:58:23-05:00","logger":"controller.secret","msg":"destroying hosted API cache because kubeconfig secret is missing","reconciler group":"","reconciler kind":"Secret","name":"admin-kubeconfig","namespace":"clusters-sjenning-example"}
```
Passing `h.cache` to the goroutine while still holding the lock fixes this.
**Which issue(s) this PR fixes** *(optional, use …
=> fix panic due to race on hosted API cache start

cmd/install/install_render.go, hack/app-sre/saas_template.yaml
The app-sre template is currently mixing the AWS region and the credential secret name
N/A
**Checklist**
=> fix the region parameter in app-sre templates

ignition-server/cmd/start.go
We should only be using strong ciphers in hypershift components. By default Go includes medieum strength ciphers in the default tls config. This adjusts to only be strong ciphers (TLS 1.2 and TLS 1.3)
Fixes #
**Checklist**
=> configure cipher suites to prevent using medium strength ssl ciphers

test/e2e/e2e_test.go
We currently hardcode the network type to SDN. This changes this to not
hardcode anything and instead use the same defaulting that is also used
when creating a cluster through the CI. Additionally, an option is added
to explicitly set the network type.
Fixes #
**Checklist**
=> E2E: Stop hardcoding network type

support/metrics/sets.go
This was removed in https://github.com/openshift/hypershift/pull/1294
and makes the conformance tests fail, which use this metric to guard
against excessive leader changes.
Fixes #
**Checklist**
=> Etcd: Keep etcd_server_leader_changes_seen_total metric

control-plane-operator/hostedclusterconfigoperator/cmd.go, control-plane-operator/hostedclusterconfigoperator/operator/config.go, hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, support/labelenforcingclient/labelenforcer.go, support/labelenforcingclient/labelenforcer_test.go
This drastically reduces the api requests the nodepool in-place
upgrading does to the guest cluster KAS by:
* Reading from a cache instead of the api. This caused the follow-up
problem that it results in a cache for pods and configmaps being
created, as we request those through the client. To not cache
everything there, we use the same approach as in the HCCO: We enforce
a label on create/update at the client level and use a label selector
on the cache. The only exception for this are Nodes, as we don't
create those
* Cache the client together with the cache: Client creation results in
api discovery, which does a good ~50 api requests. Cache the client to
avoid this
* Key the cache by hostedcluster instead of nodepool: Currently, the
cache is keyed and lifecycled by nodepool, resulting in …
=> Nodepool in-place upgrade: Reduce api requests

api/fixtures/example_kubevirt.go, api/v1alpha1/nodepool_types.go, cmd/cluster/kubevirt/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/kubevirt.go, hypershift-operator/controllers/nodepool/kubevirt_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, test/e2e/e2e_test.go
This PR makes the KubeVirt `ContainerDisk` value on the NodePool optional. When no disk is explicitly defined on the nodepool the nodepool controller will automatically detect a disk for KubeVirt using the x86 OpenStack qcow2 image found in the release payload.
The OpenStack image is compatible with KubeVirt, however in the future we plan to ship our own KubeVirt specific image. Once that new KubeVirt image is introduced into the payload, we'll transition this logic to attempt to detect the kubevirt image first, then fall back to the openstack image if necessary.
=> Autodetect KubeVirt disk image using release payload

hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go
I'm working to make the KubeVirt provider work with the generic e2e tests and noticed we are missing resource requests on the capk container (which causes e2e to fail)
=> Add resource requests to cluster-api-provider-kubevirt container

hypershift-operator/controllers/platform/aws/controller.go, hypershift-operator/controllers/platform/aws/controller_test.go
This makes sure that deletion of a management cluster cleans up the
endpoint services. Otherwise they will block the management cluster deletion.
Fixes #
**Checklist**
=> Tag endpoint services with the mgmt cluster infra ID

docs/content/how-to/kubevirt/create-kubevirt-cluster.md
RHCOS disk images are now auto-detected for KubeVirt, so there's no requirement to specify the disk during cluster creation anymore. 
This updates the docs to reflect the new change.
=> Update KubeVirt Doc to indicate RHCOS is no longer a required cli arg

Makefile
Before this commit, e2e test parallelism was limited to the default of
`GOMAXPROCS`, which was causing some of our tests to pause execution
so long that the tests can time out, even though those tests could have
executed in parallel.
This commit increases the parallelism limit so that all our tests run
in parallel.
=> e2e: Increase parallel test limit

test/e2e/util/util.go
Now that periodic are running to completion again (HO is operating for longer), we are running right up against the HO mutate limit.  This temporarily raises the HO mutate budget and should be readjusted after the in-place node upgrade refactor lands and we aren't talking to the guest KAS anymore.
Fixes #
**Checklist**
=> test: adjust HO mutate budget

cmd/cluster/core/dump.go
When debugging the KubeVirt platform, it would be helpful to have access to the KubeVirt capi objects as well as routes within the hosted cluster's namespace.
=> Add more resources to hypershift dump cmd

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, hack/app-sre/saas_template.yaml
This fields are propagated to the HCP and its backend defaults behaviour when they are empty.
Default behaviour should explicit signaled by the API so we provide a consistent UX and we avoid the posibility of breaking the API policy transparently by chaging backend behaviour.
Fixes #
**Checklist**
=> Add sane defaults for InfrastructureAvailabilityPolicy and ControllerAvailabilityPolicy

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/manifests/aws.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/pki/aws_pod_identity_webhook.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/aws_pod_identity_webhook.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, support/upsert/upsert.go
This change makes us deploy the AWS Pod Identity Webhook in the
management cluster for AWS clusters. It is comprised of:
* Deploying the webhook as sidecar to the KAS for AWS clusters: Why
sidecar? Because that is both the easiest and fastest, as we avoid a
bunch of network hops
* Minting a serving cert for the webhook
* Minging a kubeconfig for the webhook
* Setting up rbac for the kubeconfig
* Setting up the MutatignWebhookconfiguration
Sample usage:
Create a ServiceAccount with sts annotations:
```yaml
apiVersion: v1
imagePullSecrets:
- name: default-dockercfg-64n54
kind: ServiceAccount
metadata:
annotations:
eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/s3-reader
eks.amazonaws.com/token-expiration: "86400"
creationTimestamp: "2022-05-05T17:19:03Z"
name: default
namespace: …
```
=> AWS: Deploy Pod Identity Webhook

ignition-server/cmd/start.go, test/e2e/util/util.go
This fixes a racing issue between the payload being available in the ign-server and any machine requesting it and being able to boot.
Let's follow the path of *-7b2b7-us-east-1b-e731d66e which is the token secret referenced by a MachinSet which Machine was unable to boot.
The payload is generated at 2022-05-18T12:39:39Z","msg":"got ignition payload
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_hypershift/1399/pull-ci-openshift-hypershift-main-e2e-aws-all/1526895205024796672/artifacts/e2e-aws-all/test-e2e/artifacts/TestReplaceUpgradeNodePool_PreTeardownClusterDump/namespaces/e2e-clusters-9v26f-example-7b2b7/core/pods/logs/ignition-server-74bd6bd554-qr7z6-ignition-server.log
The above happens right after …
=> Change ignition server http code if token not found.

hypershift-operator/metrics.go, hypershift-operator/metrics_test.go
Generates metrics to answer questions like:
- How many hosted clusters are there in a management clusters? what
platform do they use? what OCP version are they using?
- How many NodePools are there in a management cluster? are they using
autorepair, autoscaling? what OCP version are they using?
- Are the HostedClusters/NodePools healthy? Do they have any conditions
in an undesirable state?
- How many NodePools are associated with a HostedCluster?
- How many replicas are there per NodePool?
Fixes # HOSTEDCP-401
**Checklist**
=> Expose HostedCluster and NodePool metrics in HyperShift operator

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/hostedclusterconfigoperator/api/scheme.go, control-plane-operator/hostedclusterconfigoperator/cmd.go, control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader.go, control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader_test.go, control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/setup.go, control-plane-operator/hostedclusterconfigoperator/operator/config.go, hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, test/e2e/util/util.go
This PR distributes the inplace upgrade logic from the NodePool controller into individual controllers running for each control plane namespace.
This let us honour our intentional network design restrictions to access hosted clusters and scope the impact and resources for each controller to specific hosted clusters.
The implementation at the moment uses annotations on MachineSets to communicate upgrade progress between NodePool controller (NodePool <-> MachineSet) and inplace upgrader (MachineSet <-> Nodes) i.e NodePool <-> Nodes. This info is modeled in the nodePoolUpgradeAPI struct which in future might be exposed as a CRD if needed.
The controller is added to the hcco manager as it already solves the problem of watching and caching targeted …
=> Add inplace upgrader controller to hcco

cmd/nodepool/core/create.go
The log gets currently printed to stdout, resulting in it being included
when redirecting that. Print to stderr instead to avoid that.
Ref https://issues.redhat.com/browse/HOSTEDCP-431
Fixes #
**Checklist**
=> Nodepool render: Avoid including a logline

Dockerfile, Dockerfile.control-plane, Dockerfile.fast, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, ignition-server/cmd/start.go
Currently, the tcp health checking spams the ignition server log with
error. This change adds a simple http healthz endpoint and uses that for
healthchecking if the docker image has a specific label that is also
added. Featuregating this is needed, because the new healthcheck will
never succeed on older ignition servers that do not have this new
handler.
Fixes #
**Checklist**
=> Ignition server: Use https health check if possible

go.mod, go.sum, hypershift-operator/controllers/hostedcluster/createorupdate_annotation_enforcer.go, hypershift-operator/controllers/hostedcluster/createorupdate_annotation_enforcer_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/platform/aws/controller.go, hypershift-operator/controllers/platform/aws/controller_test.go, vendor/gopkg.in/ini.v1/.gitignore, vendor/gopkg.in/ini.v1/.golangci.yml, vendor/gopkg.in/ini.v1/LICENSE, vendor/gopkg.in/ini.v1/Makefile, vendor/gopkg.in/ini.v1/README.md, vendor/gopkg.in/ini.v1/codecov.yml, vendor/gopkg.in/ini.v1/data_source.go, vendor/gopkg.in/ini.v1/deprecated.go, vendor/gopkg.in/ini.v1/error.go, vendor/gopkg.in/ini.v1/file.go, vendor/gopkg.in/ini.v1/helper.go, vendor/gopkg.in/ini.v1/ini.go, vendor/gopkg.in/ini.v1/key.go, vendor/gopkg.in/ini.v1/parser.go, vendor/gopkg.in/ini.v1/section.go, vendor/gopkg.in/ini.v1/struct.go, vendor/modules.txt
Before this commit creating a private link between a management cluster
and a hosted cluster in a different AWS account failed because the
service endpoints created on the management side did not allow endpoints
on the guest side to connect.
This PR adds the control plane role as an allowed principal to the
endpoint service, making it possible to establish the private link
across accounts.
The way it obtains the control plane role is by reading the control
plane credentials secret referenced by the hosted cluster. In order
to parse the secret (in ini format), it vendors the
gopkg.in/ini.v1 package.
Fixes # [HOSTEDCP-408](https://issues.redhat.com/browse/HOSTEDCP-408)
**Checklist**
=> Add allowed principals to service endpoints

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, support/util/deployment.go, support/util/deployment_test.go
This CPO change ensures `kube-apiserver` and `openshift-apiserver` deployments to roll out all updated replicas before proceeding with reconciliation. This makes it so that hypershift control planes adheres to the supported upgrade order as described in kube version skew policy.
Fixes #1222 
**Checklist**
=> feat(cpo): adhere to upgrade order from kube version skew policy

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/registry/registry.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, support/globalconfig/infrastructure.go
This changes the InfrastructureAvailabilityPolicy to SingleReplica to be consistent with the ControllerAvailabilityPolicy default..
Fixes #
**Checklist**
=> Change infrastructureAvailabilityPolicy default to single replica

hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
Currently, nodepool deletion will fail if the hostedcluster doesn't
exist anymore which means that if nodepool deletion is too slow, we will
deadlock. This fixes that.
Note that this introduces an backwards-incompatible change to how
machinedeployments are named. This means that the hypershift operator
will create a new machinedeployment for existing nodepools when
upgraded. The same goes for cleanup, the machinedeployment will be
deleted transiently by the garbage collector controller, however the
same goes for the capi pods, hence cleanup might not work automatically.
Fixes # …
=> Allow nodepool deletion when hcluster is gone

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/deployment.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go
**What this PR does / why we need it**: Currently, the TLS Security Profile config isn't propagated to the kube-scheduler and kube-controller-manager like it is for other control plane components. This PR ensures the components are configured accordingly with the MinTLSVersion and CipherSuites. 
**Which issue(s) this PR fixes** https://github.com/openshift/hypershift/issues/1371
**Checklist**
=> Fix(cpo): Propagate TLS security profile config to kube-controller-manager and kube-scheduler

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/deployment.go, control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/service.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oauth/service.go, control-plane-operator/controllers/hostedcontrolplane/ocm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/deployment.go, support/config/deployment.go
This fixes an error in the control plane operator where it will fail to reconcile and properly adopt deployments based on roks toolkit clusters. This is due to the fact that the selectors has changed and that is an immutable field. Specifically, hypershift selectors add a duplicate selector hypershit.component that is not contained in roks toolkit clusters. Even with the single app selector: deployment rollout behavior is unchanged. This allows for zero downtime adoption of roks toolkit clusters. Associated issue: https://github.com/openshift/hypershift/issues/1042
Key Changes:
1) Need to preserve label selector on services to ensure network connectivity isn't cutoff on adoption 
2) Need to adopt deployment immutable  selector on deployments in order to be able to successfully adopt …
=> adopt existing immutable selectors to prevent errors reconciling components from roks toolkit clusters

support/upsert/loopdetector.go
The current treshold causes flakes, presumably because changes do not
get back into the cache in time. Give some leeway, if we actually revert
defaults we will likely end up with a very high number of updates and
still detect that.
Fixes #
**Checklist**
=> Loopdetector: Give some more leeway

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go
The service account for the private router pod doesn't specify any
image pull secrets. This means that the pull secret specified for the
hosted cluster is not used in pulling the router image.
This change ensures that the private-router service account uses the
pull secret for the hosted cluster.
**Checklist**
=> Ensure that the private router pod uses the HC's pull secret

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
We were relying on the autoscaler default machine api group which if changed by accident as in https://github.com/openshift/kubernetes-autoscaler/commit/8a93f4e3b065e9b2c8c3329707c52ee9053f36bf would automatically break usas we don't grant rbac for machine.openshift.io https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_hypershift/1424/pull-ci-openshift-hypershift-main-e2e-aws-all/1531259053521506304/artifacts/e2e-aws-all/test-e2e/artifacts/TestAutoscaling_PreTeardownClusterDump/namespaces/e2e-clusters-hzlnb-example-wrtvk/core/pods/logs/cluster-autoscaler-59858bdf6d-qst7w-cluster-autoscaler.log
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, …
=> Set autoscaler CAPI group explicitely

Makefile, hack/ci-test-e2e.sh
This enables junit for the ci-test-e2e maketarget. It uses a Bash exit
trap to ensure that failure of the test command get properly propagated.
/hold
/test e2e-aws-all
Fixes #
**Checklist**
=> Tests: Enable junit

availability-prober/availability_prober.go, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, cmd/version/version.go, control-plane-operator/hostedclusterconfigoperator/cmd.go, control-plane-operator/main.go, hypershift-operator/main.go, ignition-server/cmd/start.go, konnectivity-socks5-proxy/main.go, kubernetes-default-proxy/kubernetes_default_proxy.go, main.go, pkg/version/version.go, token-minter/tokenminter.go
Adds git commit, tree state and build date as ldflags to hypershift
binaries. It then includes the version in output logs.
It also adds a command `version` that outputs the version from the CLI
and also includes that version as an annotation in the HyperShift
deployment to indicate which version of the CLI was used to generate it.
This enables us to better debug errors and understand which version of
the code is running in a particular installation.
**Checklist**
=> Use git commit as version in HyperShift binaries

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
The controller currently only reports aws error codes which are not helpful in understanding in which call the error occurred, or what the original error was.
**Checklist**
=> aws private link controller: improve error messages

hypershift-operator/controllers/nodepool/nodepool_controller.go
This is to try to mitigate and isolate CI flakiness https://github.com/openshift/hypershift/pull/1430#issuecomment-1144666152 where ocassionaly cluster creation with autorepair enabled has failed to get healthy Nodes. In these failures Machines are being deleted when the NodeStartupTimeout is met. If there's a legit reason why the Nodes are not being created this won't help, however it will help to make more clear the former is true.
Fixes #
**Checklist**
=> Increase MHC nodeStartupTimeout

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
CNO operands in the guest cluster should use the private API server address when the HC is private.
Fixes #
**Checklist**
=> CNO operands use private APIServer address when HCP is private

cmd/cluster/agent/create.go, cmd/cluster/kubevirt/create.go
Allows for overriding the API server address that is put in the NodePort service publishing strategy if there is infrastructure (LBs, etc) around the mgmt cluster of which the `hypershift` CLI is not aware.
This field already existed in the platform specific create options, but there was no flag to set them.
Fixes #
**Checklist**
=> add api-server-address flags to kubevirt and agent cluster create

cmd/install/assets/recordingrules/hypershift.yaml, hack/app-sre/saas_template.yaml
This will allow us to monitor for changes to component requests over time and % over/under requests on memory.
Fixes #
**Checklist**
=> Add recording rule for component memory requests

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go, control-plane-operator/controllers/hostedcontrolplane/configoperator/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-certified.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/packageserver-deployment.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This aligns memory requests for components under our direct management with recommendations from PerfScale.
Net impact is total HCP memory request increases by 1005Mi for SingleReplica and 1905Mi for HA.  Total HCP memory request after this change is 7.3Gi for SR and 18Gi for HA.
A follow-on to this PR is adjusting `ovnkube-master` pod from 1500Mi total request to more like ~400Mi.  This will save 1.1Gi of requests on SR and 3.3Gi on HA making total HCP request 6.2Gi for SR and ~14.7Gi for HA.
Currently, HCPs actually _use_ 5Gi for SR and 10Gi for HA in CI.  CI clusters are largely idle though and generally represent a lower bound on usage.
`etcd` pods are not adjusted in this PR as we are currently aligned with standalone OCP at `600Mi` memory request.  However, real world usage seems to …
=> Adjust memory requests to align with PerfScale recommendations

Dockerfile, Dockerfile.control-plane, Dockerfile.fast, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go, hypershift-operator/controllers/util/deployment.go
This changes moves the ignition server management from the HO into the
CPO. In order to stay backwards compatible, the HO will still reconcile
the ignition server if the CPO isn't opted into doing that through a
Docker image label.
Ref https://issues.redhat.com/browse/HOSTEDCP-411
/cc @enxebre 
Fixes #
**Checklist**
=> Manage ignition server from CPO

api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, support/api/scheme.go, test/e2e/nodepool_machineconfig_test.go, test/e2e/nodepool_machineconfig_verification_ds.yaml
This adds a new test that checks if a nodepool rolls out additional
machine configs. It works by:
* Creating a cluster inclusive nodes and waiting for everything to be
ready
* Adding an additional machineconfig to all nodepools of the cluster
that specifies to create a file /etc/custom-config
* Deploying a daemonset whose readyness probe does an exec to cat this
new file
* Waiting until the daemonset has as many pods as there are nodes and
for all those pods to be ready
Ref https://issues.redhat.com/browse/HOSTEDCP-412
Fixes #
**Checklist**
=> E2E: Add TestNodepoolMachineconfigGetsRolledout

cmd/install/assets/hypershift_operator.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
4.11 management clusters have a different default SCC which breaks the
router pods. Update the deployment and role to match what the
cluster-ingress-operator does to fix it.
Fixes #
**Checklist**
=> Fix the private router to work on a 4.11 mgmt cluster

cmd/infra/aws/ec2.go
We are currently only checking whether there is an invalid subnet when retrying nat gateway creation, but we also need to check for an invalid eip error
**Checklist**
=> nat gateway: check for invalid eip

ignition-server/controllers/tokensecret_controller.go
We are observing unexpected cache regeneration in IBM, this attempt to prevent those from happening.
Set the new token before patching the object. Otherwise, there is a race: if the secret is reconciled before the value is set in the cache the new token would require a new payload generation in that reconciliation.
If token patch operation fails, consistently restore the cache.
Otherwise, the next reconciliation the token would require a new payload generation because it wouldn't be in the cache anymore.
Fixes #
**Checklist**
=> Ensure cache is set during token rotation before reconciling

hypershift-operator/controllers/nodepool/inplace.go
These reasons need to be changed, currently we see
```
- lastTransitionTime: "2022-06-15T20:51:30Z"
message: 'Updating version in progress. Target version: "4.11.0-0.nightly-2022-06-14-172335".
Total Nodes: 3. Upgraded: 1'
observedGeneration: 2
reason: InplaceUpgradeFailed
status: "True"
type: UpdatingVersion
replicas: 2
```
Fixes #
**Checklist**
=> Use right conditions reason for inplace upgrade

control-plane-operator/hostedclusterconfigoperator/controllers/resources/alerts/assets/apiusage.yaml, control-plane-operator/hostedclusterconfigoperator/controllers/resources/alerts/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/alerts.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
This PR adds "api-usage" Prometheus alert rules (APIRemovedInNextReleaseInUse and APIRemovedInNextEUSReleaseInUse https://github.com/openshift/cluster-kube-apiserver-operator/blob/release-4.9/bindata/assets/alerts/api-usage.yaml) to Hypershift-hosted clusters . The rules are missing because the component that normally creates them ([cluster-kube-apiserver-operator](https://github.com/openshift/cluster-kube-apiserver-operator)) does not exist Hypershift-hosted clusters.
GitHub issue: https://github.com/openshift/hypershift/issues/1201
**Checklist**
=> Add missing control plane prometheus rules

api/v1alpha1/hostedcluster_types.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, support/releaseinfo/fake/fake.go
We need validation for changes to `spec.release.image` on the `HostedCluster`.  This is an attempt to implement basic checks and block reconciliation when a user sets the release image to something unsupported.
https://issues.redhat.com/browse/HOSTEDCP-389
**Checklist**
=> Add ValidReleaseImage condition to HostedCluster

hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent_test.go
This add unit tests and fixes the ReconcileCAPIInfraCR agent implementation to avoid an unncesesary kas call to fetch the HCP, since all needed info is available already.
Aditionally it returns early if there's no ign endpoint to ensure we create the agentCluster only after ignition endpoint exists so AgentClusterInstall is only created with the right ign to boot machines.
https://bugzilla.redhat.com/show_bug.cgi?id=2097895
https://github.com/openshift/assisted-service/blob/241ad46db74add5f16e153f5f7ba0a5496fb06ba/pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook.go#L185
https://github.com/openshift/cluster-api-provider-agent/blob/master/controllers/agentcluster_controller.go#L126
This change honours the following …
=> Drop kas call in agent ReconcileCAPIInfraCR and fail if no ign

docs/content/how-to/agent/create-agent-cluster.md
The existing agent documentation goes into too much detail on things that are not on the fast path to success and covers things that should be covered elsewhere such as "how to install golang".
It also implies that a metal IPI OCP cluster with bare metal operator are required when they are not.
This tries to streamline the agent docs to put users on a fast path to success.
There are still some things that need cleaned up like the use of 3rd party `tasty` tool, but leaving that for another day.
@csrwng @enxebre @eranco74 
Fixes #
**Checklist**
=> docs: refactor agent documentation

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
* If the pull-secret is created after the hostedCluster resource,  the generation check that is done, would block access to trying the validation again if the first attempt failed.
* ACM creates the HostedCluster resource and secrets with ManifestWork the creation order of resources is not guaranteed.
Signed-off-by: Joshua Packer <jpacker@redhat.com>
Provisioning with ACM/MCE was blocked after [Merge pull request](https://github.com/openshift/hypershift/commit/069d7d1f4e7908d68ece987257e5a0e6b4f0ffa6) https://github.com/openshift/hypershift/pull/1296
NA
**Checklist**
=> The ValidateReleaseImage was returning an error stating it could not find the pull-secret and blocked HC

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml
Do not always pull Hypershift images
Fixes #
**Checklist**
=> Use ImagePullPolicyIfNotPresent for HO

docs/content/how-to/agent/create-agent-cluster.md
In #1466 I simplied the agent docs.  As part of that, I switched the `AgentServiceConfig` script to reference the moving target `latest` rather than a specific version, which is likely to lag behind in the future.
However, assisted-service stores a hash of the referenced resources at the time the `AgentServiceConfig` is created/modified.  When `latest` is changed, the hash check fails and hosts booted with the discovery ISO are unable to join as Agents.
This reverts the script to pointing to a particular RHCOS build to avoid breaking when `latest` changes.
@avishayt @eranco74 @csrwng 
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira …
=> docs: agent: AgentServiceConfig script used fixed version instead of latest

control-plane-operator/controllers/hostedcontrolplane/kas/config.go
Mirrors
https://github.com/openshift/cluster-kube-apiserver-operator/pull/1358
/cherrypick release-4.11
Fixes #
**Checklist**
=> Excempt build controller SA from PodSecurity admission

hypershift-operator/controllers/nodepool/nodepool_controller.go
This is a minor fix to nodepool controller to remove the right condition type when not missing CA cert
**Checklist**
=> nodepool controller: remove right condition type

hypershift-operator/metrics.go
Changes the name of hypershift operator metrics based on recommedation from monitoring team. Gauges should not include _count or _total suffixes
**Checklist**
=> Rename hypershift operator metrics

api/v1alpha1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/deployment.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/util/strings.go
**What this PR does / why we need it**: Add annotation to support disabling profiling for control plane components. 
Fixes #1438
**Checklist**
=> feat(cpo): Support disable profiling annotation

cmd/infra/powervs/create.go
Resource instance's nextUrl accessed without validating nil condition due to incorrect usage of OR condition instead of AND.
Fixed it by replacing it with AND condition.
https://issues.redhat.com/browse/MULTIARCH-2574
Fixes #
**Checklist**
=> PowerVS : CIS Domain nextUrl usage fixed

hypershift-operator/controllers/nodepool/haproxy.go, support/util/visibility.go
Fix issue where guest cluster components do not communicate over privatelink when connecting to the KAS over the service network.  This causes guest cluster components to be blocked when using `apiAllowedCIDRBlocks`.
Fixes #
**Checklist**
=> kube-apiserver-proxy use privatelink for private clusters

api/v1alpha1/hostedcluster_types.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
https://issues.redhat.com/browse/HOSTEDCP-493
Example condition on the HC if CPO cred is missing for platform AWS
```
- lastTransitionTime: "2022-06-30T16:43:38Z"
message: 'failed to get control plane operator provider creds example-cpo-creds:
Secret "example-cpo-creds" not found'
observedGeneration: 3
reason: PlatformCredentialsInvalid
status: "False"
type: PlatformCredentialsValid   
```
Fixes #
**Checklist**
=> Add PlatformCredentialsFound condition to report missing platform creds

test/e2e/util/fixture.go
We have a default dumping mechanism that works and provides value for
all platforms. Rather than failing by default and require each platform
to opt in, despite most using the default logic, we should just use the
default logic and only use the platform-level switching to allow adding
platform-specific logic if wanted.
Fixes #
**Checklist**
=> E2E dump: Do not require platform opt-in for dump to work

control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
Allow `challenge` parameter to be override-able for OpenID identity providers.
Fixes #1502 
**Checklist**
=> feat(oauth): allow challenge override for OpenID

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
This change makes the oauth server route external traffic through the
guest cluster, in order to enable communication with IDPs that are only
accessible from the guest cluster network.
https://issues.redhat.com/browse/HOSTEDCP-421
Fixes #
**Checklist**
=> Oauth server: Route external traffic through guest cluster

api/v1alpha1/hostedcluster_types.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
This adds a catch-all condition to hostedclusters that indicate the
success of a reconciliation and will surface errors, if any.
Fixes #
**Checklist**
=> HO: Add a reconciliation success condition

cmd/cluster/agent/create.go, cmd/cluster/aws/create.go, cmd/cluster/azure/create.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/cluster/kubevirt/create.go, cmd/cluster/none/create.go, cmd/cluster/powervs/create.go, cmd/infra/aws/create.go, cmd/infra/aws/ec2.go, cmd/infra/azure/create.go, test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/chaos_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/nodepool_machineconfig_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/olm_test.go
This change makes us use the zaptest logger for cluster creation in E2E
tests. The zaptest logger scopes its output to the current testcase,
which should help a lot with legibility of E2E output. In order for this
change to be useful, all providers need to use the passed logger for
their cluster creation log, this change only does that for AWS and
Azure.
Fixes #
**Checklist**
=> E2E: Use zaptest logger for cluster creation

ignition-server/cmd/start.go, ignition-server/controllers/image_file_cache.go, ignition-server/controllers/image_file_cache_test.go, ignition-server/controllers/local_ignitionprovider.go
This PR adds caching capability to the registry client function registryclient.ExtractImageFile() to prevent it from re-downloading big binary image files multiple times so that load on the back-end registry is reduced.
Please see issue https://github.com/openshift/hypershift/issues/1437
**Checklist**
=> cache registry files

api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/azure.go
This makes the disk type on Azure configurable and defaults it to SSD
disks, instead of hdd in order to speed things up. Comparison of join
times, the nodepools were created at the same time:
```
hdd-qpghq   Ready    worker   4m10s   v1.24.0+b5932d4
hdd-rv576   Ready    worker   3m41s   v1.24.0+b5932d4
hdd-vxnhr   Ready    worker   5m4s    v1.24.0+b5932d4
ssd-n27qp   Ready    worker   6m21s   v1.24.0+b5932d4
ssd-q4s5f   Ready    worker   6m13s   v1.24.0+b5932d4
ssd-tqlmh   Ready    worker   6m24s   v1.24.0+b5932d4
```
Fixes #
**Checklist**
=> Azure: Make disk type configurable and default to SSD instead of HDD

cmd/cluster/aws/destroy.go, cmd/cluster/cluster.go, cmd/cluster/core/destroy.go, cmd/cluster/core/dump.go, cmd/infra/aws/destroy.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/route53.go, test/e2e/e2e_test.go, test/e2e/util/dump/dump.go, test/e2e/util/fixture.go, test/e2e/util/util.go
This ensures that the logging in the tests get scoped to the specific test, making the E2E output more legible.
Fixes #
**Checklist**
=> E2E: Use zaptest logger for dumping and AWS/Azure destroy

api/v1alpha1/hosted_controlplane.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, docs/content/reference/api.md, support/config/deployment.go
Requires https://github.com/openshift/hypershift/pull/1554
https://issues.redhat.com/browse/HOSTEDCP-495
Adds a `Degraded` condition on the HCP with Reason `UnavailableReplicas` if any of the CPO managed deployments has a `status.unavailableReplicas` > 0.
Fixes #
**Checklist**
=> add Degraded condition to HCP

test/e2e/util/fixture.go
In situations where we don't create anything, e.G. because an invalid
release image was specified, the e2e destroy code loops forever withot
any chance of success. Avoid this.
Fixes #
**Checklist**
=> E2E: Stop retrying destroy if inputs are missing

Makefile, cmd/install/install.go, support/metrics/platform_monitoring.go
Instead of providing a simple boolean for enabling OCP monitoring for
the HyperShift operator and all control plane namespaces, this commit
introduces an option to enable OCP monitoring only for the HyperShift
operator and not control plane namespaces.
This additional option is needed for the MCE standalone use case in
which we want to use OCP monitoring to collect metrics from the
HyperShift operator to send to telemetry. For control plane namespaces
we want to use User Workload Monitoring to remote write telemetry of the
individual hosted clusters.
**Checklist**
=> install: add operator-only option for OCP metrics

test/e2e/autoscaling_test.go, test/e2e/e2e_test.go, test/e2e/util/fixture.go
The zone suffix is only correct for AWS clusters, on other platforms
like Azure this test fails because no nodepool of that name exists.
Fixes #
**Checklist**
=> TestAutoscaling: Fix to work on Azure

go.mod, hypershift-operator/controllers/manifests/supportedversion/configmap.go, hypershift-operator/controllers/supportedversion/reconciler.go, hypershift-operator/controllers/supportedversion/reconciler_test.go, hypershift-operator/main.go, support/supportedversion/version.go, support/supportedversion/version_test.go
Introduces a controller that maintains a configmap in the `hypershift`
namespace that contains a list of supported minor versions by the
current controller.
This is done by a controller and not laid down by the installer because
the operator itself is the source of truth for what it supports, and not
the CLI.
The ConfigMap will be used by the MCE UI to filter the versions that can
be used when creating a HostedCluster.
Fixes #[HOSTEDCP-496](https://issues.redhat.com//browse/HOSTEDCP-496)
**Checklist**
=> Add configmap containing supported versions to hypershift namespace

api/v1alpha1/hostedcluster_types.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Follow up to #1560 
https://issues.redhat.com/browse/HOSTEDCP-495
Copies the Degraded condition on the HCP up to the user-facing HC.
As of this PR, the HC controller does not have any additional logic to observe degraded conditions within its management domain but that is in the plan e.g. deployment availability checks on CAPI and the CPO, etc
Fixes #
**Checklist**
=> add Degraded condition to HostedCluster

hypershift-operator/controllers/supportedversion/reconciler.go
Because HyperShift can be installed in any namespace, this label helps find the configmap in a management cluster
Fixes #[HOSTEDCP-496](https://issues.redhat.com//browse/HOSTEDCP-496)
**Checklist**
=> Add label to supported versions configmap

test/e2e/olm_test.go
This test should use whatever platform is configured innstead of always
using AWS. I verified that this change makes it pass on Azure.
Fixes #
**Checklist**
=> TestOLM: Don't hardcode to AWS

hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
Small fix for https://github.com/openshift/hypershift/pull/1516
If ARNs are not provided in the HC, either through the new or old fields, we just render a credentials file that looks like
```
[default]
role_arn = 
web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
```
This results in an error in the underlying component that is hard to detect without looking at the logs.
Instead, return a HC-level reconciliation error and report that on the `PlatformCredentialsFound` condition.
Fixes #
**Checklist**
=> Add check for AWS ARNs

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/deployment.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go
Adds `hyperv1.ControlPlaneComponent` to components that are missing it:
network operator, ingress operator, scheduler.
```kubectl get pods -l hypershift.openshift.io/control-plane-component -nclusters-agl```
Might follow up with some refactor to the deployment config library.
Fixes #
**Checklist**
=> Add control plane operator component template label to components missing it

api/v1alpha1/hostedcluster_types.go
The optional field RestoreSnapshotURL does not have `json omitempty`. When the HypershiftDeployment controller tries to update a HostedCluster CR, the following error occurs because of missing `omitempty`.
```
spec.hostedClusterSpec.etcd.managed.storage.restoreSnapshotURL: Invalid value: "null": spec.hostedClusterSpec.etcd.managed.storage.restoreSnapshotURL in body must be of type array: "null"
```
Fixes #
**Checklist**
=> Optional RestoreSnapshotURL should have omitempty

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Shuffling of the deployment list is resulting in unnecessary status updates.  Sort the list so the condition message is stable for a given set of deployments. 
Fixes #
**Checklist**
=> Sort deployments for Degraded condition check

cmd/cluster/powervs/create.go, cmd/infra/powervs/create.go, cmd/infra/powervs/destroy.go, docs/content/how-to/powervs/prerequisites-and-env-guide.md, hypershift-operator/controllers/hostedcluster/internal/platform/powervs/powervs.go, test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/nodepool_machineconfig_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/olm_test.go, test/e2e/util/fixture.go, test/e2e/util/util.go
Add e2e changes for PowerVS cloud platform.
Changes added are:
- Added env var `IBMCLOUD_CREDENTIALS` to pass cred file containing API key for auth purpose, since prow job follows secrets to be passed as files for e2e job authentication, added this change.
- Added changes in `test/e2e` for handling PowerVS platform.
- Handled timeout in `WaitForNReadyNodes` func respective to cloud platform, since PowerVS requires some extra time for nodes to get ready. 
- Added resource request for CAPI, since `EnsureHCPContainersHaveResourceRequests` test is validating the resource requests for HC containers.
- Returned nil when ever no resources are available to delete instead of an error in infra deletion. This is required, during tearDown, if there is any …
=> Add e2e changes for PowerVS

cmd/install/assets/hypershift_operator_test.go, support/util/volumes.go
We need to ensure the default certs aren't overwritten when a user
provides additional certs - looking at
https://go.dev/src/crypto/x509/root_linux.go it seems we should be
able to use a non-default filename in /etc/pki/tls/certs instead
Aims to fix reported issues testing with additionalTrustBundle on AWS (I only tested with `none` platform when developing #972)
Leaving this WIP until we can confirm it fixes the reported issue, but also that the new cert location is correctly read in the case where user additional CA certs are provided.
=> Use non-default path for user CA certs

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, konnectivity-socks5-proxy/main.go
The socks5 proxy has code to avoid sending traffic destined for cloud
provider apis through konnektivity in order to not require nodes to be
up for that communication to work.
When running a management cluster with a proxy setup and not setting
proxy env vars in the socks5 proxy, that code effectively means that it
is not possible to commnicate with those apis, as the sidecar can not
route it as it has no direct Internet connectivity.
The above currently breaks imagestreamimports if the import is from a docker
registry hosted in AWS S3, as the Openshift APIServer is supposed to
route all its imports through Konnektivity, which is why its proxy
sidecar does not get the mgmt cluster proxy env vars.
The only reason for special casing cloud provider apis here is the
ingress operator, as it …
=> Socks 5 proxy: Only use mgmt cluster for cloud apis for ingress operator

support/api/scheme.go, support/globalconfig/globalconfig.go, support/globalconfig/globalconfig_test.go
The HyperShift operator uses the latest version of the OpenShift API to
serialize global config in the HCP (for compatibility with older CPOs).
The issue is that if there's a new field in the latest API that the
older CPO does not understand, we currently produce an error decoding
the YAML because the YAML serializer we use is using strict mode.
This commit switches to a YAML serializer that does have strict mode for
parsing of the global configuration. Making it possible for older CPOs
to parse YAML from the latest HyperShift operator.
**Checklist**
=> Use non-strict mode when parsing global config

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
all hosted control-plane components should have the release image annotation set to be able to easily monitor that the associated component is derived from the active release image. Control-plane-operator is missing this annotation. This pr adds that in (utilized in IBM Cloud to track rollout progress).
Fixes #
**Checklist**
=> ensure release image annotation set on control-plane-operator

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
IBM has a large estate of production 4.9_openshift hypershift clusters. 4.9 cannot be deemed unsupported until a strategy is worked out and communicated to customers
Fixes #
**Checklist**
=> ensure 4.9 openshift clusters can be managed by hypershift

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
These fields cannot be cleared since it breaks validation for 4.10 and 4.9 control-plane-operator images. Those images with this removed fail validation with:
APIServer: named serving certificate ibm-named-certs not included in secret references, OAuth: identity provider IAM openid client secret hypershift-ibm-iam-clientsecret is not included in referenced secrets
The reconciliation of these values needs to continue to occur until all existing production control-plane-operators are confirmed to be at a compatible version.
Fixes #
**Checklist**
=> stop clearing configMapRef and secretRef since it breaks reconciliation of existing production workload using these fields

cmd/cluster/powervs/destroy.go
This PR trying to address this bug https://issues.redhat.com/browse/MULTIARCH-2692 for not handling the flags for destroy cluster powervs command.
Fixes #
**Checklist**
=> Add flags for destroy cluster powervs command

control-plane-operator/controllers/hostedcontrolplane/kas/ibmcloud_kms.go
There is a problem in the unmanaged auth path where an optional mount that is necessary for the build out of the container is not getting mounted. It is only getting mounted in the managed auth path. This ensures the volume is added in both paths so unamanged authentication (customer provided authentication) works
Fixes #
**Checklist**
=> ensure optional mount always added to ibmcloud kms pod for appropriate container build

ignition-server/controllers/local_ignitionprovider.go
In #972 I relied on the fact that MCSIgnitionProvider [mounts the MCO
ConfigMap](https://github.com/openshift/hypershift/blob/main/ignition-server/controllers/machineconfigserver_ignitionprovider.go#L265) under `/assets/manifests` - this means that the
`user-ca-bundle-config.yaml` file path matches the [default location
from the MCO bootstrap code](https://github.com/openshift/machine-config-operator/blob/master/cmd/machine-config-operator/bootstrap.go#L69), thus no explicit
`--additional-trust-bundle-config-file` argument was required.
In #1214 we introduced a new LocalIgnitionProvider, which [unpacks the
MCO config](https://github.com/openshift/hypershift/blob/main/ignition-server/controllers/local_ignitionprovider.go#L164) to a different path e.g …
=> Fix additionalTrustBundle with local ignition provider

api/v1alpha1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
https://issues.redhat.com/browse/HOSTEDCP-492
Set condition message when waiting for KAS readiness.
It also changes the wording of some reasons and messages from "unavailable" to "waiting" for better UX, conveying that nothing is wrong (probably) and that things are likely just still progressing. 
Fixes #
**Checklist**
=> set condition messsage when waiting for kas readiness

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/nodepool/aws.go, hypershift-operator/controllers/nodepool/aws_test.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
Without enforcing this in the NodePool controller there's race with HC defaulting itself in the backend. The race might result in unncessary MachineDeployment rolling uprades caused by generating different awsmachinetemplates (with / without the tag). This relax the coupling.
Fixes #
**Checklist**
=> Enforce aws cluster cloud provider tag in NodePool controller

control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go
When a hostname is specified we should still block infra readiness on the LB being created.  Otherwise, the guest cluster can come up before the LB and external-dns registered record are ready.
I think this is the source of a lot of our CI flakes.
Fixes #
**Checklist**
=> Wait for LB even when hostname is specified

api/fixtures/example.go, cmd/cluster/core/create.go, cmd/cluster/none/create.go, test/e2e/chaos_test.go, test/e2e/util/fixture.go
These tests only test etcd behavior which is the same regardless of
platform. Run them on the none platform to speed things up and avoid
needlessly creating cloud provider resources.
Fixes #
**Checklist**
=> E2E etcd tests: Always run on none platform

docs/content/how-to/aws/create-aws-hosted-cluster-multiple-zones.md
Fix the break path to getting started on the AWS documentation page.
cc @derekwaynecarr
=> doc(how-to/aws/create-aws-multi-az): fix getting started path

hypershift-operator/controllers/nodepool/haproxy.go, hypershift-operator/controllers/nodepool/haproxy_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_private_cluster_uses_.local_address.yaml, hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_private_cluster_uses_.local_address_and_custom_apiserver_port.yaml, hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_public_and_private_cluster_uses_.local_address.yaml, hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_public_and_private_cluster_uses_.local_address_and_custom_apiserver_port.yaml, hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_public_cluster_uses_address_from_kubeconfig.yaml, hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_public_cluster_uses_address_from_kubeconfig_and_custom_port.yaml
This change adds a couple of unittests for the static haproxy pods
config to ensure it is correct in various hostedcluster configurations.
Fixes #
**Checklist**
=> Add unittests for haproxy config generation

Makefile
It regularly times out in CI. Also remove the dependency on `build`,
unittests do not need any binaries built.
Fixes #
**Checklist**
=> Increase the unittest timeout to 20m from the default 10m

control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/ingress.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/oauth.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
Currently, the hcco redefines some manifests owned by the CPO. The
content of the two must be the same, otherwise things won't work.
Reference the CPO manifests instead to clarify this dependency.
Fixes #
**Checklist**
=> HCCO: Use cpo manifests for references

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go
We need serviceaccount kubeconfigs for a variety of use cases. Make this
simple to encourage creating distinct kubeconfigs rather than using the
admin kubeconfig everywhere and de-duplicate the existing occurences of
this.
Fixes #
**Checklist**
=> Add a helper to create SA kubeconfigs

hack/ci/install-mce.sh
This script allows us to take a MCE downstream dev preview build found in the quay repo [here](https://quay.io/repository/acm-d/mce-custom-registry?tag=latest&tab=tags), and install MCE + enable the hypershift operator.
This script lets us do two things.
1. install a dev release of MCE locally on a cluster in order to debug, etc... 
2. create CI automation that exercises hypershift as delivered by the MCE olm bundle
Example: Installing the latest MCE 2.1 downstream release candidate
```
export QUAY_AUTH=<your quay auth token that can pull from quay.io/acm-d>
export MCE_DEV_RELEASE_IMAGE="quay.io/acm-d/mce-custom-registry:v2.1.0-FC1"
./hack/ci/install-mce.sh
```
That installs MCE from a custom catalog source, makes the OCP cluster a "local-cluster", and enables the hypershift operator. …
=> CI script to install hypershift from pre-release MCE catalog source

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/registryoperator.go, control-plane-operator/controllers/hostedcontrolplane/pki/registryoperator.go, control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile_test.go, control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcileDeployment.yaml, control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcilePodMonitor.yaml, support/metrics/sets.go
Stops CVO from reconciling the cluster image registry operator into the
guest cluster and enables the control plane operator to reconcile it on
the management cluster side.
This change is needed to make it possible to clean up resources created
by the guest cluster. Having the image registry operator on the control
plane side allows it to keep running after worker nodes have been
removed from the cluster. On the guest cluster, changing the operator
config state to "Removed" tells the operator to remove the S3 bucket
(or other cloud storage) it created when starting up.
Fixes …
=> Move image registry operator to control plane

api/v1alpha1/hostedcluster_types.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile_test.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Configure ingress controller with endpoint publishing strategy as Private. Expose this configuration setting as an annotation on the HostedCluster/HostedControlPlane CRs. And will be generic to be applicable to any providers. Support ingress endpoint publishing strategy scope like we do today. Support for this was recently added to the IBM ROKS Toolkit and our ROKS 4 ansible code. (Focus on scoping this up to Hypershift).
Issue: https://github.com/openshift/hypershift/issues/1599
Fixes #
**Checklist**
=> Ingress endpoint

hypershift-operator/controllers/hostedcluster/internal/platform/powervs/powervs.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2749
Add `--powervs-provider-id-fmt=v2` param as part of capi deployment to use provider-id-fmt.
Fixes #
**Checklist**
=> PowerVS: Add provider id fmt for capi deployment

Makefile, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, cmd/install/install_render.go, hack/app-sre/saas_template.yaml
allow `--external-dns-*` install flags to be used for template rendering.
additionally, a setting `--external-dns-txt-owner-id` is introduced to provide a txt registry owner id for external-dns instead of generating a new one on each install
Part of [HOSTEDCP-485](https://issues.redhat.com/browse/HOSTEDCP-485)
=> external-dns settings for operator install template rendering

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/oauth/route.go
https://issues.redhat.com/browse/HOSTEDCP-531
Drops port 80 from the `private-router` and `router` services and explicitly sets `insecureEdgeTerminationPolicy` on all routes to `None`.
Fixes #
**Checklist**
=> Drop insecure port on router to save rules

test/e2e/util/fixture.go
fixes https://issues.redhat.com/browse/MULTIARCH-2741
- Since HostedCluster is used to access baseDomain and CIS details, in case of an error in infra creation, these values would be nil and causing a crash. Fixed it by using CreateOpts.
- InfraID is a required param for destroy PowerVS infra, so added code to set infraID explicitly in e2e CreateOpts.
Fixes #
**Checklist**
=> Fix e2e powervs destroy opts

test/e2e/autoscaling_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/nodepool_upgrade_test.go
In the e2e tests we always want to set specific field(s) to specific
value(s) and we don't care if the object has changed after we received
it. By using Update we allow such failures to fail the test, so replace
the Update calls with Patch calls.
Example of e2e failing due to a conflict when updating: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/31161/rehearse-31161-pull-ci-openshift-hypershift-main-e2e-aws-nested/1556732246054932480#1:build-log.txt%3A1716
Fixes #
**Checklist**
=> E2E: Consistently use Patch to avoid conflict failures

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go
* If the apiserver is public we don't need a router at all
* If it is publicAndPrivate, we need a router but not a public router
service and the router must not use a custom template
* In all cases we need to delete the resources related to the old
private-router deployment
I verified manually that after this PR, a 4.11 PublicPrivateCluster that
exposes its apiserver through an LB can be updated to the CPO from this
change and everything works as expected.
Fixes #
**Checklist**
=> Fix router reconciliation when apiserver is exposed through LB

support/upsert/upsert.go
Add IBMPowerVSCluster to status sub resource set since IBMPowerVSCluster has also status sub resource.
Fixes #
**Checklist**
=> Add IBMPowerVSCluster to status subresource set

hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go
=> ClusterID and infraID should be immutable.

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, cmd/cluster/cluster.go, cmd/cluster/core/destroy.go, control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/webhookconfig.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go, control-plane-operator/hostedclusterconfigoperator/operator/config.go, docs/content/getting-started.md, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, test/e2e/e2e_test.go
Enables the removal of cloud resources created during the lifetime of a
guest cluster. These include:
- registry storage
- ingress load balancer and dns records
- load balancer services
- persistent volumes
Removal of these resources will occur when the following annotation is
present:
hypershift.openshift.io/cleanup-cloud-resources: "true"
The CLI adds this annotation to a HostedCluster when invoking the
destroy command with the 'destroy-cloud-resources' flag:
hypershift destroy cluster aws --destroy-cloud-resources
Fixes #[HOSTEDCP-486](https://issues.redhat.com//browse/HOSTEDCP-486)
**Checklist**
=> Enable cleaning up of hosted cluster cloud resources on destroy

test/e2e/autoscaling_test.go, test/e2e/nodepool_machineconfig_test.go
The E2E tests currently try to match nodepools to a hostedcluster by
using an ownerReference on it. This ownerreference is added by the
nodepoool controller and doesn't exist initially, which makes this
approach racy and thus causes flakes.
Use the same matching logic as the nodepool controller
(`nodepool.spec.clusterName`) to avoid this.
Fixes #
**Checklist**
=> E2E: Fix flakes due to inability of finding matching nodepools

cmd/install/install_render.go, hack/app-sre/saas_template.yaml
the `--external-dns-provider` parameter must not be a parameter in the openshift template generated by `hypershift install render --template`. the value of `--external-dns-provider` influences parts of the generated template, e.g. the `AWS_SHARED_CREDENTIALS_FILE` env var being added to the `external-dns` deployment or not. therefore the value of the provider must be known already at template generation time (`hypershift install render --template`) and not at template instantion time (`oc process`).
Signed-off-by: Gerd Oberlechner <goberlec@redhat.com>
=> remove external-dns provider variable from openshift template parameters

control-plane-operator/controllers/hostedcontrolplane/ingress/router.template
Currently the route expose strategy doesn't work for private clusters
because the routers default backend is the public KAS route which
doesn't exist.
Use the internal route instead as it always exists.
Ref https://issues.redhat.com/browse/HOSTEDCP-485
Fixes #
**Checklist**
=> APIServer route expose strategy: Fix with private clusters

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
Adds capabilities and clusterID to the fields we reconcile for the
ClusterVersion resource inside the guest cluster.
Only overrides should be allowed to be set by the administrator of the
guest cluster.
Fixes #
**Checklist**
=> Reconcile spec of clusterversion resource

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
We currently validate the OCP version when upgrading a HostedCluster.
However, we don't validate that it's valid with the SDN type on initial
install. This fixes the HostedCluster validation so we validate on
initial cluster creation.
Fixes #
**Checklist**
=> Validate OCP release version and SDN on initial install

control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
In https://github.com/openshift/hypershift/pull/1614 the KAS was changed
to always listen on port 6443 in oder to support privileged external
ports by doing the mapping external port -> internal port in the service
object.
This resulted in an invalid KAS networkpolicy if the external port is
not 6443, as it would allowlist the external port rather than 6443 where
the KAS is actually listening.
Fixes #
**Checklist**
=> Fix clusters that use LB expose strategy with a custom port

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
We are facing issues with OVN Kube CNI. RH JIRA: https://issues.redhat.com/browse/MULTIARCH-2631
Please temporarily allow OpenShift SDN CNI for PowerVS platform alone.
Once that is resolved will remove this change to block in PowerVS platform too.
Fixes #
**Checklist**
=> Allow OpenShiftSDN CNI for PowerVS platform

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
CNCC should be deployed in the management cluster: https://issues.redhat.com/browse/SDN-3236
This PR renders the CNCC credentials in the management cluster and allows CNO to create deployments.
CNO PR: https://github.com/openshift/cluster-network-operator/pull/1525
=> Move Cloud network config controller to the management cluster

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/oauth/route.go, support/util/expose.go
If that happens, we must not use the private router as it does not have
a public LB.
Fixes #
**Checklist**
=> Fix clusters where apiserver is exposed through LB and DNS indirection is used

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, test/e2e/util/util.go
It seems the CVO has issues applying this (complains that it failed
because it doesn't exist). We don't care about this, as there is no etcd
inside the hostedclsuter, so just omit it.
Fixes #
**Checklist**
=> Cleanup etcd rule manifest in CVO

cmd/infra/aws/destroy.go
The current check assumes that we directly get an AWS error back, but we
always get a [batch error back][0]. Fix the current check and make it
more robust by simply checking for the substring.
[0]: https://github.com/openshift/hypershift/blob/0f997c1a8a8abd5831ae96ca6eb8f7b4f4c627ec/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/batch.go#L353
Samplejob where this failed: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ipi-deprovision-aws-osd-hypershift/1562548271694483456
Fixes #
**Checklist**
=> AWS infra destroy: Handle bucket not found during batch delete

hypershift-operator/controllers/nodepool/haproxy.go, hypershift-operator/controllers/nodepool/haproxy_test.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
We are currently only using a default port for the Kube APIServer in the
public case (unless it's overriden). This doesn't take into
consideration a nodeport in the case that the APIServer is exposed via
NodePort. A safer configuration route is to take the port of the
external kubeconfig which already has the calculated external endpoint
of the Kube APIServer.
When using private link, we can keep using what we had before because
the port is fixed.
**Checklist**
=> Use kubeconfig port for worker haproxy

Makefile, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/assets/recording-rules.yaml, control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor_test.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go, support/util/metrics.go
Certain metrics sent to telemetry rely on recording rules. This PR adds
code to reconcile a prometheus rule resource in the control plane
namespace with those rules.
Fixes #[HOSTEDCP-400](https://issues.redhat.com//browse/HOSTEDCP-400)
**Checklist**
=> Add recording rules for telemetry

api/v1alpha1/nodepool_types.go, control-plane-operator/hostedclusterconfigoperator/cmd.go, control-plane-operator/hostedclusterconfigoperator/controllers/node/node.go, control-plane-operator/hostedclusterconfigoperator/controllers/node/node_test.go, control-plane-operator/hostedclusterconfigoperator/controllers/node/setup.go, hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, test/e2e/create_cluster_test.go, test/e2e/util/util.go
What:
This introduces a feature to reconcile Nodes with an opinionated Hypershift label pointing to the owning NodePool.
Why:
This is useful to list and filter Nodes by NodePool. This is useful for all operators to have a single and consistent bidirectional way for NodePool<->Node without having to reimplement the same logic, vendoring clients and consuming compute resources. E.g NTO tuneD.
How:
Change the NodePool controller to propagate the NodePool annotation down to Machines.
Introduce a Node controller within the HCCO manager:
- Watches Nodes.
- Find the Machine by using the appropriate CAPI annotations.
- Find the NodePool annotation.
- Apply the annotation as a Label into the Node.
In future we might extend this to support label propagation …
=> Add node controller to HCCO Manager

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/dnsoperator/dnsoperator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/dnsoperator.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/dns.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
Move the DNS operator into the management cluster so that the operator doesn't require that the hosted cluster have control-plane nodes.
* `control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go` (`manifestsToOmit`): Add "0000_70_dns-operator_02-deployment-ibm-cloud-managed.yaml".
* `control-plane-operator/controllers/hostedcontrolplane/dnsoperator/dnsoperator.go`: New file.
(`dnsOperatorContainerName`): New const.
(`Images`, `Params`): New types to describe the configuration of the DNS operator deployment in the management cluster.
(`NewParams`): New function.  Return a `Params` object for a DNS operator deployment.
(`ReconcileDeployment`): New function.  Reconcile a DNS operator deployment.
* `control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_contro …
=> NE-1043: Move the DNS operator into the management cluster

control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile_test.go
Stops continously reconciling the default ingress controller to allow
day 2 configuration of the ingress controller. This mirrors what the
installer does on a standalone OCP cluster.
Fixes #[HOSTEDCP-491](https://issues.redhat.com//browse/HOSTEDCP-491)
**Checklist**
=> Reconcile default ingress controller on creation only

control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcileDeployment.yaml
Client-go sets the token file location when using in-cluster config:
https://github.com/openshift/cluster-image-registry-operator/blob/39ea65a1ea93043e8b3ec156fde719760a807e1f/vendor/k8s.io/client-go/rest/config.go#L540
This in turn results in the token-file being periodically live-reloaded,
without needing to restart the controller:
https://github.com/openshift/cluster-image-registry-operator/blob/39ea65a1ea93043e8b3ec156fde719760a807e1f/vendor/k8s.io/client-go/rest/config.go#L75-L77
/assign @csrwng 
Fixes #
**Checklist**
=> Registry operator: Avoid restarts when token file changes

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator_test.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, test/e2e/util/util.go
Currently, the OVN SBDB never uses the private router, which is wrong.
It needs to be used if the cluster is private or if the apiserver is
exposed through a route and a custom hostname has been set for OVNSBDB.
As espcially the first check is likely to change, the settings for which
hostname to use and if the private router should be used are determined
in the CPO and passed on to the CNO.
Fixes https://issues.redhat.com/browse/HOSTEDCP-517
Related to https://issues.redhat.com/browse/HOSTEDCP-485
/hold
Requires https://github.com/openshift/cluster-network-operator/pull/1531 to merge first …
=> OVN SBDB: Use private router when possible

cmd/cluster/core/create.go
Fixes a panic when specifying the --wait flag on cluster creation
**Checklist**
=> Fix CLI panic when status.version is nil

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
This builds on top of https://github.com/openshift/hypershift/pull/1689
Handle all possible route hostnames and set OVN_SBDB_ROUTE_HOST.
With this change CNO should not modify OVN SBDB route hostname.
/cc @csrwng 
=> Bug SDN-3459: Handle long OVN SBDB route hostname

control-plane-operator/hostedclusterconfigoperator/controllers/resources/network/reconcile.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2631
Trying to add routing config for OVN Kube CNI for PowerVS platform 
Fixes #
**Checklist**
=> Add PowerVS OVN Kube routing config

cmd/nodepool/create.go, cmd/nodepool/powervs/create.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2534
Adding support for node pool create command for PowerVS platform.
Fixes #
**Checklist**
=> Add nodepool create cmd for PowerVS

control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/rbac.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
In standalone, this binding is created by the
cluster-kube-apiserver-operator: https://github.com/openshift/cluster-kube-apiserver-operator/blob/9d023ca0121c1c9509666ec5add93c6d43b4471d/bindata/assets/kube-apiserver/delegated-incluster-authentication-rolebinding.yaml
Fixes https://issues.redhat.com/browse/OCPBUGS-990
Fixes #
**Checklist**
=> Add missing rbac for authentication reader

control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, konnectivity-socks5-proxy/main.go
This changes makes us route LDAP IDPs in the oauth server to the guest
VPC by:
* Setting the ALL_PROXY env var to the ldap dialer will use the socks5
sidecar
* Extending the socks5 sidecar to optionally resolve everything through
the guest clusters cluster-dns
Ref https://issues.redhat.com/browse/HOSTEDCP-421
Fixes #
**Checklist**
=> Route LDAP IDPs in the oauth server through guest VPC

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
Add socks5 proxy image to CNO so it can be used for ovnkube-master to enable grpc connectivity with the worker nodes.
CNO: https://github.com/openshift/cluster-network-operator/pull/1539
=> SDN-3283: CNO: Add an environment variable with socks5-proxy image

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Handle long route hostnames and set OVN_SBDB_ROUTE_HOST.
This is a partial backport of https://github.com/openshift/hypershift/pull/1711 that only handles long route names.
As a follow up we should also backport https://github.com/openshift/hypershift/pull/1689 and the rest of the route hostname handling for CNO. 
=> [release-4.11] Bug OCPBUGS-1367: CNO: Handle long OVN SBDB route hostnames

hack/ci-test-e2e.sh
gotestsum's generated junit.xml doesn't have a suite name, and the test
names themselves are really generic sounding, e.g. 'TestAutoscaling'.
Adding a suite name will help us identify them in Sippy as belonging to
hypershift.
I couldn't find a way with gotestsum to get it to put something useful
in the suite name, so this just hacks it in with sed.  Open to better
solutions.
[TRT-506](https://issues.redhat.com//browse/TRT-506)
**Checklist**
- [N/A] This change includes docs. 
- [N/A] This change includes unit tests.
=> Ensure generated junit.xml has a defined suite name

control-plane-operator/controllers/hostedcontrolplane/cloud/kubevirt/manifests.go, control-plane-operator/controllers/hostedcontrolplane/cloud/kubevirt/providerconfig.go, control-plane-operator/controllers/hostedcontrolplane/cloud/kubevirt/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Add new External cloud provider for Kubevirt platform
This new controller is running in the management cluster, in the
controlplane namespace
The infrastructure used for this controller is the management cluster,
therefore as part of the deployment, creating special ServiceAccount
including very limited permissions inside the namespace (Services, VMs
and VMIs)
For more info about the Kubevirt-cloud-controller-manager see:
https://github.com/openshift/cloud-provider-kubevirt
**Checklist**
=> Add Kubevirt Cloud Controller Manager

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_route_cm.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/pki/openshift.go, control-plane-operator/controllers/hostedcontrolplane/routecm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/routecm/params.go, control-plane-operator/controllers/hostedcontrolplane/routecm/service.go, control-plane-operator/controllers/hostedcontrolplane/routecm/servicemonitor.go, support/metrics/sets.go
In 4.12 the controller that converts ingress to routes has been separated from the main openshift controller manager into its own process. In HyperShift, we need to create a separate deployment along with corresponding service and servicemonitor to run the separate controller.
Fixes broken origin conformance tests
**Checklist**
=> Add separate deployment for openshift route controller manager

control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, ignition-server/cmd/run_local_ignitionprovider.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/controllers/tokensecret_controller_test.go, support/util/util.go, support/util/util_test.go
This PR compresses and base64-encodes the Ignition configs before placing them into a K8s ConfigMap. K8s ConfigMaps (and Secrets) have a 1 MB size limitation and in practice, the Ignition config can be around 280KB. Over time, this size could grow and exceed the 1 MB limit. Gzipped, this drops to around 78 KB giving us much more headroom. We also need to base64-encode the contents since ConfigMaps cannot store binary data.
This should be merged after https://github.com/openshift/machine-config-operator/pull/3280 since that PR implements the MCO-side decompression / decoding steps.
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira …
=> gzip and base64-encode ignition configs

control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go
**What this PR does / why we need it**
Currently gitlab oauth is broken as it references a secret which does not necessarily exist.
ref https://issues.redhat.com/browse/HOSTEDCP-421
**Checklist**
=> Specify ca for gitlab oauth only when passed as input

control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-certified.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-community.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-marketplace.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-operators.deployment.yaml
4.12 images are not published yet.  4.11 is the latest.
Pulls fix for slow catalog start from https://github.com/operator-framework/operator-lifecycle-manager/pull/2791
=> update OLM catalogs to 4.11

control-plane-operator/controllers/hostedcontrolplane/routecm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/routecm/params.go
The route controller manager was recently separated into its own image and is no longer a subcommand of openshift-controller-manager. This change switches to using the separate route-controller-manager image and adjusts the deployment for it accordingly.
**Checklist**
=> Use separate image for route controller manager

control-plane-operator/controllers/hostedcontrolplane/kas/assets/recording-rules.yaml
This PR adds a recording rule that exists in standalone OCP which counts the number of nodes using custom TuneD profiles in the cluster. This metric is sent via telemetry to get an idea of how many users are customizing tuning on nodes.
Part of enabling Node Tuning of HyperShift hosted cluster nodes: [PSAP-742](https://issues.redhat.com/browse/PSAP-742)
**Checklist**
=> Add recording rule for NTO metric needed in telemetry

Dockerfile
Because we include the control-plane-operator in the hypershift-operator image, we normally use that image when testing hypershift locally. The hypershift-operator image should have the same labels as the control plane operator one. This commit adds the most recent label to the hypershift-operator image.
**Checklist**
=> Update Dockerfile with same labels as Dockerfile.control-plane

api/v1alpha1/nodepool_types.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/metrics.go
Made the platform specific condition types for PowerVS, KubeVirt, and AWS a generic condition type
Fixes [HOSTEDCP-425](https://issues.redhat.com/browse/HOSTEDCP-425)
**Checklist**
=> Make NodePool platform condition types generic

test/e2e/util/util.go
Switching to file-based catalogs (FBC) in 4.11 has made `registry` container start times highly variable, sometimes in excess of the 150s `StartupProbe` timeout.
Exclude those pods from the restart check for now so they don't flake the e2e runs.
https://github.com/openshift/hypershift/pull/1746
https://github.com/operator-framework/operator-lifecycle-manager/pull/2791
=> test: e2e: exclude catalog pods from restart check

test/e2e/e2e_test.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2967
Need this since we want to pass custom inputs for these args.
Fixes #
**Checklist**
=> Add compute and memory args for powervs e2e

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go
- Prevents kubeletconfigs.machineconfiguration.openshift.io and controllerconfigs.machineconfiguration.openshift.io CRDs from being created in the HyperShift cluster
Fixes [HOSTEDCP-516](https://issues.redhat.com/browse/HOSTEDCP-516)
**Checklist**
=> Remove KubeletConfig & ContainerRuntimeConfig CRDs

support/upsert/loopdetector.go
Fix this flake
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-e2e-aws-periodic/1580166552538320896
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-e2e-aws-periodic/1580166552538320896/artifacts/e2e-aws-periodic/run-e2e/artifacts/TestReplaceUpgradeNodePool_PreTeardownClusterDump/namespaces/e2e-clusters-lhxk9-example-b5vhz/core/pods/logs/hosted-cluster-config-operator-7dd7bc5b8f-hdsk4-hosted-cluster-config-operator.log
I think we are just updating the Node legitimately a lot and triggering the loop detector
=> increase loop detector threshold to 10

control-plane-operator/hostedclusterconfigoperator/controllers/resources/registry/registry.go
When setting the image registry storage to EmptyDir{}, a reconcile loop is occurring for the KubeVirt and None platforms.
The issue is that the the `imageregistry.spec.storage` struct has a `managementState` field that now receives an default value, but our HCCO reconcile loop clobbers that default value over and over again.
Example. HCCO sets
```
spec:                   
httpSecret: f840c08af1fe8d5a9e18467f6f304afd39a83b282efa201a6a76c7b836c0938cbfdcb25f039606b7170bb7ae42a793d03170f1ada8740a823732c45f2d366fdb
logLevel: Normal
managementState: Managed
observedConfig: null
operatorLogLevel: Normal  
proxy: {}
replicas: 1
requests: 
read:
maxWaitInQueue: 0s
write:
maxWaitInQueue: 0s                   
storage:
emptyDir: {}      
```
Then the image registry gets the …
=> Fix image registry reconcile loop

ignition-server/controllers/local_ignitionprovider.go, ignition-server/controllers/local_ignitionprovider_test.go, support/releaseinfo/registryclient/client.go
Handles manifest listed images and extracts correct mco image based on the managed cluster's arch. This allows you to create HyperShift hosted control planes on other architectures other than AMD64.
Fixes [ARMOCP-441](https://issues.redhat.com//browse/ARMOCP-441)
**Checklist**
=> Extracts correct mco image based on managed cluster's arch

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
A side-scenario bug could happen when someone or some piece deletes the OIDC configuration while it's in use. The race condition ends on the AWS Instance deleted and the platform provider cannot continue with the AWS components deletion.
For that we've set the default status as false the ValidOIDCConfiguration status condition, then always will come from false state and rechecked in a posterior step of the reconcile loop.
Fixes https://issues.redhat.com/browse/HOSTEDCP-528
**Checklist**
=> bug: Fixes HOSTEDCP-528, OIDCConfigurationInvalidReason should be always present

docs/content/how-to/automated-machine-management/index.md, docs/content/how-to/automated-machine-management/scale-to-zero-dataplane.md, docs/mkdocs.yml
Documented the "Scale data plane to zero" workflow to allow the customers to save money and compute time. It's mainly focussed in AWS but should be provider agnostic.
Fixes #[HOSTEDCP-576](https://issues.redhat.com//browse/HOSTEDCP-576)
**Checklist**
=> feat: Added "Scale dataplane to zero" workflow to the documentation

cmd/cluster/kubevirt/OWNERS, cmd/install/assets/cluster-api-provider-kubevirt/OWNERS, control-plane-operator/controllers/hostedcontrolplane/cloud/kubevirt/OWNERS, control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/OWNERS, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/OWNERS, hypershift-operator/controllers/nodepool/kubevirt/OWNERS, hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
This PR proposes that we add @davidvossel (me) and @nirarg as approvers for the areas of code isolated to the KubeVirt platform.
Note that the changes to the nodepool kubevirt.go file are merely to refactor that code into a separate isolated package. No change in behavior is expected.
=> Add KubeVirt Platform Owners

docs/content/how-to/agent/create-agent-cluster.md
Signed-off-by: Mario Vazquez <mavazque@redhat.com>
Updates the agent provider docs.
**Checklist**
=> Updated Agent provider docs

api/fixtures/example_ibmcloud_powervs.go, api/v1alpha1/nodepool_types.go, cmd/cluster/core/create.go, cmd/cluster/powervs/create.go, cmd/nodepool/powervs/create.go, docs/content/reference/api.md, hypershift-operator/controllers/nodepool/powervs.go, test/e2e/e2e_test.go
Add custom types for enum fields in PowerVSNodePoolPlatform.
Constants used only for PowerVSNodePoolProcType not for PowerVSNodePoolStorageType, PowerVSNodePoolImageDeletePolicy since we are only using default value defined via kubebuilder. In future if requires will define constants and use it.
Fixes https://github.com/openshift/hypershift/issues/1769
Fixes https://issues.redhat.com/browse/MULTIARCH-2975
Fixes #
**Checklist**
=> Add custom types for enum fields in PowerVSNodePoolPlatform

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go
Some of our KubeVirt csi containers didn't have resource requests and pull policy set. This wasn't caught by CI initially when kubevirt-csi was merged due to this openshift/release[ issue that caused the presubmit not to use the latest CPO/HCCO in the pr](https://github.com/openshift/release/pull/32903). Now that the ci issue is resolved, we have ci failures due to the requests check.
This PR fixes the following issues in our KubeVirt e2e CI.
```
util.go:698: container csi-provisioner in pod kubevirt-csi-controller-c948d65b9-w858n has no resource requests
=== RUN   TestCreateCluster/EnsureAllContainersHavePullPolicyIfNotPresent
util.go:424: container csi-driver in pod kubevirt-csi-controller-c948d65b9-w858n has doesn't have imagePullPolicy IfNotPresent but Always
```
=> Ensure kubevirt-csi containers all have resource.Requests and PullPolicy set

cmd/cluster/powervs/destroy.go, cmd/infra/powervs/create.go, cmd/infra/powervs/destroy.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2974
Fixes https://issues.redhat.com/browse/MULTIARCH-2980
Fixes #
**Checklist**
=> PowerVS: Bug fix on flags usage

cmd/cluster/aws/create.go
Currently we use the default gp2 volumes for etcd's PV because we don't default a storage class in the `EtcdSpec` so the cluster uses the default storage class, which is still gp2.
Because the default size of the volume is 4Gi and IOPS are provisioned proportial to size in gp2, the PV only has 100 IOPS and could be the cause of our CI troubles.  gp3 is 3000 IOPS at any size.
Switch to gp3 volumes by default, provided by the `gp3-csi` storage class in OpenShift, for etcd PVs.
Oh, and it is cheaper.
=> aws: use gp3-csi storage class by default

control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/reconcile.go
konnectivity-agent is overly verbose as currently configured. Dropped loglevel from 4 to 3, removes lines
`received DATA`
`write to remote`
`close connection`
`received DIAL_REQ`
=> reduce konnectivity-agent log verbosity

api/v1alpha1/nodepool_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/content/how-to/node-tuning.md, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, test/e2e/nodepool_nto_machineconfig_test.go
This PR renames the spec.TunedConfig field of the NodePool API to spec.tuningConfig. This is needed to keep the name general because we will likely use this field to reference PerformanceProfiles later on when we enable the PAO / PerformanceProfile functionality (~4.13 timeframe). 
As discussed in the HyperShift project sync meeting, we would like to make the change while the NodePool API is still in alpha.
/cc @jlojosnegros
Related to [PSAP-742](https://issues.redhat.com/browse/PSAP-742) and [CNF-6291](https://issues.redhat.com/browse/CNF-6291)
**Checklist**
=> NodePool API: rename spec.tunedConfig to spec.tuningConfig

OWNERS
While I've made an effort to isolate as much of the KubeVirt platform into separate directories as possible, the reality is much of our work at least touches other components as an entry point into our platform specific code. In order to make the KubeVirt hypershift platform more self sufficient, I'm asking for project wide approval access with the understanding that I'm only approving items isolated to the KubeVirt platform initially.
Note that I didn't put myself as a project wide reviewer. I'm already a reviewer in all the kubevirt directories of openshift/hypershift, so I should get automatically assigned as a reviewer just for KubeVirt related PRs.
=> Adds davidvossel as approver

control-plane-operator/hostedclusterconfigoperator/controllers/resources/network/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/network/reconcile_test.go
The ovn-k cluster has a CIDR for internal communication this CIDR appear
at the packages if the communication is from infra to tenant [1], so
ovn-k tenant routing get confused. This change use a non default value
for the tenant ovn-k V4InternalSubnet so there is no problem with that.
Depends on:
- https://github.com/openshift/cluster-network-operator/pull/1582
Fixes https://issues.redhat.com/browse/OCPBUGS-1150
**Checklist**
=> network: Use non default ovn-k V4InternalSubnet at tenant

docs/content/how-to/automated-machine-management/nodepool-upgrades.md, docs/content/how-to/upgrades.md
Added docs for InPlace upgrades and a stub for Replace upgrade nodepools. Not sure if this is the right place to do so but thought I'd start here.
This assumes the changes in https://github.com/openshift/hypershift/pull/1757 and https://github.com/openshift/hypershift/pull/1656 are present.
=> Docs: add nodes for InPlace Upgrade NodePools

docs/content/getting-started.md
=> docs: fix getting-started.md typo

docs/content/how-to/agent/create-agent-cluster.md
This PR is due to https://bugzilla.redhat.com/show_bug.cgi?id=2081788 - the new metallb-operator no longert support OwnNamespace InstallMode. 
Also, AddressPool was deprecated in favor of IPAddressPool
Fixes #
**Checklist**
=> Docs: Updated `Handling Ingress` section in create agent cluster to se updated metallb operator

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
Recently CNO started deploying cloud network config controller in the management cluster. 
CNCC connects to cloud providers so it should use the management cluster proxy if required. 
Pass the settings to CNO so it can use them to deploy CNCC with correct proxy settings.
CNO PR: https://github.com/openshift/cluster-network-operator/pull/1577
=> SDN-3508: Add proxy env variables to CNO deployment
