openshift/hypershift

api/v1alpha1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
This bug happens when you try to provision a HC and you have not created the PullSecret. The reconcile process will try to pull the ReleaseImage and verify it, but it cannot because cannot recover the Pull Secret. 
With the current verification process the controller returns 'nil' and after 7 tries, the reconcile process gets blocked. 
The fix validates this situation of the missing pull secret before this second check, but in this case the controller returns an error, which made possible the controller to wait indefinitely until the PullSecret gets created by the user.
Fixes: [HOSTEDCP-569](https://issues.redhat.com//browse/HOSTEDCP-569)
**Checklist**
=> bug: HOSTEDCP-569 HC controller blocked reconcile verifying releaseImage

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/main.go, support/util/services.go
Using a 2-term selector for events in the client cache results in no events listed when querying for events. The code that looks at events will skip over 'Normal' type of events already. 
This fixes reporting of cloud provider issues while provisioning infra for a control plane such as apiserver load balancer, etcd pv's, etc.
ref https://issues.redhat.com/browse/HOSTEDCP-592
**Checklist**
=> Use default namespace filtering for events

api/v1alpha1/nodepool_types.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/controllers/tokensecret_controller_test.go
The motivation to progress on this was an OCM cluster runing an old version of the HO was encoding the MachineConfig in a way the CPO ign server was unable to decode. This resulted in instances not becoming Nodes with no clear reason.
ref https://issues.redhat.com/browse/HOSTEDCP-637
**Checklist**
=> Signal ignition server payload generation in NodePool conditions

api/v1alpha1/hostedcluster_types.go, api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hack/app-sre/saas_template.yaml
This is to prevent conflicts from happening during server side apply as see in https://issues.redhat.com/browse/HOSTEDCP-644
Source:
https://github.com/kubernetes/kube-openapi/blob/master/pkg/idl/doc.go#L42-L51 Examples https://github.com/openshift/api/search?q=listType
Fixes #
**Checklist**
=> Defines resourceTags merge granularity

docs/content/how-to/node-tuning.md, hypershift-operator/controllers/nodepool/nodepool_controller.go
Update the ConfigMap key in the docs from tuned to tuning, as this was missing in PR#1802. Improve logs when wrong key is used or the ConfigMap has no contents.
Related to [PSAP-742](https://issues.redhat.com/browse/PSAP-742). Docs fix should have been included in #1802.
**Checklist**
/cc @jmencak @liqcui
=> node tuning: Fix docs and improve logs

hypershift-operator/controllers/nodepool/nodepool_controller.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/controllers/tokensecret_controller_test.go
Storing the machine payload in the token secrets causes performance issues at a large scale. We can omit that field in replace upgrade node pools
Fixes #1843
ref https://issues.redhat.com/browse/HOSTEDCP-604
**Checklist**
=> Don't store machine payload in token secret for replace node pools

Dockerfile
Changing entrypoint to exec form to allow for argument to be passed to the hypeshift executable
Signed-off-by: Arvin Amirian <aarvin@gmail.com>
Fixes #1806
=> Changing entrypoint to exec form to allow for argument to be passed to the hypeshift executable

test/e2e/util/util.go
Temporarily skip reporting crash errors for the machine-approver so CI can get unstuck. Requires followup investigation.
**Checklist**
=> Add crashing pods exception for machine-approver

api/scheme.go, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/hostedclusterconfigoperator/api/scheme.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/api/scheme.go, support/rhobsmonitoring/scheme.go
This change enables the CLI, hypershift operator, and control plane operator to optionally use the rhobs.monitoring/v1 group version when creating and reconciling monitoring resources. This is a global setting that must be set on the HyperShift  operator and gets propagated to all hosted control planes managed by the operator.
This will enable the HyperShift operator to create resources that can be understood by the RHOBS monitoring stack.
Fixes #[HOSTEDCP-624](https://issues.redhat.com//browse/HOSTEDCP-624)
**Checklist**
=> Optionally use rhobs.monitoring group for monitoring resources

api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hack/app-sre/saas_template.yaml
This uses the new CEL validations available in kubernetes 1.25 and
above, requiring OpenShift 4.12 or greater.  I tested with OpenShift
4.10 and while the validations do not work, they are also ignored so it
should be safe to have them in place for all versions.
For HOSTEDCP-582
Fixes #
**Checklist**
=> HOSTEDCP-582: Add CEL immutability validations to nodepool.

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, support/releaseinfo/registryclient/client.go, support/util/imagemetadata.go, test/e2e/util/fixture.go
Retrieves the CAPI and CAPA image components from the release image rather than registry.ci.openshift.org/hypershift/cluster-api:v1.0.0 and registry.ci.openshift.org/hypershift/cluster-api-aws-controller:v1.1.0 respectively
Fixes [HOSTEDCP-577](https://issues.redhat.com/browse/HOSTEDCP-577)
**Checklist**
=> Retrieve CAPI/CAPA from release image

cmd/cluster/core/create.go, test/e2e/e2e_test.go, test/e2e/util/fixture.go
This feature enable us to avoid issues from local E2E tests execution like this one:
**Checklist**
=> Added new flag on E2E test to avoid send metrics from Local executions

control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader.go
The MCD pods currently gets created when a node is marked for update, but doesn't get removed until the whole pool finishes updating.
To conserve resources, this adds logic to remove any idle upgrade pods.
The longer term goal is to use daemonsets instead, see: https://github.com/openshift/hypershift/pull/1757, but as a proof-of-concept, spinning this out separately from https://github.com/openshift/hypershift/pull/1757#issuecomment-1294001810
I am happy to close this in favour of doing daemonsets, since this intermediary step seems of limited value, and the daemonset does dynamic scheduling as well
=> inplaceupgrade: delete idle MCD pods

control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader.go, control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader_test.go
It is possible to have 0 or negative capacity, and the code doesn't check for it, leading to a potential panic.
Add that check and some unit tests for that function.
=> inplaceupgrade: add capacity check and tests

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/kcm/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/oapi/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/ocm/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go, control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcilePodMonitor.yaml, control-plane-operator/controllers/hostedcontrolplane/routecm/servicemonitor.go
The recent split in CAs from root-ca requires that servicemonitors and podmonitors that we create use the client-ca bundle that can validate the root-ca which is used for creating metrics serving certs.
**Checklist**
=> Fix CA bundle in podmonitors/servicemonitors

docs/content/how-to/aws/migrate-hosted-cluster.md
After the HC migration, the OVN pods still have the connections "opened" with the old OVN master in the source Management cluster. In order to create new pods in the HC and regenerate the network sandbox, we need to delete the OVN pods to connect with the new OVN Master in the destination Management cluster.
**Checklist**
=> doc: OVN Pod restart needed after the HC migration

api/v1alpha1/hostedcluster_types.go, cmd/bastion/aws/create.go, cmd/cluster/aws/create.go, cmd/cluster/azure/create.go, cmd/cluster/core/create.go, cmd/cluster/core/dump.go, cmd/cluster/powervs/create.go, cmd/consolelogs/aws/getlogs.go, cmd/infra/aws/create.go, cmd/infra/azure/create.go, cmd/infra/powervs/destroy.go, cmd/install/install.go, cmd/install/install_render_test.go, cmd/version/version.go, control-plane-operator/hostedclusterconfigoperator/cmd.go, ignition-server/cmd/run_local_ignitionprovider.go, ignition-server/controllers/image_file_cache.go, ignition-server/controllers/image_file_cache_test.go, ignition-server/controllers/local_ignitionprovider.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go, support/releaseinfo/pod_provider.go, support/testutil/testutil.go, support/util/util.go, test/e2e/e2e_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/util/dump/journals.go, test/setup/main.go
As of Go 1.16, the same functionality, previously provided in `ioutil`, is now provided by package `io` or package `os`, and those implementations should be preferred.
Fixes [HOSTEDCP-649](https://issues.redhat.com/browse/HOSTEDCP-649)
**Checklist**
=> Replace deprecated ioutil calls

control-plane-operator/controllers/hostedcontrolplane/kas_pki_setup.go, control-plane-operator/controllers/hostedcontrolplane/pki/ca.go
This is a continuation of the client-cert trust split.
/assign @csrwng 
/cc @ibihim
=> AUTH-323: pki: remove root-ca from the aggregator CA bundle

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/kcm/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/oapi/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/ocm/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go, control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcilePodMonitor.yaml, control-plane-operator/controllers/hostedcontrolplane/routecm/servicemonitor.go
The total client bundle works for now because the root-ca is included in it, but when it's removed, ServiceMonitors/PodMonitors will be broken. This switches them to the root-ca bundle since that is what signs our metrics serving certs.
**Checklist**
=> Use the root CA bundle in ServiceMonitors/PodMonitors

docs/content/how-to/aws/deploy-aws-private-clusters.md
The PR fixes a command to find private node IP addresses by a filter to use `$INFRA_ID` instead of `$CLUSTER_NAME` in the tag name
Signed-off-by: Moti Asayag <masayag@redhat.com>
**Which issue(s) this PR fixes** *:
Fixes https://github.com/openshift/hypershift/issues/1904
**Checklist**
=> Update filter for listing ec2 private nodes

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/manifests/infra.go, control-plane-operator/controllers/hostedcontrolplane/oauth/route.go, hypershift-operator/main.go, support/util/route.go, support/util/util.go, test/e2e/util/util.go
This PR is a refactor of the route reconcilation with a change needed for https://issues.redhat.com/browse/HOSTEDCP-572
Private routes for `oauth` and `kube-apiserver` are now seperate and the resource name is suffixed with `-private` and the route has a new `hypershift.openshift.io/private-route` label.
When the HCP router is deployed in an `endpointAccess: Private` mode, it will only admit routes with the new label.  This prevents it from admitting the public routes with the wrong `routerCanonicalHostname` during a `Private` -> `PublicAndPrivate` transition.
The refactor combines all route reconciliation on a common path in the `util` package in separate `ReconcilePublicRoute` and `ReconcilePrivateRoute` functions.
Note: This leaves the `kube-apiserver-internal` orphaned on upgrade as …
=> refactor route reconcilation

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/mcs/params.go, control-plane-operator/controllers/hostedcontrolplane/mcs/reconcile.go, ignition-server/controllers/local_ignitionprovider.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/util/node.go
The client certificate used by the Kube APIServer is no longer signed by
the root-ca. We need to pass the right CA to the kubelet so it can
properly authenticate the KAS.
Added e2e check to ensure we don't break KAS->Kubelet communication in the future.
Fixes #OCPBUGS-3900 
**Checklist**
=> OCPBUGS-3900: Fix CA passed to MCO for kubelet 

hypershift-operator/controllers/nodepool/conditions.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
At the moment if the infra for a Machine or the software for a Node fail to operate it's completely transparent for NodePool API consumers.
We need to solve agreggation upstream:
https://github.com/kubernetes-sigs/cluster-api/pull/6218
https://github.com/kubernetes-sigs/cluster-api/pull/6025
This PR is a stopgap to mitigate the above and facilitate reaction and decisions for NodePool consumers.
Examples
In progesss:
```
- lastTransitionTime: "2022-11-30T09:03:08Z"
message: |
Machine agl-nested-us-east-1a-6d9fcd6565-n5lpf: InstanceProvisionStarted
Machine agl-nested-us-east-1a-6d9fcd6565-k872l: InstanceProvisionStarted
observedGeneration: 6
reason: InstanceProvisionStarted
status: "False"
type: AllMachinesReady
- lastTransitionTime: "2022-11-30T09:03:08Z"
message: |
Machine …
```
=> Add AllMachinesReady and AllNodesHealthy conditions to NodePool

api/v1beta1/hostedcluster_conditions.go, api/v1beta1/hostedcluster_types.go, cmd/infra/aws/iam.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
There's scenarios where the identity provider might have been conflicted, e.g. delete by accident. In that case the HC is not able to operate successfully e.g. aws endpoints, ec2 machines... and there's no clear signal in the HC. This is also true if the HC is in deleting state, which will hang forever with no clear signal.
This PR tries to allivites those scenarios by capturing them in a condition.
Ref [HOSTEDCP-660](https://issues.redhat.com/browse/HOSTEDCP-660)
**Checklist**
=> Add ValidIdentityProvider condition

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go, hypershift-operator/main.go, support/releaseinfo/fake/fake.go, support/util/imagemetadata.go
This allows OCP 4.13 clusters to work while we bump the CAPA dependency (and API version) in our code
**Checklist**
=> Temporarily override the CAPI AWS provider image 

hypershift-operator/controllers/nodepool/nodepool_controller.go
https://github.com/openshift/hypershift/pull/1907 introduced unchecked condition logic
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x266e6a4]
goroutine 1131 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118 +0x2d7
panic({0x2e3a780, 0x48d4120})
/usr/local/go/src/runtime/panic.go:844 +0x25a
github.com/openshift/hypershift/hypershift-operator/controllers/nodepool.(*NodePoolReconciler).reconcile(0xc000ef6a80, {0x36aca20, 0xc00cf7b980}, 0xc00a920000, 0xc00a86fd40) …
```
=> fix nil deref in nodepool controller

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/storage.go, control-plane-operator/controllers/hostedcontrolplane/storage/assets/10_deployment-hypershift.yaml, control-plane-operator/controllers/hostedcontrolplane/storage/assets/README.md, control-plane-operator/controllers/hostedcontrolplane/storage/assets/assets.go, control-plane-operator/controllers/hostedcontrolplane/storage/assets/role.yaml, control-plane-operator/controllers/hostedcontrolplane/storage/assets/rolebinding.yaml, control-plane-operator/controllers/hostedcontrolplane/storage/envreplace.go, control-plane-operator/controllers/hostedcontrolplane/storage/envreplace_test.go, control-plane-operator/controllers/hostedcontrolplane/storage/operator.go, control-plane-operator/controllers/hostedcontrolplane/storage/params.go
Move cluster-storage-operator + its operands (aws-ebs-csi-driver-operator + AWS EBS CSI driver control plane pods) to HyperShift mgmt. cluster.
[cluster-storage-operator](https://github.com/openshift/cluster-storage-operator/pull/318) must be updated first!
**Testing**
Update control-plane-operator RBACs:
1. Build your own hypershift-operator image.
1. Clone  openshift/hypershift git repo + apply this PR.
2. Build the custom image, e.g. quay.io/jsafrane/hypershift:latest:
```sh
make docker-build docker-push quay.io/jsafrane/hypershift:latest
```
2. Install hypershift-operator from the custom image: `./hypershift install --hypershift-image=quay.io/jsafrane/hypershift:latest ...`
Install a guest cluster:
1. Build a release that contains this PR + …
=> STOR-1037: Add cluster-storage-operator to mgmt. cluster

availability-prober/availability_prober.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, support/util/containers.go
Fixes an issue in CI where the CNO starts before the `cluster` Infrastructure resource is available.
=> availability-prober: add wait for cluster infrastructure resource

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go
Consider the following `services` block on a cluster with `endpointAccess: PublicAndPrivate`.
```
services:
- service: APIServer
servicePublishingStrategy:
type: LoadBalancer
- service: OAuthServer
servicePublishingStrategy:
route:
hostname: oauth-sjenning-guest.service.ci.hypershift.devcluster.openshift.com
```
Currently the `routerCanonicalHostname` is not set on the `oauth` route because the router is not configured with the `ROUTER_CANONICAL_HOSTNAME` env var because we only set it when the KAS is exposed through the router.  This results in external-dns not registering the oauth DNS record and the `console` ClusterOperator in the guest failing to become Available since it requires oauth connectivity for `console` pods to be ready.
We should set the `ROUTER_CANONICAL_HOSTNAME` on the …
=> always set ROUTER_CANONICAL_HOSTNAME

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
All metrics produced by a HostedControlPlane should contain the _id label identifying the cluster that they come from
**Checklist**
=> Add clusterID to ignition-server PodMonitor

control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/storage.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/storage/reconcile.go
Overwrite any user changes in `Storage` and `ClusterCSIDriver` CRs that are managed by CPO and other operators in the hosted control plane.
**Checklist**
=> STOR-1038: Reconcile Storage and ClusterCSIDrivers in the guest clusters

hack/ci/install-cnv.sh
This makes hpp csi optional during the HS/KV platform's install of cnv.
=> Update cnv ci script to make hpp optional

control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/assets/05_operator_role-hypershift.yaml
This PR doesn't introduce any new functionality, it simply syncs manifests from https://github.com/openshift/cluster-csi-snapshot-controller-operator/tree/master/manifests.
The old manifests contain wildcards in RBAC rules, which is not recommended.
CC @openshift/storage
=> Bug 2066664: Sync manifests from cluster-csi-snapsht-controller-operator

cmd/cluster/powervs/create.go, cmd/infra/powervs/create.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2984
Removed some of the dup blocks like validating empty base-domain and generating infraID.
Fixes #
**Checklist**
=> Refactor powervs infra for reusing fields in create cluster cmd

cmd/cluster/agent/create.go, cmd/cluster/aws/create.go, cmd/cluster/aws/destroy.go, cmd/cluster/azure/create.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/cluster/core/destroy.go, cmd/cluster/kubevirt/create.go, cmd/cluster/none/create.go, cmd/cluster/powervs/create.go, cmd/util/secrets.go, docs/content/how-to/aws/create-aws-hosted-cluster-secret-credentials.md
* Documentation
* Secret support:
* Base Domain
* AWS Key ID
* AWS Secret Key 
* SSH Keys Public/private 
* Pull-Secret
This allows existing MCE credentials or new credentials created via the MCE console to be consumed by the CLI. This is a known quantity in MCE that is documented and utilized by MCE/ACM users
Signed-off-by: Joshua Packer <jpacker@redhat.com>
1. Allows the hypershift CLI to leverage MCE created Credential Secrets for the AWS provider.
2. This provides an easy repeatable provisioning flow with less chance of a typo
3. This helps the MCE Console generate/describe a hypershift cli command to create a cluster
4. Users can create secret to represent a number of parameters the CLI uses, having the secret ties nicely into a tekton task for …
=> Add CLI support for Multi-cluster engine secret:

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go
When upgrading from an AWS cluster that runs the cluster storage operator
inside the guest cluster, operand deployments such as the aws-csi-driver-operator,
aws-csi-driver-controller, csi-snapshot-webhook, and
csi-snapshot-controller need to be explicitly removed from the guest
cluster so that they won't fight with the deployments on the control plane side.
**Checklist**
=> Storage: cleanup operand deployments on upgrade

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Removes CAPI manager container command path since it can differ based on release image used.
N/A
**Checklist**
=> Remove CAPI manager container command path

control-plane-operator/controllers/hostedcontrolplane/kas_pki_setup.go, test/e2e/control_plane_upgrade_test.go
This is a continuation of the client-cert trust split.
/cc @ibihim
=> AUTH-323: pki: remove root-ca from the client CA bundle

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go, support/util/imagemetadata.go
Starting with 4.12, the CAPI/CAPA images we use should come from the release payload. In an MCE deployment, we should ignore env vars set by MCE for those images, but only if the release payload is >= 4.12.
**Checklist**
=> Ignore CAPI/CAPA env var image overrides for 4.12 and later

docs/content/how-to/agent/create-agent-cluster.md
fix doc description error. Now the nodepool name is not same with hostedcluster name anymore.  The nodepool name now is {hostedcluster}-{az}, e.g. 
```
$ oc get nodepool -n clusters
NAME                            CLUSTER              DESIRED NODES   CURRENT NODES   AUTOSCALING   AUTOREPAIR   VERSION       UPDATINGVERSION   UPDATINGCONFIG   MESSAGE
hypershift-ci-8712-us-east-2a   hypershift-ci-8712   2               2               False         False        4.12.0-rc.4  
```
**Checklist**
- [ x] This change includes docs.
=> [doc] fix nodepool name description error

api/v1beta1/nodepool_conditions.go, hypershift-operator/controllers/nodepool/conditions.go, hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, ignition-server/cmd/start.go
There're scenarios where is diffcult too understand why an instance does not become a Kubernetes Node. Once concrete problem is the instances because of reasons are not able to reach the ignition endpoint, e.g. bad networling blocking security groups.
This PR tries to makes obvious and expliciti when an instance for a NodePool was able to reach the ignition endpoint. When that happens the ign server creates an event, sends a metric and sets the conditions in the NodePool.
Additionally this PR delays MHC creation until the previous conditions is set and true, as otherwise keep recreating Machines in loop won't fix the problem but would rather result in very awkward UX.
ref https://issues.redhat.com/browse/HOSTEDCP-678
ref …
=> Signal when ignition is reached via event, metric and condition and delay MHC creation

support/util/containers.go
Need to set `Command` flags before container is copied to the pod spec
=> fix wait-for-infrastructure-resource flag on CNO availablity prober

control-plane-operator/controllers/hostedcontrolplane/pki/kas.go
=> add kubernetes.default to KAS certificate SAN

api/v1beta1/hosted_controlplane.go, api/v1beta1/hostedcluster_conditions.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/metrics.go
Adds two new metrics
hypershift_cluster_deletion_duration_seconds
hypershift_cluster_guest_cloud_resources_deletion_duration_seconds
As a consequence CloudResourcesDestroyed is bubble up from HCP into HC.
Ref https://issues.redhat.com/browse/HOSTEDCP-635
**Checklist**
=> Add metrics for hostedCluster deletion SLIs

hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
The ENTRYPOINT in the CAPA image should dictate the command used. This allows us to use either images built via OCP release process or via ACM pipeline.
**Checklist**
=> Remove CAPA command from deployment

hypershift-operator/metrics.go
Follow up for https://github.com/openshift/hypershift/pull/1956 to send the right clusterGuestCloudResourcesDeletionTime metric
Ref https://issues.redhat.com/browse/HOSTEDCP-635
Fixes #
**Checklist**
=> Fix send clusterGuestCloudResourcesDeletionTime metric

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
The code that propagated the HostedCluster configuration spec to the HostedControlPlane resource was dropped in the v1beta1 PR. This PR reinstates the propagation of the configuration to the HostedControlPlane resource.
Fixes #OCPBUGS-4973
**Checklist**
=> OCPBUGS-4973: Reinstate hosted cluster configuration propagation

control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator.go, control-plane-operator/controllers/hostedcontrolplane/storage/operator.go
All service accounts used to run workloads pulled from the release payload should use the pull secret that was specified for the HostedCluster. This commit adds the pull secret to the service accounts used for cluster-storage-operator and csi-snapshot-controller-operator
**Checklist**
=> Add pull secret to storage service accounts

control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go
https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler/cloudprovider/clusterapi#scale-from-zero-support
When deployed with NodePool with 0 replicas, `cluster-autoscaler` logs errors:
```
User "system:serviceaccount:clusters-sjenning-guest:cluster-autoscaler" cannot list resource "awsmachinetemplates" in API group "infrastructure.cluster.x-k8s.io" in the namespace "clusters-sjenning-guest
```
=> autoscaler get/list for infrastructure.cluster.x-k8s.io api group

test/e2e/olm_test.go
https://issues.redhat.com/browse/OCPBUGS-4600 is currently blocking CI
Skip the OLM test until it is fixed
=> test: disable OLM test until catalog pods are fixed

test/e2e/nodepool_autorepair_test.go, test/e2e/nodepool_machineconfig_test.go, test/e2e/nodepool_test.go
This PR refactors the E2E MachineConfig test. Also it implements a mechanism to signal the TestNodePool set of test to avoid context cancelation.
Fixes #[HOSTEDCP-686](https://issues.redhat.com/browse/HOSTEDCP-686)
**Checklist**
=> MachineConfig E2E test refactored

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, test/e2e/create_cluster_test.go, test/e2e/util/util.go
Right now in a private setup the ovnkube-sbdb route is never addmited as it's missing the label that let the ingress controller reconcile it.
This was most likely missed here https://github.com/openshift/hypershift/pull/1861/files.
The e2e included in this PR should prevent this from happening again.
Ref https://issues.redhat.com/browse/OCPBUGS-5026
**Checklist**
=> Set missing internal route label for ovnkube-sbdb  and add e2e smoke test for private clusters

control-plane-operator/controllers/hostedcontrolplane/etcd/params.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/main.go, dnsresolver/cmd.go
Waits until a reverse dns lookup of the pod's IP address returns the pod's expected hostname. This ensures that a statefulset does not rollout until names can be resolved.
**Checklist**
=> Add init container to etcd pods to test DNS

control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/machineapprover/reconcile.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/config/ownerref.go, support/config/ownerref_test.go
Updates HO to continue using `v1alpha1` ownerRefs for components (cluster-autoscaler, machine-approver, ignition-server) that will eventually move to CPO management. This will be the case for HCs < 4.12.
Fixes #1955 
**Checklist**
=> fix(ho): Use v1alpha1 ownerRef for future CPO managed components

test/e2e/nodepool_upgrade_test.go, test/e2e/util/util.go
We should not check the status of underlying Nodes in the `NodePool` during the NodePool upgrade tests.   This logic should be abstracted by the nodepool contoller and the test should simply wait for the NodePool status to report the upgrade is complete.
This is causing timeouts in the `TestInPlaceUpgradeNodePool` waiting for unready Nodes that never become unready.  At least one node becoming unready is not a test criteria for NodePool upgrade; only that the NodePool status eventually reports that the pool is upgraded.
=> test: e2e: remove node checks during NodePool upgrade test

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
https://issues.redhat.com/browse/HOSTEDCP-645
=> add KAS egress network policy

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
If the hcco is not available, the cpo will wait indefinitely for it to update hcp conditions to indicate that guest resources have been deleted. To solve that, the hcco will periodically update a condition to let the CPO that it's working on deletion. If the condition is not updated after a certain amount of time, the CPO gives up waiting and proceeds with the rest of the deletion.
Fixes # [HOSTEDCP-667](https://issues.redhat.com//browse/HOSTEDCP-667)
**Checklist**
=> Prevent cluster deletion hangs by using heartbeat condition

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml
Changes `aws-batch-change-interval` from 1s (default) to 10s.  Hopefully this results in fewer, larger change batches to avoid route53 rate limiting.
=> external-dns: set AWS batch internal to 10s

control-plane-operator/controllers/hostedcontrolplane/dnsoperator/dnsoperator.go, control-plane-operator/controllers/hostedcontrolplane/nto/clusternodetuningoperator.go
Our recording rules aggregate on the `app` label and two HCP components lack that label
=> add missing app label to HCP components

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kubevirt.go
This PR adds logic to automatically install a default storage class into kubevirt platform guest clusters that maps to the underlying infra's default storage class.
=> Add default kubevirt guest cluster storageclass

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
parameters were being passed in the wrong order.
Healthz handler should be the 7th parameter and managementClusterHasCapabilitySecurityContextConstraint be the 9th as seen here: https://github.com/openshift/hypershift/blob/release-4.11/control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go#L41
Hypershift operator is doing it correctly: https://github.com/openshift/hypershift/blob/ad40abf4f1ed00c7fb70d05bef26dbb2d15b14c2/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go#L1443-L1446
Fixing parameters being passed to reconcile the ignition server. 
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub …
=> Fix parameters used to reconcile the ignition server

api/v1beta1/hostedcluster_types.go, cmd/infra/aws/iam.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hack/app-sre/saas_template.yaml
route53 has very aggressive rate limiting and doing this health check of every reconcile loop can lead to rate limiting and delays in external-dns registration
=> avoid using route53 api for OIDC health check

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go, support/capabilities/management_cluster_capabilities.go
OpenShiftSDN bug prevent proper application of egress network policy.  We use `OpenShiftSDN` in our root CI cluster.
Workaround is to not apply the egress rules of the mgmt cluster is detected to be OCP with OpenShiftSDN.
https://issues.redhat.com/browse/OCPBUGS-2105
https://github.com/openshift/sdn/pull/464
=> workaround OpenShiftSDN network policy egress bug

hack/ci-test-e2e.sh, test/e2e/autoscaling_test.go, test/e2e/chaos_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/nodepool_nto_machineconfig_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/olm_test.go, test/e2e/util/util.go
Currently, we create test clusters with NodePools and AWS networking infra in all zones specified in the `--e2e.availability-zones` flag.
However, all test clusters are currently `InfrastructureAvailabilityPolicy: SingleReplica` and can operate on 2 workers in a single zone.
Limiting the test cluster to a single zone prevents a considerable number of AWS resources from being created, particularly NAT gateways.
This PR uses `--e2e.availability-zones` as a bank zones to which test clusters can be assigned and created.  It also removes the `-e2e.node-pool-replicas` flag from the e2e binary and allows each test to control this.
Tests default to running `InfrastructureAvailabilityPolicy: SingleReplica` with 2 workers in a single assigned zone.  `TestCreateCluster` exercises …
=> test: dynamically assign single AWS zone to SingleReplica guest clusters

api/fixtures/example.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go
Allows setting `nodeDrainTimeout` on NodePools created with `hypershift create cluster`
=> add node-drain-timeout flag to create cluster cmd

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas_pki_setup.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/mcs/params.go, control-plane-operator/controllers/hostedcontrolplane/mcs/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/pki/ca.go
The CA bundle that the kubelet uses to verify mTLS certificates needs to include the CA used to sign the KAS client certs to allow communication from the KAS as well as the CSR signer CA to allow service accounts that have the right RBAC to access metrics.
This commit adds a new CA bundle (kubelet-client-ca) that includes both the KASToKubelet signer as well as the CSR signer. This allows the prometheus-k8s service account to scrape metrics from the kubelet.
**Checklist**
=> Add CSR signer to Kubelet client CA

Makefile
[Because][1]:
```
Makefile:54: *** untracked files detected: M api/v1beta1/hosted_controlplane.go  M api/v1beta1/zz_generated.deepcopy.go  M cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml  M cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml  M hack/app-sre/saas_template.yaml.  Stop.
```
isn't as easy for contributors to fix, vs. giving them a patch with recommended changes to make to their local checkout, to bring it in line with what CI is expecting.
And actually, even with this pull request, I had trouble figuring out the changes I wanted, so in #1954, I've been supplementing with f77a0c4bc439641f3f5e03b2f1663a7468274fa1's:
```Makefile
verify: update staticcheck fmt vet promtool
...
$(eval STATUS = $(shell sh -c …
```
=> Makefile: Include full 'git diff' output

control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go
There was a missing nil check in the parsing when configOverride is not present.
This causes CPO to crash and the config is not applied
* Fixes https://issues.redhat.com/browse/HOSTEDCP-719
**Checklist**
=> Fix OpenID OAuth config parsing

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
=> cherry-pick #2006

api/v1beta1/hostedcluster_types.go, hypershift-operator/metrics.go
This extend existing metrics exposed by the HO to include hostedClusterInfo with relevant information for HCs. These metrics are useful to infer symptons and point to causes when observing a fleet of clusters. E.g. Lets say we notice a subset of customers having IDP issues but no reported outages on github. We would be able to analyze the metrics and indeed say that github was having issues if we had outages fleetwide across github. These metrics are used in ROSA today. In future if they grow in a very opinionated way we might want to decouple them from the HO.
ref …
=> Expose proxy, identityProviders and limited support metrics

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
The label is dropped when reported in metrics if it doesn't have a value.
**Checklist**
=> Add value to hosted control plane namespace label

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
resulting in failed reconciliation in the HCCO
```
{"level":"error","ts":"2023-01-16T17:00:11Z","msg":"Reconciler error","controller":"resources","object":{"name":""},"namespace":"","name":"","reconcileID":"80729130-cf29-4546-8453-fe52fdfe23a9","error":"failed to reconcile ClusterCSIDriver ebs.csi.aws.com: resourceVersion should not be set on objects to be created","errorCauses":[{"error":"failed to reconcile ClusterCSIDriver ebs.csi.aws.com: resourceVersion should not be set on objects to be created"}],"stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/root/go/src/github.com/openshift/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Co …
```
=> fix cluster csi driver reconcile

control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/namespaces.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
This commit adds pod security annotations to the kube-system namespace before reconciling the konnectivity agent daemonset. This prevents a warning that causes the kube-apiserver to crash.
**Checklist**
=> Kube API server panic: Fix podsecurity annotations on kube-system

control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/rbac.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
PodSecurityAdmissionController RBAC was added here: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/616. We need to do the same.
Ref https://issues.redhat.com/browse/HOSTEDCP-683
**Checklist**
=> policy-controller: add missing rbac

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
Now that metrics are back online,  adjusting some component that are overrunning their memory requests
=> adjust memory requests for HCP components

api/scheme.go
The dump cluster command is failing to ouptut artifacts because the scheme it uses to convert go types to resources is missing the imagev1 group, resulting in `unknown.unknown` in the types it needs to output and failing to output anything.
**Checklist**
=> Add imagev1 to scheme used by dump command

control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
This ensures that cloud platform specific node labels are ignored by the cluster autoscaler
Fixes #[HOSTEDCP-711](https://issues.redhat.com/browse/HOSTEDCP-711)
**Checklist**
=> Add autoscaler balancing ignore labels args

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
The timeout to proceed with deletion of the hostedcontrolplane is not taking effect because there is nothing requeueing the hcp resource. This adds a requeue time to the resource when waiting for cloud resource deletion.
**Checklist**
=> Requeue hostedcontrolplane when waiting for deletion

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/networkpolicy/manifests.go
When a LB service is created to expose a pod at kubevirt hosted cluster, at some environments (azure, google cloud) connectivity with LB ingress IP is not permited, this change add a network policy that permites ingress to all the ports for virt-launcher pod.
**Checklist**
=> kubevirt: Install virt-launcher networkpolicy

control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/rbac.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
The image trigger controller is used to trigger builds/deployments from imagestream tag events
**Checklist**
=> Add missing image trigger controller RBAC

control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/rbac.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Creation of this role was moved from the OAS to the OCM operator (which we don't run)
https://github.com/openshift/openshift-apiserver/pull/331
https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/270
We need to create this ClusterRole in the guest cluster.  Lack of this role is causing all `Server-Side apply` conformance tests to fail.
=> add system:deployer ClusterRole to HCCO

control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go
Bad copy from https://github.com/openshift/cluster-openshift-controller-manager-operator/blob/master/bindata/v3.11.0/openshift-controller-manager/deployer-clusterrole.yaml#L11-L26
Combined the `delete` but accidentally dropped the `patch` :man_facepalming: 
Causing failures of the `[Feature:DeploymentConfig]` conformance tests.
=> hcco: fix deployer role to include patch for replicationcontrollers

hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go
We're abandoning the pre-release branch in favor of the standard ocp related branches. This updates the capk image to reflect that.
=> Update internal capk image to match current devel branch

contrib/ci/README.md, contrib/ci/hypershift-ci-1.yaml
https://issues.redhat.com/browse/HOSTEDCP-603
This moves everything of value out of the https://github.com/openshift/hypershift-ops repo and adds a `hypershift-installer` deployment that will do a full `hypershift install` on the CI cluster on imagestream change, updating both the HO deployment and the manifests.
=> HOSTEDCP-603: move CI manifests to core repo

control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go
workaround https://github.com/openshift/origin/pull/27689
Causes `deploymentconfigs when tagging images should successfully tag the deployed image` conformance test to fail
=> workaround bad SAR check in deploymentconfigs conformance test

hypershift-operator/controllers/nodepool/nodepool_controller.go
Propagate changes to the hosted cluster pull secret down to the nodes within a NodePool
Fixes [HOSTEDCP-593](https://issues.redhat.com/browse/HOSTEDCP-593)
**Checklist**
=> Propagate Pull Secret Changes to NodePool Nodes

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
This should be done anyway, but we found it because of https://github.com/openshift/hypershift/pull/2005 combined with an apparent OVN bug that does not allow egress pod traffic to loop back to itself over the service network, even when the egress policy allows same-namespace traffic.
=> kas token-minter should use localhost kubeconfig

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
When the hosted control plane no longer has access to a cloud account, it should not attempt to cleanup cloud resources since it no longer can communicate with the cloud provider.
Fixes # [HOSTEDCP-709](https://issues.redhat.com//browse/HOSTEDCP-709)
**Checklist**
=> Skip destroying cloud resources when cloud creds lost

control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go
The etcd SM CA should be `etcd-signer`, not `etcd-metrics-signer`
This should fix conformance failure `etcd leader changes are not excessive`
=> fix etcd ServiceMonitor CA

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor.go
`ServiceMonitors`, contrary to their name, do not scrape the `Service` but the backing `Pods` listed in the `Endpoint`.  Thus we need to use the port on which the `Pod` listening, not the `Service`.
Currently the `kube-apiserver` ServiceMonitor is not working.
=> fix kas ServiceMonitor to TargetPort 6443

docs/content/reference/api.md, hack/gen-api-docs.sh
Use v1beta1 as the documented API documentation instead of v1alpha1 which is deprecated
**Checklist**
=> Switch API documentation to v1beta1

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go, support/capabilities/management_cluster_capabilities.go
tl;dr: Egress policy from the KAS can not be effectively employed because of issues with SDNs, both OpenshiftSDN/ovn-k, and, even more so, because the KAS has controllers that call out to cloud APIs which can not be effectively filtered by any ip/port based rule.
Initial attempt
https://github.com/openshift/hypershift/pull/1905
Revert
https://github.com/openshift/hypershift/pull/2001
New attempt
https://github.com/openshift/hypershift/pull/2005
Took out hypershift CI cluster based on 4.11/OpenShiftSDN
workaround bug OpenShiftSDN egress policy by not deploying policy
https://github.com/openshift/hypershift/pull/2022
KAS unable to mint SA token, breaking conformance tests
workaround bug in ovn-k egress policy but using localhost
https://github.com/openshift/hypershift/pull/2082
Ongoing …
=> Re-revert KAS egress policy

control-plane-operator/hostedclusterconfigoperator/controllers/resources/registry/reconcile_test.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/registry/registry.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
This updates HCCO to initialize image registry config for IBM Cloud platform. With the move of cluster-image-registry-operator to the control plane, a "bad" config is being initialized by the operator (bug: https://issues.redhat.com/browse/OCPBUGS-6797) causing the operator pods to crashloop.
Fixes #
**Checklist**
=> fix(ibmcloud): Initialize image registry config on creates and bad config

test/e2e/util/util.go
Regression: https://github.com/openshift/ovn-kubernetes/pull/1496
Bug filed: https://issues.redhat.com/browse/OCPBUGS-6953
Upstream fix PR: https://github.com/ovn-org/ovn-kubernetes/pull/3395
`ovnkube-master` panics on Node delete
Skip the pod crash check for `ovnkube-master` pods until this fix arrives.
Also, this check is replacing an outdated exclusion for `capi-provider` when we were fighting with etcd cert issues.
=> test: skip ovnkube-master in crashing pods check

docs/content/how-to/aws/disaster-recovery.md, docs/content/how-to/aws/external-dns.md, docs/mkdocs.yml
Making clear in the documentation that the Migration capability it's just for disaster recovery purposes.
=> Moving from HC Migration to Disaster Recovery in documentation

go.mod, vendor/modules.txt
Set k8s.io/kubernetes to v0.23.3 to match the version needed in github.com/openshift/cluster-node-tuning-operator v0.0.0-20220614214129-2c76314fb3cc
Fixes an art issue with respect to go dependency checks in Cachito.
**Checklist**
=> Set k8s.io/kubernetes dependency to v0.23.3

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go
When the OIDC provider is no longer valid, we should remove the finalizer from deleted AWSMachines given that they cannot be cleaned up by the CAPI provider.
Fixes #[HOSTEDCP-709](https://issues.redhat.com//browse/HOSTEDCP-709)
**Checklist**
=> AWS: remove finalizer from deleted awsmachines if lost STS

Makefile, cmd/install/assets/cluster-api-provider-aws/infrastructure.cluster.x-k8s.io_awsclustercontrolleridentities.yaml, cmd/install/assets/cluster-api-provider-aws/infrastructure.cluster.x-k8s.io_awsclusterroleidentities.yaml, cmd/install/assets/cluster-api-provider-aws/infrastructure.cluster.x-k8s.io_awsclusterstaticidentities.yaml, cmd/install/assets/cluster-api-provider-aws/infrastructure.cluster.x-k8s.io_awsmachinepools.yaml, cmd/install/assets/cluster-api-provider-aws/infrastructure.cluster.x-k8s.io_awsmanagedmachinepools.yaml, hack/app-sre/saas_template.yaml
Updates the command used to generate CRDs for the AWS CAPI provider so that it produces repeatable results every time.
**Checklist**
=> Fix CAPA crd generation

test/e2e/nodepool_machineconfig_test.go, test/e2e/nodepool_nto_machineconfig_test.go, test/e2e/nodepool_test.go
Refactor of NTO MachineConfig for InPlace and Replace upgrade modes
- Fixes #[HOSTEDCP-687](https://issues.redhat.com/browse/HOSTEDCP-687)
**Checklist**
=> Refactoring NTO MachineConfig InPlace and Replace E2E Tests

.ci-operator.yaml, Dockerfile, Dockerfile.control-plane, Dockerfile.fast
Kube 1.26 rebase landed and requires golang 1.19.  Doing this in preparation for dep bumps.
=> update to golang 1.19 and 4.13 base image

control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go
Cluster image registry operator needs to be able to restart on demand.
Fixes #https://github.com/openshift/hypershift/issues/376
**Checklist**
=> fix(cpo): Restart registry operator on annotation

control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go, control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert_test.go
This has been added in OCP 4.10 and allows syncing groups in OCP from an OpenID provider. 
So far the config was discarded if passed in the HostedCluster
Feature used by customers
*Related: [HOSTEDCP-799](https://issues.redhat.com//browse/HOSTEDCP-799)
**Checklist**
=> OpenID add support for groups claim in the config

support/metrics/sets.go
`PrometheusOperatorRejectedResources` alert triggering on ServiceMonitor `openshift-route-controller-manager`
```
level=warn ts=2023-01-31T18:54:46.192269295Z caller=operator.go:2020 component=prometheusoperator msg="skipping servicemonitor" error="invalid regex * for relabel configuration: error parsing regexp: missing argument to repetition operator: `*`" servicemonitor=clusters-sjenning-guest/openshift-route-controller-manager namespace=openshift-monitoring prometheus=k8s
```
=> fix openshift-route-controller-manager ServiceMonitor regex

api/v1beta1/hostedcluster_conditions.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/util/expose.go, support/util/util.go
This adds a new condition to report whether external DNS is working correctly.
Fixes #[HOSTEDCP-726](https://issues.redhat.com/browse/HOSTEDCP-726)
**Checklist**
=> Add external DNS health condition

hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/inplace_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
Before this change, when the NodePool replicas was not set or was nil and the autoscaling was enabled, the number of replicas was fixed to 1. Now it should match the minimum number of replicas set in the 'autoscaling' field of the nodepool spec file
Fixes #[HOSTEDCP-795](https://issues.redhat.com/browse/HOSTEDCP-795)
**Checklist**
=> Changes autoscalling replica number when the nodepool replica is not set

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/egresscfg.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/packageserver-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/pki/ca.go, control-plane-operator/controllers/hostedcontrolplane/pki/konnectivity.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/konnectivity.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go, konnectivity-socks5-proxy/main.go, support/util/util.go
=> AUTH-323: pki: split out konnectivity certs from the rootCA

api/v1beta1/hostedcluster_types.go, hypershift-operator/metrics.go
This exposes a new metric hypershift_cluster_silence_alerts whose value represents the existence of a label on the HostedCluster CR. We use this metric to communicate to central observability that alerts from a specific HostedCluster should be silenced. This ability to silence clusters is currently present on ROSA.
https://issues.redhat.com/browse/OSD-15100
**Checklist**
=> expose silence alerts metric

test/e2e/create_cluster_test.go
In powervs e2e periodic, for example
```
=== CONT  TestCreateClusterKms
create_cluster_test.go:90: 
failed to retrieve kms key arn
Unexpected error:
<*awserr.baseError | 0xc0004b8800>: {
code: "NoCredentialProviders",
message: "no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors",
errs: nil,
}
NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
occurred
--- FAIL: TestCreateClusterKms (6.56s)
```
=> test: skip TestCreateClusterKms on non-AWS platforms

hypershift-operator/metrics.go, hypershift-operator/metrics_test.go
Ensures the creation and deletion timestamps are not nil before dereferencing the time value. Also, ensure we return the error from observeNodePools.
Signed-off-by: Bryan Cox <brcox@redhat.com>
Should fix Issue #2072
**Checklist**
=> Check creation and deletion timestamps are not nil

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
[SRE alerts defined on hypershift](https://gitlab.cee.redhat.com/service/rhobs-rules-and-dashboards/-/tree/main/rules/hypershift-platform) may be triggered if `servicemonitor` and `podmonitor` resources get created before the `hostedcluster` is`Completed`.
This PR delays the creation of those scrape configs till reaching this `Completed` state. 
**Which issue(s) this PR fixes** *:
Fixes [OSD-15099](https://issues.redhat.com/browse/OSD-15099)
**Checklist**
=> OSD-15099: Delaying the creation of servicemonitor and podmonitor resources till the hostedcluster is Completed

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/pki/ca.go
This is a continuation of https://github.com/openshift/hypershift/pull/1891. We do it this way to ensure smooth upgrades of the CI cluster.
=> AUTH-323: konnectivity: split away the rootCA from konnectivity trust

control-plane-operator/controllers/hostedcontrolplane/kas/config.go, test/e2e/autoscaling_test.go
I noticed this discrepancy between hypershift and standalone KAS configurations.
Let's see if we can tighten the enforcement without breaking.
=> set default PSA enforce to restricted

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/infra_role.yaml
In order to properly detect if hotplugged volumes are available the driver needs to inspect the kubevirt VMI the volume was hotplugged into. This gives the controller the ability to get an individual VMI
Signed-off-by: Alexander Wels <awels@redhat.com>
Once https://github.com/kubevirt/csi-driver/pull/82 merges, the kubevirt csi driver requires
`get` on VMIs in order to properly function. This PR adds that RBAC
Fixes #
**Checklist**
=> Give kubevirt csi controller get VMI RBAC

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/manifests/ingressoperator.go
With this PR, a PodMonitor for ingress-operator pods in HCP namespaces is added to the control-plane-operator reconcile loop. 
This enables scraping of ingress-operator pod metrics, which are needed by SRE-P.
Tested on staging by manually adding an observability operator that looks for PodMonitors on all namespaces.
**Which issue(s) this PR fixes** * 
https://issues.redhat.com/browse/OSD-15101
**Checklist**
=> Add PodMonitor for ingress-operator pods in HCP namespaces

test/e2e/util/dump/journals.go
This enables the data recollection only in Nodes which are up and running
=> Filtering data recolection only for aws instances running

api/fixtures/example.go, api/fixtures/example_aws.go, cmd/cluster/aws/create.go, cmd/cluster/core/create.go, cmd/nodepool/aws/create.go
Enables setting KMS encryption key for nodepool root volume encryption.
Fixes #
**Checklist**
=> Add cli flag to enable root volume encryption

control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/namespaces.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/namespaces/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
After https://github.com/openshift/hypershift/pull/2097, conformance test `[sig-storage] PersistentVolumes NFS when invoking the Recycle reclaim policy should test that a PV becomes Available and is clean after the PVC is deleted.` began failing.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-4.13-conformance-aws-ovn/1625150475412180992
This is because the recycler pod is being blocked by PSA
```
Recycle failed: unexpected error creating recycler pod: pods "recycler-for-nfs-9mqrj" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "pv-recycler" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "pv-recycler" must set …
```
=> add PSA labels to openshift-infra in guest cluster

docs/content/getting-started.md
Add default NodePool name clarification to documentation to explain what the default NodePool name is when creating a cluster with the --node-pool-replicas flag. Also, expanded hosted cluster ready example to show what how the NodePools appear when ready.
N/A
**Checklist**
=> Add default NodePool name clarification to docs

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/cno.go
With `multus-admission-controller` in the CP side for 4.12, it does not cycle when the HC/HCP restart annotation is applied. This change makes it so that CPO will set the restart annotation.
Fixes #376
**Checklist**
=> fix(cpo): Set restart annotation on multus-admission-controller

docs/content/how-to/kubevirt/create-kubevirt-cluster.md
This fixes some of the formatting issues present in the prerequisites section of this doc, https://hypershift-docs.netlify.app/how-to/kubevirt/create-kubevirt-cluster/
=> Fix kubevirt how-to doc formatting issues

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kcm/config.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kcm.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/kcm.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Follow on to https://github.com/openshift/hypershift/pull/2180
KCM currently isn't configured with the PV recycle pod template that standalone uses
https://github.com/openshift/cluster-kube-controller-manager-operator/blob/master/bindata/assets/config/defaultconfig.yaml#L15
https://github.com/openshift/cluster-kube-controller-manager-operator/blob/master/bindata/assets/kube-controller-manager/recycler-cm.yaml
Because of this, the default pv recycler from upstream kube is started in the `default` namespace rather than `openshift-infra`, resulting in a failed in conformance due to PSA policy.
This PR aligns Hypershift KCM with standalone.
=> cpo: kcm: add nfs pv recycler pod template

go.mod, vendor/modules.txt
Fixes an art issue with respect to go dependency checks in Cachito.
Fixes [HOSTEDCP-833](https://issues.redhat.com/browse/HOSTEDCP-833)
**Checklist**
=> HOSTEDCP-833: Set kubevirt.io/client-go version to fix ART Issue

Makefile
Add Golang check for 'go list' errors in Makefile within deps section.
Fixes [HOSTEDCP-833](https://issues.redhat.com/browse/HOSTEDCP-833)
**Checklist**
=> HOSTEDCP-833: Add Golang check for 'go list' errors in Makefile

cmd/cluster/kubevirt/create.go
To support live migration the PVCs have to be with ReadWriteMany mode, this change add an option to use that mode.
*Checklist**
=> cli: Add --cli-root-volume-access-modes

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go
This disables the node controller on HCCO for IBM Cloud. For IBM Cloud, nodes are not managed through the CAPI system. This will help us ensure that nodes will never be touched by HCCO and reduce control plane load by removing unnecessary watches on resources.
Fixes #
**Checklist**
=> fix(ibmcloud): Explicitly set HCCO controllers

control-plane-operator/controllers/hostedcontrolplane/mcs/reconcile.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, ignition-server/cmd/run_local_ignitionprovider.go, ignition-server/controllers/local_ignitionprovider.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/controllers/tokensecret_controller_test.go, support/util/util.go
Fixes the race condition between the MCS ConfigMap update and ignition payload creation - updates the pull secret source for ignition payload. The NodePool controller will save a hash of the pull secret in every newly created token secret. During creation of an ignition payload, a comparison between the token secret's pull secret hash and a hash of the pull secret will be made to ensure they match. The pull secret will be written to the bootstrap config directory, overwriting the one from the MCS ConfigMap.
[HOSTEDCP-593](https://issues.redhat.com/browse/HOSTEDCP-593)
**Checklist**
=> HOSTEDCP-593: Update the pull secret source for ignition payload

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Check the error code of the SG delete operation. If not authorized, skip deletion instead of retrying. Also, only attempt to delete the SG if the cleanup cloud resources annotation is present.
Fixes #[HOSTEDCP-834](https://issues.redhat.com//browse/HOSTEDCP-834)
**Checklist**
=> Cleanup default security group only if authorized

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/params_test.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/nodepool/haproxy.go, support/util/networking.go
This code was not ported when the branch was originally setup and is breaking critical functionality in ibm cloud. This will add the necessary code to reconcile the apiserver port field appropriately in the hostedCluster struct
Fixes #
**Checklist**
=> ensure reconcilation of apiserver port

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/params_test.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/nodepool/haproxy.go, support/util/networking.go
This code was not ported when the 4.12 branch was originally setup and is breaking critical functionality in ibm cloud. This will add the necessary code to reconcile the apiserver port field appropriately in the hostedCluster struct
Fixes #
**Checklist**
=> ensure reconcilation of apiserver port is in 4.12

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
This includes the network validation for hostedcluster in the hosted cluster controller.
Fixes: [HOSTEDCP-820](https://issues.redhat.com//browse/HOSTEDCP-820)
Fixes #
**Checklist**
=> Validate Network Input for HostedCluster

api/v1beta1/nodepool_conditions.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
The condition was added in the original default SG PR but it was not being set by the nodepool controller. It is now computed and set by the nodepool controller.
Fixes #[HOSTEDCP-841](https://issues.redhat.com//browse/HOSTEDCP-841)
**Checklist**
=> Add condition to NodePool indicating whether a security group for it is available

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
The name of the CNO `ovn-kubernetes` image has changed in the release payload
https://github.com/openshift/cluster-network-operator/pull/1712#issuecomment-1442980448
This is causing 4.13 tests to fail.
=> cpo: cno: follow image name change in release payload

.github/labels.yaml, api/OWNERS, availability-prober/OWNERS, control-plane-operator/OWNERS, dnsresolver/OWNERS, hypershift-operator/OWNERS, ignition-server/OWNERS, konnectivity-socks5-proxy/OWNERS, kubernetes-default-proxy/OWNERS, token-minter/OWNERS
Adds OWNERS files in directories to automatically set a label on a PR if a file is changed in that directory.
Adds labels.yaml file that allows /area type of commands on PRs to add the area label.
**Checklist**
=> Add configuration for automatic labeling and label commands

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
Supersedes #2210 with an amended implementation to block on delete of the incluster dns operator only--to have less of an impact on control plane bring up time.
Fixes #2128
**Checklist**
=> feat(HCCO): Block DNS operator delete until Cluster Version updated

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
IBM Cloud fleets currently sets:
```
machineNetwork: 
- cidr: "{{ pod_network_cidr }}"
clusterNetwork: 
- cidr: "{{ pod_network_cidr }}"
serviceNetwork: 
- cidr: "{{ service_network_cidr }}" 
```
Temporarily disabling network validation until all fleets are patched with updated networking configs.
Fixes #
**Checklist**
=> fix(ho): No network validation for IBM Cloud

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/nto/clusternodetuningoperator.go, control-plane-operator/controllers/hostedcontrolplane/olm/olm-collect-profiles.go
Leads to image pull failures for these components if the mgmt cluster doesn't have permissions to pull
=> add pull-secret to imagePullSecrets for NTO, CNO, and olm-collect-profiles

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
The current code that updates the CloudResourcesDestroyed condition on the hostedcontrolplane resource is not updating the LastTransitionTime. The hostedcontrolplane controller understands this to mean that the hcco is no longer active and proceeds to remove the finalizer from the hostedcontrolplane on the configured timeout. This fix ensures that the LastTransitionTime gets updated on the condition so it can behave as a heartbeat for the hostedcontrolplane controller.
Fixes #OCPBUGS-8231
**Checklist**
=> OCPBUGS-8231: Fix cleanup of volumes on cluster deletion

hypershift-operator/main.go, main.go, pkg/version/version.go
Makes it easier to understand at a glance the latest OCP supported by the Operator / CLI
```
➜  hypershift git:(version-show-latestl-ocp) ✗ ./bin/hypershift -v
hypershift version openshift/hypershift: 42e85b6ed107c4b99a5ef00b886e1943ea896095. Latest supported OCP: 4.13.0
➜  hypershift git:(version-show-latestl-ocp) ✗ ./bin/hypershift-operator -v
hypershift-operator version openshift/hypershift: 42e85b6ed107c4b99a5ef00b886e1943ea896095. Latest supported OCP: 4.13.0
```
Ref https://issues.redhat.com/browse/HOSTEDCP-638
**Checklist**
=> HOSTEDCP-638: Add latest ocp supported info to -v command for cli and operator

api/v1alpha1/hostedcluster_types.go, api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
The current API documentation states that the audit webhook field is only supported for IBM Cloud. It should be supported for all platforms.
Fixes #OCPBUGS-8421
**Checklist**
=> OCPBUGS-8421: fix API documentation for audit webhook field

control-plane-operator/controllers/hostedcontrolplane/pki/ca.go, support/certs/tls.go
Clone CA key/cert to TLS key/cert as some certificate managers expect to use tls.key/tls.crt rather than ca.key/ca.crt.
[HOSTEDCP-809](https://issues.redhat.com/browse/HOSTEDCP-809)
**Checklist**
=> HOSTEDCP-809: Clone CA key/cert to TLS key/cert

api/v1beta1/hostedcluster_types.go, cmd/infra/aws/iam.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/cloud/aws/manifests.go, control-plane-operator/controllers/hostedcontrolplane/cloud/aws/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/namespaces.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, test/e2e/nodepool_test.go, test/e2e/nodepool_upgrade_test.go
Introduces a new deployment for the AWS cloud controller manager. This is required because in 4.14 kubelets are initialized with an external cloud manager.
Updates the kube cloud controller manager AWS role with additional permissions.
**Checklist**
=> HOSTEDCP-919: Add AWS cloud controller manager

docs/content/contribute/release-process.md
This PR contains the documentation related with Release process of Hypershift and CPO. It does not involves only Hypershift repo but openshift/release one, which means that the consequence will involve, new jobs in the CI, new payloads for external teams, changes in the images generated and some modifications in the release branches
Fixes #[HOSTEDCP-501](https://issues.redhat.com/browse/HOSTEDCP-501)
**Checklist**
=> HOSTEDCP-501: Added detailed documentation about Hypershift release process

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/oauth/config.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/pki/oauth.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/oauth/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
For oauth, we currently only copy the self-signed cert to openshift-config-managed
of the hosted cluster. However, if a certificate has been specified for
the oauth endpoint via spec.config.apiServer, the bundle that we copy
over should contain the additional certificate.
Adds CA bundle to the oauth server configuration that contains certs
specified through apiserver namedcerts and the self-signed cert that we
normally generate.
Fixes #OCPBUGS-8381
**Checklist**
=> OCPBUGS-8381: Use appropriate serving certificate for OAuth

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
Without this additional logic cluster might get stuck deleting when either the CPO didn't have the chance to set the valid identity provider condition or when the credentials are invalid.
Ref OCPBUGS-10227
**Checklist**
=> OCPBUGS-10227: Ensure identity provider health check condition is persisted and remove awsendpoint control plane finalizer if invalid aws creds

test/e2e/nodepool_test.go, test/e2e/nodepool_upgrade_test.go
Refactored the E2E NodePool Upgrade tests following the same principles then before, it follows the 2 ways of upgrade 'Replace' and 'InPlace'.
Fixes #[HOSTEDCP-688](https://issues.redhat.com/browse/HOSTEDCP-688)
**Checklist**
=> HOSTEDCP-688: E2E Test NodePool Upgrade 

api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/cloud/aws/manifests.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
Follow up to #2271
Removes unnecessary manifest functions and adds a comment with the source of the policy used for the cloud controller manager.
**Checklist**
=> HOSTEDCP-919: Clean up and API doc

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, hypershift-operator/controllers/platform/aws/controller.go
Now AWSPrivateLinkController checks the HostedControlPlane.Spec.PausedUntil field and pauses the reconciliation until the definition describes. In the same way, AWSEndpointServiceController has been modified to check the HostedCluster.Spec.PausedUntil field and pauses the reconciliation accordingly
Fixes #[HOSTEDCP-900](https://issues.redhat.com/browse/HOSTEDCP-900)
**Checklist**
=> HOSTEDCP-900: Modified AWSPrivateLinkController and AWSEndpointServiceController to respect PausedUntil spec field

api/v1alpha1/hostedcluster_types.go, api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/cloud/kubevirt/providerconfig.go, control-plane-operator/controllers/hostedcontrolplane/cloud/kubevirt/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/ingress.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
As we're looking to expand the kubevirt platform to manage VMs on external infra (an ocp cluster external to the one hypershift runs on), it's possible that VMs from multiple clusters will get placed in the same namespace. As a result, we need to start labeling the components we place in these namespaces using the unique HostedCluster.Spec.InfraID. 
This serves two purposes for us.
1. We can ensure our ingress passthrough services only route to VMs within a specific cluster
2. We can clearly identify what resources associated with a HostedCluster need to be cleaned up on the external cluster (routes, services, VMs, etc...)
=> Route to kubevirt VMs using infra id as service label selector

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/auditcfg.go, control-plane-operator/controllers/hostedcontrolplane/oapi/config.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
This adds a tail sidecar container for the audit logs for the above deployments. It
also plumbs the audit config into the two deployments.
Fixes #[HOSTEDCP-839](https://issues.redhat.com//browse/HOSTEDCP-839)
Fixes #
**Checklist**
=> HOSTEDCP-839: Audit log sidecars for openshift-apiserver and openshift-oauth-apiserver

control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/assets/05_operator_role-hypershift.yaml, control-plane-operator/controllers/hostedcontrolplane/storage/assets/role.yaml
cluster-storage-operator and csi-snapshot-controller-operators should be able to list/watch HostedControlPlanes to get its nodeSelector.
**Checklist**
=> OCPBUGS-8691: Add storage operators perms. to watch HostedControlPlane

api/fixtures/example.go, api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift_operator.go, control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/manifests/infra.go, control-plane-operator/controllers/hostedcontrolplane/oauth/route.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, control-plane-operator/main.go, hack/app-sre/saas_template.yaml, support/util/route.go, test/e2e/util/oauth.go
For clusters with an endpoint access of type Private, that use route as
a publishing strategy and specify a hostname, the hostname is exposed
externally via external-dns using a service of type ExternalName.
Clusters can be switched back and forth between Private and
PublicAndPrivate and the external-dns records are adjusted as needed.
Fixes #[HOSTEDCP-801](https://issues.redhat.com//browse/HOSTEDCP-801)
**Checklist**
=> HOSTEDCP-801: Expose external DNS for private cluster endpoints

test/e2e/nodepool_test.go, test/e2e/nodepool_upgrade_test.go
Disable inplace upgrade tests until OCPBUGS-10218 is fixed
https://issues.redhat.com/browse/OCPBUGS-10218
**Checklist**
=> [release-4.13] Disable inplace upgrade e2e tests

api/scheme.go, cmd/install/install.go
This PR creates a second scheme, InstallScheme
This second scheme is needed because the [ServiceMonitor for the hypershift operator itself](https://github.com/openshift/hypershift/blob/05b97dea8201cd43954cf854a9dab05e83a54570/cmd/install/assets/hypershift_operator.go#L1108-L1133) currently must always use the prometheus operator's GVKs, not the RHOBS fork, while the other controllers should use the RHOBS fork when configured to do so.
Fixes [OCPBUGS-8713](https://issues.redhat.com/browse/OCPBUGS-8713)
=> Create a second scheme that always registers `prometheusoperatorv1` GVKs

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Validates and reports conflicting services published hostnames
Fixes #[HOSTEDCP-934](https://issues.redhat.com/browse/HOSTEDCP-934)
**Checklist**
=> HOSTEDCP-934: Validate PublishingStrategyMapping

cmd/infra/powervs/create.go, cmd/infra/powervs/destroy.go, cmd/infra/powervs/validate.go
Fixes https://issues.redhat.com/browse/MULTIARCH-3028
This PR mainly trying to handle PowerVS instance which goes to failed state during infra create and destroy process.
Fixes #
**Checklist**
=> MULTIARCH-3028: handle PowerVS instance which goes to failed state during infra create and destroy process.

control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, konnectivity-socks5-proxy/main.go
Fallback to the management cluster resolution (i.e. no proxy) when the guest cluster DNS resolution fails.
Fixes [OCPBUGS-8073](https://issues.redhat.com/browse/OCPBUGS-8073)
**Checklist**
=> OCPBUGS-8073: Do not proxy when guest cluster resolution fails

hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, support/supportedversion/version.go
Because `releases before 4.8 are not supported` and similar are helpful, but folks may not know which release they'd requested.  By including the version inline, they can distinguish between "makes sense, I'll request a different version" and "hrm, why was I requesting `0.0.1-0.test-2023-03-27-200807-ci-ln-wl9g9xk-latest` ? Maybe cluster-bot or ci-controller needs a patch".
=> support/supportedversion: Include the problematic version strings in error messages

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
This reverts commit 956d0936625c4f76dbe306af6c537d890c3a1ab6.
CNO changed the OVN image name in the payload again
https://github.com/openshift/cluster-network-operator/pull/1747
=> Revert "cpo: cno: follow image name change in release payload"

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
This PR fixes the security problem of multus-admission-controller running with root account. The code fix passes RUN_AS_USER environment variable to CNO deployment so that it can run its managed services, including multus-admission-controller, with proper pod security context.
Corresponding CNO bug https://issues.redhat.com/browse/OCPBUGS-10647 and code change https://github.com/openshift/cluster-network-operator/pull/1745
=> OCPBUGS-10807: Pass runAsUser to CNO so it can run its managed services with proper security context

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/kcm/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/nto/clusternodetuningoperator.go, control-plane-operator/controllers/hostedcontrolplane/oapi/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/ocm/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go, control-plane-operator/controllers/hostedcontrolplane/routecm/servicemonitor.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/monitoring/servicemonitor.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This PR no more specifies the scrape interval at `servicemonitors` & `podmonitors` level when the global scrape interval specified at Prometheus root config level can be used instead.
The `ingress-operator` `service-monitor` for which the scrape interval is set to 60 sec is not impacted by this change; indeed this value is much higher than the value you could expect at Prometheus root config level.
This PR is needed lo lower the memory and CPU consumption of the [OBO operator](https://github.com/rhobs/observability-operator) on the MC clusters. This will also indirectly reduce the traffic sent to RHOBS by the OBO Prometheus instances.
This PR replaces https://github.com/openshift/hypershift/pull/2323 which was still hardcoding a value into the code. …
=> SDA-8609: No more specifying the scrape interval at servicemonitors & podmonitors level 

control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
In client environments that run with a HTTP_PROXY: that proxy information is lost when the image import is done on the openshift-apiserver side and sent through the konnectivity-sidecar. There are a set of well known domains that are necessary for the MVP set of samples that get deployed in an openshift cluster. These well known public domains should not have to be proxied into the client environment and instead can go direct from the management cluster. Any other defined domains do need to proxy into the cluster network for the ability to access on prem registries.
Fixes # …
=> OCPBUGS-10823 ensure well known public domains do not get proxied on image imports

cmd/cluster/core/create.go, cmd/util/secrets.go
get pull secret instead of dockerconfigjson from mce credentials to make consistent with https://github.com/openshift/hypershift/blob/main/docs/content/how-to/aws/create-aws-hosted-cluster-secret-credentials.md. This allows for successful cluster creation when following the docs
Fixes https://github.com/openshift/hypershift/issues/2179 & https://issues.redhat.com/browse/ACM-4615
**Checklist**
Before:
```
2023-03-28T14:53:44-04:00	INFO	Retreiving credentials secret	{"namespace": "clusters", "name": "aws-secret-test"}
2023-03-28T14:53:51-04:00	ERROR	Failed to create cluster	{"error": "failed to default network: failed to get version for release image quay.io/openshift-release-dev/ocp-release:4.13.0-rc.0-x86_64: the …
```
=> ACM-4615 get pull secret instead of dockerconfigjson from mce credentials

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
When the hostedcontrolplane has been removed, we may still depend on the ValidAWSIdentityProvider condition to determine whether to abandon the AWSEndpointService. Current behavior is that the condition status reverts to Unknown. This prevents the AWSEndpointService controller from abandoning the cleanup of the VPC endpoint.
This change preserves the value of the condition if it was false and can no longer be determined via the hostedcontrolplane resource.
Fixes #OCPBUGS-10227
**Checklist**
=> OCPBUGS-10227: Preserve false status of ValidAWSIdentityProvider condition

cmd/cluster/aws/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/iam.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/oidc/oidc.go, test/e2e/autoscaling_test.go, test/e2e/chaos_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/nodepool_test.go, test/e2e/olm_test.go, test/e2e/util/aws.go, test/e2e/util/fixture.go
Only a single OIDC provider will be created and shared between all e2e HostedClusters. 
Fixes #[HOSTEDCP-939](https://issues.redhat.com/browse/HOSTEDCP-939)
**Checklist**
=> HOSTEDCP-939: Setup shared OIDC provider for e2e clusters

test/e2e/nodepool_upgrade_test.go, test/e2e/util/node.go
Fix nodepool upgrade e2e test labels and taints validation logic
Fixes #
=> Fix nodepool upgrade e2e test

hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/inplace_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
Ensures MachineDeployment/MachineSet has correct replicas count corresponding to autoscaler min/max values
Fixes #[HOSTEDCP-850](https://issues.redhat.com/browse/HOSTEDCP-850)
**Checklist**
=> HOSTEDCP-850: Fix nodepool autoscaler logic

docs/content/how-to/aws/troubleshooting.md
Added another entry in the troubleshooting guide to fix the storage ClusterOperator during a Disaster recovery migration
Fixes #[HOSTEDCP-445](https://issues.redhat.com/browse/HOSTEDCP-445)
**Checklist**
=> HOSTEDCP-445: Fix the storage ClusterOperator during a DR migration

test/e2e/e2e_test.go, test/e2e/util/fixture.go
https://github.com/openshift/hypershift/pull/2335 introduced AWS platform specific code in the platform agnostic path.
Only run the common OIDC provider code if the platform is AWS.
=> e2e: fix for non-AWS platform

api/v1beta1/hostedcluster_conditions.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, support/util/util.go, test/e2e/util/oauth.go
This enhances HCAvailable condition to better represent day2 state
Fixes #[HOSTEDCP-807](https://issues.redhat.com/browse/HOSTEDCP-807)
**Checklist**
=> HOSTEDCP-807: Check KAS loadbalancer health

api/scheme.go, cmd/install/install.go
Reverts openshift/hypershift#2292
We will use OBO to ship hypershift metrics, so no need to register this version group, and we are seeing this error in the installer pod:
```
oc logs -n open-cluster-management-agent-addon hypershift-install-job-25cr8-nnlvw
already exists: PriorityClass /hypershift-control-plane
already exists: PriorityClass /hypershift-etcd
already exists: PriorityClass /hypershift-api-critical
already exists: PriorityClass /hypershift-operator
applied Namespace /hypershift
applied ServiceAccount hypershift/operator
applied ClusterRole /hypershift-operator
applied ClusterRoleBinding /hypershift-operator
applied Role hypershift/hypershift-operator
applied RoleBinding hypershift/hypershift-operator
applied ServiceAccount hypershift/external-dns
applied ClusterRole …
```
=> Revert "Create a second scheme that always registers prometheusoperatorv1 GVKs"

api/fixtures/example.go, api/v1beta1/nodepool_types.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/nodepool/core/create.go, cmd/nodepool/create.go, test/e2e/e2e_test.go
Nodepool upgrade has two different upgrade methods, Replace and InPlace.
I think our CI upgrade test should cover both. So I add one flag in our CLI to support the completion of the Replace upgrade and InPlace upgrade in the prow.
```
Flag: 
--upgrade-type string    The upgrade type is a type of high-level upgrade behavior nodes in a NodePool. Supported options: Replace, InPlace (default "Replace")
```
example:
```
bin/hypershift create cluster aws --aws-creds xxx --pull-secret xxx --upgrade-type InPlace  --base-domain xxx --render
```
Fixes [HOSTEDCP-802](https://issues.redhat.com/browse/HOSTEDCP-802)
**Checklist**
=> HOSTEDCP-802: add cli flag to enable upgrade type

api/v1beta1/hostedcluster_types.go, cmd/infra/aws/iam.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
Checking if ec2:ReleaseAddress is needed for NodePool management polcy or not 
Fixes https://issues.redhat.com/browse/HOSTEDCP-954
**Checklist**
- [x ] Subject and description added to both, commit and PR.
- [ x] Relevant issues have been referenced.
=> HOSTEDCP-954: Remove ec2:ReleaseAddress

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
https://issues.redhat.com/browse/HOSTEDCP-632
Refactored version of https://github.com/openshift/hypershift/pull/2336 to address https://github.com/openshift/hypershift/pull/2336#discussion_r1151394058 and fixup/add unit tests
fyi @wking
=> OCPBUGS-11439: allow z-stream upgrade even if CVO Upgradeable is false

docs/content/how-to/kubevirt/create-kubevirt-cluster.md
It updates the kubevirt configuration as of the latest release (03/23/2023).
**Checklist**
=> Updated kubevirt docs

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, support/globalconfig/proxy.go
Users are able to and directed to configure the cluster-wide proxy directly in the guest cluster when needing to setup local proxying in the guest cluster network: https://docs.openshift.com/container-platform/4.10/networking/enable-cluster-wide-proxy.html. Currently: even when the proxy configuration in the hosted cluster is nil: we are squashing all these changes and revoking what they are doing locally. This makes it impossible for them to configure the proxy within their network (they should not need to have to proxy these configurations to the hostedcluster resource each time and get it to propogate as that can be controlled by a separate entity like a managed cloud provider). This allows the user to create those changes and have them persist …
=> OCPBUGS-11442: properly reconcile with user specified changes for in proxy configuration

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, konnectivity-socks5-proxy/main.go
* Consolidates #1741 and #1722.
Fixes [HOSTEDCP-568](https://issues.redhat.com/browse/HOSTEDCP-568)
**Checklist**
=> HOSTEDCP-568: Update Konnectiviy socks5 proxy for IBM exception

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
The health check will incorrectly report a healthy condition for the
AWSIdentityProvider when reusing the same client. This change fixes that
by creating a new client every time the health check is executed.
**Checklist**
=> OCPBUGS-11654: [release-4.12] Create new EC2 client for AWS identity provider health check

test/e2e/util/oauth.go, test/e2e/util/util.go
Fixes oauth idp e2e test conflict error when updating HosterCluster
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_hypershift/2381/pull-ci-openshift-hypershift-main-e2e-aws/1643947449200414720
=> e2e: Fixed idp test conflict error on HosterCluster update

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Update HostedCluster oauthCallbackURLTemplate to use 'oauth2callback' in URL, not 'oauthcallback'.
Fixes [OCPBUGS-11640](https://issues.redhat.com/browse/OCPBUGS-11640)
**Checklist**
=> OCPBUGS-11640: Update HostedCluster oauthCallbackURLTemplate

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
For HyperShift, we are currently scraping hosted control plane metrics via the Observability Operator. The [namespaceSelector](https://github.com/rhobs/observability-operator/blob/main/docs/api.md#monitoringstackspecnamespaceselector) field of the operator's MonitoringStack CR does not support multiple labels. With Management Cluster metrics soon to be forwarded by the Observability Operator, we need a common label that acts as an identifier that the namespace should be monitored by Observability Operator. 
This PR adds the `hypershift.openshift.io/monitoring` label to the hosted control plane namespace to achieve this goal.
Resolves: [OSD-15905](https://issues.redhat.com/browse/OSD-15905)
**Checklist**
=> Add monitoring label to HCP namespace

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kubevirt.go
ClusterRoles and ClusterRoleBindings are cluster scoped, and do not need namespaces.  Trying to set the namespace during reconciliation results in errors like the one below.
```{"level":"error","ts":"2023-03-06T20:38:30Z","msg":"Reconciler error","controller":"resources","object":{"name":""},"namespace":"","name":"","reconcileID":"8e7c2ab5-e628-412e-9419-fb889e766185","error":"MutateFn cannot mutate object name and/or object namespace","errorCauses":[{"error":"MutateFn cannot mutate object name and/or object namespace"}],"stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/hypershift/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start …
```
=> Fixes HCCO reconcile error for kubevirt csi driver

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/metrics/labels.go
For HyperShift, the Observability Operator will be scraping HCP and Management Cluster platform metrics via a common label; `hypershift.openshift.io/monitoring`. This is because [namespaceSelector](https://github.com/rhobs/observability-operator/blob/main/docs/api.md#monitoringstackspecnamespaceselector) field of the operator's MonitoringStack CR does not support multiple labels.
As we need the HyperShift Operator metrics to be forwarded to RHOBS for effective monitoring, this PR adds the common monitoring label to the `hypershift` namespace to achieve this functional goal.
Resolves: [OSD-15973](https://issues.redhat.com/browse/OSD-15973)
**Checklist**
=> Enable monitoring for hypershift namespace

docs/content/getting-started.md
AWS has changed how s3 public buckets work
https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/
We need to update our docs to remove the ACL and add a command to remove the public access block.
=> docs: update OIDC s3 bucket creation procedure

hypershift-operator/controllers/nodepool/nodepool_controller.go
NTOMachineConfigRolloutTest got transparently broken in CI NodePool show error [1]
```
- lastTransitionTime: "2023-04-14T15:43:46Z" message: 'configmap "nto-mc-example-7tldp-test-ntomachineconfig-replace" failed validation: error decoding config: strict decoding error: unknown field "spec.baseOSExtensionsContainerImage"' observedGeneration: 2 reason: ValidationFailed status: "False" type: ValidMachineConfig
```
The NTO generate MachineConfig has a field that our strict decoding doesn't like [2]
This seems to be caused because the NTO just recently bumped their vendored MCO API [3]
Relaxing the strict decoding should prevent NTO from breaking us transparenrly. Actual use of a new field by NTO requires concious bump of the MCO API in Hypershift as well.
[1] …
=> Relax MCO API strict decoding

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Pod security restrictions do not allow a private router to be created. The hosted control plane namespace must be labeled appropriately so that pod security admission can allow the private router.
Fixes #OCPBUGS-11749
**Checklist**
=> OCPBUGS-11749: Add pod security labels to hcp namespace

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/deployment.go
Currently changes to the configuration of the kube scheduler do not result in a restart of the kube-scheduler pods. This commit adds an annotation to the scheduler's deployment template that contains a hash of the scheduler's configuration. This will result in a redeploy every time the scheduler configuration changes.
Fixes #OCPBUGS-7091
**Checklist**
=> OCPBUGS-7091: Restart kube-scheduler when its configuration changes

cmd/infra/aws/create_iam.go, test/e2e/e2e_test.go
some OIDC providers created by the CI are not cleaned up properly because the run was terminated abnormally.
I am assuming the reason is that the deferred functions are not called when the test is terminated abnormally (for some reason). This adds the cleanup logic for that case when we detect a SIGTERM.
I also moved the actual creation of the provider to the end of the setupSharedOIDCProvider function, so that if we fail before that, the provider will not be created. Before this change, we could create the provider, fail at the next step and then return in main without calling the cleanup.
=> e2e: Cleanup shared OIDC provider on SIGTERM

OWNERS
Adds Hide and Francisco as reviewers to the repo so they are able to lgtm PRs
=> Add IBMers as reviewers

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, test/e2e/e2e_test.go
Fixes https://issues.redhat.com/browse/OCPBUGS-11773
AWS has recently disabled ACL support by default.
https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/
OCP installer fixed in the same way https://github.com/openshift/installer/pull/7085
Docs update was https://github.com/openshift/hypershift/pull/2425
=> OCPBUGS-11773: remove ACL for aws bucket

docs/content/getting-started.md
Follow on to https://github.com/openshift/hypershift/pull/2425 and https://github.com/openshift/hypershift/pull/2423
Following the current procedure results in a bucket that _can_ have public access but does not allow `GetObject` on a public basis.
Adding this bucket policy allows public access to objects in the OIDC bucket.
=> docs: update OIDC bucket create with bucket policy

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
We're seeing a lot of the errors below in our kubevirt e2e tests. It appears the pod security label syncer is battling the hosted cluster to set some pod-security related labels. 
```
{"level":"info","ts":"2023-04-20T20:04:51Z","msg":"WARNING: Object got updated more than one time without a no-op update, this indicates hypershift incorrectly reverting defaulted values","type":"*v1.Namespace","name":"/clusters-vossel1","diff":"  &v1.Namespace{\n  \tTypeMeta: {Kind: \"Namespace\", APIVersion: \"v1\"},\n  \tObjectMeta: v1.ObjectMeta{\n  \t\t... // 8 identical fields\n  \t\tDeletionTimestamp:          nil,\n  \t\tDeletionGracePeriodSeconds: nil,\n  \t\tLabels: map[string]string{\n  \t\t\t\"hypershift.openshift.io/hosted-control-plane\": \"true\",\n …
```
=> Fixes loop between HC controller and pod security label syncer

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/daemonset.yaml
The HCCO was clobbering some daemonset default values for the kubevirt-csi driver within the guest cluster. The result was that the HCCO would define the daemonset, some default values would get applied server side, then we'd detect those changes and remove them, then they'd get added back and so on the loop goes.
This PR fixes the reconcile loop by ensuring that we explicitly set the default values we were clobbering. Now there's no loop.
=> Fix kubevirt csi daemonset reconcile loop

Makefile, docs/content/contribute/index.md
Adds the pre-commit command to the Make file to automatically update Golang and API dependencies, build the source code, build the e2e's, verify source code formatting, and run unit tests.
Fixes [HOSTEDCP-972](https://issues.redhat.com/browse/HOSTEDCP-972)
**Checklist**
=> HOSTEDCP-972: Add pre-commit command to Make file

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/metrics.go, hypershift-operator/metrics.go, test/e2e/util/fixture.go
/hold
Needs https://github.com/openshift/hypershift/pull/2459
Fixes #
**Checklist**
=> HOSTEDCP-969: Move guest cluster resource deletion metric

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This adds the hyperv1.SilenceClusterAlertsLabel label to a HostedCluster CR during the deletion process. It will facilitate silencing alerts triggered during the uninstall process.
[OSD-15598](https://issues.redhat.com/browse/OSD-15598)
**Checklist**
=> add hyperv1.SilenceClusterAlertsLabel to HostedCluster on deletion

test/e2e/create_cluster_test.go, test/e2e/util/node.go, test/e2e/util/oauth.go, test/e2e/util/util.go
Validates switching a cluster from `PublicAndPrivate` to `Private` and vice versa to be working .
Fixes #[HOSTEDCP-917](https://issues.redhat.com/browse/HOSTEDCP-917)
**Checklist**
=> HOSTEDCP-917: Add publicAndPrivate <-> Private e2e test

test/e2e/util/fixture.go
We have seen failures `Failed to validate that metrics are exposed: "hypershift_cluster_deletion_duration_seconds" not found  for the TestNodePool/ValidateMetricsAreExposed`
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_hypershift/2477/pull-ci-openshift-hypershift-main-e2e-aws/1651173441761447936/artifacts/e2e-aws/run-e2e/artifacts/TestNodePool_PreTeardownClusterDump/namespaces/hypershift/core/pods/logs/operator-85bbc866c7-7kjxl-operator.log
Even though the code for exposing the metric has run as proved by this log
```
{"level":"info","ts":"2023-04-26T11:41:27Z","msg":"Deleted hostedcluster","controller":"hostedcluster","controllerGroup":"hypershift.openshift.io","controllerKind":"HostedCluster","hosted …
```
=> Add PollImmediate for e2e metrics to avoid race with prom scrape interval

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, test/e2e/util/oauth.go
this removes "kube:admin" IdP as an available option when an explicit idp is defined
Fixes #[OCPBUGS-11738](https://issues.redhat.com/browse/OCPBUGS-11738)
**Checklist**
=> OCPBUGS-11738: Delete kubeadmin secret when an idp is defined

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/metrics.go, hypershift-operator/controllers/hostedcluster/metrics_test.go
/hold
needs https://github.com/openshift/hypershift/pull/2477
Fixes #
**Checklist**
=> HOSTEDCP-969: Only track available metric once

cmd/install/assets/hypershift_operator.go, hypershift-operator/metrics.go, hypershift-operator/metrics_test.go, test/e2e/util/fixture.go
Added new metric with 4 fields to expose:
- The Hypershift version
- The container image
- The container image id
- Latest Supported Version
- The GoVersion which is executing the operator. 
- The GoArch (This could be useful in the future)
All these markers will help the users and consumers to identify and debug possible issues in some scenarios
Fixes #[HOSTEDCP-937](https://issues.redhat.com/browse/HOSTEDCP-937)
**Checklist**
=> HOSTEDCP-937: New metric to expose Hypershift operator info

api/v1alpha1/nodepool_types.go, api/v1beta1/nodepool_types.go, cmd/cluster/kubevirt/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hack/app-sre/saas_template.yaml, test/e2e/e2e_test.go
Increases Mem defaults to 8gi
Increases Root Volume defaults to 32 Gi
Adds option to e2e tests to configure cpu counts and root volume size.
This aligns closer with the requirements set here, https://docs.openshift.com/container-platform/4.12/post_installation_configuration/node-tasks.html#rhel-compute-requirements_post-install-node-tasks 
We're erroring on the side of overshooting the minimal root volume size by default in order to provide a more usable default experience. In practice, we've seen that the container images can fill up the root volume quickly depending on the workloads installed.
=> ACM-5116: Increase KubeVirt default Mem and Root Volume Sizes

control-plane-operator/controllers/hostedcontrolplane/kas/config.go
Set hosted cluster KAS config pod security enforcement to privileged.
Fixes [OCPBUGS-12689](https://issues.redhat.com/browse/OCPBUGS-12689)
**Checklist**
=> OCPBUGS-12689: hosted clusters default KAS PDA config should be consistent with OCP

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
CI is currently borken https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn/1653511338548269056/artifacts/e2e-aws-ovn/run-e2e/artifacts/TestCreateCluster_PreTeardownClusterDump/namespaces/e2e-clusters-glkxm-example-qmb9l/core/pods/logs/kube-apiserver-79b6c48d7-mzv44-init-bootstrap-previous.log.
This introduced a new command which is effectively required https://github.com/openshift/cluster-config-operator/pull/288
This introduced new status in featureGate CRD https://github.com/openshift/api/pull/1405
Here it was added to the installer github.com/openshift/installer/pull/6990 …
=> Add new --featuregate-manifest to /usr/bin/cluster-config-operator render

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Cleaning up load balancers and ingress controllers concurrently can lead to a race condition that causes deletion to be stuck on a hosted cluster. This commit prevents load balancer cleanup from happening until all ingress controllers have been removed.
Fixes #OCPBUGS-10400
**Checklist**
=> OCPBUGS-11719: Ensure ingress controllers are removed before load balancers

cmd/cluster/core/create.go, cmd/util/secrets.go
Backport of https://github.com/openshift/hypershift/commit/142d91e6b81858adbfd50907674c59d9f016c447
Issue: https://issues.redhat.com/browse/ACM-5173
=> ACM-5173 [backport 4.13] get pull secret instead of dockerconfigjson from mce credentials

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
The current health check HTTP client can block reconciliation for a long time if it cannot access the destination endpoint. This commit adds a timeout to the client so that reconciliation can proceed.
Fixes #OCPBUGS-13112
**Checklist**
=> OCPBUGS-13112: Add timeout to KAS health check client

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/main.go, docs/content/how-to/metrics-sets.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go, support/metrics/sets.go, support/metrics/sets_test.go, support/metrics/testdata/sreconfig.yaml
Introduces the use of a ConfigMap to configure the metrics relabelings to use in control plane ServiceMonitors. The ConfigMap should live in the hypershift operator namespace, be named 'sre-metric-set' and have a single key named 'config'. The contents of the config should be a YAML file with keys for each of the control plane components that produces a service monitor. An example is included in support/metrics/testdata.
Changes to the configuration ConfigMap result in the ConfigMap getting copied to all hosted control planes and the Control Plane Operator pod in those namespaces to be restarted. For the CPO pod, the configuration is only read once during startup and used by the service monitor reconciliation functions. …
=> HOSTEDCP-788: Configurable SRE MetricsSet

control-plane-operator/controllers/hostedcontrolplane/oapi/config.go
In order to meet CIS and PCI-DSS compliance, we need to have an audit-log-max backup set to 10 or any appropriate value, we should add this as a default so that no additional configuration is needed after the installation.
**Which issue(s) this PR fixes** *
Jira #https://issues.redhat.com/browse/OSD-15157
**Checklist**
=> Add audit-log-maxbackup setting for openshift-api-server

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/main.go, docs/content/how-to/metrics-sets.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go, hypershift-operator/main.go, support/metrics/sets.go, support/metrics/sets_test.go, support/metrics/testdata/sreconfig.yaml
Introduces the use of a ConfigMap to configure the metrics relabelings to use in control plane ServiceMonitors. The ConfigMap should live in the hypershift operator namespace, be named 'sre-metric-set' and have a single key named 'config'. The contents of the config should be a YAML file with keys for each of the control plane components that produces a service monitor. An example is included in support/metrics/testdata.
Changes to the configuration ConfigMap result in the ConfigMap getting copied to all hosted control planes and the Control Plane Operator pod in those namespaces to be restarted. For the CPO pod, the configuration is only read once during startup and used by the service monitor reconciliation functions. …
=> Bug HOSTEDCP-788: [release-4.13] Configurable SRE MetricsSet

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/main.go, docs/content/how-to/metrics-sets.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go, hypershift-operator/main.go, support/metrics/sets.go, support/metrics/sets_test.go, support/metrics/testdata/sreconfig.yaml
Introduces the use of a ConfigMap to configure the metrics relabelings to use in control plane ServiceMonitors. The ConfigMap should live in the hypershift operator namespace, be named 'sre-metric-set' and have a single key named 'config'. The contents of the config should be a YAML file with keys for each of the control plane components that produces a service monitor. An example is included in support/metrics/testdata.
Changes to the configuration ConfigMap result in the ConfigMap getting copied to all hosted control planes and the Control Plane Operator pod in those namespaces to be restarted. For the CPO pod, the configuration is only read once during startup and used by the service monitor reconciliation functions. …
=> [release-4.12] Configurable SRE MetricsSet

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/controller.yaml, control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go
This PR integrates [work completed recently](https://github.com/kubevirt/csi-driver/pull/62) in the kubevirt-csi driver to enforce what infra cluster storageclasses can be used by guest clusters.
Right now, we only want to allow the default mapping of the default infra sc to a guest sc. In the future, we'll expand this to [allow users creating HostedClusters to define this storageclass mapping](https://github.com/openshift/hypershift/pull/2528) in greater detail.
=> Lock down kubevirt csi storageclass mappings

api/v1beta1/hostedcluster_types.go, cmd/infra/aws/iam.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
Removed KMS permissions not required to encrypt EC2 root volumes (ref: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#ebs-encryption-permissions)
Fixes #
**Checklist**
=> Removed unused KMS permissions for nodePool role

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/pki.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/certs/tls.go
- Sync Proxy TrustedCA ConfigMap to guest cluster
- Add proxy TrustedCA to MachineConfigServer trusted bundle
- Append proxy TrustedCA to oauth master CA bundle
This PR is a split from https://github.com/openshift/hypershift/pull/2240, but without the e2e test which was failing due to an incorrect configuration of the test proxy server.
This should be followed up by a new PR with an e2e to validate proxy setup works with a TrustedCA once a solution is found.
Fixes #[OCPBUGS-11383](https://issues.redhat.com/browse/OCPBUGS-11383)
**Checklist**
=> OCPBUGS-11383: Sync proxy TrustedCA to guest cluster

test/e2e/e2e_test.go
Add the `e2e.etcd-storage-class` e2e CLI flag to get the storage class for ETCD, if needed. By default, this flag is empty.
Fixes #
**Checklist**
=> Add a new e2e option for the ETCD storage class

docs/content/how-to/agent/create-agent-cluster.md
Fix docs
The last update to `Handling Ingress` section in create agent cluster (#1836) replaced AddressPool with IPAddressPool, unlike AddressPool IPAddressPool is used only for the ip assignement part. In order advertise the IP we should create L2Advertisement.
Fixes #
https://issues.redhat.com/browse/ACM-4277
**Checklist**
=> ACM-4277: docs: Add L2Advertisement CR to the Handling Ingress section in the agent docs

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Fixes #[OCPBUGS-13034](https://issues.redhat.com/browse/OCPBUGS-13034)
**Checklist**
=> OCPBUGS-13034: Cluster-api SA can't create events

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
Seen in 4.14
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn/1658789482020737024/artifacts/e2e-aws-ovn/run-e2e/artifacts/TestCreateClusterCustomConfig_PreTeardownClusterDump/namespaces/e2e-clusters-vlb54-example-zcndx/core/pods/logs/control-plane-operator-7cbb5b4964-mnfzz-control-plane-operator-previous.log
Seen in 4.13
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.13-periodics-e2e-aws-ovn/1658804612850782208/artifacts/e2e-aws-ovn/run-e2e/artifacts/TestCreateCluster_PreTeardownClusterDump/namespaces/e2e-clusters-j9wqg-example-frpkt/core/pods/logs/control-plane-operator-8596978568-6v4sp-control-plane-operator-previous.log …
=> fix nil deref in DefaultWorkerSecurityGroupID check

cmd/cluster/core/dump.go, cmd/cluster/core/forwarder.go, vendor/k8s.io/client-go/tools/portforward/doc.go, vendor/k8s.io/client-go/tools/portforward/portforward.go, vendor/modules.txt
Uses port-forwarding to access a kube-apiserver pod in the control plane directly. This avoids the need to have access to the external API endpoint of the guest cluster.
Fixes #[HOSTEDCP-996](https://issues.redhat.com//browse/HOSTEDCP-996)
**Checklist**
=> HOSTEDCP-996: CLI: enable guest cluster dump for private clusters

contrib/ci/hypershift-ci-1.yaml
We are hitting HC quota in the root CI cluster.  This was originally set conservatively to avoid overload issues in the root cluster.  Time has shown it to be stable at this load and worker memory utilization is low at around 50% on 64Gi nodes.
Lets push it from 20 to 30.
=> contrib: ci: increase HC quota in clusters namespace

ignition-server/controllers/local_ignitionprovider.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go
MCO recently introduced a new flag `--payload-version` that expects to take the payload release version as a value. This is currently inert but will be required once openshift/machine-config-operator#3688 is merged.
This was added to the installer in openshift/installer#7160.
Fixes #
**Checklist**
=> OCPBUGS-13547: Pass release image version to MCO bootstrap via --payload-version

hypershift-operator/metrics.go, support/conditions/conditions.go, support/util/expose.go, support/util/visibility.go, test/e2e/create_cluster_test.go, test/e2e/nodepool_test.go
Validates that all HostedCluster and NodePool conditions match their execrated status (true / false)
Fixes #[HOSTEDCP-960](https://issues.redhat.com/browse/HOSTEDCP-960)
**Checklist**
=> HOSTEDCP-960: Add e2e to validate HC/NP conditions expected status

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Using `hcp.Spec.Platform.Type` to avoid things like claiming "Kubevirt" for an AWS service account.  Also spell out "ccm" in "ccm deployment" on AWS and Kubevirt to match the existing phrasing for PowerVS.
**Checklist**
- [n/a] This change includes docs. 
- [n/a] This change includes unit tests.
=> control-plane-operator/controllers/hostedcontrolplane: Align reconcileCloudControllerManager error strings

api/fixtures/example.go, api/v1alpha1/nodepool_types.go, api/v1beta1/nodepool_conditions.go, api/v1beta1/nodepool_types.go, cmd/cluster/aws/create.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, cmd/nodepool/aws/create.go, cmd/nodepool/core/create.go, cmd/nodepool/create.go, cmd/version/version.go, docs/content/how-to/aws/create-aws-hosted-cluster-arm-workers.md, docs/content/reference/api.md, docs/mkdocs.yml, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, support/releaseinfo/fake/fake.go, test/e2e/arm_nodepool_test.go, test/e2e/e2e_test.go
Allows a User to add an ARM AWS instance type in a nodepool
https://issues.redhat.com/browse/ARMOCP-412
**Checklist**
@enxebre, @bryan-cox and I have been working on this and need some help.
Initially, we wanted the hypershift operator to intake an `instancetype`, and select the right AMI based on its `arch`. Unfortunately, this wouldn't work because the hypershift controller doesn't have enough AWS access to make that validation. Instead, we choose to put this logic in the hypershift cli.  While this works, I'm not sure if the hypershift cli is the only code that creates nodepools/hostedcontrolplanes. I'm afraid that we may have made an assumption that could break things like ACM/MCE, but we don't know enough about …
=> ARMOCP-412: Add ARM nodepool to AWS x86 Hosted Cluster

hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/metrics/metrics.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, test/e2e/util/fixture.go
Adds `hypershift_nodepools_deletion_duration_seconds` and `hypershift_nodepools_initial_rollout_duration_seconds` metrics
Fixes #[HOSTEDCP-975](https://issues.redhat.com/browse/HOSTEDCP-975)
**Checklist**
=> HOSTEDCP-975: Add NodePool DeletionDuration and InitialRolloutDuration metrics

cmd/install/install.go
Follow on to https://github.com/openshift/release/pull/39012
Remove magic flag setting when running in CI.  Workflow in o/r now explicitly sets these flags.
=> remove flags set by CI env var

control-plane-operator/controllers/hostedcontrolplane/routecm/deployment.go
What this PR does / why we need it:
Updated some more secret permissions to 416 specifically those mounted by
openshift-route-controller-manager
Which issue(s) this PR fixes (optional, use fixes #<issue_number>(, fixes #<issue_number>, ...) format, where issue_number might be a GitHub issue, or a Jira story:
Fixes #1031
**Checklist**
- [x ] Subject and description added to both, commit and PR.
- [x ] Relevant issues have been referenced.
=> Updated secret permissions for openshift-route-controller-manager

hypershift-operator/controllers/nodepool/metrics/metrics.go, test/e2e/util/fixture.go
This adds a `cluster_name` label to all nodepools metrics, which is needed to map nodepools to their HostedCluster
context: https://redhat-internal.slack.com/archives/C01C8502FMM/p1684256556058189
Fixes #[HOSTEDCP-975](https://issues.redhat.com/browse/HOSTEDCP-975)
**Checklist**
=> HOSTEDCP-975: Add cluster_name label to nodepools metrics

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/manifests/ingress.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/pki/ca.go, control-plane-operator/hostedclusterconfigoperator/cmd.go, control-plane-operator/hostedclusterconfigoperator/controllers/cmca/configmap_observer.go, control-plane-operator/hostedclusterconfigoperator/controllers/cmca/setup.go, control-plane-operator/hostedclusterconfigoperator/operator/config.go
Cleans up code of the CMCA controller in the HCCO. It watches configmaps that we are interested in in the guest cluster's
openshift-config-managed namespace and syncs them to target configmaps on the control plane side. The CMCA controller not longer updates deployments directly, rather the recocile function of each deployment updates the hash annotation for itself.
The 'router-ca' configmap no longer exists, so it was removed. Instead the 'default-ingress-cert' configmap is what is now synced.
Fixes #OCPBUGS-13168
**Checklist**
=> OCPBUGS-13168: Include default ingress CA in root CA bundle

hypershift-operator/controllers/nodepool/kubevirt/imagecacher.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt_test.go, support/releaseinfo/fixtures/4.10-installer-coreos-bootimages.yaml, support/releaseinfo/releaseinfo.go, support/releaseinfo/releaseinfo_test.go, test/e2e/e2e_test.go, test/e2e/nodepool_kv_cache_image_test.go, test/e2e/nodepool_machineconfig_test.go, test/e2e/nodepool_nto_machineconfig_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/util/util.go
This PR introduces the ability to use the new kubevirt platform rhcos image as detected from the release image. This entirely replaces the old usage of the openstack image. Moving forward, we will only allow guest clusters to be created with kubevirt platform when the guest cluster contains a reference to the kubevirt rhcos image (ocp >= 4.14)
I also re-enabled some of the nodepool tests which appear to be working when given a longer timeout period.
=> Use newly introduced KubeVirt Platform rhcos Image

api/v1alpha1/hostedcluster_types.go, api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, hack/app-sre/saas_template.yaml
This is a follow up PR from https://github.com/openshift/hypershift/pull/2549. 
This PR contains 2 changes:
- Make immutable the Etcd storage size in alpha and beta APIs
- Equalised the default storage size on alpha API
Fixes #[HOSTEDCP-947](https://issues.redhat.com/browse/HOSTEDCP-947)
**Checklist**
=> HOSTEDCP-947: Set ETCD Storage Size as immutable field and equalised the default size among both api versions

api/scheme.go, cmd/cluster/core/dump.go, support/api/scheme.go
1. fixed wrong namespace
2. only request kubevirt resources if kubevirt is in use, to avoid error of resource type unknown.
**Checklist**
=> Fix dump for Kubevirt

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
fixes the case where the kubeadmin secret deletion succeeded but removing the annotation from oauthDeployment failed, which will make it not possible to reconcile again because we are retuning early if the secret is not found.
**Checklist**
=> OCPBUGS-13970: Reconcile oauthDeployment annotations even if kubeadmin secret is not found

hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/metrics/metrics.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/metrics.go, test/e2e/util/fixture.go
backport of https://github.com/openshift/hypershift/pull/2532, https://github.com/openshift/hypershift/pull/2558 and https://github.com/openshift/hypershift/pull/2580
=> [release-4.13] HOSTEDCP-975: Backport nodepools metrics

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml
The events flag causes the external-dns controller to ignore route events for extended periods of time in some circumstances. For now, removing the flag and replacing with the interval flag.
Fixes #OCPBUGS-14169
**Checklist**
=> OCPBUGS-14169: Remove external-dns --events flag

api/v1alpha1/hostedcluster_types.go, api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, hack/app-sre/saas_template.yaml
Manual cherry-pick from https://github.com/openshift/hypershift/pull/2588
Fixes #[HOSTEDCP-1010](https://issues.redhat.com/browse/HOSTEDCP-1010)
**Checklist**
=> [release-4.13] HOSTEDCP-1010: Set ETCD Storage Size as immutable field and equalised the default size among both api versions

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/metrics/metrics.go, test/e2e/util/fixture.go
Fixes #[OCPBUGS-13113](https://issues.redhat.com/browse/OCPBUGS-13113)
**Checklist**
=> OCPBUGS-13113: Add ClusterUpgradeDuration metric

cmd/install/install.go, hack/app-sre/saas_template.yaml
Disables `v1alpha1` and the conversion webhook by default when installing hypershift.
Fixes #[HOSTEDCP-967](https://issues.redhat.com/browse/HOSTEDCP-967)
**Checklist**
=> HOSTEDCP-967: Disable v1alpha1 and conversion webhook by default

docs/content/how-to/aws/create-aws-hosted-cluster-arm-workers.md
Adds 'Creating Arm NodePools Through the API' section to clarify how to create Arm NodePools through the API directly.
Fixes #
**Checklist**
=> Add 'Creating Arm NodePools Through the API' Section

api/scheme.go, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ignition/params.go, control-plane-operator/controllers/hostedcontrolplane/ignition/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/manifests/ignition.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/main.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go, ignition-server/cmd/start.go, support/capabilities/management_cluster_capabilities.go, support/globalconfig/imagecontentsource.go, support/releaseinfo/fake/fake.go, support/releaseinfo/registry_image_content_policies.go, support/releaseinfo/releaseinfo.go, support/util/util.go, support/util/util_test.go
Includes any registry mirrors from ImageContentSourcePolicy (ICSP) and ImageDigestMirrorSet (IDMS) policies from the management cluster. Registry mirrors from these policies provide the cluster with alternatives to the default Operator Hub and image registries in disconnected environments.
Injects the trusted CA bundle from the openshift-config-managed pod into the HyperShift Operator pod. These additional CAs are needed in disconnected environments utilizing an OpenShift management cluster.
Fixes [OCPBUGS-11939](https://issues.redhat.com/browse/OCPBUGS-11939)
**Checklist**
=> OCPBUGS-11939: Initialize RegistryOverrides w/ mgmt cluster ICSP

cmd/cluster/core/dump.go
When executing multiple 'cluster dump' within the same pod (as in the e2e case), only one run can listen on port 6443 and the others fail. This changes the dump command to use a random port locally so that different runs do not conflict.
**Checklist**
=> hypershift dump: use random local port for kas port-forwarding

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Backport for release-4.13 version which includes
- https://github.com/openshift/hypershift/pull/2565
- https://github.com/openshift/hypershift/pull/2586
- Fixes #[OCPBUGS-13034](https://issues.redhat.com/browse/OCPBUGS-13034) (main)
- Fixes #[OCPBUGS-13735](https://issues.redhat.com/browse/OCPBUGS-13735) (backport for 4.13)
**Checklist**
=> [release-4.13] OCPBUGS-13735: Cluster-api SA can't create events and fix permissions wrongly included

cmd/install/install.go, hack/app-sre/saas_template.yaml
Allow the external-dns image to be set in the install cli through the external-dns-image flag.
Fixes [HOSTEDCP-1009](https://issues.redhat.com/browse/HOSTEDCP-1009)
**Checklist**
=> HOSTEDCP-1009: Allow external-dns image to be set in install cli

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go, control-plane-operator/hostedclusterconfigoperator/operator/config.go
Fixes #[OCPBUGS-14087](https://issues.redhat.com/browse/OCPBUGS-14087)
**Checklist**
=> OCPBUGS-14087: Enable HCCO to reconcile over the OperatorHub's disableAllDefaultSources object

cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/version/version.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, test/e2e/e2e_test.go
Allow to specify a `release-stream` like 4.14.0-0.nightly instead of a full pull-spec release-image
=> cli: Add release-stream flag

api/fixtures/example.go, api/v1beta1/hostedcluster_types.go, hypershift-operator/controllers/nodepool/kubevirt/imagecacher.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
This allows the unsupported openstack rhcos variant to be used with kubevirt when a special annotation is used. We need this for internal testing of tenant clusters <= 4.13
example hypershift cli command to enable this functionality
```
hypershift create cluster kubevirt \
--name $CLUSTER_NAME \
--annotations "hypershift.openshift.io/allow-unsupported-kubevirt-rhcos-variants=true"
--pull-secret $PULL_SECRET_PATH \
--ssh-key $SSH_KEY_PATH  \
--node-pool-replicas $REPLICAS \
--release-image $RELEASE_IMAGE \
--memory $MEM \
--cores $CPU
```
=> KubeVirt Openstack image annotation override

hypershift-operator/main.go, support/globalconfig/imagecontentsource.go
Only check for IDMS CRs only if the management cluster has the required API
Fixes [OCPBUGS-14575](https://issues.redhat.com/browse/OCPBUGS-14575)
**Checklist**
=> OCPBUGS-14575: Check for IDMS only if mgmt cluster has req API

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go, hypershift-operator/controllers/hostedcluster/internal/platform/powervs/powervs.go
This is needed to accomodate CAPI 1.4 coming in 4.14 payload https://main.cluster-api.sigs.k8s.io/developer/providers/migrations/v1.3-to-v1.4.html, https://github.com/kubernetes/enhancements/issues/2845, https://github.com/kubernetes/kubernetes/pull/112120
This is currently breaking CAPI/CAPA rebases:
See https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-api/175/pull-ci-openshift-cluster-api-master-e2e-hypershift/1661096357663870976/artifacts/e2e-hypershift/run-e2e/artifacts/TestCreateCluster_PreTeardownClusterDump/namespaces/e2e-clusters-cdnlw-example-6pcmz/core/pods/logs/cluster-api-7bfdd5447-qc5xt-manager.log …
=> Remove alsologtostderr flag form CAP*

test/e2e/nodepool_machineconfig_test.go, test/e2e/nodepool_nto_machineconfig_test.go
Sometimes it takes the networking stack awhile to come online for new nodes with the KubeVirt platform. This likely has to do more with our CI environment than anything else. We're running the KubeVirt VMs very lean in order to be able to run so many tests in parallel. 
If we increase time timeout for the NTO and MachineConfig node pool tests, i have been able to confirm that they will pass with better consistency.
=> Extend np test timeout for KubeVirt platform

Makefile, product-cli/cmd/cluster/cluster.go, product-cli/cmd/create/create.go, product-cli/main.go
Adds a Makefile build command to create a productized version of the HyperShift CLI and adds the beginning source code directory structure for the productized CLI commands.
Fixes [HOSTEDCP-1036](https://issues.redhat.com/browse/HOSTEDCP-1036)
**Checklist**
=> HOSTEDCP-1036: Create Makefile path to create productized CLI

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Not all cloud provider load balancer provisioners populate the Hostname field in the service.status.loadBalancer.ingress Some cloud providers (e.g. Azure, GCP, MetalLB) have load balancers that their ingress points are IP-based, not hostname-based. This PR changes the kube apiserver load balancer healthcheck to accomodate for IP-based ingress points as well. This fixes in issue where in some providers, the hosted cluster is successfully created but it has not completed due to a misleading 'APIServer load balancer is not provisioned' message.
Fixes #
**Checklist**
=> Minor fix in KAS LB HealthCheck

control-plane-operator/controllers/hostedcontrolplane/cloud/aws/providerconfig.go
This commit sets this value to always be true, otherwise we rely on an explicit list of valid AWS regions in the upstream cloud-provider https://github.com/openshift/kubernetes/blob/release-4.12/vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go#L19-L41 which may become out-of-date. This addresses the bug found in OCPBUGS-14620 where ap-southeast-3 became supported starting in OCP 4.11, but was not in this explicit upstream list until OCP 4.13.
Fixes OCPBUGS-14620
**Checklist**
=> OCPBUGS-14620: Set `DisableStrictZoneCheck = true` in the AWS Cloud Provider config

control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile_test.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, support/globalconfig/ingress.go
The ingress.config.openshift.io API allows setting the type of LoadBalancer to use for AWS ingress. This commit honors that setting when creating the initial default IngressController for clusters on AWS.
Fixes #OCPBUGS-14784
**Checklist**
=> OCPBUGS-14784: Honor global ingress configuration LoadBalancer type on AWS

control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcileDeployment.yaml, hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt_test.go, support/config/deployment.go, support/config/deployment_test.go, support/config/types.go, test/e2e/util/fixture.go, test/e2e/util/util.go
Fixes #[OCPBUGS-11882](https://issues.redhat.com/browse/OCPBUGS-11882)
Depend on:
- https://github.com/openshift/aws-ebs-csi-driver-operator/pull/231
- https://github.com/openshift/cluster-network-operator/pull/1822
- https://github.com/openshift/aws-ebs-csi-driver-operator/pull/232
- https://github.com/openshift/cluster-network-operator/pull/1830
This is a second approach from https://github.com/openshift/hypershift/pull/2597. This makes more sense.
**Checklist**
=> OCPBUGS-11882: Annotate HCP pods with the safe-to-evict-local-volume CA annotation

control-plane-operator/main.go
Check for the existence of OPENSHIFT_IMG_OVERRIDES before using the environment variable to create registry overrides.
https://github.com/openshift/hypershift/pull/2437 created a binding between HO and CPO as a CPO that contains this PR crashes when deployed by an HO that does not.
The reason appears to be related to the absence of the OPENSHIFT_IMG_OVERRIDES envvar on the CPO deployment.
Fixes [OCPBUGS-14633](https://issues.redhat.com/browse/OCPBUGS-14633)
**Checklist**
=> OCPBUGS-14633: Check for OPENSHIFT_IMG_OVERRIDES before using

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/oauth/config.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
This fixes the issue by checking to see if the config map for the CA Bundle exists, and only applying the config/using the volume if it does.
Note that this fix is against 4.12 only.  This is to fix a Z stream upgrade issue from 4.12.8 to 4.12.9 and is not needed in 4.13 or main.
Introduced by https://github.com/openshift/hypershift/pull/2295
Fixes: OCPBUGS-11555
Fixes #
**Checklist**
=> [release 4.12] OCPBUGS-11555: OAuth OpenShift deployment requires ConfigMap mount

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, ignition-server/controllers/local_ignitionprovider.go, test/e2e/nodepool_test.go
Currently we render the feature gate at the HCP level which results in a discrepancy when mco consume it along with a given NodePool payload-version that differs from the one used by the HCP to generate it. Related https://github.com/openshift/hypershift/pull/2643
CI Failure example
bootstrap.go:47] error running MCC[BOOTSTRAP]: error creating feature gate access: unable to determine features: missing desired version \"4.14.0-0.ci.test-2023-06-08-101141-ci-op-gvin17ww-initial\" in featuregates.config.openshift.io/cluster\n"}
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/3724/pull-ci-openshift-machine-config-operator-master-e2e-hypershift/1666749702499995648
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/p …
=> Let payload provider render feature gate yaml

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/tenant_csidriver.yaml, control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kubevirt.go
Add FSGroup support to kubevirt-csi-driver deployment. Add CSI driver resource because it was missing in hypershift deployments.
Source of CSIDriver:
https://github.com/kubevirt/csi-driver/pull/87
Fixes #
**Checklist**
=> CNV-24818: Add fsGroup support to kubevirt-csi-driver

api/v1alpha1/hostedcluster_types.go, api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hack/app-sre/saas_template.yaml
Some KubeVirt platform values were meant to be immutable, but immutability was not being enforced. This fixes that by adding validation rules to enforce immutability on those values.
=> Enforce Immutability of some KubeVirt Platform Values

control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This is needed to let the autoscaler to operate https://github.com/openshift/kubernetes-autoscaler/pull/256#issuecomment-1582621901 https://github.com/kubernetes/autoscaler/pull/4676
Fixes #
**Checklist**
=> Update autocaler RBAC to accomodate machinepools support added upstream

api/v1beta1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hack/app-sre/saas_template.yaml
Changing this field in a NodePool is not supported. Enforcing this via CEL to raise the UX bar. This becomes specially important as we plan to GA for self-hosted where consumers interact directly with this API.
Fixes #
**Checklist**
=> Make NodePool arch input immutable

hypershift-operator/controllers/nodepool/metrics/metrics.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
records time in seconds it took from NodePool creation until a given condition transitions to true, for the following conditions:
- NodePoolReachedIgnitionEndpoint
- NodePoolAllMachinesReadyConditionType
- NodePoolAllNodesHealthyConditionType
Fixes #https://issues.redhat.com/browse/HOSTEDCP-1008
**Checklist**
=> HOSTEDCP-1008: Add NodePoolTransitionSeconds metric

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws_test.go
fixes deletion of aws resources not skipped when OIDC/ValidIdentiityProvider condition is set to `Unknown`
Fixes #[OCPBUGS-14859](https://issues.redhat.com/browse/OCPBUGS-14859)
**Checklist**
=> OCPBUGS-14859: Skip AWS resource deletion for 'Unknown' OIDC state

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/mcs/reconcile.go
Currently the code does not gracefully handle the UserCA bundle not existing and errors out on fetching the trusted CA bundle which short circuts any further reconcilation automation. This ensures it is gracefully handled to allow full reconcilation of the control-plane-operator
Fixes #
**Checklist**
=> properly handle user CA bundle not existing

cmd/cluster/kubevirt/create.go, product-cli/cmd/cluster/cluster.go, product-cli/cmd/cluster/kubevirt/OWNERS, product-cli/cmd/cluster/kubevirt/create.go
Add the create cluster command for the KubeVirt platform for the HCP CLI.
Fixes [HOSTEDCP-1020](https://issues.redhat.com/browse/HOSTEDCP-1020).
**Checklist**
=> HOSTEDCP-1020: Add Create Cluster for KubeVirt for HCP CLI

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Now the HCCO checks the annotations and labels of the LoadBalancer services in order to decide if we should take care of the deletion or delegate to the ingress-operator
Fixes #[OCPBUGS-14637](https://issues.redhat.com/browse/OCPBUGS-14637)
**Checklist**
=> OCPBUGS-14637: Check OwningIngressController also in Labels

api/v1beta1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Allows creating a HostedCluster with alternate images for the different components included in the release.
**Checklist**
=> Expose annotation to allow release image overrides

cmd/destroy/destroy.go, product-cli/cmd/cluster/cluster.go, product-cli/cmd/cluster/kubevirt/destroy.go, product-cli/cmd/destroy/destroy.go, product-cli/main.go
Add destroy cluster command for the KubeVirt platform for the HCP CLI.
Fixes [HOSTEDCP-1031](https://issues.redhat.com/browse/HOSTEDCP-1031)
**Checklist**
=> HOSTEDCP-1031: Add Destroy Cluster Cmd for KubeVirt for HCP CLI

product-cli/cmd/cluster/kubevirt/create.go
The KubeVirt platform has a cli arg used during cluster create called `service-publishing-strategy`. This arg allowed us to switch between using a NodePort or LoadBalancer for exposing the HCP's api server and other services.
The NodePort option works in dev, but is not resilient enough for production. This is because the NodePort option picks a random mgmt node for the api server passed in the guest cluster's kubeconfig. If that mgmt node ever cycles out, it will result in the guest cluster no longer being accessible. That's fine for development, but we don't want to expose end users to this behavior.
=> Remove --service-publishing-strategy from production cli

cmd/install/install.go, hack/app-sre/saas_template.yaml
Reverts openshift/hypershift#2685
revert because this would drop support for older 4.12.z clusters before https://github.com/openshift/cluster-network-operator/pull/1816
=> Revert "HOSTEDCP-967: [Re-revert] Disable v1alpha1 and conversion webhook by default"

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, support/util/deployment.go, support/util/deployment_test.go
https://issues.redhat.com/browse/HOSTEDCP-1073
After this PR, the HCP reconciliation rolls out in the following runlevels, in line with what the CVO would do, where all components in each runlevel must be fully rolled out before reconciling the next runlevel.
- etcd
- kube-apiserver
- kube-controller-manager, kube-scheduler, openshift-apiserver
- everything else
This fixes both the Jira issue and the issue where previously `IsDeploymentReady` didn't actually work because the `Get` did not get the just create/updated version of the resource.
Timing looks like this:
- 2m30s etcd rollout
- 6m KAS rollout
- 3m30 for KCM, KS, OAS
- 4m for everything else
Total HCP upgrade time is 16m.
Before this change upgrade time was ~10m.  It could be faster if the race in `IsDeploymentReady` is hit, …
=> HOSTEDCP-1073: enforce blocked rollout of HCP

.github/dependabot.yml
In order to keep track of dependency updates in an automatic manner, let's add dependabot to the repository.
It adds configuration so that the dependabot service manages the go module dependencies in this repository. It will solve the lack of automated dependency detection.
**Checklist**
=> HOSTEDCP-1067: Add dependabot dependency management

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
1. validate hostname required for APIServer service when type is `Route`
2. validate hostname is not set for all services except APIServer and OAuth if endpoint access is not `Public`
3. validate APIServer is published as `Route` if endpoint access is `Public`
Fixes #[HOSTEDCP-1016](https://issues.redhat.com/browse/HOSTEDCP-1016)
**Checklist**
=> HOSTEDCP-1016: Validate publishing strategies

cmd/kubeconfig/create.go, product-cli/cmd/create/create.go, product-cli/cmd/kubeconfig/create.go
Add Create kubeconfig for HCP CLI
Fixes [HOSTEDCP-1027](https://issues.redhat.com/browse/HOSTEDCP-1027)
**Checklist**
=> HOSTEDCP-1027: Add Create kubeconfig for HCP CLI

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Reverts openshift/hypershift#2651
CI management clusters are failing to create:
```
- lastTransitionTime: "2023-06-27T14:21:54Z"
message: service type APIServer with publishing strategy LoadBalancer is not supported
in combination with a Public endpoint access, use Route
observedGeneration: 3
reason: InvalidConfiguration
status: "False"
type: ValidConfiguration
```
=> Revert "HOSTEDCP-1016: Validate publishing strategies"

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, support/util/deployment.go, support/util/deployment_test.go
Manual pick of https://github.com/openshift/hypershift/pull/2726
Significant diff stat is due to https://github.com/openshift/hypershift/pull/2368 not being backported to 4.13.
Diff starts to line up here
https://github.com/openshift/hypershift/pull/2726/files#diff-3d4ffda0834e09a59a4d510523932e20b9234bcb9816e40258a0fb32a87a7006L819
=> [release-4.13] HOSTEDCP-1073: enforce blocked rollout of HCP

test/e2e/chaos_test.go
Avoid test flake like this
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn/1674055681918898176
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn/1673918852737536000
@csrwng
=> test/e2e: retry configmap create in etcd chaos tests

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/pki/ignitionserver.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/ignitionserver/manifests.go
4.13 backport of https://github.com/openshift/hypershift/pull/2662 and https://github.com/openshift/hypershift/pull/2668 for https://issues.redhat.com/browse/HOSTEDCP-1060
Manual backport required to resolve registry override and featuregate work present in `main`.
=> [release-4.13] HOSTEDCP-1060: refactor ignition-server reconcilation and add ignition-server proxy

api/v1beta1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/configoperator/params.go, control-plane-operator/controllers/hostedcontrolplane/cvo/params.go, control-plane-operator/controllers/hostedcontrolplane/dnsoperator/dnsoperator.go, control-plane-operator/controllers/hostedcontrolplane/etcd/params.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/machineapprover/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/nto/clusternodetuningoperator.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, control-plane-operator/controllers/hostedcontrolplane/ocm/params.go, control-plane-operator/controllers/hostedcontrolplane/olm/params.go, control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/routecm/params.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
**What this PR does / why we need it**: This PR adds support to override the default implementation of priority class handling by the HyperShift Operator to allow addition of custom priority classes.
Relates to #1041
Enhancement document: https://github.com/openshift/enhancements/blob/master/enhancements/hypershift/priority-class/priority-class-override.md
Doesn't include support for multus-admission-controller.--support for this component can be added after https://issues.redhat.com/browse/OCPBUGS-7942 is resolved. 
**Checklist**
=> feat: Enable priority class override

Dockerfile
I'm transitioning the KubeVirt platform OpenShift CI lanes to exercise the new production cli (hcp). However, it appears that we aren't building that tool in the hypershift-operator image.
my rehearse runs in this[ ci pr](https://github.com/openshift/release/pull/40716) fail due to no `hcp` cli being present.
```
/bin/bash: line 13: /usr/bin/hcp: No such file or directory
```
I think copying the hcp tool into the hypershift-operator container using the default Dockerfile will resolve this.
=> Add production cli (hcp) to dockerfile

hack/OWNERS
add OWNERS for new ci-tooling area label
N/A
=> add OWNERS for new ci-tooling area label

HACKING.md, hack/ci-test-e2e.sh, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/nodepool_kms_root_volume_test.go, test/e2e/util/aws.go
This PR adds flags to the e2e binary so that the hardcoded AWS objects can be removed from the e2e codebase:
* --e2e.aws-oidc-s3-bucket-name
* --e2e.aws-kms-key-alias
So that the e2e test can be run accordingly locally after creating the required AWS infrastructure on your own.
**Checklist**
=> Remove hardcoded AWS CI References

api/v1beta1/hostedcluster_types.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Currently: there is no path to disable data aggregation from Red Hat insights operator. Clients in sensitive environments operating hypershift under a managed deployment like IBM Cloud Satellite want the ability to disable this flow. This enables a path that will allow the existing documentation for disablement of these resources to work in hypershift environments (https://docs.openshift.com/container-platform/4.12/support/remote_health_monitoring/opting-out-of-remote-health-reporting.html).
Fixes #
**Checklist**
=> OCPBUGS-12208 ensureExists pullSecret resource reconciliation strategy

hypershift-operator/controllers/nodepool/nodepool_controller.go
This prevent the NodePool controller from producing a different condition message to convey the same state of the world
Fixes #
**Checklist**
=> OCPBUGS-15723: Let getMachinesForNodePool return machines ordered by creation Timestamp

control-plane-operator/controllers/hostedcontrolplane/kcm/config.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, support/config/constants.go
Fixes #[1391](https://github.com/openshift/hypershift/issues/1391)
**Checklist**
=> Leader election config update.

control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go
This indicates the autoscaler to detect similar node groups and balance the number of nodes between them https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md. For a HA setup is recommended to create similar pools across Zones and let the Autoscaler balance them
Fixes #
**Checklist**
=> OCPBUGS-15769: Set --balance-similar-node-groups for autoscaler

api/v1beta1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go, hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes_test.go, hypershift-operator/main.go, support/config/deployment.go, support/config/deployment_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go
Enables an isolation mode of only request serving pods in which those pods are allocated to dedicated nodes of the management cluster. The rest of the control plane pods can coexist with the pods of other hosted clusters in common nodes.
Fixes #[HOSTEDCP-1061](https://issues.redhat.com//browse/HOSTEDCP-1061)
**Checklist**
=> HOSTEDCP-1061: Implement dedicated request serving nodes for HostedClusters

cmd/nodepool/agent/create.go, product-cli/cmd/nodepool/agent/create.go, product-cli/cmd/nodepool/create.go
Add create NodePool for Agent for HCP CLI
Fixes [HOSTEDCP-1023](https://issues.redhat.com/browse/HOSTEDCP-1023)
**Checklist**
=> HOSTEDCP-1023: Add create NodePool for Agent for HCP CLI

hypershift-operator/controllers/platform/aws/controller.go, hypershift-operator/controllers/platform/aws/controller_test.go, hypershift-operator/metrics_test.go, vendor/github.com/go-logr/logr/funcr/funcr.go, vendor/github.com/go-logr/logr/testr/testr.go, vendor/modules.txt
This commit fixes a bug where VPC Endpoint Connections were not being successfully rejected by the HyperShift Operator during the cleanup process even after the original fix in #2438 because the error "ExistingVpcEndpointConnections" confusingly does not get returned as an error directly, but inside a valid response's "Unsuccessful" array.
Fixes OCPBUGS-14862
**Checklist**
=> OCPBUGS-14862: Reject VPCE Connections during VPCE Service cleanup

hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt_test.go
By default KubeVirt virtual machines using bridge binding are not migratable, this change annotate them to allow KubeVirt and ovn-kubernetes to migrate them.
**Checklist**
=> kubevirt: Annotate VMs to be live migratable

ignition-server/controllers/local_ignitionprovider.go, support/releaseinfo/registryclient/client.go, support/releaseinfo/registryclient/client_test.go
Retrieves the valid image for cluster-config-operator based on the arch of the system.
[OCPBUGS-15594](https://issues.redhat.com/browse/OCPBUGS-15594)
=> OCPBUGS-15594: Get valid arch image for cluster-config-operator

cmd/cluster/agent/destroy.go, cmd/kubeconfig/create.go, product-cli/cmd/cluster/agent/destroy.go, product-cli/cmd/cluster/cluster.go, product-cli/cmd/cluster/kubevirt/destroy.go, product-cli/cmd/kubeconfig/create.go
Add destroy cluster for Agent for HCP CLI
Fixes [HOSTEDCP-1030](https://issues.redhat.com/browse/HOSTEDCP-1030)
**Checklist**
=> HOSTEDCP-1030: Add destroy cluster for Agent for HCP CLI

cmd/cluster/agent/create.go, product-cli/cmd/cluster/agent/create.go, product-cli/cmd/cluster/cluster.go
Add create cluster for Agent for HCP CLI
Fixes [HOSTEDCP-1019](https://issues.redhat.com/browse/HOSTEDCP-1019)
**Checklist**
=> HOSTEDCP-1019: Add create cluster for Agent for HCP CLI

control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go
Follow up for https://github.com/openshift/hypershift/pull/2769
Fixes #
**Checklist**
=> OCPBUGS-15769: Include hypershift specific labels to be ignored by similar autoscaler groups

docs/content/how-to/aws/deploy-aws-private-clusters.md, hypershift-operator/controllers/platform/aws/controller.go
* The operator now expects to be able to perform ec2:RejectVpcEndpointConnections
* The message of AWS errors is logged, which can help identify which AWS operation is running into errors.
In response to feedback during QA, we should document required permissions and return AWS error messages to improve the troubleshooting experience when AWS permissions are missing.
OCPBUGS-14862
**Checklist**
=> OCPBUGS-14862 Improve clarity around hypershift operator permissions

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
This commit fixes a case where the deletion of an awsendpointservice can hang when the control plane operator is unable to perform route53:ListResourceRecordSets due to the Route53 Hosted Zone not existing anymore. In this case, we should just exit early as the record no longer exists.
Fixes OCPBUGS-16135
**Checklist**
=> OCPBUGS-16135: fix deletion bug when hostedzone is already deleted

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/ignitionserver/ignitionserver.go
https://issues.redhat.com/browse/OCPBUGS-16113
The HO has not reconciled the ignition-server in the HCP since 4.10.  However, due to unbounded support skew between the HO and CPOs, the HO must still be able to deploy the ignition-server is a way that is compatible with 4.10 and earlier.
https://github.com/openshift/hypershift/pull/2581, in particular, broke this by introducing a flag on the ignition-server that didn't exist in 4.10.
Ideally, we just want to freeze the ignition-server reconciliation code in the HO since it should never need to be updated and changing it risks introducing backward incompatibility.
Thus, this PR unshares the ignition-server reconciliation code between the CPO and HO and rolls back the changes introduced in https://github.com/openshift/hypershift/pull/2581 …
=> OCPBUGS-16113: unshare ignition-server reconciliation between HO and CPO

test/e2e/autoscaling_test.go
Updates autoscaler e2e to validate `--balance-similar-node-groups` feature of the autoscaler 
Fixes #[HOSTEDCP-1094](https://issues.redhat.com/browse/HOSTEDCP-1094)
**Checklist**
=> HOSTEDCP-1094: e2e autoscaler balancing similar node groups

control-plane-operator/controllers/hostedcontrolplane/ocm/params.go, control-plane-operator/controllers/hostedcontrolplane/routecm/params.go
This PR adds missing liveness and readiness probes to openshift-route-controller-manager and openshift-controller-manager. The services implement the probes but Hypershift does not utilize them.
This is the result of a security review for 4.12 Hypershift, original investigation can be found https://github.ibm.com/alchemy-containers/armada-update/issues/4117#issuecomment-53149378
=> OCPBUGS-11835: Add missing probes to two services

api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, hack/app-sre/saas_template.yaml
Makes ImageContentSource immutable
Fixes [HOSTEDCP-710](https://issues.redhat.com/browse/HOSTEDCP-710)
**Checklist**
=> HOSTEDCP-710: Make ImageContentSource immutable

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ignition/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, support/globalconfig/imagecontentsource.go
Allow HCP Specification to Support ICSP & IDMS. IDMS is replacing ICSP in OCP 4.13+. hcp.Spec.ImageContentSources was updated in OCPBUGS-11939 to replace ICSP with IDMS; however, HCP needs to support both ICSP & IDMS. Note, OpenShift clusters can only have either ICSP CRs or IDMS CRs; clusters cannot utilize both CR types at the same time.
Fixes [HOSTEDCP-1046](https://issues.redhat.com/browse/HOSTEDCP-1046)
**Checklist**
=> HOSTEDCP-1046: Allow HCP Specification to Support ICSP & IDMS

product-cli/cmd/cluster/cluster.go
Adds cloud platform-agnostic default flags to the HCP create cluster CLI command.
Fixes [HOSTEDCP-1093](https://issues.redhat.com/browse/HOSTEDCP-1093)
**Checklist**
=> HOSTEDCP-1093: Add default flags to HCP create cluster CLI cmd

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This is a follow up for https://github.com/openshift/hypershift/pull/2796 With out this existing HCs upgrading to this version of the HO fail to reconcile CAPI as they attempt to change the labelSelector.
Fixes #
**Checklist**
=> HOSTEDCP-1062: Make CAPI pod selector backward compatible

api/v1beta1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go, hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes_test.go, hypershift-operator/main.go, support/config/deployment.go, support/config/deployment_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go
Enables an isolation mode of only request serving pods in which those pods are allocated to dedicated nodes of the management cluster. The rest of the control plane pods can coexist with the pods of other hosted clusters in common nodes.
Fixes #[HOSTEDCP-1061](https://issues.redhat.com//browse/HOSTEDCP-1061)
**Checklist**
=> HOSTEDCP-1061: [release-4.13] Implement dedicated request serving nodes for HostedClusters

api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, hack/app-sre/saas_template.yaml
Reverts openshift/hypershift#2815
This is necessary for the ability to convert from public endpoints (public registries) to private endpoints (private registries) in IBM Cloud
=> Revert "HOSTEDCP-710: Make ImageContentSource immutable"

hypershift-operator/controllers/hostedcluster/network_policies.go, support/util/util.go, support/util/util_test.go
The implementation added now, validates the ClusterNetwork CIDR used to build the HostedCluster CR. The CIDR added to the NetworkPolicy now matches the ClusterNetwork stack in order to block egress traffic
Fixes #[OCPBUGS-14783](https://issues.redhat.com/browse/OCPBUGS-14783)
**Checklist**
=> OCPBUGS-14783: Fix NetworkPolicy to work over IPv4 and IPv6

product-cli/cmd/cluster/cluster.go
Removes name as a persistent flag required field since this is already initialized. Marking the field as required forces a user to include the flag in the cli command.
Fixes [HOSTEDCP-1020](https://issues.redhat.com/browse/HOSTEDCP-1020)
**Checklist**
=> HOSTEDCP-1020: Remove name as a persistent flag required field

control-plane-operator/controllers/hostedcontrolplane/etcd/params.go, control-plane-operator/controllers/hostedcontrolplane/etcd/params_test.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile_test.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Added supportability for IPv6 and Dual stack networks on ETCD StatefulSet.
Already tested in a IPv6 environment in 4.14 with MCE 2.4
Fixes #[OCPBUGS-14163](https://issues.redhat.com/browse/OCPBUGS-14163)
**Checklist**
=> OCPBUGS-14163: Fixed ETCD to work in Ipv6 and Dual stack envs

control-plane-operator/controllers/hostedcontrolplane/oauth/config.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
This is an additional fix for 11555, making it so the container also does not try to mount the CA bundle mount.
This patch only applies to 4.12 as it is a z stream updgrade issue.
Fixes #
**Checklist**
=> [release 4.12] OCPBUGS-11555: OAuth OpenShift deployment requires ConfigMap mount patch2

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, hypershift-operator/controllers/hostedcluster/ignitionserver/ignitionserver.go
Modified the Ignition proxy server to support IPv4 and IPv6
Fixes #[OCPBUGS-16809](https://issues.redhat.com/browse/OCPBUGS-16809)
**Checklist**
=> OCPBUGS-16809: Configured IgnitionProxy to support IPv4 and IPv6

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ignition/params.go, control-plane-operator/controllers/hostedcontrolplane/ignition/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/manifests/ignition.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, support/globalconfig/imagecontentsource.go
Allow HCP Specification to Support ICSP & IDMS. IDMS is replacing ICSP
in OCP 4.13+. hcp.Spec.ImageContentSources was updated in OCPBUGS-11939
to replace ICSP with IDMS; however, HCP needs to support both ICSP &
IDMS. Note, OpenShift clusters can only have either ICSP CRs or IDMS
CRs; clusters cannot utilize both CR types at the same time.
Fixes [HOSTEDCP-1110](https://issues.redhat.com/browse/HOSTEDCP-1110)
**Checklist**
=> HOSTEDCP-1110: [backport-4.13] Allow HCP Specification to Support ICSP & IDMS

hypershift-operator/controllers/nodepool/nodepool_controller.go
Adds ImageDigestMirrorSet (IDMS) to the list of valid config manifests to be included in node ignition configuration.
Fixes [HOSTEDCP-1046](https://issues.redhat.com/browse/HOSTEDCP-1046)
**Checklist**
=> HOSTEDCP-1046: Add IDMS to the list of valid config manifests

hypershift-operator/controllers/hostedcluster/network_policies.go
At some lab experimental scenarios users are using different CNIs. This change remove the ovn-k API dependency to remove problems with other CNIs.
Fixes #
**Checklist**
=> kubevirt: Reconcile EgressFirewall only for ovn-k

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_cm.go, control-plane-operator/controllers/hostedcontrolplane/ocm/config.go, control-plane-operator/controllers/hostedcontrolplane/ocm/config_test.go, control-plane-operator/controllers/hostedcontrolplane/ocm/testdata/zz_fixture_TestReconcileOpenShiftControllerManagerConfig.yaml, control-plane-operator/controllers/hostedcontrolplane/routecm/config.go, control-plane-operator/controllers/hostedcontrolplane/routecm/config_test.go, control-plane-operator/controllers/hostedcontrolplane/routecm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/routecm/params.go, control-plane-operator/controllers/hostedcontrolplane/routecm/testdata/zz_fixture_TestReconcileOpenShiftRouteControllerManagerConfig.yaml
- split config from OCM and pass only relevant data
- pass kubeconfig and pod name/namespace
This has to be merged before https://github.com/openshift/route-controller-manager/pull/28
Fixes # https://issues.redhat.com/browse/WRKLDS-730
**Checklist**
=> [WRKLDS-730] react to route-controller-manager refactoring

control-plane-operator/controllers/hostedcontrolplane/ocm/params.go, control-plane-operator/controllers/hostedcontrolplane/routecm/params.go
openshift-controller-manager deployment uses `/healthz` endpoint https://github.com/openshift/cluster-openshift-controller-manager-operator/blob/master/bindata/v3.11.0/openshift-controller-manager/deploy.yaml even though `/healhtz/ready` is available, there does not seem to be good reason for using it: https://github.com/openshift/openshift-controller-manager/blob/80c4923e0b2014ec8b8a6845c21078e6cc036f91/pkg/cmd/controller/standalone_apiserver.go#L75
With a switch to library-go in https://github.com/openshift/route-controller-manager/pull/28 (and k8s.io/apiserver) `/healthz/ready` endpoint is no longer available: https://github.com/kubernetes/apiserver/blob/d2172f30e1af3782a7124e21b8cb4676fc789acc/pkg/server/config.go#L412, so we need to update …
=> WRKLDS-730: use default /healthz path for readiness probe in OCM and RCM

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go
The KubeVirt platform is currently failing a conformance test [1] due to a missing annotation on the kubevirt-csi daemonset. This PR resolves that failure.
1. [sig-node][apigroup:config.openshift.io] CPU Partitioning cluster platform workloads should be annotated correctly for DaemonSets [Suite:openshift/conformance/parallel]
=> [CNV-31227] Add workload management annotation to kubevirt-csi daemonset

cmd/cluster/aws/create.go, cmd/cluster/aws/destroy.go, cmd/cluster/aws/destroy_test.go, product-cli/cmd/cluster/aws/destroy.go, product-cli/cmd/cluster/cluster.go
Add HCP CLI Command to Destroy a Cluster on AWS
Fixes [HOSTEDCP-1029](https://issues.redhat.com/browse/HOSTEDCP-1029)
**Checklist**
=> HOSTEDCP-1029: Add HCP CLI Command to Destroy a Cluster on AWS

docs/content/how-to/kubevirt/configuring-storage.md, docs/content/how-to/kubevirt/create-kubevirt-cluster.md, docs/content/how-to/kubevirt/external-infrastructure.md, docs/content/how-to/kubevirt/ingress-and-dns.md, docs/mkdocs.yml
This addresses two issues with the kubevirt platform docs.
1. Some new sections where not added to the documentation's index yaml, which caused these sections to not appear in the left hand navigation bar.
2. This transitions the documentation to reference the new `hcp` cli tool over the `hypershift` cli tool during cluster creation/destruction. The `hypershift` cli tool is still referenced as a method of installing a development version of the HyperShift Operator.
=> Kubevirt how-to docs updates

api/v1beta1/hostedcluster_types.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/operator/config.go, test/e2e/create_cluster_test.go, test/e2e/util/util.go
Disallow mutating/validating webhooks using URLs targeting any service in the hcp namespace, unless 'hypershift.io/allow-guest-webhooks' flag is present.
Fixes #[HOSTEDCP-1063](https://issues.redhat.com/browse/HOSTEDCP-1063)
**Checklist**
=> HOSTEDCP-1063: Disallow webhooks URLs targeting control plane services

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller_test.go
This ensures that clusters running before we enforced the hypershift security group on the endpoint creation get that SG as well. 
Fixes #
**Checklist**
=> HOSTEDCP-1121: Ensure SG reconciliation for aws endpoint

hypershift-operator/controllers/hostedcluster/network_policies.go
The private router should only be able to use the pod network to contact considered request serving components.
Fixes #[HOSTEDCP-1064](https://issues.redhat.com/browse/HOSTEDCP-1064)
**Checklist**
=> HOSTEDCP-1064: Add egress policy for private-router

test/e2e/util/util.go
Follow on to https://github.com/openshift/hypershift/pull/2854
This causes e2e to fail ~5% of the time depending on what random `spec.schedule` is selected for the `olm-collect-profiles` CronJob
Example failure:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_hypershift/2834/pull-ci-openshift-hypershift-main-e2e-aws/1686695356840022016
=> skip olm-collect-profiles in EnsureComponentsHaveNeedManagementKASAccessLabel

test/e2e/util/util.go
For interconnect upgrades (https://issues.redhat.com/browse/SDN-4042) - i.e when moving from OCP 4.13 to OCP 4.14 where IC is enabled, we do a 2 phase rollout of ovnkube-master and ovnkube-node pods in the openshift-ovn-kubernetes namespace. This is to ensure we have minimum disruption since major architectural components are being brought from control-plane down to the data-plane.
Since its a two phase roll out with each phase taking taking approximately 10mins, we effectively double the time it takes for OVNK component to upgrade thereby increasing the timeout thresholds for upgrades rollout. Thus opening this PR to push up the timers.
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, …
=> SDN-4042: Increase upgrade rollout timers

product-cli/cmd/nodepool/aws/create.go, product-cli/cmd/nodepool/create.go
Add HCP CLI Command to Create a NodePool on AWS
Fixes [HOSTEDCP-1025](https://issues.redhat.com/browse/HOSTEDCP-1025)
**Checklist**
=> HOSTEDCP-1025: Add HCP CLI Command to Create a NodePool on AWS

api/v1beta1/hostedcluster_types.go, cmd/cluster/core/create.go, cmd/cluster/core/create_test.go, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, support/supportedversion/version.go
Previously, the hostedCluster.Spec.Release.Image was required and the hcp or hypershift cli defaulted that value client side. This posed several issues though.
1. The defaulting did not take into consideration what the max and min version the deployed hypershift operator supports, which will eventually lead to the client defaulting unsupported versions.
2. This logic was all client side, which meant that it couldn't be used in a gitops flow or reused by the console web UI.
The new logic performs defaulting the release image on the backend using an **optional** mutating webhook. The logic takes into account the latest/min supported versions and picks the most recent version that falls within those constraints.
A webhook was chosen over performing defaults in the controller's reconcile loop …
=> [HOSTEDCP-1041] Defaulting webhook for self managed HCP

control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile_test.go, control-plane-operator/controllers/hostedcontrolplane/pki/etcd.go
Changes the host name used for an etcd member's advertise address and ensures that the etcd server certificate considers that address a valid address.
This allows referencing etcd members by their advertise address directly. The name that was used previously did not resolve.
Fixes #OCPBUGS-17446
**Checklist**
=> OCPBUGS-17446: Set advertise-address in HCP etcd to resolvable name

api/v1beta1/hostedcluster_types.go, cmd/cluster/core/create.go, cmd/cluster/core/create_test.go, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, support/supportedversion/version.go
Reverts openshift/hypershift#2864
Took out CI, must restore
`
2023-08-09T12:11:42Z	ERROR	Failed to create cluster	{"error": "failed to apply object \"clusters/c67a39c9c1920084cf95-mgmt\": HostedCluster.hypershift.openshift.io \"c67a39c9c1920084cf95-mgmt\" is invalid: spec.release.image: Invalid value: \"\": spec.release.image in body should match '^(\\w+\\S+)$'"}
github.com/openshift/hypershift/cmd/cluster/aws.NewCreateCommand.func1
`
Removal of the client-side release image defaulting in combination with the disabling (by default) the webhook caused this.
Example job
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn/1689157066083536896
cc @davidvossel
=> Revert "[HOSTEDCP-1041] Defaulting webhook for self managed HCP"

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, docs/content/how-to/disconnected/automatically-initialize-registry-overrides.md, docs/content/how-to/disconnected/disconnected-workarounds.md, docs/content/how-to/disconnected/image-content-sources.md, docs/mkdocs.yml
Follow on for [HOSTEDCP-1046](https://issues.redhat.com//browse/HOSTEDCP-1046) that:
* Removes the version check on reconciling the image content type policy since that is not needed in release image versions greater than 4.13 (for [HOSTEDCP-1102](https://issues.redhat.com//browse/HOSTEDCP-1102)).
* Adds documentation on the ImageContentSources field.
* Adds documentation on how RegistryOverrides are automatically initialized by the HyperShift Operator from ICSPs or IDMSs within the management cluster.
* Adds documentation on disconnected environment workaround with respect to ICSP and image tags.
Fixes 
* [HOSTEDCP-1046](https://issues.redhat.com/browse/HOSTEDCP-1046)
* …
=> HOSTEDCP-1046, HOSTEDCP-1102: Follow-on Items

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/nodepool/haproxy.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, support/util/fakeimagemetadataprovider/fakeimagemetadataprovider.go, support/util/imagemetadata.go
This PR has been tested and validated in a bare metal environment based on IPv6/Disconnected
Fixes #[HOSTEDCP-1001](https://issues.redhat.com/browse/HOSTEDCP-1001)
**Checklist**
=> HOSTEDCP-1001: Image registryOverride included in the image metadata extraction flow

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/daemonset.yaml
The "[sig-arch] Managed cluster should only include cluster daemonsets that have maxUnavailable or maxSurge update of 10 percent or maxUnavailable of 33 percent [Suite:openshift/conformance/parallel]" conformance test is failing.
The kubevirt-csi-node DaemonSet in the KubeVirt gueest cluster is with wrong configurations: spec.updateStrategy.rollingUpdate.maxUnavailable must not be > 10%, but was 1.
This PR set it to  %10.
Fixes [CNV-30260](https://issues.redhat.com/browse/CNV-30260)
**Checklist**
=> fix-CNV-30260: KubeVirt: fix failed conformance test

api/v1beta1/hostedcluster_types.go, cmd/cluster/core/create.go, cmd/cluster/core/create_test.go, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, support/supportedversion/version.go
This is a second attempt at this PR. The previous PR #2864 caused issues in CI due to one of our CI flows requiring client side release defaulting when release streams are specified.
This PR addresses this CI issue by still performing client-side defaulting when the `--release-stream` cli arg is present. This `--release-stream` cli arg is only exposed in the developer client tool `hypershift` and not the productized cli `hcp`.
---
Previously, the hostedCluster.Spec.Release.Image was required and the hcp or hypershift cli defaulted that value client side. This posed several issues though.
1. The defaulting did not take into consideration what the max and min version the deployed hypershift operator supports, which will eventually lead to the client defaulting unsupported versions.
2. This …
=> [HOSTEDCP-1041] Re-introducing defaulting webhook for self managed HCP

product-cli/cmd/cluster/cluster.go
Sets Arch to amd64 so the InstanceType is chosen through the HCP CLI. This is consistent with how the hypershift CLI sets Arch as well.
Fixes [HOSTEDCP-1022](https://issues.redhat.com/browse/HOSTEDCP-1022)
**Checklist**
=> HOSTEDCP-1022: Set Arch to amd64

control-plane-operator/main.go
In preparation for an e2e to verify proper ControlPlaneRelease function, I noticed that containers that use the self-referencing image lookup by the CPO were using an image ref different from that of the CPO itself.
This occurs when the `ControlPlaneRelease` image is set to a release image that shares an identical CPO image with the `Release` image.  In that case, the `imageID` still contains the `Release` reference to the image, since the sha256 is the same; only the registry path is different.
In order to verify that all HCP containers are using the `ControlPlaneRelease` image, we need all containers to reflect the expected registry path.
=> HOSTEDCP-1146: cpo: use CPO spec container image if it is a sha256 reference

api/v1beta1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Introduces an annotation to override the pod security admission label for hosted control plane namespaces.
This is a follow up to https://github.com/openshift/hypershift/pull/2778 where the default PSA is now changed to 'Restricted'. For some consumers like IBM, this label may be too restrictive for other workloads they may want to run in the control plane namespace.
**Checklist**
=> Allow overriding pod security admission label

test/e2e/chaos_test.go
Removes `TestEtcdChaos` since it is basically a subset of `TestHAEtcdChaos` and etcd will always be HA in prod.
Relieves some AWS CI account stress.
=> test: e2e: remove SingleReplica etcd chaos test

control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile_test.go
When an etcd member's data has been lost, the only recourse we currently have is to do a hacky manual recovery. With this change, it is as simple as deleting the bad member's pvc and pod to restore a member.
Automates the steps described in https://issues.redhat.com/browse/HOSTEDCP-1081
Fixes #[HOSTEDCP-1081](https://issues.redhat.com//browse/HOSTEDCP-1081)
**Checklist**
=> HOSTEDCP-1081: Perform etcd recovery when etcd member data is lost

api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/params_test.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, control-plane-operator/controllers/hostedcontrolplane/pki/params.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/haproxy.go, hypershift-operator/controllers/nodepool/haproxy_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, support/config/constants.go, support/util/networking.go, support/util/networking_test.go, support/util/util.go, support/util/util_test.go
- Now IPv6 and Dual Stack scenarios are covered in self-hosted environments.
- KAS PKI modified to include IPv4/6 addresses into the certificate
- Proxy still support only single stack scenarios, using the first ServiceCIDR as a AdvertiseAddress or InternalAPIAddress, but IPv4 and IPv6 could be used in any case (this is temporary meanwhile the Issue mentioned down bellow is open).
Fixes #[OCPBUGS-15331](https://issues.redhat.com/browse/OCPBUGS-15331)
Fixes #[OCPBUGS-16049](https://issues.redhat.com/browse/OCPBUGS-16049)
- https://github.com/kubernetes/enhancements/issues/2438 - This issue prevents the KAS to support dual stack and the `AdvertiseAddress` even being an slice, it only supports only one element (if more provided it will take the last one as …
=> OCPBUGS-15331,OCPBUGS-16049: Enable AdvertiseAddress dual stack and IPv6 support and added the changes to be included in the certificates

cmd/cluster/core/create.go
Validates the HostedCluster name meets RFC1123 in the HyperShift and HCP CLIs.
Fixes [OCPBUGS-16076](https://issues.redhat.com/browse/OCPBUGS-16076)
**Checklist**
=> OCPBUGS-16076: Validate HostedCluster name against RFC1123 in CLI

api/v1beta1/hostedcluster_types.go
Remove the immutable note from the HostedCluster.Spec.PullSecret. This field is mutable since 4.12.
Fixes [OCPBUGS-17680](https://issues.redhat.com/browse/OCPBUGS-17680)
**Checklist**
=> OCPBUGS-17680: Remove immutable note from PullSecret

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
`snapshot.storage.k8s.io` webhook was not detected because of this, although the service didn't have the label yet.
PR to add the label to the `csi-snapshot-webhook` service:
https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/155
Fixes #
**Checklist**
=> HOSTEDCP-1063: Account for guest webhook URLs without a port

cmd/install/assets/dashboard-template/monitoring-dashboard-template.json, cmd/install/assets/hypershift_operator.go, cmd/install/install.go, docs/content/how-to/per-hostedcluster-dashboard.md, docs/mkdocs.yml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/manifests.go, hypershift-operator/main.go
Adds an install option to enable monitoring dashboards for HostedClusters created by the HyperShift operator. Each dashboard consists of a ConfigMap that is placed in the openshift-config-managed namespace of the management cluster.
Fixes #[HOSTEDCP-1085](https://issues.redhat.com//browse/HOSTEDCP-1085)
**Checklist**
=> HOSTEDCP-1085: Create a monitoring dashboard per HostedCluster

docs/content/getting-started.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Validates the HostedCluster name meets RFC1123 in the HostedCluster controller.
Fixes [OCPBUGS-17669](https://issues.redhat.com/browse/OCPBUGS-17669)
**Checklist**
=> OCPBUGS-17669: Validate HostedCluster name against RFC1123

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
Last bit of cleanup after CNO replaced `ovnkube-master` in the HCP with `ovnkube-control-plane`
`CLI_IMAGE` is now only used in HCP components
https://github.com/search?q=repo%3Aopenshift%2Fcluster-network-operator%20%7B%7B.CLIImage%7D%7D&type=code
=> HOSTEDCP-1065: CNO deployed hosted-cluster-kubecfg-setup initContainers use CPR image

control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/assets/05_operator_role-hypershift.yaml
The [PR](https://github.com/openshift/cluster-csi-snapshot-controller-operator/pull/157) implements restarting `csi-snapshot-webhook` if the secret `csi-snapshot-webhook-secret` is updated. To do it, the operator needs to monitor for secret updates. This requires new perms in `05_operator_role-hypershift.yaml`. This PR simply syncs those changes to hypershift repo manifest.
/cc @openshift/storage 
**Checklist**
- [*] Subject and description added to both, commit and PR.
- [*] Relevant issues have been referenced.
=> STOR-1443: Sync `05_operator_role-hypershift.yaml` manifest from cluster-csi-snapsht-controller-operator

control-plane-operator/controllers/hostedcontrolplane/etcd/params.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go
The previous etcd health check uses an exec probe. Because we don't set a timeout, the timeout defafults to 1. This commit modifies the etcd statefulset to use a sidecar container with the cluster etcd operator image that implements an http get type of probe. It also modifies the timeouts to mirror those set in the standalone case.
Fixes #[OCPBUGS-17812](https://issues.redhat.com/browse/OCPBUGS-17812)
**Checklist**
=> OCPBUGS-17812: Update Etcd health check to mirror standalone etcd

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml, hypershift-operator/init.go, hypershift-operator/init_test.go, hypershift-operator/main.go, support/capabilities/management_cluster_capabilities.go
[HOSTEDCP-1000](https://issues.redhat.com/browse/HOSTEDCP-1000)
Adds the CA certificates for mirror registries specified by the user to the ocm-trusted-ca-bundle ConfigMap created in
https://github.com/openshift/hypershift/pull/2437 so that these certificates may be used to pull images from these mirror registries.
Users in disconnected environments will host their own image registry. The certificates from these registries are needed in order to pull from them.
Fixes #[HOSTEDCP-1000](https://issues.redhat.com//browse/HOSTEDCP-1000)
**Checklist**
=> HOSTEDCP-1000: Add user CA(s) to ocm-trusted-ca-bundle ConfigMap

api/v1alpha1/hostedcluster_types.go, api/v1beta1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, test/e2e/util/hypershift_framework.go
Whenever, the branch occurs and new release streams are created, we have to create a PR like[ this one](https://github.com/openshift/hypershift/pull/2927) to bump the supported version in the HO.
However, we can't merge such a PR until automatic fast-forward to the `release-4.14` branch stops, which means that we are blocking 4.15 release payload during this period of time.
The PR adds annotation to skip release image validation to use for our e2e flows.
=> TRT-1202: add annotation to skip release image validation

hypershift-operator/controllers/hostedcluster/ignitionserver/ignitionserver.go
**What this PR does / why we need it**: Fix ignition-server reconciliation for older control plane releases
Fixes #
**Checklist**
=> fix(ho): Restore match label selector behavior

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
Fixes the ignition-server-proxy part of https://issues.redhat.com/browse/OCPBUGS-16813
Allow `replicas` for the `ignition-server-proxy` Deployment to be controlled by the HC `ControllerAvailabilityPolicy`
=> OCPBUGS-16813: do not hardcode ignition-server-proxy replicas

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
The lookupDisconnectedRegistry function can return an empty string if the registry doesn't match a release repo. However, we don't handle that result in the calling code in ReconcileIgnitionServer. This commit adds handling for an empty string.
Fixes #OCPBUGS-17985
**Checklist**
=> OCPBUGS-17985: Handle empty mirrorImage result for ignition disconnected registry

control-plane-operator/controllers/hostedcontrolplane/ingress/router.go
Part 2/3 for https://issues.redhat.com/browse/OCPBUGS-17827 follow on to https://github.com/openshift/hypershift/pull/2928
=> OCPBUGS-17827: remove NeedManagementKASAccessLabel from router pods

test/e2e/chaos_test.go
Adds a test under the etcd chaos test to verify that we can recover from the destruction of a single member along with its data.
=> Add e2e test for etcd member recovery

test/e2e/e2e_test.go, test/e2e/util/hypershift_framework.go
=> TRT-1202: set SkipReleaseImageValidation annotation properly on e2e clusters

docs/content/getting-started.md, docs/content/how-to/automated-machine-management/nodepool-lifecycle.md
Nodes can become stuck if scaling down all NodePools for a cluster to zero if there are nodes that can't be drained successfully.
Adds documentation so users are aware of this issue and how to prevent it.
Fixes # [MGMT-15368](https://issues.redhat.com/browse/MGMT-15368)
**Checklist**
=> MGMT-15368: Document scaling down NodePools

cmd/infra/powervs/destroy.go
[MULTIARCH-3708](https://issues.redhat.com//browse/MULTIARCH-3708): PowerVS - Fix cluster deletion when existing resources passed
Fixes #
**Checklist**
=> MULTIARCH-3708: PowerVS - Fix cluster deletion when existing resources passed

test/e2e/util/util.go
Part 3/3 for https://issues.redhat.com/browse/OCPBUGS-17827
=> OCPBUGS-17827: e2e: remove private-router from NeedManagementKASAccessLabel allowlist

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Updated hosted cluster controller to stop using deprecated flags in error messages.
**Checklist**
=> Updating hostedcluster controller to stop using deprecated flags

product-cli/cmd/nodepool/create.go
Sets Arch to amd64 for HCP NodePool Create so the InstanceType is chosen through the HCP CLI.
Fixes [OCPBUGS-18024](https://issues.redhat.com/browse/OCPBUGS-18024)
**Checklist**
=> OCPBUGS-18024: Set Arch to amd64 for HCP NodePool Create

control-plane-operator/hostedclusterconfigoperator/controllers/resources/registry/registry.go
This allows the user to override with custom storage for image registry
Fixes #
**Checklist**
=> OCPBUGS-18072: Set emptyDir storage for the image registry only on initial time for None and Kubevirt platform

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
**What this PR does / why we need it**: Add hcp label to ignition-server `MatchLabels` by default to avoid upgrade restriction from `4.12.27+` to `4.13.7+`
https://redhat-internal.slack.com/archives/C01C8502FMM/p1692808565816429
Fixes #
**Checklist**
=> fix(ignition): Add HCP label to ignition-server by default

support/releaseinfo/registry_mirror_provider.go
Before this PR, if an ICSP was present in the mgmt cluster, we would end up using it to modify the cluster config operator image for the kube apiserver. This should not happen, since we should rely on the mgmt cluster's container runtime to do the substitution.
Fixes #[OCPBUGS-18308](https://issues.redhat.com/browse/OCPBUGS-18308)
**Checklist**
=> OCPBUGS-18308: Do not use mgmt cluster ICSP to mutate CCO image in KAS pod

control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go
https://issues.redhat.com/browse/OCPBUGS-18065
regression for 4.14 introduced by https://github.com/openshift/hypershift/pull/2271
=> OCPBUGS-18065: enable aws-pod-identity-webhook on AWS

api/v1beta1/hostedcluster_types.go
The existing label key that was used in ROSA was `api.openshift.com/limited-support`
Fixes [HOSTEDCP-1178](https://issues.redhat.com//browse/HOSTEDCP-1178)
=> HOSTEDCP-1178 fix limited support label key

api/v1beta1/hostedcluster_conditions.go, api/v1beta1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go
This patch basically adds a HostedCluster destroy grace period when there are cloud dangling objects that Hypershift cannot delete. It includes a default timeout, initially set to 0 seconds, and it should be increased depending of the deployment needs.
If the Time.Now() reaches the DeletionTimestamp + timeout (of that concrete object), the controller mark that object as ignored and it will continue with deprovisioning.
Cloud objects involved:
- ImageRegistryStorage
- IngressControllers
- LoadBalancers
- PersistentVolumes
When the cluster is marked as deleted but not finalized, a new condition is created "HostedClusterDestroyed". That condition will give extra time for OCM to grab the non deleted cloud dangling objects and send a notification to the final user. After that the finalizer is …
=> OCPBUGS-14611: Ignored cloud dangling objects after timeout on HC teardown

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
Ignition-server deployment doesn't configure the additionaltrustbundle configured by the user. This PR fixes that.
Fixes #OCPBUGS-16221
**Checklist**
=> OCPBUGS-16221: Adds trust bundle to ignition-server when configured in HC

cmd/cluster/aws/destroy.go, cmd/cluster/azure/destroy.go, cmd/cluster/kubevirt/create.go, cmd/cluster/none/destroy.go, cmd/nodepool/kubevirt/create.go, product-cli/cmd/cluster/aws/destroy.go, product-cli/cmd/cluster/kubevirt/create.go, product-cli/cmd/nodepool/kubevirt/create.go
Without this default, when issuing the `hypershift create nodepool kubevirt` command without specifying the `--root-volume-size` arg, the VMs' storage request is created with 0, which is not valid, and VMIs are not being created.
The default of 32Gi is taken from the hostedcluster default for the same:
https://github.com/openshift/hypershift/blob/7575b03733f056027cc1eed4565b7a8a5deaf7d9/cmd/cluster/kubevirt/create.go#L37
Fixes # [OCPBUGS-17517](https://issues.redhat.com/browse/OCPBUGS-17517)
**Checklist**
=> [OCPBUGS-17517] Add a default value (32Gi) for nodepool in `create nodepool kubevirt` command

hypershift-operator/controllers/nodepool/nodepool_controller.go, test/e2e/nodepool_test.go
Fixes #[HOSTEDCP-979](https://issues.redhat.com/browse/HOSTEDCP-979)
**Checklist**
=> HOSTEDCP-979: Re-enable nodepool in-place upgrade tests

docs/content/getting-started.md
Adds the enable-defaulting-webhook flag to the hypershift install and a note about the flag only being available for OCP versions greater than or equal to 4.14. 
Adds note to create cluster command that either the release-image or release-stream flag is needed when the enable-defaulting-webhook is not available.
Fixes [HOSTEDCP-1156](https://issues.redhat.com/browse/HOSTEDCP-1156)
**Checklist**
=> HOSTEDCP-1156: Add defaulting webhook to installation and notes

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, test/e2e/nodepool_rolling_upgrade_test.go, test/e2e/nodepool_test.go
Ensures a rolling upgrade is triggered, by creating a new machine template with a different name if any field under .spec.platfrom changes.
Fixes #[OCPBUGS-18127](https://issues.redhat.com/browse/OCPBUGS-18127)
**Checklist**
=> OCPBUGS-18127: Trigger a rolling upgrade on NodePool .spec.platfrom changes

konnectivity-socks5-proxy/main.go
When sending a numeric IPv6 address to the proxy in a CONNECT request, the address needs to be surrounded by brackets, otherwise the proxy sends back a Bad Request (400) result.
Fixes #
**Checklist**
=> OCPBUGS-18438: Properly format IPv6 address when proxying it through Konnectivity

test/e2e/nodepool_nto_machineconfig_test.go, test/e2e/nodepool_test.go, test/e2e/util/fixture.go
In order to restore the ability for devs to merge into the hypershift repo, I am disabling this test until https://issues.redhat.com/browse/OCPBUGS-18566 is resolved.
=> Disable nto inplace test for kubevirt

control-plane-operator/controllers/hostedcontrolplane/cloud/kubevirt/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go
The the kubevirt-csi and cloud-provider-kubevirt pods were not being pulled using the correct pull secret. This resulted in some odd behavior where the mgmt cluster could only deploy these components if the management cluster's global pull secret had access to the containers. Instead, we should be able to pull these components based on the HCP's pull secret.
=> Use the correct pull secret for HCP KubeVirt components

support/util/util.go
Currently, when serializing management cluster ICSP to environment variables, the order in which mirrors are listed in the original ICSP is lost because we sort all entries alphabetically. This change switches sorting to only the registry keys and preserves the ordering of the mirrors within that key.
Fixes #[OCPBUGS-18399](https://issues.redhat.com/browse/OCPBUGS-18399)
**Checklist**
=> OCPBUGS-18399: Preserve mirror order when serializing ICSP to env

api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kas/params_test.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/nodepool/haproxy.go, support/util/networking.go
With this change, existing HCs defaulting Networking.APIServer.Port to 443 will preserve current behaviour of overriding the kas endpoint in the guest cluster.
This is to avoid data plane rollouts that would result from changing the haproxy config.
New HCs wont default to 443 and they won't override the kas endpoint. Setting Networking.APIServer.Port to 443 by a consumer is still techincally possible but unrecommended.
Fixes #
**Checklist**
=> OCPBUGS-7840: Untangle kas port

api/fixtures/example.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, product-cli/cmd/cluster/cluster.go
This PR is to add `pausedUntil` create cluster option in `hcp` CLI to support MCE's cluster create/update Ansible automation template. https://issues.redhat.com/browse/ACM-1368 
MCE is integrated with Red Hat Ansible Automation Platform so that you can create prehook and posthook Ansible job instances that occur before or after creating or upgrading hive clusters. MCE should provide users same experience with hosted clusters. This requires an ability to pause cluster provisioning so that prehook job can be executed before cluster creation. MCE's cluster curator controller orchestrates this and clears the `spec.pausedUntil` from the HostedCluster and NodePools when the conditions are met.
**Which issue(s) this PR fixes** *(optional, use `fixes …
=> ACM-6435: add pausedUntil create cluster option in CLI

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
follow-up of https://github.com/openshift/hypershift/pull/2956 
Fixes #
**Checklist**
=> OCPBUGS-18127: Ensure machineTemplate name length respects RFC1123 spec

test/e2e/util/hypershift_framework.go
Currently we run all the `Ensure*` checks on the HostedCluster under test _before_ the `Main` part of the test runs.   We should do this after `Main`.
This is currently breaking 4.15 ci release stream because the `initial` release does not contain https://github.com/openshift/hypershift/pull/2934 but the e2e binary is built with https://github.com/openshift/hypershift/pull/2939
=> e2e: run Ensure functions after Main part of test

test/e2e/util/util.go
We are getting flakes with the CNO pod restarting due to https://github.com/openshift/cluster-network-operator/pull/1986
Because the fix is in the CNO and this is not an urgent bugfix, lets skip on our side until they can merge the fix.
cc @csrwng @enxebre
=> e2e: skip CNO pod restart check

api/v1beta1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go, control-plane-operator/controllers/hostedcontrolplane/olm/params.go, docs/content/how-to/disconnected/automatically-initialize-registry-overrides.md
Amend the image address used for the imageStreams
used for the OLM catalog source according to the value
of OpenShiftImageRegistryOverrides as genetically used
in the control plane operator in order to handle the disconnected use case.
This will implicitly assume that the images used for
the 4 default OLM catalogs got mirrored to the internal registry
using the original name and tag.
An annotation based escape mechanism is also defined:
the owner of the hostedcluster will be able to inject custom
addresses (only by digest) for the catalog images.
In that case the imageStream mechanism is completely skipped
and the catalog deployments are directly with the values
in the annotations.
It will be completely up to the user to manually refresh
them when …
=> HOSTEDCP-591: Amend OLM catalog IS according to OpenShiftImageRegistryOverrides

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver_test.go, konnectivity-socks5-proxy/main.go
Currently, we unconditionally use an image mapping from the management cluster if a mapping exists for ocp-release-dev or ocp/release. When the individual images do not use those registries, the wrong mapping is used.
This commit uses the individual images from the payload to look for any image mappings that may exist on the management cluster.
Fixes # [OCPBUGS-18568](https://issues.redhat.com/browse/OCPBUGS-18568)
**Checklist**
=> OCPBUGS-18568: Use MCO and CCO image references when looking up mappings

cmd/cluster/aws/create.go, cmd/cluster/core/create.go, cmd/infra/aws/create.go
When creating multi-zone hosted clusters, the --single-nat-gateway flag allows creating a single nat gateway instead of 3 and configures all cluster traffic to flow through that gateway. This is meant to be used in development and testing so that we can avoid spending on a nat gateway for every zone of a hosted cluster.
Fixes #[HOSTEDCP-1185](https://issues.redhat.com/browse/HOSTEDCP-1185)
**Checklist**
=> HOSTEDCP-1185: Add flag to create a single NAT gateway

docs/content/how-to/etcd-recovery.md
In the case of quorum loss, the etcd cluster needs to be restored from a snapshot. This commit documents the manual procedure.
Fixes #[HOSTEDCP-1075](https://issues.redhat.com//browse/HOSTEDCP-1075)
**Checklist**
=> HOSTEDCP-1075: Document instructions for recovering etcd cluster from lost quorum

test/e2e/autoscaling_test.go, test/e2e/chaos_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/nodepool_test.go, test/e2e/olm_test.go, test/e2e/util/hypershift_framework.go
currently the `Main` tests use a gomega var `g` created from the parent test contest `t` instead from the subtest.
On failure, this causes the error logs to be scrambled and the following error to show:
```
testing.go:1343: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
```
Fixes #
**Checklist**
=> e2e: fixed gomega created from parent test context

Makefile
The current hypershift operator cannot be run in FIPS enabled cluster because the binary is not FIPS compliant. In order to build FIPS compliant images, CGO_ENABLED needs to be set to 1. 
Fixes #
https://issues.redhat.com/browse/HYPBLD-99
**Checklist**
=> HYPBLD-99: enable CGO_ENABLED for building FIPS compliant images

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/nto/clusternodetuningoperator.go
This one fell through the cracks
https://issues.redhat.com/browse/OCPBUGS-18754
cc @csrwng
=> OCPBUGS-18754: tuned DS should not use controlPlaneReleaseImage

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
https://issues.redhat.com/browse/OCPBUGS-18762
=> OCPBUGS-18762: unset ControlPlaneReleaseImage on HCP when ControlPlaneRelease is unset on HC

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/network_policies.go, test/e2e/util/util.go
Even though the `router` does not have the KAS mgmt label, it can still access the KAS because the `private-router` NetworkPolicy allows it.
=> OCPBUGS-18907: add KAS endpoints to Except in router egress rule

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, support/globalconfig/authentication.go, support/globalconfig/cloudcreds.go
https://issues.redhat.com/browse/OCPBUGS-17906
We currently take the `AuthenticationSpec` in `spec.Configuration` in the HC.  The HO even copies ref'ed secrets/configmaps into the HCP namespace.  However, the HCCO does not reconcile the Authentication global config into the guest cluster.
This PR adds that reconcilation.
=> OCPBUGS-17906: reconcile Authentication global config

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, hypershift-operator/controllers/hostedcluster/network_policies.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, kubevirtexternalinfra/externalinfra.go, support/supportedversion/version.go, test/e2e/nodepool_kv_cache_image_test.go
This PR only impacts the hypershift-operator. We are doing some validation checks to ensure that we only allow creation of HCPs with supported guest, mgmt, and infra versions.
The minimum requirements are
* HCP payload >= v4.14.0
* KubeVirt >= v1.0.0 [CNV 4.14]
* Kubernetes >= v1.27.0 [OCP 4.14]
=> [CNV-31919] Validate KubeVirt platform required versioning

hypershift-operator/controllers/hostedcluster/network_policies.go
Removes the private-router network policy if OCP < 4.14 because it
prevents access to the ignition-server-proxy which doesn't have a
request-serving label in OCP < 4.14
Fixes #OCPBUGS-19014
**Checklist**
=> OCPBUGS-19014: Apply private-router network policy only if running OCP 4.14

Makefile
This is for backporting https://github.com/openshift/hypershift/pull/2997 into 4.14 branch.
The current hypershift operator cannot be run in FIPS enabled cluster because the binary is not FIPS compliant. In order to build FIPS compliant images, CGO_ENABLED needs to be set to 1. 
CGO_ENABLED=1 is necessary so that the Golang program can be compiled to use C libraries such as FIPS compliant crypto libraries on a build machine where those libraries are available.
Fixes #
https://issues.redhat.com/browse/HYPBLD-99
**Checklist**
=> enable CGO_ENABLED for building FIPS compliant images

cmd/cluster/aws/create.go, product-cli/cmd/cluster/aws/create.go, product-cli/cmd/cluster/cluster.go
Remove marking pull secret as required in hcp cli as you can just pass `--secret-creds` without passing the pull secret flag.
Fixes [ACM-7278](https://issues.redhat.com/browse/ACM-7278)
**Checklist**
=> ACM-7278: Remove marking pull secret as required in hcp cli

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, hypershift-operator/controllers/hostedcluster/network_policies.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, kubevirtexternalinfra/externalinfra.go, support/supportedversion/version.go, test/e2e/nodepool_kv_cache_image_test.go
This PR only impacts the hypershift-operator. We are doing some validation checks to ensure that we only allow creation of HCPs with supported guest, mgmt, and infra versions.
The minimum requirements are
HCP payload >= v4.14.0
KubeVirt >= v1.0.0 [CNV 4.14]
Kubernetes >= v1.27.0 [OCP 4.14]
=> [release-4.14] CNV-31919: Validate KubeVirt platform required versioning

docs/content/how-to/kubevirt/troubleshooting-kubevirt-cluster.md, docs/mkdocs.yml
The VM console logs are really useful to troubleshoot issues when the HyperShift/KubeVirt VM nodes are not correctly joining the cluster.
KubeVirt v1.1.0 will expose logs from the serial console of guest VMs in a k8s native way (`kubectl logs -n <namespace> <vmi_pod> -c guest-console-log`) but his is still not available with KubeVirt v1.0.0.
Document how to collect VM logs on the Kubevirt provider with an helper script while we wait to have
k8s standard log collection mechanism with Kubevirt v1.1.0.
Fixes https://issues.redhat.com/browse/CNV-32835
**Checklist**
=> KubeVirt: document VMs logs collection

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
This PR mostly reverts https://github.com/openshift/hypershift/pull/2914. The note added to the docs in that PR should remain. This PR removes the cluster name validation from the HostedCluster Controller (HCC). This is not needed in the HCC since the KAS will reject a HostedCluster CR with an invalid name automatically.
Fixes [OCPBUGS-17669](https://issues.redhat.com/browse/OCPBUGS-17669)
**Checklist**
=> OCPBUGS-17669: Remove cluster name validation from HCC

docs/content/how-to/kubevirt/create-kubevirt-cluster.md, docs/content/how-to/kubevirt/ingress-and-dns.md
Moving forward, the KubeVirt platform only supports OCP 4.14+ for the mgmt and guest cluster, as well as OpenShift Virt 4.14+ for hosting the VMs. This updates the docs to reflect that change.
=> Use example versions for KubeVirt platform that are supported

Containerfile.operator
To prevent the ubi8 image labels from being inherited, we must set our own.
Fixes [HOSTEDCP-1209](https://issues.redhat.com//browse/HOSTEDCP-1209)
**Checklist**
=> HOSTEDCP-1209: set ubi Containerfile labels

control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
Standalone `cluster-authentication-operator` sets the `accesstoken-inactivity-timeout` flag on the `openshift-oauth-apiserver` when `tokenConfig.accessTokenInactivityTimeout` is set in the global OAuth config.
We pass this to `oauth-openshift` via the config file but not to `openshift-oauth-apiserver` via its flag.  This results in OAuth tokens not expiring when expected.
=> OCPBUGS-13829: set accesstoken-inactivity-timeout flag to openshift-oauth-apiserver

control-plane-operator/controllers/hostedcontrolplane/kas/service.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
When using a route to expose the API server, the external port should be
443. This commit makes the change in the HyperShift operator, as well as the real fix in the control plane operator so that we can account for existing hosted control planes that report the wrong port.
Fixes #[OCPBUGS-19674](https://issues.redhat.com/browse/OCPBUGS-19674)
**Checklist**
=> OCPBUGS-19674: Report correct port when API exposed via route

api/v1beta1/hostedcluster_conditions.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/network/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/conditions/conditions.go, test/e2e/util/util.go
When using an hosted cluster based on a kubevirt provider, we recommend having a management cluster with MTU of 9000 bytes or grater in order for the hosted cluster to function properly. If a smaller sized MTU is used, a performance degragation is expected. We should bring visibility when this occurs, in terms of a new condition on the HostedCluster resource, e.g.:
```
- lastTransitionTime: "2023-09-08T12:18:14Z"
message: A suboptimal MTU size of 8900 has been detected. Due to performance,
we recommend setting an MTU of 9000 bytes or greater for the infra cluster
that hosts the KubeVirt VirtualMachines. When smaller MTUs are used, the cluster
will still operate, but network performance will be degraded due to fragmentation
of the double encapsulated ovn-k.
observedGeneration: 1
reason: …
```
=> [kubevirt platform] Detect Suboptimal MTU and raise HostedCluster Condition accordingly

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/controller.yaml, control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/daemonset.yaml
https://github.com/kubevirt/csi-driver/pull/93 updated the timeouts of the csi-provisioner and csi-attacher to be 3 minutes instead of 15 seconds to avoid the timeout happening while waiting for disk to hotplug.
This PR modifies the controller deployment and daemonset to match that PR
Fixes #
**Checklist**
=> Update kubevirt csi driver deployment with proper timeouts

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
Fixes OAuth template config in HostedCluter.configuration.ouath is not honored in HyperShift bug.
Fixes #
https://issues.redhat.com/browse/OCPBUGS-15215
**Checklist**
=> OCPBUGS-15215: OAuth template config in HostedCluter.configuration.ouath is not honored in HyperShift

test/e2e/e2e_test.go, test/e2e/util/fixture.go
Manual cherry-pick of #2902
Fixes #
**Checklist**
=> [release-4.12] MULTIARCH-3709: PowerVS - Add reuse resource flags to e2e test

Dockerfile, cmd/cluster/core/dump.go, fast.Dockerfile, go.mod, hack/tools/go.mod
Bump Golang to v1.20
Fixes [HOSTEDCP-1212](https://issues.redhat.com/browse/HOSTEDCP-1212)
**Checklist**
=> HOSTEDCP-1212: Bump Golang to v1.20

docs/content/how-to/aws/deploy-aws-private-clusters.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Without this perms the HO would always fail to describe and reject endpoints in the case they exist but the CPO can't remove them.
Fixes #
**Checklist**
=> Add private link perms to docs and clarify log message

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/manifests/cpo.go, control-plane-operator/hostedclusterconfigoperator/cmd.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/manifests.go, hypershift-operator/controllers/nodepool/haproxy.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/main.go, ignition-server/controllers/local_ignitionprovider.go, support/releaseinfo/fake/fake.go, support/releaseinfo/registry_image_content_policies.go, support/releaseinfo/releaseinfo.go, support/util/deployment.go, support/util/fakeimagemetadataprovider/fakeimagemetadataprovider.go, support/util/imagemetadata.go, support/util/imagemetadata_test.go
This PR contains the work needed to support HCP in a disconnected environment. The majority of the work in this PR is to determine image metadata in a disconnected environment, include user-ca bundles in appropriate HCP pods, and fixing the ignition server to support extracting image files in disconnected environments.
[OCPBUGS-11939](https://github.com/openshift/hypershift/pull/2950/commits/160d7a9055cdfc291e699872520b79b6ea8a1a48) - Get the image metadata from any ICSP/IDMS in a management cluster allowing a hosted cluster to be created in a disconnected environment with image mirror registry data from the ICSP/IDMS.
[OCPBUGS-18128](https://github.com/openshift/hypershift/pull/2950/commits/41cdd9fbc06e87b212fcf6c63c602526656936a2)  - Automatically …
=> OCPBUGS-11939, OCPBUGS-18128, OCPBUGS-18460 , OCPBUGS-18602, OCPBUGS-18879: Support Disconnected HCP

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
This change adds reconciliation for openshift-apiserver and openshift-oauth-apiserver when the audit configuration is changed.
First patch: https://github.com/openshift/hypershift/pull/2945
Fixes: #OCPBUGS-13348
Fixes #
**Checklist**
=> OCPBUGS-13348: Hypershift Audit configuration not working (part2).

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
[OCPBUGS-19746](https://github.com/openshift/hypershift/pull/3047/commits/773aa1b71af559a16b7f3bc4fa80dac40ff4f4d2) - Added network validations for AdvertiseAddress
- Implemented a validation mechanism for the AdvertiseAddress, which verifies its absence of overlap with the presently defined networks.
When the AdvertiseAddress is explicitly specified by the user, it will be utilised for the validation. In cases where it is not explicitly defined, the controller will automatically employ the default definitions, contingent upon the primary network stack.
Furthermore, this commit encompasses the inclusion of unit tests for the 'validateSliceNetworkCIDRs' function.
[OCPBUGS-16189](https://github.com/openshift/hypershift/pull/3047/commits/c5427639656a844c0d219a95b7dc6f5d6ce62ca6) - …
=> OCPBUGS-19746, OCPBUGS-16189: Added network validations

control-plane-operator/controllers/hostedcontrolplane/kas/config.go
Set hosted cluster KAS config pod security enforcement to privileged.
Fixes [OCPBUGS-20249](https://issues.redhat.com/browse/OCPBUGS-20249)
**Checklist**
=> OCPBUGS-20249: Set KAS config pod security Enforce to privileged

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go
Starting from v1.5, CAPI uses a cached client to retrieve the kubeconfig secret. However, only secrets with the clusterName label `cluster.x-k8s.io/cluster-name` are cached, see:
https://github.com/kubernetes-sigs/cluster-api/pull/8940/files#diff-8bdee7925f4d1adc50383754391472636156a2a857a7c76290f6073c8d83f5cdR216
This PR ensures we can consume CAPI v1.5+,  by adding the required label to the kubeconfig secret generated for CAPI.
Fixes #[HOSTEDCP-1232](https://issues.redhat.com/browse/HOSTEDCP-1232)
**Checklist**
=> HOSTEDCP-1232: Add clusterName label to CAPI kubeconfig secret

cmd/cluster/aws/destroy.go, cmd/cluster/core/destroy.go, cmd/infra/aws/destroy.go, product-cli/cmd/cluster/aws/destroy.go
Adds InfraGracePeriod timeout flag for deleting AWS infrastructure resources so that if something goes wrong with deleting the infrastructure resources, the deletion process is not stuck.
Fixes #
[HOSTEDCP-1051](https://issues.redhat.com/browse/HOSTEDCP-1051)
**Checklist**
=> HOSTEDCP-1051 addition of grace period for aws infra destruction

docs/content/how-to/kubevirt/ingress-and-dns.md
documents that port only HTTPS over port 443 is supported with default ingress for kubevirt platform.
=> CNV-31891: Document port 80 is not supported with default ingress for KubeVirt

test/e2e/util/util.go
Reverts openshift/hypershift#2881
IC upgrades were a one time thing, reverting this back to original values in 4.15/main branch.
=> SDN-4062: Revert "SDN-4042: Increase upgrade rollout timers"

Makefile, cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml
Change the hypershift operator pod anti-affinity rule from `required` to `preferred` while keeping the default replica at 2 so that the hypershift operator can be installed on SNO and can be upgraded (rolling update) on 2-node OCP cluster.
https://issues.redhat.com/browse/OCPBUGS-18341
**Checklist**
=> OCPBUGS-18341: change required pod anti-affinity rule to preferred rule

api/v1beta1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
PR connected to issue: https://github.com/openshift/hypershift/issues/2679
=> Disabling unused monitoring services

test/e2e/util/util.go
Removes EnsurePSANotPrivileged test since enforce was reverted back to privilege through https://github.com/openshift/hypershift/pull/3083.
Fixes [OCPBUGS-21869](https://issues.redhat.com/browse/OCPBUGS-21869)
**Checklist**
=> OCPBUGS-21869: Remove EnsurePSANotPrivileged

control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas_test.go
In order to make URLs understables by kubectl and oc clients, if the server is set as a plane IPv6 it should be surrounded by brackets (e.g https://[fd02::1]:6443)
Fixes #[OCPBUGS-20246](https://issues.redhat.com/browse/OCPBUGS-20246)
**Checklist**
=> OCPBUGS-20246: Added brackets to the kubeconfig server address when IPv6

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/config.go
Add `OpenShiftPodSecurityAdmission=false` featureGate to ClusterPolicyController, to disable setting `pod-security.kubernetes.io/enforce` label on namespace in the guest cluster.
Fixes #[OCPBUGS-20526](https://issues.redhat.com/browse/OCPBUGS-20526)
**Checklist**
=> OCPBUGS-20526: Align PSA labels on guest cluster namespaces with standalone OCP

api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, hack/app-sre/saas_template.yaml
Validates that accessTokenInactivityTimeout >= 300s, similar to Standalone https://github.com/openshift/kubernetes/blob/c0449761f4ad0c3a585990c26aea90a1dadb82cb/openshift-kube-apiserver/admission/customresourcevalidation/oauth/validate_idp.go#L75C1-L81
Fixes #[OCPBUGS-21626](https://issues.redhat.com/browse/OCPBUGS-21626)
**Checklist**
=> OCPBUGS-21626: Validate accessTokenInactivityTimeout >= 300s

control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/rbac.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
PriviligedNamespacesPSALabelSyncer RBAC added in https://github.com/openshift/cluster-kube-controller-manager-operator/pull/743
Fixes #[OCPBUGS-21776](https://issues.redhat.com/browse/OCPBUGS-21776)
**Checklist**
=> OCPBUGS-21776: Cluster-policy-controller: add missing RBAC for privileged namespaces PSA syncer controller

test/e2e/create_cluster_test.go, test/e2e/util/util.go
presub e2e on `main` is blocked on this because the upgrade test does a y-stream upgrade and deploys 4.14 where this check is currently run, and fails, before the upgrade.
xref https://github.com/openshift/hypershift/pull/3107
=> run EnsurePSANotPrivileged for TestCreateCluster only

test/e2e/util/util.go
Remove pod exceptions from EnsureNoCrashingPods that were either fixed or cant be reproduced.
Fixes # [HOSTEDCP-1200](https://issues.redhat.com/browse/HOSTEDCP-1200)
**Checklist**
=> HOSTEDCP-1200: Remove pod exceptions from EnsureNoCrashingPods

control-plane-operator/controllers/hostedcontrolplane/cloud/azure/manifests.go, control-plane-operator/controllers/hostedcontrolplane/cloud/azure/params.go, control-plane-operator/controllers/hostedcontrolplane/cloud/azure/providerconfig.go, control-plane-operator/controllers/hostedcontrolplane/cloud/azure/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/manifests/azure.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/cloudcontrollermanager/azure/cloud_node_manager.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Updates the cloud manager to reconcile Azure
Fixes [HOSTEDCP-1229](https://issues.redhat.com/browse/HOSTEDCP-1229)
**Checklist**
=> HOSTEDCP-1229: Move azure cloud provider to out of tree

api/v1beta1/nodepool_conditions.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
Improves the UX around notifying a user the CPU arch cannot be changed from the default amd64 unless changing the NodePool CPU arch is supported for the platform.
Fixes [HOSTEDCP-1113](https://issues.redhat.com/browse/HOSTEDCP-1113)
**Checklist**
=> HOSTEDCP-1113: Improve NodePool CPU arch & platform check

test/e2e/util/util.go
`ingress-operator` still restarts because it can't find the `Route` type in the first two minutes of running.  Re-adding that check that was removed in https://github.com/openshift/hypershift/pull/3138
OLM introduced new function that restarts the pod on purpose
https://github.com/openshift/operator-framework-olm/commit/1cf358424a0cbe353428eab9a16051c6cabbd002
Adding a new skip for OLM
=> tests: e2e: exempt ingress, OLM and catalog from pod restart check

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/olm/olm-collect-profiles.go, docs/content/contribute/run-tests.md, test/e2e/util/hypershift_framework.go, test/e2e/util/util.go
Adds e2e to check that we don't regress our affinity opinions
Fixes # [HOSTEDCP-1050](https://issues.redhat.com/browse/HOSTEDCP-1050)
**Checklist**
=> HOSTEDCP-1050: Add e2e to check we dont regress affinity opinions

cmd/install/assets/hypershift_operator.go, cmd/install/install.go, go.mod, go.sum, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go, hypershift-operator/main.go, kubevirtexternalinfra/externalinfra.go, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/errgroup/errgroup.go, vendor/golang.org/x/sync/errgroup/go120.go, vendor/golang.org/x/sync/errgroup/pre_go120.go, vendor/modules.txt
Add validating webhook for HostedClusters and NodePools, to check if kubevirt external infra cluster is with sufficient CNV and K8s versions.
This is already checked on the operator, but adding this logic to the webhook will prevent the creating of resources in insufficient environment, in advance. Fixing this error is not an easy task and require upgrading the infra cluster, or the CNV installation, and we prefer to fail fast in this case.
Fixes #[CNV-34094](https://issues.redhat.com//browse/CNV-34094)
**Checklist**
=> CNV-34094: Add validating webhook

api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, hack/app-sre/saas_template.yaml
https://github.com/openshift/hypershift/pull/3110 made `accessTokenInactivityTimeout` field required accidentally, this fixes that.
Fixes #[OCPBUGS-21626](https://issues.redhat.com/browse/OCPBUGS-21626)
**Checklist**
=> OCPBUGS-22868: Fixed accessTokenInactivityTimeout validation

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Fixes: OCPBUGS-16079
Ensure that the nodeport IP for the API Server does not conflict with the Service Network CIDR.
Fixes #
**Checklist**
=> OCPBUGS-16079: No error for overlapping service network and API IP

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go
We want to remove the unncessary exposure of port 6443 externally, as this increases the used SG rules, which decreases our max number of HC per management aws account #3139 We split the PR to roll out the HO first to all envs to make sure the haproxy in dataplane for newly created HCs don't point to a port 6443 that won't be exposed.
Fixes #
**Checklist**
=> OCPBUGS-20161: Stop exposing kas on 6443 private route service load balancer

api/v1beta1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hack/app-sre/saas_template.yaml
Update regex validation for nodepool.spec.taints.value. Previous validation wasnt actually validating the following case
-  `must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345'`
Fixes # [OCPBUGS-10423](https://issues.redhat.com/browse/OCPBUGS-10423)
**Checklist**
=> OCPBUGS-10423: Update regex validation for nodepool.spec.taints.value

api/fixtures/example.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, product-cli/cmd/cluster/cluster.go, test/e2e/e2e_test.go
Adjustment cluster-cidr,service-cidr to support dual-stack
[HOSTEDCP-1278](https://issues.redhat.com/browse/HOSTEDCP-1278)
**test** 
```
➜  hcp create cluster aws --base-domain qe.devcluster.openshift.com --aws-creds config/awscredentials  --pull-secret config/.dockerconfigjson
➜  oc get hostedcluster -n clusters example -ojsonpath='{.spec.networking}'     
{"clusterNetwork":[{"cidr":"10.132.0.0/14"}],"machineNetwork":[{"cidr":"10.0.0.0/16"}],"networkType":"OVNKubernetes","serviceNetwork":[{"cidr":"172.31.0.0/16"}]} 
➜  hcp create cluster aws --base-domain qe.devcluster.openshift.com --aws-creds config/awscredentials  \
--pull-secret config/.dockerconfigjson --name testv6 \
--cluster-cidr fd03::/48 --service-cidr …
```
=> HOSTEDCP-1278: Adjustment cluster-cidr,service-cidr to support dualstack

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
To allow creating of KubeVirt hosted cluster using the hosted cluster API (rather than using the cli).
When creating the hosted cluster using the cli, the cli also creates the secret. But when creating the hosted cluster using the hosted cluster API, the secret is not created.
This PR changes hypershift so it now creates the etcd encryption key secret, if it is not already exist.
Fixes #[CNV-33847](https://issues.redhat.com//browse/CNV-33847)
**Checklist**
=> CNV-33847: KubeVirt: create the etcd encryption key secret, if missing

api/fixtures/example.go
When creating a HostedCluster from command line, the HostedCluster CR is one of the first resources that been created. Some resources are created later but are actually needed.
The new validating webhook need the secret that holds the kubeconfig of the infra-cluster (when creating a a cluster with an external KubeVirt infra cluster). The webhook is called for HostedCluster cration, while the secret is not created yet, and so the creation of the HostedCluster fails.
This PR changes the order of the resources when creatig a new cluster, so all the dependencies are created before the HostedCluster CR.
Fixes #[HOSTEDCP-1281](https://issues.redhat.com//browse/HOSTEDCP-1281)
=> HOSTEDCP-1281: Fix a bug in the validating webhook

control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go
Add "--strict-transport-security-directives" for kube-apiserver.
OCP has enabled HSTS in kube-apiserver since OCP 4.12: https://github.com/openshift/cluster-kube-apiserver-operator/blob/release-4.12/bindata/assets/config/defaultconfig.yaml
IBM Cloud uses only "max-age=31536000".
Fixes #
**Checklist**
=> OCPBUGS-23015: Configure HSTS for kube-apiserver

hack/ci-test-e2e.sh, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/util/requestserving.go, test/e2e/util/util.go
supersedes [github.com/openshift/hypershift/pull/3104](https://github.com/openshift/hypershift/pull/3104)
Fixes # [HOSTEDCP-1206](https://issues.redhat.com/browse/HOSTEDCP-1206)
**Checklist**
=> HOSTEDCP-1206: Req serving isolation e2e enxebre

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
Allow the cluster network operator to create network-node-identity deployment in Calico environment
Fixes https://issues.redhat.com/browse/OCPBUGS-23083
**Checklist**
=> OCPBUGS-23083: adding permission to CNO RBAC Calico path for network-node-identity deploy

api/v1beta1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/metrics/metrics.go, hypershift-operator/controllers/hostedcluster/metrics/metrics_test.go, hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/metrics/metrics.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/main.go, hypershift-operator/metrics.go, test/e2e/util/hypershift_framework.go, test/e2e/util/util.go
[`hostedcluster`](hypershift-operator/controllers/hostedcluster/metrics/metrics.go) and [`nodepool`](hypershift-operator/controllers/nodepool/metrics/metrics.go) time series keep being defined long after the `hostedcluster` or `nodepool` is gone.
This is problematic because:
1. We plan to add a new `hostedcluster` metric which will "count" the number of worker cores and which will be used to bill the customers (see `OSD-19085`).  
This metric must stop to be defined as soon as the cluster is gone or we will continue to bill the customer for a cluster which is gone.
2. This is misleading.
3. This is kind of a leak; time series were defined forever... unless the hypershift operator was restarting which was not coherent at all.
4. Alerts based on …
=> OCPBUGS-20179: Stop defining time series for hosted clusters or node pools which do not exist anymore.

api/hypershift/v1beta1/hostedcluster_types.go, go.mod, hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, test/e2e/nodepool_kv_cache_image_test.go, test/e2e/nodepool_kv_jsonpatch_test.go, test/e2e/nodepool_test.go
Suport the new HostedCluster/NodePool annotation
"hypershift.openshift.io/kubevirt-vm-jsonpatch", to modify the KubeVirt VM template using jsonpatch string.
Fixes #
**Checklist**
=> CNV-23418: unsupported escape hatch mechanism custom HS/KV vms

Containerfile.operator
Bump Golang builder to 1.20 for RHTAP dockerfile
Fixes [HOSTEDCP-1306](https://issues.redhat.com/browse/HOSTEDCP-1306)
**Checklist**
=> HOSTEDCP-1306: Bump Golang builder to 1.20 for RHTAP dockerfile

cmd/infra/aws/ec2.go
The value of the kubernetes.io/role/elb and
kubernetes.io/role/internal-elb tag should be '1' and not 'true'. Ref:
https://github.com/openshift/aws-load-balancer-operator/blob/main/docs/prerequisites.md#subnets
Fixes #OCPBUGS-22912
**Checklist**
=> OCPBUGS-22912: Set value of elb tag to 1 instead of true

cmd/cluster/core/dump.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent_test.go, hypershift-operator/controllers/hostedcluster/network_policies.go, hypershift-operator/controllers/manifests/manifests.go, hypershift-operator/controllers/nodepool/metrics/metrics.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, test/e2e/chaos_test.go, test/e2e/nodepool_kv_cache_image_test.go, test/e2e/nodepool_kv_jsonpatch_test.go, test/e2e/nodepool_kv_qos_guaranteed_test.go, test/e2e/nodepool_rolling_upgrade_test.go, test/e2e/olm_test.go, test/e2e/util/hypershift_framework.go, test/e2e/util/oauth.go, test/e2e/util/util.go
32 out of 38 calls to `HostedControlPlaneNamespace` are only to get the
controlPlane namespace name. These cases are actually creating a namespace object only to take its `Name` field.
This PR renames the `HostedControlPlaneNamespace` function, to `HostedControlPlaneNamespaceObject`, and add a new   `HostedControlPlaneNamespace` function to only return the namespace name. Then use this new function anywhere we only want the namespace name, to simplify the code by avoiding the creation of the namespace object just to then take the `Name` field.
=> HOSTEDCP-1305: Simplify HostedControlPlaneNamespace().Name

hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt_test.go, test/e2e/nodepool_kv_jsonpatch_test.go
The Virtual Machine Instance (VMI) template is one field in the Virtual Machine (VM) template.
The current implementation only patch the VMI template, instead of the whole VM template.
This PR fixes the wrong implementation and allow modifiying the VM template.
Fixes #[CNV-23418](https://issues.redhat.com//browse/CNV-23418)
**Checklist**
=> CNV-23418: fix the jsonpath annotation implemetation

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/controlplaneoperator/manifests.go, support/util/oauth.go
https://issues.redhat.com/browse/HOSTEDCP-1254
WIP:
:heavy_check_mark: Needs to be able to handle Authentication type `OIDC` but no `OIDCProviders`
=> HOSTEDCP-1254: disable deployment of integrated oauth when authentication type is OIDC and set KAS flags

api/v1beta1/hostedcluster_types.go, go.mod, hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go, hypershift-operator/controllers/nodepool/kubevirt/kubevirt_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, test/e2e/nodepool_kv_cache_image_test.go, test/e2e/nodepool_kv_jsonpatch_test.go, test/e2e/nodepool_test.go
This is a backport of #3187 and #3201 
We need this escape hatch mechanism in order to grant support exceptions for users who need to modify the KubeVirt VMs outside the bounds of what the NodePool api can express.
=> "[release-4.14] CNV-35326: unsupported escape hatch mechanism custom HS/KV vms"

api/hypershift/v1beta1/nodepool_conditions.go, cmd/install/assets/hypershift_operator.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
* validate the jsonpatch annotation in webhook. Make sure the jsonpatch string is a valid standard jsonpatch
* If the creation of a kubevirt machine template fails, add a new condition to the node pool to reflect this error.
Fixes #[CNV-23418](https://issues.redhat.com//browse/CNV-23418)
=> CNV-23418: Validate jsonpatch annotation + add condition on wrong patch

cmd/cluster/azure/create.go, cmd/infra/azure/create.go, support/releaseinfo/deserialize_test.go, support/releaseinfo/releaseinfo.go
Retrieves the RHCOS VHD image from release image rather than hardcoding it
Fixes [HOSTEDCP-1237](https://issues.redhat.com/browse/HOSTEDCP-1237)
**Checklist**
=> HOSTEDCP-1237: Retrieve RHCOS VHD image from release image

api/hypershift/v1beta1/hosted_controlplane.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, hack/app-sre/saas_template.yaml
Clients using PATCH or SSA require fields to be properly annotated when they are maps-as-lists, in the Kubernetes convention. These annotations allow individual clients to update and have opinions on only a subset of the list, rather than all of it at once.
=> HOSTEDCP-1256: api/v1beta1: annotate hostedcontrolplane conditions

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
https://issues.redhat.com/browse/OCPBUGS-23472
https://github.com/openshift/hypershift/pull/2778 broke y-stream upgrade 4.13 -> 4.14 because `ignition-server-proxy` deployment was configured with a ServiceAccount but then removed in 4.14.  However, we didn't explicitly unset it in the reconciliation so a deployment created in 4.13 will retain the removed ServiceAccount when upgraded to 4.14.
=> OCPBUGS-23472: unset ServiceAccount on ignition-server-proxy

control-plane-operator/controllers/hostedcontrolplane/machineapprover/reconcile.go
https://github.com/openshift/cluster-machine-approver/pull/211 is changing the metrics endpoint to listen only on localhost so these probes will not work
=> OCPBUGS-23737: remove machine-approver probes

control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas_test.go
In there first approach [here](https://github.com/openshift/hypershift/pull/3117) I've missed the situation where the URLs passed to the function contains already the port.
Fixes #[OCPBUGS-20246](https://issues.redhat.com/browse/OCPBUGS-20246)
=> OCPBUGS-20246: Added brackets to IPv6 KAS address on kubeconfig

hypershift-operator/controllers/nodepool/metrics/metrics.go, hypershift-operator/controllers/nodepool/metrics/metrics_test.go, hypershift-operator/main.go
This info will be needed to properly bill the customer; indeed customers are billed on a per core basis.
Remark that this PR contains https://github.com/openshift/hypershift/pull/2671 as we need to make sure that the metric get undefined when the hosted cluster is deleted (see [this comment](https://github.com/openshift/hypershift/pull/3089#discussion_r1356949749))
**Because of this inclusion, please only review the last commit of this PR.**
Closes [OSD-19085](https://issues.redhat.com//browse/OSD-19085)
**Checklist**
=> OSD-19085: New hypershift_cluster_cores metric giving the total number of worker cores

api/fixtures/example.go, api/hypershift/v1beta1/hostedcluster_types.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, docs/content/how-to/disconnected/known-issues.md, docs/mkdocs.yml, product-cli/cmd/cluster/cluster.go
This PR adds the OLMCatalogPlacement capability to be set from the CLI.
Fixes #[OCPBUGS-22473](https://issues.redhat.com/browse/OCPBUGS-22473)
=> OCPBUGS-22473: Added OLMCatalogPlacement option to the CLI

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
**What this PR does / why we need it**:  
-  Adds a watch for HCP pullsecret  to HCCO
Fixes # [OCPBUGS-19834](https://issues.redhat.com/browse/OCPBUGS-19834)
**Checklist**
=> OCPBUGS-19834: add watch for HCP pullsecret to HCCO

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/cno.go
With network-node-identity in the CP side for 4.14, it does not cycle when the HC/HCP restart annotation is applied. This change makes it so that CPO will set the restart annotation. Similar to https://github.com/openshift/hypershift/pull/2150.
Fixes #376
**Checklist**
=> OCPBUGS-24062: fix(cpo): Set restart annotation on network-node-identity

test/e2e/create_cluster_test.go, test/e2e/nodepool_test.go, test/e2e/util/requestserving.go, test/e2e/util/util.go
**What this PR does / why we need it**: Adds e2e to ensure pods dont land in default nodepool
Supports # [OCPBUGS-20157](https://issues.redhat.com/browse/OCPBUGS-20157)
**Checklist**
=> OCPBUGS-20157: add e2e to ensure pods dont land in default pool

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
**What this PR does / why we need it**: This allows the rest of the KAS pod to clean up before dropping network connections, resulting in fewer interruptions on restarts.
Fixes # https://issues.redhat.com/browse/OCPBUGS-22459
**Checklist**
=> OCPBUGS-22459: Add prestop to konnectiviy server

test/e2e/nodepool_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/util/hypershift_framework.go, test/e2e/util/util.go
Now that we have branched out to 4.15, we have a previous release that contains a kubevirt RHCOS image, thus we can test the node pool upgrade flow.
fixes #[CNV-29003]( https://issues.redhat.com/browse/CNV-29003)
**Checklist**
=> CNV-29003: Re-enable NodePoolUpgradeTest for KubeVirt (Replace Only)

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/kcm/service.go, control-plane-operator/controllers/hostedcontrolplane/oauth/service.go, control-plane-operator/controllers/hostedcontrolplane/ocm/service.go, control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/routecm/service.go
This is a manual backport from https://github.com/openshift/hypershift/pull/3210 
Added IPFamilyPolicy to HostedCluster exposed services with the default setting of PreferDualStack. This means that services exposed in the HCP namespace will use dual-stack if the MGMT Cluster is configured as such. If the MGMT cluster is set to Single Stack, HCP will expose the services accordingly.
**Which issue(s) this PR fixes** : 
Backport Bug #[OCPBUGS-23569](https://issues.redhat.com/browse/OCPBUGS-23569)
Fixes#[OCPBUGS-23350](https://issues.redhat.com/browse/OCPBUGS-23350)
=> OCPBUGS-23569: Added IPFamilyPolicy to services exposed at the HCP in DualStack mode

api/fixtures/example.go, cmd/cluster/cluster.go, product-cli/cmd/cluster/cluster.go, product-cli/cmd/nodepool/create.go
The NodeUpgradeType option by default is set in all the cases from the CLI to `Replace`. This PR changes that and set the option by provider.
- AWS: `Replace`
- Azure: `Replace`
- PowerVS: `Replace`
- None: `InPlace`
- Kubevirt: `Replace`
- Agent: `InPlace`
Fixes #[HOSTEDCP-1322](https://issues.redhat.com/browse/HOSTEDCP-1322)
=> HOSTEDCP-1322: NodeUpgradeType defaulted by provider via CLI

api/fixtures/example.go, api/hypershift/v1alpha1/hostedcluster_types.go, api/hypershift/v1alpha1/nodepool_types.go, api/hypershift/v1beta1/hostedcluster_types.go, api/hypershift/v1beta1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go
This PR is part of an effort to improve the overall API defaulting for the HostedCluster and NodePool objects. The goal to begin transitioning defaulting logic that currently lives within the client tooling (hypershift/hcp) and make these same defaults function when someone is using the API directly.
This PR contains the following generic changes
- HostedCluster Network CRD defaults
- NodePool  NodePoolManagement, UpgradeType, and AutoRepair CRD defaults
and the following kubevirt platform specific changes
- NodePool KubeVirt platform CRD defaults
- NodePool mutating webhook initializes kubevirt platform spec when Kubevirt platform is in use in order for CRD defaults to be applied
- HostedCluster mutating webhook initializes some dynamic kubevirt values related to the …
=> CNV-35774: Improve CRD defaulting for HostedCluster and NodePool

api/fixtures/example.go, cmd/cluster/core/create.go, cmd/cluster/core/destroy.go, cmd/cluster/none/destroy.go, cmd/util/client.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
A user destroying a HostedCluster can cause the HostedCluster to hang indefinitely if the destroy command times out during execution.
This is due to the hcp cli placing a finalizer on the HostedCluster during deletion which the cli tool later removes after waiting for some clean up actions to occur. If a user cancels the `hcp destroy cluster` command (or the command times out) while the cli is waiting for cleanup, then the HostedCluster will hang indefinitely with a DeletionTimestamp != nil.
This PR only performs the additional cleaning logic, including the setting and removing the special finalizer, for platform that actually creates additional resources. Also, this PR sets the hostedCluster as the owner for these secrets, so they will be deleted with the HostedCluster.
Fixes …
=> OCPBUGS-23126: Fix a bug on deletion of a hostedcluster

cmd/install/assets/hypershift_operator.go, cmd/install/install.go, control-plane-operator/controllers/hostedcontrolplane/cvo/params.go, control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/cvo.go, control-plane-operator/main.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/network_policies.go, hypershift-operator/controllers/manifests/networkpolicy/manifests.go, hypershift-operator/main.go, support/config/constants.go
This pull request will enable the hosted Cluster Version Operator (CVO) to evaluate conditional updates on self-managed HyperShift deployed on an OpenShift management cluster.
Implements #[OTA-855](https://issues.redhat.com/browse/OTA-855)
**Checklist**
=> OTA-855: Enable CVO to evaluate conditional updates on self-managed HyperShift deployed on OpenShift

cmd/cluster/cluster.go, cmd/cluster/core/create.go, product-cli/cmd/cluster/cluster.go, support/globalconfig/network.go
This feature is only supported for now in Agent provider.
Fixes #[HOSTEDCP-1272](https://issues.redhat.com/browse/HOSTEDCP-1272)
=> HOSTEDCP-1272: Added CLI support to create DualStack clusters using default values

api/fixtures/example.go, api/hypershift/v1alpha1/hostedcluster_types.go, api/hypershift/v1alpha1/zz_generated.deepcopy.go, api/hypershift/v1beta1/hostedcluster_types.go, api/hypershift/v1beta1/zz_generated.deepcopy.go, client/applyconfiguration/hypershift/v1alpha1/clusterconfiguration.go, client/applyconfiguration/hypershift/v1beta1/clusterconfiguration.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/olm/deployments.go, control-plane-operator/controllers/hostedcontrolplane/olm/services.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/olm.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, product-cli/cmd/cluster/cluster.go
The pull request (PR) embeds the OperatorHubSpec field into the `hostedcluster.Spec.Configuration` API field. This allows us to disable/enable default sources in Management or Guest placement only during creation.
This functionality is also incorporated into the CLIs through a flag called `olmDisableDefaultSources`.
However, it's important to note that the OperatorHub capability to disable/enable individual default sources is not covered in this PR. As a result, that field will be disregarded in the CPO and HCCO reconciliation.
Fixes #[HOSTEDCP-1273](https://issues.redhat.com/browse/HOSTEDCP-1273)
=> HOSTEDCP-1273: Added support for OLM Disable default sources on HC creation

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml
This PR is to guarantee that all pods running within the ACM (Advanced Cluster Management) cluster adhere to Kubernetes Security Context Constraints (SCC) to ensure that containers run with the 'readonlyrootfilesystem' and 'privileged' settings, in order to enhance the security and functionality.
Fixes # https://issues.redhat.com/browse/ACM-8466
**Checklist**
=> ACM-8466: Add Kubernetes SCC V2 options to HO containers

control-plane-operator/controllers/hostedcontrolplane/kas/config.go
Kubernetes v1.29 no longer includes the flowcontrol v1alpha1 API. The argument referencing it in the cpo should be removed.
Fixes #[OCPBUGS-25103](https://issues.redhat.com/browse/OCPBUGS-25103)
**Checklist**
=> OCPBUGS-25103: Remove reference to v1alpha1 flowcontrol

api/fixtures/example.go, api/fixtures/example_agent.go, cmd/cluster/agent/create.go, cmd/cluster/core/create.go, cmd/nodepool/agent/create.go, product-cli/cmd/cluster/agent/create.go, product-cli/cmd/nodepool/agent/create.go
This commit allows specifying agentLabelSelector via hypershift CLI as part of 'create nodepool' and 'create cluster'.
The labelselector is passed as a JSON string, for example: ./bin/hypershift create nodepool agent \
--cluster-name for \
--name bar \
--node-count 2 \
--agentLabelSelector 'size=large,zone notin (az1,az2)'
Fixes #[ACM-8917](https://issues.redhat.com//browse/ACM-8917)
**Checklist**
=> ACM-8917: Add agentLabelSelector to nodepool agent create to CLI

cmd/cluster/agent/create.go, product-cli/cmd/cluster/agent/create.go
Clarifies which API Server Address this flag refers to and adds a warning about being connected to the management cluster if leaving the flag unset.
Fixes # [HOSTEDCP-1353](https://issues.redhat.com/browse/HOSTEDCP-1353)
**Checklist**
=> HOSTEDCP-1353: Improve description for agent APIServerAddress CLI flag

api/fixtures/example.go, api/fixtures/example_azure.go, cmd/cluster/azure/create.go, cmd/cluster/azure/destroy.go, cmd/cluster/core/create.go, cmd/cluster/core/destroy.go, cmd/infra/azure/create.go, cmd/infra/azure/destroy.go, cmd/util/azure.go, cmd/util/azure_test.go, docs/content/how-to/azure/create-azure-cluster.md, test/setup/fake_credentials
Allows a user to bring their own resource group to be used to contain all the created Azure infrastructure needed for their hosted cluster. Also allows a user to specify the resource group they brought when deleting a hosted cluster.
Fixes [HOSTEDCP-1329](https://issues.redhat.com/browse/HOSTEDCP-1329)
**Checklist**
=> HOSTEDCP-1329: Allow user to specify resource group for NodePool resources

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go, control-plane-operator/controllers/hostedcontrolplane/manifests/ingress.go
The router deployment is in the request serving path and should be protected from outages by a PDB like the other request serving components
Fixes #[OCPBUGS-24308](https://issues.redhat.com/browse/OCPBUGS-24308)
**Checklist**
=> OCPBUGS-24308: Add PodDisruptionBudget for router deployment

docs/content/how-to/disconnected/known-issues.md, docs/content/how-to/metrics-sets.md, hypershift-operator/main.go
This PR is disabling the UWM telemetry remote writer controller when the management cluster is working in disconnected mode. We asume that this mode is enabled when the first Service network entry is an IPv6, being that entry the first citizen for OVN.
Follow up To-Do:
Fixes #[OCPBUGS-22399](https://issues.redhat.com/browse/OCPBUGS-22399)
=> OCPBUGS-22399: Disable UWM Telemetry remote writer when MGMT cluster is disconnected

api/hypershift/v1beta1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hack/app-sre/saas_template.yaml
Follow on to #3072. Adds additional CEL to the Arch field in the NodePoolSpec to ensure Arch can only be set to arm64 when the platform is AWS.
Fixes [HOSTEDCP-1262](https://issues.redhat.com/browse/HOSTEDCP-1262)
**Checklist**
=> HOSTEDCP-1262: Add additional CEL to Arch in NodePoolSpec

OWNERS
In order to increase the team ability to do general release tasks of tagging, cutting releases and modifying bot automated PRs, we should increase the amount of contributors that have access to such functions.
Adding the following members to approvers:
* bryan-cox
* jparrill
* muraee
jparrill will have an additional approving focus on self-managed PRs.
muraee will have a more general approving focus.
=> NO-JIRA: Approvers update

hypershift-operator/controllers/uwmtelemetry/uwm_telemetry.go
This PR allow the HO to disable UWM telemetry remote writer when `telemeter-client` from `openshift-monitoring` namespace are not present. This CM is necessary to a proper UWM reconciliation. Failing early we avoid to generate unnecessary noise.
Old error:
```
{"level":"error","ts":"2023-12-21T15:33:41Z","msg":"Reconciler error","controller":"deployment","controllerGroup":"apps","controllerKind":"Deployment","Deployment":{"name":"operator","namespace":"hypershift"},"namespace":"hypershift","name":"operator","reconcileID":"c38a8dc2-61de-4dbe-b376-ac0b93cde9b8","error":"cannot get telemeter client secret: Secret \"telemeter-client\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/hypershift/vendor/sigs.k8s.io/controller-runti …
```
=> OCPBUGS-22399: Disable UWM Telemetry writer when telemeter-client cm not exists

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go
The next version of capk (cluster-api-provider-kubevirt) is reading the DataVolume resource. When the new image will land, it will fail as the capk operator does not have permissions to read the DataVolume resource.
This PR adds the missing permissions to allow the capk operator reading this resource.
**Checklist**
=> NO-JIRA: Add rbac permission for kubevirt capi

api/hypershift/v1beta1/hostedcluster_conditions.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Set a new `status.condition` when CPO deletes the SecurityGroup.
Fixes #[OCPBUGS-23362](https://issues.redhat.com/browse/OCPBUGS-23362)
=> OCPBUGS-23362: Set new condition on SG deletion.

.ci-operator.yaml, Dockerfile, Dockerfile.control-plane, fast.Dockerfile, go.mod, go.sum, hack/tools/go.mod, hack/tools/go.sum, hack/tools/vendor/modules.txt
Bumps Golang to v1.21 in the main go.mod and hack/tools go.mod 
[HOSTEDCP-1371](https://issues.redhat.com/browse/HOSTEDCP-1371)
**Checklist**
=> HOSTEDCP-1371: Bump Golang to v1.21

docs/content/how-to/kubevirt/external-infrastructure.md
Documenting the minimal set of permissions needed to create an hosted cluster on an external infrastructure cluster with kubevirt provider.
Fixes # https://issues.redhat.com/browse/CNV-36656
**Checklist**
=> CNV-36656: Documenting the mimimum RBAC required for External Infra cluster with KubeVirt provider

control-plane-operator/controllers/hostedcontrolplane/kas/kms/aws.go, control-plane-operator/controllers/hostedcontrolplane/kas/kms/azure.go, control-plane-operator/controllers/hostedcontrolplane/kas/kms/ibmcloud.go, support/config/kms.go
Standalone OCP encrypts various resources at rest in etcd including routes, oauth access tokens etc.  This change makes HCP also encrypt those objects.
Fixes #
**Checklist**
=> OCPBUGS-25342: Add extra resources to be encrypted.

control-plane-operator/controllers/hostedcontrolplane/kas/config.go
https://issues.redhat.com/browse/OCPBUGS-26232
xref https://github.com/openshift/cluster-kube-apiserver-operator/pull/1561
=> OCPBUGS-26232: set KAS runtime-config in alignment with feature gates

api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, hack/app-sre/saas_template.yaml
manual cherry-pick of https://github.com/openshift/hypershift/pull/3110 and https://github.com/openshift/hypershift/pull/3157
=> [release-4.14] OCPBUGS-22360: Validate accessTokenInactivityTimeout >= 300s

control-plane-operator/main.go
On management clusters 4.15 and newer, the container ID in the CPO pod status is not a valid image reference and should not be used to determine the CPO image.
Fixes #[OCPBUGS-25974](https://issues.redhat.com/browse/OCPBUGS-25974)
**Checklist**
=> OCPBUGS-25974: Do not use CPO image from status if it's not a valid image reference

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
https://issues.redhat.com/browse/HOSTEDCP-1374
Worth noting there is a bug enabling `TechPreviewNoUpgrade` feature gate in the HC to allow Authentication type `OIDC`.  The HCP fails to rollout with crash loop in the KAS.  This will need to be solved before QE can verify this.
Update:
Found the issue with HCP rollout https://github.com/openshift/hypershift/pull/3377
=> HOSTEDCP-1374: external OIDC: copy Authentication OIDC client secrets through to guest

api/hypershift/v1beta1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Exposes GOMEMLIMIT and GOGC for kube-apiserver via annotations in HostedCluster.
Fixes #[HOSTEDCP-1309](https://issues.redhat.com/browse/HOSTEDCP-1309)
**Checklist**
=> HOSTEDCP-1309: Add GC knobs for KAS

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml
Getting error in external-dns `time="2024-01-11T12:34:55Z" level=fatal msg="flag parsing error: flag 'aws-zone-type' cannot be repeated"`
=>  OCPBUGS-26547: fix up external-dns flags

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml
This is causing the oauth private route to not be registered
=> OCPBUGS-26547: remove LoadBalancer filter from external-dns

control-plane-operator/controllers/hostedcontrolplane/cloud/kubevirt/reconcile.go
kCCM deployment was not respecting the node selector configured at `hcp.spec.nodeSelector` that was set with `--node-selector` flag in the create cli command. This PR fixes the issue, by applying `SetDefaults()` to the `deploymentConfig`, which sets the node selector along with other required configurations (e.g. tolerations, affinity, replica count, etc.)
Fixes # https://issues.redhat.com/browse/OCPBUGS-25696
**Checklist**
=> OCPBUGS-25696: Apply Scheduling Configuration for kCCM

availability-prober/availability_prober.go
[OCPBUGS-27027](https://issues.redhat.com/browse/OCPBUGS-27027)
=> OCPBUGS-27027: availability-prober: wait for infrastructure name to be set

Dockerfile.control-plane, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, ignition-server/controllers/local_ignitionprovider.go
Change KAS bootstrap image to cluster-config-api.
Fixes # [OCPBUGS-26757](https://issues.redhat.com/browse/OCPBUGS-26757)
**Checklist**
=> OCPBUGS-26757: Change KAS bootstrap image to cluster-config-api

control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
We regressed on our ability to create HCPs on Azure on the k8s bump to v1.29. 
Fixes [HOSTEDCP-1382](https://issues.redhat.com//browse/HOSTEDCP-1382)-subtask
**Checklist**
=> HOSTEDCP-1382: [Subtask] Restore Ability to Create HCPs on Azure

hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
This fixes the issue of Azure VMs not joining a HostedCluster as nodes because they were not getting added to the outbound LoadBalancer in their resource group. This change sets the name of the outbound LoadBalancer in the AzureCluster so that the CAPI provider can set the proper backend pool on VM NICs.
Fixes #[HOSTEDCP-1283](https://issues.redhat.com/browse/HOSTEDCP-1283)
**Checklist**
=> HOSTEDCP-1283: Set outbound LoadBalancer name on AzureCluster

Dockerfile, Dockerfile.control-plane, fast.Dockerfile
This is needed for compatibility with RHEL9-based images in the release payload. The change will not impact CI or ART images, since they use their own replacements
Fixes #
**Checklist**
=> NO-JIRA: Update Dockerfiles to use publicly available RHEL9 images

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator_test.go
Fixes #OCPBUGS-26977
**Checklist**
=> OCPBUGS-26977: Required RBAC for network-node-identity is not created when hosted cluster networkType is set to Other.

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, ignition-server/controllers/local_ignitionprovider.go
In order to get different schemas and featuregates for hypershift, it is necessary to indicate that we're rendering for hypershift.
=> OCPBUGS-27366: indicate cluster profile to render the correct manifests

test/e2e/util/util.go
This PR allows the test to tolerate a single restart only for KubeVirt when running on external infra. The centralized KubeVirt infra test still does not tolerate any unexpected restarts. 
--- 
The KubeVirt platform has two modes, centralized infra (where HCP and VMs run on the same OCP cluster, and external infra (Where HCP and VMs run on separate OCP clusters)
When we test external infra, we are running HCP KubeVirt running within HCP KubeVirt. This is a complex environment that is difficult to ensure has predictable performance. We occasionally see that random pods in the HCP  namespace restart in this nested environment due to "Error: context deadline exceeded" being reported by the kubelet. This is likely a result of etcd latency within this environment.
=> NO-JIRA: Tolerate restarts for kubevirt external infra

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
This PR Contains:
Fixes #[OCPBUGS-26940](https://issues.redhat.com/browse/OCPBUGS-26940)
=> OCPBUGS-26940: Include OperatorHubSpec sync with HC when Config is empty

cmd/cluster/azure/create.go, cmd/cluster/core/create.go, cmd/infra/azure/create.go
**What this PR does / why we need it**: Add BYO network security group  capability to Azure
Fixes # [HOSTEDCP-1401](https://issues.redhat.com/browse/HOSTEDCP-1401)
**Checklist**
=> HOSTEDCP-1401: Enable BYO NSG

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator_test.go
This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/3403
/assign csrwng
=> [release-4.14] OCPBUGS-28249: Required RBAC for network-node-identity is not created when hosted cluster networkType is set to Other.

cmd/install/assets/hypershift_operator.go, control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/hostedclusterconfigoperator/cmd.go, control-plane-operator/hostedclusterconfigoperator/controllers/machine/machine.go, control-plane-operator/hostedclusterconfigoperator/controllers/machine/machine_test.go, control-plane-operator/hostedclusterconfigoperator/controllers/machine/setup.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile.go, docs/content/how-to/kubevirt/external-infrastructure.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
The KubeVirt provider default ingress uses a passthrow service to
connect to the hosted cluster ingress using it's ingress service
nodeport, this works fine with pod network but when using secondary
networks custom endpoints has to be created and maintained. This change
remove the selector from the service and maintain the endpoints at a
reconcile cycle at nodepool controller, this is done for unconditionally
to pod network attachment configuration.
Depends on:
- https://github.com/openshift/release/pull/47850
Fixes #[HOSTEDCP-1364](https://issues.redhat.com//browse/HOSTEDCP-1364)
**Checklist**
=> HOSTEDCP-1364: kubevirt,  use selector less services for ingress

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Cherry pick of https://github.com/openshift/hypershift/pull/3237 with small change to fix too many arguments in conversion to source.Kind that was seen in automated [cherry pick](https://github.com/openshift/hypershift/pull/3241/files)
=> [release-4.14] OCPBUGS-23997: add watch for HCP pullsecret to HCCO

api/hypershift/v1alpha1/nodepool_types.go, api/hypershift/v1beta1/nodepool_types.go, client/applyconfiguration/hypershift/v1alpha1/azurenodepoolplatform.go, client/applyconfiguration/hypershift/v1beta1/azurenodepoolplatform.go, cmd/cluster/azure/create.go, cmd/cluster/core/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, cmd/nodepool/azure/create.go, docs/content/how-to/azure/create-azure-cluster-with-options.md, docs/content/reference/api.md, examples/fixtures/example.go, examples/fixtures/example_azure.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/azure.go
Adds the capability to enable ephemeral disks for the OS disks in the Azure VMs. In addition, the ability to set the disk storage account type for the OS disks through the CLI was added in this PR as part of the prerequisite work.
[HOSTEDCP-1373](https://issues.redhat.com/browse/HOSTEDCP-1373)
**Checklist**
=> HOSTEDCP-1373: ARO HCP - Add capability for Azure VMs to be created with ephemeral disks

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/ingress.go, control-plane-operator/main.go
Old cleanup code watching `v1.IngressController` which is not available for vanilla kube.  This code is only used for removing an IngressController we used to create long ago.  No modern HC should require this cleanup.
Remove to increase compatibility.
=> NO-JIRA: remove PrivateIngressController cleanup

test/e2e/nodepool_kv_multinet_test.go, test/e2e/nodepool_test.go
Add a e2e at kubevirt provider with a additional network nodepool that will check if that additional network is configured at the VMI.
**Checklist**
=> NO-JIRA: kubevirt, e2e, Add additional network test

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Backport for:
- [OCPBUGS-16189](https://issues.redhat.com/browse/OCPBUGS-16189)
- [OCPBUGS-19746](https://issues.redhat.com/browse/OCPBUGS-19746)
Manual cherry-pick from #3047 
Reason: There was a unit testing failure which I've fixed here. Original automatic PR: https://github.com/openshift/hypershift/pull/3080
=> [release-4.14] OCPBUGS-20547,OCPBUGS-20180: Added network validations

product-cli/cmd/cluster/kubevirt/create.go
This feature of removing the default pod network from the KubeVirt VMs is not fully supported by us yet. We will re-introduce the cli arg once this feature is GAed.
=> [release-4.15] CNV-37394: Remove '--attach-default-network' from productized cli

hypershift-operator/controllers/nodepool/nodepool_controller.go
**What this PR does / why we need it**: Updates AllMachinesReady and AllNodesHealthy status to false as expected with the message NodePool Replicas set to nil.
Fixes # [OCPBUGS-27161](https://issues.redhat.com/browse/OCPBUGS-27161)
**Checklist**
=> OCPBUGS-27161: reflect NodePool replica count nil in status

hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
We were previously using Manual Service Principal in the AzureClusterIdentity, which is now deprecated. This was causing lots of warning messages in the capi provider pod in the control plane. This PR updates the AzureClusterIdentity to now use Service Principal which is identical. 
See [this page](https://capz.sigs.k8s.io/topics/identities#deprecated-identity-types) in the CAPZ book for further details.
Fixes [HOSTEDCP-1408](https://issues.redhat.com/browse/HOSTEDCP-1408)
**Checklist**
=> HOSTEDCP-1408: Update CAPZ Identity Type to Service Principal

test/e2e/nodepool_kv_multinet_test.go, test/e2e/nodepool_test.go
Add a e2e at kubevirt provider with a additional network nodepool that will check if that additional network is configured at the VMI.
=> [release-4.15] NO-JIRA: kubevirt, e2e Add additional network test

support/config/deployment.go
At kubevirt provider we pass "nil" labels to the deployment defaults configurator, that should skip pod anti affinity, but a bit was missing to do so.
Whitout this the kccm deployement end up with 
```yaml
podAntiAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
- labelSelector: {}
topologyKey: kubernetes.io/hostname
```
Which prevent it from schedule.
The pod anti affinity feature was introduced by https://github.com/openshift/hypershift/pull/3286
Fixes #
**Checklist**
=> NO-JIRA: manifests: Skip pod anti affinity for nil labels

cmd/infra/powervs/create.go, cmd/infra/powervs/destroy.go, cmd/infra/powervs/service_id.go, cmd/infra/powervs/service_id_test.go
This PR reduces the permission access scope to Service Instance for various CRs.
Fixes #https://issues.redhat.com/browse/MULTIARCH-4084
**Checklist**
=> MULTIARCH-4084: Reduce the policy access scope to specific instance

control-plane-operator/controllers/hostedcontrolplane/cloud/kubevirt/reconcile.go
Previously the kubevirt cloud controller manager  did not have an `app` label associated with it. The outcome of this is the component would not be guaranteed to be spread out according to our anti-affinity rules. With the labels, anti-affinity rules are applied.
=> NO-JIRA: Add app labels to KubeVirt CCM component

support/supportedversion/version.go
When no release image is provided on a HostedCluster, the backend hypershift operator picks the latest OCP release image within the operator's support windown.
Today this fails due to how the operator selects this default image. For example, hypershift operator 4.14 does not support 4.15, but the 4.15.0.rc.3 is picked as a default release image today. 
This is a result of not anticipating that release candidates would not be reported as the latest stable release. The filter used to pick the latest release needs to consider patch level releases before the next y stream release.
=> OCPBUGS-28741: Fix default release image lookup

docs/content/how-to/disconnected/known-issues.md, docs/content/how-to/metrics-sets.md, hypershift-operator/main.go
This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/3380
/assign jparrill
=> [release-4.14] OCPBUGS-26526: Documented to disable UWM telemetry writer in disconnected envs

control-plane-operator/controllers/hostedcontrolplane/kas/config.go
**What this PR does / why we need it**: This plugin is in base OpenShift KAS config, but missing in HyperShift
Fixes #28659
**Checklist**
=> OCPBUGS-28659: Add ValidatingAdmissionPolicy to KAS config

api/util/configrefs/refs_test.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Copying of the Authentication configmap and secret refs is already handled here https://github.com/openshift/hypershift/blob/96cc2066d61627252bdb66782cb5b922b80cae2c/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go#L1498-L1542
No reason to do it twice.
=> NO-JIRA: remove unneeded code to copy Authentication refs

api/hypershift/v1alpha1/hosted_controlplane.go, api/hypershift/v1beta1/hosted_controlplane.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, hack/app-sre/saas_template.yaml
Sets ControllerAvailabilityPolicy field immutable so a customer cannot go between SingleReplica to HighAvailability and vice versa.
Fixes [OCPBUGS-27282](https://issues.redhat.com/browse/OCPBUGS-27282)
**Checklist**
=> OCPBUGS-27282: Make ControllerAvailabilityPolicy immutable

test/e2e/nodepool_upgrade_test.go
Due to an issue in nmstate in which files on the ostree filesystem have been modified, MCO could not drain the node and apply an RHCOS rollout in place.
This has been [fixed](https://github.com/nmstate/nmstate/pull/2499) in a recent release of RHCOS, thus we can enable it now.
Fixes # https://issues.redhat.com/browse/CNV-36608
**Checklist**
=> CNV-36608: Enable InPlace NodePool upgrade test for kubevirt

hypershift-operator/controllers/nodepool/nodepool_controller.go
**What this PR does / why we need it**: Updates AllMachinesReady and AllNodesHealthy status to false as expected with the message NodePool Replicas set to nil.
Fixes # [OCPBUGS-29179](https://issues.redhat.com/browse/OCPBUGS-29179)
**Checklist**
=> OCPBUGS-29179: [4.15] reflect NodePool replica count nil in status

hypershift-operator/controllers/supportedversion/reconciler_test.go, support/supportedversion/version.go, support/supportedversion/version_test.go
In order to support a set of known OCP versions, we are setting a fixed minimum supported version, instead of a number of previous versions.
Fixes #[HOSTEDCP-1420](https://issues.redhat.com/browse/HOSTEDCP-1420)
**Checklist**
=> HOSTEDCP-1420: Set a fixed minimum supported version

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml
Ideally, we would not need to backport this.  However, release-4.15 across the org currently use the HO built from the release-4.15 branch and it is not trivial to change this.  release-4.15 jobs are still creating route53 throttling situation so let's backport this fix.
Contains https://github.com/openshift/hypershift/pull/3394 and follow up fix https://github.com/openshift/hypershift/pull/3408
=> OCPBUGS-29020: reduce external-dns route53 call volume

contrib/ci/README.md, contrib/ci/dev-namespace-template.yaml
Adds a template for developers to use in creating their own management clusters on a CI cluster.
=> NO-JIRA: Developer namespace template for CI clusters

test/e2e/nodepool_machineconfig_test.go, test/e2e/nodepool_nto_machineconfig_test.go
The increase in KubeVirt specific nodepool tests has introduced instability into the test suite. This instability is a result of increasing the number of parallel VMs that are created during the nodepool tests to account for the KubeVirt unique test cases. The infra is performing inconsistently which results in unpredictable variations in the VM startup time.
For now, we're reducing some of the generic test cases that were previously exercised for the KubeVirt platform. The aws lane covers these generic cases and the kubevirt lane covers the kubevirt unique nodepool cases.
Related to: https://issues.redhat.com/browse/CNV-38196
=> NO-JIRA: Reduce nodepool test cases for KubeVirt due to infra perf issues

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
=> OCPBUGS-29209: hypershift-operator: don't create PKI rbac when disabled

docs/content/how-to/agent/other-sdn-providers.md, docs/content/how-to/aws/other-sdn-providers.md, docs/content/how-to/sdn/other-sdn-providers.md, docs/mkdocs.yml
This PR adds docs to the agent provider section on how to get other SDN providers (Calico and Cilium) deployed in a HostedCluster.
None
**Checklist**
=> OCPBUGS-28538: Added docs to get other sdn providers deployed with agent provider

test/e2e/nodepool_upgrade_test.go
Reverts openshift/hypershift#3517
There is a suspicion that this test causes flakes for the entire kubevirt nodepool test suite and reduces the job's pass rate.
=> Revert "CNV-36608: Enable InPlace NodePool upgrade test for kubevirt"

cmd/nodepool/core/create.go
This bug regards on a day2 nodepool creation. If you creates a cluster using the CLI, it defaults the NodepoolUpgradeType according to the HostedCluster Platform Type. With this PR we also covers the day 2 Nodepool creation which is not using the default fixtures.
Fixes #[OCPBUGS-29115](https://issues.redhat.com/browse/OCPBUGS-29115)
=> OCPBUGS-29115: Default NodeUpgradeType on day2 nodepool creation

docs/content/how-to/kubevirt/configuring-network.md, docs/content/how-to/kubevirt/create-kubevirt-cluster.md, docs/content/how-to/kubevirt/performance-tuning.md, docs/mkdocs.yml
This adds KubeVirt platform documentation for the following new features.
- Additional Networks
- CPU Performance
- VM NodeSelector
=> NO-JIRA: KubeVirt Platform Documentation for Additional Network, CPU Performance, and VM NodeSelector

control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/machineapprover/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/nto/clusternodetuningoperator.go, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go, control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go
The changes here simply extends what was already started back in https://github.com/openshift/hypershift/pull/1082 to more components.  Specifically, adding container resource preservation for the following control-plane components:
```
hosted-cluster-config-operator
cluster-network-operator
konnectivity-server
konnectivity-agent
machine-approver-controller
cluster-autoscaler
olm-operator
packageserver
cluster-node-tuning-operator
ingress-operator
ignition-server
catalog-operator
```
=> HOSTEDCP-1438: Preserve container resources for more hosted control plane components

control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/cco/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/cco/reconcile_test.go, control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/deployment.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator_test.go, control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/dnsoperator/dnsoperator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/machineapprover/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go, control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/deployment.go, control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator.go, control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator_test.go, control-plane-operator/controllers/hostedcontrolplane/storage/operator.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/network_policies.go, support/config/constants.go
A recent [PR](https://github.com/openshift/hypershift/commit/c030ab66d897815e16d15c987456deab8d0d6da0) updated the kube-apiserver service port to `6443`. That change causes a small outage when upgrading from a 4.13 cluster in IBMCloud. This PR makes changes to remain on `2040` as the kube-apiserver  service.
Fixes https://issues.redhat.com/browse/OCPBUGS-29586
**Checklist**
=> OCPBUGS-29586: use 2040 for apiserver svc in IBM provider

docs/content/how-to/sdn/other-sdn-providers.md
Fixes #[OCPBUGS-28538](https://issues.redhat.com/browse/OCPBUGS-28538)
Forgot to add an SCC for Cilium validation pods.
=> OCPBUGS-28538: Add an SCC for validation pods with Cilium SDN

support/releaseinfo/releaseinfo.go
This PR incorporates the changes in openshift/oc#1685 in Hypershift but with a slight 
differences. Since oc uses all the component versions, we are printing a warning to a user
about kubectl mismatches. On the other hand, Hypershift only deals with [version](https://github.com/openshift/hypershift/blob/b4209f3c421a319efa0a350737edc17318fd87ae/control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go#L2073) and
[kubernetes](https://github.com/openshift/hypershift/blob/e8a0c300a659d8d3cb0507b842771ee820a9554e/control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go#L3954) fields in component versions and there is no benefit of a kubectl version mismatch warning. 
Besides, printing a warning …
=> NO-JIRA: Ignore kubectl version mistmaches in Component Versions

cmd/nodepool/aws/create.go
A security group is no longer created by the CLI when creating a new cluster since we rely on the default one created by the control plane operator. This fix removes the requirement to specify a security group when creating a new nodepool through the CLI, otherwise creation fails when one is not specified.
Fixes #[OCPBUGS-29723](https://issues.redhat.com/browse/OCPBUGS-29723)
**Checklist**
=> OCPBUGS-29723: CLI: create nodepool aws - remove sg requirement

control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go, control-plane-operator/controllers/hostedcontrolplane/kas/pdb.go, control-plane-operator/controllers/hostedcontrolplane/oapi/pdb.go, control-plane-operator/controllers/hostedcontrolplane/oauth/pdb.go
We are currently experiencing issues in CI when the autoscaler scales down the cluster and evicts pods from actively running mgmt clusters running prow jobs.  These mgmt clusters run `SingleReplica` to save on resources and can not tolerate being evicted without control plane downtime.  Depending on when this downtime occurs during the job, it frequently causes flakes.
Setting `minAvailable` to `1` on deployments that are required for smooth running of the KAS (etcd, kas itself, aggregated apiservers, and ingress to the kas) will prevent these pods from being evicted until the jobs complete.
=> NO-JIRA: always set minAvailable on PDBs to 1

cmd/cluster/azure/create.go, cmd/infra/azure/create.go, control-plane-operator/controllers/hostedcontrolplane/cloud/azure/providerconfig.go
This PR provides support for disabling outbound SNAT through the Azure Cloud Provider configuration. This is accomplished by providing the Azure Cloud Provider configuration a load balancer to use and setting the flag to disable outbound SNAT.
In addition, this PR updates the HyperShift CLI by creating a load balancer, with an outbound rule, and public IP address when creating Azure infrastructure. The Azure Cloud Provider will use the load balancer to add an additional public IP address and the appropriate load balancer rules.
Fixes [HOSTEDCP-1424](https://issues.redhat.com/browse/HOSTEDCP-1424)
**Checklist**
=> HOSTEDCP-1424: ARO HCP Support Disabling Outbound SNAT

control-plane-operator/controllers/hostedcontrolplane/cco/testdata/zz_fixture_TestReconcileDeployment.yaml, control-plane-operator/controllers/hostedcontrolplane/pkioperator/testdata/zz_fixture_TestReconcileControlPlanePKIOperatorDeployment.yaml, control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcileDeployment.yaml, control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/testdata/zz_fixture_TestReconcileOperatorDeployment.yaml, support/config/deployment.go
Reduce default `RevisionHistoryLimit` to improve control plane scalability. The default of 10 is significantly impacting etcd load on management cluster.
Fixes/alleviates [OCPBUGS-28607](https://issues.redhat.com/browse/OCPBUGS-28607)
**Checklist**
=> OCPBUGS-28607: feat(config): Default RevisionHistoryLimit to 2 for deployments

cmd/install/assets/hypershift_operator.go, cmd/install/assets/hypershift_operator_test.go, cmd/install/install.go, hack/app-sre/saas_template.yaml, hypershift-operator/main.go
Adding HO flag to support disabling dedicated request serving isolation controllers.
Fixes #
**Checklist**
=> OCPBUGS-29855: feat(ho): Add flag for dedicated request serving isolation

test/e2e/nodepool_upgrade_test.go
Reverts openshift/hypershift#3547
The fix for the inplace upgrade has been fixed on MCO side and merged at https://github.com/openshift/machine-config-operator/pull/4190
Re-enabling the test to validate kubevirt provider can now perform NodePool InPlace upgrades.
=> NO-JIRA: Re-enable InPlace NodePool upgrade test for kubevirt (CNV-36608)

control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
Follow up to https://github.com/openshift/hypershift/pull/3204 
Updates the shutdown delay duration for the OAuth API server as well
Fixes # [OCPBUGS-27180](https://issues.redhat.com/browse/OCPBUGS-27180)
**Checklist**
=> OCPBUGS-27180: Update the oauth API server's shutdown delay duration

control-plane-operator/controllers/hostedcontrolplane/kas/auth_types.go
https://issues.redhat.com/browse/OCPBUGS-30029
Fixes an issue in `release-4.15` that does not exist in `main`
Sync source:
https://github.com/openshift/kubernetes/pull/1884/files#diff-6c0eb218aff9987eeae38d64283b622250d4c1e2275e4dba11477d9e6ba64083
=> OCPBUGS-30029: sync AuthenticationConfiguration type with o/k 1.28 carry

test/e2e/util/util.go
Created https://issues.redhat.com/browse/OCPBUGS-30061 to track this regression.
Making this change to reduce flakes in the meantime.
=> NO-JIRA: test: increase CPO mutate budget

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/auth.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
KEP on structured authentication config states that KAS will reload the config when it changes
https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/3331-structured-authentication-configuration/README.md?plain=1#L115
However, this does not seem to be true.
If the Authentication config is changed, the auth-config configmap is updated and the projected file in the KAS pod is also updated. However, the KAS does not reload the config dynamically.
Working on a solution that manually triggers a KAS rollout on authentication config changes.
=> OCPBUGS-30030: rollout kas on auth config change

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go
This PR sets the cipher suite parameter for Konnectivity server
Fixes # https://issues.redhat.com/browse/OCPBUGS-29773
**Checklist**
=> OCPBUGS-29773: set Konnectivity cipher suites

test/e2e/util/util.go
We are seeing test flakes due to CCO pod restart because of https://issues.redhat.com/browse/OCPBUGS-30068
Skip for now to avoid flakes.
=> NO-JIRA: test: skip CCO in pod crash check

test/integration/control_plane_pki_operator.go
This works for newer k8s API servers. Bug is reported against 4.15 ... wondering if the 1.28->1.29 bump is the fix?
=> OCPBUGS-29613: test: add a test for invalid CSRs

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/auth.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
Clean pick of https://github.com/openshift/hypershift/pull/3647
Automated cherry-pick failed because https://github.com/openshift/hypershift/pull/3522 had not yet merged, but now it has.
=> OCPBUGS-30088: rollout kas on auth config change

hypershift-operator/controllers/hostedcluster/network_policies.go
When creating an HostedCluster with 'NodePort' service publishing strategy, the VMs (guest nodes) are trying to contact HCP services, such as ignition and oauth. If these services are colocated on the same infra node, they can't be reached via NodePort because the 'virt-launcher' NetworkPolicy is blocking it. Explicitly adding access to oauth and ignition-server-proxy pods so they can be reached from the virtual machines on the same node.
Fixes #
**Checklist**
=> OCPBUGS-30301: [kubevirt] Fix virt-launcher netpol to allow missing access

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
**What this PR does / why we need it**:  Fixes use of incorrect error return when deleting AWS SG
Fixes # [OCPBUGS-28370](https://issues.redhat.com/browse/OCPBUGS-28370)
**Checklist**
- [] This change includes docs.
=> OCPBUGS-28370: Use correct return error when destroying AWS SG

control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcileDeployment.yaml
Set the operator image environment variable so that the image-registy cluster operator can proceed. This is a newer requirement coming from [here](https://github.com/openshift/cluster-image-registry-operator/blob/master/manifests/07-operator.yaml#L71).
Fixes [OCPBUGS-30060](https://issues.redhat.com/browse/OCPBUGS-30060)
**Checklist**
=> OCPBUGS-30060: Set OPERATOR_IMAGE environment variable

availability-prober/availability_prober.go, cmd/infra/powervs/destroy.go, control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go, control-plane-pki-operator/certificaterevocationcontroller/certificaterevocationcontroller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/platform/aws/controller.go, hypershift-operator/init.go, hypershift-operator/main.go, ignition-server/cmd/run_local_ignitionprovider.go
This analyzer was recently added to `gopls`.  We should look at adding this to `make verify`.
```
$ go install golang.org/x/tools/go/analysis/passes/nilness/cmd/nilness@latest
$ go vet -vettool $(which nilness) ./...
cmd/infra/powervs/destroy.go:479:10: nil dereference in field selection
cmd/infra/powervs/destroy.go:480:10: nil dereference in field selection
availability-prober/availability_prober.go:175:12: tautological condition: non-nil != nil
control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go:521:9: impossible condition: nil != nil
control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go:748:9: impossible condition: nil != nil
ignition-server/cmd/run_local_ignitionprovider.go:75:9: impossible condition: nil != nil …
```
=> NO-JIRA: cleanup: nilness check failures

test/e2e/nodepool_nto_machineconfig_test.go
Reverts openshift/hypershift#3683
Break has been reverted
https://amd64.ocp.releases.ci.openshift.org/#4.16.0-0.ci
=> Revert "NO-JIRA: test/e2e: temporarily skip NTO machineconfig test"

ignition-server/controllers/local_ignitionprovider.go
**What this PR does / why we need it**:  Use cluster-config-operator for 4.14 payloads
Fixes # [OCPBUGS-30242](https://issues.redhat.com/browse/OCPBUGS-30242)
**Checklist**
=> OCPBUGS-30242: Use cluster-config-operator for 4.14 payload

control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
4.16 default olm catalog sources are available already, so we can now update the default catalog sources to point to 4.16 indices instead of 4.14.
Fixes #
**Checklist**
=> OCPBUGS-30574: Update OLM Default Catalog Sources to 4.16 on main

support/metrics/sets.go
The HCCO emits very few metrics, all of which are central to understanding how the controller is running. We don't need to omit anything from the HCCO, for the same reasons that we don't omit anything from the CPO.
=> HOSTEDCP-1466: support/metrics: don't filter HCCO metrics

support/certs/tls.go
Updates TLS cert hash creation with sha512 instead of sha1
Fixes [HOSTEDCP-1480](https://issues.redhat.com/browse/HOSTEDCP-1480)
**Checklist**
=> HOSTEDCP-1480: Update TLS cert hash creation with sha512

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
**What this PR does / why we need it**: Removes resource limits on azure-cloud-node-manager which fails the[ conformance test](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/49476/rehearse-49476-pull-ci-openshift-hypershift-main-e2e-conformance-azure/1765029560367190016)
Fixes #  https://issues.redhat.com/browse/HOSTEDCP-1460
**Checklist**
=> HOSTEDCP-1460: Remove resource limits on azure-cloud-node-manager

control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
OCP 4.15.0 is GA, we can now update the default catalog sources to point to 4.15 indices instead of 4.14
Fixes #
**Checklist**
=> OCPBUGS-30572: [release-4.15] Update OLM Default Catalog Sources to 4.15

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go
In-cluster clients should be able to talk directly to the node local apiservert ip address and as a best practice should all be configured to use it. This load balancer provides added benefit in cloud environments of healthchecking the path from the machine to the load balancer fronting the kube-apiserver. It becomes more cruicial in baremetal/on-prem environments where there may not be a load balancer and instead just 3 unique endpoints directly to redundant kube-apiservers. In this case: if using just dns: intermittent traffic failures will be experienced if a control plane instance goes down. Using the node local load balancer: there will be no traffic disruption …
=> OCPBUGS-30769: include node local client loadbalancer address in kube-apiserver signing ips

cmd/cluster/aws/create.go, cmd/cluster/aws/create_test.go, cmd/cluster/core/create.go, docs/content/how-to/aws/create-heterogeneous-nodepools.md, docs/mkdocs.yml, support/releaseinfo/registryclient/client.go
Adds the multi-arch flag to the HyperShift CLI to trigger additional validation to ensure a multi-arch release image or stream was used.
Fixes [HOSTEDCP-1220](https://issues.redhat.com/browse/HOSTEDCP-1220)
**Checklist**
=> HOSTEDCP-1220: Add multi-arch flag to CLI & associated validation

docs/content/labs/common/mce/agentserviceconfig.md
Instructing customers to override PUBLIC_CONTAINER_REGISTRIES is not ideal since the value specified for that override will completely wipe the default list and they could run into issues getting their images pulled (see https://issues.redhat.com/browse/OCPBUGS-28634). Instead we should provide the option to just add their registry to the default list.
Modifies the document for setting up assisted service to add a customer's registry as a "public" registry (one that doesn't require authentication). Prevents customers from using PUBLIC_CONTAINER_REGISTRIES which will override the default list. …
=> OCPBUGS-28634: Update agentserviceconfig.md to remove PUBLIC_CONTAINER_REGISTRIES

ignition-server/controllers/local_ignitionprovider.go
**What this PR does / why we need it**:  Reverts checks to simple major and minor checks that will work with nighlty images
Fixes # [OCPBUGS-30242](https://issues.redhat.com/browse/OCPBUGS-30242)
**Checklist**
=> OCPBUGS-30242: consider nigthly images in payoad version check

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
AWS recommends using Regional AWS STS endpoints instead of the global endpoint to reduce latency, build in redundancy, and increase session token validity.
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html
[HOSTEDCP-1488](https://issues.redhat.com//browse/HOSTEDCP-1488)
**Checklist**
=> HOSTEDCP-1488: Use regionalized STS endpoints in AWS

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator.go, control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator_test.go, control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/testdata/zz_fixture_TestReconcileOperatorDeployment.yaml
Sets an environment variable when the management cluster the HCP is on supports SCC. This is needed to let the CSI operators not run their pod images as non-root.
Fixes [STOR-1805](https://issues.redhat.com/browse/STOR-1805)
**Checklist**
=> STOR-1805: Set env var when the mgmt cluster supports SCC 

test/e2e/util/util.go
Bump CPO Read API budget to 4000 in EnsureApiBudget to stay in sync with 4.15
=> NO-JIRA:Bump CPO Read API budget to 4000 in EnsureApiBudget

cmd/install/assets/hypershift_operator.go, cmd/install/install.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Adds the ability to set managed service type in HO
Fixes [HOSTEDCP-1487](https://issues.redhat.com/browse/HOSTEDCP-1487)
**Checklist**
=> HOSTEDCP-1487: Add ability to set managed service type in HO

api/hypershift/v1beta1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go, control-plane-operator/controllers/hostedcontrolplane/kas/service.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go, support/util/util.go, vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
Introduces an annotation to HostedClusters
(hypershift.openshift.io/aws-load-balancer-subnets) that will drive the service.beta.kubernetes.io/aws-load-balancer-subnets annotation on services of type LoadBalancer created by a hosted control plane.
Modifies the request serving node scheduler to automatically set the above annotation if the label
hypershift.openshift.io/request-serving-subnets is set on request serving nodes.
Fixes #[OCPBUGS-30260](https://issues.redhat.com/browse/OCPBUGS-30260)
**Checklist**
=> OCPBUGS-30260: Support specifying AWS LB subnets

test/e2e/create_cluster_test.go, test/e2e/util/util.go
Full revert of [1] and partial revert of [2].
[1] https://github.com/openshift/hypershift/pull/3107
[2] https://github.com/openshift/hypershift/pull/3137
Fixes # [OCPBUGS-30651](https://issues.redhat.com/browse/OCPBUGS-30651)
**Checklist**
=> [release-4.15] OCPBUGS-30651: Remove EnsurePSANotPrivileged

api/hypershift/v1alpha1/nodepool_types.go, api/hypershift/v1beta1/nodepool_types.go, client/applyconfiguration/hypershift/v1alpha1/azurenodepoolplatform.go, client/applyconfiguration/hypershift/v1beta1/azurenodepoolplatform.go, cmd/cluster/azure/create.go, cmd/cluster/core/create.go, cmd/infra/azure/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, cmd/nodepool/azure/create.go, docs/content/how-to/azure/create-azure-cluster-with-options.md, docs/content/reference/api.md, examples/fixtures/example.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/azure.go, vendor/github.com/openshift/hypershift/api/hypershift/v1alpha1/nodepool_types.go, vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go
This PR allows the subnet to be set on a NodePool basis rather than just at the Hosted Cluster level. 
This PR also adds a flag to define the initial NodePool's subnet name when creating an Azure cluster, and it adds a flag when creating Azure NodePools to the HyperShift CLI.
Fixes [HOSTEDCP-1467](https://issues.redhat.com/browse/HOSTEDCP-1467)
**Checklist**
=> HOSTEDCP-1467: ARO HCP - Add ability to specify subnet at nodepool level

test/e2e/util/util.go
Bump CPO API budget to 4000 in EnsureApiBudget
=> NO-JIRA: Bump CPO API budget to 4000 in EnsureApiBudget

cmd/install/assets/hypershift_operator.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go, control-plane-operator/controllers/hostedcontrolplane/kas/pdb.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/pdb.go, control-plane-operator/controllers/hostedcontrolplane/oauth/pdb.go, hack/app-sre/saas_template.yaml, support/util/pdb.go
Two commits to increase stability in autoscaled environments:
* Set `MaxUnavailable: 1` on API critical component PDBs when `HighlyAvailable`
* Disable preemption for hypershift PriorityClasses
=> NO-JIRA: Increase stability in autoscaled environments

api/hypershift/v1beta1/hostedcluster_types.go, cmd/install/install.go, vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
Adds managed service constants to HyperShift API
Fixes [HOSTEDCP-1487](https://issues.redhat.com/browse/HOSTEDCP-1487)
**Checklist**
=> HOSTEDCP-1487: Add managed service constants to HyperShift API

cmd/install/assets/hypershift_operator.go, cmd/install/install.go, control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/hostedclusterconfigoperator/cmd.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go, test/integration/framework/install.go
Controls whether the controller that labels clusters based on size is enabled. Default is disabled.
Fixes #[HOSTEDCP-1429](https://issues.redhat.com//browse/HOSTEDCP-1429)
**Checklist**
=> HOSTEDCP-1429: Add install flag to enable/disable size tagging

hack/ci-test-e2e.sh, test/e2e/control_plane_upgrade_test.go, test/e2e/e2e_test.go
=> NO-JIRA: Adding Disable PKI Reconciliation annotation as an option

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
MCO treats KubeletConfigs and ContainerRuntimeConfigs  with no `machinePoolSelector` as matching nothing, not everything.
https://github.com/openshift/machine-config-operator/blob/master/pkg/controller/kubelet-config/kubelet_config_bootstrap.go#L37-L41
https://github.com/openshift/machine-config-operator/blob/master/pkg/controller/container-runtime-config/container_runtime_config_bootstrap.go#L29-L33
=> OCPBUGS-31102: inject built-in MCP selector for KubeletConfigs and ContainerRuntimeConfigs

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
The control-plane-operator Role has a rule to allow use of the hostnetwork SCC, but the control-plane-operator actually runs under the restricted-v2 SCC.
This change removes the unused rule.
Fixes #
**Checklist**
=> NO-JIRA: Remove unused ref to hostnetwork in cpo role

cmd/install/assets/hypershift_operator.go, cmd/install/install.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedclustersizing/setup.go
Before this PR, the install command was creating the default cluster sizing config CR. This caused existing configuration to be overwritten on upgrade of the hypershift operator. Now it's created by the operator only if it doesn't exist.
Fixes #[HOSTEDCP-1501](https://issues.redhat.com/browse/HOSTEDCP-1501)
**Checklist**
=> HOSTEDCP-1501: Create default ClusterSizingConfig CR on start

api/hypershift/v1alpha1/hostedcluster_types.go, api/hypershift/v1beta1/hostedcluster_types.go, client/applyconfiguration/hypershift/v1alpha1/awsplatformspec.go, client/applyconfiguration/hypershift/v1beta1/awsplatformspec.go, cmd/cluster/aws/create.go, cmd/cluster/core/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, docs/content/how-to/aws/create-heterogeneous-nodepools.md, docs/content/reference/api.md, examples/fixtures/example.go, examples/fixtures/example_aws.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/util/util.go, vendor/github.com/openshift/hypershift/api/hypershift/v1alpha1/hostedcluster_types.go, vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
Validate a multi-arch release image is used when an AWS Hosted Cluster
is set up for multi-arch. Validate management and nodepool CPU arches
match in the CLI if the multi-arch flag is not set. Also, validate each
NodePool CPU arch matches the management cluster's CPU arch when an AWS
Hosted Cluster is not setup for multi-arch.
Fixes [HOSTEDCP-1105](https://issues.redhat.com/browse/HOSTEDCP-1105)
**Checklist**
=> HOSTEDCP-1104,HOSTEDCP-1105: Validate multi-arch aspects in an AWS Hosted Cluster

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
**What this PR does / why we need it**: Fixes priority class override feature that was accidentally removed for ignition server deployment by https://github.com/openshift/hypershift/pull/2668
Fixes #
**Checklist**
=> OCPBUGS-31118: fix(ignition): Fix priority class override

cmd/infra/azure/create.go
Fix the following error encountered when creating Azure infrastructure:
```bash
hypershift create infra azure --name $CLUSTER_NAME --azure-creds $HOME/.azure/osServicePrincipal.json --base-domain $BASE_DOMAIN --infra-id $INFRA_ID --location eastus --output-file $OUTPUT_INFRA_FILE --resource-group-tags 'foo=bar,baz=quux' --resource-group-tags 'abc=def'
2024-03-20T13:38:36+08:00	INFO	Using credentials from file	{"path": "/Users/fxie/.azure/osServicePrincipal.json"}
2024-03-20T13:38:42+08:00	INFO	Successfully created resource group	{"name": "fxie-hcp-1-fxie-hcp-1-13639"}
2024-03-20T13:38:45+08:00	INFO	Successfully created managed identity	{"name": "/subscriptions/53b8f551-f0fc-4bea-8cba-6d1fefd54c8a/resourcegroups/fxie-hcp-1-fxie-hcp-1-13639/providers/Microsoft.ManagedIdentity/userAssignedIde …
```
=> OCPBUGS-31090: Fix empty subnet name error when creating Azure infrastructure

cmd/infra/azure/destroy.go
Fix the following error:
```bash
$ hypershift destroy infra azure --azure-creds $HOME/.azure/osServicePrincipal.json --location eastus --infra-id $INFRA_ID --name $CLUSTER_NAME 
2024-03-20T03:48:24+08:00	INFO	Using credentials from file	{"path": "/Users/fxie/.azure/osServicePrincipal.json"}
2024-03-20T03:48:24+08:00	ERROR	Failed to destroy infrastructure	{"error": "failed to start deletion: parameter resourceGroupName cannot be empty"}
github.com/openshift/hypershift/cmd/infra/azure.NewDestroyCommand.func1
/Users/fxie/Projects/hypershift/cmd/infra/azure/destroy.go:47
github.com/spf13/cobra.(*Command).execute
/Users/fxie/Projects/hypershift/vendor/github.com/spf13/cobra/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
/Users/fxie/Projects/hypershift/vendor/github.com/spf13/cobra/co …
```
=> OCPBUGS-31089: Fix empty resourceGroupName error when deleting Azure infra

cmd/cluster/core/create.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/util/util.go, support/util/util_test.go
Skips the cluster/nodepool CPU check on render and properly gets the mgmt cluster CPU from the API Server version to check against the NodePool CPU.
We are also not blocking the CLI execution if these don't match now.
Fixes [HOSTEDCP-1104](https://issues.redhat.com/browse/HOSTEDCP-1104)
**Checklist**
=> HOSTEDCP-1104: Skip CPU Check on Render & Get Mgmt Cluster CPU from API Server

cmd/infra/azure/create.go
Fix the following error:
```bash
$ hypershift create infra azure --name $CLUSTER_NAME --azure-creds $HOME/.azure/osServicePrincipal.json --base-domain $BASE_DOMAIN --infra-id $INFRA_ID --location eastus --output-file $OUTPUT_INFRA_FILE
2024-03-20T14:26:23+08:00	INFO	Using credentials from file	{"path": "/Users/fxie/.azure/osServicePrincipal.json"}
2024-03-20T14:26:30+08:00	INFO	Successfully created resource group	{"name": "fxie-hcp-1-fxie-hcp-1-13639"}
2024-03-20T14:26:32+08:00	INFO	Successfully created managed identity	{"name": "/subscriptions/53b8f551-f0fc-4bea-8cba-6d1fefd54c8a/resourcegroups/fxie-hcp-1-fxie-hcp-1-13639/providers/Microsoft.ManagedIdentity/userAssignedIdentities/fxie-hcp-1-fxie-hcp-1-13639"}
2024-03-20T14:26:32+08:00	INFO	Assigning role to managed identity, this may …
```
=> OCPBUGS-31110: Fix empty RHCOSImage error when creating Azure Infrastructure

api/hypershift/v1beta1/hostedcluster_types.go, hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go, hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes_test.go, hypershift-operator/controllers/scheduler/placeholders.go, hypershift-operator/main.go, support/util/deployment.go, vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
Introduces a new scheduler that is only enabled if cluster size tagging is enabled. It takes into consideration the size label of a particular hosted cluster to select nodes where the cluster's request serving pods are scheduled and applies settings configured in the cluster sizing configuration to the hosted cluster.
Fixes #[HOSTEDCP-1478](https://issues.redhat.com/browse/HOSTEDCP-1478)
**Checklist**
=> HOSTEDCP-1478: Request serving node scheduler that uses HC size label

Makefile, hack/ci-test-e2e-azure.sh, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/util/util.go
**What this PR does / why we need it**: getting TestCreateCluster and TestNodePool to work with Azure so we can use them as presubmits to get started with.
Fixes # [HOSTEDCP-1462](https://issues.redhat.com/browse/HOSTEDCP-1462)
**Checklist**
=> HOSTEDCP-1462: Enable TestNodePool and CreateCluster tests on Azure

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
manual backport of https://github.com/openshift/hypershift/pull/3780 because 4.15 is missing https://github.com/openshift/hypershift/pull/1782
=> OCPBUGS-31265: inject built-in MCP selector for KubeletConfigs and ContainerRuntimeConfigs

api/hypershift/v1alpha1/hostedcluster_types.go, api/hypershift/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, vendor/github.com/openshift/hypershift/api/hypershift/v1alpha1/hostedcluster_types.go, vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
Our recommendation for production is to always use Highly Available control planes, but our default (Single Replica) conflicts with this recommendation. as a result, we've had cases reported where users ended up inadvertently with single replica control planes (meaning no etcd replication) without understanding they needed to opt-in to HA mode.
The `hcp` cli defaults to HA mode. People using the API directly don't benefit from this default though. This PR makes the API default align with both the `hcp` cli and our recommendations for production.
=> NO-JIRA: Set control plane to HA by default

cmd/nodepool/core/create.go, cmd/nodepool/create.go, product-cli/cmd/nodepool/create.go
The `--auto-repair` flag is already present during `hcp create cluster...` however this value is not present when creating a new nodepool for an existing cluster. This PR addresses that by bringing parity to the cli nodepool creation.
=> NO-JIRA: Add --auto-repair flag to `hcp create nodepool`

control-plane-operator/controllers/hostedcontrolplane/cloud/kubevirt/providerconfig.go, control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/cmca/setup.go, control-plane-operator/hostedclusterconfigoperator/controllers/drainer/setup.go, control-plane-operator/hostedclusterconfigoperator/controllers/hcpstatus/hcpstatus.go, control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/setup.go, control-plane-operator/hostedclusterconfigoperator/controllers/machine/machine.go, control-plane-operator/hostedclusterconfigoperator/controllers/machine/machine_test.go, control-plane-operator/hostedclusterconfigoperator/controllers/machine/setup.go, control-plane-operator/hostedclusterconfigoperator/controllers/node/setup.go, control-plane-operator/hostedclusterconfigoperator/controllers/nodecount/setup.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/operator/config.go
With kubevirt cluster use selectorless cloud-provider-kubevirt and reconcile endpointslices pointing to all the VMs. 
Fixes #
**Checklist**
=> HOSTEDCP-1365: kubevirt, Generate kccm lb endpointslices

api/fixtures/example.go, cmd/cluster/cluster.go, product-cli/cmd/cluster/cluster.go, product-cli/cmd/nodepool/create.go
Manual backport from https://github.com/openshift/hypershift/pull/3273
Fixes #[HOSTEDCP-1322](https://issues.redhat.com/browse/HOSTEDCP-1322)
=> [release-4.14] HOSTEDCP-1322: NodeUpgradeType defaulted by provider

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Currently, `computeClusterVersionStatus` does not update the desired image if 1) hcp is nil and 2) version status is set.
This leads to a situation where if the initial release image was invalid, the HC is blocked, even if you update the `image` later.
This moves the update of the desired image before the `return` when `hcp == nil` to ensure that the new release image is validated.
=> OCPBUGS-31415: update desired image even when HCP doesn't exist yet

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go, support/util/util.go
Allow the operator to manage a select group of hostedcluster resources that contain a specified annotation.  This feature can be useful for situations in which you want to test a new version of the operator without affecting an existing workload that is being managed by the current production-level operator.  In a dual operator setup like this, the "production" operator would be configured to ignore events for all `scope` annotated hostedclusters, while the "test" operator would ignore events for all hostedclusters that do not have the annotation.  Thus each operator would only process/reconcile hostedclusters that it manages.  The exact annotation to match in the test operator would be defined in the env var `HOSTEDCLUSTERS_SCOPE_ANNOTATION`, while the production operator wouldn't need …
=> HOSTEDCP-1513: Support annotation scoping for hostedcluster resources

api/hypershift/v1beta1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go
The key name in the ConfigMap is `tuning` and not `tuned`.
https://github.com/openshift/hypershift/blob/main/hypershift-operator/controllers/nodepool/nodepool_controller.go#L101 
Fixes #
N/A
=> NO-JIRA: docs: fixing wrong key name

control-plane-operator/controllers/hostedcontrolplane/nto/clusternodetuningoperator.go
PAO controller which is part of NTO, creates events as part of its reconciliation loop: https://github.com/openshift/cluster-node-tuning-operator/blob/master/pkg/performanceprofile/controller/performanceprofile_controller.go#L703
In order to performs operation on events, we should add the events under the role of the operator.
Fixes # [CNF-11885](https://issues.redhat.com/browse/CNF-11885)
=> CNF-11885: nto: add events resources under operator `Role`

api/hypershift/v1beta1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
Creates a new `DisableClusterAutoscalerAnnotation` set on the `HostedControlPlane` by the `hypershift-operator` when none of the `NodePools` for a particular `HostedCluster` have `spec.autoScaling` set.  When this annotation is set on the HCP, the CPO sets `replicas` on the `cluster-autoscaler` Deployment to 0.
=> OCPBUGS-14383: disable autoscaler when no nodepool requires it

docs/content/how-to/aws/deploy-aws-private-clusters.md
In the hypershift documentation, it would be helpful to provide clarification that the "ec2:DescribeInstanceTypes" policy is required. Otherwise, errors would occur in the HO logs.
```
{“level”:“error”,“ts”:“2024-04-07T12:59:39Z”,“msg”:“failed to call AWS to resolve the number of cores per node for the following EC2 instance type: m5.xlarge”,“error”:“UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:iam::301721915996:user/preserved-hypershift-ci is not authorized to perform: ec2:DescribeInstanceTypes because no identity-based policy allows the ec2:DescribeInstanceTypes action\n\tstatus code: 403, request id: 93a25aef-0936-4ce9-9d78-23c55f0aa49c”,“stacktrace”:“[github.com/openshift/hypershift/hypershift-operator/co …
```
=> NO-JIRA: update private cluster IAM policy doc

test/e2e/e2e_test.go
This addition will allow us to insert a custom annotation needed for the e2e test suite for the HostedCluster.
In particular, specify the management platform type in case of kubevirt external infra testing.
Fixes #
**Checklist**
=> NO-JIRA: [e2e test framework] Add a flag to add an annotation to HostedCluster

control-plane-operator/controllers/hostedcontrolplane/kas/auditcfg.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/auditcfg.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
Related: https://github.com/openshift/hypershift/issues/3764
I was able to test by build and running on existing ibm hypershift test cluster.
Fixes #
**Checklist**
=> OCPBUGS-31012: Disable audit-log container in kas when profile is None

support/util/imagemetadata.go, support/util/imagemetadata_test.go
Now the Hypershift operator does not ignore RegistryOverrides and the metadata inspection works as expected
Fixes #[OCPBUGS-29494](https://issues.redhat.com/browse/OCPBUGS-29494)
- PR Tested in a Baremetal/Dual Stack/Disconnected environment with this custom image: [quay.io/jparrill/hypershift:OCPBUGS-29494v7](http://quay.io/jparrill/hypershift:OCPBUGS-29494v7)
=> OCPBUGS-29494: Fix disconnected metadata inspection

control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator.go, control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/testdata/zz_fixture_TestReconcileOperatorDeployment.yaml
Set RUN_AS_USER if mgmt cluster doesn't have SCC
Fixes [STOR-1805](https://issues.redhat.com/browse/STOR-1805)
**Checklist**
=> STOR-1805: Set RUN_AS_USER if mgmt cluster doesn't have SCC

hypershift-operator/main.go, support/globalconfig/imagecontentsource.go, support/globalconfig/imagecontentsource_test.go
The registriesOverrides are now filled initially looking for ICSPs and then IDMSs, concatenating both contents in the same map
Fixes #[OCPBUGS-29466](https://issues.redhat.com/browse/OCPBUGS-29466)
=> OCPBUGS-29466: Fix ICSP and IDMS inclusion as registriesOverrides

api/hypershift/v1beta1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/config/deployment.go, support/util/util.go, support/util/util_test.go
Adds annotation to specify additional node selectors. This is needed for request serving nodes to request the corresponding size label.
Fixes #[HOSTEDCP-1524](https://issues.redhat.com/browse/HOSTEDCP-1524)
**Checklist**
=> HOSTEDCP-1524: [release-4.15] Support additional node selectors for request serving nodes

test/e2e/util/util.go
related to https://issues.redhat.com/browse/CNV-40820 
A recent kubevirt-csi change went in that causes race condition at startup. The result is kubevirt-csi crashes but eventually stabilizes. We will solve the race condition. For now we need to disable crash detection of kubevirt-csi to unblock the presubmit jobs
=> NO-JIRA: Disable kubevirt-csi crash detection in e2e

docs/content/how-to/kubevirt/configuring-network.md
Added guidelines for avoiding network CIDR collisions and DNS-related issues between hosting and guest clusters.
When creating a guest cluster, it's crucial to ensure that the hosting and guest clusters do not share the same subnet (cidr) for the cluster network otherwise guest cluster deployment will not complete successfully.
Fixes # [CNV-40622](https://issues.redhat.com//browse/CNV-40622)
**Checklist**
=> CNV-40622: Docs: Avoid cidr Collisions b/w Infra &Guest cluster

api/v1beta1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/config/deployment.go, support/util/util.go, support/util/util_test.go
Adds annotation to specify additional node selectors. This is needed for request serving nodes to request the corresponding size label.
Fixes #[HOSTEDCP-1526](https://issues.redhat.com/browse/HOSTEDCP-1526)
**Checklist**
=> HOSTEDCP-1526: [release-4.14] Support additional node selectors for request serving nodes

test/e2e/util/hypershift_framework.go
Previously, an error during `Teardown` subtest would cause the main outer test to fail directly and the subtest to succeed, which makes it difficult to identify the source of the error.
Fixes #
**Checklist**
=> NO-JIRA: fixed e2e teardown failing the outer test instead of subtest

hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
Before this, the new scheduler was not setting the proper value for subnets in the HostedCluster annotation.
Fixes #[OCPBUGS-32248](https://issues.redhat.com/browse/OCPBUGS-32248)
**Checklist**
=> OCPBUGS-32248: Replace periods with commas in subnet label value

api/hypershift/v1beta1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/nodepool_controller.go, vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go
Add [ClusterImagePolicy](https://github.com/openshift/machine-config-operator/pull/4160) CRD to valid manifests as MCO bootstraps it. This cluster-wide CRD is for sigstore signature verification. IBM ROKS deployments will require this CRD to work through hypershift.
Fixes # https://issues.redhat.com/browse/OCPNODE-2096
**Checklist**
=> OCPNODE-2096: Add ClusterImagePolicy to the list of valid config manifests

api/fixtures/example.go, api/v1alpha1/hostedcluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, api/v1beta1/hostedcluster_types.go, api/v1beta1/zz_generated.deepcopy.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/olm/deployments.go, control-plane-operator/controllers/hostedcontrolplane/olm/services.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/olm.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, product-cli/cmd/cluster/cluster.go
This is a manual backport of https://github.com/openshift/hypershift/pull/3321.
The pull request (PR) embeds the OperatorHubSpec field into the hostedcluster.Spec.Configuration API field. This allows us to disable/enable default sources in Management or Guest placement only during creation.
This functionality is also incorporated into the CLIs through a flag called . However, it's important to note that the OperatorHub capability to disable/enable individual default sources is not covered in this PR. As a result, that field will be disregarded in the CPO and HCCO reconciliation.
Original bug [OCPBUGS-25782](https://issues.redhat.com/browse/OCPBUGS-25782)
=> [release-4.14] OCPBUGS-32221: Added support for OLM Disable default sources on HC creation

hypershift-operator/controllers/scheduler/autoscaler.go, hypershift-operator/controllers/scheduler/autoscaler_test.go, hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go, hypershift-operator/controllers/scheduler/placeholders.go, hypershift-operator/main.go, support/api/scheme.go
Moves warm placeholder pods and sizing placeholder pods to a single namespace.
Adds a controller that looks at pending placeholder pods, determines a set of machinesets to scale up to satisfy the placeholders, and scales up those machinesets. Scaling down is still up to the cluster autoscaler which will eventually scale down nodes that are not being used. 
Fixes #[OCPBUGS-32496](https://issues.redhat.com/browse/OCPBUGS-32496)
**Checklist**
=> OCPBUGS-32496: Controller to assist autoscaling for placeholder nodes

docs/content/how-to/kubevirt/configuring-storage.md
Add documentation for the KubeVirt CSI driver
snapshotting feature. In particular how to map the storage classes and volume snapshot classes using
the hcp cli.
Fixes #
**Checklist**
=> ACM-11259: Add mapping documentation for KubeVirt CSI driver snaphotting

cmd/cluster/core/create.go, product-cli/cmd/cluster/aws/create.go, product-cli/cmd/cluster/cluster.go, product-cli/cmd/nodepool/create.go
Adds teh arch & multi-arch flags to HCP CLI 
Fixes [HOSTEDCP-1219](https://issues.redhat.com/browse/HOSTEDCP-1219)
**Checklist**
=> HOSTEDCP-1219: Add arch & multi-arch flags to HCP CLI

support/util/util.go
Partially reverts behavior introduced with https://github.com/openshift/hypershift/pull/3746
We need to figure out why specifying subnets results in a broken load balancer.
Fixes #OCPBUGS-30260
**Checklist**
=> OCPBUGS-30260: Ignore subnet annotations for control plane load balancers

api/hypershift/v1beta1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, test/e2e/nodepool_kv_nodeselector_test.go, test/e2e/util/util.go, vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
If the management cluster is Azure and the hosted cluster is created with the kubevirt-provider, the LB port of the kube-apiserver at the HCP can't be 6443 due to azure limitation. In such case, use port 7443 instead.
Fixes #
**Checklist**
=> NO-JIRA: Kubevirt on Azure: Change KAS LB Port to 7443
