cmd/create/cluster/cluster.go
@ironcladlou show default values in `help` output
=> cli: show default values in help output

docs/api.md
Document to keep track of the Hypershift API design
(imported from hackmd.io)
=> API reference document

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
implements https://issues.redhat.com/browse/HOSTEDCP-86
`HostedCluster` controller should not block waiting for the removal of the underlying `Cluster`.
This is hard to test due to https://issues.redhat.com/browse/HOSTEDCP-85 but can be verified like this
```
$ oc delete hostedcluster -n clusters --all
hostedcluster.hypershift.openshift.io "example-1" deleted
hostedcluster.hypershift.openshift.io "example-2" deleted
^C
[sjennings@cerebellum hypershift]$ oc get clusters -A -ojson | jq '.items[] | .metadata.deletionTimestamp'
"2021-02-17T17:13:17Z"
"2021-02-17T17:13:17Z"
```
Note the `deletionTimestamp` on the underlying clusters set at the same time
=> hypershift-operator: async Cluster delete

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
@ironcladlou includes changed from https://github.com/openshift/hypershift/pull/44 and does away with `ensureClusterDeleted`
=> hostedcluster: refactor delete

hypershift-operator/controllers/hostedcluster/manifests/clusterapi/manifests.go, hypershift-operator/controllers/hostedcluster/manifests/controlplaneoperator/manifests.go
The "just get it working" for https://issues.redhat.com/browse/HOSTEDCP-85
I will follow up with an audit to figure out if these are even needed any more
=> manifests: suffix per guest ClusterRoleBinding names with cluster name

test/e2e/quick_start_test.go
We just realized today that the `IngressController` that routes guest cluster ingress proxying has been broken for some time.  This could have been detected by the canary route tests in the `ingress-operator` of the guest cluster.
We should ensure that all the operators in the guest cluster are ready before passing the test.
This likely adds ~5-6m to the `e2e-aws` test.
=> e2e: check guest cluster operators are ready

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Looking to minimize the number of NodePort based endpoints we need to expose for the guest cluster
=> control-plane-operator: convert oauth endpoint to Route

HACKING.md, test/e2e/quick_start_test.go
Adds additional flags to e2e test to specify infra, updates Hacking doc
=> Update e2e to work with BYO infra

api/v1alpha1/groupversion_info.go, api/v1alpha1/hostedcluster_types.go
Just a general cleanup before I went modifying some of the types.  Didn't want this messing up the diff.
=> api: cleanup types

cmd/cluster/create.go, cmd/infra/aws/create_iam.go
Fixes passing the profile name from 'create iam' to 'create cluster'
=> Pass information from create iam to create cluster

api/fixtures/example.go, api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/cluster/create.go, cmd/infra/aws/iam.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/kube-apiserver/config.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/render/kube_apiserver.go, control-plane-operator/controllers/hostedcontrolplane/render/pki/openshift.go, control-plane-operator/controllers/hostedcontrolplane/render/pki/spec.go, control-plane-operator/controllers/hostedcontrolplane/render/types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/manifests/controlplaneoperator/manifests.go, hypershift-operator/controllers/hostedcluster/manifests/manifests.go
The next step in unblocking https://github.com/openshift/hypershift/pull/94
The next, and hopefully final, step will be wiring in all the Role ARNs to the various components in the guest cluster
=> wire in KAS signing key and issuer URL from IAM create

cmd/cluster/destroy.go
This commit adds a cluster deletion grace period option to the `destroy cluster`
command so that if the hostedcluster fails to be deleted for whatever reason the
infra can still be torn down to prevent leaks. The default grace period is 10
minutes, but can be configured for whatever the use case demands.
=> cli: destroy infra after cluster deletion grace period expires

cmd/cluster/dump.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/manifests/autoscaler/manifests.go, hypershift-operator/controllers/hostedcluster/manifests/clusterapi/manifests.go, hypershift-operator/controllers/hostedcluster/manifests/controlplaneoperator/manifests.go, hypershift-operator/controllers/hostedcluster/manifests/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
Modifies *Name functions to return typed resources
=> Further refactoring of HostedCluster controller

hypershift-operator/controllers/machineconfigserver/machineconfigserver_controller.go, hypershift-operator/controllers/machineconfigserver/manifests.go
This is a refactor to make the controller more consistent with the
hosted cluster controller. This commit doesn't change any behavior.
=> Refactor machine config server controller for consistency

cmd/infra/aws/ec2_sg.go
Makes `create infra` more robust by adding a retry
=> Retry lookup of security group after creation

cmd/create/create.go, cmd/nodepool/create.go
There are other features of NodePools we could control with the command i.e. autoscaling, but this is the MVP and we can expand it.
=> cmd: add create nodepool command

hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
Add support for a nodePool to manage the lifecycle of its awsMachineTemplate.
When an aws value is changed the nodePool will delete the old awsMachineTemplate, create a new one and assign it to the machineDeployment.
=> Trigger a rolling upgrade when nodePool aws values change

README.md
=> Some minor fixes and additions to the README

cmd/cluster/destroy.go, cmd/infra/aws/destroy.go
When deleting a cluster or infrastructure, retry failed deletes until
an interrupt is received. This helps backstop transient issues with
internal retry handling (e.g. AWS dependencies which need cleaned up).
=> cli: retry failed deletes

cmd/infra/aws/iam.go
Reimplementation of https://github.com/openshift/hypershift/pull/153
=> infra: Restrict roles to expected service accounts

cmd/cluster/destroy.go, test/e2e/control_plane_upgrade_test.go, test/e2e/helpers.go, test/e2e/quick_start_test.go
Reimplement some minor reliability fixes lost during the revert of https://github.com/openshift/hypershift/pull/154.
=> cli/e2e: reliability fixes

hypershift-operator/controllers/machineconfigserver/machineconfigserver_controller.go
Use ObjectKeyFromObject / ObjectKeyFromObject.String
Move from CreateOrUpdate to CreateOrPatch to simplify mcsService.Spec.Ports[0].NodePort logic
=> Add cosmetic changes to reconcileMCSServiceNodePort

cmd/infra/aws/destroy_iam.go, cmd/infra/aws/iam.go
Reviewer note: An access key is generated on each pass and we can't reuse them.  `destroy` is smart enough to remove them all.
Do we want to remove old access keys on `create` so there is only ever one?
=> make user creation idempotent

cmd/cluster/destroy.go, cmd/infra/aws/destroy.go, cmd/infra/aws/destroy_iam.go
Make destroy commands retry until they either succeed or are cancelled.
=> cli: Improve destroy retry handling

README.md, cmd/cluster/create.go, cmd/cluster/destroy.go, cmd/cluster/dump.go, cmd/create/create.go, cmd/destroy/destroy.go, cmd/dump/dump.go, cmd/infra/aws/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy.go, cmd/infra/aws/destroy_iam.go, cmd/infra/create.go, cmd/infra/create_iam.go, cmd/infra/destroy.go, cmd/infra/destroy_iam.go, cmd/install/install.go, cmd/kubeconfig/create.go, cmd/nodepool/create.go, main.go
=> Add SilenceUsage for all commands to not to print usage on error

cmd/infra/aws/iam.go
When I run `create cluster` with existing infra more that twice, I get:
```
Cannot exceed quota for AccessKeysPerUser: 2
```
This was mentioned as an outstanding question in https://github.com/openshift/hypershift/pull/178#issue-621360846 and I guess this is the answer.
This PR cleans up old access keys during infra create, even if the user already exists, since we can retrieve old access key secrets.
=> remove old access keys for existing users on create infra

control-plane-operator/controllers/hostedcontrolplane/assets/cluster-version-operator/cluster-version-operator-deployment.yaml
needed after https://github.com/openshift/cluster-version-operator/pull/481
=> CPO: update CVO deployment with empty listen

cmd/cluster/destroy.go
Before this commit, the `destroy cluster` command was incapable of deleting
infrastructure for a missing HostedCluster resource. Now, provided the user
supplies the required inputs, the command can tear down infrastructure for a
HostedCluster which doesn't exist.
=> cli: Make `destroy cluster` useful even when the hostedcluster is gone

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Impose a hard-coded 2 minute timeout for release image metadata lookups
so the reconciliation can't hang if lookups take too long. If this value
proves to be flaky we can adjust it later, but the current indefinite wait
causes destroy to hang forever if, for example, the lookup image can't
be pulled.
=> Add a hard timeout to release image metadata lookups

hypershift-operator/controllers/manifests/manifests.go
Follow up for https://github.com/openshift/hypershift/pull/203
=> Removed unused DefaultNodePool function

cmd/kubeconfig/create.go
This commit expands the `create kubeconfig` command to allow selecting a single
hostedcluster by namespace/name for rendering.
=> cli: Enable rendering a single kubeconfig for a cluster

hypershift-operator/controllers/machineconfigserver/machineconfigserver_controller.go
This drops support for 4.6 which was needing ign skew.
=> Drop 4.6 ign support

control-plane-operator/controllers/hostedcontrolplane/pki/kas.go
@ironcladlou @csrwng 
Prevents the KAS from connecting to kubelets
introduced by #200
=> fix typo in KAS and boostrapper users

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Resolves https://github.com/openshift/hypershift/issues/220
=> add support for ibmcloud config

cmd/install/assets/hypershift_operator.go, cmd/install/install.go
This commit enables integration with OCP user workload monitoring[1] by exposing
hypershift-operator metrics using a Prometheus `ServiceMonitor` resource. When
user workload monitoring is enabled, hypershift-operator metrics should be
available through the management cluster's `thanos-querier` route.
Currently the metrics are exposed insecurely because to do otherwise requires an
integration based on actively reconciling all the supporting resources within
the hypershift operator itself[2].
[1] https://docs.openshift.com/container-platform/4.7/monitoring/enabling-monitoring-for-user-defined-projects.html
[2] User workload `ServiceMonitor` resources must reference dynamically generated
secrets for token authentication.
=> Integrate hypershift-operator with user workload monitoring

control-plane-operator/controllers/hostedcontrolplane/config/deployment.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/manifests/konnectivity.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/pki/konnectivity.go, control-plane-operator/controllers/hostedcontrolplane/pki/openshift.go, control-plane-operator/main.go
part 2 of konnectivity support following https://github.com/openshift/hypershift/pull/280
=> Add konnectivity agent to guest cluster

test/e2e/helpers.go
The time to wait for various assertions (e.g. nodes or operators becoming ready)
varies quite a bit, and using fixed timeout values internally leads to
instability unless the timeouts are so long as make them basically irrelevant.
Also, conceptually, specifying a specific timeout on these assertions seems like
an implicit SLO which hasn't actually been designed or agreed upon.
This commit removes explicit fixed timeouts in favor of letting the test do all
it can up until the point where the external orchestration system (e.g. CI or
the end user) cancels the test. At the point of cancellation, if the specific
timings during the course of that run are of interest, they should be analyzed
in a metrics aggregator.
=> e2e: remove explicit fixed timeouts in test assertions

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/egresscfg.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/manifests/konnectivity.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/pki/konnectivity.go
=> Add konnectivity agent to hosted control plane

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Use cases it enables are in this note:
https://docs.google.com/document/d/1Gs7imMSyhulwxKXpwRIJH8jJqGyzz6HAXjeADkEeic0/edit#heading=h.cellft5j76ix
=> cloud provider agnostic Audit webhook support

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/egresscfg.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/pki/konnectivity.go, control-plane-operator/main.go
=> Enable konnectivity

control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/main.go
@csrwng @relyt0925 
xref
https://github.com/openshift/apiserver-network-proxy
https://github.com/openshift/release/pull/19968
=> Use OCP konnectivity images

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/ignition-configs/30-fips.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/render/types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This is straightfoward and does work, however, openvpn is not FIPS compliant and can not be made so.
https://community.openvpn.net/openvpn/ticket/725
This functionality is blocked until we can move to a FIPS compliant solution.
=> Add FIPS support

api/fixtures/example.go, cmd/cluster/create.go
=> add FIPS flag to create cluster command

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
What is the problem?
Out of the box imagestreams delivered in the openshift namespace are
failing to fetch tags.
What this does:
It syncs the pull-secret to the openshift namespace in addition to the
openshift-config namespace. This enables imagestreams in the openshift
namespace to use the cluster's pull secret.
Fixes https://github.com/openshift/hypershift/issues/347
=> Add pull secret for out of box imagestreams

api/v1alpha1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/oauth/config.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Solves: https://github.com/openshift/hypershift/issues/224
=> add ibmcloud oauth config overrides. Enables ROKS integration with IBM Cloud IAM

cmd/infra/aws/iam.go
Fixes issue in which the image registry itself cannot access the bucket created by the registry operator
=> Trust registry service account in STS policy

control-plane-operator/controllers/hostedcontrolplane/ingress/ingresscontroller.go
#381 had a bug setting the default-ingress-cert
@csrwng
=> fixup ingress cert plumbing

api/fixtures/example.go, api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Solves:
https://github.com/openshift/hypershift/issues/365
=> add suport for exposing ignition service as node port

cmd/nodepool/create.go
Adds AWS defaults for instance type, instance profile, security group id, and subnet id to avoid creating invalid nodepools.
=> hypershift create nodepool: add proper defaults for AWS nodepools

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
If the hosted cluster desired image was newer than what the hosted control plane spec and status reported, the hosted cluster may incorrectly report the rollout was completed.  The fix ensures that the hosted cluster desired image matches the hosted control plane spec and status to avoid a race condition from occuring.
=> Fix premature reporting of completed upgraded logic

test/e2e/e2e_test.go, test/e2e/scenarios/autoscaling.go, test/e2e/scenarios/control_plane_upgrade.go, test/e2e/scenarios/create_cluster.go, test/e2e/util/util.go
=> Run e2e tests in parallel

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Before this PR capi, capa and ign-server were not considered for the optimal topology and HA settings that affect critical compoments. They are added here as these are essential components for node management.
Fixes https://github.com/openshift/hypershift/issues/406.
=> Add HA topology settings for capi, capa and ign-server

cmd/install/assets/etcd/etcd.database.coreos.com_etcdclusters.yaml, control-plane-operator/controllers/hostedcontrolplane/config/constants.go, control-plane-operator/controllers/hostedcontrolplane/etcd/params.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/thirdparty/etcd/v1beta2/cluster.go, thirdparty/etcd/v1beta2/cluster.go
@csrwng @derekwaynecarr 
WIP: requires https://github.com/openshift/etcd-operator/pull/3 to merge first
=> Add priority to etcd pods

Dockerfile, Dockerfile.fast
=> switch Dockerfiles to 4.8 base

Makefile, control-plane-operator/controllers/hostedcontrolplane/config/clusterconfig.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/auditcfg.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/releaseinfo/pod_provider.go
=> Add staticcheck to verify and address failures

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Currently, creating a cluster always results in a bunch of errors from
the hosted cluster reconciler because it got a 404 trying to fetch the
hosted controlplane kubeconfig. This happens because the hosted
controlplane operator sets status.kubeconfig before that secret actually
exists, whereas the hosted controlplane operator assumes that as soon as
that field is non-nil, it exists.
=> Controlplaneoperator: Don't set status.kubeconfig before it exists

Dockerfile, Dockerfile.fast
=> Update base image to 4.9

api/v1alpha1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/main.go
=> hypershift-operator support multiple CPO version

cmd/infra/aws/ec2_sg.go
Create infra is sometimes terminating with an error because it claims
that the security group rule we are trying to create is a duplicate.
This is likely caused by retry logic in the AWS client. This change
avoids the error by ignoring an error of duplicate permission when
creating security group rules.
=> Ignore Duplicate permission error code when creating security group

control-plane-operator/controllers/hostedcontrolplane/assets/hosted-cluster-config-operator/cp-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/assets/olm/packageserver-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/cvo/params.go, control-plane-operator/controllers/hostedcontrolplane/etcd/params.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go, control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
@csrwng @jiezhao16 
fix https://issues.redhat.com/browse/HOSTEDCP-191?focusedCommentId=19063416
=> apply correct HCP component priority

control-plane-operator/controllers/hostedcontrolplane/assets/cluster-bootstrap/cluster-infrastructure-02-config.yaml, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/render/manifests_test.go, control-plane-operator/controllers/hostedcontrolplane/render/types.go
Ref https://issues.redhat.com/browse/HOSTEDCP-148
/cc @csrwng
=> Add AWS ResourceTags from HostedCluster to clusters Infrastructure

test/e2e/util/util.go
Until https://issues.redhat.com/browse/HOSTEDCP-238 is resolved
=> EnsureNoCrashingPods: Add exception for packageserver

Makefile
Enables more flexible local development workflows.
=> Make binary output dir configurable

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
Fix spurious KAS updates by setting all defaultable fields and being careful with assignments.
=> Fix spurious KAS updates

cmd/install/assets/hypershift_operator.go
Set generic name for hypershift recording rules group.
=> Split recording rules groups for operator and control plane

cmd/install/assets/hypershift_operator.go, cmd/install/install.go
More AWS Private cluster support work.
It adds an optional `--aws-creds` flag to `hypershift install`.
The `hypershift-operator` will need AWS credentials sufficient to create Endpoint Services in AWS.
These creds will be plumbed into the controller that creates the Endpoint Service in AWS in response to `AWSEndpointService` creation in the next PR.
If you don't pass `aws-creds`, the `hypershift-operator-creds` secret `credentials` key is just empty.  We can then use this as an indicator on whether or not to start the `AWSEndpointService` controller in the `hypershift-operator`.  If the `credentials` key is empty, don't start the controller.
=> Add aws-creds flag to hypershift-operator

Dockerfile, Makefile, api/fixtures/example.go, cmd/cluster/aws/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/destroy_iam.go, cmd/infra/aws/iam.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kcm/config.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/util/util.go, hypershift-operator/main.go, token-minter/main.go
@csrwng @derekwaynecarr @enxebre 
This PR switches the `kube-controller-manager` and `capa-controller-manager` in the HCP to use IAM Roles and tokens instead of Users and access keys.  This makes hypershift fully STS on AWS with no remaining Users.
There is a new small `token-minter` binary introduced that contacts the guest API server and mints tokens for service accounts that exist in the guest cluster.  This binary is run as an init container on the components that require AWS access.  Currently the token from the API server is long lived with a 1y expiration.  The underlying STS token will be renewed transparently by AWS SDK every hour.  In other words, the service account token can be used to get new STS tokens for up to 1y.  Currently the only method of rotation is the restart the …
=> Switch HCP components from IAM users to roles

cmd/cluster/aws/dump.go
Currently, CI artifacts do not include the kube objects and pod logs
from the Hypershift namespace, which makes diagnosing issues where
something in the Hypershift operator went wrong difficult.
=> E2E: Also dump objects and logs from Hypershift namespace

cmd/install/assets/hypershift_operator.go
This PR adds readiness and liveness probes to hypershift operator.
=> added liveness/readiness probes for hypershift operator

docs/content/quickstart.md
Updates instructions for installing hypershift to reflect the latest
state.
Adds instructions for creating and scaling nodepools.
=> Update QuickStart instructions

Makefile
Should help to debug why "verify" fails here https://github.com/openshift/release/pull/23848
=> Print git status output when verify fails

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Needs https://github.com/openshift/release/pull/23913
=> Update CAPA image to come from internal openshift CI

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
`controlPlaneEndpoint` is not resolvable/reachable from the management cluster for private clusters.
This PR switches the OIDC controller to read from the HCP KAS over the service network rather than using the `controlPlaneEndpoint`, which is the endpoint _nodes_ use to contact the KAS.
=> Switch OIDC controller to use service network to read from KAS

api/fixtures/example.go, api/fixtures/example_aws.go
Refactored the fixtures.ExampleResources to adopt new platform easily
- Introduced the interfaces
- separated the aws code into different file
=> Refactor the ExampleResources

docs/content/developers/how-to/onboard-a-platform.md, hypershift-operator/controllers/hostedcluster/internal/platform/platform.go
=> Improve platforms docs

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go
=> Scope down ign server rbac

availability-prober/main.go, cmd/version/version.go, control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kas/ibmcloud_kms.go, control-plane-operator/controllers/hostedcontrolplane/mcs/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-collect-profiles.serviceaccount.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/olm-collect-profiles.go, control-plane-operator/controllers/hostedcontrolplane/pki/cert.go, control-plane-operator/controllers/hostedcontrolplane/pki/etcd.go, control-plane-operator/controllers/hostedcontrolplane/pki/ingress.go, control-plane-operator/controllers/hostedcontrolplane/pki/kas.go, control-plane-operator/controllers/hostedcontrolplane/pki/konnectivity.go, control-plane-operator/controllers/hostedcontrolplane/pki/mcs.go, control-plane-operator/controllers/hostedcontrolplane/pki/oauth.go, control-plane-operator/controllers/hostedcontrolplane/pki/olm.go, control-plane-operator/controllers/hostedcontrolplane/pki/openshift.go, control-plane-operator/controllers/hostedcontrolplane/render/funcs.go, hosted-cluster-config-operator/controllers/cmca/configmap_observer.go, hosted-cluster-config-operator/controllers/cmca/setup.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/platform/aws/controller.go, ignition-server/controllers/tokensecret_controller.go, konnectivity-socks5-proxy/main.go, support/globalconfig/globalconfig.go
Mostly:
* Close http bodies (otherwise connctions are leaked)
* Remove unusued function parameters
* Remove unneccesary conversions
* Remove deadcode
This change shouldn't result in any change in behavior other than not
leaking connections anymore.
=> Fix some issues found through linting

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
We currently issue a lot of patch requests because we use Serverside
Apply for managing objects that are defined as manifests. This change
replaces that with CreateOrUpdate usage, effectively trading load on the
APIServer for a presumambly smaller increase in load in the Controlplane
operator.
=> Reduce patch requests by replacing SSA with CreateOrUpdate

cmd/install/assets/hypershift_operator.go, cmd/install/install.go
Remove mount and secret from hypershift deployment, when not provided.
https://github.com/openshift/hypershift/issues/651
=> hypershift creds mount optional

docs/Dockerfile, docs/content/quickstart.md, docs/mkdocs.yml
This commit makes several updates to the quickstart guide for clarity
and accuracy.
=> docs: Update the quickstart guide

control-plane-operator/main.go
Private clusters regressed by #689.  This is effectively a partial revert of that but only for IngressControllers and Services.
=> Make ingresscontrollers and services uncached to fix private clusters

docs/mkdocs.yml
=> Fix edit_uri for docs

hosted-cluster-config-operator/controllers/resources/resources.go
The registry should not be consistently reconciled for IBM Cloud: IBM Cloud follows a strategy of initializing once and than allowing the user to make changes as they see fit afterwards. That initialization is handled by the managed service automation that wraps hypershift. Therefore the reconciliation code path in general is not needed
=> remove reconciliation of registry resource for ibmcloud

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, support/globalconfig/infrastructure.go
Drop unnecessary platform check.
=> Drop unnecessary platform check

control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
Fixes the name of the oauth server's main container
=> Fix oauth server container name

cmd/infra/aws/ec2.go
Adds a retry to the function that creates the s3 vpc endpoint for infra.
Uses a single backoff for any retries and lower case comparison for AWS
error codes due to inconsistency in error code case.
=> create infra: retry creating s3 vpc endpoint

hypershift-operator/controllers/nodepool/nodepool_controller.go
Drop exclude drain annotation from Machines
=> Drop exclude drain annotation from Machines

cmd/infra/aws/destroy.go
It already destroys endpoints, so nothing to do there.
Ref https://issues.redhat.com/browse/HOSTEDCP-287
=> AWS infra destroy: Also destroy endpoint services

cmd/infra/aws/iam.go, docs/content/how-to/deploy-aws-private-clusters.md
needed after https://github.com/openshift/hypershift/pull/786
=> add ec2 CreateTags to roles

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Currently, there's a race condition between the control-plane-operator removing the HostedControlPlane CRD and the hypershift operator removing the cluster's namespace that the control-plane-operator lives in on deletion. When that occurs the HostedControlPlane CRD will remain and the namespace will never terminate. Examples below:
```
NAME                           STATUS        AGE
master-prtesting410-61180717   Terminating   12d
master-prtesting410-61182308   Terminating   12d
master-prtesting410-61346672   Terminating   8d
master-prtesting410-61365648   Terminating   8d
master-prtesting410-61583391   Terminating   9h
master-prtesting48-61266069    Terminating   10d
master-prtesting48-61533600    Terminating   2d3h
master-prtesting49-60560414    Terminating   24d …
```
=> wait for deletion of hostedControlPlane CRD before removing namespace

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
This should fix some CI issues we are seeing caused by the `AWSEndpointServiceReconciler` in the CPO operating on old `AWSEndpointService` status and creating more than one AWS Endpoint for a particular `AWSEndpointService` resource.
In the case the `status.endpointID` is not set, we query AWS for an Endpoint that matches tags on cluster InfraID and AWSEndpointService name.  If one is found, then we adopt it vs the old behavior of creating a new one, resulting in an orphaned AWS Endpoint.
Test procedure:
* create HC and wait for AWSEndpointServices to be fully created
* scale down HO
* scale down CPO
* edit AWSEndpointServices to remove finalizers
* delete AWSEndpointServices
* scale up HO (which will scale up CPO)
* AWSEndpointServices should be reconstructed with the exact same status …
=> cpo: awsprivatelink: adopt existing Endpoints by tag

cmd/infra/aws/route53.go
Always log something, rather than only logging when there was no error
to make sure issues can be debugged.
=> Improve logging for route 53 record clean up

support/thirdparty/oc/pkg/cli/image/manifest/manifest.go
This allows to install multiplatform image
=> Allow installing multiplatform ocp image

api/v1alpha1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/content/reference/api.md
=> add API doc for instance profile field

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Currently the HO makes an inter-namespace HTTP request again the guest KAS in the HCP namespace in order to get the OIDC documents and mirror them to an s3 bucket.
We are looking to prohibit inter-namespace network access for security.  Additionally, we want to be able to run components outside the cluster for development purposes and currently the HO must run in the cluster because it accesses the KAS over the service network.
This PR fixes both of those issues by having the HO create the discovery documents on its own from the service account signing key that resides in a secret in the HCP namespace.
=> oidc: generate OIDC documents directly

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Before this commit, the hosted cluster controller treated a missing
hostedcluster the same as a deleted one. This is incorrect, because any cache or
other transient weirdness from the apiserver for a hostedcluster which actually
still exists will result in that cluster being accidentally destroyed. Absence
of the hostedcluster being reconciled isn't the same as deletion intent.
This commit fixes the problem by short-circuiting reconciliation if the
requested hostedcluster doesn't exist. If on a subsequent event the resource can
be fetched, we'll reconcile it as usual. If we continue to get queued events for
a resource the apiserver says isn't found, that could be some other cache or
connectivity issue we want to surface and resolve. What we should not do is
infer a deletion event from it.
=> Prevent accidental cluster deletion

cmd/cluster/none/create.go
follow on to https://github.com/openshift/hypershift/pull/821
=> create none honors base-domain

token-minter/main.go
Before this commit, most failure conditions resulted in the token-minter process
exiting, which can cause process restart churn under transient conditions like
the API server not yet being available or a kubeconfig secret not yet being
created.
This commit makes the process always retry failed operations until signalled to
quit. In addition, the process now uses the `log` package so log output contains
timestamps.
=> Make token-minter more resilient to failures

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go, docs/content/how-to/oauth.md, docs/mkdocs.yml
make kubeadmin login optional from IBM Cloud deployments
https://github.com/openshift/hypershift/issues/718
=> Make kubeadmin optional

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
Looking at the ingress operator code:
https://github.com/openshift/cluster-ingress-operator/blob/master/cmd/ingress-operator/start.go#L74
The only possible "web probe" to call is the prometheus endpoint hence why I added this to be the initial probe for readiness and liveliness. In the future if a probe option was exposed to have a health endpoint we could move to using that.
It's critical to have liveness and readiness probes on components in the controlplane to be able to account and monitor for oddities in the programs over time (even if it seems like the program is setup to "never fail").
We should brainstorm if there's some clever way to do this in the token minter as well if that is part of operations
=> add health probes to ingress operator to ensure it is functioning

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
The log is specific to each Reconcile() invocation, so we can not store
it persistently, as multiple concurrent Reconciles will stomp each
others logger.
This happens to not be a problem right now, because we run with only one
worker, but that is something we likely want to change to improve
throughput.
/cc @csrwng
=> Hostedcluster controller: Don't store log on Reconciler

.gitignore, Makefile, contrib/cleanzones/main.go
Utility for cleaning up leaked hosted zones and records in CI
=> add cleanzones util to contrib

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
=> Allow custom apiserver port in network policy

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/networkpolicy/manifests.go
=> Allow monitoring access to HCP

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
fixes regression from https://github.com/openshift/hypershift/pull/895
=> fix monitoring network policy name

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go
Right now a pods service account is only getting created with one CA at a time: this will not work with CA rotation. The pod's serviceaccount CA field should be populated with the combined CA so that CA rotation can be properly supported (allows adding multiple CAs to the trust store at a given period of time)
Key changes:
In a pod with a service account
/var/run/secrets/kubernetes.io/ca.crt use to only have one root ca cert. Now it will include the combined ca bundle to ensure all active CAs are accounted for
The service-ca.crt in a pods service account use to only have the openshift-signer cert. It will now have the combinedCA bundle to ensure all CAs are accounted for …
=> ensure hostedconfigoperator kube-controller-manager CA syncer uses combined ca to properly support ca rotation

test/e2e/util/fixture.go
Before this commit, some cluster dumps (e.g. the pre and post teardown dumps)
were going to the same artifacts directory, overwriting the prior contents.
This commit refactors the e2e cluster fixture so that every cluster dump is kept
separate by test name so that it's easier to associate the dumped resources with
the failure condition that produced them.
=> e2e: ensure cluster dumps are separated by test

go.mod, go.sum, vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml, vendor/github.com/openshift/api/config/v1/types_feature.go, vendor/github.com/openshift/api/config/v1/types_infrastructure.go, vendor/modules.txt
/cc @csrwng 
Likely needs https://github.com/openshift/release/pull/25568 to merge first
/hold
=> Get current feature gate config by updating o/api

docs/content/how-to/distribute-hosted-cluster-workloads.md
Follow up for https://github.com/openshift/hypershift/pull/918
Fixes #
**Checklist**
=> Improve docs for distribute Hosted Cluster workloads

docs/content/contribute/onboard-a-platform.md
Fixes a broken link to a Go package.
=> docs: Fix broken link

cmd/install/assets/hypershift_operator.go, docs/content/how-to/distribute-hosted-cluster-workloads.md, support/config/constants.go
Follow up for https://github.com/openshift/hypershift/pull/919
Ref https://issues.redhat.com/browse/HOSTEDCP-309
**Checklist**
=> Add priority classes to Distribute Hosted Cluster workloads doc

Dockerfile.fast, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-certified.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-community.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-marketplace.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-operators.deployment.yaml
Just bumping some references to 4.9 assets to 4.10
Fixes #
**Checklist**
=> bump 4.9 refs to 4.10

docs/content/how-to/distribute-hosted-cluster-workloads.md
Before this was rendering inline the item list
Fixes #
**Checklist**
=> Fix Priority section rendering

docs/content/how-to/restart-control-plane-components.md
Bulleted list is malformed and the content can be made more consise.
Fixes #
**Checklist**
=> clean up docs for restarting control plane

cmd/install/assets/hypershift_operator.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go
Added Resource Request objects to components missing them (hypershift-operator, machine-config-server, openshift-oauth-apiserver, control-plane-operator)
Fixes #650 
**Checklist**
=> Added Resource Request objects to components missing them

support/upsert/loopdetector.go
=> Skip endpointservices in the loopdetector

cmd/nodepool/aws/create.go
Switching to zone-suffixed names for NodePools in AWS broke an assumption about NodePool naming in the code for `create nodepool aws`.  This PR fixes it by not assuming the name of the NodePool, but just searching for a NodePool belonging to the HostedCluster.
Fixes #
**Checklist**
=> fix nodepool lookup in create nodepool aws

docs/content/how-to/upgrades.md, docs/mkdocs.yml
Add docs for upgrades
Fixes #
**Checklist**
=> Add docs for upgrades

cmd/infra/aws/ec2.go
We are seeing occasional errors in the NAT gateway creation because the
subnet doesn't exist yet. This change makes us fetch the subnet
repeatedly after creating it until we can successfully retrieve it to
avoid that.
Fixes #
**Checklist**
=> AWS infra: Wait for subnet after creating it

go.mod, go.sum, test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/util/util.go, vendor/github.com/jpillora/backoff/LICENSE, vendor/github.com/jpillora/backoff/README.md, vendor/github.com/jpillora/backoff/backoff.go, vendor/github.com/mwitkow/go-conntrack/.gitignore, vendor/github.com/mwitkow/go-conntrack/.travis.yml, vendor/github.com/mwitkow/go-conntrack/LICENSE, vendor/github.com/mwitkow/go-conntrack/README.md, vendor/github.com/mwitkow/go-conntrack/dialer_reporter.go, vendor/github.com/mwitkow/go-conntrack/dialer_wrapper.go, vendor/github.com/mwitkow/go-conntrack/listener_reporter.go, vendor/github.com/mwitkow/go-conntrack/listener_wrapper.go, vendor/github.com/prometheus/client_golang/api/client.go, vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go, vendor/github.com/prometheus/common/config/config.go, vendor/github.com/prometheus/common/config/http_config.go, vendor/golang.org/x/net/internal/timeseries/timeseries.go, vendor/golang.org/x/net/trace/events.go, vendor/golang.org/x/net/trace/histogram.go, vendor/golang.org/x/net/trace/trace.go, vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go, vendor/modules.txt
Now, that we've done the work to root out causes of high API activity, lets seal against further regression.
This introduces a check to ensure that the CPO and HO don't go over a certain read/mutate budget
Fixes #
**Checklist**
=> e2e: add API call budget check

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
Only aws needs the token minter sidecar, don't add it on other
platforms.
Fixes #
**Checklist**
=> Only add the token-minter sidecar to the ingressoperator when on AWS

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go, control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go, control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, support/util/cloudprovidercreds.go, test/e2e/control_plane_upgrade_test.go, test/e2e/util/util.go
Follow up to https://github.com/openshift/hypershift/pull/1051 to make sure none of the HCP pods run as `BestEffort` and we have scheduler accounting for ever container in the HCP.
Fixes #
**Checklist**
=> add resource requests to sidecars and e2e test to prevent regression

control-plane-operator/controllers/hostedcontrolplane/cloud/azure/azure.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Clarify some context for azure cloud config funcs
Fixes #
**Checklist**
=> Add comments on Azure cloud config funcs

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
https://github.com/openshift/hypershift/pull/1039 introduced unprotected `Delete()` on new `Roles` and `RoleBindings`.
Fixes #
**Checklist**
=> fix unchecked deletes on CPO RBAC resources for ingress

ignition-server/README.md
Set righ ttl in ign server
Fixes #
**Checklist**
=> Fix ign server docs

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/deployment.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-certified.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-community.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-operator-deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-marketplace.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-operators.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-operator-deployment.yaml
=> No automount service tokens

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This reduces the leader election frequencies of components that leader elect in the management cluster to the centralized API Server of that cluster. At scale: all these components end up aggregating requests to the API Server and if not reduced appropriately it can cause substantial load on both the etcd database and apiserver memory/cpu usage. The default values previously triggered election updates every 2 seconds. This pr moves those to be 15 seconds which should provide significant alleviation of the pressure the apiserver is experiencing at max scale (440 clusters in a management cluster).
LeaderElectionReleaseOnCancel supporting details:
ClusterAutoscaler does specify it: https://github.com/openshift/kubernetes-autoscaler/blob/release-4.10/cluster-autoscaler/main.go#L453
No …
=> reduce frequency of leader election for components in the management cluster

ignition-server/main.go
This makes the ignition server dynamically reload its serving cert when
it changes. Sample output after deleting the cert secret to force a
recreation:
```
{"level":"info","ts":"2022-03-03T16:09:38Z","logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
{"level":"debug","ts":"2022-03-03T16:16:36Z","logger":"controller-runtime.certwatcher","msg":"certificate event","event":"\"/var/run/secrets/ignition/serving-cert/tls.key\": REMOVE"}
{"level":"error","ts":"2022-03-03T16:16:36Z","logger":"controller-runtime.certwatcher","msg":"error re-reading certificate","error":"tls: failed to find any PEM data in certificate input","stacktrace":"sigs.k8s.io/controller-runtime/pkg/certwatcher.(*CertWatcher).handleEvent\n\t/home/alvaro/git/golang/src/github.com/openshift/hypershif …
```
=> Ignition server: Dynamically reload serving cert

docs/content/how-to/cluster-configuration.md, docs/mkdocs.yml
Adds general documentation for configuration that should be embedded
in the HostedCluster resource.
Fixes #[HOSTEDCP-305](https://issues.redhat.com/browse/HOSTEDCP-305)
**Checklist**
=> Cluster configuration documentation

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
The conformance tests expect this to exist for Azure and will fail to
start if it doesn't:
https://github.com/openshift/origin/blob/625733dd1ce7ebf40c3dd0abd693f7bb54f2d580/test/extended/util/cluster/cluster.go#L186
The config does not contain any secret information, so this should be
fine.
Fixes #
**Checklist**
=> Azure: Deploy cloud-config into guest clusters to fix e2e

docs/content/reference/multi-platform-support.md, docs/mkdocs.yml
Add docs for multi platform support
Fixes #
**Checklist**
=> Add docs for multi platform support

api/fixtures/example.go, api/v1alpha1/nodepool_types.go, cmd/cluster/azure/create.go, cmd/cluster/core/create.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/nodepool/azure.go
Ref https://issues.redhat.com/browse/HOSTEDCP-323
Fixes #
**Checklist**
=> Azure: Make the rootdisksize on nodepool configurable

cmd/infra/azure/create.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Signed-off-by: Joshua Packer <jpacker@redhat.com>
Fixes typo in the name of the Azure Private DNS entry
NA
**Checklist**
=> Fix type in azurecluser for Private DNS name

control-plane-operator/controllers/hostedcontrolplane/kas/params.go
this adds an https prefix to the url for proper redirects
Fixes #
**Checklist**
=> add https prefix for proper redirects of console url

cmd/cluster/core/dump.go
So the question "Did nodes join this cluster" can be answered easily,
rather than having to infer it from "Is there a running pod somwhere".
Fixes #
**Checklist**
=> Dump: Dump guest cluster nodes

Makefile
=> Run unitests with racedetector and -count=25 to detect flakes

.gitleaks.toml, control-plane-operator/controllers/hostedcontrolplane/pki/ca.go, control-plane-operator/controllers/hostedcontrolplane/pki/cert_test.go, control-plane-operator/controllers/hostedcontrolplane/pki/sa.go, control-plane-operator/controllers/hostedcontrolplane/pki/util.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/certs/tls.go, support/certs/tls_test.go
These are computationally cheaper to generate and use and more secure
and smaller. They are also FIPS-compliant[0].
Compatibility with exiting RSA CAs is retained.
Due to lacking fips-compliance we can not use ed25519, as of time of
writing they are only proposed for that: [1].
For comparison:
Previously:
```
go test -race -count=5 ./control-plane-operator/controllers/hostedcontrolplane/pki/
ok github.com/openshift/hypershift/control-plane-operator/controllers/hostedcontrolplane/pki 25.986s
```
With this change:
```
go test -race -count=5 ./control-plane-operator/controllers/hostedcontrolplane/pki/
ok      github.com/openshift/hypershift/control-plane-operator/controllers/hostedcontrolplane/pki       6.939s
```
[0]: https://csrc.nist.gov/publications/detail/fips/186/4/final
[1]: …
=> PKI: Use ECDSA keys by default 

docs/content/how-to/pause-reconciliation.md
Fix typo in how to pause reconciliation doc.
**Checklist**
=> Fix typo in how to pause reconciliation doc

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, cmd/install/assets/hypershift_operator.go, control-plane-operator/controllers/hostedcontrolplane/cvo/params.go, control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/kcm/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/oapi/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/ocm/servicemonitor.go, control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go, docs/content/how-to/pause-reconciliation.md, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/internal/platform/agent/agent.go, support/util/metrics.go
https://github.com/openshift/hypershift/pull/1151 broke 4.10 CPO working with a HO from main, because it doesn't set the now required clusterID parameter.
/cc @csrwng 
Fixes #
**Checklist**
=> [release-4.10] Forward from main

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
This makes it possible for the control plane operator to work with
future versions of the HostedControlPlane CRD that contain required
fields that it's not aware of.
Using MergeFromWithOptimisticLock option enables similar semantics to
the update operation, ensuring that we update a known resourceVersion
of the resource.
**Checklist**
=> Use patch instead of update when updating HCP status and finalizers

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/manifests/clusterapi/manifests.go
=> Delete Cluster API Cluster Role binding

api/fixtures/example.go
Currently `hypershift create cluster aws` with the `--external-dns-domain` flag set will set `hostname` on the `LoadBalancer` and `Route` publishing strategies, even if the `endpointAccess` is private and the hostname should not be set.
The PR fixes this by:
- If `endpointAccess` is not Private, hostname is set on the `APIServer` and `OAuthServer` services
- If `endpointAccess is Public, hostname is set on `Konnectivity` and `Ignition`
This needs to go in before https://github.com/openshift/hypershift/pull/1163
Fixes #
**Checklist**
=> fix AWS HostedCluster fixture to set hostname in alignment with endpointAccess

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/util/pausereconcile.go, support/util/pausereconcile_test.go
Trigger reconcile when paused time is up
ref https://issues.redhat.com/browse/HOSTEDCP-364
**Checklist**
=> Trigger reconcile when paused time is up

Makefile
Follow up to https://github.com/openshift/hypershift/pull/1149
Fixes #
**Checklist**
=> add external-dns flags to CI install make target

cmd/cluster/core/dump.go
Currently, dump just drops a lot of files. This is useful for browsing
them in the CI job output, but terrible for downloading them for local
inspection, as downloading a lot of files is extremely slow, even if the
files aren't big.
This change makes us always create an archive of the dump to not require
extending every CI job to do this manually.
Fixes #
**Checklist**
=> Dump: Always create an archive

docs/content/how-to/aws/deploy-aws-private-clusters.md, docs/content/how-to/external-dns.md, docs/mkdocs.yml
Docs for DNS indirection
Fixes #
**Checklist**
=> docs for DNS indirection

control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-operator-deployment.yaml
The single-hyphen flags do not work anymore due to
https://github.com/operator-framework/operator-lifecycle-manager/pull/2362
Fixes #
**Checklist**
=> Fix CPO to work with 4.11

cmd/infra/aws/ec2.go
Before this commit, EIP tagging failures resulting from the EIP not
being found after the EIP was successfully created led to infra creation
failing overall because the tagging operation was not retried.
This commit adds retry logic to EIP tagging to account for the case when
EIP creation succeeds but tagging fails because the AWS tagging API doesn't
yet see the new EIP.
=> Retry EIP tagging failures during infra creation

cmd/install/assets/hypershift_operator.go, cmd/install/install.go, docs/content/how-to/distribute-hosted-cluster-workloads.md, hack/app-sre/saas_template.yaml
=> Hypershift operator: Give a priority that is higher than any controlplane component

hypershift-operator/controllers/nodepool/nodepool_controller.go
Before this commit, the `ValidAMI=True` condition was applied to AWS NodePools
which specified user-defined AMIs, which was misleading because those AMIs are
not actually validated by HyperShift.
This commit removes the `ValidAMI` condition entirely from AWS NodePools which
declare user-specified AMIs, since they can't be validated.
Fixes https://issues.redhat.com/browse/HOSTEDCP-369
=> Remove `ValidAMI` AWS NodePool condition when AMI is user-defined

docs/content/getting-started.md, docs/content/how-to/debug-nodes.md, docs/mkdocs.yml
Documents some tools that are available in our code base that can help
understanding why nodes are not able to join a cluster.
Also adds some fixes to the getting started documentation.
**Checklist**
=> Add node troubleshooting documentation

hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/inplace_test.go, hypershift-operator/controllers/nodepool/manifests.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
This is still gated by validateManagement which prevents this logic from ever running.
Upcoming PRs will drop the gating validation and will complete the in place upgrade logic to run pods in the guest cluster.
Fixes #
**Checklist**
=> Introduce logic to accommodate in place upgrades.

control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/oauth/route.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Before this PR, the `route.spec.host` field associated with a given
`hostedcluster.spec.services[].route` value was being defaulted by OCP and then
later overrwritten with an empty string on subsequent reconcile loops. This is
fundamentally a side effect of a violation of the immutability constraint on the
`hostname` field.
To fix the issue, this PR refactors the relevant Route reconciliation code to
compute and set the `route.spec.host` field only during the creation of the
Route resource, which enforces the immutability constraint and resolves the side
effect.
The bug was introduced by #1220
Problem was discovered by https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-e2e-aws-periodic/1511947085056839680
=> Enforce hostedcluster service route immutability constraints

cmd/infra/aws/destroy.go
VPCs are building up because `destroy infra aws` currently only removes classic ELBs via ELBv1 API.  The ELBv2 interface lists NLB.  The PR adds a removal path for NLBs.
There is also a drastic cleanup in dependency error logging.
New example output
```
./bin/hypershift destroy infra aws --aws-creds=$HOME/hypershift/aws-creds --infra-id=sjenning-dev --region=us-west-1 --base-domain=hypershift.sjennings.me
2022-04-12T23:01:09-05:00       INFO    Detached internet gateway from VPC      {"gateway id": "igw-016b2a17ae4c68fbb", "vpc": "vpc-0e0a46a3513d23cd3"}
2022-04-12T23:01:09-05:00       INFO    Deleted internet gateway        {"id": "igw-016b2a17ae4c68fbb"}
2022-04-12T23:01:11-05:00       INFO    Deleted VPC endpoints   {"IDs": …
```
=> destroy infra aws: delete network LBs and reduce dependency error noise

support/globalconfig/network.go
This is needed to fix a deadlock in the networking stack when using a
proxy:
* The networking stack needs to have a proxy configured to come up and
will like everything else use .status for that
* The proxyconfig controller only populates the proxy status after the
network status is set ([0], [1]), which will never happen if the
network doesn't come up
[0]: https://github.com/openshift/cluster-network-operator/blob/f1297ed7b53010813b13fe0c5cd2334aa9f53c3b/pkg/util/proxyconfig/no_proxy.go#L76-L82
[1]: https://github.com/openshift/cluster-network-operator/blob/f1297ed7b53010813b13fe0c5cd2334aa9f53c3b/pkg/util/proxyconfig/no_proxy.go#L107-L113
**Which issue(s) this PR fixes** *(optional, use `fixes …
=> Set network status if empty

test/e2e/create_cluster_test.go
This PR re-adds the `TestClusterCreate` test in the e2e suite.
The original rationale for removing it was that it was a subset of `TestUpgradeControlPlane`.  However, this is not exactly true as `TestUpgradeControlPlane` _creates_ the cluster with the existing hypershift code and then _upgrades_ to the code under test. There is no test that ensures that the code under test can initially create a cluster.
Additionally we have some situations where we break upgrade compatibility against pre-release versions of OCP.  The work to move the CNO into the management cluster is an example.  Such a change will always fail the upgrade test, but should pass a create test like the one being reintroduced in this PR.
**Which issue(s) this PR fixes** *(optional, …
=> e2e: add AWS cluster create test

api/fixtures/example.go, api/v1alpha1/hostedcluster_types.go, cmd/cluster/cluster.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/cno.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
Just a rebase of https://github.com/openshift/hypershift/pull/1101 while @kyrtapz is on vacation.
=> Move CNO into management cluster / add OVN to types

api/v1alpha1/hostedcluster_types.go, cmd/cluster/cluster.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, hack/app-sre/saas_template.yaml
Signed-off-by: Zenghui Shi <zshi@redhat.com>
=> Use OVNKubernetes as default network type

control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Otherwise it doesn't work in a proxy setup.
Fixes #
**Checklist**
=> Konnektivity: Set proxy env vars

cmd/cluster/cluster.go, cmd/cluster/core/create.go
=> Default network to SDN if minor < 11

cmd/cluster/core/create.go, cmd/cluster/core/create_test.go, support/releaseinfo/fake/fake.go
Addresses https://github.com/openshift/hypershift/pull/1271#issuecomment-1099537376
/cc @enxebre 
Fixes #
**Checklist**
=> Add tests for network defaulting

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, hypershift-operator/controllers/platform/aws/controller.go
For a normal `AWSEndpointService` resource, we expect to see ~8 updates to the resource
CPO creates
CPO adds finalizer
HO adds finalizer
HO adds subnetIDs to spec
HO updates status EndpointService is not available (waiting on LB)
HO updates status EndpointService is available
CPO updates status Endpoint not yet available (delay and ES being available)
CPO updates status Endpoint is available
On delete, we expect to see 4 updates
HO subnetID removal as a results of `cluster` deletion
HO deletes
CPO finalizer removal
HO finalizer removal
There will be some 409 conflicts sometimes as controllers race but that should be minimal.
Thus in a periodic job with 9 HCs and 2 `AWSEndpointServices` per HC, we expect to see about 12 x 2 x 9 = 216 mutating calls …
=> avoid no-op status updates to AWSEndpointServices

.gitignore, contrib/admission-tracer/Dockerfile, contrib/admission-tracer/Makefile, contrib/admission-tracer/main.go, contrib/admission-tracer/manifests/deployment.yaml, contrib/admission-tracer/manifests/service.yaml, contrib/admission-tracer/manifests/validatingwebhookconfiguration.yaml
This tool registers as a webhook for AWSEndpointServices and will log every operation with a diff on updates.
Fixes #
**Checklist**
=> contrib: admission-tracer for API call tracing

.ci-operator.yaml
=> Use go 1.18 for CI builds

test/e2e/util/util.go
Help with debugging timeout flakes in CI, so we can see if the duration for steps are approaching their timeout.
Fixes #
**Checklist**
=> e2e: report elapsed time for each test step

ignition-server/cmd/start.go
The defaulting was incorrect
Fixes #
**Checklist**
=> Ignition server: Actually use workdir

control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/kas/aws_kms.go, control-plane-operator/controllers/hostedcontrolplane/kas/ibmcloud_kms.go, control-plane-operator/controllers/hostedcontrolplane/kas/portieries.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-certified.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-community.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-marketplace.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-operators.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go, control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/reconcile.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go, hypershift-operator/controllers/hostedcluster/internal/platform/powervs/powervs.go, support/util/cloudprovidercreds.go, support/util/containers.go, test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/util/util.go
Ref https://issues.redhat.com/browse/HOSTEDCP-330
Fixes #
**Checklist**
=> Ensure that everything uses imagePullPolicy IfNotPresent for resiliency

test/e2e/util/dump/copy-machine-journals.sh, test/e2e/util/dump/journals.go
Fix flakiness with journal dump by retrying ssh and scp commands.
Outputs a dump of ec2 instances in the case that the dump fails for
further debugging.
**Checklist**
=> Add retries and debug output to journal dump

cmd/infra/aws/ec2.go
Retries creating a NAT gateway when the subnet used for the NAT gateway
is still creating.
Prevents a failure to create infrastructure like:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_hypershift/1327/pull-ci-openshift-hypershift-main-e2e-aws-nested/1519742692798500864
**Checklist**
=> Retry NAT Gateway creation

test/e2e/e2e_test.go
=> E2E: Allow configuring a SSH key

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Enforce pull policy for all capi providers
Fixes #
**Checklist**
=> Enforce pull policy for all capi providers

cmd/infra/aws/route53.go
Ignition on the nodes negatively caches the ignition endpoint DNS since the nodes can boot before all the PrivateLink infra is set up and the DNS names for the `hypershift.local` zone can be populated.
This PR sets the Minimum field in the SOA record value to 60 (seconds) to prevent long negative caching delays.
In my observations, this should reduce overall cluster rollout time by ~3m (~20%).
Fixes #
**Checklist**
=> create infra aws: set minimum on private zone SOA records

cmd/cluster/core/dump.go
This should aid in debugging scc-related issues.
Fixes #
**Checklist**
=> Dump: Dump namespaces, rbac and SCCs of hosted cluster

hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/nodepool_controller.go
Cancel context to kill watch guest cluster subroutines
ref https://issues.redhat.com/browse/HOSTEDCP-405
**Checklist**
=> Cancel context to kill watch guest cluster subroutines

control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/pdb.go, control-plane-operator/controllers/hostedcontrolplane/manifests/etcd.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go, control-plane-operator/controllers/hostedcontrolplane/manifests/oauth.go, control-plane-operator/controllers/hostedcontrolplane/manifests/olm.go, control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_apiserver.go, control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_oauth_apiserver.go, control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go, control-plane-operator/controllers/hostedcontrolplane/oapi/pdb.go, control-plane-operator/controllers/hostedcontrolplane/oauth/pdb.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-certified-rollout.cronjob.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-community-rollout.cronjob.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-marketplace-rollout.cronjob.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-operators-rollout.cronjob.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-collect-profiles.cronjob.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go, control-plane-operator/controllers/hostedcontrolplane/olm/olm-collect-profiles.go, support/upsert/upsert.go
move to ga apis for all components now that management clusters at minimum release boundary
Fixes #
**Checklist**
=> move to ga apis for all components now that management clusters at minimum release boundary

hypershift-operator/controllers/nodepool/inplace.go
We should honour hosted cluster availability before trying to crete a client for it.
Fixes #
**Checklist**
=> Add hostedClusterAvailable check for in place upgrades

test/e2e/control_plane_upgrade_test.go
=> Upgrade test: Stop verifying the nodecount

test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/util/fixture.go
Run the Ensure* validations in the generic create cluster to avoid maintining the list in each individual test.
Fixes #
**Checklist**
=> Refactor e2e test common cleanup

Makefile
Create a make target for e2e runs so they can all do the same thing and we can update in one place
Fixes #
**Checklist**
=> add ci-test-e2e target to Makefile

support/upsert/loopdetector.go
The inplace upgrade currently does three update requests to a node in a
row, which incorrectly triggers the loop detector. Increase the treshold
for them to avoid that.
Fixes #
**Checklist**
=> Update loopdetector to not get tripped by inplace upgrade

test/e2e/util/util.go
HO is going over mutate budget because of node upgrade tests and we've increase the number of HCs in a full e2e from 9 to 10.
Fixes #
**Checklist**
=> test: update API budget

hypershift-operator/controllers/nodepool/nodepool_controller.go
MachineDeployments are updated by CAPI after they are created to apply
defaults. This change sets the defaults on initial reconcile to avoid
an unnecessary update.
**Checklist**
=> Prevent update of a MachineDeployment after it is initially created

Makefile, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/util/fixture.go
New make target in https://github.com/openshift/hypershift/pull/1368 did not use `shell`
Fixes #
**Checklist**
=> fix Makefile

cmd/infra/aws/destroy.go
Currently, if an endpoint service has active endpoint connections its
deletion will silently fail. This change makes us delete the endpoint
connections first, which results in the deletion succeeding even if
there were any leftover endpoint connections.
Fixes #
**Checklist**
=> Delete endpoint connections before deleting endpoint services

docs/content/reference/goals-and-design-invariants.md, docs/mkdocs.yml
Add docs section for goals and design invariants
Fixes #
**Checklist**
=> Add docs section for goals and design invariants

test/e2e/util/util.go
This increase the budgets to 3x the max we see in CI right now.
Get the periodic passing
Fixes #
**Checklist**
=> e2e: increase budget to only catch extreme situations

api/fixtures/example.go, api/fixtures/example_ibmcloud_powervs.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go, cmd/cluster/core/destroy.go, cmd/cluster/powervs/create.go, cmd/cluster/powervs/destroy.go, cmd/infra/powervs/create.go, cmd/infra/powervs/destroy.go, docs/content/how-to/powervs/create-cluster-powervs.md, docs/content/how-to/powervs/create-infra-powervs-separately.md, docs/content/how-to/powervs/prerequisites-and-env-guide.md, docs/mkdocs.yml, hypershift-operator/controllers/hostedcluster/internal/platform/powervs/powervs.go
Added implementation for PowerVS Cluster Create and destroy 
Fixes #
**Checklist**
=> Added PowerVS Cluster Create & Destroy

test/e2e/util/util.go
This introduces timeouts to our polling e2e tests functions to avoid hitting the overall CI timeout. With this we intent to fail earlier and avoid CI timeout killing our process abruptly preventing us from dumping artefacts needed for debugging and understanding what went wrong.
ref https://issues.redhat.com/browse/HOSTEDCP-449
Fixes #
**Checklist**
=> Add local timeouts for e2e tests

control-plane-operator/controllers/hostedcontrolplane/kcm/deployment_test.go
Ref #1391
Fixes #
**Checklist**
=> KCM: Set leader election args

hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go
This change makes us insert the `machineconfiguration.openshift.io/role: worker`
label into all extra machineconfigs in oder to improve the UX.
Ref https://issues.redhat.com/browse/HOSTEDCP-418
/cc @enxebre 
Fixes #
**Checklist**
=> Nodepool: Insert the worker role label

cmd/install/assets/recordingrules/hypershift.yaml, hack/app-sre/saas_template.yaml
Same as #1442 but for CPU
Fixes #
**Checklist**
=> Add recording rule for cpu requests

cmd/install/assets/recordingrules/hypershift.yaml, hack/app-sre/saas_template.yaml
We need this to determine the unreclaimable memory used by each component to inform setting component memory resource requests
Fixes #
**Checklist**
=> Add memory rss recording rule

test/e2e/util/fixture.go, test/e2e/util/util.go
We have had issues with CI clusters being overcommitted in the past leading situations that are difficult to diagnose or reproduce.  This should increase visibility when that happens.
Fixes #
**Checklist**
=> e2e: notice FailedScheduling or Preempted events

api/fixtures/example.go, api/fixtures/example_ibmcloud_powervs.go, api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, control-plane-operator/controllers/hostedcontrolplane/cloud/powervs/powervs.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/powervs.go, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/internal/platform/powervs/powervs.go
Integrating cloud control manager for powervs platform to manage the worker nodes.
Fixes #
**Checklist**
- [x ] Subject and description added to both, commit and PR.
=> Add PowerVS Cloud Controller Manager

hypershift-operator/metrics.go
To include an initial set of metrics for telemetry, this PR reduces the
number of labels to report for hosted clusters and nodepools. This is
to keep an initial set of metrics under 10 series. (5 for hc, 5 for np)
The current metric with multiple labels is also flawed in that it can
potentially count a cluster multiple times as its version or endpoint
access type changes. We will need a way to update the counts for all
possible values of each label, but this can be done at a later time.
**Checklist**
=> Reduce HyperShift operator metrics cardinality

control-plane-operator/hostedclusterconfigoperator/controllers/resources/alerts/assets/apiusage.yaml, control-plane-operator/hostedclusterconfigoperator/controllers/resources/alerts/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/alerts.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Manual cherry-pick of #1406
Fixes #1201
**Checklist**
=> [release-4.10] Add missing control plane prometheus rules

control-plane-operator/hostedclusterconfigoperator/controllers/resources/alerts/assets/apiusage.yaml, control-plane-operator/hostedclusterconfigoperator/controllers/resources/alerts/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/alerts.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Manual cherry-pick of https://github.com/openshift/hypershift/pull/1406
Fixes #1201
**Checklist**
=> [release-4.9] Add missing control plane prometheus rules

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/kas/aws_kms.go, control-plane-operator/controllers/hostedcontrolplane/kas/ibmcloud_kms.go, control-plane-operator/controllers/hostedcontrolplane/kas/portieries.go, control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-certified.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-community.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-marketplace.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/catalog-redhat-operators.deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/operator.go, control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/reconcile.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go, hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go, support/util/cloudprovidercreds.go, support/util/containers.go, test/e2e/autorepair_test.go, test/e2e/autoscaling_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/util/util.go
Manual cherry-pick of https://github.com/openshift/hypershift/pull/1304
Fixes #1182, https://issues.redhat.com/browse/HOSTEDCP-330
**Checklist**
=> [release-4.10] Ensure that everything uses imagePullPolicy IfNotPResent for resiliency

contrib/admission-tracer/manifests/deployment.yaml, control-plane-operator/controllers/hostedcontrolplane/olm/assets/packageserver-deployment.yaml, hypershift-operator/controllers/hostedcluster/internal/platform/powervs/powervs.go
Updates more secret permissions to conform to the CIS Kubernetes benchmark
Fixes #1031 
**Checklist**
=> Updated secret permissions to conform to kubernetes CIS benchmark

control-plane-operator/controllers/hostedcontrolplane/olm/assets/packageserver-deployment.yaml
Manual cherry-pick of #1477 
Fixes #
**Checklist**
=> [release-4.9] Updated secret permissions to conform to kubernetes CIS benchmark

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
We currently don't set the kind which makes the CPO unable to
deserialize the objects and we permanently update, because we set the
Object field in the RawExtension object, which does not match what the
server gives us.
Fixes #
**Checklist**
=> HO: Fix raw extension generation for hcp configuration

cmd/infra/powervs/create.go, cmd/infra/powervs/validate.go
Added implementation for attaching security group rules to allow http and https ports in VPC during infra creation for accessing the console once the cluster is deployed.
Fixes #
**Checklist**
- [ x] Subject and description added to both, commit and PR.
=> powervs: Added inbound access rules for VPC security group to allow http & https

test/e2e/nodepool_machineconfig_test.go
Prevent modified object error:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-e2e-aws-periodic/1541662791214043136#1:build-log.txt%3A4252
co-authored-by: Alvaro Aleman <aaleman@redhat.com>
Fixes #
**Checklist**
=> Use Patch instead of Update to prevent error.

control-plane-operator/controllers/hostedcontrolplane/scheduler/config.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/config_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/config/constants.go
This PR supersedes https://github.com/openshift/hypershift/pull/1423
Fixes #
**Checklist**
=> Set Recommended Leader Election Values

api/v1alpha1/hostedcluster_types.go, control-plane-operator/hostedclusterconfigoperator/controllers/hcpstatus/hcpstatus.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
https://issues.redhat.com/browse/HOSTEDCP-390
requires https://github.com/openshift/hypershift/pull/1496
Fixes #
**Checklist**
=> Add ClusterVersionUpgradeable condition, upgrade block, and override annotation

api/v1alpha1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/config.go, control-plane-operator/controllers/hostedcontrolplane/kas/params.go, control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go, control-plane-operator/controllers/hostedcontrolplane/kcm/params.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/deployment.go, control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/util/strings.go
Manual cherry-pick of PR #1481
Fixes #1438
**Checklist**
=> [release-4.10] feat(cpo): Support disable profiling annotation

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go
This is done before anything else to prevent other update calls from failing if e.g. they are missing a new required field.
Fixes #
**Checklist**
=> Run reconcileDeprecated* earlier

hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go
Move TestReconcileDeprecatedGlobalConfig to proper file
Fixes #
**Checklist**
=> Move TestReconcileDeprecatedGlobalConfig to proper file

api/v1alpha1/hostedcluster_types.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/metrics.go, support/util/pausereconcile.go, support/util/pausereconcile_test.go
Step toward https://issues.redhat.com/browse/HOSTEDCP-495
Fixes #
**Checklist**
=> invert conditions that are false in expected state

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
=> Fix typo in namespace

cmd/cluster/core/dump.go
If any of the commands used in dumping the guest cluster failed, we did
not create a tar archive of the dump.  Move this code into a new function,
log any errors that occur, and always create the tar archive.
Fixes #
**Checklist**
=> Ensure that we always create a tar archive of the dump.

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
=> Fix logging arguments to not be odd

cmd/install/assets/recordingrules/hypershift.yaml, hack/app-sre/saas_template.yaml
Adds rules for metrics exposed through telemetry.
Rules for telemetry metrics clean up some fields such as pod/container/namespace that are not needed for telemetry
**Checklist**
=> Add rules for telemetry metrics

api/v1alpha1/hostedcluster_types.go, cmd/cluster/cluster.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/network/reconcile_test.go, docs/content/reference/api.md
`OpenshiftSDN` is not a valid value for the network-type, hence fix the typo for all the references.
Fixes #
**Checklist**
=> Rename OpenshiftSDN to OpenShiftSDN

cmd/infra/aws/destroy.go
Check return error code from s3 and only return an error other than the
s3 bucket being gone.
Fixes:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-main-periodics-aws-conformance/1546805465193648128
Fixes #
**Checklist**
=> Fail gracefully if s3 bucket is already deleted.

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/metrics.go, test/e2e/util/util.go
https://issues.redhat.com/browse/HOSTEDCP-495
Fixes #
**Checklist**
=> Add Progressing condition to HostedCluster

support/config/deployment.go
In service to adding a Degraded condition to the HCP
https://issues.redhat.com/browse/HOSTEDCP-495
This will allow us to easily list and check the status of all CPO managed deployments in the HCP.
Fixes #
**Checklist**
=> add label to all CPO managed deployments in the HCP

api/fixtures/example.go, api/fixtures/example_agent.go, api/fixtures/example_aws.go, api/fixtures/example_azure.go, api/fixtures/example_kubevirt.go, api/fixtures/example_none.go
This PR fixes:
- Align the code platform wise
- remove unused `getIngressWithHostnameServicePublishingStrategyMapping` function
Fixes #
**Checklist**
=> Align api/fixtures code platform wise

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
Clarify CloudProviderConfig purpose.
Fixes #
**Checklist**
=> Add link to CloudProviderConfig code

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/ingress/router.go
=> Drop unsued domain in ReconcilePrivateRouterDeployment signature

cmd/cluster/core/destroy.go
Otherwise the destroy command might transiently fail if something
modifies the hostedcluster in between retrieval and the Update call to
add/remove the finalizer.
Fixes #
**Checklist**
=> Destroy: Use patch for modifying finalizer to not get conflicts

cmd/cluster/core/destroy.go, cmd/cluster/powervs/destroy.go, cmd/infra/powervs/create.go, cmd/infra/powervs/destroy.go, vendor/github.com/IBM/networking-go-sdk/dnsrecordsv1/dns_records_v1.go, vendor/modules.txt
Current powervs destroy infra does not have DNS record deletion and Load balancer deletion in VPC subnet.
This PR implements the same to delete them.
Introduced `BaseDomain, CisCRN and CisDomainID` as part of `PowerVSPlatformDestroyOptions` so when we call destroy infra from destroy cluster, CIS domain details can be passed to attempt the DNS record deletion.
Fixes #
**Checklist**
=> PowerVS: Add DNS Record and VPC LB deletion

go.mod, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, support/supportedversion/version.go
Add latest version check and unit test isValidReleaseVersion
Fixes #
**Checklist**
=> Add latest version check and unit test isValidReleaseVersion

cmd/infra/powervs/create.go
This PR trying to add a check during infra creation that If DNS record with the cluster name already exist in base domain, do not allow infra creation.
RH Issue: https://issues.redhat.com/browse/MULTIARCH-2634
Fixes #
**Checklist**
=> PowerVS: Add DNS record check in base-domain

api/v1alpha1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
Fix `s/StorageOIDC/StorageARN` and `s/NetworkOIDC/NetworkARN/` and remove references to OIDC, which is abstracted at this level (the authn mechanism underneath roles in our case).  It just needs to be a role with a policy appropriate for the use.
Fixes #
**Checklist**
=> Fix comments/docs in AWSRoleRefs

docs/content/contribute/develop-in-cluster.md
Minor fix - the region/name variables are transposed
=> Docs: develop-in-cluster.md minor fix

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, support/supportedversion/version.go
Add min supported version check for isValidReleaseVersion
Fixes #
**Checklist**
=> Add min supported version check for isValidReleaseVersion

docs/content/how-to/agent/create-agent-cluster.md
If booting manually: set hostname and installation disk on the Agent,
then approve.
If booting via BMH: set these on the BMH (no need to approve).
No need to set role in this context - it will always be "worker".
=> Update Agent docs on setting hostname and disk

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/main.go, support/capabilities/management_cluster_capabilities.go, support/capabilities/management_cluster_capabilities_test.go
Fixes #1598
Fixes #1598
**Checklist**
=> fix(ho): detect capabilities on API resource availability

cmd/kubeconfig/create.go
Currently, the combined kubeconfig will always be for all namespaces.
With this change, it will be for the configured namespace only. In order
to allow getting kubeconfigs for clusters in all namespaces, the
--all-namespaces/-a flag is added.
Fixes #
**Checklist**
=> Create kubeconfig: Respect namespace

control-plane-operator/controllers/hostedcontrolplane/cloud/powervs/powervs.go
This PR trying to address https://issues.redhat.com/browse/MULTIARCH-2730 for renaming the env var for public endpoint in CCM.
Fixes #
**Checklist**
=> Rename PowerVS CCM public endpoint env variable

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
In the typed configuration we store, we only use the spec struct of each
configuration resource. However, when we serialize it, we include the
entire resource. The stauts resource is not needed and is causing
incompatibility with older OCP versions.
Going forward, the incompatibility should be fixed by #1616. However,
this change is needed to ensure we don't immediately break things while
CPOs in production are upgraded.
**Checklist**
=> Remove .status from serialized configuration on HCP

go.mod, go.sum, hypershift-operator/controllers/hostedcluster/internal/platform/powervs/powervs.go, vendor/modules.txt
Trying to upgrade capi image. 
Fixes #
**Checklist**
=> PowerVS: upgrade capi image

api/v1alpha1/hosted_controlplane.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
Fixes #1623 
Fixes #1623
**Checklist**
=> fix(api): make HCP networking optional for backward compatibility

cmd/cluster/core/dump.go
Copy ovn dbs and save db cluster status for all ovnkube-master pods for given hosted cluster name.
Needed for networking debugging
A new folder `network_logs` with ovn-related information will be created.
├── cluster-scoped-resources
├── event-filter.html
├── hypershift-dump.tar.gz
├── namespaces
├── network_logs
│   ├── ovnkube-master-0_ovnnb_db.db
│   ├── ovnkube-master-0_OVN_Northbound_status
│   ├── ovnkube-master-0_ovnsb_db.db
│   └── ovnkube-master-0_OVN_Southbound_status
└── timestamp
Fixes [#SDN-3215](https://issues.redhat.com/browse/SDN-3215)
**Checklist**
=> [dump] Add ovn-k specific collection commands

docs/content/how-to/agent/create-agent-cluster.md
Adds documentation for handling Ingress when using Hypershift agent platform
This doc provides a way to mitigate the issue that users can't set the Ingress VIP when using Hypershift Agent provider.
Relates to #https://bugzilla.redhat.com/show_bug.cgi?id=2105983 
**Checklist**
=> Add Handling Ingress to Agent docs

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, support/globalconfig/globalconfig.go
Fixes #1630 
Fixes #1630
**Checklist**
=> fix(ho): honor deprecated global config fields

ignition-server/controllers/local_ignitionprovider.go
Signed-off-by: nadav dolin <nadavdolin1@gmail.com>
What this PR does / why we need it:
Fixes https://github.com/openshift/hypershift/issues/1615
=> additional trust bundle into vm

docs/content/how-to/aws/deploy-aws-private-clusters.md
Trying to deploy a private HostedCluster, I kept getting `UnauthorizedOperation` error. By trial and error, I kept adding missing permissions to the policy until I got the cluster to deploy. Please review if this policy makes sense.
So that the documentation is up to date.
N/A
**Checklist**
=> private aws cluster guide - update IAM policy example

control-plane-operator/main.go, hypershift-operator/main.go
Occasionally this appears to return am empty string, which then makes
things fail down the line as an empty string is not a valid image. Retry
if that happens.
Output for when this happened:
```
{"level":"info","ts":"2022-07-28T16:55:17Z","logger":"setup","msg":"using operator image","image":""}
```
Fixes #
**Checklist**
=> Self image lookup: Retry on empty string

control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go
This operator has to communicate with the cloud provider, thus it needs
the management clusters proxy settings.
/assign @csrwng 
Fixes #
**Checklist**
=> Registry operator: Set proxy vars

support/config/deployment.go
In a recent refactor we lost the capability of disabling a deployment for local debugging. This commit restores that ability.
**Checklist**
=> Honor the debug-deployments annotation

control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go
The current identity provider conversion code will create a reference to
configmaps/secrets even if they have not been specified in the input
configuration. This results in invalid oauth configuration.
For optional references, we should check whether they are
specified before adding them to the configuration.
**Checklist**
=> OAuth: do not reference paths for empty optional secrets or configmaps

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
We currently only update the infra status after we got an event. If we
reconcile a hostedcluster that uses an LB for the apiserver in a
management cluster that does not support those, we will never update the
status because we never get an event.
Recheck after a minute when the infrastructure is not ready to make sure
the condition gets updated regularly.
/cc @csrwng 
Fixes #
**Checklist**
=> Correctly manage infra status condition when there is no LB controller

hypershift-operator/controllers/hostedcluster/hostedcluster_webhook.go, hypershift-operator/controllers/hostedcluster/hostedcluster_webhook_test.go
Validate that the CIDRs are properly formatted in the old version,
and then check that none of them overlap.
Fixes #
**Checklist**
=> Add CIDR checks to webhook on create

cmd/install/install.go, hack/app-sre/saas_template.yaml
Just keep up with latest external-dns since it isn't in the release payload
https://catalog.redhat.com/software/containers/edo/external-dns-rhel8/61d4c35023156829b87a434a?container-tabs=gti
**Checklist**
=> Update external-dns image

control-plane-operator/controllers/hostedcontrolplane/oauth/route.go
When DNS indirection is used but the cluster doesn't have a public LB
for its private router, the logic incorrectly set the default ingress
domain on the oauth route. This results in clients using the service DNS
domain name -> hitting the router -> getting a PKI failure because the
router doesn't know anything about this hostname and falls through to
its 404 page, which uses a different cert.
Fixes #
**Checklist**
=> Oauth: Fix hostname when using DNS indirection and no public router LB

control-plane-operator/hostedclusterconfigoperator/operator/config.go, support/labelenforcingclient/labelenforcer.go
=> Set right API group

cmd/cluster/core/destroy.go
Currently, the destroy cmd simply doesn't work at all if the
HostedCluster is already deleted but doesn't have the cmds finalizer.
Tolerate the corresponding error if that happens.
Fixes #
**Checklist**
=> Destroy: Don't fail if finalizer can not be added

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Ref https://issues.redhat.com/browse/HOSTEDCP-507
Fixes #
**Checklist**
=> HO: Ignore NoSuchBucket error when deleting OIDC docs

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
Fixes BYO PKI for ignition server certs.
Fixes #
**Checklist**
=> fix(pki): Allow BYO PKI for ignition server

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
Fixes: https://github.com/openshift/hypershift/pull/1522#issuecomment-1234973427
Fixes #
**Checklist**
=> fix(oauth): Do not proxy IBM Cloud IAM endpoints

api/fixtures/example.go, api/fixtures/example_ibmcloud_powervs.go, cmd/cluster/core/create.go, cmd/cluster/core/destroy.go, cmd/cluster/powervs/create.go, cmd/cluster/powervs/destroy.go, cmd/infra/powervs/create.go, cmd/infra/powervs/destroy.go, cmd/infra/powervs/util.go, cmd/infra/powervs/validate.go, test/e2e/e2e_test.go, test/e2e/util/fixture.go
Trying to refactor PowerVS changes to address comments given in earlier PRs on below things
- Capitalise abbreviations
- Removing named return var
- Using inline if wherever required
- and few minor changes like flag rename to remove redundant powervs prefix in it. e.g. `--powervs-zone` to `--zone`
Fixes #
**Checklist**
=> Refactor PowerVS changes

OWNERS
=> remove alvaroaleman and ironcladlou from OWNERS

cmd/infra/powervs/service_id.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2794
Fixes #
**Checklist**
=> Add cluster name prefix before secrets

cmd/infra/powervs/create.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2771
Fixes #
**Checklist**
=> Increase DHCP service polling interval

docs/content/how-to/powervs/create-cluster-powervs.md, docs/content/how-to/powervs/create-infra-powervs-separately.md, docs/content/how-to/powervs/prerequisites-and-env-guide.md
Fixes https://issues.redhat.com/browse/MULTIARCH-2569
Fixes #
**Checklist**
=> Refactor how-to docs

cmd/cluster/powervs/create.go, cmd/infra/powervs/create.go, cmd/infra/powervs/destroy.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2896
Fixes #
**Checklist**
=> Fix cmd.Context() usage in PowerVS

konnectivity-socks5-proxy/main.go
fixes #1738 
fixes https://issues.redhat.com/browse/MULTIARCH-2795
fixes https://issues.redhat.com/browse/HOSTEDCP-568
Fixes #
**Checklist**
=> Add cloud.ibm.com into konnectivity cloudAPI

control-plane-operator/main.go
Allow users / developers to override a list of images from a release to another image. This is useful for debugging of a hosted cluster control plane components, where building a whole release image with a simple fix in a single image would be cumbersome.
Tested using:
```
./control-plane-operator run --image-overrides=cluster-network-operator=quay.io/openshift/origin-cluster-network-operator:latest
oc -n clusters-jsafrane describe deployment cluster-network-operator
...
Image:      quay.io/openshift/origin-cluster-network-operator:latest
```
**Checklist**
=> Add image overrides

Dockerfile.control-plane, hypershift-operator/controllers/nodepool/nodepool_controller.go, ignition-server/cmd/run_local_ignitionprovider.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/controllers/tokensecret_controller_test.go, support/util/util.go
Follow up for https://github.com/openshift/hypershift/pull/1671
Decompress and decode config always but when not supported by the CPO
Fixes #
**Checklist**
=> Decompress and decode config if supported by current CPO

api/fixtures/example.go, cmd/cluster/cluster.go, cmd/cluster/core/create.go
Expose HC NodeSelector in the cli.
This will be leveraged by cluster-bot
Fixes #
**Checklist**
=> Expose HC NodeSelector in the cli

cmd/infra/powervs/create.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2961
Fixes #
**Checklist**
=> Ensure existing DHCP server is in ACTIVE state

Dockerfile, Dockerfile.fast
Switches to a 4.12 base and adds missing label to Dockerfile.fast
**Checklist**
=> Update Dockerfiles for consistency

cmd/cluster/core/create.go, cmd/cluster/powervs/create.go, cmd/infra/powervs/create.go, cmd/infra/powervs/destroy.go, docs/content/how-to/powervs/create-cluster-powervs.md, docs/content/how-to/powervs/create-infra-powervs-separately.md
Fixes https://issues.redhat.com/browse/MULTIARCH-2895
Fixes #
**Checklist**
=> Fix recreate issue on serviceID - MULTIARCH-2895

control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader.go
We currently use a bare MCD pod to do in-place upgrades.  Pods are mostly immutable and the code currently stomps the pod rather than reconciling it, resulting in both no-op warnings and `Forbidden: pod updates may not change fields` errors.
This PR switches the logic to only create the pod if it doesn't already exist.
=> HCCO: inplace upgrade: do not reconcile bare upgrade pod

api/v1alpha1/hostedcluster_types.go, hypershift-operator/controllers/hostedcluster/internal/platform/powervs/powervs.go, support/images/envvars.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2969
Fixes #
**Checklist**
=> Add CAPI provider image override for PowerVS

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, hypershift-operator/controllers/platform/aws/controller.go
=> Add comments to clarify aws endpoints controllers

docs/content/getting-started.md
Add a note so that customers will not create a duplicate public zones according to the help doc.  They might broke their own account network with duplicate public zones.
N/A
Fixes #
**Checklist**
=> add note for public zone creation doc

hypershift-operator/metrics.go, hypershift-operator/metrics_test.go
Adds a new `hypershift_cluster_available_duration_seconds` which measures, on a per HostedCluster basis, how long it took before the HostedClusterAvailable condition became true.  This supplements `hypershift_cluster_initial_rollout_duration_seconds` as a measure of HostedCluster deployment speed.
@derekwaynecarr @enxebre @jparrill
=> add HC available duration metric

docs/content/how-to/powervs/create-cluster-powervs.md, docs/content/how-to/powervs/create-infra-separately.md, docs/content/how-to/powervs/prerequisites-and-env-guide.md, docs/mkdocs.yml
Fixes https://issues.redhat.com/browse/MULTIARCH-2985
Fixes #
**Checklist**
=> PowerVS Refactor docs - bug fixes

control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader.go, control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader_test.go
Compared to self-driving OCP, there is an additional scenario to consider: since the ConfigMap contents are synced separately, those will change on the fly in the pod, meaning that we could have a scenario where there are multiple queue'ed updates, in which case the MCD will just jump straight to the latest version.
This will cause the MCD to softlock, so let's make sure for those unavailable nodes, we are also update their desired configuration.
I've tested this alongside https://github.com/openshift/hypershift/pull/1757, so if we want, I can add this commit to that PR, but these should be completely separate issues.
=> MCO-258: inplaceupgrader: handle multiple upgrade versions

docs/content/getting-started.md
Keep the same tabulation and line break across all the Getting Started page
- Keep the same tabulation and line breaker as used in the initial commands from the entire Getting Started page.
Fixes #
**Checklist**
=> nit: same tabulation across all the Getting Started

hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, support/releaseinfo/fake/fake.go, support/supportedversion/version.go, support/supportedversion/version_test.go
4.13 branch has occured and we need to update
=> move LatestSupportedVersion to 4.13

cmd/infra/powervs/destroy.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2977
Fixes #
**Checklist**
=> Add retry for cloud connection and VPC LB deletion

docs/mkdocs.yml
=> Add nodepool upgrades section to index

api/v1alpha1/hostedcluster_types.go
=> Add omitempty for RestoreSnapshotURL

docs/content/how-to/agent/create-agent-cluster.md
=> Change domain reference

api/v1alpha1/hosted_controlplane.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
This is the first of a series of PRs to make the HC conditions look more granular and closer to the HCP. Also will follow up to clean up and be consistent on reasons/messages.
ref https://issues.redhat.com/browse/HOSTEDCP-643
**Checklist**
=> Bubble up infrastructure condition from HCP into HC

cmd/infra/powervs/create.go, cmd/infra/powervs/destroy.go
Fixes https://issues.redhat.com/browse/MULTIARCH-2943
Fixes #
**Checklist**
=> PowerVS: Introduce retry on retryable errors on API call failure

docs/content/how-to/aws/migrate-hosted-cluster.md
Bug found on HC Migration. Some missing HCP objects needed.
Fixes #[HOSTEDCP-445](https://issues.redhat.com/browse/HOSTEDCP-445)
**Checklist**
=> Adding missing objects to the HC Migration

cmd/install/assets/recordingrules/hypershift.yaml, hack/app-sre/saas_template.yaml
This should help us see when the mgmt cluster API is having issues
=> add apiserver_request_aborts_total to recording rules

api/v1alpha1/hosted_controlplane.go, api/v1alpha1/hostedcluster_types.go, control-plane-operator/hostedclusterconfigoperator/controllers/hcpstatus/hcpstatus.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Bubble up conditions from CVO into HCP and into HC
Follow up for https://github.com/openshift/hypershift/pull/1851.
Ref https://issues.redhat.com/browse/HOSTEDCP-474
ref https://issues.redhat.com/browse/HOSTEDCP-643
**Checklist**
=> Conditions cvo

docs/content/getting-started.md
Add namespace argument to create nodepool command.
Fixes #
**Checklist**
=> Update create nodepool command in getting-started.md

test/e2e/util/fixture.go
This https://github.com/openshift/hypershift/pull/1826 is failing because we short circuit deletion until machines are gone, delaying the HCP deletion (and so the infra for guest cluster) and resulting in the e2e failing as it sees the infra resources still existing because of this delay.
This is a follow up for #1855 to avoid the race and wait to get a more deterministic output.
Supersedes https://github.com/openshift/hypershift/pull/1877
Fixes #
**Checklist**
=> Add wait for infra guest cluster deletion e2e

docs/content/how-to/aws/migrate-hosted-cluster.md
=> Remove invalid expectation about cli

ignition-server/controllers/tokensecret_controller.go
https://github.com/openshift/hypershift/pull/1873
This mistakenly prevent the TokenSecretMessageKey/TokenSecretReasonKey from being set in replace upgrades.
Fixes #
**Checklist**
=> Always set TokenSecretReasonKey/TokenSecretMessageKey

api/v1alpha1/hostedcluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
For consumers to watch if they see fit.
Ref https://issues.redhat.com/browse/HOSTEDCP-559
**Checklist**
=> Bubble up control plane endpoint from hcp into hc

api/v1beta1/hostedcluster_conditions.go, api/v1beta1/nodepool_conditions.go, api/v1beta1/nodepool_types.go, hypershift-operator/controllers/nodepool/inplace.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, hypershift-operator/controllers/nodepool/nodepool_controller_test.go, hypershift-operator/metrics.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/controllers/tokensecret_controller_test.go
Add docs for all conditions.
Give hints to consumers:
- // A failure here is unlikely to resolve without the changing user input.
- // A failure here often means a software bug or a non-stable cluster.
- // A failure here may require external user intervention to resolve. E.g. hitting quotas on the cloud provider.
Goes after https://github.com/openshift/hypershift/pull/1907
/hold
Fixes #
**Checklist**
=> Add better docs for conditions

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
fixes #1692 
Fixes #
**Checklist**
=> Force delete pod stuck in terminating state during hosted cluster cleanup

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Fixes a bug where we were returning the error message from failing to set the CAPI image from the release payload prior to trying to set the CAPI image from an environment variable or the hosted cluster annotation.
N/A
**Checklist**
=> Change CAPI image initialization order

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Fix a wrong error message.
**Checklist**
=> Fix snapshot-controller error message

cmd/infra/aws/destroy.go
This should reduce the chance that target groups are leaked by HostedClusters in CI
**Checklist**
=> Destroy target groups explicitly

docs/content/reference/controller-architecture.md
=> Clarify CAPI in controller arch doc

docs/content/reference/infrastructure/aws.md
Clarify aws private link service/endpoint requirement #1919
Fixes #
**Checklist**
=> Clarify aws private link service/endpoint requirement

control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/controllers/hostedcontrolplane/pki/ca.go, control-plane-operator/controllers/hostedcontrolplane/pki/etcd.go
What:
- Decouple etcd trust chain from root CA.
- Use etcd proxy for metrics.
- Add etcd metrics trust chain.
- Add distinct certificates for etcd proxy. 
Why:
- Create distinct trust zones.
- Use distinct certs for metrics scraping.
Fixes #
**Checklist**
=> AUTH-323: Add etcd and etcd metrics certs, add etcd metrics proxy

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
fixes #1936 
Fixes #
**Checklist**
=> Add resolve-from-guest-cluster-dns flag to ingress socks-proxy

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Without a kubelet present, pods will not go away without being force-deleted. Ensure that we do that whenever cleaning up pods.
**Checklist**
=> guest cleanup: ensure pods are force-deleted

hypershift-operator/controllers/nodepool/inplace.go
Implemented a separation in status.conditions to identify when a ConfigChange vs OpenshiftUpgrade happens in the InPlace upgrade type.
The behaviour it's the next:
Regarding UpdateConfig:
- If there is a change in progress, a new status.condition appears: UpdatingConfig
- It will show UPDATINGCONFIG as True in the oc get interface
- This status will comeback to False when the ConfigChange finishes
Regarding UpdateVersion:
- If you modify the NodePool release, a new field in NodePool.Status.Conditions appears: UpdatingVersion
- It will show UPDATINGCONFIG and UPDATINGVERSION in the oc get interface
- These statuses will comeback to False when the Upgrade finishes
NOTE: Kudos to @enxebre for helping me in the implementation. …
=> Added separation among UpdateVersion and UpdateConfig in NodePool Inplace Upgrade

support/certs/tls.go, support/certs/tls_test.go
The leaf certificate Subject Key Identifier generation was broken as it was assigning the CA pub key fingerprint to the leaf certificate SKID.
This commit removes the logic completely, golang generates the SKIDs/AKIDs where necessary.
/assign @csrwng 
/cc @ibihim 
---------
related rfc: https://www.rfc-editor.org/rfc/rfc3280#section-4.2.1.2
=> certs: fix SKID/AKID generation

test/e2e/olm_test.go
OLM test can hang cleanup and junit parsing of the log
=> test: add OLM test timeout

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
#1905 broke KAS communication with etcd
=> Revert "add KAS egress network policy"

control-plane-operator/controllers/hostedcontrolplane/kas/service.go
Follow up for https://github.com/openshift/hypershift/pull/2004
Fixes #
**Checklist**
=> Add clarifying comment

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
=> fix(ho): Set restart date annotation back

control-plane-operator/controllers/hostedcontrolplane/cvo/params.go, control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
=> fix(cpo): Remove storage from mgmt cluster for IBM Cloud

docs/content/reference/SLOs.md, docs/mkdocs.yml
Small step towards formalising docs and dev driven by SLOs/SLIs for the project.
Ref https://issues.redhat.com/browse/HOSTEDCP-701
**Checklist**
=> Add ref for SLOs

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
See linked issue.
Fixes #1989
**Checklist**
=> fix(hcco): Clean up resources intended to be removed by CVO

docs/content/contribute/custom-images.md, docs/content/contribute/develop-in-cluster.md, docs/mkdocs.yml
Updated the documentation on how to develop HyperShift components in-cluster
Fixes #
**Checklist**
=> Updatd development contribution docs

api/v1beta1/hostedcluster_conditions.go, support/util/pausereconcile.go, support/util/pausereconcile_test.go
Consolidate to use asExpected for happy path condition
Ref https://issues.redhat.com/browse/HOSTEDCP-722
**Checklist**
=> Use asExpected reason for ReconciliationActive=true

cmd/infra/powervs/create.go, cmd/infra/powervs/destroy.go, cmd/infra/powervs/validate.go
Fixes #
Fixes https://issues.redhat.com/browse/MULTIARCH-3237
**Checklist**
=> Use context func for PowerVS SDKs

test/e2e/util/util.go
Failures [like][1]:
```
util.go:252: Waiting for hostedcluster to rollout image. Namespace: e2e-clusters-w4dxm, name: example-b6ljs, image: registry.build05.ci.openshift.org/ci-op-l1wqy6tv/release@sha256:b3ae9f071cd8acf4163fb473a22fea37696f872ddcb0450ef18db1d293a7886f
util.go:276:
failed waiting for image rollout
Unexpected error:
<*errors.errorString | 0xc0002fdea0>: {
s: "timed out waiting for the condition",
}
timed out waiting for the condition
occurred
```
don't shed much light on why the test suite wasn't happy with the HostedCluster state.  This commit builds up strings explaining any current issues, logs them at check time, and includes the most recent set of issues in a final failure message.  That should save some time hunting around in gathered assets when folks are debugging …
=> test/e2e/util: Explain incomplete reasons in WaitForImageRollout*

control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go, control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/cvo/params.go, control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Made two mistakes in https://github.com/openshift/hypershift/pull/2055 :man_facepalming: 
Adjusting additional components that are over their limits as well.
=> Additional memory request adjustments

cmd/cluster/aws/create.go, cmd/infra/aws/create.go
Signed-off-by: Moti Asayag <masayag@redhat.com>
**Checklist**
=> Fix typo in cli create command usage

support/globalconfig/infrastructure.go
Currently in a PublicAndPrivate setup behind a proxy, nodes remain unready because ovn-node pods fail to talk to the control plane osdb and api endpoints. This is because the connection to .hypershift.local tries to go through the proxy. This PR set's the right value in the infra status that will result in hypershift.local being added to the NO_PROXY list of the ovn-pods via
https://github.com/openshift/cluster-network-operator/blob/8db9a00429dd4a5e4123b1217da93419557645eb/pkg/util/proxyconfig/no_proxy.go#L76
and
https://github.com/openshift/hypershift/blob/117c87f271ad7dc7cab875afb17769795fb7d117/control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go#L248
Additionally we also want to let the CNO set .hypershift.local in NO_PROXY unconditionally as this is a …
=> Fix infrastructure.status.apiServerInternalURI for PublicAndPrivate

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Add logs for when hc decide to not honour intent to clean up cloud resources
follow up for https://github.com/openshift/hypershift/pull/2083
**Checklist**
=> Add logs for when hc decide to not honour intent to clean up cloud resources

cmd/infra/powervs/create.go, vendor/github.com/IBM/platform-services-go-sdk/globaltaggingv1/global_tagging_v1.go, vendor/modules.txt
Fixes https://issues.redhat.com/browse/MULTIARCH-2897
Suffixes are used more of an identification that they created by hypershift, to add that and identify the resources better, added tags. 
Fixes #
**Checklist**
=> Add tags and rename cloud instance name suffix

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/cno.go, control-plane-operator/controllers/hostedcontrolplane/manifests/nto.go, control-plane-operator/controllers/hostedcontrolplane/nto/clusternodetuningoperator.go
Creating separate RBAC resources for NTO. And separate Service Account for CNO (do not use default).
Fixes #
**Checklist**
=> fix(cpo): Separate RBAC for NTO + CNO

docs/content/how-to/aws/external-dns.md
=> Add dns docs clarification for private topology

docs/content/getting-started.md, docs/content/how-to/automated-machine-management/nodepool-upgrades.md
Fixes a minor doc issue on Getting Started page and updates a note to an Important block on the NodePool Upgrades page.
N/A
**Checklist**
=> Minor fixes to notes on Getting Started and NodePool Upgrades pages

control-plane-operator/controllers/hostedcontrolplane/kas/params.go
Original feature was delivered in: https://github.com/openshift/hypershift/pull/1481
Fixes #1438 
**Checklist**
=> fix(cpo): Allow KAS profiling disablement

api/v1alpha1/zz_conversion.go, api/v1alpha1/zz_conversion_test.go
Please review this change thoroughly. This updates `v1alpha1` --> `v1beta1` conversion logic to ignore reconciling deprecated fields from Hub (raw) to HC conversion. Without this, deprecated cluster config fields were clobbering the supported fields during the conversion round trip.
Fixes #1988
**Checklist**
=> fix(api): Fix deprecated API conversion

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
=> reduce ignition server scope

api/v1beta1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hack/app-sre/saas_template.yaml
=> Basic immutability for NodePool

test/e2e/nodepool_machineconfig_test.go, test/e2e/nodepool_nto_machineconfig_test.go, test/e2e/nodepool_test.go
This reverts commit 9d41dc6286b04c8e7a7ceaaddb4dcb5028e2804a.
Checking to see if this fixes presub job
=> Revert "Refactored NTO MachineConfig InPlace and Replace E2E Tests"

hypershift-operator/controllers/nodepool/nodepool_controller.go
Reinstate user-data clean up for non-AWS platforms. The change to skip clean up was introduced by: https://github.com/openshift/hypershift/pull/1826
Fixes #
**Checklist**
=> fix(ho): Delete user-data secret for non-AWS platforms

api/v1beta1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
=> Clarify docs for nodePool.spec.config

go.mod, test/e2e/create_cluster_test.go, test/e2e/util/pod_exec.go, test/e2e/util/util.go
Ensure secrets are encrypted using KMS
Fixes #[HOSTEDCP-386](https://issues.redhat.com/browse/HOSTEDCP-386)
**Checklist**
=> Add e2e test for secrets encryption using kms

control-plane-operator/controllers/hostedcontrolplane/cloud/powervs/powervs.go
Fixes https://issues.redhat.com/browse/MULTIARCH-3238
Fixes #
**Checklist**
=> Use KAS kubeconfig for PowerVS CCM instead of external kubeconfig

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
=> Skip destroyAWSDefaultSecurityGroup if not AWS

test/e2e/create_cluster_test.go
Ref https://issues.redhat.com/browse/HOSTEDCP-731
blocked by https://issues.redhat.com/browse/OCPBUGS-6651
**Checklist**
=> Add e2e test for hosted cluster behind a proxy

control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcilePodMonitor.yaml, support/metrics/sets.go
https://issues.redhat.com/browse/HOSTEDCP-648
=> fix regex in registry operator pod monitor

docs/content/how-to/kubevirt/create-kubevirt-cluster.md
This PR updates the KubeVirt platform's How-to documentation to reflect all the most recent improvements, changes, and recommendations.
=> Update KubeVirt platform how-to documentation

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Supersedes #2123 
Fixes #
**Checklist**
=> fix(cpo): Reduce CNO access if Calico used as network provider

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Supersedes https://github.com/openshift/hypershift/pull/2127
Fixes #
**Checklist**
=> fix(cpo): Remove OLM collect for IBM Cloud to reduce artifacts and rbac

availability-prober/availability_prober.go, control-plane-operator/controllers/hostedcontrolplane/dnsoperator/dnsoperator.go, support/util/containers.go
- Add pod gone check to availability prober
- Include ^ check for DNS operator
- Add leader elect args to DNS operator deployment
Fixes #2128
**Checklist**
=> feat: Add pod gone check to prober + DNS operator leader elect

test/e2e/nodepool_autorepair_test.go, test/e2e/nodepool_machineconfig_test.go, test/e2e/nodepool_nto_machineconfig_test.go, test/e2e/nodepool_test.go, test/e2e/util/util.go
Bug hunting on data recollection after failing.
- PR Merged in the past: https://github.com/openshift/hypershift/pull/2051
- PR Reverted: https://github.com/openshift/hypershift/pull/2145
Fixes #[HOSTEDCP-687](https://issues.redhat.com/browse/HOSTEDCP-687)
**Checklist**
=> Adding NTO again to find the issue with data recollection

test/e2e/nodepool_kms_root_volume_test.go, test/e2e/nodepool_test.go
Fixes #[HOSTEDCP-827](https://issues.redhat.com/browse/HOSTEDCP-827)
**Checklist**
=> HOSTEDCP-827: Add root volume encryption e2e test

api/v1beta1/hostedcluster_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml, cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml, docs/content/reference/api.md, hack/app-sre/saas_template.yaml
Follow up for https://github.com/openshift/hypershift/pull/2213
Fixes #
**Checklist**
=> Add comment for BaseDomainPrefix

docs/content/reference/versioning-support.md
Fixes #[HOSTEDCP-794](https://issues.redhat.com/browse/HOSTEDCP-794)
**Checklist**
=> Added documentation around supported-versions configmap

test/e2e/util/util.go
NTO is restarting a few times making all presumits fail skipping until this is solved. Discussion for fixing is taking place.
Fixes #
**Checklist**
=> Skip pod restart check for NTO

control-plane-operator/controllers/hostedcontrolplane/kas/ibmcloud_kms.go
=> kms addition for pod identity workflow

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
Deletes multus validating webhook configuration as part for CNO init. Ensures no conflicting validating webhook configuration resource is present when multus transitions to control plane side for 4.12.
Fixes #2227
**Checklist**
=> fix(cpo): Delete multus validatingwebhookconfiguration on CNO init

docs/content/how-to/automated-machine-management/node-tuning.md
Improve docs for Node Tuning section
**Checklist**
=> Add a debug section to the Node Tuning docs

api/v1beta1/hostedcluster_conditions.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/kas/aws_kms.go, control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/awsutil/sts.go, support/util/svcaccounts.go
This introduces a new condition indicating whether both key and role are compatible/operational
Fixes #[HOSTEDCP-806](https://issues.redhat.com/browse/HOSTEDCP-806)
**Checklist**
=> Validate etcd KMS config

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
=> Update HCP version in capi cluster ref

test/e2e/nodepool_autorepair_test.go, test/e2e/nodepool_machineconfig_test.go, test/e2e/nodepool_nto_machineconfig_test.go, test/e2e/nodepool_test.go
=> Refactor e2e nodepool tests

api/v1beta1/hostedcluster_conditions.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/util/expose.go, support/util/util.go
cherry-pick of https://github.com/openshift/hypershift/pull/2130
=> OCPBUGS-8241: Add external DNS health condition / release-4.12

docs/content/how-to/powervs/prerequisites-and-env-guide.md
Fixes https://issues.redhat.com/browse/MULTIARCH-3149
Fixes #
**Checklist**
=> Update PowerVS prereq doc with install and authorization details

docs/content/how-to/aws/disaster-recovery.md, docs/content/how-to/aws/troubleshooting.md, docs/mkdocs.yml
As discussed in the meeting with the SRE team, we agreed in create a documentation to cover the most common issues that could happen during a HostedCluster migration, this will mitigate the possible effects caused by the side-scenarios. 
More details in the Jira Card
Fixes #[HOSTEDCP-445](https://issues.redhat.com/browse/HOSTEDCP-445)
**Checklist**
=> HOSTEDCP-445: Documented the possible issues found during a HostedCluster migration

test/e2e/control_plane_upgrade_test.go
This fixes 4.12 e2e test
Fixes https://github.com/openshift/hypershift/pull/2275#issuecomment-1467239798
=> Force controleplane upgrade always

control-plane-operator/controllers/hostedcontrolplane/mcs/reconcile.go, hypershift-operator/controllers/nodepool/nodepool_controller.go, ignition-server/cmd/run_local_ignitionprovider.go, ignition-server/controllers/local_ignitionprovider.go, ignition-server/controllers/machineconfigserver_ignitionprovider.go, ignition-server/controllers/tokensecret_controller.go, ignition-server/controllers/tokensecret_controller_test.go, support/util/util.go
Fixes failed cherry pick  on https://github.com/openshift/hypershift/pull/2187
Fixes [OCPBUGS-8334](https://issues.redhat.com/browse/OCPBUGS-8334)
**Checklist**
=> OCPBUGS-8334: [release-4.12] Update the pull secret source for ignition payload

api/v1beta1/nodepool_types.go, cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml, hack/app-sre/saas_template.yaml
Fail earlier for invalid input.
Fixes #
**Checklist**
=> OCPBUGS-10423: Add validation for taint.value in nodePool

api/v1beta1/endpointservice_types.go, docs/content/reference/api.md, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
This propagates `AWSEndpointServices` conditions to the HostedCluster
Fixes #[HOSTEDCP-903](https://issues.redhat.com/browse/HOSTEDCP-903)
**Checklist**
=> HOSTEDCP-903: Propagate AWSEndpointService conditions

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml
Fixes #[HOSTEDCP-938](https://issues.redhat.com/browse/HOSTEDCP-938)
**Checklist**
=> HOSTEDCP-938: Added PSA default profile to RunTimeDefault in operator deployment

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
=> HOSTEDCP-934: [release-4.13] Validate PublishingStrategyMapping

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
The health check will incorrectly report a healthy condition for the AWSIdentityProvider when reusing the same client. This change fixes that by creating a new client every time the health check is executed.
Fixes #OCPBUGS-10227
**Checklist**
=> OCPBUGS-10227: Create new EC2 client for AWS identity provider health check

hypershift-operator/metrics.go
=> HOSTEDCP-944: Add more expectedHCConditionStates metrics

hypershift-operator/metrics.go
This is a first step towards having the abiility to identify and visualise more granular SLIs that might be bottle necks impacting our SLOs. It provides a picture on duration for CP components to available
Fixes #
**Checklist**
=> HOSTEDCP-943: Add hypershift_hosted_cluster_transition_seconds histogram

cmd/cluster/aws/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/iam.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/oidc/oidc.go, test/e2e/autoscaling_test.go, test/e2e/chaos_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/nodepool_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/olm_test.go, test/e2e/util/aws.go, test/e2e/util/fixture.go
cherry-pick of #2335 and #2360
=> HOSTEDCP-939: [release-4.13] Setup shared OIDC provider for e2e clusters

cmd/cluster/aws/create.go, cmd/infra/aws/create_iam.go, cmd/infra/aws/iam.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/oidc/oidc.go, test/e2e/autoscaling_test.go, test/e2e/chaos_test.go, test/e2e/control_plane_upgrade_test.go, test/e2e/create_cluster_test.go, test/e2e/e2e_test.go, test/e2e/nodepool_nto_machineconfig_test.go, test/e2e/nodepool_test.go, test/e2e/nodepool_upgrade_test.go, test/e2e/olm_test.go, test/e2e/util/aws.go, test/e2e/util/fixture.go
cherry-pick of #2335 and #2360
=> HOSTEDCP-939: [release-4.12] Setup shared OIDC provider for e2e clusters

cmd/install/install.go
=> HOSTEDCP-951: Let install apply to aggregate errors

test/e2e/util/oauth.go
Wait for oauth config configMap to reconcile before attempting to request a token
=> e2e: Fix oauth idp e2e test

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Requeue HCP controller with different intervals depending on the Ready status. This will ensure external resources are reconciled in a timely fashion.
Fixes #[HOSTEDCP-807](https://issues.redhat.com//browse/HOSTEDCP-807) (LoadBalancer taking a long time to report ready, because the reconcile loop can't watch its status).
**Checklist**
=> HOSTEDCP-807: Requeue HCP always

cmd/OWNERS, docs/OWNERS, test/OWNERS
goes along with https://github.com/openshift/release/pull/38274
=> add OWNERS for new area labels

control-plane-operator/controllers/hostedcontrolplane/cloud/powervs/powervs.go, control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Fixes #
Fixes [MULTIARCH-3449](https://issues.redhat.com//browse/MULTIARCH-3449)
**Checklist**
=> MULTIARCH-3449: set priority class for cloud controller manager pod for PowerVS

contrib/metrics/SLOs-grafana-dashboard.json
=> json export for a common grafana dashboard for SLOs

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/metrics/labels.go
This PR is a manual cherry-pick of https://github.com/openshift/hypershift/pull/2419
Git SHA: `e1c39f2f94e84adde83cbf3cbbff5bd47543eb44`
=> [release-4.13] Enable monitoring for hypershift & HCP namespace

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/manifests/egressfirewall/manifests.go
=> kubevirt: Block metadata server egress

ignition-server/controllers/local_ignitionprovider.go
Fix haproxy image name in ignition server
Fixes #
**Checklist**
=> HOSTEDCP-950: Fix haproxy image name in ignition server

test/e2e/nodepool_upgrade_test.go
Add basic input/output validation for default security group condition expectations. If we want to and find it valuable in future could add more assertions e.g MD SG = hcluster.Status.Platform.AWS.DefaultWorkerSecurityGroupID.
Fixes #
**Checklist**
=> HOSTEDCP-918: Add validation for default Security Group conditions during NodePool upgrade test

cmd/infra/aws/create_iam.go, test/e2e/e2e_test.go
=> [release-4.13] e2e: Cleanup shared OIDC provider on SIGTERM

cmd/infra/aws/create_iam.go, test/e2e/e2e_test.go
cherry-pick of https://github.com/openshift/hypershift/pull/2435
=> [release-4.12] e2e: Cleanup shared OIDC provider on SIGTERM

hypershift-operator/controllers/platform/aws/controller.go
When authentication with a customer account fails due to an OIDC provider no longer being available, the HyperShift operator should unilaterally cleanup any VPC endpoint services that exist on the management side. In some cases, this cannot happen until any existing private link connections have been terminated. This commit adds code to find any existing connections and reject them so that the endpoint service can be removed.
Fixes #OCPBUGS-11930
**Checklist**
=> OCPBUGS-11930: Clean up existing VPC endpoint connections

hypershift-operator/metrics.go
=> OCPBUGS-7841: Set metrics to 0 when needed to keep time series honest

cmd/install/assets/hypershift_operator.go, hack/app-sre/saas_template.yaml, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go, hypershift-operator/controllers/manifests/egressfirewall/manifests.go
This is a manual cherry-pick of:
- https://github.com/openshift/hypershift/pull/2399
=> [release-4.13] kubevirt: Block metadata server egress

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/olm/params.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Fixes https://issues.redhat.com/browse/OCPBUGS-12153
**Checklist**
=> OCPBUGS-12153: fix(hcco): Get OLM CatalogSource images from defined map

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/metrics.go, hypershift-operator/metrics.go, test/e2e/util/fixture.go
=> HOSTEDCP-969: Move proxy, silence alerts and limited support metrics into HC controller

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, hypershift-operator/controllers/hostedcluster/metrics.go, hypershift-operator/controllers/hostedcluster/metrics_test.go
Consolidate on using namespace and name labels to give oberserver flexibility to filter by namespace and construct hcp namespace
Fixes #
**Checklist**
=> HOSTEDCP-969: Consolidate labels for metrics

test/e2e/create_cluster_test.go, test/e2e/util/node.go, test/e2e/util/oauth.go, test/e2e/util/util.go
cherry-pick of https://github.com/openshift/hypershift/pull/2383
=> [release-4.13] HOSTEDCP-917: Add publicAndPrivate <-> Private e2e test

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, test/e2e/util/oauth.go
cherry-pick of https://github.com/openshift/hypershift/pull/2452
=> [release-4.13] OCPBUGS-12844: Delete kubeadmin secret when an idp is defined

cmd/install/assets/hypershift_operator.go, hypershift-operator/metrics.go, hypershift-operator/metrics_test.go, test/e2e/util/fixture.go
=> [release-4.13] HOSTEDCP-937: Add new metric to expose hypershift operator info

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, support/globalconfig/featuregate.go
https://issues.redhat.com/browse/OCPBUGS-13309
=> OCPBUGS-13309: set FeatureGate global config

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
The health check on internal load balancers will only work if the load balancer includes the private subnets. However, this is not guaranteed unless the subnets of the management cluster are labeled with public or private labels. For now, we'll only check the public load balancers in a non-private cluster and just the KAS service in a private cluster.
Fixes #OCPBUGS-13021
**Checklist**
=> OCPBUGS-13021: Health check load balancers only on public clusters

hypershift-operator/main.go
Without this setting e.g. --private-platform=aws would just run the HO without the logic expected for AWS
Fixes #
**Checklist**
=> Validate HO private platform input

docs/content/contribute/index.md, docs/content/getting-started.md, docs/content/how-to/debug-nodes.md
Updates the Contribute and Getting Started pages to use a numbered list rather than a bullet list; this makes it easier to point people to certain sections of the document, for example, referencing a section in peer review comment in a pull request.
Fixes [HOSTEDCP-981](https://issues.redhat.com/browse/HOSTEDCP-981)
**Checklist**
- N/A This change includes unit tests.
=> HOSTEDCP-981: Minor updates to Getting Started & Contribute pages

test/e2e/nodepool_test.go
Validates nodePool `NodePoolAWSSecurityGroupAvailable` condition is true, when using the default security group (i.e. setting Spec.Platform.AWS.SecurityGroups = nil)
Fixes #[HOSTEDCP-918](https://issues.redhat.com/browse/HOSTEDCP-918)
**Checklist**
=> HOSTEDCP-918: Add validation for NodePool security Group condition when using default SG

cmd/infra/aws/ec2.go
Internal/external tags are used by the aws cloud provider to select subnets assigned to load balancers. In standalone OCP, the installer sets these tags on subnets it creates. This commit sets the same tags for hypershift clusters.
Fixes #OCPBUGS-13021
**Checklist**
=> OCPBUGS-13021: Add internal/external elb tags to subnets

docs/content/how-to/aws/troubleshooting.md
Fixes #[HOSTEDCP-445](https://issues.redhat.com/browse/HOSTEDCP-445)
**Checklist**
=> HOSTEDCP-445: Included how to fix image-registry clusteroperator after a disaster recovery migration

control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Fixes [HOSTEDCP-830](https://issues.redhat.com/browse/HOSTEDCP-830)
Fixes #
**Checklist**
=> HOSTEDCP-830: Update auto scaler role to get and list agentmachinetemplates

contrib/metrics/SLOs-grafana-dashboard.json
Fixes #[HOSTEDCP-975](https://issues.redhat.com/browse/HOSTEDCP-975)
**Checklist**
=> HOSTEDCP-975: Add new grafana panels for nodepools SLOs

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go, support/awsutil/sg.go
Cherry-picks https://github.com/openshift/hypershift/pull/2574 and https://github.com/openshift/hypershift/pull/2529
in one go to avoid chance to face the nil deref.
Fixes #
**Checklist**
=> OCPBUGS-13639: Cherry pick aws endpoint sg

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go, control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/pki.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go, control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go, hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, support/certs/tls.go
cherry-pick of https://github.com/openshift/hypershift/pull/2550
=> [release-4.12] OCPBUGS-13626: Sync proxy TrustedCA to guest cluster

cmd/infra/aws/ec2_sg.go
Recent flakes on `AuthorizeSecurityGroupIngress` even though we verify the SG can be described before we make the call.
Wrap in a retry to avoid test flakes.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn/1661494115142995968
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn/1661674583138242560
=> cmd: infra: aws: retry on AuthorizeSecurityGroup failure

docs/content/reference/infrastructure/agent.md, docs/content/reference/infrastructure/aws.md, docs/content/reference/infrastructure/index.md, docs/mkdocs.yml
**What this PR does / why we need it**: Infrastructure docs for the agent platform
Fixes #[OCPBU-609](https://issues.redhat.com//browse/OCPBU-609)
**Checklist**
=> OCPBU-609: agent infrastructure docs

cmd/install/install.go, hack/app-sre/saas_template.yaml
This reverts commit 74c336e5e5e9bf65cebb4101d591c492a07ccf62, reversing changes made to d5a31a74718dea331658a15f54c83cda71e3c98d.
Fixes #
**Checklist**
=> Revert "Merge pull request #2596 from muraee/disable-valpha1"

ignition-server/controllers/local_ignitionprovider.go
Follow up to #2572, all MCO related components need to have the payload version passed in, so pass to MCC and MCS as well, else they cannot construct a featuregateaccess once openshift/machine-config-operator#3688 merges.
=> OCPBUGS-13547: Pass payload-version to MCS and MCC

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
When creating a guest cluster with kubevirt provider, we need to enforce isolation on the virtual machines that they won't be able to access other control plane pods or other pods in the management cluster. This PR restricts access only for the required services:
- guest's kube-apiserver
- ignition server
- DNS server
- router-ingress
- other guest nodes (virt-launchers)
Fixes #
**Checklist**
=> Network isolation of VirtualMachines for KubeVirt provider

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go, test/e2e/create_cluster_test.go, test/e2e/nodepool_test.go
This makes sure AWS specific conditions are only set if platform is AWS
Fixes #[HOSTEDCP-1003](https://issues.redhat.com/browse/HOSTEDCP-1003)
**Checklist**
=> HOSTEDCP-1003: Set AWS conditions only for AWS platform

control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
https://issues.redhat.com/browse/HOSTEDCP-992
No functional change, just refactor to match CPO coding style of a main component level `Reconcile` with per-resource `reconcile` functions within the package.
=> HOSTEDCP-992: refactor ignition-server reconcilation

test/e2e/nodepool_test.go
/hold
This might be way out if
https://github.com/openshift/hypershift/pull/2664 doesn't go green.
Fixes #
**Checklist**
=> Disable nodepool replace upgrade test

cmd/cluster/core/dump.go, cmd/util/client.go, docs/content/how-to/troubleshooting.md, docs/mkdocs.yml
Manual cherry-pick from:
- https://github.com/openshift/hypershift/pull/2653
=> [release-4.13] HOSTEDCP-1048: Add impersonate feature to the CLI and document HC dump procedure

docs/content/how-to/automated-machine-management/nodepool-lifecycle.md, docs/mkdocs.yml
=> Update NodePool docs to include data propagation

control-plane-operator/controllers/hostedcontrolplane/oauth/config.go, control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
https://issues.redhat.com/browse/OCPBUGS-13829
=> OCPBUGS-13829: cpo: oauth: honor AccessTokenInactivityTimeout
