- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
If the guest cluster was created with `--service-publishing-strategy=NodePort`, the guest nodes (virt-launchers) will then need access to NodePort services, which means they would need a connection to one of the infra Node IP addresses as well.
The chosen infra node in this case will the address specified for the APIServer NodePort Service in `HostedCluster.spec.services`.
Fixes #
**Checklist**
> [KubeVirt] Whitelist access from virt-launchers to NodeIP if NodePort ServicePublishingStrategy is used

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
> OCPBUGS-15168: fix(oauth): Do not proxy IBM Cloud IAM endpoints

- test/e2e/create_cluster_test.go
- test/e2e/util/util.go
https://issues.redhat.com/browse/HOSTEDCP-1032
> HOSTEDCP-1032: e2e: ensure default PSA policy is not privileged

- product-cli/cmd/create/create.go
- product-cli/cmd/nodepool/create.go
- product-cli/cmd/nodepool/kubevirt/create.go
Add Create NodePool for KubeVirt for HCP CLI
Fixes [HOSTEDCP-1024](https://issues.redhat.com/browse/HOSTEDCP-1024)
**Checklist**
> HOSTEDCP-1024: Add Create NodePool for KubeVirt for HCP CLI

- hypershift-operator/main.go
- support/capabilities/management_cluster_capabilities.go
- support/globalconfig/imagecontentsource.go
Follow up to PR comments on #2642, specifically [here](https://github.com/openshift/hypershift/pull/2642#pullrequestreview-1480964875).
Related to work on [OCPBUGS-11939](https://issues.redhat.com/browse/OCPBUGS-11939)
**Checklist**
> Follow up to PR comments on #2642

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
cherry-pick of https://github.com/openshift/hypershift/pull/2604
> [release-4.13] HOSTEDCP-1003: Set AWS conditions only for AWS platform

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- support/util/deployment.go
- support/util/deployment_test.go
Unmodified pick from https://github.com/openshift/hypershift/pull/2735
https://issues.redhat.com/browse/HOSTEDCP-1073
> [release-4.12] HOSTEDCP-1073: enforce blocked rollout of HCP

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
on non AWS platform, the LB ingress point for the kube-apiserver might not be DNS-based (`.svc.status.loadBalancer.ingress[].hostname`), but IP-based (`.svc.status.loadBalancer.ingress[].ip`).
In that case, the healthcheck won't succeed, since we are passing only the hostname into the `healthCheckKASEndpoint()` function, resulting in an error message like:
```
message: 'Get https://:7443/healthz: dial tcp :7443: connect: connection refused'
```
Fixes # [CNV-30376](https://issues.redhat.com//browse/CNV-30376)
**Checklist**
> Fix KAS HealthCheck for non DNS-Based ingress points in LB service

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go
- control-plane-operator/controllers/hostedcontrolplane/pki/ignitionserver.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/controllers/manifests/ignitionserver/manifests.go
Unmodified pick from https://github.com/openshift/hypershift/pull/2748
> [release-4.12] HOSTEDCP-1060: refactor ignition-server reconcilation and add ignition-server proxy

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
https://issues.redhat.com/browse/OCPBUGS-15991
> OCPBUGS-15991: use ignition-proxy Service to populate ignitionEndpoint with strategy NodePort

- hypershift-operator/controllers/platform/aws/controller.go
- hypershift-operator/controllers/platform/aws/controller_test.go
- hypershift-operator/metrics_test.go
- vendor/github.com/go-logr/logr/funcr/funcr.go
- vendor/github.com/go-logr/logr/testr/testr.go
- vendor/modules.txt
This is a manual cherry-pick of #2700 due to the automated one not quite vendoring correctly - #2783
> [release-4.13] OCPBUGS-15965: Reject VPCE Connections during VPCE Service cleanup

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- hypershift-operator/main.go
- support/globalconfig/imagecontentsource.go
Addresses Cesar's comments on the backport for https://github.com/openshift/hypershift/pull/2642#pullrequestreview-1524598573.
Adds on to [OCPBUGS-11939](https://issues.redhat.com/browse/OCPBUGS-11939)
**Checklist**
> OCPBUGS-11939: Fix additional issues with OCPBUGS-11939

- test/e2e/autoscaling_test.go
Reverts openshift/hypershift#2808
This caused instability in the TestAutoscaler test and is blocking the release.  SOP is to revert and we will rework.
> Revert "HOSTEDCP-1094: e2e autoscaler balancing similar node groups"

- renovate.json
Add config to set creation frequency of RHTAP PRs
Fixes [HOSTEDCP-1112](https://issues.redhat.com/browse/HOSTEDCP-1112)
**Checklist**
> HOSTEDCP-1112: Add config to set creation frequency of RHTAP PRs

- api/v1beta1/nodepool_types.go
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
- docs/content/reference/api.md
- hack/app-sre/saas_template.yaml
Add ImageDigestMirrorSet to Config API comment
Fixes [HOSTEDCP-1046](https://issues.redhat.com/browse/HOSTEDCP-1046)
**Checklist**
> HOSTEDCP-1046: Add ImageDigestMirrorSet to Config API comment

- control-plane-operator/controllers/hostedcontrolplane/olm/olm-collect-profiles.go
https://issues.redhat.com/browse/OCPBUGS-16770
> OCPBUGS-16770: add need-management-kas-access label to olm-collect-profiles pods

- control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
OLM catalog images should reference images that correspond to the release
Fixes #OCPBUGS-17171
**Checklist**
> OCPBUGS-17171: Update OLM catalog image tags

- docs/content/how-to/upgrades.md
> Fix nodepool upgrade docs link

- cmd/cluster/aws/create.go
- cmd/cluster/aws/create_test.go
- product-cli/cmd/cluster/aws/create.go
- product-cli/cmd/cluster/cluster.go
Add HCP CLI Command to Create a Cluster on AWS
Fixes [HOSTEDCP-1022](https://issues.redhat.com/browse/HOSTEDCP-1022)
**Checklist**
> HOSTEDCP-1022: Add HCP CLI Command to Create a Cluster on AWS

- control-plane-operator/controllers/hostedcontrolplane/storage/assets/10_deployment-hypershift.yaml
- control-plane-operator/controllers/hostedcontrolplane/storage/envreplace.go
- control-plane-operator/controllers/hostedcontrolplane/storage/envreplace_test.go
Next step after https://github.com/openshift/cluster-storage-operator/pull/392
cc @jsafrane @gnufied
> STOR-1432: cso: add envvars for CSI driver controller images

- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
follow-up of https://github.com/openshift/cluster-network-operator/pull/1942
Fixes #
**Checklist**
> SDN-4057: Pass ControlPlane image to OVN

- control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
- control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver_test.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/controllers/nodepool/haproxy.go
- hypershift-operator/controllers/nodepool/nodepool_controller.go
- support/util/fakeimagemetadataprovider/fakeimagemetadataprovider.go
- support/util/imagemetadata.go
Reverts openshift/hypershift#2820
> Revert "HOSTEDCP-1001: Image registryOverride included in the image metadata extraction flow"

- docs/content/how-to/etcd-recovery.md
- docs/mkdocs.yml
Includes documentation for recovering a single member. Documentation for recovering from quorum loss is still pending.
Fixes #[HOSTEDCP-1075](https://issues.redhat.com/browse/HOSTEDCP-1075)
**Checklist**
> HOSTEDCP-1075: Document how to recover single etcd member

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/ignition/params.go
- control-plane-operator/controllers/hostedcontrolplane/ignition/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/ignition.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
- support/globalconfig/imagecontentsource.go
Reverts openshift/hypershift#2839
> Revert "HOSTEDCP-1110: [backport-4.13] Allow HCP Specification to Support ICSP & IDMS"

- test/e2e/util/util.go
We have painted ourselves into a corner with the current `EnsureComponentsHaveNeedManagementKASAccessLabel` check.
It is currently implemented as a match list, not an allowlist.  The list of components that have the `NeedManagementKASAccessLabel` must _exactly match_ the list of `components`.
This leads to a situation where there is no workable way to add or remove the label from components, as the e2e binary image is update immediately upon merge and will be used to test against older CPOs.
This PR converts the check into an allowlist such that if a component is on the allowlist but doesn't have the `NeedManagementKASAccessLabel`, it does not fail the test.
After this change, removing the label from a component can be done in 2 steps:
* remove the label from the component and wait for …
> OCPBUGS-17827: e2e: refactor checkPodsHaveLabel to be allowlist rather than exact match

- cmd/infra/powervs/destroy.go
- cmd/infra/powervs/validate.go
Fixes #
Fixes https://issues.redhat.com/browse/MULTIARCH-3478
**Checklist**
> MULTIARCH-3478: Minor bug fix on PowerVS infra

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
- control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/kas/egresscfg.go
- control-plane-operator/controllers/hostedcontrolplane/kas/params.go
- control-plane-operator/controllers/hostedcontrolplane/kas/service.go
- control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go
- control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/pki/konnectivity.go
https://issues.redhat.com/browse/OCPBUGS-16813
> OCPBUGS-16813: switch konnectivity-server to additional container in KAS pods

- hypershift-operator/controllers/hostedcluster/ignitionserver/ignitionserver.go
**What this PR does / why we need it**: Mimics the implementation for the fix employed in https://github.com/openshift/hypershift/pull/2949 to restore match label selector behavior without copying over the pod template so as to keep them separate in case new labels are added to either component in the future. 
Fixes #
**Checklist**
> fix(ho): Restore match label selector behavior

- cmd/cluster/core/dump.go
This PR adds a flag for the dump command. The flag is `--archive-dump`. By default it follows the current behavior of dump command and creates a tar archive at the end of the dump. When we pass `--archive-dump=false` it avoid creating the archive.
We are using `hypershift dump cluster` in an effort to create a must-gather compatible package. We plan to organize the files after the dump is created and then archive them. But the default tar behavior will take extra space and processing time. So we would like to add this optional flag to help with the script.
Currently this does not …
> Avoid creating tar archive if --archive-dump=false

- control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go
**What this PR does / why we need it**: Similar fix to https://github.com/openshift/hypershift/pull/2949, this is needed to avoid upgrade restrictions.
Fixes #
**Checklist**
> fix(hcco): Add HCP label to HCCO by default

- control-plane-operator/controllers/hostedcontrolplane/kas/service.go
AWS uses the HCP router by default where kubevirt uses the mgmt cluster default cluster ingress (OCP router) by default.  OCP router sets `balance source` on the haproxy backend which means that only one backend `server` is ever choosen for a particular source IP.  This resulted in the konnectivity-agent on the guest cluster nodes being unable to connect to more than one konnectivity-server, no matter how many attempts were made.
This PR overrides the `balance` to be `roundrobin`.
> OCPBUGS-18336: make konnectivity routes roundrobin

- hypershift-operator/main.go
https://github.com/openshift/hypershift/pull/2956 resulted in a ~4x increase in HO reads because of unstructured objects not being cached by the client.
This enables caching of unstructured objects in the HO.
Fixes #
**Checklist**
> OCPBUGS-18127: Enable caching of Unstructured Objects in HO

- api/v1beta1/nodepool_conditions.go
- hypershift-operator/controllers/nodepool/inplace.go
- hypershift-operator/controllers/nodepool/nodepool_controller.go
- support/conditions/conditions.go
- test/e2e/nodepool_rolling_upgrade_test.go
Fixes #[HOSTEDCP-1133](https://issues.redhat.com/browse/HOSTEDCP-1133)
**Checklist**
> HOSTEDCP-1133: Signal NodePool rolling upgrade because of platform changes

- control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
> fix(olm): Use 4.13 catalog source images

- cmd/cluster/core/dump.go
- kubevirtexternalinfra/externalinfra.go
When using kubevirt provider with an external infra cluster, the dump now will include the info for this cluster as well.
In this case, the dump directory will include a new `external-infra-clusters` directory, containing a directory for each external infra cluster used; e.g.
```
dump-dir
+- external-infra-clusters
+- nodepool-<node pool UID>
```
Also, if kubevirt is not installed on the management cluster, the dump log won't include errors about unknown resource types.
**Checklist**
> Dump kubevirt external infra clusters

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
- hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go
- support/releaseinfo/fake/fake.go
- support/supportedversion/version.go
- support/supportedversion/version_test.go
used https://github.com/openshift/hypershift/pull/2249 as a template
> bump HO supported version for 4.15

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
> OCPBUGS-18122: Rename isUpgradeable to isUpgrading according to its return value

- cmd/cluster/core/dump.go
Add the log of KubeVirt pods, to the dump result.
**Checklist**
> Dump KubeVirt pod logs

- test/e2e/util/util.go
> Relax network policy e2e for private

- control-plane-operator/controllers/hostedcontrolplane/cloud/aws/params.go
- control-plane-operator/controllers/hostedcontrolplane/cloud/aws/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
https://issues.redhat.com/browse/OCPBUGS-19346
cc @csrwng
> OCPBUGS-19346: set default deploymentconfig params on AWS CCM

- api/v1beta1/hostedcluster_types.go
- support/supportedversion/version.go
- support/supportedversion/version_test.go
> OCPBUGS-19381: Let NodePools skip min version when SkipReleaseImageValidation is in HC

- docs/content/how-to/kubevirt/troubleshooting-kubevirt-cluster.md
This PR adds more troubleshooting steps that are specific to the KubeVirt platform.
> KubeVirt platform troubleshooting documentation

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
- .tekton/hypershift-release-414-pull-request.yaml
- .tekton/hypershift-release-414-push.yaml
Migrate deprecated-base-image-check pipeline
Fixes #
**Checklist**
> Migrate deprecated-base-image-check pipeline

- docs/content/how-to/azure/create-azure-cluster.md
> Upate azure docs

- docs/content/how-to/kubevirt/troubleshooting-kubevirt-cluster.md
Fix a typo in KubeVirt troubleshooting script
Fixes #
**Checklist**
> [doc] Fix a typo in KubeVirt troubleshooting script

- cmd/install/assets/recordingrules/hypershift.yaml
- hack/app-sre/saas_template.yaml
This is so we get this info into the CI grafana metrics
Fixes #
**Checklist**
> Add record rules for kas qps

- hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
- hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes_test.go
This add two changes in logic:
1 - For HCs that are already scheduled but there's no two running Nodes will let reconciliation continue to find new Nodes. https://issues.redhat.com/browse/OCPBUGS-20105.
2 - Scheduler will only find paired Nodes via osd-fleet-manager.openshift.io/paired-nodes label. https://issues.redhat.com/browse/OCPBUGS-20109.
Fixes https://issues.redhat.com/browse/OCPBUGS-20109
Fixes https://issues.redhat.com/browse/OCPBUGS-20105
**Checklist**
> OCPBUGS-20105: OCPBUGS-20109: Update the scheduler to only accept paired Nodes and check scheduler HCs has two Nodes

- hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
Reconciles the OpenShift Cloud Network Config Controller to the CPO namespace.
Fixes [OCPBUGS-19957](https://issues.redhat.com/browse/OCPBUGS-19957)
**Checklist**
> OCPBUGS-19957: Reconcile CNCC secret to CPO namespace

- hypershift-operator/controllers/hostedcluster/internal/platform/powervs/powervs.go
> MULTIARCH-3760: Rename depricated flag for PowerVS capi deployment

- control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
> OCPBUGS-21822: Add ign proxy label selector for LabelTopologyZone PodAntiAffinity

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Without this the selector check was always nil resulting in the controller always enforcing the labels
Fixes #
**Checklist**
> OCPBUGS-22195: Fix label selector check for CAPI provider

- api/v1beta1/hostedcluster_types.go
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
- hack/app-sre/saas_template.yaml
Fixes #[OCPBUGS-20033](https://issues.redhat.com/browse/OCPBUGS-20033)
> OCPBUGS-20033: Make the OLMCatalogPlacement field immutable

- api/v1alpha1/hostedcluster_types.go
- api/v1beta1/hostedcluster_types.go
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml
- control-plane-operator/controllers/hostedcontrolplane/etcd/etcd-init.sh
- control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile_test.go
- docs/content/how-to/aws/etc-backup-restore.md
- docs/content/reference/api.md
- hack/app-sre/saas_template.yaml
Fixes #[HOSTEDCP-1215](https://issues.redhat.com/browse/HOSTEDCP-1215)
Fixes https://github.com/openshift/hypershift/issues/2736
**Checklist**
> HOSTEDCP-1215: Use the same etcd snapshot for all replicas during etcd restore

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
Fixes log formatting for release image in hcp controller
Fixes #
**Checklist**
> NO-JIRA: fix formatting for releaseImage log

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
- control-plane-operator/controllers/hostedcontrolplane/kas/params.go
- control-plane-operator/controllers/hostedcontrolplane/kas/service.go
- control-plane-operator/controllers/hostedcontrolplane/kas/servicemonitor.go
- support/util/networking.go
> HOSTEDCP-1285: Consume kas Pod port by name

- docs/content/how-to/kubevirt/create-kubevirt-cluster.md
This adds documentation around MTU recommendations for HyperShift/KubeVirt
> CNV-30444: Document recommended MTU settings for KubeVirt HCP

- main.go
- test/e2e/e2e_test.go
fixes https://issues.redhat.com/browse/OCPBUGS-23314
I need help verifying this as I have been unable to reproduce.
> OCPBUGS-23314: SetLogger for CLI

- cmd/install/assets/hypershift_operator.go
- cmd/install/install.go
- hack/app-sre/saas_template.yaml
> HOSTEDCP-1256: expose cert rotation scale parameter

- control-plane-operator/controllers/hostedcontrolplane/kas/aws_kms.go
Fixes #[OCPBUGS-23398](https://issues.redhat.com/browse/OCPBUGS-23398)
**Checklist**
> OCPBUGS-23398: Fixed AWS KMS Backup container args

- cmd/cluster/core/destroy.go
Attempting to destroy an AWS cluster can result in an error indicating that the CLI is trying to add a finalizer. This is likely due to a conflict between the HostedCluster CR that the CLI has in memory and the current version of the CR. This change adds a retry loop and invokes the patch operation with optimistic concurrency lock
Fixes #OCPBUGS-23528
**Checklist**
> OCPBUGS-23528: Fix error when removing finalizer on cluster destroy

- api/hypershift/v1alpha1/endpointservice_types.go
- api/hypershift/v1alpha1/hosted_controlplane.go
- api/hypershift/v1alpha1/hostedcluster_types.go
- api/hypershift/v1beta1/endpointservice_types.go
- api/hypershift/v1beta1/hostedcluster_types.go
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_awsendpointservices.yaml
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml
- hack/app-sre/saas_template.yaml
Follow-up for https://github.com/openshift/hypershift/pull/3211 to get the rest
> HOSTEDCP-1256: api/hypershift: mark more conditions with list key types

- cmd/nodepool/create.go
- control-plane-operator/controllers/hostedcontrolplane/machineapprover/reconcile.go
It does nothing. It only serves to rehearse the hotfix process
Fixes #[HOSTEDCP-1301](https://issues.redhat.com//browse/HOSTEDCP-1301)
**Checklist**
> HOSTEDCP-1301:	hotfix rehearsal

- api/fixtures/example.go
- cmd/cluster/azure/create.go
- cmd/install/assets/hypershift_operator.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- docs/content/how-to/azure/create-azure-cluster.md
- hypershift-operator/controllers/hostedcluster/network_policies.go
> HOSTEDCP-1236: Enable public router+external DNS for azure

- control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/oauth.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/oauth/reconcile.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
https://issues.redhat.com/browse/OCPBUGS-23555
> OCPBUGS-23555: add CLI oauthclient

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
https://issues.redhat.com/browse/HOSTEDCP-1318
xref https://github.com/openshift/openshift-apiserver/pull/395
> HOSTEDCP-1318: pass internal-oauth-disable flag to openshift-apiserver when Auth type is OIDC

- control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/oauth.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/oauth/reconcile.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
manual pick of #3238 and #3249
> [release-4.14] OCPBUGS-24269: add CLI oauthclient

- docs/content/reference/manifests/ibmcloud/4.10.md
- docs/content/reference/manifests/ibmcloud/4.11.md
- docs/content/reference/manifests/ibmcloud/4.12.md
- docs/content/reference/manifests/ibmcloud/4.13.md
- docs/content/reference/manifests/ibmcloud/4.9.md
- docs/content/reference/manifests/index.md
- docs/mkdocs.yml
Supersedes:
- https://github.com/openshift/hypershift/pull/2841
- https://github.com/openshift/hypershift/pull/2842
- https://github.com/openshift/hypershift/pull/2843
- https://github.com/openshift/hypershift/pull/2844
- https://github.com/openshift/hypershift/pull/2845
Fixes #
**Checklist**
> HOSTEDCP-1343: docs(ibmcloud): Add HC/HCP yamls for IBM Cloud

- hypershift-operator/controllers/platform/aws/controller.go
- hypershift-operator/controllers/platform/aws/controller_test.go
Confusingly, AWS arns that include a path are not valid IAM principals, the path needs to be removed before they are applied to VPC Endpoint Service additional allowed principals.
Fixes OCPBUGS-23511
**Checklist**
/area hypershift-operator
> OCPBUGS-23511: Remove IAM path when applying control-plane-operator ARN to VPC Endpoint Service allowed principals

- control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/reconcile.go
**What this PR does / why we need it**: Use 10% rather than 1 for maxUnavailable since agents are independant.
Fixes # https://issues.redhat.com/browse/OCPBUGS-24261
**Checklist**
> OCPBUGS-24261: Konnectivity agent update strategy

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
Migration of https://github.com/openshift/hypershift/pull/3194
> NO-JIRA: RHTAP Multi-Arch PipelineSpec

- cmd/util/secrets.go
- control-plane-operator/controllers/hostedcontrolplane/ignition/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/kcm/config.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/ingress.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/oauth.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_oauth_apiserver.go
- control-plane-operator/controllers/hostedcontrolplane/pki/openshift.go
- control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/creds.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/monitoring.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/openshift_apiserver.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/openshift_controllermanager.go
- hypershift-operator/controllers/manifests/ignitionserver/manifests.go
- support/assets/readasset.go
- support/globalconfig/imagecontentsource.go
- support/rhobsmonitoring/scheme.go
- support/util/networking.go
Removes unused functions from repo
Fixes [HOSTEDCP-1355](https://issues.redhat.com/browse/HOSTEDCP-1355)
**Checklist**
> HOSTEDCP-1355: Remove unused functions from repo

- control-plane-operator/hostedclusterconfigoperator/controllers/hcpstatus/hcpstatus.go
https://issues.redhat.com/browse/OCPBUGS-23518
> OCPBUGS-23518: consider HCP upgradeable if CVO has no upgradable condition

- docs/content/how-to/kubevirt/external-infrastructure.md
Fixing #3364 as validated at https://github.com/openshift/release/pull/47248
https://github.com/openshift/release/blob/dfe99ad69ace3195ea73fcd30265e8d9cc2b9f81/ci-operator/step-registry/hypershift/kubevirt/install/create-external-infra-kubeconfig/hypershift-kubevirt-install-create-external-infra-kubeconfig-commands.sh#L44-L81
Fixes #
**Checklist**
> NO-JIRA: [KubeVirt] Fix external infra permissions documentation

- cmd/install/assets/hypershift_operator.go
- hack/app-sre/saas_template.yaml
WIP: need to verify that external dns in e2e mgmt cluster is making fewer calls
> OCPBUGS-26547: reduce external-dns route53 call volume

- cmd/install/install.go
- hack/app-sre/saas_template.yaml
> NO-JIRA: remove non-existent v1beta2 from webhook

- hypershift-operator/controllers/nodepool/nodepool_controller.go
- hypershift-operator/controllers/nodepool/nodepool_controller_test.go
The current set the message of the "AllMachinesReady" nodepool condition to be a list of machine "Ready" condition reasons.
This is not always enough. the cluster-api sets more verbose messages in the machine "InfrastructureReady". This PR changes the nodepool controller to check if there is a valid message in the machine InfrastructureReady condition, and use it instead of the Reason field from the Ready condition, to help the user to understand what actually happening, when not all the machines are ready.
**Checklist**
> NO-JIRA: Improve nodepool's machine condition message

- control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
- control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/kas/params.go
- ignition-server/controllers/local_ignitionprovider.go
This is a cherry-pick of https://github.com/openshift/hypershift/pull/3400
/assign Patryk-Stefanski
> [release-4.15] OCPBUGS-27155: Change KAS bootstrap image to cluster-config-api

- docs/content/how-to/automated-machine-management/configure-machines.md
- docs/mkdocs.yml
Adds a document explaining how machines are configured in HyperShift
Fixes #
**Checklist**
> NO-JIRA: Document machine configuration in HyperShift

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
Includes RHTAP updates and fixes things needed from the migration - https://github.com/redhat-appstudio/build-definitions/blob/main/task/init/0.2/MIGRATION.md
N/A
**Checklist**
> NO-JIRA: Update RHTAP references (main)

- .ci-operator.yaml
> NO-ISSUE: .ci-operator.yaml: base off of RHEL 9

- support/releaseinfo/releaseinfo.go
There is a change in the original function `readComponentVersions` as seen https://github.com/openshift/oc/pull/1662 and this PR mirrors the same changes in here.
**Checklist**
> NO-JIRA: Simplified kubectl component version check

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
- .tekton/hypershift-release-414-pull-request.yaml
- .tekton/hypershift-release-414-push.yaml
Includes RHTAP updates and fixes things needed from the migration - https://github.com/redhat-appstudio/build-definitions/blob/main/task/init/0.2/MIGRATION.md
N/A
**Checklist**
> NO-JIRA: Update RHTAP references (release-4.14)

- Makefile
- hack/tools/release/notes.go
Add a more clear error message and return on error in release note tool.  Also add support for an authorization token so we can avoid 403 errors.
Fixes #
**Checklist**
> NO-JIRA: Fix issue with release note tool

- control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/cpo.go
- control-plane-operator/hostedclusterconfigoperator/cmd.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/controllers/manifests/manifests.go
- hypershift-operator/controllers/nodepool/haproxy.go
- hypershift-operator/controllers/nodepool/nodepool_controller.go
- hypershift-operator/main.go
- ignition-server/controllers/local_ignitionprovider.go
- support/releaseinfo/fake/fake.go
- support/releaseinfo/registry_image_content_policies.go
- support/releaseinfo/releaseinfo.go
- support/util/deployment.go
- support/util/fakeimagemetadataprovider/fakeimagemetadataprovider.go
- support/util/imagemetadata.go
- support/util/imagemetadata_test.go
Manual cherry pick
**Checklist**
> [release-4.14] OCPBUGS-29000,OCPBUGS-28984,OCPBUGS-28985,OCPBUGS-28986,OCPBUGS-19956: Support Disconnected HCP

- control-plane-pki-operator/OWNERS
- test/integration/OWNERS
@stevekuznetsov is the primary contributor to these components
> NO-JIRA: stevekuznetsov approver on CPPO and integration tests

- contrib/ci/AzureCI/README.md
- contrib/ci/AzureCI/hypershift-install-azure.yaml
**What this PR does / why we need it**: Adds docs for setting up Azure CI
Fixes # [HOSTEDCP-1407](https://issues.redhat.com/browse/HOSTEDCP-1407)
**Checklist**
- [] This change includes docs.
> HOSTEDCP-1407: Add steps for seting up  azure CI cluster

- cmd/infra/powervs/create.go
- cmd/infra/powervs/destroy.go
- cmd/infra/powervs/service_id.go
- cmd/infra/powervs/service_id_test.go
This is a cherry-pick of https://github.com/openshift/hypershift/pull/3491
> [release-4.14]  MULTIARCH-4084: Reduce the policy access scope to specific instance

- cmd/infra/powervs/create.go
- cmd/infra/powervs/destroy.go
- cmd/infra/powervs/service_id.go
- cmd/infra/powervs/service_id_test.go
This is a cherry-pick of #3491
> [release-4.15] MULTIARCH-4084: Reduce the policy access scope to specific instance

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/kas/config.go
CPO is in the payload now and does not need to do version detection
> NO-JIRA: remove dead code from kas config

- control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/cco/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/cco/reconcile_test.go
- control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator_test.go
- control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/dnsoperator/dnsoperator.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
- control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go
- control-plane-operator/controllers/hostedcontrolplane/kas/service.go
- control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/machineapprover/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/olm/operator.go
- control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go
- control-plane-operator/controllers/hostedcontrolplane/pki/kas.go
- control-plane-operator/controllers/hostedcontrolplane/scheduler/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator.go
- control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator_test.go
- control-plane-operator/controllers/hostedcontrolplane/storage/operator.go
- hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
- hypershift-operator/controllers/hostedcluster/network_policies.go
- support/config/constants.go
This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/3569
> [release-4.15] OCPBUGS-29780: use 2040 for apiserver svc in IBM provider

- control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
missed this one in https://github.com/openshift/hypershift/pull/3616
> NO-JIRA: adjust pdb for oauth-apiserver

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
**What this PR does / why we need it**:  Skips SG deletion to proceed with cluster deletion if there is a dependency violation with the SG (SG referenced by other non-hypershift controller resources), Also bubbles up an error to the HC to point to specific SG that hasn't been deleted.
Fixes # [OCPBUGS-28370](https://issues.redhat.com/browse/OCPBUGS-28370)
HC CR remains on cluster with following error in status
```
2024-02-22T11:33:29Z'
message: 'failed to delete AWS default security group due to dependency violation, security group: sg-0b9093871a'
observedGeneration: 4
reason: AWSError
status: 'False'
type: …
```
> OCPBUGS-28370: Skip SG deletion if it has dependancy violation

- control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
- Removes specific watch for pull secret as general watch for secrets already covers this.
Fixes #
**Checklist**
> NO-JIRA: Remove specific pull secret watch in HCCO

- test/integration/control_plane_pki_operator.go
In a test flake we're seeing the following flow play out:
1. request a new signed client certificate via CSR
2. get it signed, create $KUBECONFIG
3. send SSR to server, get unauthz
This is unexpected. To debug how/why we're seeing the error, we need both the client certificate we got back and the server's current trust bundle.
> NO-JIRA: test: debug certificates on unauthz error

- control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator_test.go
- control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/dnsoperator/dnsoperator.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
- control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go
- control-plane-operator/controllers/hostedcontrolplane/kas/service.go
- control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/machineapprover/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/olm/operator.go
- control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go
- control-plane-operator/controllers/hostedcontrolplane/pki/kas.go
- control-plane-operator/controllers/hostedcontrolplane/scheduler/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator.go
- control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator_test.go
- control-plane-operator/controllers/hostedcontrolplane/storage/operator.go
- hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
- hypershift-operator/controllers/hostedcluster/network_policies.go
- support/config/constants.go
This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/3569
> [release-4.14] OCPBUGS-29782: use 2040 for apiserver svc in IBM provider

- docs/content/how-to/azure/create-azure-cluster.md
Just cleaning up the Azure create cluster instructions to differentiate between creating a nominal Azure HC and one with externalDNS.  
Fixes #
**Checklist**
> NO-JIRA: Minor cleanup of Azure create cluster document

- control-plane-operator/controllers/hostedcontrolplane/kas/config.go
supercedes https://github.com/openshift/hypershift/pull/3668
> OCPBUGS-30124: do not set KAS OAuthMetadataFile with Authentication type OIDC

- api/hypershift/v1beta1/hostedcluster_types.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
> OCPBUGS-30281: [release-4.15] OCPBUGS-30102: Support to disable machine management components

- cmd/install/assets/hypershift_operator.go
- cmd/install/install.go
- hack/app-sre/saas_template.yaml
Fixes [HOSTEDCP-1464](https://issues.redhat.com/browse/HOSTEDCP-1464)
**Checklist**
> HOSTEDCP-1464: Add pull secret to install CLI & create k8s secret

- hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
If a label of `hypershift.openshift.io/request-serving-gomemlimit` is found in the request serving nodes for a given HostedCluster, the HostedCluster will get an annotation of
`hypershift.openshift.io/kube-apiserver-gomemlimit` with the same value.
Fixes #[HOSTEDCP-1469](https://issues.redhat.com/browse/HOSTEDCP-1469)
**Checklist**
> HOSTEDCP-1469: Set GOMEMLIMIT annotation based on request serving node label

- cmd/infra/powervs/create.go
- go.mod
- go.sum
- vendor/github.com/IBM/networking-go-sdk/directlinkv1/direct_link_v1.go
- vendor/modules.txt
> HOSTEDCP-1479: Update IBM/networking-go-sdk package

- hypershift-operator/controllers/nodepool/aws.go
- hypershift-operator/controllers/nodepool/aws_test.go
- hypershift-operator/controllers/nodepool/nodepool_controller.go
- hypershift-operator/controllers/nodepool/nodepool_controller_test.go
Fixes #[HOSTEDCP-929](https://issues.redhat.com/browse/HOSTEDCP-929)
**Checklist**
> HOSTEDCP-929: Add nodepool annotation to allow requesting IMDSv2

- hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
In the dedicated request serving node reaper, we want to react to the deletion of hosted clusters and reap the related nodes. Today, we only watch nodes and effectively turn our controller into a polling-based actuator when the hosted clusters still exist. Instead, this change wires up the controller to watch hosted clusters and enqueue any nodes related to those clusters. This allows us to remove our polling logic and react to hosted cluster deletion directly.
/assign @csrwng @sjenning
> NO-ISSUE: hypershift-operator: react to hosted cluster changes

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
**What this PR does / why we need it**: Manual backport for [OCPBUGS-28370](https://issues.redhat.com/browse/OCPBUGS-28370) because fix had two seperate MRs  #3622  & #3661 
Fixes # [OCPBUGS-30742](https://issues.redhat.com/browse/OCPBUGS-30742)
**Checklist**
> OCPBUGS-30742: [4.15] HCP deletion can get stuck if CPO is unable to delete the default worker security group

- control-plane-operator/controllers/hostedcontrolplane/kas/kms/ibmcloud.go
Enable support for KMS v2 and removes a check which had been broken by some earlier changes in https://github.com/openshift/hypershift/pull/3183.
For https://issues.redhat.com/browse/OCPBUGS-30968
Fixes #
**Checklist**
> OCPBUGS-30968: ibmcloud KMS: remove breaking image check and enable KMS v2 support

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/kas/auth.go
- control-plane-operator/controllers/hostedcontrolplane/kas/config.go
- control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
> OCPBUGS-30991: external OIDC: fix certificateAuthority field in structured auth config

- ignition-server/controllers/local_ignitionprovider.go
This is a manual  cherry-pick of https://github.com/openshift/hypershift/pull/3685 & https://github.com/openshift/hypershift/pull/3727
> [release-4.15] OCPBUGS-30862: Manual cherry pick 3685&3727 to release 4.15

- cmd/infra/azure/create.go
Fix loopvar issue in a range loop.
> OCPBUGS-31088: Fix loopvar issue

- api/hypershift/v1alpha1/hostedcluster_types.go
- api/hypershift/v1beta1/hostedcluster_types.go
- client/applyconfiguration/hypershift/v1alpha1/azureplatformspec.go
- client/applyconfiguration/hypershift/v1beta1/azureplatformspec.go
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml
- control-plane-operator/controllers/hostedcontrolplane/cloud/azure/providerconfig.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- docs/content/reference/api.md
- hack/app-sre/saas_template.yaml
- support/conditions/conditions.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1alpha1/hostedcluster_types.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
> OCPBUGS-31076: Support other azure clouds

- cmd/infra/azure/create.go
Manually cherry-pick #3782 to release-4.15.
> [release-4.15] OCPBUGS-31377: Manually cherry pick #3782 to 4.15

- control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
- control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
- control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
- control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/konnectivity/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/machineapprover/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/nto/clusternodetuningoperator.go
- control-plane-operator/controllers/hostedcontrolplane/olm/operator.go
- control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go
This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/3120 to the `release-4.15` branch.
> HOSTEDCP-1438: [release-4.15] Preserve container resources for more hosted control plane components

- docs/content/how-to/disconnected/known-issues.md
Document additional known issues for the disconnected scenario with, for each of them, an explicit reference to a bug tracking it so that we can remove them as we fix the gaps.
Fixes https://issues.redhat.com/browse/CNV-38570
**Checklist**
> NO-JIRA: Document additional known issues for the disconnected scenario

- hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go
> NO-JIRA: bump capk ci image

- hypershift-operator/controllers/hostedclustersizing/hostedclustersizing_controller.go
- hypershift-operator/controllers/hostedclustersizing/hostedclustersizing_controller_test.go
- hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes_test.go
- hypershift-operator/controllers/scheduler/placeholders.go
- hypershift-operator/controllers/scheduler/placeholders_test.go
- test/integration/hosted_cluster_sizing_test.go
@csrwng added the constant a second time in the API module but did not move the previous usages over
> NO-ISSUE: *: use the api package constant for the size label

- hypershift-operator/controllers/nodepool/metrics/metrics.go
- hypershift-operator/controllers/nodepool/metrics/metrics_test.go
This PR is changing the metric used for billing. The billing is indeed per *vCpu* and not per *core*.
This issue corrects a mistake introduced in [OSD-19085](https://issues.redhat.com//browse/OSD-19085).
**Checklist**
> OSD-19085: Replaced hypershift_cluster_cores metric with hypershift_cluster_vcpus metric

- cmd/install/assets/hypershift_operator.go
- cmd/install/install.go
- contrib/aks/setup_aks_cluster.sh
- contrib/aks/setup_external_dns.sh
- contrib/aks/setup_install_ho_on_aks.sh
- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go
- control-plane-operator/controllers/hostedcontrolplane/pki/azure_disk_csi_driver_controller.go
- control-plane-operator/controllers/hostedcontrolplane/pki/azure_file_csi_driver_controller.go
- control-plane-operator/controllers/hostedcontrolplane/pki/cert.go
- control-plane-operator/controllers/hostedcontrolplane/pki/cert_test.go
- control-plane-operator/controllers/hostedcontrolplane/pki/etcd.go
- control-plane-operator/controllers/hostedcontrolplane/pki/multus_admission_controller.go
- control-plane-operator/controllers/hostedcontrolplane/pki/network_node_identity.go
- control-plane-operator/controllers/hostedcontrolplane/pki/ovn_control_plane_metrics.go
- docs/content/how-to/azure/create-azure-cluster_on_aks.md
- docs/mkdocs.yml
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- support/capabilities/management_cluster_capabilities.go
We need to be able to create HCPs with externalDNS on AKS clusters for ARO HCP.
Fixes [HOSTEDCP-1465](https://issues.redhat.com/browse/HOSTEDCP-1465)
**Checklist**
> HOSTEDCP-1465: Create HCPs with externalDNS on AKS Clusters

- test/e2e/e2e_test.go
this is a manual backport of #3854 
Fixes #
**Checklist**
> NO-JIRA: [release-4.15] [e2e test framework] Add a flag to add an annotation to HostedCluster

- control-plane-operator/controllers/hostedcontrolplane/kas/auditcfg.go
- control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/auditcfg.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
related: https://github.com/openshift/hypershift/issues/3764
Fixes #
**Checklist**
> OCPBUGS-32191: Kas disable audit cherry pick release 4.15

- test/e2e/e2e_test.go
manual backport of #3854
Fixes #
**Checklist**
> NO-JIRA: [4.14] [e2e test framework] Add a flag to add an annotation to Hosted Cluster

- hypershift-operator/controllers/scheduler/placeholders.go
> NO-ISSUE: placeholders: ignore auto-sizer placeholders

- cmd/install/assets/hypershift_operator.go
- cmd/install/install.go
- contrib/aks/setup_aks_cluster.sh
- contrib/aks/setup_external_dns.sh
- contrib/aks/setup_install_ho_on_aks.sh
- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go
- control-plane-operator/controllers/hostedcontrolplane/pki/azure_disk_csi_driver_controller.go
- control-plane-operator/controllers/hostedcontrolplane/pki/azure_file_csi_driver_controller.go
- control-plane-operator/controllers/hostedcontrolplane/pki/cert.go
- control-plane-operator/controllers/hostedcontrolplane/pki/cert_test.go
- control-plane-operator/controllers/hostedcontrolplane/pki/etcd.go
- control-plane-operator/controllers/hostedcontrolplane/pki/multus_admission_controller.go
- control-plane-operator/controllers/hostedcontrolplane/pki/network_node_identity.go
- control-plane-operator/controllers/hostedcontrolplane/pki/ovn_control_plane_metrics.go
- docs/content/how-to/azure/create-azure-cluster_on_aks.md
- docs/mkdocs.yml
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- support/capabilities/management_cluster_capabilities.go
Reverts openshift/hypershift#3890
> Revert "Revert "HOSTEDCP-1465: Create HCPs with externalDNS on AKS Clusters""

- api/hypershift/v1beta1/hostedcluster_types.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/params.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile_test.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Manual cherry-pick of https://github.com/openshift/hypershift/pull/3848
Fixes #
**Checklist**
> HOSTEDCP-1519: [release-4.15] feat(api): Add ingress-controller-load-balancer-scope annotation

- test/e2e/autoscaling_test.go
> NO-JIRA: reduce autoscaling test memory requests

- cmd/install/assets/recordingrules/hypershift.yaml
- hack/app-sre/saas_template.yaml
Fixes #[HOSTEDCP-1044](https://issues.redhat.com/browse/HOSTEDCP-1044)
**Checklist**
> HOSTEDCP-1044: Add NodePool Size/Replicas to Telemetry

- api/hypershift/v1beta1/hostedcluster_types.go
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml
- docs/content/reference/api.md
- hack/app-sre/saas_template.yaml
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
Adds API definitions and k8s cel to fields within AzurePlatformSpec
Fixes [HOSTEDCP-1522](https://issues.redhat.com/browse/HOSTEDCP-1522)
**Checklist**
> HOSTEDCP-1522: Add API definitions and CEL for AzurePlatformSpec vars

- control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go
Follow-on fix for https://github.com/openshift/hypershift/pull/3846
> OCPBUGS-14383: fix setting replicas on autoscaler

- docs/content/how-to/azure/create-azure-cluster_on_aks.md
Added a few changes to the doc: explicitly call out this started in 4 .16, add FIPS enablement flags, remove expected failures since those are fixed now
N/A
**Checklist**
> NO-JIRA: Minor doc updates to creating Azure HC on AKS

- hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
The logical flows in the request serving node component scheduler and sizer are complex; we need a little more insight into what decisions we're taking, when, and why.
> NO-JIRA: sizing: add logging for what we're doing

- control-plane-operator/controllers/hostedcontrolplane/kas/kms/azure.go
Fixes #[HOSTEDCP-1525](https://issues.redhat.com/browse/HOSTEDCP-1525)
**Checklist**
> HOSTEDCP-1525: Fixed azure using incorrect kms socket

- hypershift-operator/controllers/hostedclustersizing/hostedclustersizing_validation_controller.go
> OCPBUGS-33320: Fix nil dereference in clustersizingconfig validation

- cmd/infra/aws/create_cli_role.go
- cmd/infra/aws/iam.go
- cmd/infra/create_iam.go
Fixes #[HOSTEDCP-1560](https://issues.redhat.com/browse/HOSTEDCP-1560)
**Checklist**
> HOSTEDCP-1560: Create AWS STS Role for the hypershift/hcp cli 

- test/e2e/util/hypershift_framework.go
Currently, if `dumpCluster()` fails, the HostedCluster is not deleted, leaving behind all of its AWS resources.  This is a problem.
> TRT-1672: e2e: proceed with teardown even if dump fails

- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator_test.go
- control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
- control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Preserve_existing_resources.yaml
- control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Private_apiserver_connectivity__proxy_apiserver_address_is_unset.yaml
- control-plane-operator/controllers/hostedcontrolplane/olm/operator.go
- control-plane-operator/controllers/hostedcontrolplane/olm/operator_test.go
- control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go
- control-plane-operator/controllers/hostedcontrolplane/olm/packageserver_test.go
- control-plane-operator/controllers/hostedcontrolplane/olm/testdata/zz_fixture_TestReconcileCatalogOperatorDeployment_Preserve_existing_resources.yaml
- control-plane-operator/controllers/hostedcontrolplane/olm/testdata/zz_fixture_TestReconcileOLMOperatorDeployment_Preserve_existing_resources.yaml
This is a manual cherry-pick of the changes from https://github.com/openshift/hypershift/pull/3864.
> [release-4.15] HOSTEDCP-1518: Preserve container resource requests and limits

- control-plane-operator/main.go
> OCPBUGS-32257: Fix userReleaseProvider not using icsp/idms from mgmt cluster

- control-plane-operator/controllers/hostedcontrolplane/kas/kms/azure.go
Encountered the following error when testing https://issues.redhat.com/browse/HOSTEDCP-1525 (ETCD key rotation for Azure):
```go
oc logs -n clusters-fxie-hcp-1 kube-apiserver-7f67c5bbfc-npxzx -c azure-kms-provider-backup
I0521 09:57:31.476088       1 exporter.go:17] "metrics backend" exporter="prometheus"
I0521 09:57:31.476325       1 prometheus_exporter.go:56] "Prometheus metrics server running" address="8095"
I0521 09:57:31.476344       1 main.go:90] "Starting KeyManagementServiceServer service" version="" buildDate=""
I0521 09:57:31.476732       1 keyvault.go:134] "using kms key for encrypt/decrypt" vaultURL="https://fxie-1234-kv2.vault.azure.net/" keyName="fxie-1234-key-2" keyVersion="f0ee8559ebea408facf44d60d847363f"
E0521 09:57:31.476942       1 prometheus_exporter.go:53] …
```
> OCPBUGS-34019: Make active & backup Azure KMS containers use different --metrics-addr

- hypershift-operator/controllers/scheduler/autoscaler.go
In some situations, the presence of a placeholder pod does not cause the autoscaler to reconcile. This adds a regular sync to the autoscaler regardless of pod events.
Fixes #[OCPBUGS-34095](https://issues.redhat.com/browse/OCPBUGS-34095)
**Checklist**
> OCPBUGS-34095: Sync the autoscaler periodically

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment_test.go
- support/util/volumes.go
Fixes #[OCPBUGS-31446](https://issues.redhat.com/browse/OCPBUGS-31446)
> OCPBUGS-31446: Add TrustedBundles to OAS container

- cmd/cluster/aws/create.go
- cmd/cluster/aws/create_test.go
- cmd/cluster/aws/destroy.go
- cmd/cluster/aws/destroy_test.go
- cmd/cluster/core/create.go
- cmd/cluster/core/destroy.go
- cmd/consolelogs/aws/getlogs.go
- cmd/infra/aws/create.go
- cmd/infra/aws/create_iam.go
- cmd/infra/aws/destroy.go
- cmd/infra/aws/destroy_iam.go
- cmd/infra/aws/util/sts.go
- cmd/infra/aws/util/util.go
- cmd/util/secrets.go
- cmd/util/util.go
- go.mod
- product-cli/cmd/cluster/aws/create.go
- product-cli/cmd/cluster/aws/destroy.go
- support/awsutil/sts.go
- test/e2e/create_cluster_test.go
- test/e2e/e2e_test.go
- test/e2e/nodepool_autorepair_test.go
- test/e2e/nodepool_kms_root_volume_test.go
- test/e2e/util/dump/dump.go
- test/e2e/util/fixture.go
This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/4027
> [release-4.16] HOSTEDCP-1561: Move HCP Product CLI to STS

- control-plane-operator/controllers/hostedcontrolplane/cvo/params.go
- control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/main.go
- support/releaseinfo/registry_mirror_provider.go
> OCPBUGS-34540: Fix RegistryMirrorProvider modifying the cached image directly

- docs/mkdocs.yml
> NO-JIRA: Add link to agent heterogeneous nodepools doc

- hypershift-operator/controllers/nodepool/nodepool_controller.go
- hypershift-operator/controllers/nodepool/nodepool_controller_test.go
Expand supported platform to allo the addition of an arm64 baremetal node to a baremetal hosted cluster.
Fixes #
**Checklist**
> HOSTEDCP-1687: Allow arm64 baremetal nodes to a nodepool in a multi-arch cluster

- hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
> OCPBUGS-34607: Disable machine pool feature gate

- test/e2e/util/util.go
test/e2e/util: use wait.PollUntilContextTimeout
The previous function is deprecated.
---
e2e/util: improve logging during node readiness poll
---
> HOSTEDCP-1709: e2e/util: improve logging during node readiness poll

- docs/content/how-to/common/exposing-services-from-hcp.md
- docs/content/how-to/disconnected/idms-icsp-for-management-clusters.md
- docs/content/how-to/disconnected/image-content-sources.md
- docs/content/how-to/disconnected/index.md
- docs/content/how-to/disconnected/known-issues.md
- docs/content/how-to/disconnected/tls-certificates.md
- docs/mkdocs.yml
Fixes #[OCPBUGS-33953](https://issues.redhat.com/browse/OCPBUGS-33953)
This PR depends on #4086, once this got merged this one will only contain one commit.
> OCPBUGS-33953: Document how ICSP/IDMS work in HCP

- cmd/infra/aws/create_cli_role.go
> OCPBUGS-34987: Add missing Tag permissions to cli role

- test/e2e/chaos_test.go
- test/e2e/olm_test.go
All async assertions must have explicit bounds on their runtime. Using an implicit bound on the overall runtime of the entire test suite is not acceptable.
> HOSTEDCP-1709: test/e2e: always bound assertions in time

- test/e2e/nodepool_autorepair_test.go
- test/e2e/nodepool_kms_root_volume_test.go
- test/e2e/nodepool_kv_advanced_multinet_test.go
- test/e2e/nodepool_kv_cache_image_test.go
- test/e2e/nodepool_kv_jsonpatch_test.go
- test/e2e/nodepool_kv_multinet_test.go
- test/e2e/nodepool_kv_nodeselector_test.go
- test/e2e/nodepool_kv_qos_guaranteed_test.go
- test/e2e/nodepool_machineconfig_test.go
- test/e2e/nodepool_nto_machineconfig_test.go
- test/e2e/nodepool_nto_performanceprofile_test.go
- test/e2e/nodepool_rolling_upgrade_test.go
- test/e2e/nodepool_test.go
1. use the newer wait.PollUntilContextTimeout
2. pass context to g.Eventually
3. pass context to cloud client calls
> HOSTEDCP-1709: test/e2e: misc context fixes:

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- hypershift-operator/controllers/nodepool/haproxy.go
- hypershift-operator/controllers/nodepool/haproxy_test.go
- hypershift-operator/controllers/nodepool/remote-kas-svc-haproxy/haproxy.cfg
- hypershift-operator/controllers/nodepool/remote-kas-svc-haproxy/remote-kas-svc-ip.service
- hypershift-operator/controllers/nodepool/remote-kas-svc-haproxy/setup-remote-kas-svc-ip.sh
- hypershift-operator/controllers/nodepool/remote-kas-svc-haproxy/teardown-remote-kas-svc-ip.sh
- hypershift-operator/controllers/sharedingress/manifests.go
- hypershift-operator/controllers/sharedingress/router.go
- hypershift-operator/controllers/sharedingress/router_config.template
- hypershift-operator/controllers/sharedingress/router_test.go
- hypershift-operator/controllers/sharedingress/sharedingress_controller.go
- hypershift-operator/controllers/sharedingress/testdata/zz_fixture_TestGenerateConfig_When_there_s_two_HostedClusters_with_all_their_Routes_and_SVCs_it_should_generate_the_config_with_frontends_and_backends_for_both.yaml
- hypershift-operator/main.go
This enables data plane -> kubernetes.svc traffic and any external dns traffic to use a common router for all HCs in Azure. The initial goal is to start transitioning the code structure (reconcilers, APIs, helpers...) towards a shared ingress oriented solution using haproxy as presented for simplicity. Main changes are:
- Change existing data plane haproxy to forward request to the management kas SVC IP.
- Add a new haproxy in the data plane that listens on the management kas SVC IP and forwards requests to the remote shared ingress.
- Introduce a new common shared ingress for the all the HC fleet management side and uses the proxy protocol to discriminate traffic originated via data plane kubernetes.svc by the dst API of theKAS SVC in the management cluster.
- Update endpoints routes to …
> HOSTEDCP-1721: Enable shared ingress for Azure

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment_test.go
- support/util/volumes.go
Manual cherry pick from https://github.com/openshift/hypershift/pull/4087
> OCPBUGS-34580: Add TrustedBundles to OAS container

- docs/content/how-to/kubevirt/configuring-storage.md
> NO-JIRA: Added markdown for storage table support

- control-plane-operator/controllers/hostedcontrolplane/olm/params.go
> NO-JIRA: feat(olm): Set packageserver replicas to 2 for IBMCloudPlatform

- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment_test.go
Fixing potential race condition issues.
> NO-JIRA: Fix tests to avoid race conditions

- control-plane-operator/controllers/hostedcontrolplane/kas/config.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/kas/reconcile.go
Fixes # https://issues.redhat.com/browse/OCPBUGS-33428
**Checklist**
> OCPBUGS-33428: Complete KAS migration to none endpoint reconciler type

- hypershift-operator/controllers/nodepool/haproxy_test.go
- hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestAPIServerHAProxyConfig_when_use_shared_router_it_should_create_two_haproxies.yaml
- hypershift-operator/controllers/sharedingress/router.go
> NO-JIRA: Shared ingress tests

- test/e2e/util/fixture.go
Failure to cleanup guest cluster infra results in a text wall like this printed 300 times
```
fixture.go:146: WARNING: found 3 remaining resources for guest cluster
fixture.go:153: Resource: arn:aws:s3:::example-d8np5-image-registry-us-east-1-ygkekqlmmunhddndvtxvegr, tags: kubernetes.io/cluster/example-d8np5=owned,Name=example-d8np5-image-registry,expirationDate=2024-06-18T16:18+00:00, service: s3
fixture.go:153: Resource: arn:aws:ec2:us-east-1:820196288204:volume/vol-07c291ad3babf77de, tags: kubernetes.io/cluster/example-d8np5=owned,expirationDate=2024-06-18T16:18+00:00, service: ec2
fixture.go:153: Resource: arn:aws:ec2:us-east-1:820196288204:volume/vol-08ab1327876ed5fa9, tags: kubernetes.io/cluster/example-d8np5=owned,expirationDate=2024-06-18T16:18+00:00, service: ec2
```
This only …
> NO-JIRA: test/e2e: reduce logging on guest cluster infra cleanup

- OWNERS
> NO-JIRA: OWNERS: add stevekuznetsov

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment_test.go
- support/util/volumes.go
Manual cherry pick from https://github.com/openshift/hypershift/pull/4211
> [release-4.14] OCPBUGS-35482: Add TrustedBundles to OAS container

- test/e2e/util/util.go
Creating a new client object does not connect to the API server, so if we're trying to wait for a client to work, we really need to send an API request and get a response. The SelfSubjectReview API is simple and we will always have the privilege to do it, so we can use it.
> HOSTEDCP-1709: test/e2e: actually wait for guest cluster client

- test/e2e/e2e_test.go
- test/e2e/nodepool_arm64_create_test.go
- test/e2e/nodepool_test.go
**What this PR does / why we need it**:  add heterogenous NP creation scenario to our e2e
Fixes # [HOSTEDCP-1221](https://issues.redhat.com/browse/HOSTEDCP-1221)
**Checklist**
> HOSTEDCP-1221: add heterogenous NP e2e

- hypershift-operator/controllers/nodepool/nodepool_controller.go
- hypershift-operator/controllers/nodepool/nodepool_controller_test.go
We currently need to keep old userdata secrets in AWS < 4.16 to prevent machineDeployments rollout from failing to delete old Machines.
https://github.com/openshift/hypershift/blob/3efa23b932a59681346a7a432d349cfb6e44b13d/hypershift-operator/controllers/nodepool/nodepool_controller.go#L775-L777
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3805
We regress that behaviour here https://github.com/openshift/hypershift/pull/3969
This PR fixes that by statically checking the hc release version.
Fixes #
**Checklist**
> OCPBUGS-35979: Keep old user data for aws < 4.16

- test/e2e/util/hypershift_framework.go
Our end-to-end tests take forever to load in Deck directly due to the number of files we have in the artifact directory. Generally, jobs will archive the results to improve this.
> HOSTEDCP-1447: test/e2e: tar.gz hosted cluster content

- cmd/cluster/kubevirt/create_test.go
- cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_test_from_dvossel.yaml
cmd/cluster/kubevirt: add a test from dvossel
---
/assign @davidvossel 
Based on #4219
> NO-JIRA: cmd/cluster/kubevirt: add a test from dvossel

- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
- control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
- control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Preserve_existing_resources.yaml
- control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Private_apiserver_connectivity__proxy_apiserver_address_is_unset.yaml
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go
backport of https://github.com/openshift/hypershift/pull/4129
Fixes #
**Checklist**
> OCPBUGS-35341: [release-4.16] Fixed ValidReleaseInfo condition

- docs/content/how-to/azure/create-azure-cluster_on_aks.md
Update HC on AKS doc for new flags for infra
N/A
**Checklist**
> NO-JIRA: Update HC on AKS doc for new flags for infra

- docs/content/how-to/azure/create-azure-cluster_on_aks.md
**What this PR does / why we need it**: fixes azure aks doc formatting
Fixes #
**Checklist**
> NO-JIRA: fixup azure aks docs

- hack/tools/deployment/deployment-update.go
> NO-JIRA: Add release notes to commit and print proper output when release errors

- test/e2e/e2e_test.go
- test/e2e/util/util.go
> NO-JIRA: skip validate metrics on azure e2e

- cmd/cluster/aws/create.go
- cmd/cluster/aws/create_test.go
- cmd/cluster/aws/testdata/zz_fixture_TestCreateCluster_default_creation_flags_for_cesar.yaml
- cmd/cluster/aws/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
Reverts openshift/hypershift#4272
> Revert "HOSTEDCP-1778: Enable MultiArch flag by default"

- docs/content/how-to/azure/create-azure-cluster_on_aks.md
Enhance aks docs by:
- specifying a custom --node-vm-size
- Dynamically obtain the image digests
- applying some formatting
Note: 
- the default vm size (Standard_DS2_v2) is not sufficient in terms of memory
```bash
$ k top node
NAME CPU(cores) CPU% MEMORY(bytes) MEMORY%
aks-nodepool1-10175151-vmss000000 1728m 90% 4762Mi 111%
aks-nodepool1-10175151-vmss000001 556m 29% 1871Mi 43%
aks-nodepool1-10175151-vmss000002 1739m 91% 4815Mi 112%
```
> NO-JIRA: Enhance aks docs

- cmd/cluster/core/dump.go
> NO-JIRA: Dump sharedingress manifest

- contrib/aks/create_basic_hosted_cluster.sh
- contrib/aks/setup_aks_cluster.sh
- contrib/aks/setup_install_ho_on_aks.sh
Update AKS contrib docs
Fixes N/A
**Checklist**
> NO-JIRA: Update AKS contrib docs

- cmd/cluster/core/dump.go
> NO-JIRA: Dump capz azure resources

- hypershift-operator/controllers/hostedcluster/network_policies.go
- hypershift-operator/controllers/manifests/networkpolicy/manifests.go
> NO-JIRA: Add net policy to allow ingress from sharedingress namespace

- docs/content/how-to/troubleshooting-general.md
> NO-JIRA: add ignition payload inspect docs

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/oauth.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/assets.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/auditcfg.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/deployment_test.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/files/audit-policy.yaml
- control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/testdata/zz_fixture_TestReconcileOauthDeploymentNoChanges.yaml
This is a manual 4.15 cherry-pick of https://github.com/openshift/hypershift/pull/3994
> [release-4.15] OCPBUGS-36606: enable audit log for oauth-openshift

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Eventually, the ETCD deployment encountered issues booting when many HostedControlPlanes were being created. This caused one or more members to get stuck while trying to join the cluster but unable to do so. Once a pod is stuck in CrashLoopBackOff, after the time of etcdRecoveryPeriod a window will be opened to check if the ETCD is Ok. if the ETCD is not ok the stateful set and PVC inside will be updated with new labels forcing recreation in the next reconcile loop. After the time of etcdRecoveryTimeout the controller will not try to recover it again to avoid issues in other scenarios.
Which issue(s) this PR fixes:
Fixes #[OCPBUGS-24400](https://issues.redhat.com/browse/OCPBUGS-24400)
This is the second approach, the initial one is: https://github.com/openshift/hypershift/pull/4161
> OCPBUGS-24400: Recreate the ETCD statefulSet on HostedCluster deployment when stays failing

- contrib/snyk/READ_ME.md
- contrib/snyk/check-for-cve-in-cpo.sh
- contrib/snyk/check-for-cve-in-ho.sh
Adding some scripts I created to help me with searching for multiple CVE related programs in the RPMs.
Fixes [HOSTEDCP-1820](https://issues.redhat.com/browse/HOSTEDCP-1820)
**Checklist**
> HOSTEDCP-1820: Add snyk helper scripts to contrib

- docs/content/reference/konnectivity.md
- docs/mkdocs.yml
Adds a more detailed description of Konnectivity and how it's implemented in HyperShift
Fixes #[HOSTEDCP-1832](https://issues.redhat.com/browse/HOSTEDCP-1832)
**Checklist**
> HOSTEDCP-1832: Document konnectivity in HyperShift

- docs/content/how-to/disaster-recovery/backup-and-restore-oadp.md
Signed-off-by: Juan Manuel Parrilla Madrid
> NO-JIRA: Fix OADP backup objects

- docs/Dockerfile
Fixes #[HOSTEDCP-1836](https://issues.redhat.com/browse/HOSTEDCP-1836)
Snyk:
- https://app.snyk.io/org/hypershift/project/408c6c8f-492a-410d-83f2-2e8d88f903ac#issue-SNYK-PYTHON-SETUPTOOLS-7448482
- https://app.snyk.io/org/hypershift/project/408c6c8f-492a-410d-83f2-2e8d88f903ac#issue-SNYK-PYTHON-ZIPP-7430899
> HOSTEDCP-1836: Fix Snyk vulnerability with python deps

- api/hypershift/v1beta1/nodepool_types.go
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
- hack/app-sre/saas_template.yaml
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go
Supersedes https://github.com/openshift/hypershift/pull/4393
Fixes #
**Checklist**
> [release-4.16] OCPBUGS-37302: fix(api): Nodepool CEL validation fix

- cmd/cluster/azure/create_test.go
- cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/core/create.go
- cmd/cluster/openstack/create_test.go
- cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_default_creation_flags.yaml
> HOSTEDCP-1791: dont render cloud-credentials secret

- cmd/nodepool/openstack/create.go
- product-cli/cmd/nodepool/create.go
Small fixes for OpenStack CLI.
> OSASINFRA-3538: openstack: small fixes for CLI

- cmd/cluster/aws/create.go
- support/releaseinfo/registryclient/client.go
- support/thirdparty/kubernetes/pkg/credentialprovider/config.go
- support/util/util.go
Refactors the algorithm performing different multi-arch validations similar to [this](https://excalidraw.com/#json=QeumxPAwNmXPFxe4GjuWt,I_h08v5-INft4lOLYO5Mcg).
Fixes [HOSTEDCP-1778](https://issues.redhat.com/browse/HOSTEDCP-1778)
**Checklist**
> HOSTEDCP-1798: Refactor multi-arch validation algorithm

- control-plane-operator/controllers/hostedcontrolplane/cloud/openstack/manifests.go
- control-plane-operator/controllers/hostedcontrolplane/cloud/openstack/providerconfig.go
- control-plane-operator/controllers/hostedcontrolplane/cloud/openstack/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/openstack.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
- hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack.go
- ignition-server/controllers/local_ignitionprovider.go
- support/globalconfig/infrastructure.go
Refactor/clean and add missing credentials for the OpenStack platform.
> OSASINFRA-3319: implements required OpenStack credentials

- control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
- support/util/deployment.go
- support/util/deployment_test.go
> OCPBUGS-24400: Only recreate etcd if hasn't ever been ready

- control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
Manual cherry-pick of https://github.com/openshift/hypershift/pull/4422
Fixes #
**Checklist**
> OCPBUGS-37645: Set right endpointSlice port

- docs/content/how-to/openstack/create-openstack-cluster.md
- docs/mkdocs.yml
First manual to document how we can deploy a cluster with the OpenStack platform.
> OSASINFRA-3546: openstack: document how to create a cluster

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
- .tekton/hypershift-release-mce-26-pull-request.yaml
- .tekton/hypershift-release-mce-26-push.yaml
* Cherry-picks the commit in https://github.com/openshift/hypershift/pull/4429
* Performs the recommend migrations per https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md
N/A
**Checklist**
> NO-JIRA: Konflux migration for release-4.16

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- support/certs/tls.go
This is an manual cherry-pick of https://github.com/openshift/hypershift/pull/4371
> [release-4.15] HOSTEDCP-1795,HOSTEDCP-1796: Customize the self-generated cert validity and rotation

- control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert_test.go
This enabled the oauth server traffic to flow through the dataplane to enable reaching private endpoints e.g ldap https://issues.redhat.com/browse/HOSTEDCP-421
This enabled fallback to the management cluster network so for public endpoints we are not blocking on having data plane, e.g. github https://issues.redhat.com/browse/OCPBUGS-8073
This PR enables the CPO oidc checks to flow through the data plane and fallback to the management side to satisfy both cases above https://issues.redhat.com/browse/RFE-5638
Fixes #
**Checklist**
> OCPBUGS-37753: Let the CPO oidc check resolve through data plane

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- support/certs/tls.go
This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/4444
> [release-4.14] HOSTEDCP-1795,HOSTEDCP-1796: Customize the self-generated cert validity and rotation

- api/hypershift/v1beta1/hostedcluster_types.go
- cmd/cluster/agent/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/aws/create.go
- cmd/cluster/aws/testdata/zz_fixture_TestCreateCluster_default_creation_flags_for_cesar.yaml
- cmd/cluster/aws/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/azure/create.go
- cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
- cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/core/create.go
- cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_test_from_dvossel.yaml
- cmd/cluster/none/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/openstack/create.go
- cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_default_creation_flags.yaml
- cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/powervs/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
- control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
- control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Preserve_existing_resources.yaml
- control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Private_apiserver_connectivity__proxy_apiserver_address_is_unset.yaml
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
This is only relevant for < 4.14
Fixes #
**Checklist**
> NO-JIRA: Remove non relevant OVNSbDb service type declarations

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
- .tekton/hypershift-release-mce-27-pull-request.yaml
- .tekton/hypershift-release-mce-27-push.yaml
Replaces #4478:
* cherry picked the commit in #4478
* Removed BASE_IMAGES_DIGEST per the Konflux migration instructions - https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md
Fixes N/A
**Checklist**
> NO-JIRA: Update Konflux and perform migration

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
- .tekton/hypershift-release-mce-27-pull-request.yaml
- .tekton/hypershift-release-mce-27-push.yaml
Replaces https://github.com/openshift/hypershift/pull/4479:
* cherry picked the commit in https://github.com/openshift/hypershift/pull/4479
* Removed BASE_IMAGES_DIGEST per the Konflux migration instructions - https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md
Fixes #
**Checklist**
> NO-JIRA: Update Konflux 4.17 and perform migration

- docs/content/how-to/openstack/create-openstack-cluster.md
Fix a typo that broke rendering.
> OSASINFRA-3546: docs/openstack: fix typo

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
- hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go
- hypershift-operator/controllers/nodepool/nodepool_controller_test.go
- support/supportedversion/version.go
- support/supportedversion/version_test.go
> NO-JIRA: Bump `LatestSupportedVersion` to 4.18.0 after branch-out

- docs/content/how-to/upgrades.md
- docs/content/reference/versioning-support.md
Updates the version support doc page since it is out of date.
Fixes [HOSTEDCP-1707](https://issues.redhat.com/browse/HOSTEDCP-1707)
**Checklist**
> HOSTEDCP-1707: Update version support and upgrade docs

- api/hypershift/v1alpha1/nodepool_types.go
- api/hypershift/v1beta1/nodepool_types.go
- client/applyconfiguration/hypershift/v1alpha1/diagnostics.go
- client/applyconfiguration/hypershift/v1beta1/diagnostics.go
- cmd/cluster/azure/create.go
- cmd/nodepool/azure/create.go
- docs/content/reference/api.md
This is to facilitate automation which requires creating an HC/NP with Azure diagnostics enabled.
> HOSTEDCP-1609: Support configuring Azure diagnostics via CLI flags

- hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
- hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes_test.go
Fixes a bug where node events would not trigger a reconcile loop for DedicatedServingComponentSchedulerAndSizer when the `hypershift.openshift.io/cluster` label was not present on the node. This can happen if:
* A hostedcluster is assigned to a pair of request-serving nodes and the `hypershift.openshift.io/cluster` label is added to both nodes
* One of the request-serving nodes is deleted by any means
* A replacement request-serving node is created without the label
Now, node events also trigger a check to determine whether the node has the `osd-fleet-manager.openshift.io/paired-nodes` label, and if so, if the other paired nodes exist with the `hypershift.openshift.io/cluster` label. If so, we assume that this new node should trigger a reconcilation …
> OCPBUGS-38154: Fix bug where nodes were not triggering dedicated serving reconciliation

- cmd/cluster/openstack/create.go
We were setting externalDNSDomain in completedCreateOptions, but reading it
from RawCreateOptions, so the value we were using was never set.
We have been unable to make external-dns-domain work correctly, so for now we remove support for it and add a validation that it is not set so we can safely fix it later.
**Checklist**
> OSASINFRA-3567: openstack: fix setting external DNS on create

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Follow-on to https://github.com/openshift/hypershift/pull/4495 to fix AKS break
> OCPBUGS-36261: label routes when using SharedIngress

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Pausing the CAPI cluster object ensures all machines reconcilation is paused during backup if the NodePool was not explicitly paused. 
Fixes #
**Checklist**
> HOSTEDCP-1868: Pause CAPI cluster when HostedCluster is paused

- cmd/install/assets/hypershift_operator.go
- cmd/install/install.go
Currently external-dns doesn't work if the cluster on which is runs has a proxy configured
> HOSTEDCP-1565: external-dns: add proxy env vars if cluster proxy is configured

- docs/content/reference/controller-architecture.md
Fix a typo in the controller architecture docs
**Checklist**
> NO-JIRA: fix a typo in the architecture doc

- hypershift-operator/controllers/nodepool/haproxy.go
- If a port is not provided by the user, `kubernetes-default-proxy` pod will fail as its expecting a host:port address. This checkes if the port is missing and joins the default 443 port to the HTTPS proxy address when passing it to the container.
Fixes #
**Checklist**
> OCPBUGS-38709: Join default HTTPS port to Spec.Configuration.Proxy.HTTPSProxy if missing

- control-plane-operator/hostedclusterconfigoperator/controllers/resources/kas/admissionpolicies.go
The CNO's `infrastructureconfig` controller modifies the global config for the platforms included here:
https://github.com/openshift/cluster-network-operator/blob/c21e13f626cfcb21fdbd42076b57d00cebb064ca/pkg/controller/infrastructureconfig/predicates.go#L23-L38
Openstack is the first of these platforms to be supported by hypershift. We need to allow changes from the CNO.
This PR allows changes to the infrastructure global config from any user, which could be further restricted to the service account of the CNO.  However, we just want to get Openstack back online asap for now.
> OCPBUGS-38878: allow changes to infrastructures global config for Openstack

- hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
CAPA ROSA feature gate is not available on releases < `4.16`
Fixes #
**Checklist**
> OCPBUGS-39001: Fix CAPA ROSA feature gate being set on releases where its not available

- control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_apiserver.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
This is a manual 4.14 cherry-pick of https://github.com/openshift/hypershift/pull/3972
> [release-4.14] OCPBUGS-37076: Fixed audit-logs sigterm failing to terminate gracefully

- cmd/install/install.go
This is a preparation PR for [HOSTEDCP-1767](https://issues.redhat.com//browse/HOSTEDCP-1767) that refactors the install command by breaking down the long `hyperShiftOperatorManifests` into smaller functions and making it focus on the high-level operations only. 
**Checklist**
> HOSTEDCP-1767: chore: organize install command for readability

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
This PR:
- updates the konflux references
- removes sbom-json-check from tekton files
N/A
**Checklist**
> NO-JIRA: Konflux migration

- hypershift-operator/controllers/sharedingress/sharedingress_controller.go
This is needed so that the sharedingress loadbalacner is created at the start without waiting for a HostedCluster to exist.
Fixes #
**Checklist**
> HOSTEDCP-1939: Trigger SharedIngress reconciliation immediately on start

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/ingress/router.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/ingress.go
Backporting PDB related commits from main
https://github.com/openshift/hypershift/pull/3337
> [release-4.14] NO-JIRA: PDB backports

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/ingress/router.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/ingress.go
This reverts commit ab18b17d053050a413afcc54623393dacf6cffa6, reversing changes made to da98ec4381a6a5d0db7dc6279761150103ce0c92.
> NO-JIRA: Revert "Merge pull request #4661 from jparrill/bp-4.14/OCPBUGS-24308"

- test/e2e/chaos_test.go
Included 2 functional tests to the TestHAEtcdChaos:
- An etcd member with data corruption.
- A test case when the ETCD Cluster lose one member.
Fixes #[HOSTEDCP-1942](https://issues.redhat.com/browse/HOSTEDCP-1942)
> HOSTEDCP-1942: Add functional tests for Etcd Recovery

- cmd/cluster/azure/create.go
- cmd/nodepool/azure/create.go
Add EncryptionAtHost to create azure cluster CLI
Fixes [OCPBUGS-39039](https://issues.redhat.com/browse/OCPBUGS-39039)
**Checklist**
> OCPBUGS-39039: Add EncryptionAtHost to create azure cluster CLI

- .tekton/hypershift-release-mce-25-pull-request.yaml
- .tekton/hypershift-release-mce-25-push.yaml
This PR cherry picks https://github.com/openshift/hypershift/pull/4653 and performs the sbom migration per https://github.com/konflux-ci/build-definitions/blob/main/task/sbom-json-check/0.2/MIGRATION.md.
Fixes N/A
**Checklist**
> NO-JIRA: chore(deps): update konflux references (release-4.15)

- ignition-server/controllers/local_ignitionprovider.go
follow up for https://issues.redhat.com//browse/OCPBUGS-39420
Fixes #
**Checklist**
> NO-JIRA: Add log for ignition provider using mirrored release image

- ignition-server/cmd/start.go
Snyk Duty task
Fixes #[OCPBUGS-41935](https://issues.redhat.com/browse/OCPBUGS-41935)
> OCPBUGS-41935: Sanitize the IgnitionPayload (XSS)

- .snyk
- ignition-server/cmd/start.go
- support/util/util.go
- support/util/util_test.go
These PR is a manual backport of 3 different PRs:
- https://github.com/openshift/hypershift/pull/4723
- https://github.com/openshift/hypershift/pull/4722
- https://github.com/openshift/hypershift/pull/4735
These ones prepares the release branch to execute (without High security issues) the Openshift CI Security job which under the hood uses the `snyk code test` command and the job fails if SNYK find any high security issue.
After this PR we will need to add a new one to add the CI Job to the release repo as we did with 4.18, 4.19 and Main branches in this PR:
- https://github.com/openshift/release/pull/56687
> [release-4.17] NO-JIRA: Security fixes for openshift-ci-security job

- cmd/infra/azure/create.go
- cmd/infra/azure/destroy.go
Creates seperate RGs for NSG and VNet
[HOSTEDCP-1788](https://issues.redhat.com/browse/HOSTEDCP-1788)
**Checklist**
> HOSTEDCP-1788: Create seperate RGs for NSG and VNet

- hypershift-operator/controllers/sharedingress/manifests.go
- hypershift-operator/controllers/sharedingress/router.go
- hypershift-operator/controllers/sharedingress/router_test.go
- hypershift-operator/controllers/sharedingress/sharedingress_controller.go
- support/config/deployment.go
- support/config/deployment_test.go
**What this PR does / why we need it**: add PDB to sharedIngress router pod
Fixes # [HOSTEDCP-1732](https://issues.redhat.com/browse/HOSTEDCP-1732)
**Checklist**
> HOSTEDCP-1732: add PDB to sharedIngress router pod

- hypershift-operator/controllers/nodepool/aws.go
- hypershift-operator/controllers/nodepool/kubevirt.go
- hypershift-operator/controllers/nodepool/nodepool_controller.go
- hypershift-operator/controllers/nodepool/powervs.go
- Move platform specific logic into their own files
- Rearrange validations
Fixes #
**Checklist**
> HOSTEDCP-1976: Nodepool controller cleanup

- docs/content/how-to/disaster-recovery/backup-and-restore-oadp.md
Add documentation for KubeVirt hosted cluster backup and restore, as part of disaster recovery documentation.
Moved the text under `Backup and Upload` to a new `AWS and Bare Metal` tab, and add a new tab for `KubeVirt`:
Did the same under `Post Restore Operations`:
**Checklist**
> CNV-48479: Add documentation for KubeVirt hosted cluster backup and restore

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/manifests/oauth.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/assets.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/auditcfg.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/deployment_test.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/files/audit-policy.yaml
- control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/testdata/zz_fixture_TestReconcileOauthDeploymentNoChanges.yaml
This is an manual cherry-pick of https://github.com/openshift/hypershift/pull/4320
> [release-4.14] OCPBUGS-42533: enable audit log for oauth-openshift

- docs/content/how-to/kubevirt/gpu-devices.md
- docs/mkdocs.yml
This documents how to add GPU devices to HCP KubeVirt NodePools
> CNV-39662: Document HCP KubeVirt GPU device usage

- cmd/cluster/core/create.go
In support of testing [SDN-5238](https://issues.redhat.com//browse/SDN-5238)
Avoid the need to do this https://github.com/openshift/release/pull/56065/files#diff-2dd93dce12c5420e483d70b5984b56fcf0d1fe4084d01901c6d5705e09cb619bR75-R92
> NO-JIRA: cli: add feature-set flag to create cluster

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
- control-plane-operator/controllers/hostedcontrolplane/imageprovider/imageprovider.go
- control-plane-operator/controllers/hostedcontrolplane/infra/infra.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/hosted-cluster-config-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/hosted-cluster-config-operator/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-autoscaler/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/hosted-cluster-config-operator/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/hosted-cluster-config-operator/podmonitor.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/hosted-cluster-config-operator/role.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/hosted-cluster-config-operator/rolebinding.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/hosted-cluster-config-operator/serviceaccount.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-route-controller-manager/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/configoperator/podmonitor.go
- control-plane-operator/controllers/hostedcontrolplane/v2/configoperator/reconcile.go
- control-plane-operator/controllers/hostedcontrolplane/v2/configoperator/role.go
- support/controlplane-component/common.go
- support/controlplane-component/controlplane-component.go
- support/controlplane-component/generic-adapter.go
- support/testutil/fake.go
Refactor HCCO Component
Fixes #
**Checklist**
> HOSTEDCP-2040: [CPO Refactor] Refactor HCCO

- support/controlplane-component/README.md
> HOSTEDCP-2040: Add README.md for ControlPlaneComponent

- docs/content/recipes/agent/exposing-dataplane-with-metallb.md
- docs/content/recipes/common/replace-crio-runtime.md
- docs/content/recipes/none/exposing-dataplane-with-metallb.md
- docs/content/reference/ocp-behaviour-deviations/index.md
- docs/content/reference/ocp-behaviour-deviations/upgrade-4.17-4.18.md
- docs/mkdocs.yml
Fixes #[HOSTEDCP-2002](https://issues.redhat.com/browse/HOSTEDCP-2002)
> HOSTEDCP-2002: Add documentation around crun migration for HCP

- docs/content/how-to/kubevirt/configuring-storage.md
This adds documentation that outlines how KubeVirt CSI achieves storage security and isolation between the guest clusters and the infrastructure cluster.
> NO-JIRA: KubeVirt CSI Security and Isolation Documentation

- hypershift-operator/controllers/nodepool/conditions.go
- hypershift-operator/controllers/nodepool/nodepool_controller.go
- hypershift-operator/controllers/nodepool/nto.go
> HOSTEDCP-2018: Reorder Nodepool conditions

- docs/content/recipes/common/replace-crio-runtime.md
Fixes #[HOSTEDCP-2002](https://issues.redhat.com/browse/HOSTEDCP-2002)
> HOSTEDCP-2002: fix typo in doc commands

- cmd/cluster/core/dump.go
We now have a new list named `featureGatedResources` which will contain
the GVKs that live behind a feature gate (e.g. ControlPlaneComponent).
This list, combined with the previously tested `ocpResources`, will be
registering the GVKs that actually exist on the management cluster and
ignore the rest.
> OCPBUGS-43698: dump: make ControlPlaneComponent's GKV optional

- api/hypershift/v1beta1/hostedcluster_conditions.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/config.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go
- docs/content/reference/api.md
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_conditions.go
Combine clean picks of https://github.com/openshift/hypershift/pull/4852 and https://github.com/openshift/hypershift/pull/4955
The changes to API and HO are not required but don't hurt and make the picks clean
> OCPBUGS-43746: add ValidIDPConfiguration condition to report IDP config issues

- api/OWNERS
Counter part PR https://github.com/openshift/release/pull/58171
Fixes #
**Checklist**
> NO-JIRA: Add API label

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/etcd/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/etcd/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/etcd/defrag-role.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/etcd/defrag-rolebinding.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/etcd/defrag-serviceaccount.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/etcd/discovery-service.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/etcd/pdb.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/etcd/service.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/etcd/servicemonitor.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/etcd/statefulset.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/etcd/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/etcd/etcd-init.sh
- control-plane-operator/controllers/hostedcontrolplane/v2/etcd/servicemonitor.go
- control-plane-operator/controllers/hostedcontrolplane/v2/etcd/statefulset.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/component.go
- support/controlplane-component/controlplane-component.go
- support/controlplane-component/status.go
- support/util/containers.go
> HOSTEDCP-2057: [CPO Refactor] Refactor ETCD

- control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
**What this PR does / why we need it**: use latest catalog operator versions for 4.17 
Fixes #
**Checklist**
> NO-JIRA: bump catalog operators version

- cmd/cluster/azure/create.go
- cmd/cluster/azure/create_test.go
- cmd/cluster/azure/destroy.go
- cmd/cluster/core/destroy.go
- cmd/infra/azure/create.go
- cmd/infra/azure/destroy.go
- cmd/install/assets/hypershift_operator.go
- cmd/install/assets/hypershift_operator_test.go
- cmd/install/install.go
- hypershift-operator/featuregate/feature.go
This PR updates the Azure CLI to handle authenticating with Service Principal (SP) backed by certificates.
Fixes #
**Checklist**
> OCPBUGS-42434: Update Azure CLI to Handle Authenticating with Service Principal Backed by Certificates

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-controller-manager/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-controller-manager/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-controller-manager/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-controller-manager/kcm-config.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-controller-manager/kubeconfig.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-controller-manager/recycler-config.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-controller-manager/service.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-controller-manager/servicemonitor.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/kubeconfig.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kcm/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kcm/config.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kcm/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kcm/kubeconfig.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kcm/servicemonitor.go
- support/api/scheme.go
> HOSTEDCP-2055: [CPO Refactor] Refactor kube-controller-manager

- docs/content/how-to/kubevirt/configuring-storage.md
This adds documentation that outlines how to disable kubevirt csi at cluster creation time.
> NO-JIRA: Document how to disable kubevirt csi

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
Adding required `rpms-signature-scan` task to pipelines.
Fixes #
**Checklist**
> NO-JIRA: Add rpms-signature-scan task

- docs/content/how-to/feature-gates.md
> NO-JIRA: Add API promotion criteria

- api/hypershift/v1beta1/azure.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/OpenStack.yaml
- cmd/cluster/azure/create.go
- cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
- cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_create_with_a_ure_marketplace_image.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-TechPreviewNoUpgrade.crd.yaml
- docs/content/reference/api.md
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/azure.go
> HOSTEDCP-1826: Remove API wording on setting AzureDiskPersistence to a default value of Persistent

- api/hypershift/v1beta1/hostedcluster_types.go
- api/hypershift/v1beta1/nodepool_types.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AROHCPManagedIdentities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/OpenStack.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-TechPreviewNoUpgrade.crd.yaml
- docs/content/reference/api.md
- support/assets/readasset.go
- test/e2e/assets/nodepool-base.yaml
- test/e2e/create_cluster_test.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go
> HOSTEDCP-2073: Review NodePool API validations and doc

- api/hypershift/v1beta1/clusterconfig.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-apiserver/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-apiserver/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-apiserver/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-apiserver/audit-config.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-apiserver/config.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-apiserver/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-apiserver/pdb.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-apiserver/servicemonitor.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/auditcfg.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/oapi/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/oapi/config.go
- control-plane-operator/controllers/hostedcontrolplane/v2/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/oapi/deployment_test.go
- control-plane-operator/controllers/hostedcontrolplane/v2/oapi/servicemonitor.go
- control-plane-operator/controllers/hostedcontrolplane/v2/ocm/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/routecm/component.go
- support/controlplane-component/controlplane-component.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/clusterconfig.go
> HOSTEDCP-2063: [CPO Refactor] Refactor openshift-apiserver

- cmd/cluster/powervs/create.go
- cmd/cluster/powervs/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
Need to fetch CloudInstanceID and VPCName from infra instead of createOptions.
Fixes #
**Checklist**
> NO-JIRA: Fix Spec retrieval from infra for PowerVS platform

- docs/content/how-to/openstack/create-openstack-cluster.md
Improvements, details, which I think will help our early adopters.
> NO-JIRA: improve OpenStack documentation

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-oauth-apiserver/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-oauth-apiserver/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-oauth-apiserver/audit-config.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-oauth-apiserver/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-oauth-apiserver/pdb.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/oauth_apiserver/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/oauth_apiserver/deployment.go
- support/controlplane-component/controlplane-component.go
> HOSTEDCP-2063: [CPO Refactor] Refactor openshift-oauth-apiserver

- api/hypershift/v1beta1/clusterconfig.go
- control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
- control-plane-operator/controllers/hostedcontrolplane/kas/params.go
- control-plane-operator/controllers/hostedcontrolplane/kcm/params.go
- control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-scheduler/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-scheduler/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-scheduler/config.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-scheduler/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-scheduler/kubeconfig.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/params.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kcm/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kube_scheduler/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kube_scheduler/config.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kube_scheduler/config_test.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kube_scheduler/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kube_scheduler/kubeconfig.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kube_scheduler/testdata/zz_fixture_TestGenerateConfig_Leader_elect_args_get_set_correctly__default_profile.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/kube_scheduler/testdata/zz_fixture_TestGenerateConfig_high_node_utili_ation_profile.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/kube_scheduler/testdata/zz_fixture_TestGenerateConfig_no_scoring_profile.yaml
- support/config/featuregates.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/clusterconfig.go
> HOSTEDCP-2077: [CPO Refactor] Refactor kube-scheduler

- cmd/cluster/agent/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_availability_ones.yaml
- cmd/cluster/core/create.go
- cmd/cluster/core/create_test.go
- cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_test_from_dvossel.yaml
- cmd/cluster/none/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_default_creation_flags.yaml
- cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
- cmd/cluster/powervs/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
Manual cherry-pick from https://github.com/openshift/hypershift/pull/5038
Fixes #[OCPBUGS-44268](https://issues.redhat.com/browse/OCPBUGS-44268)
> [release-4.17] OCPBUGS-44268: Fix order rendering HCP objects

- control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/openstack/config.go
This was missing when adding the v2.
> OCPBUGS-44336: add missing comment in v2 openstack ccm

- docs/content/how-to/openstack/create-openstack-cluster.md
Add missing hypershift CLI and clarify why we need it.
> NO-JIRA: docs/openstack: clarify CLI

- docs/content/how-to/openstack/create-openstack-cluster.md
Minor fix on how we get kubeadmin password.
> NO-JIRA: docs: minor fix for OpenStack

- docs/content/contribute/release-process.md
**What this PR does / why we need it**: removes out of date docs on what should be during release/branching that are confusing 
Fixes #
**Checklist**
> NO-JIRA: remove out of date releas notes

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Adds the Service type to a few unit tests that are failing since Service is now required in the API. 
Fixes #
**Checklist**
> NO-JIRA: Fix unit tests

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-version-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-version-operator/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-version-operator/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-version-operator/role.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-version-operator/rolebinding.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-version-operator/service.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-version-operator/serviceaccount.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-version-operator/servicemonitor.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/cvo/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/cvo/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/cvo/servicemonitor.go
- support/controlplane-component/controlplane-component.go
> HOSTEDCP-2177: [CPO Refactor] Refactor cluster-version-operator

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-policy-controller/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-policy-controller/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-policy-controller/config.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-policy-controller/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/clusterpolicy/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/clusterpolicy/config.go
> HOSTEDCP-2187: [CPO Refactor] Refactor cluster-policy-controller

- hypershift-operator/controllers/nodepool/secret_janitor_test.go
- support/supportedversion/version.go
- support/supportedversion/version_test.go
- test/e2e/util/version.go
**What this PR does / why we need it**: update latest supported version to 4.19 for pre branching testing
Fixes # [HOSTEDCP-2181](https://issues.redhat.com/browse/HOSTEDCP-2181)
**Checklist**
> HOSTEDCP-2181: update latest supported version for 4.19 branching

- api/hypershift/v1beta1/hostedcluster_types.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AROHCPManagedIdentities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/HCPPodsLabels.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AROHCPManagedIdentities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
- test/e2e/create_cluster_test.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
> HOSTEDCP-2075: Nodeport address cel

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
> OCPBUGS-44934: Fix error message when kas is route and hostname is not set

- api/hypershift/v1beta1/hostedcluster_types.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AROHCPManagedIdentities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/HCPPodsLabels.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AROHCPManagedIdentities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
- test/e2e/create_cluster_test.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
> HOSTEDCP-2075: Dns cel e2e

- docs/content/how-to/disconnected/tls-certificates.md
Fixes #[HOSTEDCP-2197](https://issues.redhat.com/browse/HOSTEDCP-2197)
> HOSTEDCP-2197: Fix TLS config documentation for disconnected

- docs/content/contribute/release-process.md
- It adds docs about what to do when a new release is cut.
Fixes #
**Checklist**
> NO-JIRA: updating ocp release task notes

- cmd/cluster/azure/create.go
- cmd/infra/azure/create.go
- test/e2e/e2e_test.go
- adds DNS RG to contributor role assignments 
- adds new flag for skipping role assignments
Fixes # [HOSTEDCP-2201](https://issues.redhat.com/browse/HOSTEDCP-2201)
**Checklist**
> HOSTEDCP-2201: add DNS RG to contributor role assignments and add new flag for skipping role assignments

- cmd/infra/azure/create.go
- Adds contributor role to the role assignments that will be assigned to the nodepoolManagement SP
Fixes # [HOSTEDCP-2204](https://issues.redhat.com/browse/HOSTEDCP-2204)
**Checklist**
> HOSTEDCP-2204: adding contributor role to nodepoolManagement SP

- Dockerfile
- Dockerfile.control-plane
- Dockerfile.dev
- Dockerfile.e2e
> HOSTEDCP-2181: bump base images in dockerfiles to 4.19

- api/hypershift/v1beta1/hostedcluster_types.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AROHCPManagedIdentities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/HCPPodsLabels.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AROHCPManagedIdentities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
- docs/content/reference/api.md
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
This is relaxed to prevent breaking existing clusters with conflicting input
Fixes #
**Checklist**
> NO-JIRA: Relax networking cel validation for IBMCloud

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
- .tekton/hypershift-release-mce-26-pull-request.yaml
- .tekton/hypershift-release-mce-26-push.yaml
This PR:
- Cherry-picks the commit in https://github.com/openshift/hypershift/pull/5256
- Performs the migration steps listed in the aforementioned PR
Fixes #
**Checklist**
> NO-JIRA: Update Konflux References and Perform Migration for Release-4.16

- api/hypershift/v1beta1/hostedcluster_types.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AROHCPManagedIdentities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/HCPPodsLabels.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AROHCPManagedIdentities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
- docs/content/reference/api.md
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
Backport of https://github.com/openshift/hypershift/pull/5258
Fixes #
**Checklist**
> NO-JIRA: Relax ibm network cel 4.18

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
This PR:
- Cherry-picks the commit in https://github.com/openshift/hypershift/pull/5248
- Performs the migration steps listed in the aforementioned PR
Fixes #
**Checklist**
> NO-JIRA: Update Konflux References and Perform Migration

- contrib/managed-azure/create_basic_hosted_cluster.sh
- contrib/managed-azure/setup_dev_environment.md
- docs/content/how-to/azure/create-azure-cluster-with-options.md
- docs/content/how-to/azure/create-azure-cluster_on_aks.md
> HOSTEDCP-2193: documenting --managed-identities-file flag

- .codespellignore
- contrib/managed-azure/setup_dev_environment.md
- docs/content/how-to/azure/create-azure-cluster-with-options.md
- docs/content/how-to/azure/create-azure-cluster_on_aks.md
> NO-JIRA: Fix pre-commit hook issues

- contrib/cleanzones/main.go
This commit fixes a couple of spelling mistakes introduced by PR #5265
Fixes #
**Checklist**
> NO-JIRA: Fix spelling mistakes from PR #5265

- support/conditions/conditions.go
Fix expected AWS HC conditions during e2e tests
**Checklist**
> NO-JIRA: Fix expected AWS HC conditions during e2e tests

- cmd/cluster/azure/create.go
- cmd/infra/azure/create.go
- test/e2e/e2e_test.go
- test/e2e/util/fixture.go
> NO-JIRA: 4.18 aks e2e cli changes

- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-controller-manager/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-controller-manager/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-controller-manager/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/kcm/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/oauth/idp_convert.go
- control-plane-operator/controllers/hostedcontrolplane/v2/oauth/idp_convert_test.go
Follow-up of https://github.com/openshift/hypershift/pull/5166 and https://github.com/openshift/hypershift/pull/5241
Fixes #
**Checklist**
> NO-JIRA: Fix oauth-v2 and kcm-v2

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/cloud-credential-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cloud-credential-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cloud-credential-operator/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cloud-credential-operator/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cloud-credential-operator/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cloud-credential-operator/kubeconfig.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/cloud_credential_operator/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/cloud_credential_operator/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/cloud_credential_operator/kubeconfig.go
> HOSTEDCP-2199: [CPO Refactor] Refactor cloud-credential-operator

- test/e2e/util/util.go
> NO-JIRA: e2e: don't check the KV's LiveMigratable condition for <4.17

- docs/content/how-to/aws/create-infra-iam-separately.md
Fix missing new line after list in markdown was breaking the rendered list in HTML.
Page ref https://hypershift-docs.netlify.app/how-to/aws/create-infra-iam-separately/
Fixes #
**Checklist**
> NO-JIRA: docs/nit: fix missing spaces in md breaking rendered html

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-storage-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-storage-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-storage-operator/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-storage-operator/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-storage-operator/README.md
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-storage-operator/azure-disk-csi-config.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-storage-operator/azure-disk-csi-secretprovider.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-storage-operator/azure-file-csi-config.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-storage-operator/azure-file-csi-secretprovider.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-storage-operator/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-storage-operator/role.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-storage-operator/rolebinding.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-storage-operator/serviceaccount.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/azure/config.go
- control-plane-operator/controllers/hostedcontrolplane/v2/storage/azure.go
- control-plane-operator/controllers/hostedcontrolplane/v2/storage/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/storage/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/storage/envreplace.go
> HOSTEDCP-2233: [CPO Refactor] Refactor cluster-storage-operator

- docs/content/how-to/azure/create-azure-cluster_on_aks.md
This commit just updates minor changes to the document.
Fixes #
**Checklist**
> NO-JIRA: Update Create Azure HC document

- test/e2e/util/hypershift_framework.go
Currently, failures in e2e test cluster infra creation generate a red herring error on `Teardown/ValidateMetricsAreExposed`
```
util.go:1453: Expected results for metric "hypershift_cluster_silence_alerts", found none
util.go:1466: Failed to validate all metrics
--- FAIL: TestCreateCluster/Teardown/ValidateMetricsAreExposed (300.06s)
```
Examples:
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.19-periodics-e2e-aws-ovn/1864279699434246144
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.19-periodics-e2e-aws-ovn/1864006972760657920
https://github.com/openshift/hypershift/pull/4143 attempted to fix this but didn't work but `t` in this context is the `Teardown` subtest, …
> NO-JIRA: test/e2e: move pre-removal metrics validation out teardown path

- .tekton/hypershift-operator-main-pull-request.yaml
Reverts openshift/hypershift#5314
> Revert "CNTRLPLANE-26: Disable building HO for s390x platform on PR"

- Dockerfile.e2e
Moves the installed Microsoft repository to the dir expected by CI so that it can be found. 
Fixes # [CNTRLPLANE-129](https://issues.redhat.com/browse/CNTRLPLANE-129)
**Checklist**
> CNTRLPLANE-129: Move Microsoft Repo to CI dir in e2e dockerfile

- docs/content/how-to/openstack/index.md
Double-level bullet points don't seem the work fine with the current
theme so we just adjust the layout a bit so it's prettier.
> NO-JIRA: doc/openstack: improve index layout

- ignition-server/controllers/local_ignitionprovider.go
PR #4331 added a check in the local ignition provider to validate that the bundle in the machine-config-server configmap under user-ca-bundle-config.yaml matched the bundle in the control plane namespace. However, the comparison was using the wrong configmap. The source of user-ca-bundle-config.yaml is trusted-ca-bundle-managed and not user-ca-bundle. This fix keeps the verification of the hash against user-ca-bundle since that hash is generated by the nodepool controller. However, when comparing the contents of the mcs configmap, it switches to the trusted-ca-bundle-managed configmap, since both should contain the aggregate of .spec.additionalTrustBundle and
**Which issue(s) this PR fixes** *(optional, use …
> OCPBUGS-45511: Compare contents of user-ca-bundle-config.yaml to the correct configmap

- test/e2e/create_cluster_test.go
This is dropped to let e2e succeed with the tech-preview-no-upgrade flag enabled https://github.com/openshift/release/pull/60715
Fixes #
**Checklist**
> NO-JIRA: Drop openstack create rejection validation

- contrib/managed-azure/setup_dev_environment.md
Fix managed azure docs for development
> NO-JIRA: Fix dev docs for managed azure

- go.mod
- go.sum
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/BREAKING_CHANGES.md
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/CHANGELOG.md
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/README.md
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TOKEN_CACHING.MD
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/TROUBLESHOOTING.md
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azidentity.go
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_cli_credential.go
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/azure_developer_cli_credential.go
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/chained_token_credential.go
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/ci.yml
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/confidential_client.go
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/default_azure_credential.go
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/device_code_credential.go
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/interactive_browser_credential.go
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/managed_identity_client.go
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/public_client.go
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/test-resources-post.ps1
- vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/version.go
- vendor/github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/oauth/ops/authority/authority.go
- vendor/modules.txt
Bumps the azure-github-dependencies group with 1 update: [github.com/Azure/azure-sdk-for-go/sdk/azidentity](https://github.com/Azure/azure-sdk-for-go).
Updates `github.com/Azure/azure-sdk-for-go/sdk/azidentity` from 1.8.0 to 1.8.1
- [Release notes](https://github.com/Azure/azure-sdk-for-go/releases)
- [Changelog](https://github.com/Azure/azure-sdk-for-go/blob/main/documentation/release.md)
- [Commits](https://github.com/Azure/azure-sdk-for-go/compare/sdk/azcore/v1.8.0...sdk/azidentity/v1.8.1)
---
updated-dependencies:
- dependency-name: github.com/Azure/azure-sdk-for-go/sdk/azidentity
dependency-type: direct:production
update-type: version-update:semver-patch
dependency-group: azure-github-dependencies
...
Signed-off-by: dependabot[bot] …
> NO-JIRA: Bump github.com/Azure/azure-sdk-for-go/sdk/azidentity

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/kubevirt-csi-controller/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/kubevirt-csi-controller/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/kubevirt-csi-controller/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/kubevirt-csi-controller/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kubevirt-csi-controller/OWNERS
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kubevirt-csi-controller/config.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kubevirt-csi-controller/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kubevirt-csi-controller/infra_role.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kubevirt-csi-controller/infra_rolebinding.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kubevirt-csi-controller/infra_serviceaccount.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kubevirt-csi-controller/kubeconfig.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/csi/kubevirt/OWNERS
- control-plane-operator/controllers/hostedcontrolplane/v2/csi/kubevirt/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/csi/kubevirt/config.go
- control-plane-operator/controllers/hostedcontrolplane/v2/csi/kubevirt/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/csi/kubevirt/kubeconfig.go
> HOSTEDCP-2062: [CPO Refactor] Refactor kubevirt csi driver

- cmd/cluster/core/create.go
manual cherry-pick https://github.com/openshift/hypershift/pull/5341
> OCPBUGS-48170: fix disconnected via CLI

- cmd/infra/powervs/destroy.go
This PR adds functionality to delete DHCP server created in PowerVS Cloud Instance before the actual instance deletion.
We need it, so that we do not rely on PowerVS Cloud Instance's recursive delete functionality to delete all other dependent resources.
**Checklist**
- Subject and description added to both, commit and PR.
- This PR was tested locally.
> HOSTEDCP-2232: Destroy DHCP Server before PowerVS Cloud Instance deletion

- api/hypershift/v1beta1/nodepool_types.go
- cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go
This a manual backport of https://github.com/openshift/hypershift/pull/5276
> [release-4.17] OCPBUGS-46440: Allow ARM64 arch deployment on Agent platform

- contrib/managed-azure/README.md
- docs/content/how-to/azure/create-azure-cluster_on_aks.md
This PR:
- updates the `export USER_ACCOUNT_ID=$(az ad signed-in-user show | jq .id)` command to remove the quotes around the value that were previously being saved
- updates the hyperlink for step 1 on the README.md file in the contrib directory. It was previously pointing to the wrong document
Fixes #
**Checklist**
> NO-JIRA: Fix a few bugs in Azure Upstream Docs

- docs/content/how-to/azure/create-azure-cluster_on_aks.md
This PR:
- adds more instructions and information on the ccoctl tool. It also fixes several minor issues with the instructions related to using the ccoctl here
Fixes #
**Checklist**
> NO-JIRA: Add instructions for ccoctl and fix minor issues

- hypershift-operator/controllers/hostedcluster/metrics/metrics.go
- hypershift-operator/controllers/hostedcluster/metrics/metrics_test.go
Add a metric to track the rosa hosted clusters which have the `hypershift.openshift.io/cluster-size-override` annotation set. 
Fixes [HOSTEDCP-1706](https://issues.redhat.com//browse/HOSTEDCP-1706)
**Checklist**
> HOSTEDCP-1706: feat: add a metric for cluster size override annotation

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-node-tuning-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-node-tuning-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-node-tuning-operator/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-node-tuning-operator/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-node-tuning-operator/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-node-tuning-operator/role.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-node-tuning-operator/rolebinding.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-node-tuning-operator/service.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-node-tuning-operator/serviceaccount.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-node-tuning-operator/servicemonitor.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/nto/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/nto/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/nto/servicemonitor.go
> HOSTEDCP-2245: [CPO Refactor] Refactor cluster-node-tuning-operator

- support/controlplane-component/controlplane-component.go
- support/controlplane-component/generic-adapter.go
- support/util/util.go
> HOSTEDCP-2256: [CPO Refactor] Delete component and its resources when predicate changes to false

- support/metrics/sets.go
- support/metrics/testdata/sreconfig.yaml
> MON-4129: adjust Prometheus classic histograms 'le' related selectors in relabel config to accommodate the update to Prometheus v3

- test/e2e/create_cluster_test.go
- test/e2e/util/util.go
> HOSTEDCP-2120: Enable EnsureCustomLabels e2e test

- test/e2e/create_cluster_test.go
- test/e2e/util/util.go
Reverts openshift/hypershift#5511
> OCPBUGS-49804: Revert "HOSTEDCP-2120: Enable EnsureCustomLabels e2e test"

- test/e2e/create_cluster_test.go
- test/e2e/util/oauth.go
> HOSTEDCP-2040: Add TestCreateClusterCustomConfigV2

- support/controlplane-component/README.md
> NO-JIRA: Update cpov2 docs

- control-plane-operator/controllers/hostedcontrolplane/kas/config.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/config.go
supersedes https://github.com/openshift/hypershift/pull/5359
> OCPBUGS-45600: enforce privileged PSA by default

- control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/pki.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/5204
/assign openshift-cherrypick-robot
/cherrypick release-4.16 release-4.15 release-4.14
> [release-4.17] OCPBUGS-45268: Reconcile proxy CA bundle into hosted cluster

- control-plane-operator/controllers/hostedcontrolplane/olm/olm-collect-profiles.go
> NO-JIRA: Apply additional labels to CollectProfilesCronJob

- hypershift-operator/controllers/nodepool/conditions.go
- hypershift-operator/controllers/nodepool/nodepool_controller.go
> NO-JIRA: Remove haproxy generation error for normal flow

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/dns-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/dns-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/dns-operator/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/dns-operator/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/dns-operator/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/dns-operator/kubeconfig.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/dnsoperator/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/dnsoperator/deployment.go
> HOSTEDCP-2243: Refactor dns operator into cpov2

- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-storage-operator/serviceaccount.yaml
- support/controlplane-component/controlplane-component.go
- support/upsert/upsert.go
> NO-JIRA: Ensure 'pull-secret' is set properly on v2 serviceAccounts

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/machine-approver/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/machine-approver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/machine-approver/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/machine-approver/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/machine-approver/config.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/machine-approver/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/machine-approver/role.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/machine-approver/rolebinding.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/machine-approver/serviceaccount.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/machine_approver/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/machine_approver/deployment.go
> HOSTEDCP-2244: Refactor machine approver into cpov2

- cmd/infra/azure/create.go
- support/controlplane-component/builder.go
- support/controlplane-component/controlplane-component.go
> NO-JIRA: update hypershift azure roles to use ids

- cmd/cluster/core/dump.go
- support/controlplane-component/builder.go
- support/controlplane-component/controlplane-component.go
> NO-JIRA: add secretproviderclass to dump

- api/hypershift/v1beta1/hosted_controlplane.go
- api/hypershift/v1beta1/hostedcluster_types.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AutoNodeKarpenter.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DisableClusterCapabilities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ImageStreamImportMode.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AutoNodeKarpenter.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DisableClusterCapabilities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ImageStreamImportMode.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
- docs/content/reference/api.md
- test/e2e/util/util.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hosted_controlplane.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
> NO-JIRA: Fix hc hcp cel inconsistency

- control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/testdata/zz_fixture_TestReconcileOauthDeploymentNoChanges.yaml
Cherry-picks https://github.com/openshift/hypershift/pull/5525
When using the konnectivity-https-proxy sidecar to communicate through workers, the proxy dials any configured proxy directly and fails to connect if it cannot trust the proxy's serving certificate. This commit adds mounts for the trusted-ca-bundle-managed configmap to sidecar containers that run the konnectivity-https-proxy. The configmap contains the aggregate of .spec.additionalTrustBundle and
This fixes the issue of the ingress operator not becoming available when using a proxy with a custom certificate.
In addition it propagates any proxy environment variables that are set on the control plane operator to the konnectivity-https-proxy containers. This is needed when the management …
> OCPBUGS-51050: Add HostedCluster additional trustbundles to konnectivity-https-proxy

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/ingress-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/ingress-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/ingress-operator/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/ingress-operator/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/ingress-operator/azure-secretprovider.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/ingress-operator/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/ingress-operator/podmonitor.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/ingressoperator/azure.go
- control-plane-operator/controllers/hostedcontrolplane/v2/ingressoperator/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/ingressoperator/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/ingressoperator/podmonitor.go
- support/controlplane-component/builder.go
- support/controlplane-component/defaults.go
- support/controlplane-component/kubeconfig.go
> HOSTEDCP-2241: [CPOv2 Refactor] Refactor ingress operator

- api/hypershift/v1beta1/hostedcluster_types.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AutoNodeKarpenter.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DisableClusterCapabilities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ImageStreamImportMode.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AutoNodeKarpenter.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DisableClusterCapabilities.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ImageStreamImportMode.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
- docs/content/reference/api.md
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
This is a revert of https://github.com/openshift/hypershift/pull/5258/commits/c7ee48dc34d9302461f6d507e80ee47c449adbb5 to reinforce CEL validation for IBMCloud.
Fixes #
**Checklist**
> NO-JIRA: Reenable ibm network cel

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/control-plane-pki-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/control-plane-pki-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/control-plane-pki-operator/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/control-plane-pki-operator/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/hosted-cluster-config-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/hosted-cluster-config-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/control-plane-pki-operator/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/control-plane-pki-operator/role.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/control-plane-pki-operator/rolebinding.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/control-plane-pki-operator/serviceaccount.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/hosted-cluster-config-operator/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/pkioperator/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/pkioperator/deployment.go
> HOSTEDCP-2247: [CPOv2 Refactor] Refactor control-plane-pki-operator

- OWNERS
Updating IBM reviewers
Fixes #
**Checklist**
> NO-JIRA: chore(owners): Update IBM reviewers

- control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oauth/testdata/zz_fixture_TestReconcileOauthDeploymentNoChanges.yaml
Manual cherry-pick for https://github.com/openshift/hypershift/pull/5707
When using the konnectivity-https-proxy sidecar to communicate through workers, the proxy dials any configured proxy directly and fails to connect if it cannot trust the proxy's serving certificate. This commit adds mounts for the trusted-ca-bundle-managed configmap to sidecar containers that run the konnectivity-https-proxy. The configmap contains the aggregate of .spec.additionalTrustBundle and
This fixes the issue of the ingress operator not becoming available when using a proxy with a custom certificate.
In addition it propagates any proxy environment variables that are set on the control plane operator to the konnectivity-https-proxy containers. This is needed when the …
> OCPBUGS-52172: [release-4.15] Add HostedCluster additional trustbundles to konnectivity-https-proxy

- .tekton/control-plane-operator-main-pull-request.yaml
- .tekton/control-plane-operator-main-push.yaml
- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
Does the migration steps in #5527 
Fixes #
**Checklist**
> NO-JIRA: chore(deps): update konflux references #5527

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-image-registry-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-image-registry-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-image-registry-operator/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-image-registry-operator/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-image-registry-operator/azure-secretprovider.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-image-registry-operator/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-image-registry-operator/podmonitor.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/registryoperator/azure.go
- control-plane-operator/controllers/hostedcontrolplane/v2/registryoperator/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/registryoperator/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/registryoperator/podmonitor.go
> HOSTEDCP-2242: [CPOv2 Refactor] Refactor image-registry-operator

- hypershift-operator/controllers/nodepool/metrics/metrics.go
Fixes a customer visible typo in the metrics code of the HyperShift Operator
Fixes #OCPBUGS-46340
**Checklist**
> OCPBUGS-46340: change plaform to platform

- docs/content/how-to/kubevirt/create-kubevirt-cluster.md
Document hot to configure the cluster-kube-descheduler operator to configure the descheduler according to the `SoftTopologyAndDuplicates` profile in order to satisfy a topologySpreadConstraint to continuously spread VMs for a NodePool out across multiple underlying nodes.
Fixes [CNV-57648](https://issues.redhat.com//browse/CNV-57648)
**Checklist**
> CNV-57648: document how to configure descheduler

- karpenter-operator/controllers/karpenter/machine_approver.go
- karpenter-operator/controllers/karpenter/machine_approver_test.go
> HOSTEDCP-2237: Auto approve Karpenter serving CSRs

- cmd/cluster/core/create.go
This PR adds a flag to the HyperShift CLI allowing the etcd storage size to be set during cluster creation.
Fixes OCPBUGS-52655
**Checklist**
> OCPBUGS-52655: Add flag to set etcd storage size

- docs/content/how-to/disaster-recovery/etcd-recovery.md
Small nit on doc
Fixes #[OCPBUGS-51364](https://issues.redhat.com/browse/OCPBUGS-51364)
> OCPBUGS-51364: fix oc patch command on doc

- hypershift-operator/controlplaneoperator-overrides/assets/overrides.yaml
Define the necessary CPO overrides to deal with OCPBUGS-48519 for the users that opt-in to CPO overrides with the HyperShift Operator env var:
ENABLE_CPO_OVERRIDES=1
Fixes #OCPBUGS-48519
**Checklist**
> OCPBUGS-52819: CPO Overrides for OCPBUGS-48519

- hypershift-operator/controllers/platform/aws/controller.go
`AWSEndpointServiceReconciler` is currently making a ton of AWS API calls because we reconcile on all `HostedCluster` and `NodePool` changes, which are very frequent during HosterCluster bringup.
24h AWS call volume across all HOs running in prow job mgmt clusters
```
DescribeVpcEndpointServiceConfigurations 76235
DescribeVpcEndpointServicePermissions 75033
DescribeLoadBalancers 39389
```
All of these originate from the `AWSEndpointServiceReconciler`.
This PR filters events triggered by `HostedCluster` and `NodePool` changes to only reconcile if fields we care about change.  These are:
* `hostedCluster.Spec.Platform.AWS.AdditionalAllowedPrincipals`
* `nodePool.Spec.Platform.AWS.Subnet.ID`
We already do this filtering on the CPO side …
> OCPBUGS-52985: filter watch events for HO AWSEndpointService reconciler

- hypershift-operator/controllers/hostedcluster/network_policies.go
- hypershift-operator/controllers/manifests/networkpolicy/manifests.go
this is a manual backport of #5120
Fixes #
**Checklist**
> [release-4.14] OCPBUGS-45559: Add Network Policies for Konnectivity server and Ignition server proxy

- control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/v2/cno/azure.go
- control-plane-operator/controllers/hostedcontrolplane/v2/cno/deployment.go
- support/config/constants.go
Reverts openshift/hypershift#5837
> Revert "CNTRLPLANE-112: Enable MIv3 for CNO/CNCC on managed Azure"

- docs/mkdocs.yml
This commit adds the Azure schedule doc to the mkdocs so this page will display on our upstream website.
N/A
**Checklist**
> NO-JIRA: Add Azure scheduler doc to mkdocs

- .tekton/OWNERS
Konflux contributions should be labeled as ci-tooling. Also adding myself to the OWNERS since I'm fiddling with it all the time.
It will be less of a chore to handle Konflux PRs
**Checklist**
> NO-JIRA: feat(builds): Add area labels and OWNERS

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/etcd/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/etcd/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/etcd/statefulset.yaml
- support/controlplane-component/controlplane-component.go
- support/controlplane-component/controlplane-component_test.go
- support/controlplane-component/crds/crds.go
- support/controlplane-component/generic-adapter.go
- support/upsert/apply.go
- support/upsert/apply_test.go
- support/upsert/upsert.go
> OCPBUGS-53263: Fixed cpov2 reconciliation making no-op calls to api-server

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/konnectivity-agent/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/konnectivity-agent/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/konnectivity-agent/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/konnectivity-agent/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_component.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/konnectivity-agent/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-apiserver/konnectivity-server-service.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/konnectivity_agent/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/konnectivity_agent/deployment.go
> CNTRLPLANE-336: [CPOv2 Refactor] Refactor konnectivity-agent into cpov2

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Introduced by https://github.com/openshift/hypershift/pull/5653 / OCPBUGS-50915
This breaks 4.14 https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-aws-ovn/1905180892821721088/artifacts/e2e-aws-ovn/hypershift-aws-run-e2e-external/artifacts/TestCreateCluster/namespaces/e2e-clusters-ggm95-create-cluster-m5bxt/core/pods/logs/cluster-api-65449c6847-8mvqs-manager-previous.log
Reverted by https://github.com/openshift/hypershift/pull/5910
Fixes #
**Checklist**
> NO-JIRA: Add version check for CAPI flag

- docs/content/reference/architecture/managed-azure/secrets-csi.md
- docs/content/reference/architecture/managed-azure/shared-ingress.md
- docs/mkdocs.yml
This PR:
- creates a managed Azure section
- adds a doc on SecretProviderClass for managed Azure
Fixes #
**Checklist**
> NO-JIRA: Add doc on SecretProviderClass for managed Azure

- test/e2e/util/util.go
to help debug https://issues.redhat.com/browse/OCPBUGS-54510
> NO-JIRA: test/e2e: output pod name on EnsureHCPPodsAffinitiesAndTolerations failure

- test/e2e/nodepool_test.go
> OCPBUGS-52983: Add check for expected conditions before running NodePool tests

- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment_test.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-oauth-apiserver/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-oauth-apiserver/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/oauth_apiserver/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/oauth_apiserver/deployment.go
- support/util/util.go
- support/util/util_test.go
Backport PR https://github.com/openshift/hypershift/pull/5876 manually.
> OCPBUGS-54411: Backport PR 5876 to release-4.18

- .tekton/hypershift-operator-main-pull-request.yaml
- .tekton/hypershift-operator-main-push.yaml
This commit enables ppc64le builds.
Fixes #
**Checklist**
> NO-JIRA: Enable ppc64le builds

- kas-bootstrap/kas_boostrap.go
> NO-JIRA: Add polling for kas-bootstrap kas network requests

- control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader.go
- control-plane-operator/hostedclusterconfigoperator/controllers/inplaceupgrader/inplaceupgrader_test.go
The MCD needs to honour dataplane proxy to pull the updated OS image and extensions
Fixes #
**Checklist**
> OCPBUGS-48540: Mcd proxy

- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment_test.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
- support/util/util.go
- support/util/util_test.go
Backport PR https://github.com/openshift/hypershift/pull/5876 to release-4.17 manually.
Finished pre-merge testing for the PR, detail see https://issues.redhat.com/browse/OCPBUGS-54841?focusedId=26964659&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26964659, looks good.
> OCPBUGS-54841: Add konnectivity-proxy sidecar to openshift-oauth-apiserver

- api/hypershift/v1beta1/hostedcluster_types.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AutoNodeKarpenter.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ClusterVersionOperatorConfiguration.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ImageStreamImportMode.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/KMSEncryptionProvider.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AutoNodeKarpenter.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ClusterVersionOperatorConfiguration.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ImageStreamImportMode.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/KMSEncryptionProvider.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
This is not supported on vanilla kube <1.31 which is a valid use case for IBM Cloud
Fixes #
**Checklist**
> OCPBUGS-54309: Drop isIP CEL check

- docs/README.md
This commit adds a README.md to the docs folder so others understand how to locally check any changes they make to the docs.
N/A
**Checklist**
> NO-JIRA: Add README.md to docs folder

- support/catalogs/images.go
- support/catalogs/images_test.go
> OCPBUGS-54810: Don't check if olm images exist if guest cluster

- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-apiserver/deployment.yaml
> OCPBUGS-54867: Use 135 for terminationGracePeriodSeconds for v2 KAS

- Makefile
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- kas-bootstrap/kas_boostrap.go
This PR adds the cpo container sync so we make sure the RHTAP and CPO Dockerfile stay in sync
N/A
**Checklist**
> NO-JIRA: Add cpo container sync to verify job

- cmd/cluster/core/dump.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/kas/admissionpolicies.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/admissionpolicies.go
- test/e2e/util/util.go
implements https://issues.redhat.com/browse/CNTRLPLANE-711
> CNTRLPLANE-711: transition admissionregistration from v1beta1 to v1

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/config.go
- control-plane-operator/controllers/hostedcontrolplane/ocm/config.go
- control-plane-operator/controllers/hostedcontrolplane/ocm/config_test.go
follow up for https://github.com/openshift/hypershift/pull/6060
Fixes #
**Checklist**
> CNTRLPLANE-713: Pass featuregates to ocm and oapi

- control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-apiserver/deployment.yaml
> [release-4.18] OCPBUGS-55146: Use 135 for terminationGracePeriodSeconds for v2 KAS

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
Follow-up to #6060
Minor unit test fix
> NO-JIRA: Fix hostedcluster_controller unit test for featuregate job

- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/deployment_test.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
- control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
- support/util/util.go
- support/util/util_test.go
Backport PR https://github.com/openshift/hypershift/pull/6017 to release-4.16 manually.
Finished pre-merge testing for the PR, detail see https://issues.redhat.com/browse/OCPBUGS-54914?focusedId=26980482&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-26980482, looks good.
> [release-4.16] OCPBUGS-54914: Add konnectivity-proxy sidecar to openshift-oauth-apiserver

- api/hypershift/v1beta1/hostedcluster_types.go
- control-plane-operator/controllers/hostedcontrolplane/kas/config.go
- control-plane-operator/controllers/hostedcontrolplane/kas/params.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/config.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/params.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
…chance
This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/6019
Fixes #
**Checklist**
> [release-4.18] OCPBUGS-55230: Add annotation to configure KAS goaway-chance

- docs/Makefile
- docs/content/how-to/disaster-recovery/backup-and-restore-oadp-1-5.md
- docs/mkdocs.yml
This PR includes the documentation around the new way to backup and restore HostedControlPlanes using the new Hypershift OADP plugin
- Fixes #[CNTRLPLANE-740](https://issues.redhat.com/browse/CNTRLPLANE-740)
> CNTRLPLANE-740: Add DR for HCP using OADP and Hypershift plugin

- control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
- control-plane-operator/controllers/hostedcontrolplane/olm/catalogs_test.go
> [release-4.18] OCPBUGS-55177: Don't check if olm images exist if guest cluster

- control-plane-operator/controllers/hostedcontrolplane/v2/kas/auth.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/auth_test.go
https://github.com/openshift/hypershift/pull/6073 follow-up to introduce the changes in CPOv2 as well.
Fixes #
**Checklist**
> CNTRLPLANE-334: Update KASv2 structured authentication configuration

- docs/content/custom.css
- docs/mkdocs.yml
This commit increases the content width in the upstream docs. The width is increased percentage wise so that a variety of monitor sizes should be accommodated.
N/A
**Checklist**
> NO-JIRA: Increase the content width in the upstream docs

- .tekton/hypershift-cli-mce-29-pull-request.yaml
- .tekton/hypershift-cli-mce-29-push.yaml
Updating the Konflux tekton files to fix https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/crt-redhat-acm-tenant/applications/release-mce-29/pipelineruns/mce-29-enterprise-contract-registry-standard-s7zt9/logs?task=verify
Fixes #
**Checklist**
> NO-JIRA: Update hypershift-cli-mce-29-pull-request.yaml

- control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
- control-plane-operator/controllers/hostedcontrolplane/olm/catalogs_test.go
> [release-4.17] OCPBUGS-55723: Don't check if olm images exist if guest cluster

- control-plane-operator/controllers/hostedcontrolplane/imageprovider/imageprovider.go
- control-plane-operator/controllers/hostedcontrolplane/testdata/cloud-controller-manager-aws/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cloud-controller-manager-aws/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-image-registry-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-image-registry-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/ingress-operator/zz_fixture_TestControlPlaneComponents.yaml
- control-plane-operator/controllers/hostedcontrolplane/testdata/ingress-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/control-plane-operator/deployment.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/control-plane-operator/podmonitor.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/control-plane-operator/role.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/control-plane-operator/rolebinding.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/assets/control-plane-operator/serviceaccount.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/controlplaneoperator/component.go
- control-plane-operator/controllers/hostedcontrolplane/v2/controlplaneoperator/deployment.go
- control-plane-operator/controllers/hostedcontrolplane/v2/controlplaneoperator/podmonitor.go
- control-plane-operator/controllers/hostedcontrolplane/v2/controlplaneoperator/role.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
- hypershift-operator/controllers/hostedcluster/testdata/control-plane-operator/zz_fixture_TestReconcileControlPlaneOperator.yaml
- hypershift-operator/controllers/hostedcluster/testdata/control-plane-operator/zz_fixture_TestReconcileControlPlaneOperator_component.yaml
- support/controlplane-component/status.go
- support/controlplane-component/token-minter-container.go
Refactor ControlPlaneOperator into v2 component.
Fixes #
**Checklist**
> CNTRLPLANE-844: Refactor ControlPlaneOperator into v2 component

- api/hypershift/v1beta1/controlplanecomponent_types.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/controlplanecomponents.hypershift.openshift.io/AAA_ungated.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/controlplanecomponents.crd.yaml
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/controlplanecomponent_types.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests.yaml
> NO-JIRA: Remove ControlPlaneV2 API featuregate

- control-plane-operator/hostedclusterconfigoperator/controllers/resources/kas/admissionpolicies.go
- control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/admissionpolicies.go
manual backport of https://github.com/openshift/hypershift/pull/6005 with only CPO changes
> OCPBUGS-56524: switch admissionregistration API to v1

- support/controlplane-component/controlplane-component.go
- support/controlplane-component/generic-adapter.go
> NO-JIRA: Fix serviceaccounts with custom adapter not getting pull-secret

- control-plane-operator/controllers/hostedcontrolplane/v2/kas/auth.go
so that all validation that is performed is based on the minimum supported Kubernetes version.
Fixes #
**Checklist**
> NO-JIRA: cpo/oidc: remove validation functions that use default CEL compiler

- control-plane-operator/controllers/hostedcontrolplane/v2/assets/assets.go
This is needed when RHOBS is enabled, otherwise the monitoring manifests like PodMonitors will fail to load as they have the prometheous api group which is not registered in the scheme when RHOBS is enabled.
Fixes #
**Checklist**
> OCPBUGS-57125: Support RHOBS when loading cpov2 monitoring manifests by replacing the API group

- Makefile
- api/hypershift/v1beta1/aws.go
- api/hypershift/v1beta1/hostedcluster_types.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/OpenStack.yaml
- cmd/cluster/core/create.go
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-TechPreviewNoUpgrade.crd.yaml
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/auth.go
- control-plane-operator/controllers/hostedcontrolplane/v2/kas/config.go
- docs/content/reference/api.md
- support/validations/authentication.go
- test/e2e/upgrade_hypershift_operator_test.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/aws.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
This PR enables codespell and fixes all of the spelling mistakes.
Fixes [CNTRLPLANE-983](https://issues.redhat.com//browse/CNTRLPLANE-983)
**Checklist**
> CNTRLPLANE-983: Enable codespell in verify and fix all spelling mistakes

- hypershift-operator/controllers/nodepool/token.go
- hypershift-operator/controllers/nodepool/token_test.go
This reverts commit e61d3e0159a686a5c2ad5845966ae9b6e9b8ede7.
Fixes #[OCPBUGS-57497](https://issues.redhat.com/browse/OCPBUGS-57497)
**Checklist**
> OCPBUGS-57497: Revert "Add proxy trustedCA to ignition config"

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
- hypershift-operator/controllers/hostedcluster/karpenter.go
- hypershift-operator/main.go
- support/globalconfig/imagecontentsource.go
- support/globalconfig/imagecontentsource_test.go
Manual cherry-pick of https://github.com/openshift/hypershift/pull/6095
Fixes #
**Checklist**
> OCPBUGS-57299: Reuse hosted cluster release and metadata providers

- api/hypershift/v1beta1/hostedcluster_types.go
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AutoNodeKarpenter.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ClusterVersionOperatorConfiguration.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDCWithUIDAndExtraClaimMappings.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ImageStreamImportMode.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/KMSEncryptionProvider.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AAA_ungated.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AutoNodeKarpenter.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ClusterVersionOperatorConfiguration.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DynamicResourceAllocation.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDC.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDCWithUIDAndExtraClaimMappings.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ImageStreamImportMode.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/KMSEncryptionProvider.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
- api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-Default.crd.yaml
- cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
Momentarily drop the version history limit
Fixes #ocpbugs-58200
**Checklist**
> OCPBUGS-58200: Drop version history length

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Deletes the capi provider deployment before applying it, it the existing deployment has older labels
Fixes #OCPBUGS-58213
**Checklist**
> OCPBUGS-58213: Ensure that capi-provider deployment does not have outdated labels

- hack/tools/deployment/deployment-update.go
- Changes in the ROSA environment
- Update ROSA Sector 5 group with new environment
- Created new group that **Should not be updated**
> NO-JIRA: Update ROSA envs

- test/e2e/upgrade_hypershift_operator_test.go
- test/e2e/util/hypershift_framework.go
- test/e2e/util/util.go
> NO-JIRA: Run validate conditions after ho upgrade test

- test/e2e/nodepool_rolling_upgrade_test.go
> CNTRLPLANE-1042: Add nodepool rollout test for azure

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
- hypershift-operator/main.go
- support/globalconfig/imagecontentsource.go
- support/globalconfig/imagecontentsource_test.go
Manual cherry-pick of https://github.com/openshift/hypershift/pull/6250
Fixes #
**Checklist**
> OCPBUGS-57818: Reuse hosted cluster release and metadata providers

- contrib/managed-azure/README.md
- contrib/managed-azure/create_basic_hosted_cluster.sh
- contrib/managed-azure/setup_MIv3_kv.sh
- contrib/managed-azure/setup_aks_cluster.sh
- contrib/managed-azure/setup_all.sh
- contrib/managed-azure/setup_dataplane_identities.sh
- contrib/managed-azure/setup_etcd_kv.sh
- contrib/managed-azure/setup_external_dns.sh
- contrib/managed-azure/setup_install_ho_on_aks.sh
- contrib/managed-azure/setup_oidc_provider.sh
- contrib/managed-azure/vars.sh
> NO-JIRA: Fix up contrib scripts for aro like env

- test/e2e/control_plane_upgrade_test.go
> CNTRLPLANE-993: Skip azure 4.19 cp upgrade for now to let the 4.20 suite be covered.

- test/e2e/util/util.go
Addresses flaking e2e test on ARO HCP clusters due to race condition between external DNS resolution and internal cluster DNS propagation.
Changes:
- Add Azure-specific retry logic with 10-minute timeout (vs 5-minute default)
- Detect DNS-related errors for targeted retries ("no such host", "dial tcp", "failed to get API group resources")
- Add success logging for custom kubeconfig verification
This ensures tests run at full speed while gracefully handling the DNS propagation delay.
Fixes https://issues.redhat.com/browse/OCPBUGS-59232
**Checklist**
> OCPBUGS-59232: fix(test): resolve Azure DNS race condition in EnsureCustomAdminKubeconfigReachesTheKAS

- contrib/managed-azure/README.md
- contrib/managed-azure/setup_MIv3_kv.sh
- contrib/managed-azure/setup_backup_extension.sh
- Includes the automation to configure and deploy Microsoft Backup Extension
- Modified MIv3 script to include velero secrets
- Modified README to include some doc.
- Fixes #[CNTRLPLANE-735](https://issues.redhat.com/browse/CNTRLPLANE-735)
> CNTRLPLANE-735: Document steps to configure Microsoft backup extension in AKS

- test/e2e/util/util.go
Follow up to https://github.com/openshift/hypershift/pull/6245
> NO-JIRA: test/e2e: add TerminationMessagePolicyFallbackToLogsOnError check to 4.19

- docs/content/how-to/disaster-recovery/backup-and-restore-oadp-1-5.md
- docs/content/how-to/disaster-recovery/backup-and-restore-oadp.md
- Adds new providers to the upstream doc from HCP OADP Plugin repo with new examples
- Fixes images pointing to the old Konflux references
> NO-JIRA: Add new doc from HCP OADP Plugin

- contrib/managed-azure/setup_aks_cluster.sh
- Fixes Pod Limitation on AKS node 
- https://github.com/openshift/release/pull/66659/files#diff-f802d6c8cc070ec9ee49b1ac00862c31bde3e1e302a06b119f15bd84501f7787R72
> NO-JIRA: increase the pod limit per node in AKS cluster

- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
Resolves the bug that if .spec.additionalTrustBundle is changed to nil on a HostedCluster, the original configmap remains in the control plane namespace, causing ignition payload generation to fail.
Extracts existing code that places .spec.additionalTrustBundle into its own function so it can be unit tested and handles the bundle changing to nil by removing the corresponding ConfigMap from the control plane namespace. Adds unit test.
Fixes #[OCPBUGS-57336](https://issues.redhat.com/browse/OCPBUGS-57336)
**Checklist**
> OCPBUGS-57336: Delete unused AdditionalTrustBundle from CP namespace

- .tekton/hypershift-cli-mce-210-pull-request.yaml
- .tekton/hypershift-cli-mce-210-push.yaml
- .tekton/hypershift-release-mce-210-pull-request.yaml
- .tekton/hypershift-release-mce-210-push.yaml
This PR is for building MCE 2.10 version of hypershift operator and hcp cli.
Fixes #https://issues.redhat.com/browse/OCPBUGS-59835
**Checklist**
> OCPBUGS-59835: MCE 2.10 konflux

- cmd/cluster/aws/create.go
In order to share an OIDC provider across multiple job mgmt clusters, we need set `spec.serviceAccountSigningKey` on the `HostedCluster` at create time.  The `cluster create azure` code already has this flag.
This PR adds the flag for `cluster create aws` as well.
> CNTRLPLANE-1191: add sa-token-issuer-private-key-path flag to create cluster aws

- CLAUDE.md
**What this PR does / why we need it**:  
Add CLAUDE.md file to provide structured guidance for Claude Code instances working in the HyperShift repository. Includes repository architecture overview, essential development commands, testing strategy, and common development patterns. 
This improves onboarding and productivity for future development work by providing a centralized reference for project-specific commands, patterns, and conventions.
N/A
**Checklist**
> NO-JIRA: add CLAUDE.md with comprehensive development guidance

- Makefile
Include gitlint validation in the verify make target to ensure commit message formatting is checked as part of the standard development workflow.
Fixes #
**Checklist**
> CNTRLPLANE-1116: build(gitlint): add gitlint to verify target

- support/controlplane-component/controlplane-component.go
> NO-JIRA: docs: Document workloadContext

- control-plane-operator/controllers/hostedcontrolplane/kas/healthcheck.go
Fixes # `make verify e2e failed`
should be related to https://github.com/openshift/hypershift/pull/6614
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/6616/pull-ci-openshift-hypershift-main-verify/1953483594403942400
**Checklist**
> NO-JIRA: Fix typo causing 'make verify' to fail

- sharedingress-config-generator/config.go
- sharedingress-config-generator/router_config.template
- sharedingress-config-generator/testdata/zz_fixture_TestGenerateConfig_When_there_s_two_HostedClusters_with_all_their_Routes_and_SVCs_it_should_generate_the_config_with_frontends_and_backends_for_both.cfg
- test/e2e/util/util.go
Otherwise haproxy complains about lines too long
Fixes #
**Checklist**
> OCPBUGS-60187: chore: Split shared proxy acls

- docs/content/how-to/kubevirt/ingress-and-dns.md
Small  fix in the docs.
Fixes #
**Checklist**
- [/] Subject and description added to both, commit and PR.
- [/] Relevant issues have been referenced.
- [/] This change includes unit tests.
> NO-JIRA: Update ingress-and-dns.md - update Metallb install link

- test/e2e/util/options.go
https://github.com/openshift/hypershift/pull/6467 follow-up
Fixes #
**Checklist**
> CNTRLPLANE-996: feat(e2e): Use ROSAManagedPolicies by default

- control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
Manual backport of https://github.com/openshift/hypershift/pull/6673
Fixes [OCPBUGS-60648](https://issues.redhat.com/browse/OCPBUGS-60648)
**Checklist**
> OCPBUGS-60648: Cache Azure KMS TokenCredential for ARO HCP and clarify CPO credentials cache naming

- api/hypershift/v1beta1/hostedcluster_types.go
- hypershift-operator/controllers/hostedcluster/validations/ocpapiserver.go
- hypershift-operator/controllers/hostedcluster/validations/ocpapiserver_test.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
- Manual backport of https://github.com/openshift/hypershift/pull/6643
> [release-4.19] OCPBUGS-60483: feat(validations): add wildcard support to DNS SAN conflict detection

- api/hypershift/v1beta1/hostedcluster_types.go
- hypershift-operator/controllers/hostedcluster/validations/ocpapiserver.go
- hypershift-operator/controllers/hostedcluster/validations/ocpapiserver_test.go
- vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go
- Manual backport of https://github.com/openshift/hypershift/pull/6648
> [release-4.18] OCPBUGS-60485: feat(validations): add wildcard support to DNS SAN conflict detection

- control-plane-operator/controllers/hostedcontrolplane/v2/kas/config.go
Disable PSA enforcement in 4.20
Related to https://github.com/openshift/api/pull/2475
> OCPBUGS-56778: fix(kas): Disable PSA enforcement in 4.20

- konnectivity-https-proxy/cmd.go
- konnectivity-https-proxy/cmd_test.go
4.19 backport of https://github.com/openshift/hypershift/pull/6789
> OCPBUGS-61567: [release-4.19] fix(proxy): ensure URLs have scheme before proxy resolution

- test/e2e/autoscaling_test.go
This addresses two issues:
- Failure in `testAutoscaling` leaving workload job orphaned and tripping up `testAutoscalingBalancing`
- Make the HC update in `testAutoscalingBalancing` tolerant of transient 409 conflict errors
> OCPBUGS-62099: make TestAutoscalingBalancing more robust

- cmd/install/assets/hypershift_operator.go
- control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/controller.yaml
- control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/infra_role.yaml
- control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go
- control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt_test.go
- hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
Manual backport of https://github.com/openshift/hypershift/pull/6226
Fixes #
**Checklist**
> [release-4.18] OCPBUGS-61700: Sync RBAC for expansion support in kubevirt CSI driver

- .claude/commands/jira-solve.md
This PR enhances the `jira-solve` command documentation to improve the PR creation workflow. The updates include:
- **PR description review loop**: Adds an iterative refinement step where the AI reviews and improves the PR description before committing, ensuring quality and completeness
- **Logical commit organization**: Introduces a structured approach to breaking commits into logical components (API changes, vendor updates, CLI modifications, operators, etc.) to make PRs easier to review
- **Automatic linting**: Integrates `make lint-fix` execution after code changes to ensure proper import sorting and adherence to project conventions
These improvements streamline the development workflow and ensure that PRs follow project best practices, making them easier for reviewers to understand …
> CNTRLPLANE-1545: docs(commands): improve jira-solve command with logical commit organization

- OWNERS
- OWNERS_ALIASES
Per $subject.
Modelled on kubevirt's approach.
> NO-JIRA: Add openstack-reviewers, openstack-approvers
