control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go

Set `ImportMode` to `PreserveOriginal` for `catalogs` image
Ref: https://issues.redhat.com/browse/OCPBUGS-32492

OCPBUGS-32492: Set ImportMode for catalog

---

control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go

This container doesn't have an associated service, so a readiness probe doesn't make sense. It can be removed.
Fixes #https://issues.redhat.com/browse/OCPBUGS-32255
**Checklist**

OCPBUGS-32255: Remove kube-scheduler readiness probe

---

hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go

When a HostedCluster is deleted, make sure that there are no leftover placeholder deployments for it.
Fixes #[OCPBUGS-32378](https://issues.redhat.com/browse/OCPBUGS-32378)
**Checklist**

OCPBUGS-32378: Ensure placeholder deployments are deleted

---

hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go

Avoid taking deleting nodes into consideration when making scheduling decisions.
Fixes #[OCPBUGS-32760](https://issues.redhat.com/browse/OCPBUGS-32760)
**Checklist**

OCPBUGS-32760: Request serving scheduler: omit deleting nodes

---

api/hypershift/v1beta1/nodepool_conditions.go
hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/nodepool/nodepool_controller_test.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_conditions.go

The hosted cluster's cluster-network needs to be on a separate cidr range from the worker nodes. Otherwise network degradation  will occur.
This PR adds a condition to the nodepool object to indicate when the cluster-network collides with the machines within the nodepool.

CNV-40687: Detect machine and cluster-network cidr collision

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/kcm/config.go

Fixes #[OCPBUGS-31398](https://issues.redhat.com/browse/OCPBUGS-31398)

OCPBUGS-31398: Recycler-pod image now points to the OCP Payload reference

---

.tekton/hypershift-operator-main-pull-request.yaml
.tekton/hypershift-operator-main-push.yaml

Update RHTAP tekton files for 0.3 -> 0.4 migration
Fixes [HOSTEDCP-1552](https://issues.redhat.com/browse/HOSTEDCP-1552)
**Checklist**

HOSTEDCP-1552: Update RHTAP tekton files for 0.3 -> 0.4 migration

---

.tekton/hypershift-release-mce-25-pull-request.yaml
.tekton/hypershift-release-mce-25-push.yaml

Update RHTAP tekton files for 0.3 -> 0.4 migration
Fixes [HOSTEDCP-1552](https://issues.redhat.com/browse/HOSTEDCP-1552)
**Checklist**

HOSTEDCP-1552: Update RHTAP tekton files for 0.3 -> 0.4 migration 

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/manifests/ingress.go
control-plane-operator/main.go

Backport of #3489
Fixes #[OCPBUGS-33105](https://issues.redhat.com/browse/OCPBUGS-33105)
**Checklist**

OCPBUGS-33105: [release-4.14] remove PrivateIngressController cleanup

---

hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go

Fixes a bug introduced by #3941 which results in a nil pointer deref when configuration does not contain an 'effects' section.
Fixes #[OCPBUGS-33101](https://issues.redhat.com/browse/OCPBUGS-33101)
**Checklist**

OCPBUGS-33101: Fix nil pointer deref when effects not specified in CSC

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

Reverts previous commits that removed RBAC for ingress controllers in control plane operator role
Fixes #[OCPBUGS-33132](https://issues.redhat.com/browse/OCPBUGS-33132)
**Checklist**

OCPBUGS-33132: Restore ingresscontroller rbac

---

api/hypershift/v1beta1/hostedcluster_types.go
control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go

Manual backport of https://github.com/openshift/hypershift/pull/3846

OCPBUGS-32229: disable autoscaler when no nodepool require it

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
support/util/util.go

These changes extend the hostedcluster annotation scoping support to the nodepool controller.  This feature was originally introduced in https://github.com/openshift/hypershift/pull/3702, but support was only added to the hostedcluster controller at that time.
https://issues.redhat.com//browse/HOSTEDCP-1513

HOSTEDCP-1513: Add operator scoping support to nodepool controller

---

hypershift-operator/controllers/scheduler/autoscaler.go
hypershift-operator/controllers/scheduler/autoscaler_test.go
hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
hypershift-operator/main.go

Adds a controller to scale down any request serving machinesets that are no longer used by hosted clusters.
Fixes logic error when determining required nodes that resulted in additional nodepairs getting scaled up.
Fixes #[OCPBUGS-33203](https://issues.redhat.com/browse/OCPBUGS-33203)
[OCPBUGS-33274](https://issues.redhat.com/browse/OCPBUGS-33274)
**Checklist**

OCPBUGS-33203,OCPBUGS-33274: Autoscaler: scale down unused machinesets

---

control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go

This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/3889
/assign jonesbr17

[release-4.15] OCPBUGS-33207: Remove kube-scheduler readiness probe

---

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/controller.yaml

The default timeout is too low in certain cases causing issues. This increases the timeout to 3 minutes.
Fixes https://issues.redhat.com/browse/CNV-36073
**Checklist**

CNV-36073: Set time out for external snapshotter on kubevirt csi driver

---

api/hypershift/v1alpha1/hostedcluster_types.go
api/hypershift/v1beta1/hostedcluster_types.go
client/applyconfiguration/hypershift/v1alpha1/azureplatformspec.go
client/applyconfiguration/hypershift/v1beta1/azureplatformspec.go
cmd/cluster/azure/create.go
cmd/cluster/core/create.go
cmd/infra/azure/create.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml
control-plane-operator/controllers/hostedcontrolplane/cloud/azure/providerconfig.go
docs/content/reference/api.md
examples/fixtures/example.go
examples/fixtures/example_azure.go
hack/app-sre/saas_template.yaml
hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
support/azureutil/azureutil.go
support/azureutil/azureutil_test.go
test/e2e/e2e_test.go
vendor/github.com/openshift/hypershift/api/hypershift/v1alpha1/hostedcluster_types.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

This PR primarily fixes the misunderstand of how a resource group provided by a client will be used in ARO HCP. We originally implemented BYO resource group as a resource group in which to create all cloud infrastructure. That is not correct understanding and not how it will be used in ARO HCP.
The expected setup should be a client brings us a resource group with a existing vnet, subnet, and NSG already setup. ARO HCP would then create a managed resource group with all the cloud infrastructure items in it and use the client's vnet, subnet, and NSG from the provided resource group.
Essentially, this PR:
* removes subnet name from the API in favor of adding the subnet ID in the API instead
* removes the vnet name from the API in favor of using the …

HOSTEDCP-1544: Allow user to specify subnet ID for Hosted Cluster & NodePool Creation

---

api/hypershift/v1beta1/nodepool_types.go
cmd/cluster/core/create.go
cmd/cluster/powervs/create.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
docs/content/reference/api.md
hack/app-sre/saas_template.yaml
hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/nodepool/nodepool_controller_test.go
test/e2e/e2e_test.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go

Want to support ppc64le arch for Agent and PowerVS cloud platform.
Due to recent changes, 4.16 powervs is blocked to use multi arch release image. Trying to fix that as well.
Fixes #
**Checklist**

MULTIARCH-4637: Support ppc64le arch for Agent and PowerVS platform

---

cmd/cluster/powervs/create.go

Set arch to ppc64le within PowerVS applyPlatformSpecificsValues so that the arch is not overridden for other platforms.
Fixes #
**Checklist**

MULTIARCH-4637: Set arch to ppc64le within PowerVS platform func

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
konnectivity-socks5-proxy/main.go

CNO uses the konnectivity-socks5-proxy to perform cluster-wide-proxy readiness checks through the hosted cluster's network.
The cluster-wide-proxy address it uses should not be resolved to avoid double-proxy issues.

OCPBUGS-26762: Disable DNS resolving for CNO

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
support/util/util.go

This is a manual cherry pick of the changes introduced in https://github.com/openshift/hypershift/pull/3702 and https://github.com/openshift/hypershift/pull/3928 to allow for [Selective Management of HostedCluster Resources via Annotations for Hypershift Operators](https://issues.redhat.com/browse/OCPSTRAT-1300).

[release-4.15] HOSTEDCP-1513: Support hypershift-operator scoping for hostedclusters

---

api/hypershift/v1beta1/hostedcluster_types.go
cmd/infra/azure/create.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml
control-plane-operator/controllers/hostedcontrolplane/cloud/azure/providerconfig.go
docs/content/reference/api.md
hack/app-sre/saas_template.yaml
support/azureutil/azureutil.go
support/azureutil/azureutil_test.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

Sets the network security group (NSG) resource group based on the resource group in the NSG ID.
Fixes [HOSTEDCP-1557](https://issues.redhat.com/browse/HOSTEDCP-1557)
**Checklist**

HOSTEDCP-1557: Allow the NSG ID to drive the NSG Resource Group for the Azure Cloud Provider Config

---

api/hypershift/v1alpha1/nodepool_types.go
api/hypershift/v1beta1/nodepool_types.go
client/applyconfiguration/hypershift/v1alpha1/azurenodepoolplatform.go
client/applyconfiguration/hypershift/v1beta1/azurenodepoolplatform.go
cmd/cluster/azure/create.go
cmd/infra/azure/create.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
cmd/nodepool/azure/create.go
docs/content/reference/api.md
examples/fixtures/example.go
examples/fixtures/example_azure.go
hack/app-sre/saas_template.yaml
hypershift-operator/controllers/nodepool/azure.go
vendor/github.com/openshift/hypershift/api/hypershift/v1alpha1/nodepool_types.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go

Refine the Azure API in the NodePool Spec:
* add additional details to the NodePool API
* Remove SubnetName in favor of SubnetID in the NodePool API
Fixes [HOSTEDCP-1563](https://issues.redhat.com/browse/HOSTEDCP-1563)
**Checklist**

HOSTEDCP-1563: Refine the Azure API in the NodePool Spec

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
control-plane-operator/main.go

Fixes #[OCPBUGS-32257](https://issues.redhat.com/browse/OCPBUGS-32257)
**Checklist**

OCPBUGS-32257: Restrict image registry overrides to control plane components

---

control-plane-operator/controllers/hostedcontrolplane/kas/kms.go
control-plane-operator/controllers/hostedcontrolplane/kas/kms/azure.go
control-plane-operator/controllers/hostedcontrolplane/kas/params.go
control-plane-operator/main.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
support/images/envvars.go

Switch to using the `aws-kms-encryption-provider` and `azure-kms-encryption-provider` images from the payload.
This PR also removes the `IMAGE_AWS_ENCRYPTION_PROVIDER` environment variables that could be set on the HO and passed through the CPO to override this image.
`hypershift.openshift.io/aws-kms-provider-image` annotation on the HC is still respected.
Blocked until included in ART payload.

HOSTEDCP-1310: use kms images from payload

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator_test.go
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Preserve_existing_resources.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Private_apiserver_connectivity__proxy_apiserver_address_is_unset.yaml
control-plane-operator/controllers/hostedcontrolplane/olm/operator.go
control-plane-operator/controllers/hostedcontrolplane/olm/operator_test.go
control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go
control-plane-operator/controllers/hostedcontrolplane/olm/packageserver_test.go
control-plane-operator/controllers/hostedcontrolplane/olm/testdata/zz_fixture_TestReconcileCatalogOperatorDeployment_Preserve_existing_resources.yaml
control-plane-operator/controllers/hostedcontrolplane/olm/testdata/zz_fixture_TestReconcileOLMOperatorDeployment_Preserve_existing_resources.yaml

There are a few components leftover from the changes in https://github.com/openshift/hypershift/pull/3120 that still do not exhibit the expected resource preservation behavior.  The changes in this PR address these issues to ensure all control plane components preserve any externally sourced modifications to their resource requests/limits during their respective reconciliations.
https://issues.redhat.com/browse/HOSTEDCP-1518

HOSTEDCP-1518: Preserve container resource requests and limits

---

cmd/cluster/azure/create.go
cmd/cluster/core/create.go
cmd/infra/azure/create.go

Doesn't ignore the SubnetID and Network Security Group ID flags when values are passed in
Fixes [HOSTEDCP-1655](https://issues.redhat.com/browse/HOSTEDCP-1655)
**Checklist**

HOSTEDCP-1655: Don't Ignore SubnetID and Network Security Group ID flags when values are passed through

---

hypershift-operator/controllers/hostedclustersizing/hostedclustersizing_controller.go

Avoids an indefinite requeue of hosted clusters that no longer exist
Fixes #[OCPBUGS-33595](https://issues.redhat.com/browse/OCPBUGS-33595)
**Checklist**

OCPBUGS-33595: Cluster sizing controller: do not error on not found HC

---

control-plane-operator/controllers/hostedcontrolplane/dnsoperator/dnsoperator.go

https://github.com/openshift/cluster-dns-operator/pull/394 removed these flags and the standalone manifests does not use them.
https://github.com/openshift/cluster-dns-operator/blob/master/manifests/0000_70_dns-operator_02-deployment.yaml#L34-L38
Currently causing an e2e outage.

HOSTEDCP-1668: remove dns-operator leader-elect flags

---

support/util/imagemetadata.go
support/util/imagemetadata_test.go

This is a manual backport of https://github.com/openshift/hypershift/pull/3860
Now the hypershift operator does not ignore RegistryOverrides and the metadata inspection works as expected
Fixes #[OCPBUGS-29494](https://issues.redhat.com/browse/OCPBUGS-29494)

[release-4.15] OCPBUGS-32220: Fix disconnected metadata inspection

---

hypershift-operator/controllers/scheduler/autoscaler.go
hypershift-operator/controllers/scheduler/autoscaler_test.go

The current logic that looks at placeholder pods ignores unpaired pods because in the case of generic placeholders, the pods are likely in the middle of getting rolled out by their respective deployment. However, unpaired pods that correspond to a specific hosted cluster (have a pair node selector) can exist by themselves if there's already an existing node for the cluster. This commit updates the logic to not ignore single placeholder pods for specific hosted clusters.
Fixes #[OCPBUGS-33729](https://issues.redhat.com/browse/OCPBUGS-33729)
**Checklist**

OCPBUGS-33729: Do not ignore single placeholder pods for a specific hosted cluster

---

hypershift-operator/controllers/hostedclustersizing/hostedclustersizing_controller.go
hypershift-operator/controllers/hostedclustersizing/hostedclustersizing_controller_test.go

When the kube apiserver of a hosted cluster is not available, the replica status of nodepools will not be accurate because the CAPI controllers can no longer get node counts from the API server. This commit improves the handling of this situation with 2 changes:
- Switches to use .spec.replicas to determine node count of nodepools that do not have autoscaling turned on.
- Once a hosted cluster has been tagged with a size, only if the kube apiserver of the hosted cluster is available is the hosted cluster allowed to move to a different size.
- 
Fixes …

OCPBUGS-33659: Improve resliency of size tagging when hostedcluster KAS down

---

api/scheduling/v1alpha1/clustersizingconfiguration_types.go
cmd/install/assets/hypershift-operator/scheduling.hypershift.openshift.io_clustersizingconfigurations.yaml
hack/app-sre/saas_template.yaml
hypershift-operator/controllers/hostedclustersizing/hostedclustersizing_controller.go
hypershift-operator/controllers/hostedclustersizing/hostedclustersizing_controller_test.go
vendor/github.com/openshift/hypershift/api/scheduling/v1alpha1/clustersizingconfiguration_types.go

hostedclustersizing: don't enforce delays on brand-new clusters
Before, we would make brand-new clusters sit through the transition
delays erroneously. Now, we allow them to take on their first size
without any delay.
---
hostedclustersizing: don't enforce concurrency on new clusters
Before, we would enforce global concurrency limits on brand new clusters
joining the fleet and being given a size. This is not tenable with an
SLA for cluster bringup, so we no longer do that.
---

OCPBUGS-33802: don't delay new cluster creation

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go

Remove service-ca annotation from azure csi & file controller metrics services.
Fixes [OCPBUGS-33726](https://issues.redhat.com/browse/OCPBUGS-33726)
**Checklist**

OCPBUGS-33726: Remove service-ca annotation from azure csi & file controller metrics services

---

control-plane-operator/controllers/hostedcontrolplane/autoscaler/reconcile.go

Fixes #[HOSTEDCP-1556](https://issues.redhat.com/browse/HOSTEDCP-1556)
**Checklist**

HOSTEDCP-1556: Support Priority based expander for cluster-autoscaler

---

hypershift-operator/controllers/nodepool/nodepool_controller.go

We are relying on .image and .proxy here to trigger upgrades and create a new tokenSecret https://github.com/openshift/hypershift/pull/3714/files#diff-c666a2a9dc48b0d3de33cc8fa3a054f853671f0428f9d56b263750dfc6d26e00R266
but then we use the whole .config for the hash in the token and mcs secret https://github.com/openshift/hypershift/pull/3795/files#diff-681fe9efe998da46c20a41e51c975bac6a9b14e93b7705f40da204d30a0ddebcR49.
Say a new NodePool is created or something triggers a rolling upgrade:
- A new token secret gets created.
- Before the ignition controllers watches it and can generate the payload, the hc.config changes to e.g. include an IDP.
- The MCS secret hc-configuration-hash is updated accordingly.
- The token secret hc-configuration-hash is not updated, because that only happens …

OCPBUGS-33377: Modify token secret MCS hash in place 

---

test/e2e/nodepool_autorepair_test.go
test/e2e/nodepool_kms_root_volume_test.go
test/e2e/nodepool_kv_advanced_multinet_test.go
test/e2e/nodepool_kv_cache_image_test.go
test/e2e/nodepool_kv_jsonpatch_test.go
test/e2e/nodepool_kv_multinet_test.go
test/e2e/nodepool_kv_nodeselector_test.go
test/e2e/nodepool_kv_qos_guaranteed_test.go
test/e2e/nodepool_machineconfig_test.go
test/e2e/nodepool_nto_machineconfig_test.go
test/e2e/nodepool_nto_performanceprofile_test.go
test/e2e/nodepool_rolling_upgrade_test.go
test/e2e/nodepool_test.go
test/e2e/nodepool_upgrade_test.go
test/e2e/util/kubevirt.go

This change add a test to start a kubevirt hosted cluster with just secondary interface as primary network and start a companion dnsmasq pod attached to that network that acts as dhcp server, gateway and masquerade. The test only has one worker so this works as expected.
Fixes #
**Checklist**

CNV-40881: kubevirt, e2e, add test for advanced multinet

---

cmd/install/assets/hypershift_operator.go
control-plane-operator/controllers/hostedcontrolplane/nto/clusternodetuningoperator.go
hack/app-sre/saas_template.yaml
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

NTO is watching for the `ConfigMap` that encpasulets the `PerformanceProfile` and creates different components based on the given profile.
We should block the `PerformanceProfile` deletion as long as the dependent components exist.
For that NTO needs access the finalizers of the `ConfigMap`.
We should also update the control plane operator since
it's its responsibility to update NTO's role.
Fixes # [CNF-11559](https://issues.redhat.com/browse/CNF-11559)

CNF-12792:nto: add configmaps/finalizers under operator `Role`

---

cmd/install/assets/hypershift_operator.go
hack/app-sre/saas_template.yaml

Hypershift operator pods are created with higher `PriorityClass` but `external-dns`, to create a successful HCP we need both of them to up and available. Due to `default` priority class on `external-dns`, this pod gets evicted by the scheduler to fit higher priorityClass pods when there is no available space on suitable nodes.
Now setting the same `priorityClassName` used by the `operator` pod for `external-dns` pod as well.
Fixes # OCPBUGS-33742
**Checklist**

OCPBUGS-33742: setting higher priority class for external-dns pods

---

control-plane-pki-operator/certrotationcontroller/certrotationcontroller.go

in #4044, the `JiraComponent` and `Description` have been removed from the cert rotation objects since the struct have been changed and these fields were no longer exist. Afterwards it has been turned out that these fields were moved to `AdditionalAnnotations`. This PR reinstates the dropped fields.
Fixes #
**Checklist**

NO-JIRA: Reinstate wrongly removed fields from cert rotation objects

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/ingress/router.go
control-plane-operator/controllers/hostedcontrolplane/ingress/router_test.go
control-plane-operator/controllers/hostedcontrolplane/ingress/testdata/zz_fixture_TestGenerateRouterConfig.yaml
control-plane-operator/controllers/hostedcontrolplane/manifests/cno.go

In 4.13, we used the OCP router for HCP ingress.  The OCP router watches the endpoints of the target service and loads them directly into the haproxy config.  Thus a service with `clusterIP: None` works because the OCP router send traffic directly to pods, bypassing the service network.
In 4.14, we switched away from the OCP router to a simple haproxy pod with a fixed config file that routed to Service clusterIPs.  Because the `ovnkube-master-external` Services have `clusterIP: None`, the string `None` is loaded into the haproxy config template where the `ovnkube-master-external` service IP is expected.  The results in the router pod crash looping.
However, we don't use the `ovnkube-sbdb` Route in 4.14.  The failure is caused by lack of cleanup by the CNO which creates the  internal and …

OCPBUGS-25758: fix router on 4.14 y-stream upgrade

---

.tekton/hypershift-operator-main-pull-request.yaml
.tekton/hypershift-operator-main-push.yaml

This leverages a CEL expression to skip the konflux builds when changes only touch things like enhancements, docs, etc.
It reduces the load on Konflux by skipping builds for PRs that do not need it. It also makes those PRs quicker and easier to merge.
Fixes #[HOSTEDCP-1681](https://issues.redhat.com//browse/HOSTEDCP-1681)
**Checklist**

HOSTEDCP-1681: Skip konflux when not necessary

---

test/e2e/util/util.go

This check can flake if the curl command fails for reasons other than timing out.
In this job, for example, curl is unable to resolve the service network name.  Rather than give a false failure, we should allow it to pass and assume that one of the other tests in the e2e will catch it with a curl command that actually doesn't return an error when an error of some kind is expected.
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/4031/pull-ci-openshift-hypershift-main-e2e-aws/1793276481930006528

NO-JIRA: test: relax mgmt KAS egress check

---

hypershift-operator/controllers/scheduler/autoscaler.go
hypershift-operator/controllers/scheduler/autoscaler_test.go

Legacy nodes (nodes without a size label) are managed by fleet manager. Therefore we should not try to scale their respective machinesets down to avoid continuously reverting fleet manager's changes.
Fixes #[OCPBUGS-34071](https://issues.redhat.com/browse/OCPBUGS-34071)
**Checklist**

OCPBUGS-34071: Do not scale down legacy nodes

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
support/supportedversion/version.go

In the past, the KubeVirt platform had a minimum supported OCP version that differed from the default supported version. This is because KubeVirt required OCP version >= 4.14.  Now that the default minimum version is 4.14, we do not need to treat the kubevirt platform any differently.

NO-JIRA: Align kv min version to the default min version (now that default is >= 4.14

---

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
control-plane-operator/controllers/hostedcontrolplane/manifests/openshift_apiserver.go
control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go

OCPBUGS-33181: Fixed audit-logs sigterm failing to terminate gracefully

---

control-plane-operator/controllers/hostedcontrolplane/kas/config.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/kas/reconcile.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/config.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/kas.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
support/util/networking.go
support/util/networking_test.go

See issue for details and test results.
Fixes # https://issues.redhat.com/browse/OCPBUGS-33428
**Checklist**

OCPBUGS-33428: Reconcile KAS endpoints and endpoint slice

---

docs/content/how-to/agent/create-heterogeneous-nodepools.md

MULTIARCH-4668: Add how to doc for heterogeneous node pools on Agent platform

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes_test.go

DedicatedServingComponentScheduler* Operate over HCs as the driving resource. With current setup it might be possible for 2..10 reconciliations to happen conccurently resulting in those HC competing for Node pairs. This might result in Node pairs being split between different HCs silenty. Optimistic lock would make this discrepancy visible by making a patch request fail if one/both of the Nodes were changed. MaxConcurrentReconciles 1 would prevent the discrepancy from happening for most scenarios. Only the case where the intended transactional patch fails for one of the Nodes would potentially cause skew.
Adds the use of configmaps as a lease for a particular fleet manager pair label for a given hosted cluster. In order to label nodes with a given …

OCPBUGS-33987: Use configmaps to track hosted cluster pair labels and set controller concurrency

---

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcileDeployment.yaml

Removes liveness and readiness probes from `cluster-image-registry-operator` and `ingress-operator` This change was discussed in the project-hypershift slack channel. Should probes be desired, upstream operator teams should introduce health endpoints for their respective components. Hypershift should not rely on metrics endpoint as a stop gap for the probes endpoints.
Fixes #
**Checklist**

HOSTEDCP-1570: remove liveness and readiness probes using metrics endpoint

---

cmd/install/install.go
hack/app-sre/saas_template.yaml

Use the specified operator namespace for `openshift-config-managed-trusted-ca-bundle` configmap rather than hard-coding to `hypershift`.
https://issues.redhat.com/browse/HOSTEDCP-1688

HOSTEDCP-1688: Use operator namespace for openshift-config-managed-trusted-ca-bundle

---

control-plane-operator/controllers/hostedcontrolplane/cvo/params.go
control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/main.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/main.go
support/releaseinfo/registry_mirror_provider.go

This is a backport of:
- OCPBUGS-34540: Fix RegistryMirrorProvider modifying the cached image directly
- OCPBUGS-32257: Fix userReleaseProvider not using icsp/idms from mgmt cluster
Supersedes #4104 and #4111 
This will allow getting them both in together for the release branch.
**Checklist**

OCPBUGS-34602,OCPBUGS-34569: Backports that should go in together

---

cmd/install/install_render.go

Unexpected output was obtained when calling hypershift install render with both --template and --outputs specified. 
For example, "hypershift install render --template --outputs crds" outputs nothing. 
It looks like the --template flag is only used to generate saas template and is not used together with --outputs. 
This pr just prevents these two flags from being used together.

OCPBUGS-31568: Prevent hypershift install render --template and --outputs from being used together

---

hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes_test.go

We should error when there is an empty fleet manager label. However, we were checking for a non-empty fleet manager label.
Fixes #[OCPBUGS-34741](https://issues.redhat.com/browse/OCPBUGS-34741)
**Checklist**

OCPBUGS-34741: Fix fleet manager pair label check

---

cmd/infra/aws/iam.go

Bug fix - in hosted cluster on AWS STS cluster [secrets store provider](https://github.com/aws/secrets-store-csi-driver-provider-aws) can't mount secrets if `sts.amazonaws.com` is not set as audience for OIDC provider. See linked Jira for details.
There might be some security implications to setting this audience by default - suggestions welcome. I've checked what CCO does when creating infrastructure for STS clusters and it's hardcoded here: https://github.com/openshift/cloud-credential-operator/blob/2f29d9103ce284095aef5f9eb2b7679c134051a0/pkg/cmd/provisioning/aws/create_identity_provider.go#L341
fixes https://issues.redhat.com/browse/OCPBUGS-18711
**Checklist**

OCPBUGS-18711: add AWS STS URL to OIDC provider audiences

---

api/hypershift/v1beta1/hostedcluster_types.go
hypershift-operator/controllers/hostedclustersizing/hostedclustersizing_controller.go
hypershift-operator/controllers/hostedclustersizing/hostedclustersizing_controller_test.go

Introduces a hosted cluster annotation
`hypershift.openshift.io/cluster-size-override` that allows setting a cluster size regardless of the number of nodes in the cluster.
Fixes #[HOSTEDCP-1697](https://issues.redhat.com/browse/HOSTEDCP-1697)
**Checklist**

HOSTEDCP-1697: Allow overriding hosted cluster size label

---

hypershift-operator/main.go

Fix disconnected metadata inspection for nodepool
**Which issue(s) this PR fixes:**
Fixes #[OCPBUGS-34734](https://issues.redhat.com/browse/OCPBUGS-34734)

OCPBUGS-34734: Fix disconnected metadata inspection for nodepool

---

cmd/install/assets/hypershift_operator.go
cmd/version/version.go
hypershift-operator/controllers/supportedversion/reconciler.go
hypershift-operator/controllers/supportedversion/reconciler_test.go
product-cli/main.go

Previously, both hcp and hypershift CLIs would only report their client versions, which was misleading to some users, as the real determination for what versions of OCP are possible to deploy relies on both the client and the server together.
```
$ ./bin/hcp version
Client Version: openshift/hypershift: 0a16c7cad4d056f4cda9a393cfc036e1ceb56d60. Latest supported OCP: 4.16.0
Server Version: openshift/hypershift: 6bb55dffe1bbf25c1086fa4398c8c97b083b57bb. Latest supported OCP: 4.16.0
Server Supports OCP Versions: 4.16, 4.15, 4.14, 4.13
```
/cc @davidvossel

OCPBUGS-32186: cmd: report server version, supported OCP

---

test/e2e/util/hypershift_framework.go

When we fail to bring up the hosted cluster, there's no reason to try to validate anything.

NO-JIRA: test/e2e: don't validate metrics after failure

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
support/azureutil/azureutil.go

Adds validation to the HostedCluster controller to ensure the VNET resource group location, the network security resource group location, and the managed resource group location match.
Fixes [HOSTEDCP-1564](https://issues.redhat.com/browse/HOSTEDCP-1564)
**Checklist**

HOSTEDCP-1564: Ensure VNET, NSG, & Managed RG locations match

---

support/config/deployment.go

A bug fix (#3382) went in earlier this year that corrected an issue where the kubevirt cloud controller manager (kccm) was not having the deployment config accurately applied. 
This resulted in some deployments having the `replace` update strategy instead of `RollingUpdate` update strategy. 
When we update OCP from one of the older versions which deployed kccm with `replace` strategy, the update fails because we attempt to set `RollingUpdate` update strategy parameters when the update strategy is still `replace`.
To fix this, when we set the inplace update parameters, we need to ensure that the upstate strategy type is set to `RollingUpdate` as well.

OCPBUGS-33724: Fixes update issue with KubeVirt platform

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator_test.go

Adds `root-ca` to the `resourceNames` in the `cluster-network-operator` role to provide the access required.
https://issues.redhat.com/browse/OCPBUGS-34699

OCPBUGS-34699: Allow access to root-ca configmap in cluster-network-operator role

---

hypershift-operator/controllers/nodepool/manifests.go
hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/nodepool/nodepool_controller_test.go
hypershift-operator/controllers/scheduler/autoscaler_test.go

When we change the config for a NodePool or the way in which we hash the values, we leak token and user data secrets. However, since these secrets are annotated with the NodePool they were created for, it's simple to check that the Secret still matches what we expect and clean it up otherwise.

OCPBUGS-32467: nodepool_controller: add a reconciler for cleanup

---

test/e2e/nodepool_kv_advanced_multinet_test.go
test/e2e/util/client.go
test/e2e/util/pod_exec.go
test/e2e/util/util.go

test/e2e: constrain actions to context, timeout
Asynchronous actions that serve to make test assertions, etc, must be
constrained by the test context and/or a timeout - otherwise, even tests
that get interrupted will hang forever on these cases.
---
test/e2e: explicitly constrain pod streams
---

HOSTEDCP-1709: test/e2e: constrain actions to context, timeout

---

cmd/install/assets/hypershift_operator.go
cmd/install/install.go
hack/app-sre/saas_template.yaml

This PR adds a `PodMonitor` for `external-dns`, enabling SRE to better observe issues with dns creation that could block cluster installations.
Fixes #[HOSTEDCP-1689](https://issues.redhat.com//browse/HOSTEDCP-1689)
**Checklist**

HOSTEDCP-1689: add PodMonitor for external-dns

---

api/hypershift/v1beta1/hostedcluster_types.go
control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

Adds annotation to support configuring kube-apiserver log verbosity to a value higher than default of 2. 
Fixes # https://issues.redhat.com/browse/OCPBUGS-32763
**Checklist**

HOSTEDCP-1553: Add annotation to customize log verbosity of kube-apiserver

---

hack/ci-test-e2e-azure.sh
hack/ci-test-e2e.sh

The top-level `go test` timeout does nothing beneficial for us - we need to be well-formed in the face of SIGTERM from the test platform anyway, and we need to time out within our tests, not from the top-level, as this will give us sensible test failure output (e.g. a specific assertion failed) versus the current panic output which makes it impossible to generate jUnit.

HOSTEDCP-1709: hack/test: remove timeouts

---

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcileDeployment.yaml

Cherry pick of #4001 on release-4.15.
#4001: remove liveness and readiness probes that use the metrics
```release-note
```

[release-4.15] HOSTEDCP-1708: remove liveness and readiness probes that use the metrics

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
support/awsutil/sg.go

Previously, these rules were generated off of the containing VPC's main CIDR range. However AWS VPCs can have multiple, distinct CIDR ranges, and the main CIDR range may not be the same as the machine CIDR, where the worker nodes are. This results in security group rules being generated that do not allow the worker nodes to communicate with the hosted control plane via the PrivateLink VPC Endpoint.
Ref: https://aws.amazon.com/about-aws/whats-new/2017/08/amazon-virtual-private-cloud-vpc-now-allows-customers-to-expand-their-existing-vpcs/
[OCPBUGS-34274](https://issues.redhat.com/browse/OCPBUGS-34274)
**Checklist**

OCPBUGS-34274: Generate default worker security group rules based on machineCIDR

---

test/e2e/util/fixture.go

Initialize infra id for e2e-azure tests
Fixes [HOSTEDCP-1712](https://issues.redhat.com/browse/HOSTEDCP-1712)
**Checklist**

HOSTEDCP-1712: Initialize infra id for e2e-azure tests

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Preserve_existing_resources.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Private_apiserver_connectivity__proxy_apiserver_address_is_unset.yaml

openshift-sdn is gone in 4.17. There are still a bunch of references to it that need to be cleaned up, but for now, at least stop trying to resolve the image, since that would cause errors even in clusters that aren't trying to use openshift-sdn.
I am not sure that this is correct... it seems like maybe a given version of hypershift supports multiple target versions of openshift? In which case it would need to be able to refer to the 4.16 and earlier sdn images, but not the 4.17 and later sdn images?
Related to SDN-4896; there was no epic for hypershift because I didn't realize …

NO-JIRA: Delete references to the openshift-sdn image in CNO

---

hack/ci-test-e2e.sh

HOSTEDCP-1446: hack: make the e2e script generic

---

control-plane-operator/controllers/hostedcontrolplane/cvo/params.go
control-plane-operator/main.go

- allows CVO image to use registry overrides
Fixes #
**Checklist**

OCPBUGS-35205: Add hypershift-cluster-version-operator image to release providers

---

test/e2e/nodepool_test.go

CI do not have enough resources to run the kubevirt advanced multinet test, this change skip that test if CI is detected.

kubevirt, e2e: Skip advanced multinet for CI

---

docs/content/how-to/disconnected/idms-icsp-for-management-clusters.md
docs/content/how-to/disconnected/known-issues.md

On the OCP Standalone product documentation, we explicitly says how to imageContentSources should be configured for IPI deployments, I'm following the same approach. Once you perform the oc-mirror stage, the output file with the ImageContentSources, should be pasted as IDMS/ICSP into the Management cluster, making possible to perform a disconnected deployment and explicitly matching the Metadata and Images OCP container images with the mirrored ones in the private registry
Fixes #[OCPBUGS-33951](https://issues.redhat.com/browse/OCPBUGS-33951)

OCPBUGS-33951: Documentation for disconnected MGMT Cluster

---

api/hypershift/v1beta1/hostedcluster_types.go
control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

Cherry pick of #4026 on release-4.16.
#4026: rebase + merge conflicts
```release-note
```

[release-4.16] HOSTEDCP-1715: Kubernetes API Server Log Verbosity Annotation cherry pick to 4.16

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Preserve_existing_resources.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Private_apiserver_connectivity__proxy_apiserver_address_is_unset.yaml
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go

Previously the condition was reconciled immediately before accessing any image in the playload. which means the condition will always be `True`
Fixes #
**Checklist**

OCPBUGS-34807: Fixed ValidReleaseInfo condition

---

control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcileDeployment.yaml

Add the missing OPERATOR_IMAGE_VERSION required by the new addition of featuregate in the Image-registry operator
In some cases the image registry operator starts (and crashes) before
the CVO has given its service account proper rbac. This commit adds a
wait for access to the infrastructure resource before allowing the
operator to start.
Fixes #OCPBUGS-34678
**Checklist**

IR-471:registry operator: Add missing env var, wait for rbac

---

api/hypershift/v1alpha1/nodepool_types.go
api/hypershift/v1alpha1/zz_generated.deepcopy.go
api/hypershift/v1beta1/nodepool_types.go
api/hypershift/v1beta1/zz_generated.deepcopy.go
client/applyconfiguration/hypershift/v1alpha1/nodepoolspec.go
client/applyconfiguration/hypershift/v1beta1/nodepoolspec.go
cmd/cluster/cluster.go
cmd/cluster/core/create.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
docs/content/how-to/agent/create-heterogeneous-nodepools.md
docs/content/how-to/automated-machine-management/configure-machines.md
docs/content/how-to/automated-machine-management/nodepool-lifecycle.md
docs/content/how-to/aws/create-aws-hosted-cluster-arm-workers.md
docs/content/labs/Dual/hostedcluster/nodepool.md
docs/content/labs/IPv4/hostedcluster/nodepool.md
docs/content/labs/IPv6/hostedcluster/nodepool.md
docs/content/reference/api.md
examples/fixtures/example.go
hack/app-sre/saas_template.yaml
hypershift-operator/controllers/nodepool/inplace.go
hypershift-operator/controllers/nodepool/nodepool_controller.go
product-cli/cmd/cluster/cluster.go

Currently, volume detachments unhandled by CAPI block the deletion of machines. Prominent examples are daemonset pods with an attached volume ([see this issue](https://github.com/kubernetes-sigs/cluster-api/issues/6158)) as well as unresponsive nodes with pods attached.
This PR allows passing the NodeVolumeDetachTimeout through NodePools to created CAPI machines, which will allow us to skip volume detachment if it doesn't happen on the CAPI side. 
Enables us to provide short term fixes for the following OCPBUGs by specifying the timeout in NodePools we create:
- https://issues.redhat.com/browse/OCPBUGS-34650 until https://github.com/kubernetes-sigs/cluster-api/issues/6158 is fixed
- https://issues.redhat.com/browse/OCPBUGS-29698 until …

OCPBUGS-34650: Allow specifying the volume detach timeout for machines via NodePools

---

hack/ci-test-e2e.sh

[release-4.16] NO-JIRA: hack: make the e2e script generic

---

Makefile
cmd/cluster/aws/destroy.go
cmd/infra/aws/delegating_client.go
cmd/infra/aws/delegatingclientgenerator/main.go
cmd/infra/aws/destroy.go
cmd/infra/aws/iam.go
cmd/infra/aws/iam_policies.go

cmd/infra/aws/iam: refactor static data
The policies in this file are statically associated with the service
account names and the user agents, and these associations are stable.
This refactor exposes the association to a) enforce the connections and
b) allow other consumers to understand it.
---
cmd/infra/aws: generate a delegating AWS client
When we run a cleanup task using the myriad credentials that cluster
components have, we need to delegate each call to an AWS service API to
the correct credential that has permissions to use it. We can generate
the delegating client directly from our policy documents to allow us to
keep consumer code from having to know that there are many different
clients operating under the hood in this mode. …

HOSTEDCP-1402: cmd/infra/aws/destroy: allow using component credentials

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
control-plane-operator/main.go
support/releaseinfo/registry_mirror_provider.go

manual-backport of https://github.com/openshift/hypershift/pull/3952 and https://github.com/openshift/hypershift/pull/4114
Fixes #
**Checklist**

[release-4.15] OCPBUGS-33627: Restrict image registry overrides to control plane components

---

hack/ci-test-e2e.sh

Cherry-pick of https://github.com/openshift/hypershift/pull/4198

[release-4.15] NO-JIRA: hack: make the e2e script generic

---

api/hypershift/v1beta1/hostedcluster_types.go
hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go
hypershift-operator/controllers/nodepool/nodepool_controller.go

The descheduler has a policy that knows how to redistribute pods based on their TopologySpreadConstraints. by transitioning VMs from pod anti-affinity to use topo spread constraints, we can integrate better with descheduler logic that will accurately re-distribute VMs after a mgmt/infra cluster is updated.

CNV-42626: Transition kubevirt vms to use topology spread constraints

---

cmd/cluster/aws/testdata/zz_fixture_TestCreateCluster_default_creation_flags_for_cesar.yaml
cmd/cluster/aws/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/core/create.go

cluster/core: fix nodepool naming
The dash was accidentally omitted.
---
Based on https://github.com/openshift/hypershift/pull/4212

OCPBUGS-35513: cluster/core: fix nodepool naming

---

test/e2e/nodepool_test.go

This reverts commit 1927260efe20f338f421fd74b0dc7152ce978454.
Fixes #
**Checklist**

NO-JIRA: Revert "kubevirt, e2e: Skip advanced multinet for CI"

---

control-plane-operator/controllers/hostedcontrolplane/kas/config.go

PersistentVolumeLabel admission plugin needs a valid cloud config. kube-apiserver does not get it in HyperShift, and thus it rejects valid Azure Disk PVs.
The admission plugin was deprecated upstream a long time ago, it was removed from Kubernetes 1.31 (OCP 4.18) and it cannot work without a cloud provider in kube-apiserver anyway.
It's also being disabled in standalone OCP, https://github.com/openshift/cluster-kube-apiserver-operator/pull/1693
Fixes OCPBUGS-34544
Related to OCPBUGS-31371
**Checklist**
cc @openshift/storage

OCPBUGS-34544: Disable PersistentVolumeLabel admission plugin

---

hack/ci-test-e2e.sh

Cherry-pick of https://github.com/openshift/hypershift/pull/4201

[release-4.13] NO-JIRA: hack: make the e2e script generic

---

hack/ci-test-e2e.sh

Cherry-pick of https://github.com/openshift/hypershift/pull/4199

[release-4.14] NO-JIRA: hack: make the e2e script generic

---

test/e2e/nodepool_kv_cache_image_test.go
test/e2e/nodepool_kv_jsonpatch_test.go
test/e2e/util/eventually.go
test/integration/control_plane_pki_operator.go
test/integration/framework/hosted-cluster.go
test/integration/hosted_cluster_sizing_test.go
test/integration/placeholder_test.go

test/e2e: add a harness for asynchronous assertions
We have a lot of functional requirements on asynchronus assertions on
top of the need that they assert correctly. Closing over these
requiredments in a helper seems prudent given how common they are in the
test codebase.
---

HOSTEDCP-1709: test/e2e: add a harness for asynchronous assertions

---

control-plane-operator/controllers/hostedcontrolplane/kas/kms/ibmcloud.go
control-plane-operator/controllers/hostedcontrolplane/kas/params.go

Remove KMS V1 provider support for IBM Cloud
Fixes # https://issues.redhat.com/projects/OCPBUGS/issues/OCPBUGS-35450
**Checklist**

OCPBUGS-35450: Remove KMS V1 provider support for IBM Cloud

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

manual cherry-pick of https://github.com/openshift/hypershift/pull/3900

[release-4.15] OCPBUGS-32404: Fix failure to create a second hostedcluster in the same namespace

---

cmd/cluster/core/dump.go
test/e2e/util/dump/copy-machine-journals.sh

Removes logging like
```
Attempt #2: ssh -F /tmp/tmp.rws1F4Y6V1 -n machine sudo journalctl > /tmp/journal.log && gzip -f /tmp/journal.log
Warning: Permanently added '3.89.9.23' (ED25519) to the list of known hosts.
Warning: Permanently added '10.0.136.42' (ED25519) to the list of known hosts.
```
and
```
logger.go:146: 2024-06-18T12:36:13.241Z	INFO	oc adm inspect returned an error	{"args": ["adm", "inspect", "--dest-dir", "/logs/artifacts/TestCreateClusterCustomConfig_Teardown/hostedcluster-example-d8np5", "--kubeconfig", "/tmp/kubeconfig-2522436477", "daemonset.apps,deployment.apps,replicaset.apps,statefulset.apps,job.batch,configmap,endpoints,event,persistentvolumeclaim,pod,replicationcontroller,service,customresourcedefinition.apiextensions.k8s.io,controllerrevision.apps,clusteroperator …
```

NO-JIRA: test/e2e: reduce logging for ssh and oc adm inspect

---

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/config.go
control-plane-operator/controllers/hostedcontrolplane/kas/config.go
test/e2e/create_cluster_test.go

Align HyperShift with OpenShift's expectation that PSA is going back to enforcing privileged by default instead of restricted.
Fixes #
- https://issues.redhat.com/browse/OCPBUGS-35252
**Checklist**

OCPBUGS-35369: OCPBUGS-35252: Enforce Privileged Instead of Restricted PSA in 4.16

---

cmd/cluster/powervs/create.go
cmd/infra/powervs/create.go
go.mod
go.sum
vendor/github.com/ppc64le-cloud/powervs-utils/README.md
vendor/github.com/ppc64le-cloud/powervs-utils/region.go
vendor/modules.txt

Currently transit gateway is using global routing by default. With this change, user has to provide flag to enable global routing and default value is set as local routing(if powervs and VPC regions are same).
Fixes #[HOSTEDCP-1729](https://issues.redhat.com/browse/HOSTEDCP-1729)
**Checklist**

HOSTEDCP-1729: Support for on-demand global routing when creating transit gateway

---

api/hypershift/v1alpha1/nodepool_types.go
api/hypershift/v1beta1/nodepool_types.go
cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
cmd/nodepool/kubevirt/create.go
cmd/nodepool/kubevirt/create_test.go
hack/app-sre/saas_template.yaml

After the performance issue [RHEL-1334](https://issues.redhat.com/browse/RHEL-1334) had solved, multiqueue should be enabled.
Fixes #[CNV-30445](https://issues.redhat.com//browse/CNV-30445)

CNV-30445: KubeVirt: Enable multiqueue by default

---

test/e2e/nodepool_kv_cache_image_test.go
test/e2e/nodepool_kv_jsonpatch_test.go
test/e2e/util/eventually.go
test/integration/control_plane_pki_operator.go
test/integration/hosted_cluster_sizing_test.go
test/integration/placeholder_test.go

test/e2e: add post-summary, verbosity toggle to eventually
We now summarize *only* the failing predicates when we fail to achieve
our target. Also, the mid-stream summarization is toggled with an
environment variable, which we can default to verbose but turn down in
CI.
---
test/e2e: round durations for brevity
---

HOSTEDCP-1709: test/e2e: updates to the eventually construct

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go

xref https://issues.redhat.com//browse/OCPBUGS-25758
https://github.com/openshift/hypershift/pull/4033 introduced cleanup for the `ovnkube-sbdb Route, however, it did not check that the management cluster has the Route CRD present before attempting the delete leading to a regression on non-OCP mgmt clusters.

OCPBUGS-35874: check mgmt cluster for route capability before DeleteIfNeeded for ovn sbdb route

---

cmd/infra/aws/ec2_sg.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
support/awsutil/sg.go

This is a manual cherry-pick of #4174
The automated one #4236 has test failures that are resolved in this PR via the changes in `cmd/infra/aws/ec2_sg.go` because the function signature of `DefaultWorkerSGIngressRules` has changed.
OCPBUGS-35714

[release-4.15] OCPBUGS-35714: Generate default worker security group rules based on machineCIDR

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/kas/params.go
hypershift-operator/controllers/nodepool/haproxy.go
hypershift-operator/controllers/nodepool/haproxy_test.go
hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_private_cluster_uses_.local_address_and_LB_kas.yaml
hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_public_and_private_cluster_uses_.local_address_and_LB_kas.yaml
support/util/expose.go
support/util/expose_test.go
support/util/networking.go
test/e2e/create_cluster_test.go
test/e2e/util/util.go

Failed to provision a private HC on AWS, following the official docs https://hypershift-docs.netlify.app/how-to/aws/deploy-aws-private-clusters/. VMs are provisioned but unable to join the HC as Nodes. 
This is due to the fact that the kubelet on each HC VM tried to use api.fxie-hcp-2.hypershift.local:443 (instead of 6443 for KAS exposed via LB) to communicate with the KAS:
```Bash
...
Apr 02 19:37:54 ip-10-0-142-1 kubenswrapper[2032]: E0402 19:37:54.769191    2032 kubelet_node_status.go:99] "Unable to register node with API server" err="Post \"https://api.fxie-hcp-2.hypershift.local:443/api/v1/nodes\": dial tcp 10.0.138.240:443: i/o timeout" node="ip-10-0-142-1.us-east-2.compute.internal"
...
```
Besides, the CNO also passes the wrong KAS port to Network components on the HC. 
Same for …

OCPBUGS-31840: Make guest cluster components use the correct KAS port

---

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go

When an external infra cluster topology is being used with the kubevirt provider, In which the guest nodes are being created on a different cluster than the mgmt cluster, the `kubevirt-csi-driver` container should be provided with an additional argument of `--infra-cluster-kubeconfig`, which should be mount on the container from the `kubevirt-infra-credentials` secret in the HCP namespace. Also, in the 'driver-config' ConfigMap, the key of `infraClusterNamespace` should be set to be the namespace of the VMs on the external infra cluster, not the HCP namespace.
Fixes # …

OCPBUGS-36188: kubevirt-csi-driver: Pass infra kubeconfig in case of external infra

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/kas/params.go
hypershift-operator/controllers/nodepool/haproxy.go
hypershift-operator/controllers/nodepool/haproxy_test.go
hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_private_cluster_uses_.local_address_and_LB_kas.yaml
hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_public_and_private_cluster_uses_.local_address_and_LB_kas.yaml
support/util/expose.go
support/util/expose_test.go
support/util/networking.go
test/e2e/create_cluster_test.go
test/e2e/util/util.go

Manually cherry-pick https://github.com/openshift/hypershift/pull/3849 to release-4.16.

[release-4.16] OCPBUGS-36220: Make guest cluster components use the correct KAS port

---

hypershift-operator/controllers/hostedcluster/metrics/metrics.go
hypershift-operator/controllers/hostedcluster/metrics/metrics_test.go

This PR adds two new metrics for the HostedCluster. `hypershift_cluster_proxy_ca_valid` and `hypershift_cluster_proxy_ca_expiry_timestamp`.
These metrics are about getting closer to feature parity with OSD.
These two metrics determine if the CA bundle configured for a hostedcluster is valid and when the earliest certificate contained will expire:
- The configmap must exist.
- It contains certificates.
- (For being valid) The certificates are not expired.
Fixes #[HOSTEDCP-1342](https://issues.redhat.com//browse/HOSTEDCP-1342)
**Checklist**

HOSTEDCP-1342: Add new metrics to check CA bundle validity and expiry [OSD-15414]

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
control-plane-operator/main.go
support/releaseinfo/registry_mirror_provider.go

cherry-pick of https://github.com/openshift/hypershift/pull/4131
Fixes #
**Checklist**

[release-4.14] OCPBUGS-35549: Restrict image registry overrides to control plane component

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/manifests/oauth.go
control-plane-operator/controllers/hostedcontrolplane/oauth/assets.go
control-plane-operator/controllers/hostedcontrolplane/oauth/auditcfg.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment_test.go
control-plane-operator/controllers/hostedcontrolplane/oauth/files/audit-policy.yaml
control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
control-plane-operator/controllers/hostedcontrolplane/oauth/testdata/zz_fixture_TestReconcileOauthDeploymentNoChanges.yaml

It enables audit logs for `oauth-openshift`.
Currently, hypershift only supports audit logs for `kube-apiserver`, `openshift-apiserver`, and `openshift-oauth-apiserver`. However, `oauth-openshift` also supports audit logs in standalone OCP.
Fixes # OCPBUGS-33060
**Checklist**
- [ *] This change includes unit tests.

OCPBUGS-33060: enable audit log for oauth-openshift

---

cmd/cluster/kubevirt/create.go

The infra-volumesnapshot-class-mapping was only part of the developer binding but should have been a core binding so it ends up in hcp as well as hypershift.
Fixes https://issues.redhat.com/browse/OCPBUGS-35521
**Checklist**

OCPBUGS-35521: Move infra-volumesnapshot-class-mapping to core binding

---

hypershift-operator/controllers/nodepool/nodepool_controller.go

The proxy configuration from the HostedCluster resource is not currently used when generating user data (an empty proxy config is used). This commit invokes the reconcile on the proxy config so that it's filled in with the values from the HostedCluster.
Fixes #[OCPBUGS-36230](https://issues.redhat.com/browse/OCPBUGS-36230)
**Checklist**

OCPBUGS-36230: Use a reconciled proxy config when generating nodepool userdata

---

cmd/cluster/aws/create.go
cmd/cluster/aws/create_test.go
cmd/cluster/aws/testdata/zz_fixture_TestCreateCluster_default_creation_flags_for_cesar.yaml
cmd/cluster/aws/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml

Enable MultiArch flag by default
Fixes [HOSTEDCP-1778](https://issues.redhat.com//browse/HOSTEDCP-1778)
**Checklist**

HOSTEDCP-1778: Enable MultiArch flag by default

---

test/e2e/nodepool_arm64_create_test.go
test/e2e/nodepool_test.go

**What this PR does / why we need it**: skips multiarch test before HC creation. Now we skip the testcase which is called after setting up the hc for it. With this change we will avoid creating an unnecessary HC during our e2e.
Fixes #
**Checklist**

NO-JIRA: skip multiarch test before HC creation

---

test/e2e/util/util.go

In case there are no worker nodes in the HostedCluster, the condition ValidKubeVirtInfraNetworkMTU is missing since the MTU prober hasn't been run, so no MTU is being reported by the Cluster Network Operator. In such case, we're removing that condition from the expectedConditions map.
Fixes #
**Checklist**

NO-JIRA: e2e tests: skip checking ValidKubeVirtInfraNetworkMTU if no workers

---

cmd/cluster/core/dump.go
cmd/cluster/core/dump_test.go

When the MC is not OpenShift, some `oc adm inspect` commands invoked by hypershift dump error out as the server does not recognize OpenShift resources like ImageStream. As a result, many GVKs are missing in the dump. 
Only dump registered OpenShift GVKs in this case.

OCPBUGS-36481: Fix Hypershift dump for non-OpenShift Management Clusters

---

docs/Dockerfile
docs/Makefile
docs/mkdocs.yml
docs/requirements.txt

This PR contains several updates:
This PR contains several updates:
- The main one addresses a security flaw identified by SNYK, as mentioned in the header. To address this, all Mkdocs dependencies have been updated, and ultimately, urllib3 is used in the mkdocs-mermaid2-plugin.
- The Dockerfile has been updated to include the latest version of Mkdocs Material.
- The mkdocs.yml file has been updated to ignore non-relevant messages.
- The Makefile has been updated to include a push target for sending the created container image to the destination repository.
- [HOSTEDCP-1810](https://issues.redhat.com/browse/HOSTEDCP-1810)
- [HOSTEDCP-1809](https://issues.redhat.com/browse/HOSTEDCP-1809)

HOSTEDCP-1808: Update Mkdocs, dependencies and dockerfile

---

hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go

This updates the capk image used for testing in main to 4.17

NO-JIRA: Update ci image of capk to 4.17

---

test/e2e/nodepool_kv_jsonpatch_test.go
test/e2e/nodepool_kv_nodeselector_test.go
test/e2e/nodepool_test.go

the following change broke the kubevirt e2e test suite:
https://github.com/openshift/hypershift/commit/6f6a78b7ff2932087b47609c5a16436bad5aeb1c#diff-fad16312cbcaea633c33fbabe940966d9d936a14dd67a239d1b6c6250fc8679aR99 as it is trying to access an empty slice by index.
This fix is required on order to fix the [4.17-periodics-e2e-kubevirt-aws-ovn](https://prow.ci.openshift.org/?job=periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-kubevirt-aws-ovn) periodic job
Fixes # [4.17-periodics-e2e-kubevirt-aws-ovn](https://prow.ci.openshift.org/?job=periodic-ci-openshift-hypershift- …

NO-JIRA: KubeVirtJsonPatchTest: fix vmi slice assignment

---

hypershift-operator/controllers/nodepool/manifests.go
hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/nodepool/nodepool_controller_test.go
support/util/route.go
support/util/route_test.go
test/e2e/nodepool_nto_performanceprofile_test.go

When a `PerformanceProfile` should be mirrored into the HCP namespace, its given name which compose from a constant (perfprof) + the node pool name.
In case there are multiple `PerformanceProfiles`, one per hosted cluster, the approach mentioned above makes it hard to understand which `PreformanceProfile` in the clusters namespace is associate with each hostedcluster.
It requires to examine the node pool \`spec.tuningConfig\` to figure out the relation between user profile and the mirrored one.
This commit suggest to embed the configMap (that encapsulates the performanceProfile) name in the mirrored profile, to make the relation clear and observable on first sight.
Fixes # …

CNF-12951:hypershift:performanceprofile: associate profile name with user input

---

hypershift-operator/controllers/nodepool/azure.go

Only set the Azure VM identity if a user assigned identity was provided.
Fixes [OCPBUGS-36681](https://issues.redhat.com/browse/OCPBUGS-36681)
**Checklist**

OCPBUGS-36681: Set Azure VM identity if user assigned identity set

---

.tekton/hypershift-operator-main-pull-request.yaml
.tekton/hypershift-operator-main-push.yaml

The upcoming OpenShift Pipelines which will be deployed shortly has stricter validations on Pipelines and Task manifests. Clamav would fail the new validations. This commit should make us ready.
Fixes #[HOSTEDCP-1818](https://issues.redhat.com//browse/HOSTEDCP-1818)
**Checklist**

HOSTEDCP-1818:fix(build): update to the fixed clamav image

---

hypershift-operator/init.go
hypershift-operator/init_test.go

Once you add more than one certificate to the ConfigMap referenced in the image.config.openshift.io spec field, the getImageRegistryCABundle processes the certificates properly. However, if you add these through the UI console, the user might not include the newline character, which results in overlapping certificates. This PR ensures a newline is always added after each certificate processed.
Fixes #[OCPBUGS-33934](https://issues.redhat.com/browse/OCPBUGS-33934)

OCPBUGS-33934: Add newline after TLS certs referenced by image.config

---

support/konnectivityproxy/dialer.go
support/konnectivityproxy/resolver.go

The new HTTPS konnectivity proxy requires that DNS names be resolved before generating a proper CONNECT string for the Konnectivity server. However the dialer was returning a nil IP if it didn't think it needed to resolve a name through the hosted cluster. This fix is to always resolve a name if using the HTTPS konnectivity proxy.
Fixes #[OCPBUGS-34865](https://issues.redhat.com/browse/OCPBUGS-34865)
**Checklist**

OCPBUGS-34865: Fix name resolution for HTTPS konnectivity proxy

---

api/hypershift/v1beta1/hostedcluster_types.go
cmd/install/assets/hypershift_operator.go
cmd/install/install.go

There's a single valid known use case for azure atm. Let's default to it.
Also this drops rosa variable since there's no usage nor valid semantic for it atm.
**Checklist**

NO-JIRA: Default azure to run as managed-service=aro

---

api/hypershift/v1beta1/hostedcluster_types.go
control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

Cherry pick of #4026 on release-4.15.
#4026: rebase + merge conflicts
Parent issue https://issues.redhat.com/browse/HOSTEDCP-1553
4.15 cherry pick issue https://issues.redhat.com/browse/HOSTEDCP-1714
4.16 cherry pick issue https://issues.redhat.com/browse/HOSTEDCP-1715
```release-note
```

[release-4.15] HOSTEDCP-1714: Kubernetes API Server Log Verbosity Annotation cherry pick to 4.15

---

docs/content/how-to/kubevirt/configuring-storage.md

Trivial typo fixes related to the table and two of the internal reference links.

NO-JIRA: trivial typo fixes to configuring-storage.md

---

control-plane-operator/controllers/hostedcontrolplane/oapi/deployment_test.go
test/e2e/util/util.go

Fixes #[OCPBUGS-35905](https://issues.redhat.com/browse/OCPBUGS-35905)
- Added E2E test to validate the proper presence of the TLS certificates into openshift-apiserver

OCPBUGS-35905: E2E test to verify openshift-apiserver TLS certificates

---

hypershift-operator/controllers/nodepool/nodepool_controller.go

Duplicated the MachineHealthCheck timeout in both Agent and None platforms to better align with real-world scenarios
Fixes #[OCPBUGS-35899](https://issues.redhat.com/browse/OCPBUGS-35899)

OCPBUGS-35899: Doubled machineHealthCheck timeout on Agent and None

---

hypershift-operator/controllers/nodepool/nodepool_controller.go

Fixing the resource used to evaluate the platform to set the MachineHealthCheckTimeout
Fixes #[OCPBUGS-35899](https://issues.redhat.com/browse/OCPBUGS-35899)

OCPBUGS-34816: Fix the resource from is checking the MHC platform

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
support/certs/tls.go

Now via annotation the self-generated certificates validity and rotation could be customised. This will help to test the certificates regeneration
Fixes #[HOSTEDCP-1779](https://issues.redhat.com/browse/HOSTEDCP-1779)
- https://issues.redhat.com/browse/HOSTEDCP-1795
- https://issues.redhat.com/browse/HOSTEDCP-1796
Another more complete approach is implemented here: https://github.com/openshift/hypershift/pull/4318 for [HOSTEDCP-1795](https://issues.redhat.com/browse/HOSTEDCP-1795)
We decided to go with a much smaller version and not exposed to the API.

HOSTEDCP-1795,HOSTEDCP-1796: Customize the self-generated cert validity and rotation

---

hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/nodepool/nodepool_controller_test.go
vendor/k8s.io/utils/set/OWNERS
vendor/k8s.io/utils/set/ordered.go
vendor/k8s.io/utils/set/set.go
vendor/k8s.io/utils/set/set_go_1.20.go
vendor/k8s.io/utils/set/set_go_1.21.go
vendor/modules.txt

NTO is one of core OCP operator and it's running as a pod in the HCP namespace.
The operartor requires containerruntime (if exists)
in order to perform certain tuning decisions.
Here, we support mirroring of this object into the HCP namespace,
so the operator will be able to access and get the information it's
needed.
Fixes # 
[CNF-11845](https://issues.redhat.com/browse/CNF-11845)
**Checklist**

CNF-11845: nodepoolcontroller: mirror containerruntimeconfig to HCP NS

---

control-plane-operator/controllers/hostedcontrolplane/kas/kms/ibmcloud.go

Separate ibmcloud kms encryption configuration types to allow enablement of KMS
Fixes # https://issues.redhat.com/browse/OCPBUGS-37102
**Checklist**

OCPBUGS-37102: Separate ibmcloud kms encryption configuration types

---

ignition-server/controllers/local_ignitionprovider.go

Dynamically use rhel9 MCO binaries for rhel8 based MCO images
xref https://github.com/openshift/machine-config-operator/pull/4476

OCPBUGS-37222: extract rhel9 MCO binaries for rhel8 based MCO images

---

api/hypershift/v1beta1/nodepool_types.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
docs/content/reference/api.md
hack/app-sre/saas_template.yaml
hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/nodepool/nodepool_controller_test.go

This PR enables Hypershift NodePool controller to recognize and process multiple MachineConfig yaml documents inside config-maps referenced by NodePool in its spec.config list.
This is required to reduce number of objects in etcd when Hypershift manages many hosted clusters to save space and improve performance.
Fixes # OCPBUGS-30282
**Checklist**

OCPBUGS-30282: Multiple MachineConfigs in one CM

---

api/hypershift/v1beta1/nodepool_types.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
hack/app-sre/saas_template.yaml

**What this PR does / why we need it**: Fixes Nodepool CEL validation to allow neither replicas or autoScaling to be set
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*: 
Fixes # https://issues.redhat.com/browse/OCPBUGS-36897
**Checklist**

OCPBUGS-36897: fix(api): Nodepool CEL validation fix

---

.tekton/hypershift-operator-main-pull-request.yaml
.tekton/hypershift-operator-main-push.yaml

This PR:
* Cherry-picks https://github.com/openshift/hypershift/pull/4400
* Updates the buildah config in the tekton files per https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md 
Fixes [HOSTEDCP-1838](https://issues.redhat.com/browse/HOSTEDCP-1838)
**Checklist**

HOSTEDCP-1838: Migrate buildah config in tekton files for migration from 0.1 to 0.2

---

cmd/cluster/cluster.go
cmd/cluster/openstack/create.go
cmd/cluster/openstack/create_test.go
cmd/cluster/openstack/destroy.go
cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_default_creation_flags.yaml
cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
go.mod
hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack.go
product-cli/cmd/cluster/cluster.go
product-cli/cmd/cluster/openstack/create.go
product-cli/cmd/cluster/openstack/destroy.go
test/e2e/e2e_test.go
test/e2e/util/fixture.go
test/e2e/util/hypershift_framework.go

* Basic CLI options for cluster create & destroy. More options
will come with Node pools and in the future with more usecases.
* Set a default Machine Network when creating the cluster with the CLI.
* Add the CLI options to e2e.

OSASINFRA-3538: openstack: cluster CLI

---

api/hypershift/v1alpha1/hostedcluster_types.go
api/hypershift/v1alpha1/nodepool_types.go
api/hypershift/v1beta1/hostedcluster_types.go
api/hypershift/v1beta1/nodepool_types.go
client/applyconfiguration/hypershift/v1alpha1/azurenodepoolplatform.go
client/applyconfiguration/hypershift/v1alpha1/azureplatformspec.go
client/applyconfiguration/hypershift/v1beta1/azurenodepoolplatform.go
client/applyconfiguration/hypershift/v1beta1/azureplatformspec.go
cmd/cluster/azure/create.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
docs/content/reference/api.md
hack/app-sre/saas_template.yaml
hypershift-operator/controllers/nodepool/azure.go

Moves `MachineIdentity` from the Azure section in the HostedCluster API to the Azure section in the NodePool API
Fixes [HOSTEDCP-1813](https://issues.redhat.com/browse/HOSTEDCP-1813)
**Checklist**

HOSTEDCP-1813: Moves MachineIdentity from the HostedCluster API to the NodePool API

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

The issue happens because the ImageContentSource field from the HostedCluster object in not in sync with the HostedControlPlane ImageContentSource field.
Fixes #[OCPBUGS-34820](https://issues.redhat.com/browse/OCPBUGS-34820)

OCPBUGS-34820: Keep in sync the HC and HCP ICS field

---

cmd/cluster/agent/create_test.go
cmd/cluster/aws/create_test.go
cmd/cluster/azure/create_test.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/core/create.go
cmd/cluster/kubevirt/create_test.go
cmd/cluster/none/create_test.go
cmd/cluster/openstack/create_test.go
cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_default_creation_flags.yaml
cmd/cluster/powervs/create_test.go

Prevent all secrets from being rendered in manifest by default.
Fixes #
**Checklist**

HOSTEDCP-1791: dont render any secrets in manifest file

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go

This https://github.com/openshift/hypershift/pull/4228 introduced an inconsistency between the endpoint and endpointSlice ports. Resulting in old HCs having hcp.Spec.Networking.APIServer.Port=443 failing to talk to the CP via kubernetes.svc.
This PR fixes that.
Fixes #
**Checklist**

OCPBUGS-37486: Set right endpointSlice port

---

hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go
hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes_test.go

The list of fleet manager labels to use in building the node selector for placeholder pods was not consistent across calls. This resulted in potentially different variations of a given placeholder deployment in every reconcile, resulting in churn of placeholders that would prevent certain hosted clusters from getting scheduled. This commit makes the list of taken labels consistent across calls to get them by putting them in a set and sorting them.
Fixes #[OCPBUGS-37625](https://issues.redhat.com/browse/OCPBUGS-37625)
**Checklist**

OCPBUGS-37625: DedicatedRequestServing scheduler: make taken labels list consistent

---

.tekton/hypershift-release-mce-27-pull-request.yaml
.tekton/hypershift-release-mce-27-push.yaml

While mce-2.7 tracks main, we need to have the tekton pipeline for the mce-2.7 app in `main`. Otherwise, PR #4407 would break the automatic fast-forwarding. Once the branching happens, we need to remove the two files introduced in this PR from the `main` branch.
While mce-2.7 tracks main, we need to have the tekton pipeline for the mce-2.7 app in `main`. Otherwise, PR #4407 would break the automatic fast-forwarding. Once the branching happens, we need to remove the two files introduced in this PR from the `main` branch.
Fixes OCPBUGS-37698
**Checklist**

OCPBUGS-37698: mce-2.7 enablement for main

---

test/e2e/nodepool_test.go
test/e2e/util/util.go

Rehearsal failure trying to use `main` HO with 4.16 release
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/52306/rehearse-52306-periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn/1818008709683482624
```
nodepool_test.go:289: correct condition: wanted ValidReleaseImage=True, got ValidReleaseImage=True: AsExpected(Using release image: registry.build01.ci.openshift.org/ci-op-0vx638ni/release@sha256:6f727aeaa9a820058419e293027d0d1c006d5776b32dbebd23d9180cc4b7e245)
nodepool_test.go:298: Failed to validate NodePool conditions in 0s: unknown condition ValidArchPlatform
--- FAIL: TestNodePool/Main/TestNodepoolMachineconfigGetsRolledout (1380.22s)
```
HO in `main` adds a condition that is not in the set of known conditions in 4.16 …

HOSTEDCP-1569: test: e2e: skip unknown conditions instead of erroring

---

docs/content/how-to/openstack/create-openstack-cluster.md

Adds content for Ingress on the OpenStack platform, with MetalLB.

OSASINFRA-3550: docs/openstack: adds content for Ingress with MetalLB

---

cmd/cluster/core/create.go
cmd/version/version.go
product-cli/cmd/cluster/aws/create.go

- Default multi-arch flag to true for HCP CLI
- Default release stream to multi-arch HCP CLI
Fixes [HOSTEDCP-1778](https://issues.redhat.com/browse/HOSTEDCP-1778)
**Checklist**

HOSTEDCP-1778: Default multi-arch flag to true and default release stream for HCP CLI

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

Manual cherry-pick from:
- https://github.com/openshift/hypershift/pull/4333
- https://github.com/openshift/hypershift/pull/4412
Fixes #[OCPBUGS-36766](https://issues.redhat.com//browse/OCPBUGS-36766)

OCPBUGS-36766: Delete IDMS in dataplane once HCP ICS field is removed

---

support/certs/tls.go

Fixing a flaky test validating the TLS Certificates. Samples:
- https://prow.ci.openshift.org/pr-history/?org=openshift&repo=hypershift&pr=4447
- https://prow.ci.openshift.org/pr-history/?org=openshift&repo=hypershift&pr=4361
Slack Thread: https://redhat-internal.slack.com/archives/G01QS0P2F6W/p1722350441545099

NO-JIRA: Flaky cert validation test

---

api/hypershift/v1beta1/nodepool_types.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
docs/content/reference/api.md
hack/app-sre/saas_template.yaml
hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/nodepool/nodepool_controller_test.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go

This PR is a manual cherry-pick of  https://github.com/openshift/hypershift/pull/3695 into branch `release-4.16` because automatic `/cherry-pick` failed due to a code conflict.

[release-4.16] OCPBUGS-30282: Multiple MachineConfigs in one CM

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go

VolumeSnapshots are similar to PVCs in that they consume persistent cloud resources. If we're going to clean up PVCs, then it seems to make sense to cleanup VolumnSnapshots as well.

NO-JIRA: Ensure VolumeSnapshots are deleted during cloud resource cleanup

---

api/hypershift/v1beta1/hostedcluster_types.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
hack/app-sre/saas_template.yaml
test/e2e/create_cluster_test.go
test/e2e/util/util.go

There's many non supported input/day 2 changes we need to validate on the API for better UX. This is one of them. Any upcoming change needs to include a validation to the introducingwq check
Fixes #
**Checklist**

HOSTEDCP-1669: Make hostedcluster.spec.services immutable for non IBM platforms

---

cmd/cluster/aws/create.go
cmd/infra/aws/create.go

Adds a new flag `--proxy-vpc-endpoint-service-name` to `create {infra|cluster} aws`.  This flag, in combination with `--enable-proxy`, will create a VPC Endpoint to a proxy service provided by the Endpoint Service.  A proxy host can still be created with `--enable-proxy` and no `--proxy-vpc-endpoint-service-name` flag.

HOSTEDCP-1565: add VPC Endpoint Service proxy support

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/4457

[release-4.14] OCPBUGS-37175: Delete IDMS in dataplane once HCP ICS field is removed

---

api/hypershift/v1beta1/hostedcluster_types.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
docs/content/reference/api.md
hack/app-sre/saas_template.yaml
support/assets/readasset.go
test/e2e/assets.go
test/e2e/assets/azure-services-ignition-route-not-hostname.yaml
test/e2e/create_cluster_test.go

This enforce all azure services to be route and have a hostname. This satisfies shared ingress expectation
This enforce all azure services to be route and have a hostname. This satisfies shared ingress expectation
This is the first of a series of PRs to improve API UX validation 
Fixes #
**Checklist**

HOSTEDCP-1669: Add first azure services validation

---

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go

Ingress operator canary checks require access to the internet since they probe the external canary routes. The socks5 proxy sidecar does not provide external access when a user proxy is required. This commit switches to using the konnectivity-https-proxy that does take into account the user's proxy configuration.
Fixes #OCPBUGS-37052
**Checklist**

OCPBUGS-37052: Use konnectivity HTTP proxy for ingress controller

---

control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
support/util/deployment.go
support/util/deployment_test.go

This PR reverts:
- https://github.com/openshift/hypershift/pull/4354
- https://github.com/openshift/hypershift/pull/4419
This is quite destructive and automatic approach, and could have side-effects in clusters already existent.
We are working in another approach which is less destructive, meanwhile we look for the root cause of the issue.

OCPBUGS-37934: Reverting ETCD cluster rebuild

---

cmd/cluster/openstack/create.go
cmd/cluster/openstack/create_test.go
cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_default_creation_flags.yaml
control-plane-operator/controllers/hostedcontrolplane/cloud/openstack/providerconfig.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
docs/content/how-to/openstack/create-openstack-cluster.md
hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack.go
test/e2e/e2e_test.go

When the user provides an external network to hypershift that must be used by CCM to ensure that network is used when creating Floating IPs for the Load Balancers. CCM expects an external Network ID, right now we accept a Name from the user. This commit changes this behavior to consume an ID instead.

OSASINFRA-3554: OpenStack: Use external network ID in favor of Name

---

api/hypershift/v1beta1/hostedcluster_types.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
test/e2e/nodepool_kv_nodeselector_test.go
test/e2e/util/util.go

If the management cluster is Azure and the hosted cluster is created with the kubevirt-provider, the LB port of the kube-apiserver at the HCP can't be 6443 due to azure limitation. In such case, use port 7443 instead.
This is a manual backport of https://github.com/openshift/hypershift/pull/3821
Fixes #
**Checklist**

NO-JIRA: [release-4.15] Kubevirt on Azure: Change KAS LB Port to 7443

---

.tekton/hypershift-release-mce-25-pull-request.yaml
.tekton/hypershift-release-mce-25-push.yaml

Replaces https://github.com/openshift/hypershift/pull/4480:
* cherry picked the commit in https://github.com/openshift/hypershift/pull/4480
* Removed BASE_IMAGES_DIGEST per the Konflux migration instructions - https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md
Fixes #
**Checklist**

NO-JIRA: Update Konflux 4.15 and perform migration

---

control-plane-operator/controllers/hostedcontrolplane/storage/assets/10_deployment-hypershift.yaml
control-plane-operator/controllers/hostedcontrolplane/storage/envreplace.go

This adds the environment variable for the `tools` image, used by some CSI operators to start an init container and create a credentials file.
This requirement was caught here: https://github.com/openshift/csi-operator/pull/248#issuecomment-2268533539
Fixes #
**Checklist**
- IIUC we don't need docs for this.
- IIUC this is covered by the existing unit tests (`envreplacer_test.go`)

OCPBUGS-37488: CSO: add environment variable for tools image

---

hypershift-operator/controllers/nodepool/nodepool_controller.go

Manual Cherrypick of:
- https://github.com/openshift/hypershift/pull/4345
- https://github.com/openshift/hypershift/pull/4365

OCPBUGS-37065: OCPBUGS-35899: Doubled machineHealthCheck timeout on Agent and None

---

api/hypershift/v1beta1/hostedcluster_types.go
client/applyconfiguration/hypershift/v1beta1/openstackplatformspec.go
cmd/cluster/openstack/create.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml
control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/ingress.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
docs/content/how-to/openstack/create-openstack-cluster.md
docs/content/reference/api.md
hack/app-sre/saas_template.yaml
support/openstackutil/ingress.go
support/openstackutil/ingress_test.go
test/e2e/e2e_test.go

Until now, we didn't have a working Ingress on an initial deployment, and we thought we would just rely on day 2 operations to setup Ingress with e.g. MetalLB.
It turns out that we could use OpenStack Octavia (Load Balancer as a service) as an optional provider for Ingress, at least for now in dev-preview.
With this PR, we don't expect the OpenStack cloud to have Octavia enabled which is why we disable the provider by default, which means Ingress won't be working on day 1 and it's up to the user to deploy something (e.g. MetalLB).
If Octavia is used, the floating IP and the DNS record for Ingress would have to be pre-created before deploying the hosted cluster.
The new CLI would be:
```bash
hypershift create cluster openstack …
```

OSASINFRA-3550: openstack: ingress API & octavia ingress provider

---

test/e2e/util/util.go

Prevents
```
{Failed  === RUN   TestCreateCluster/Main/EnsureHostedClusterImmutability
util.go:911: 
Expected
<string>: Operation cannot be fulfilled on hostedclusters.hypershift.openshift.io "example-c88md": the object has been modified; please apply your changes to the latest version and try again
to contain substring
<string>: Services is immutable
--- FAIL: TestCreateCluster/Main/EnsureHostedClusterImmutability (0.05s)
}
```
https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn/1820792184916414464

OCPBUGS-38041: test: e2e: handle 409 conflict in EnsureHostedClusterImmutability

---

api/hypershift/v1beta1/nodepool_types.go
cmd/cluster/azure/create.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
cmd/nodepool/azure/create.go
hack/app-sre/saas_template.yaml
hypershift-operator/controllers/nodepool/nodepool_controller.go

This adds support for Arm NodePools when using an Arm RHCOS Azure Marketplace image.
Fixes [HOSTEDCP-1853](https://issues.redhat.com/browse/HOSTEDCP-1853)
**Checklist**

HOSTEDCP-1853: Add Arm NodePool Support Through Azure Marketplace

---

control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go

The Kubernetes controller manager default for node monitor grace period is not sufficient to avoid node readiness flaps during brief connectivity problems.
Fixes # https://issues.redhat.com/browse/HOSTEDCP-1776
**Checklist**

HOSTEDCP-1776: Set KCM node monitor grace period

---

control-plane-operator/controllers/hostedcontrolplane/cloud/openstack/reconcile.go
hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack.go
test/e2e/util/fixture.go
test/e2e/util/hypershift_framework.go

* Allow e2e to destroy a cluster that runs on the OpenStack platform.
* Override HostedCluster name if CLUSTER_NAME env is set on OpenStack platform.
* openstack: add missing resources fields to CAPO
* openstack: add missing AutomountServiceAccountToken to CCM

OSASINFRA-3555: openstack: e2e adjustments

---

control-plane-operator/controllers/hostedcontrolplane/oapi/deployment_test.go
test/e2e/util/util.go

manual backport of [OCPBUGS-35905](https://issues.redhat.com/browse/OCPBUGS-35905)
- Depending on https://github.com/openshift/hypershift/pull/4357

OCPBUGS-37060: OCPBUGS-35905: E2E test to verify openshift-apiserver TLS certificates

---

control-plane-operator/controllers/hostedcontrolplane/kas/kms.go
control-plane-operator/controllers/hostedcontrolplane/kas/kms/aws.go
control-plane-operator/controllers/hostedcontrolplane/kas/kms/azure.go
control-plane-operator/controllers/hostedcontrolplane/kas/kms/ibmcloud.go
control-plane-operator/controllers/hostedcontrolplane/kas/kms/kms.go
control-plane-operator/controllers/hostedcontrolplane/kas/secretencryption.go
control-plane-operator/controllers/hostedcontrolplane/kas/secretencryption_test.go
test/e2e/create_cluster_test.go
test/e2e/util/util.go

This PR add support for KMS v2 on AWS. New AWS clusters will only be able to use the new KMS v2 API whilst existing clusters that are already using the v1 API will not be migrated to v2 and stay on v1.
Fixes #OCPBUGS-25937
**Checklist**

OCPBUGS-25937: Support KMS v2 on AWS

---

control-plane-operator/controllers/hostedcontrolplane/storage/envreplace.go

**What this PR does / why we need it**: Allows azure-disk-csi-driver-controller to use registryOverride images, without affecting azure-disk-csi-driver dataplane images 
Fixes # [OCPBUGS-38183](https://issues.redhat.com/browse/OCPBUGS-38183)
**Checklist**

OCPBUGS-38183: make use of azure-disk-driver-control-plane-image

---

api/hypershift/v1beta1/hostedcluster_types.go
hypershift-operator/controllers/nodepool/kubevirt/imagecacher.go
hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go
hypershift-operator/controllers/nodepool/kubevirt/kubevirt_test.go

Added the `hypershift.openshift.io/nodepool-name` label to the rhcos datavolume, to allow easy access to these datavolumes, e.g. for backup.
Fixes #
**Checklist**

CNV-42532: KubeVirt: add label to DataVolume

---

hypershift-operator/init.go
hypershift-operator/init_test.go

Once you add more than one certificate to the ConfigMap referenced in the image.config.openshift.io spec field, the getImageRegistryCABundle processes the certificates properly. However, if you add these through the UI console, the user might not include the newline character, which results in overlapping certificates. This PR ensures a newline is always added after each certificate processed.
This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/4443

OCPBUGS-37173: Add newline after TLS certs referenced by image.config

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
control-plane-operator/controllers/hostedcontrolplane/kas/service.go
control-plane-operator/controllers/hostedcontrolplane/oauth/route.go
hypershift-operator/controllers/hostedcluster/ignitionserver/ignitionserver.go
support/util/route.go

Right now, we use `hostname` being set on the `Route` publishing strategy as a proxy for the HCP router being enabled.  However, there are cases where the `hostname` is set by the user, when a non-default domain is used for example, when the Routes should be admitted by the mgmt cluster ingress but are not because they are labels for the HCP router.
This PR result in the Route only being label when we know the HCP router is in use.
If the cluster is `Private` or `PublicAndPrivate`, and the `oauth` service does not have a hostname specified, the internal (privatelink) oauth name is used for the oauth endpoint `infraStatus` and the KAS `oauthMetadata` config which is how the `console` gets the oauth endpoint.
https://github.com/openshift/hypershift/pull/4495/files#diff-3d4ffda0834e09a59a4d51 …

OCPBUGS-36261: label routes only when HCP router used

---

control-plane-operator/hostedclusterconfigoperator/cmd.go

Remove the hard-coded connectivity agent image URI.
The URI points to a non-existing image and isn't used anymore. 
Fixes [HOSTEDCP-1475](https://issues.redhat.com/browse/HOSTEDCP-1475)
**Checklist**

HOSTEDCP-1475: Remove hard-coded konnectivity agenty image URI

---

api/hypershift/v1beta1/hostedcluster_types.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml

Some CEL rules seems to be wrong, using double single-quotes instead of double quotes.
e.g.
```yaml
rule: 'self.platform.type == ''Azure'' ? self.services.exists(s, s.service
== ''APIServer'' && s.servicePublishingStrategy.type == ''Route''
&& s.servicePublishingStrategy.route.hostname != '''') : true'
```
This PR change this strings to use real double quotes:
```yaml
rule: 'self.platform.type == "Azure" ? self.services.exists(s, s.service
== "APIServer" && s.servicePublishingStrategy.type == "Route" 
&& s.servicePublishingStrategy.route.hostname  != "") : true'
```
Fixes # …

NO-JIRA: Fix CEL rules in the CRD

---

docs/content/how-to/openstack/create-openstack-cluster.md
support/config/deployment.go
support/config/deployment_test.go

We don't know whether an OpenStack cloud is deployed across multiple availability zones or not.
So we can't require the scheduling of HA pods across multiple zones.
For the OpenStack platform, let's relax that rule and allow to use the
`PodAntiAffinity.PreferredDuringSchedulingIgnoredDuringExecution` instead.
So now in HA mode, pods will be scheduled on multiple zones by preference but if it's not possible
they'll just be spread across nodes which is fine for us now.
Note: we also apply this change to the Kubevirt platform since this was explicitly asked in the review.

OSASINFRA-3553: relax PodAffinityTerm for zone spreading in HA

---

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
konnectivity-https-proxy/cmd.go

The dialer that the https proxy was creating was not configured by
default to talk directly to cloud provider endpoints. This was
preventing the ingress operator from successfully tearing down hosted
clusters.
This commit configures the konnectivity-https-proxy to talk directly
to cloud api endpoints for the ingress operator and adds proxy env
variables if they exist.
Fixes #[OCPBUGS-37052](https://issues.redhat.com/browse/OCPBUGS-37052)
**Checklist**

OCPBUGS-37052: HTTPS proxy: do not proxy communication to cloud providers

---

.tekton/hypershift-operator-main-pull-request.yaml
.tekton/hypershift-operator-main-push.yaml

This update configures the SAST task to upload SARIF results to quay.io for long-term storage
Related: 
- https://issues.redhat.com/browse/KONFLUX-3663
- https://issues.redhat.com/browse/KONFLUX-2263

NO-JIRA: fix(KONFLUX-3663): format PipelineRun files and upload SAST results

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Preserve_existing_resources.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Private_apiserver_connectivity__proxy_apiserver_address_is_unset.yaml

cluster-network-operator will start deploying a new console plugin for the Networking section in the OCP UI. in order to maintain compitability with hypershift guest clusters, the hosted CNO will also have to do that. for CNO to be able to access the networking console plugin image, it will need to fetch it from the OCP release payload, that is being added at https://github.com/openshift/cluster-network-operator/pull/2332.
Fixes #
**Checklist**

CONSOLE-3952: Add networking-console-plugin image to CNO as an env var

---

contrib/snyk/READ_ME.md
contrib/snyk/check-for-cve.sh

**What this PR does / why we need it**: script that can be used to retrieve the package versions for HO and CPO using docker without having to provide images. Uses latest nightlies for CPO and latest HO build from rhtap.
Fixes #
sample output 
```
➜  hypershift git:(pstefans-add-cve-script) PULL_SECRET=$PULL_SECRET /bin/bash /Users/pstefans/GitHub/openshift/hypershift/contrib/snyk/check-for-cve.sh krb5
===== Searching HO Image =====
quay.io/acm-d/rhtap-hypershift-operator:latest
Image: quay.io/acm-d/rhtap-hypershift-operator:latest
krb5-libs-1.21.1-1.el9.aarch64
=============================================
===== …
```

NO-JIRA: add docker script to find package versions in HO & CPO

---

Dockerfile
Dockerfile.control-plane

**What this PR does / why we need it**: Bump HO and CPO image to use 4.18 base images
Fixes # [OCPBUGS-38409](https://issues.redhat.com/browse/OCPBUGS-38409)
**Checklist**

OCPBUGS-38409: Update CPO and HO base images to 4.18

---

Makefile
cmd/infra/aws/delegating_client.go
control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/kas/config.go
control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
control-plane-operator/controllers/hostedcontrolplane/kas/kubeconfig.go
control-plane-operator/controllers/hostedcontrolplane/kas_pki_setup.go
control-plane-operator/controllers/hostedcontrolplane/manifests/configoperator.go
control-plane-operator/controllers/hostedcontrolplane/manifests/kas.go
control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go
control-plane-operator/controllers/hostedcontrolplane/pki/ca.go
control-plane-operator/controllers/hostedcontrolplane/pki/kas.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/kas/admissionpolicies.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/admissionpolicies.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
control-plane-operator/hostedclusterconfigoperator/operator/config.go
go.mod
go.work.sum
support/config/types.go
test/e2e/util/hypershift_framework.go
test/e2e/util/util.go
vendor/modules.txt

Added ValidatingAdmissionPolicies to the KAS's HostedCluster to block all configuration requests managed in the management cluster via the HostedCluster object.
Enabling the ValidatingAdmissionPolicy feature gate in the KAS allows us to block certain requests from the Data Plane side without using a webhook. To achieve this, we created the necessary resources (Certificate, RBAC, etc.) that allow HCCO to be identified with a specific user. This designated user will be the only one authorized to execute the required requests. All other users, including those using the admin-kubeconfig, will be blocked by the VAPs validation
Pull Request Content:
- Enabled ValidatingAdmissionPolicies (VAP) FeatureGate on the KAS
- Added a new user (via certificates) to HCCO
- Implemented a new reconciler on …

OCPBUGS-34816: Block data plane HC configuration requests

---

Dockerfile.control-plane

**What this PR does / why we need it**: Bumps CPO  base image to 4.17:base-rhel9
Fixes #
**Checklist**

OCPBUGS-38410: bump CPO base image to use 4.17:base-rhel9

---

hypershift-operator/controllers/nodepool/nodepool_controller.go
support/conditions/conditions.go
test/e2e/util/util.go

In cases where the NodePool has 0 replicas and there are no KubevirtMachines registered with the nodepool, the condition of KubeVirtNodesLiveMigratable should not be set at all (whether true or false).
This is done in order to fix the failure in the TestNodePool e2e, in which the HostedCluster conditions are being verified on a 0-replicas NodePool.
Fixes #
**Checklist**

NO-JIRA: [kubevirt] Fix KubeVirtNodesLiveMigratable condition for NodePools with 0 replicas

---

hypershift-operator/controllers/nodepool/nodepool_controller.go

There are cases when more than a single `NodePool` is associated with the hosted-cluster. In such cases there could me more than a single `PerformanceProfile` as well - one profile per each `NodePool`.
NTO generates a `ConfigMap` that holds the `PerformanceProfile` status in it. HyperShift controller is watching for these configMap status and write its status into the `NodePool` status.
There's a bug in the `List` logic - the controller should filter the `ConfigMap` status per `NodePool`, otherwise it might lists other `ConfigMap`s as well, which are associated to different `NodePool`s on the cluster. This will result with an error that the controller wouldn't be able to recover from.
In order to fix the issue we need to list the `ConfigMap` based …

OCPBUGS-38463: nodepoolcontroller: `List()` PerformanceProfile status per NodePool

---

cmd/cluster/azure/create.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_create_with_a_ure_marketplace_image.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/infra/azure/create.go

We should be using the infraID from the infra-json file if it is present.
Also, the --rhcos-image flag is not required, for example, when using an Azure marketplace image.

OCPBUGS-38739: [Azure] Use infraID from infra-json if provided

---

contrib/snyk/check-for-cve.sh

**What this PR does / why we need it**: Adds hardcoded 4.14 and 4.14 HO base images to cve scan script
Fixes #
**Checklist**

NO-JIRA: add 4.14 and 4.15 HO base images to docker cve scan scripts

---

hypershift-operator/controllers/nodepool/nodepool_controller.go
ignition-server/cmd/run_local_ignitionprovider.go
ignition-server/controllers/local_ignitionprovider.go
ignition-server/controllers/tokensecret_controller.go
ignition-server/controllers/tokensecret_controller_test.go

Adds a has for the additionalTrustBundle CM specified in the HC to the token secret, this will regenerate the payload and re rollout the nodes with the up to date additionalTrustBundle
Fixes # https://issues.redhat.com/browse/OCPBUGS-36680
**Checklist**

OCPBUGS-36680: ensure additionalTrustBundle propogates to workers

---

control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go

**What this PR does / why we need it**: fixes conformance test failures due to [OAPI failure](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.17-periodics-e2e-aws-ovn-conformance/1827247135871995904/artifacts/e2e-aws-ovn-conformance/dump/artifacts/namespaces/clusters-86846e8bf78169421cfc/core/pods/logs/openshift-apiserver-9cd49cf48-8hrnf-oas-trust-anchor-generator-previous.log) 
Fixes # [OCPBUGS-38925](https://issues.redhat.com/browse/OCPBUGS-38925)
**Checklist**

OCPBUGS-38925: copy oapi ca-trust recursively when building trust anchor

---

test/e2e/util/hypershift_framework.go

HCCO installs the admission policies, however, `NonePlatform` clusters can be ready before the HCCO is fully up and reconciling, resulting in a potential race and flaky test assertions.

OCPBUGS-39078: e2e: skip VAP checks if platform is None

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/kas/config.go
control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go
control-plane-operator/controllers/hostedcontrolplane/pki/kas.go

This mostly reverts https://github.com/openshift/hypershift/pull/4566 and regroups private mgmt cluster service network dns names for the KAS into their own cert stored in a new `kube-server-private` secret.

OCPBUGS-39147: regroup KAS certs into public and private certs

---

control-plane-operator/controllers/hostedcontrolplane/cvo/params.go
control-plane-operator/main.go

cherry-pick of https://github.com/openshift/hypershift/pull/4185
Fixes #
**Checklist**

[release-4.15] OCPBUGS-35815: Add hypershift-cluster-version-operator image to release providers

---

api/hypershift/v1alpha1/nodepool_types.go
api/hypershift/v1beta1/nodepool_types.go
client/applyconfiguration/hypershift/v1alpha1/awsnodepoolplatform.go
client/applyconfiguration/hypershift/v1beta1/awsnodepoolplatform.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
docs/content/reference/api.md
hypershift-operator/controllers/nodepool/aws.go
vendor/github.com/openshift/hypershift/api/hypershift/v1alpha1/nodepool_types.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go

This allows launching AWS EC2 instances into dedicated instances or dedicated hosts.
Fixes #
**Checklist**

HOSTEDCP-1933: Expose AWS Tenancy through NodePool API

---

control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go
control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert_test.go

Manual cherry-pick of https://github.com/openshift/hypershift/pull/4564
Includes a new commit adding a restMapper parameter for transportForCARef so we can fake tests with this client go version. Otherwise this client go version requires the fake kubeconfig kas address to be a valid serving URL.

[release-4.14] OCPBUGS-38791: Let the CPO oidc check resolve through data plane 

---

api/hypershift/v1beta1/nodepool_types.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
hypershift-operator/controllers/nodepool/azure.go
hypershift-operator/controllers/nodepool/azure_test.go
hypershift-operator/controllers/nodepool/nodepool_controller.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go

This PR:
* lets Image be mutable in Azure NodePools. If Image is not mutable, then there is no way of upgrading the image for an Azure NodePool.
* Uses machineTemplateSpec for Azure in the NodePool controller so changes to the spec trigger NodePool upgrades.
Fixes [OCPBUGS-38921](https://issues.redhat.com/browse/OCPBUGS-38921)
**Checklist**

OCPBUGS-38921: Set Image as mutable and trigger upgrades on Azure NodePool spec changes

---

cmd/infra/aws/route53.go
control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
control-plane-operator/controllers/awsprivatelink/route53.go
test/e2e/util/hypershift_framework.go
test/e2e/util/util.go

This change is only for our CI.
Instead of handling the DNS prior to deploy a HostedCluster, we now leverage AWS Route53 service, using the CI credentials to create the `*.apps.<cluster-name>.<base-domain>` DNS record dynamically.
With that work, we'll be able to not only simplify our CI workflow (that used to create a FIP, update DNS, etc), but also to deploy concurrent HostedClusters.
This PR leverages as much as possible the existing functions used by AWS infra to find DNS domains or create a DNS record.

OSASINFRA-3572: e2e/openstack: handle DNS for ingress using route53

---

.tekton/hypershift-release-414-pull-request.yaml
.tekton/hypershift-release-414-push.yaml

This PR:
* updates the konflux references 
* removes BASE_IMAGES_DIGEST for buildah migration
* removes sbom-json-check from tekton files
N/A
**Checklist**

NO-JIRA: Konflux migration 4.14

---

ignition-server/controllers/local_ignitionprovider.go
ignition-server/controllers/local_ignitionprovider_test.go

Goes before/after https://github.com/openshift/hypershift/pull/4651
Fixes #
**Checklist**

OCPBUGS-38794: handle version skewed NodePools that do not have rhel9 binaries

---

cmd/cluster/aws/create.go

Fix validation for multi-arch image by checking the absence of ReleaseImage before ReleaseStream
Fixes OCPBUGS-39396
**Checklist**

OCPBUGS-39396: Fix multi-arch validation by prioritizing ReleaseImage check

---

cmd/cluster/aws/create.go
cmd/cluster/core/create.go
cmd/nodepool/kubevirt/create.go
control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/hostedclusterconfigoperator/controllers/machine/machine.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
hypershift-operator/controllers/hostedcluster/network_policies.go

This PR systematically replaces all uses of MustParse functions with non-constant input with their Parse equivalent, except in one case where the containing function does not have an error return. We add a warning comment there instead.
2 of these in particular may allow a user who is able to create a HostedCluster to cause the HostedCluster controller to panic-loop. Specifically the following 2 fields are not validated by the API server on admission, and are parsed with MustParse:
* HostedCluster.Spec.Networking.APIServer.AdvertiseAddress
* HostedCluster.Spec.Networking.ClusterNetwork.CIDR …

OCPBUGS-39525: Fix uses of MustParse* on non-constant input

---

control-plane-operator/controllers/hostedcontrolplane/pki/kas.go

When configuring Openshift Auth Provider talking to openshift.default.svc kas complains
Fixes #
**Checklist**

OCPBUGS-33628: Add oauth domain for kas cert

---

cmd/cluster/core/create.go

We need the ability to add labels to the HostedCluster from the cli. This will be used by MCE to allow people to influence what hypershift addons are associated with a HostedCluster through the use of label selectors.

CNV-45889: Add --labels hcp cli arg for adding labels to HostedCluster

---

api/hypershift/v1beta1/hostedcluster_types.go
client/applyconfiguration/hypershift/v1beta1/openstackplatformspec.go
cmd/cluster/openstack/create.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedclusters.yaml
cmd/install/assets/hypershift-operator/hypershift.openshift.io_hostedcontrolplanes.yaml
control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/ingress.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
docs/content/how-to/openstack/create-openstack-cluster.md
docs/content/reference/api.md
test/e2e/e2e_test.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

This feature was added with the goal of being able to
have Ingress working on day 1 but the way it's implemented is racy
because it depends on a resource that Hypershift controller don't own,
and is owned by the Ingress controller.
Let's remove it now and re-add it later when it's safer.

OSASINFRA-3584: openstack: remove support for floating IP

---

konnectivity-https-proxy/cmd.go
support/konnectivityproxy/dialer.go
support/konnectivityproxy/proxy_dialer.go
support/konnectivityproxy/resolver.go

Fixes dialing from ingress where we want to use the management cluster's proxy (if configured) when connecting to cloud APIs.
Fixes #[OCPBUGS-37052](https://issues.redhat.com/browse/OCPBUGS-37052)
**Checklist**

OCPBUGS-37052: Use http dialer when dialing through proxy

---

control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go

The host name of an IDP endpoint may not be resolvable by the management cluster. The setting to resolve the name before dialing forces the dialer to use the data plane to resolve a name before sending a request through konnectivity.
Fixes #[OCPBUGS-38349](https://issues.redhat.com/browse/OCPBUGS-38349)
**Checklist**

OCPBUGS-38349: CPO oauth idp converter: resolve names before dialing

---

ignition-server/cmd/run_local_ignitionprovider.go
ignition-server/controllers/local_ignitionprovider.go
support/releaseinfo/registry_image_content_policies_test.go

Without this the value in the env variable is always used, which comes from the HC and doesn't necessarily match the intentded nodepool version
Fixes #
**Checklist**

OCPBUGS-39420: Let payload generation pick the release for the NodePool

---

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go
control-plane-operator/hostedclusterconfigoperator/cmd.go

Changes the certificate used by the HostedClusterConfigOperator to enable root certificate authority (root CA) rotation. 
Fixes # https://issues.redhat.com/browse/OCPBUGS-41328
**Checklist**

OCPBUGS-41328: Use KubeClientCABundle for HostedClusterConfigOperator cluster-signer-ca

---

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
konnectivity-https-proxy/cmd.go
support/konnectivityproxy/dialer.go
support/konnectivityproxy/proxy_dialer.go
support/konnectivityproxy/resolver.go

Ingress operator canary checks require access to the internet since they
probe the external canary routes. The socks5 proxy sidecar does not
provide external access when a user proxy is required. This commit
switches to using the konnectivity-https-proxy that does take into
account the user's proxy configuration.
The dialer that the https proxy was creating was not configured by
default to talk directly to cloud provider endpoints. This was
preventing the ingress operator from successfully tearing down hosted
clusters.
This commit configures the konnectivity-https-proxy to talk directly
to cloud api endpoints for the ingress operator and adds proxy env
variables if they exist.
Fixes dialing from ingress where we want to use the management cluster's …

OCPBUGS-38062: [release-4.16] Use HTTP proxy for ingress controller 

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/ingress/router.go
control-plane-operator/controllers/hostedcontrolplane/manifests/ingress.go

This PR was merged in a backport, the reverted and this will restore back and this is the timeline:
**Timeline**:
- First backport merge: https://github.com/openshift/hypershift/pull/4661
- Revert: https://github.com/openshift/hypershift/pull/4667
- This PR will put back the initial PR
**The Why**:
I've misunderstood that a Bare metal HCP on 4.14 cannot deploy a MHC because it never reaches the IgnitionReached and mixed that with the PDBs. So to summarise, we need this backport to add the PDBs for the router deployment in 4.14 payload.
Original msg:
The router deployment is in the request serving path and should be protected from outages by a PDB like the other request serving components

NO-JIRA: Add PodDisruptionBudget for router deployment

---

api/hypershift/v1alpha1/conditions.go
api/hypershift/v1beta1/hostedcluster_conditions.go
docs/content/reference/api.md
hypershift-operator/controllers/hostedcluster/etcd_recovery.go
hypershift-operator/controllers/hostedcluster/metrics/metrics.go
vendor/github.com/openshift/hypershift/api/hypershift/v1alpha1/conditions.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_conditions.go

This PR consists of two parts.
Firstly, I've added a new condition to the HostedCluster called `EtcdRecoveryActive`, which indicates that the Etcd recovery job has been triggered due to an error in the Etcd cluster. The condition covers three scenarios:
- The job has been initiated and is in progress (Status: True / Reason: AsExpected)
- The job has completed successfully (Status: False / Reason: AsExpected)
- The job has completed but failed (Status: False / Reason: EtcdRecoveryJobFailed)
The second part of the PR introduces a new metric called `hypershift_etcd_manual_intervention_required`. This metric helps SD/SRE teams identify Etcd clusters that require manual intervention. The metric includes the following fields:
- HC Namespace
- HC Name
- HC ID
- ROSA Environment
- ROSA ID
The …

HOSTEDCP-1940: Add alert for Etcd recovery

---

hypershift-operator/controllers/nodepool/haproxy.go
hypershift-operator/controllers/nodepool/haproxy_test.go
hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestAPIServerHAProxyConfig_when_noproxy_matches_the_external_kas_adress_it_should_create_an_haproxy.yaml

Without this users need to add either the internal address, kubernets.svc, serviceNetwork or clusterNetwork. With this adding the external kas address will make the pod->kas communication to ignore the proxy as well
Fixes #
**Checklist**

OCPBUGS-39123: Add external kas address to no proxy skip list

---

api/go.mod
api/go.sum
api/hypershift/v1alpha1/nodepool_types.go
api/hypershift/v1beta1/nodepool_types.go
api/vendor/golang.org/x/net/LICENSE
api/vendor/golang.org/x/net/http2/transport.go
api/vendor/golang.org/x/text/LICENSE
api/vendor/modules.txt
client/applyconfiguration/hypershift/v1alpha1/azurenodepoolplatform.go
client/applyconfiguration/hypershift/v1beta1/azurenodepoolplatform.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_nodepools.yaml
cmd/nodepool/azure/create.go
docs/content/reference/api.md
hypershift-operator/controllers/nodepool/azure.go
hypershift-operator/controllers/nodepool/azure_test.go
vendor/github.com/openshift/hypershift/api/hypershift/v1alpha1/nodepool_types.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go

This PR adds a field to the Azure NodePool API to enable EncryptionAtHost and allows EncryptionAtHost to be set in the NodePool controller independently from DiskEncryptionSetID.
Fixes [OCPBUGS-39039](https://issues.redhat.com/browse/OCPBUGS-39039)
**Checklist**

OCPBUGS-39039: Allow Encryption at Host to be Independently Toggled from DiskEncryptionSetID

---

test/e2e/e2e_test.go
test/e2e/util/util.go
test/e2e/util/version.go

This PR adds a simple mechanism for gating/skipping test cases based on the version of the latest release image

HOSTEDCP-1569: e2e: add version gating for 4.17

---

control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
control-plane-operator/controllers/hostedcontrolplane/olm/catalogs_test.go

Which issue(s) this PR fixes :
Fixes #[OCPBUGS-38425](https://issues.redhat.com/browse/OCPBUGS-38425)

OCPBUGS-38425: Return the right tagReference on Catalogs ImageStream

---

cmd/install/install.go
cmd/install/install_render.go

if `hypershift install render --output-file my-file` is given, the generated manifests will be written into that specific file instead to STDOUT
Reason: this gives an option to mitigate situations where the `install render` command logs errors to stdout and makes the consumption of the generated manifests hard, e.g. the best-effort in-cluster proxy detection for external DNS.
Fixes https://issues.redhat.com/browse/ARO-10259
**Checklist**

ARO-10259: add install render option to write manifests to file

---

test/e2e/nodepool_nto_performanceprofile_test.go
test/e2e/util/util.go
test/e2e/util/version.go

Add required version gates for 4.16 to pass with e2e from `main`
Informed by the rehearsal of https://github.com/openshift/release/pull/56637
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/56637/rehearse-56637-periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn/1834244434464608256

HOSTEDCP-1569: e2e: add version gating for 4.16

---

.snyk

vendor is handled by dependabot
resources.go uses MD5 that is a broken crypto but our usage is just to check if the file changed and the likelihood of collision in our managed usage does not warrant a change.

HOSTEDCP-1965: Ignore vendor and resources.go from snyk code test

---

test/e2e/util/util.go

Add gating to test cases that only run in 4.16+
Informed by rehearse on https://github.com/openshift/release/pull/56724
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/56724/rehearse-56724-periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-aws-ovn/1834729010085498880

HOSTEDCP-1569: e2e: add version gating for 4.15

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

Before this commit, the HostedCluster controller would only preserve the status of the ValidAWSIdentityProvider condition if its value was false when the hostedcontrolplane was no longer available. This resulted in the following sequence of events:
- The hosted cluster is deleted
- The CAPI cluster is deleted causing the hosted control plane to be deleted
- The ValidAWSIdentityProvider condition was set to Unknown because there is no longer a hosted control plane to get a value from.
- The AWSEndpointService resource control-plane-operator-finalizer is removed because there is no longer a ValidAWSIdentityProvider
- The control plane namespace is deleted along with the control plane operator pod in it.
- The control plane operator does not get a …

OCPBUGS-42107: Allow the control plane operator to finish deleting VPC endpoint for PrivateLink clusters

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go

Hypershift should conditionally manage the kubeconfig secrets for the DNS operator and Ingress operator based off the DisablePKIReconciliationAnnotation.
Fixes # https://issues.redhat.com/browse/OCPBUGS-41824
**Checklist**

OCPBUGS-41824: Conditionally manage kubeconfig secrets for DNS and Ingress operators

---

test/e2e/util/util.go
test/integration/control_plane_pki_operator.go

This is likely just the first PR to properly adapt `main` e2e for testing 4.14

HOSTEDCP-1569: e2e: add version gating for 4.14

---

api/hypershift/v1beta1/hostedcluster_types.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

Adds an annotation to prevent deletion of the hosted control plane namespace when set.
Near-term backup and restore for Agent platform requires that the HCP namespace remain intact during the hosted cluster deletion due to the Agent CRs that exist in that namespace.
Fixes #OCPBUGS-32592
**Checklist**

OCPBUGS-32592: Add Annotation to skip deleting hcp namespace

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/kas/params.go
hypershift-operator/controllers/nodepool/haproxy.go
hypershift-operator/controllers/nodepool/haproxy_test.go
hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_private_cluster_uses_.local_address_and_LB_kas.yaml
hypershift-operator/controllers/nodepool/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_public_and_private_cluster_uses_.local_address_and_LB_kas.yaml
support/util/expose.go
support/util/expose_test.go
support/util/networking.go
test/e2e/create_cluster_test.go
test/e2e/util/util.go

Manual backport of https://github.com/openshift/hypershift/pull/4275 due to conflict in e2e

[release-4.15] OCPBUGS-42214: Make guest cluster components use the correct KAS port

---

.snyk
ignition-server/cmd/start.go
support/util/util.go
support/util/util_test.go

These PR is a manual backport of :
- https://github.com/openshift/hypershift/pull/4748
This one prepares the release branch to execute (without High security issues) the Openshift CI Security job which under the hood uses the `snyk code test` command and the job fails if SNYK find any high security issue.
After this PR we will need to add a new one to add the CI Job to the release repo as we did with 4.17, 4.18, 4.19 and Main branches in these PRs:
- https://github.com/openshift/release/pull/56687 (4.18, 4.19, Main)
- https://github.com/openshift/release/pull/56912 (4.17)

[release-4.16] NO-JIRA: Security fixes for openshift-ci-security job

---

api/hypershift/v1beta1/endpointservice_types.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_awsendpointservices.yaml
control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller_test.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
hypershift-operator/conversion/conversion_test.go
support/awsutil/errorcode.go
support/awsutil/sg.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/endpointservice_types.go

- Adds code to the AWS privatelink controller to create a security group
per AWSEndpointResource.
- No longer actively removes additional security groups from vpc
endpoints, allowing customers to add their own security groups if
desired.
- Tidies the security group rules for workers, adding descriptions and
missing rules required for IPSEC.
- Fixes deletion bug that caused the default security group to remain in
some instances because the CPO did not make sure that it had actually
been removed.
Fixes #[HOSTEDCP-1442](https://issues.redhat.com/browse/HOSTEDCP-1442)
**Checklist**

HOSTEDCP-1442: Split worker and vpc endpoint security groups

---

.snyk
ignition-server/cmd/start.go
support/util/util.go
support/util/util_test.go

These PR is a manual backport of :
- https://github.com/openshift/hypershift/pull/4750
This one prepares the release branch to execute (without High security issues) the Openshift CI Security job which under the hood uses the `snyk code test` command and the job fails if SNYK find any high security issue.
After this PR we will need to add a new one to add the CI Job to the release repo as we did with 4.17, 4.18, 4.19 and Main branches in these PRs:
- https://github.com/openshift/release/pull/56687 (4.18, 4.19, Main)
- https://github.com/openshift/release/pull/56912 (4.17)
- https://github.com/openshift/release/pull/56938 (4.16)

[release-4.15] NO-JIRA: Security fixes for openshift-ci-security job

---

.snyk
ignition-server/cmd/start.go
support/util/util.go
support/util/util_test.go

These PR is a manual backport of :
- https://github.com/openshift/hypershift/pull/4751
This one prepares the release branch to execute (without High security issues) the Openshift CI Security job which under the hood uses the `snyk code test` command and the job fails if SNYK find any high security issue.
After this PR we will need to add a new one to add the CI Job to the release repo as we did with 4.17, 4.18, 4.19 and Main branches in these PRs:
- https://github.com/openshift/release/pull/56687 (4.18, 4.19, Main)
- https://github.com/openshift/release/pull/56912 (4.17)
- https://github.com/openshift/release/pull/56938 (4.16)
- https://github.com/openshift/release/pull/56941 (4.15)

[release-4.14] NO-JIRA: Security fixes for openshift-ci-security job

---

Dockerfile

`hypershift-operator` image builds are taking a long time in prow ~20m.
Don't build more than we need.

NO-JIRA: remove CPO/CPPKIO from the hypershift-operator image build

---

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
konnectivity-https-proxy/cmd.go
support/konnectivityproxy/dialer.go
support/konnectivityproxy/proxy_dialer.go
support/konnectivityproxy/resolver.go

Backport of https://github.com/openshift/hypershift/pull/4699
Ingress operator canary checks require access to the internet since they
probe the external canary routes. The socks5 proxy sidecar does not
provide external access when a user proxy is required. This commit
switches to using the konnectivity-https-proxy that does take into
account the user's proxy configuration.
The dialer that the https proxy was creating was not configured by
default to talk directly to cloud provider endpoints. This was
preventing the ingress operator from successfully tearing down hosted
clusters.
This commit configures the konnectivity-https-proxy to talk directly
to cloud api endpoints for the ingress operator and adds proxy env
variables if they exist.
Fixes …

OCPBUGS-38066: [release-4.14] Use HTTP proxy for ingress controller

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go

Not supporting 4.11 anymore this is not needed

NO-JIRA: Remove hack for CI in 4.11 release

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/params.go

The socks5 konnectivity proxy does not honor user-configured HTTP/S proxies when sending traffic through the dataplane. Most identity providers handled by the OAuth server do use HTTP/S for external communication and should honor any user configured proxy. This commit adds an additional container to the oauth server deployment with the HTTP konnectivity proxy. This proxy does honor the user-configured HTTP/S proxy for the HostedCluster when sending traffic through the data plane. The socks5 proxy is still used for the LDAP identity provider which does not use the proxy for its traffic. On the OAuth server, the HTTP_PROXY and HTTPS_PROXY environment variables point to the HTTP proxy while the ALL_PROXY variable still points to the socks5 proxy. …

[release-4.14] OCPBUGS-38060: Add HTTP konnectivity proxy to OAuth server

---

cmd/cluster/core/dump.go

They were missing and will be useful for debug.

NO-JIRA: cmd/dump: add OpenStack CAPI resources

---

Containerfile.operator
Dockerfile
support/releaseinfo/registryclient/test/Dockerfile.testdriver

Getting this error in local:
I've check that we have some `Dockerfiles` and `Containerfiles` entries with the `AS` "command" in lowercase.

NO-JIRA: Fix docker check 'AS' as uppercase in container and docker files

---

Dockerfile.dev

This allows us to continue building all-in-one container images in local with the benefits of https://github.com/openshift/hypershift/pull/4754 PR

NO-JIRA: Add Dockerfile.dev to build all-in-one container image for development purposes

---

test/e2e/e2e_test.go

In some complex test scenarios, we would like to allow specifying custom IP ranges for the service and the cluster CIDR, to avoid overlapping addresses that use the defaults.
Fixes #
**Checklist**

NO-JIRA: e2e: add service and cluster CIDRs as flags to the e2e framework

---

api/hypershift/v1beta1/hostedcluster_conditions.go
control-plane-operator/hostedclusterconfigoperator/controllers/hcpstatus/hcpstatus.go
docs/content/reference/api.md
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_conditions.go

The pull propagates `RetrievedUpdates` from ClusterVersion up to HostedCluster
To make it easier for folks working at the management-cluster level to notice and address issues with update-recommendation retrieval.
Especially useful since de4bcbe35e (#3576) made `updateService` a configurable knob, because:
* Users might configure a broken `updateService`, and the new condition would tell them that it wasn't working.
* Users might install a 4.15 or earlier HostedCluster, where the HostedControlPlane controller (which is extracted from the HostedCluster's release image) was too old to have de4bcbe35e, so it doesn't propagate the configured `updateService`, and the cluster-version operator ends up using the default upstream update service.  That …

OTA-1349: *: Propagate RetrievedUpdates from ClusterVersion up to HostedCluster

---

Dockerfile.e2e

This PR is in service to consolidating the `hypershift-aws-e2e-nested` and `hypershift-aws-e2e-external` workflows in the o/r step-registry.
The only real difference between the two is the former uses `test-bin` as the image and the latter uses `hypershift-tests`.
https://github.com/openshift/release/blob/master/ci-operator/step-registry/hypershift/aws/run-e2e/hypershift-aws-run-e2e-ref.yaml#L35
https://github.com/openshift/release/blob/master/ci-operator/step-registry/hypershift/aws/run-e2e/external/hypershift-aws-run-e2e-external-ref.yaml#L24
The two flows are being synced in https://github.com/openshift/release/pull/57123/commits/b650be1daa2c418766f709fa59d7f65f5647ed28
If we have our own Dockerfile for the e2e, instead of using `test_binary_build_commands`, we can specify the name to …

HOSTEDCP-1569: add dockerfile for e2e

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

Before this commit, if configuration was determined to be invalid, we simply returned a nil from the reconciliation loop and waited for something to change in the HostedCluster. This fails to account for when the reason for the invalid configuration is transient, such as a missing ConfigMap. When the ConfigMap is finally made available, the HostedCluster does not resume reconciliation.
Now an error is thrown when configuration is not valid, resulting in a requeue of the HostedCluster, until the invalid configuration is resolved.
Fixes …

OCPBUGS-42433: Retry reconciliation with invalid configuration

---

test/e2e/util/util.go

observed in MCO rehearsal
```
--- FAIL: TestCreateCluster (2136.19s)
--- FAIL: TestCreateCluster/ValidateHostedCluster (1908.04s)
--- FAIL: TestCreateCluster/Teardown (225.96s)
--- PASS: TestCreateCluster/Teardown/ValidateMetricsAreExposed (0.07s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x712fa07]
goroutine 1383 [running]:
testing.tRunner.func1.2({0x799cd20, 0xb3ccb30})
/usr/lib/golang/src/testing/testing.go:1631 +0x49e
testing.tRunner.func1()
/usr/lib/golang/src/testing/testing.go:1634 +0x669
panic({0x799cd20?, 0xb3ccb30?})
/usr/lib/golang/src/runtime/panic.go:770 +0x136 …
```

NO-JIRA: e2e: openstack: fix nil deref in route53 teardown

---

cmd/infra/azure/create.go
cmd/infra/azure/destroy.go

use getResourceGroupName for infra deletion in azure so destroy infra can be ran without --resource-group-name
Follow up PR for comments on https://github.com/openshift/hypershift/pull/4282
Fixes # [HOSTEDCP-1788](https://issues.redhat.com/browse/HOSTEDCP-1788)
**Checklist**

HOSTEDCP-1788: use getResourceGroupName for infra deletion in azure so destroy infra can be ran without --resource-group-name

---

api/hypershift/v1beta1/hostedcluster_types.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

**What this PR does / why we need it**: Adds support to disable ignition server reconcilement 
Fixes # https://issues.redhat.com/browse/HOSTEDCP-1815
**Checklist**

HOSTEDCP-1815: feat(ignition): Add option to disable ignition server reconciliation

---

etcd-recovery/etcdrecovery.go

The `recover-etcd` command was setting up a flag that doesn't exist as required. This PR cleans up that and fixes the require flags handling logic.
There were two main problems that were hidden by the swallowed errors:
1. The `etcd-endpoints` flag didn't exist
Here's a test when I changed the code to not swallow the error 
```shell
./bin/hypershift-operator recover-etcd --help
error occurred no such flag -etcd-endpoints
```
2. The `namespace` flag was set using the wrong method. It is a `PersistedFlag` so must be set using `MarkPersistentFlagRequired`  instead of `MarkFlagRequired`. 
```shell
./bin/hypershift-operator recover-etcd --help
error setting up namespace flag as required: no such flag -namespace
```
**Checklist**

NO-JIRA: Fix recover-etcd cmd marking a missing flag required

---

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go
control-plane-operator/controllers/hostedcontrolplane/kcm/params.go
control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
control-plane-operator/controllers/hostedcontrolplane/ocm/params.go
control-plane-operator/controllers/hostedcontrolplane/routecm/params.go
control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go
support/config/deployment.go

**What this PR does / why we need it**: Reduce size of control plane by running 2 replicas of active/passive HA deployments
Fixes #42100
**Checklist**

OCPBUGS-42100: Run 2 replicas of active/passive HA components

---

test/e2e/util/util.go

**What this PR does / why we need it**: disables the ensurePSANotPrivileged test on 4.16 as we use privileged instead of restricted ref https://github.com/openshift/hypershift/pull/4193
Fixes #
**Checklist**

NO-JIRA: disable ensurePSANotPrivileged test on <4.17

---

api/hypershift/v1beta1/hostedcluster_types.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

Backport of PR https://github.com/openshift/hypershift/pull/4741
---
Near-term backup and restore for Agent platform requires that the HCP namespace remain intact during the hosted cluster deletion due to the Agent CRs that exist in that namespace.
Adds an annotation to prevent deletion of the hosted control plane namespace when set.
Fixes # [OCPBUGS-42608](https://issues.redhat.com/browse/OCPBUGS-42608)
**Checklist**
/cc @jparrill

[release-4.16] OCPBUGS-42608: Add Annotation to skip deleting hcp namespace

---

availability-prober/availability_prober.go
control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Preserve_existing_resources.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Private_apiserver_connectivity__proxy_apiserver_address_is_unset.yaml
control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/kas/admissionpolicies.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/kas/admissionpolicies_test.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
go.mod
support/util/containers.go
support/util/manifests.go
test/e2e/util/util.go

This PR adds:
Fixes #[OCPBUGS-39369](https://issues.redhat.com/browse/OCPBUGS-39369)

OCPBUGS-39369: Add TokenMinter container and RBAC for the CNO

---

hypershift-operator/controllers/hostedcluster/network_policies.go
hypershift-operator/controllers/manifests/networkpolicy/manifests.go

This fixes two issues that impact HCP with the NodePort publishing strategy.
1. The konnectivity server component has moved in and out of the kas pod throughout several releases. The result is, some releases have network policies that allow connections to the konnectivity server, and others do not. To account for this, the hypershift operator needs to support both when the konnectivity server is in the kas pod and when it is outside of the pod.
This is resolved by adding a new network policy that allows access to the konnectivity server when it is hosted within the kas pod (which is how this is currently deployed in 4.17)
2. Nodes currently can't access the ignition proxy to retrieve their configs. This is resolved by adding a network policy for the ignition proxy.

OCPBUGS-42579: Add network policies for konnectivity server and ignition server proxy

---

hypershift-operator/controllers/nodepool/kubevirt.go
hypershift-operator/controllers/nodepool/kubevirt/imagecacher.go
hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go
hypershift-operator/controllers/nodepool/kubevirt/kubevirt_test.go
hypershift-operator/controllers/nodepool/nodepool_controller.go

This fixes a regression to the kubevirt provider that was introduced sept 26th by some nodepool refactoring PRs, https://github.com/openshift/hypershift/pull/4795 and https://github.com/openshift/hypershift/pull/4823

NO-JIRA: Fixes kubevirt image cacher

---

konnectivity-https-proxy/cmd.go

When sending traffic through konnectivity (whether proxied or not) we need dns names to be resolved by the data plane. This change ensures we do that (not only for internal service names).
Fixes #[OCPBUGS-42783](https://issues.redhat.com/browse/OCPBUGS-42783)
**Checklist**

OCPBUGS-42783: Use guest DNS resolution in Konnectivity HTTPS proxy by default

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
control-plane-operator/controllers/hostedcontrolplane/kas/service.go
control-plane-operator/controllers/hostedcontrolplane/oauth/route.go
hypershift-operator/controllers/hostedcluster/ignitionserver/ignitionserver.go
support/util/route.go

manual backport combining https://github.com/openshift/hypershift/pull/4495 and https://github.com/openshift/hypershift/pull/4562

OCPBUGS-42714: label routes only when HCP router used

---

control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
support/config/constants.go

In managed services, a local audit-webhook service is used to forward audit logs externally. This traffic should not be routed through konnectivity since it goes to a local service in the control plane.
Fixes #[OCPBUGS-42873](https://issues.redhat.com/browse/OCPBUGS-42873)
**Checklist**

OCPBUGS-42873: Do not send traffic to local audit-webhook through konnectivity

---

cmd/infra/azure/create.go

**What this PR does / why we need it**: Changing from NumberOfProbes to ProbeThreshold when creating LoadBalancer for Azure infra as NumberOfProbes will become deprecated in 2027
Fixes # [HOSTEDCP-2009](https://issues.redhat.com/browse/HOSTEDCP-2009)
**Checklist**

HOSTEDCP-2009: change from NumberOfProbes to ProbeThreshold

---

test/e2e/create_cluster_test.go

OpenShiftPodSecurityAdmission feature gate is not enabled by default in 4.17 any longer. We need to stop enforcing that PSA is privileged
https://github.com/openshift/api/blob/release-4.17/features/features.go
https://github.com/openshift/api/pull/2018
Fixes #
**Checklist**

NO-JIRA: Remove EnsurePSANotPrivileged check

---

control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
support/config/constants.go

In managed services, a local audit-webhook service is used to forward audit logs externally. This traffic should not be routed through konnectivity since it goes to a local service in the control plane.
Backport of https://github.com/openshift/hypershift/pull/4864
Fixes #
**Checklist**

OCPBUGS-42974: [release-4.17] Do not send traffic to local audit-webhook through konnectivity

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/manifests/azure.go

Azure disk and file csi controllers currently reuse the cloud provider secret to set up their authentication with Azure cloud API. These components should each use their own secrets; this will be required on ARO HCP deployments.
A follow on PR will be created providing different credentials for azure disk and file to use respectively.
Fixes #
**Checklist**

HOSTEDCP-1994: Create separate secrets for Azure disk and file

---

test/e2e/util/util.go

OpenShiftPodSecurityAdmission feature gate is not enabled by default in 4.17 any longer. We need to stop enforcing that PSA is privileged
https://github.com/openshift/api/blob/release-4.17/features/features.go
https://github.com/openshift/api/pull/2018
Fixes #
**Checklist**

NO-JIRA: Enforce EnsurePSANotPrivileged for 4.18 and later

---

api/hypershift/v1beta1/endpointservice_types.go
cmd/install/assets/hypershift-operator/hypershift.openshift.io_awsendpointservices.yaml
control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller_test.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
hypershift-operator/conversion/conversion_test.go
support/awsutil/errorcode.go
support/awsutil/sg.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/endpointservice_types.go

- Adds code to the AWS privatelink controller to create a security group
per AWSEndpointResource.
- No longer actively removes additional security groups from vpc
endpoints, allowing customers to add their own security groups if
desired.
- Tidies the security group rules for workers, adding descriptions and
missing rules required for IPSEC.
- Fixes deletion bug that caused the default security group to remain in
some instances because the CPO did not make sure that it had actually
been removed.
Backport of https://github.com/openshift/hypershift/pull/4742
Fixes …

HOSTEDCP-2023: [release-4.17] Split worker and vpc endpoint security groups

---

control-plane-operator/controllers/hostedcontrolplane/kas/config.go

KASO did this here
https://github.com/openshift/cluster-kube-apiserver-operator/pull/1731/files#diff-1460721532208bb105e22ac02386e5e51a23c597dac5ab57ba59592a0e0eef1bR22-R25

OCPBUGS-43064: move resource.k8s.io to v1alpha3 for kube 1.31

---

cmd/cluster/aws/create.go
cmd/infra/aws/create.go
cmd/infra/aws/ec2.go
cmd/infra/aws/util/util.go

This makes it possible to create VPC peering connections between different cluster infrastructures. It is a prerequisite for more extensive proxy testing.
Fixes #[HOSTEDCP-2025](https://issues.redhat.com/browse/HOSTEDCP-2025)
**Checklist**

HOSTEDCP-2025: Allow setting the VPC CIDR when creating AWS infrastructure

---

Makefile

QE tests extract the hypershift binary from the HO image can sometime run it in a rhel8 environment where the binary will have linking errors.
CGO was enabled in https://github.com/openshift/hypershift/pull/2997 for FIPS compliance, but I don't think we need this for the CLIs

NO-JIRA: statically link CLI binaries

---

cmd/install/assets/hypershift_operator.go
cmd/install/install.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controlplaneoperator-overrides/assets/overrides.yaml
hypershift-operator/controlplaneoperator-overrides/assets/overrides_sample.yaml
hypershift-operator/controlplaneoperator-overrides/overrides.go
hypershift-operator/controlplaneoperator-overrides/overrides_test.go
support/config/constants.go
test/e2e/e2e_test.go

Adds a file where we can statically specify replacement CPO images for specific OCP releases. Enables e2e testing of this combination by setting previous and latest release images in e2e based on the presence of an environment variable.
Fixes #[HOSTEDCP-2026](https://issues.redhat.com/browse/HOSTEDCP-2026)
**Checklist**

HOSTEDCP-2026: Add support for static control plane operator overrides

---

hypershift-operator/controllers/nodepool/capi.go
hypershift-operator/controllers/nodepool/nodepool_controller.go
test/e2e/nodepool_machineconfig_test.go
test/e2e/nodepool_nto_machineconfig_test.go
test/e2e/nodepool_nto_performanceprofile_test.go
test/e2e/nodepool_test.go
test/e2e/util/util.go

* When running the nodepool tests, the HostedCluster is created with a
initial Nodepool and a replica == 0. That involves that the
router-default won't exist and therefore we can't expect the Ingress to
work. So let's skip the DNS record creation when there is no nodepool
but show a warning because we can't expect the cluster to be healthy.
* Remove double get guestClient when creating Route54 records.
* nodepool: force replica to 1 for the default since we need one
nodepool for Ingress to be working.
* Use an existing function to test the Nodepool replicas and the nodes
numbers.
* skip NTO tests which can't work on the OpenStack platform at this
time.
* nodepool/openstack: support AMD64 arch.
* nodepool/openstack: add missing watch in the reconciler.

OCPBUGS-43087: openstack/e2e: re-work nodepool tests

---

test/e2e/create_cluster_test.go
test/e2e/util/util.go

We currently have no test coverage for `TechPreviewNoUpgrade` feature set in hypershift.  We uncovered https://github.com/openshift/cluster-storage-operator/pull/519 and https://github.com/openshift/hypershift/pull/4887 recently.
As of `4.18.0-0.ci-2024-10-11-065556`, this was working again.
This makes `TestCreateCluster` deploy a `TechPreviewNoUpgrade` cluster so we can ensure it stays working.

HOSTEDCP-2028: e2e: use TechPreviewNoUpgrade feature set in TestCreateCluster

---

api/hypershift/v1beta1/hostedcluster_conditions.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/oauth/config.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go
docs/content/reference/api.md
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_conditions.go

Right now, IDP config/reachability issues are fatal to the CPO reconcile loop and lead to all manner of weird issues due to partial reconciliation of the HCP.
This makes the error non-fatal to the reconcile loop and reports any IDP issues on a new HC condition `ValidIDPConfiguration`
cc @csrwng

OCPBUGS-38132: add ValidIDPConfiguration condition to report IDP config issues

---

test/e2e/e2e_test.go
test/e2e/nodepool_prev_release_test.go
test/e2e/nodepool_test.go

**What this PR does / why we need it**: Add nodepool test case for creating  nodepool n-2 minor ocp release
Fixes # [HOSTEDCP-1472](https://issues.redhat.com/browse/HOSTEDCP-1472)
**Checklist**

HOSTEDCP-1472: add CP with n-2 NP test

---

control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/config.go
control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go

This is a general bug fix. The cluster policy controller was previously not using the proper feature flags, this data needs to be passed to it.
https://ibm-argonauts.slack.com/archives/C015MKYUVSR/p1729088012086239?thread_ts=1729086853.463239&cid=C015MKYUVSR
Fixes #
**Checklist**

OCPBUGS-43448: Pass feature flags to clusterpolicy controller

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
control-plane-operator/controllers/hostedcontrolplane/kas/service.go
control-plane-operator/controllers/hostedcontrolplane/oauth/route.go
hypershift-operator/controllers/hostedcluster/ignitionserver/ignitionserver.go
support/util/route.go

manual backport of https://github.com/openshift/hypershift/pull/4845 without the shared ingress fix since 4.16 never supported that

OCPBUGS-43104: label routes only when HCP router used

---

cmd/install/assets/hypershift_operator.go
cmd/install/install.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
support/config/constants.go

In ARO HCP deployments, a managed identity will be assigned to each AKS management cluster. This managed identity will be responsible for pulling out the secrets from any Azure Key Vault on the management cluster, such as the HCP component's managed identity's backing certificate.
Since there is a single managed identity doing this for all HostedClusters on a management cluster, it makes sense for this value to be passed to the HyperShift Operator (HO) installed on the management cluster. However, the control plane operator (CPO) also needs this value when it creates the SecretProviderClass for the Secrets Store CSI driver. 
This PR:
- adds a flag to the HO installation to pass the client ID of the previously mentioned managed identity
- passes the …

HOSTEDCP-1994: Pass Azure Key Vault's Managed Identity's Client ID to HO and CPO Deployments

---

control-plane-operator/controllers/hostedcontrolplane/oauth/config.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go

follow up fix to https://github.com/openshift/hypershift/pull/4852
After https://github.com/openshift/hypershift/pull/4852, we returned `nil` instead of the valid oauth config (without the invalid IDPs).  We want is a valid oauth config with the invalid IDPs removed.

OCPBUGS-38132: cpo: produce valid oauth config even if idp config is invalid

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
control-plane-operator/controllers/hostedcontrolplane/olm/deployments.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/olm/params.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
control-plane-operator/hostedclusterconfigoperator/operator/config.go
support/releaseinfo/registryclient/client.go
test/e2e/util/util.go

**What this PR does / why we need it**: removes hardcoded catalog images in CPO which have to be updated every release, we now retrieve the openshift version from the ocp payload
Fixes # [HOSTEDCP-1883](https://issues.redhat.com/browse/HOSTEDCP-1883)
**Checklist**

HOSTEDCP-1883: Remove hardcoded catalog images in CPO

---

control-plane-operator/controllers/hostedcontrolplane/manifests/secretproviderclass.go
support/azureutil/azureutil.go

Add generic create function for SecretProviderClass for ARO HCP. 
Example usage - https://github.com/openshift/hypershift/pull/4884.
Fixes #
**Checklist**

HOSTEDCP-1994: Add generic create function for SecretProvider

---

api/hypershift/v1beta1/openstack.go
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/OpenStack.yaml
client/applyconfiguration/hypershift/v1beta1/openstacknodepoolplatform.go
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-TechPreviewNoUpgrade.crd.yaml
cmd/nodepool/openstack/create.go
cmd/nodepool/openstack/create_test.go
docs/content/how-to/openstack/create-openstack-cluster.md
docs/content/reference/api.md
hypershift-operator/controllers/nodepool/capi.go
test/e2e/e2e_test.go
test/e2e/nodepool_osp_az_test.go
test/e2e/nodepool_test.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/openstack.go

In OpenStack NodePools, add the AZ option which will configure the Machine spec with the failure domain.
We need it because customers sometimes want to deploy their Nodepools in a given availability zone (e.g. east-1, west-1, etc). This patch enables that.

OCPBUGS-38357: openstack: add option to configure nodepool AZ

---

docs/content/how-to/openstack/create-openstack-cluster.md

This is needed for installing the operator to handle OpenStack clusters.

NO-JIRA: doc/openstack: install operator with `--tech-preview-no-upgrade`

---

api/hypershift/v1beta1/manual-override-crd-manifests/nodepools.hypershift.openshift.io/hypershift.openshift.io_nodepools_scale_subresource.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-Default.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-TechPreviewNoUpgrade.crd.yaml

While this should be generated by the tooling/marker, it's not atm https://github.com/openshift/api/issues/2075. This fixes the regression while the tooling is fixed
Fixes #
**Checklist**

OCPBUGS-43707: Add crd override for NodePool scale subresource

---

hypershift-operator/controllers/nodepool/conditions.go
hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/nodepool/nto.go

HOSTEDCP-1989: Move NTO reconcile logic into their own file

---

Dockerfile.control-plane

In order to get the Konflux CPO Application to be able to use the same containerfile as we use for ART, we need to parametrize the image references, keeping the current values as defaults. Then, the konflux tekton configuration can override.
Fixes #[HOSTEDCP-2046](https://issues.redhat.com//browse/HOSTEDCP-2046)
**Checklist**

HOSTEDCP-2046: Parametrize Control Plane Dockerfile

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Preserve_existing_resources.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Private_apiserver_connectivity__proxy_apiserver_address_is_unset.yaml
control-plane-operator/controllers/hostedcontrolplane/storage/assets/10_deployment-hypershift.yaml
control-plane-operator/controllers/hostedcontrolplane/storage/envreplace.go
control-plane-operator/hostedclusterconfigoperator/cmd.go

**What this PR does / why we need it**: fixes image registry overrides being used in data plane.
Prereq: https://github.com/openshift/cluster-network-operator/pull/2507
Fixes # [OCPBUGS-41365](https://issues.redhat.com/browse/OCPBUGS-41365)
**Checklist**

OCPBUGS-41365: use appropriate images to avoid overrides in dataplane

---

cmd/cluster/core/create.go
cmd/cluster/openstack/create_test.go
cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_default_creation_flags.yaml

Empty by default for backward compatibility, we can now configure the
Machine networks via the CLI.
This will become handy for the OpenStack platform, where when we let the
CAPI provider (namely CAPO) to handle the networks, we still need to
provide a machine network CIDR and using the CLI seems a consistent way
to do so.

NO-JIRA: cmd: add support to configure machine networts via CLI

---

test/e2e/nodepool_upgrade_test.go

**What this PR does / why we need it**: adding retry timeout to nodepoolUpgradeTest so it nodepool has enough time to set status.Version after node becomes ready
Fixes # [OCPBUGS-43943](https://issues.redhat.com/browse/OCPBUGS-43943)
**Checklist**

OCPBUGS-43943: add retry timeout to nodepoolUpgradeTest

---

hypershift-operator/controllers/nodepool/kubevirt.go

HOSTEDCP-1989: Prevent kubevirt from removing valid machine config condition

---

test/e2e/nodepool_upgrade_test.go
test/e2e/util/util.go

Starting from OpenShift 4.18, the container runtime on worker nodes has been changed to crun. This new test validates that all those worker nodes in this release version contain the correct runtime handlers.
Fixes #[HOSTEDCP-2000](https://issues.redhat.com/browse/HOSTEDCP-2000)

HOSTEDCP-2000: Add E2E test validating the node runtime

---

cmd/cluster/agent/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_availability_ones.yaml
cmd/cluster/core/create.go
cmd/cluster/core/create_test.go
cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_test_from_dvossel.yaml
cmd/cluster/none/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_default_creation_flags.yaml
cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/powervs/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml

Fix order rendering HCP objects, modified to be always first the Namespace, and the last ones the HC and NP. Covered with unit tests.
Fixes #[OCPBUGS-42422](https://issues.redhat.com/browse/OCPBUGS-42422)

OCPBUGS-42422: Fix order rendering HCP objects

---

api/hypershift/v1beta1/hostedcluster_conditions.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/oauth/config.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go
docs/content/reference/api.md
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

Manual backport of https://github.com/openshift/hypershift/pull/4969
Changes from parent PR:
* removed api change from `vendor` since we didn't vendor hypershift api in 4.15
* `SetStatusCondition` does not return if the condition changed in 4.15 so we unconditionally update the new condition on each reconcile

[release-4.15] OCPBUGS-44201: add ValidIDPConfiguration condition to report IDP config issues

---

cmd/cluster/azure/create.go

**What this PR does / why we need it**: removes hard dependency on kubeconfig when running hypershift --help
Fixes # [OCPBUGS-44221](https://issues.redhat.com/browse/OCPBUGS-44221)
**Checklist**

OCPBUGS-44221: remove hard dependcy on kubeconfig for hypershift CLI

---

test/e2e/nodepool_machineconfig_test.go
test/e2e/nodepool_nto_machineconfig_test.go

- removes namespace wide nodepool replica count checks on nodepool specific tests, this was causing false test failures because other tests in the same namespace failed eg [pull-ci-openshift-hypershift-main-e2e-aws-4-17/1852002020232269824 ](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/4996/pull-ci-openshift-hypershift-main-e2e-aws-4-17/1852002020232269824)
Fixes #
**Checklist**

NO-JIRA: remove namespace wide node check on nodepool specific tests

---

.tekton/control-plane-operator-4-17-pull-request.yaml
.tekton/control-plane-operator-4-17-push.yaml
Dockerfile.control-plane

Adds 4.17 CPO build Konflux pipeline configuration. We need it in order to get builds of CPO when there's CPO changes in the release-4.17 branch. These builds can then be used for CPO image overrides.
Fixes #[HOSTEDCP-2046](https://issues.redhat.com//browse/HOSTEDCP-2046)
**Checklist**

HOSTEDCP-2046: CPO 4.17 tekton builds

---

api/hypershift/v1beta1/hostedcluster_types.go
hypershift-operator/controllers/nodepool/capi.go
hypershift-operator/controllers/nodepool/capi_test.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

The MachineHealthCheck that is generated for node pools when autorepair is enable has NodeStartupTimeout currently hardcoded to 20 minutes. For bare metal instances, this may need to be set to a bigger value, as the instance is slower to join the cluster.
This commit exposes this parameter as annotation on the HostedCluster and/or NodePool, with NodePool level annotation which will take precedence. This is aligned with the annotation already exposed for the readiness timeout.
Change covered by unit testing.
**Checklist**

OCM-12313: expose NodeStartupTimeout in MHC as annotation in HC/NP

---

Dockerfile.e2e
cmd/cluster/azure/create.go
cmd/infra/azure/create.go

- add az cli to e2e dockerfile
- We need to add the az cli to the e2e dockerfile so that we can execute the az cli commands for creating SPs during the e2e
Fixes # [HOSTEDCP-2070](https://issues.redhat.com/browse/HOSTEDCP-2070)
**Checklist**

HOSTEDCP-2070: add az cli to e2e dockerfile

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/kas/admissionpolicies.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/nodepool/nto.go
hypershift-operator/controllers/nodepool/nto_test.go
test/e2e/nodepool_mirrorconfigs_test.go
test/e2e/nodepool_test.go
test/e2e/util/util.go

Adding capability for HCCO to copy KubeletConfig objects to the Hosted-Cluster in a ConfigMap.
This is needed for a day-2 operators like NUMA-Resources-Operator to function properly.
Implementation of enhancement: https://github.com/openshift/enhancements/blob/master/enhancements/hypershift/topology-aware-scheduling/topology-aware-scheduling.md 
Fixes: [CNF-14742](https://issues.redhat.com/browse/CNF-14742)
**Checklist**

CNF-14742: HCCO: copy KubeletConfigs to hosted-cluster

---

control-plane-operator/controllers/hostedcontrolplane/cloud/openstack/providerconfig.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack.go

When we introduced the support for providing the external network ID, we
used pointers and this is causing pointer nil issues when the user
doesn't provide the external network ID (which is a valid use case).
For that, I refactored a few function's signatures (and I did it in the
same way as it was done for the v2 controllers to ease readability).

OCPBUGS-44375: openstack: make external network ID really optional

---

control-plane-operator/controllers/hostedcontrolplane/pki/kas.go

The managed-cluster-validating-webhooks that are deployed to rosa clusters are preventing the HCCO from updating certain resources including ingress.config.openshift.io. This is because they have a list of privileged users and groups that are allowed. We recently changed the user for the HCCO to system:hosted-cluster-config which is not considered a privileged user.
This commit adds "system:serviceaccounts:openshift" as an organization to the certificate of the system:hosted-cluster-config user. Kubernetes considers any organizations specified in the certificate subject as the groups to which the subject belongs, effectively making
system:hosted-cluster-config a member of the system:serviceaccounts:openshift group, which is one of the accepted …

OCPBUGS-44473: Add openshift to the groups of system:hosted-cluster-config

---

cmd/cluster/azure/destroy.go
cmd/cluster/core/destroy.go
cmd/infra/azure/destroy.go

-  adds --skip-service-principal-deletion flag to remove az cli dependency when deleting clusters
Fixes #
**Checklist**

OCPBUGS-44041: add --skip-service-principal-deletion flag

---

test/e2e/nodepool_osp_multinet_test.go

This feature was only added in 4.18 so let's skip the test otherwise.

NO-JIRA: e2e: skip OSP multinet before 4.18

---

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
control-plane-operator/main.go

Before this commit, the private link controller was assuming the same role for all cloud operations in a shared VPC infrastructure. In order to support the topology in which private hosted zones are created in the cluster account and not in the VPC owner account, the private link controller will now use the ingress role for route53 operations and only use the shared control plane operator role for vpc endpoint operations. This allows customers to create the ingress role in the account where the private hosted zones live, and the ingress role can be used to manage dns records by both the ingress operator and the private link controller.
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, …

OCPBUGS-44476: Use ingress role in private link controller for DNS operations

---

api/hypershift/v1beta1/azure.go
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/AAA_ungated.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/OpenStack.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-Default.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-TechPreviewNoUpgrade.crd.yaml
docs/content/reference/api.md
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/azure.go

**What this PR does / why we need it**: this is causing issues as capz expects these values https://github.com/openshift/cluster-api-provider-azure/blob/711d907f6902cdca76f675f5a5f19bb96423c24e/vendor/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v5/constants.go\#L616"
Fixes # [OCPBUGS-44568](https://issues.redhat.com/browse/OCPBUGS-44568)
**Checklist**

OCPBUGS-44568: update diskStorageAccountType consts

---

hypershift-operator/controllers/nodepool/nodepool_controller.go

**What this PR does / why we need it**: Allows for skipping NP image validation, we currently don't do this and when pre testing 4.19 payloads it causes failures.
Fixes # https://issues.redhat.com/browse/[OCPBUGS-44689](https://issues.redhat.com/browse/OCPBUGS-44689)
**Checklist**

OCPBUGS-44689: skip np image validation when skipReleaseImageValidation annotation is present on HC

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go

**What this PR does / why we need it**: to fix registry overrides in the dataplane a new controlPlaneCli image was added to distinguish between the two, I forgot to update the init container to use the new controlplane image so registryOverrides wouldn't have been working on the init containers because of this.
Fixes # [OCPBUGS-41365](https://issues.redhat.com/browse/OCPBUGS-41365)
**Checklist**

OCPBUGS-41365: use controlplaneCLI image in CNO init containers

---

HACKING.md
control-plane-operator/controllers/hostedcontrolplane/cloud/config.go
control-plane-operator/controllers/hostedcontrolplane/cloud/openstack/providerconfig.go
control-plane-operator/controllers/hostedcontrolplane/cloud/openstack/providerconfig_test.go
control-plane-operator/controllers/hostedcontrolplane/cloud/openstack/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/manifests/openstack.go
control-plane-operator/controllers/hostedcontrolplane/storage/assets/10_deployment-hypershift.yaml
control-plane-operator/controllers/hostedcontrolplane/storage/envreplace.go
control-plane-operator/controllers/hostedcontrolplane/testdata/cloud-controller-manager-openstack/zz_fixture_TestControlPlaneComponents_component.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/cloud-controller-manager-openstack/config-secret.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/cloud-controller-manager-openstack/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/openstack/component.go
control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/openstack/config.go
control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/openstack/config_test.go
control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/openstack/deployment.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
docs/content/contribute/develop_in_cluster.md
hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack.go
support/globalconfig/infrastructure.go
test/e2e/util/util.go

Enable the Cluster Storage Operator for the OpenStack platform, enabling storage.
Fixes [OSASINFRA-3636](https://issues.redhat.com//browse/OSASINFRA-3636)
**Checklist**
**Testing notes**
This has been manually tested using a release image built (by cluster-bot) with this PR and the other two below (URL exported as `RELEASE_IMAGE`) along with a custom `hypershift-operator` image. Initial deployment on a 4.17.2 management cluster was done like so:
```bash
❯ cd hypershift
❯ HYPERSHIFT_IMAGE="ghcr.io/stephenfin/hypershift-operator:latest"
❯ podman build -t "${HYPERSHIFT_IMAGE}" -f …
```

OSASINFRA-3636: Enable cluster-storage-operator for OpenStack Cinder

---

hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go

This was enabled by default here https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4969/files#diff-bd8758c39c0deb35ee6c5c387594f6575580918777fbf2926f5762c7c9fce755L68
We don't install these CRDs hence the controllers complain.
Fixes #
**Checklist**

NO-JIRA: Disable ASOAPI feature gate for CAPz

---

control-plane-operator/controllers/hostedcontrolplane/storage/assets/10_deployment-hypershift.yaml
control-plane-operator/controllers/hostedcontrolplane/storage/envreplace.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack.go
test/e2e/util/util.go

This PR enables the Manila CSI integration to Hypershift. It reconciles the OpenStack credentials needed by Manila and defines the `MANILA_DRIVER_CONTROL_PLANE_IMAGE`.
Related Changes:
-  https://github.com/openshift/csi-operator/pull/312
-  https://github.com/openshift/cluster-storage-operator/pull/527

OSASINFRA-3639: Enable cluster-storage-operator for OpenStack Manila

---

api/hypershift/v1beta1/openstack.go
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
client/applyconfiguration/hypershift/v1beta1/openstackplatformspec.go
cmd/cluster/openstack/create.go
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/params.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile_test.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/ingress.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
docs/content/how-to/openstack/create-openstack-cluster.md
docs/content/reference/api.md
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/openstack.go

Leverage a new feature in the Cluster Ingress Operator where we can now pre-define a floating IP for the Default Ingress Controller.
This will allow customers to pre-create a floating IP, update their DNS and then deploy a HostedCluster. This floating IP will be the load balancer IP for the `router-default` Service created by the Ingress controller.
Feature: [OSASINFRA-3644](https://issues.redhat.com//browse/OSASINFRA-3644)
Note: this contains a workaround commit that will be reverted as soon as we bump openshift/api here.

OSASINFRA-3644: openstack: allow to pre-define a floating IP for Ingress router-default

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
control-plane-operator/controllers/hostedcontrolplane/manifests/azure.go
control-plane-operator/controllers/hostedcontrolplane/manifests/secretproviderclass.go
control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/secretproviderclass/secretproviderclass.go
control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/azure/config.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
support/azureutil/azureutil.go
support/config/constants.go

Reconcile the SecretProviderClass for the image registry operator for ARO HCP deployments. The SecretProviderClass is used by the Secrets Store CSI driver to mount a certificate to a volume in the image registry pod deployment.
Fixes #
**Checklist**

HOSTEDCP-2022: Reconcile SecretProviderClass for Image Registry on ARO HCP

---

test/e2e/util/util.go

**What this PR does / why we need it**: increases the time allowed for node pool config to start updating to 1 minute. We've seen a lot of flakes around this and have [Jira](https://issues.redhat.com/browse/OCPBUGS-43824) to investigate further. This is also causing trouble for external teams trying to merge PRs before the feature freeze. 
Fixes #
**Checklist**

NO-JIRA: bump nodepoolConfigUpdate start timeout to 1min to reduce flakes

---

cmd/cluster/aws/create.go
cmd/cluster/aws/destroy.go
cmd/cluster/core/destroy.go
cmd/infra/aws/create.go
cmd/infra/aws/create_iam.go
cmd/infra/aws/destroy.go
cmd/infra/aws/destroy_iam.go
cmd/infra/aws/ec2.go
cmd/infra/aws/iam.go
cmd/infra/aws/route53.go

Adds a flag `--private-zones-in-cluster-account` to the following commands: hypershift create infra aws
hypershift create iam aws
hypershift create cluster aws
hypershift destroy infra aws
hypershift destroy iam aws
hypershift destroy cluster aws
The flag enables private hosted zones to be created in the cluster creator account in a shared vpc infrastructure.
Fixes #[HOSTEDCP-2178](https://issues.redhat.com/browse/HOSTEDCP-2178)
**Checklist**

HOSTEDCP-2178: Add CLI flag to support shared vpc private zones in cluster account

---

.pre-commit-config.yaml
Containerfile.control-plane
hack/tools/git-hooks/cpo-containerfiles-in-sync.sh

ART machinery checks that the FROM images are consistent in the release payload. Since the Control Plane Operator does go in the release payload, the work I did to have the FROM image references be parametrized for Konflux, trips it up.
This PR separates the container files into:
- Containerfile.control-plane: For Konflux, using RH catalog/brew
- Dockerfile.control-plane: For ART/release-payload
To help developers avoid the situation where one changes one but not the other, this commit adds a git pre-commit hook that enforces the only differences to be in the "^FROM" lines.
In order to install this pre-commit hook, one can run:
pipx install pre-commit
pre-commit install
Then, any new commit that the developer attempts will have to conform to the new …

OCPBUGS-44326: Separate CPO containerfiles

---

test/e2e/util/util.go

The name of the operator pod is `manila-csi-driver-operator`.
This will fix e2e for `e2e-openstack`.

OCPBUGS-44929: e2e: fix manila CSI operator

---

cmd/cluster/azure/create.go
cmd/infra/azure/create.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/azure/config.go
hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
support/azureutil/azureutil_test.go
test/e2e/e2e_test.go

Reconcile the SecretProviderClass for the ingress operator for ARO HCP deployments. The SecretProviderClass is used by the Secrets Store CSI driver to mount a certificate to a volume in the ingress pod deployment.
Fixes [OCPBUGS-44964](https://issues.redhat.com/browse/OCPBUGS-44964)
**Checklist**

OCPBUGS-44964: Reconcile SecretProviderClass for Ingress on ARO HCP

---

hypershift-operator/controllers/scheduler/placeholders.go
hypershift-operator/controllers/scheduler/placeholders_test.go

Before this commit, the placeholder controller looked at nodes with hosted cluster labels to determine which fleet manager labels it should exclude for placeholders. However, in the case when a hostedcluster control plane is cleaned up, but the HostedCluster CR itself has not been deleted due to the controlplane namespace not getting cleaned up, there are no longer any nodes with the hostedcluster label, but the hostedcluster is still associated with a particular pair label. Placeholder pods are not prevented from landing on nodes with this same pair label. These nodes cannot be used to allocate to a new HostedCluster because they are still associated with previous HostedCluster. This change modifies the placeholder controller to use the pair …

OCPBUGS-44957: Use fleet manager configmaps to determine placeholder pod node antiaffinity

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
docs/content/how-to/openstack/create-openstack-cluster.md

For platforms where cluster-image-registry-operator (CIRO) needs a PVC to be created, bootstrap needs to happen
in CIRO before the registry config is created. For now, this is the case for the OpenStack platform.
If the object exist, we reconcile the registry config for other other fields as it should be fine since the PVC would
exist at this point.
This patch will maintain a list of platforms that require a PVC for CIRO
(OpenStack only for now), check whether an image registry config already
exist and if it does, skip reconcile to let CIRO bootstrap doing it and
creating the needed PVC for CIRO.

OCPBUGS-44910: openstack: don't reconcile image registry config during bootstrap

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go

Reconcile the SecretProviderClass for the cluster network operator for ARO HCP deployments. The SecretProviderClass is used by the Secrets Store CSI driver to mount a certificate to a volume in the ingress pod deployment.
Fixes [OCPBUGS-44967](https://issues.redhat.com/browse/OCPBUGS-44967)
**Checklist**

OCPBUGS-44967: Reconcile SecretProvider for CNCC on ARO HCP

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/pki.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go

The openshift controller manager operator syncs the CA bundle that was configured in the global proxy config into a configmap in the openshift-controller-manager namespace. This configmap is then used by the build controller to generate the CA that is mounted into builds for registry access. Because we don't run the controller manager operator in hypershift, this needs to be done by the HCCO. This code adds the reconciliation to the HCCO so that it puts the configmap in the right location.
Ref: https://github.com/openshift/cluster-openshift-controller-manager-operator/blob/08c64512c055ae246b3a14f6d1088d39988c44fe/pkg/operator/usercaobservation/user_ca_observation_controller.go#L80-L90
**Which issue(s) this PR fixes** *(optional, use `fixes …

OCPBUGS-44380: Reconcile proxy CA bundle into hosted cluster

---

cmd/cluster/azure/create.go
cmd/infra/azure/create.go
test/e2e/e2e_test.go
test/e2e/util/fixture.go

This or adds a flag that we can use while executing the e2e in ci. The addition of this flag will allow us to pass in precreated SP and certs along with keyvault information that will then be used to populate the control plane managed identities field in the HC.
Fixes #
**Checklist**

HOSTEDCP-2193: allow reuse of SP for e2e

---

control-plane-operator/controllers/hostedcontrolplane/cloud/azure/providerconfig.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/storage/azure.go
control-plane-operator/controllers/hostedcontrolplane/storage/operator.go
control-plane-operator/controllers/hostedcontrolplane/storage/params.go

Reconcile the SecretProviderClass for the cluster storage operator (CSO) for ARO HCP deployments. The SecretProviderClass is used by the Secrets Store CSI driver to mount a certificate to a volume in the azure-disk-csi-controller and azure-file-csi-controller pod deployments.
Fixes [OCPBUGS-44968](https://issues.redhat.com/browse/OCPBUGS-44968)
**Checklist**

OCPBUGS-44968: Reconcile SecretProvider for CSO on ARO HCP

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go

This is causing a hot rollout of the `oauth-openshift` deployment leading to a very high flake rate in CI.
Hot change is the addition/removal of the `hypershift.openshift.io/kubeadmin-secret-hash` annotation that is added by the HCCO and apparently stomped by the new reconciliation logic.

NO-JIRA: cpov2: revert oauth reconciliation

---

hypershift-operator/controllers/nodepool/nodepool_controller.go
hypershift-operator/controllers/nodepool/nodepool_controller_test.go
support/supportedversion/version.go
support/supportedversion/version_test.go

This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/4657

[release-4.16] OCPBUGS-39372: Fixed NodePool version validation

---

test/e2e/util/util.go

* In `EnsurePodsWithEmptyDirPVsHaveSafeToEvictAnnotations`, we need both
`openstack-manila-csi` and `manila-csi-driver-controller`.
See: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_hypershift/5200/pull-ci-openshift-hypershift-main-e2e-openstack/1862228917390151680/artifacts/e2e-openstack/hypershift-openstack-e2e-execute/artifacts/TestCreateCluster/namespaces/e2e-clusters-whcqh-example-nqcr9/apps/deployments/openstack-manila-csi-controllerplugin.yaml
for an example. We were missing `openstack-manila-csi`.
* In `EnsureSATokenNotMountedUnlessNecessary`, we need to add
`csi-driver` and `csi-driver-nfs`. See:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/ …

OCPBUGS-45189, OCPBUGS-45182: e2e/openstack: adjustments for missing manila apps & pods

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
support/config/constants.go

Pass only the certificate name for the CNO deployment for managed Azure.
CNO uses its own certificate path here, https://github.com/openshift/cluster-network-operator/blob/7736bfe37f1276f771fcef03077f6d840eb6b862/pkg/network/cloud_network.go#L23.
This is combined with the certificate name here, https://github.com/openshift/cluster-network-operator/blob/7736bfe37f1276f771fcef03077f6d840eb6b862/pkg/network/cloud_network.go#L111.
Fixes OCPBUGS-44967
**Checklist**

OCPBUGS-44967: Pass only the certificate name for CNO deployment

---

docs/content/how-to/openstack/create-openstack-cluster.md

LB has to be functional on the mgt cluster for kube-api.

NO-JIRA: openstack/doc: add a requirement for Octavia

---

control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go
control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert_test.go

Before this change, if a custom CA was configured for either the proxy or a particular IDP, the CPO client would get built with an empty bundle that only included the specified CAs but not the system trust bundle. This prevented connections to IDP endpoints with publicly trusted certificates. This changes the https client for IDP endpoins in the CPO to include the system trust bundle in the CAs it trusts.
Fixes #[OCPBUGS-44236](https://issues.redhat.com/browse/OCPBUGS-44236)
**Checklist**

OCPBUGS-44236: Use system trust bundle in CPO IDP https client

---

test/e2e/util/util.go

NO-JIRA: e2e: followup cleanup for OpenStack Manila

---

control-plane-operator/controllers/hostedcontrolplane/kcm/deployment.go
control-plane-operator/controllers/hostedcontrolplane/kcm/params.go

Follow-up to https://github.com/openshift/hypershift/pull/4786
The Kubernetes controller manager default for node monitor grace period is not sufficient to avoid node readiness flaps during brief connectivity problems. Change is restricted to IBMCloud only.
Fixes #https://issues.redhat.com/browse/OCPBUGS-42338
**Checklist**

OCPBUGS-42338: Update KCM node monitor grace period

---

test/e2e/e2e_test.go
test/e2e/nodepool_osp_az_test.go

In some environments, we'll want to change the name of the availability
zone where the nodepool AZ will be tested on.
Let's allow that with this change.

NO-JIRA: openstack/e2e: allow to change AZ name

---

ignition-server/controllers/tokensecret_controller.go
ignition-server/controllers/tokensecret_controller_test.go

This patch addresses the issue of excessive patch attempts in a short period, which could overwhelm the KAS in the control plane.  A new safeguards have been implemented to prevent this scenario which involves a conditional check before executing patch commands that could potentially flood the API.  
Fixes #[OCPBUGS-42320](https://issues.redhat.com/browse/OCPBUGS-42320)

OCPBUGS-42320: Prevent IgnitionServer from flooding the API server with patch requests

---

.pre-commit-config.yaml
Makefile
docs/content/contribute/index.md
docs/content/contribute/release-process.md
docs/content/how-to/agent/create-agent-cluster.md
docs/content/how-to/automated-machine-management/scale-to-zero-dataplane.md
docs/content/how-to/aws/shared-vpc.md
docs/content/how-to/kubevirt/configuring-storage.md
docs/content/how-to/kubevirt/create-kubevirt-cluster.md
docs/content/how-to/powervs/create-cluster-powervs.md
docs/content/how-to/powervs/create-infra-separately.md
docs/content/reference/api.md
support/azureutil/azureutil_test.go
support/controlplane-component/README.md
support/controlplane-component/defaults.go
test/e2e/nodepool_kv_advanced_multinet_test.go

This PR:
- reduces the unit test runtime by ~90% from my tests locally
- reduces the CI runtime by ~72%*
- fixes some minor codespelling mistakes picked up by `pre-commit` hooks
_\*calculated from 8 runs of this PR vs 8 successful runs of the unit tests without this PR_
---
The majority of the time reduction is due from taking count from 25 to 1. Setting this value to 1 ensures all the unit tests are always run.
```
% go help testflag
...
-count n
Run each test, benchmark, and fuzz seed n times (default 1).
If -cpu is set, run n times for each GOMAXPROCS value.
Examples are always run once. -count does not apply to
fuzz tests matched by -fuzz.
```
This PR also sets the parallel flag on unit tests according to the number of cores on the machine …

HOSTEDCP-2206: Improve Unit Test Runtime

---

contrib/cleanzones/Dockerfile
contrib/cleanzones/go.mod
contrib/cleanzones/go.sum
contrib/cleanzones/main.go
contrib/cleanzones/manifests/01-serviceaccount.yaml
contrib/cleanzones/manifests/02-cronjob.yaml
contrib/cleanzones/role-policy.json

This utility is now installed in the `hypershift` namespace of the root CI cluster and a CronJob (daily) to clean up CI related hosted zones and records from the `ci` and `service.ci` zones.  The intent is to be non-disruptive to running tests by extracting the list of infraIDs in-use from the VPC list, then use that to find CI related zones/records that don't match an in-use infraID and remove them.

NO-JIRA: contrib: update route53 zone cleaning utility

---

api/hypershift/v1beta1/hostedcluster_types.go
cmd/cluster/aws/create.go
cmd/infra/aws/create.go
hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws_test.go
hypershift-operator/controllers/nodepool/aws.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

Adds a new flag to create cluster aws and create infra aws that enables the creation of a HostedCluster that only uses public subnets for machines. Adds annotation to HostedCluster to indicate that we want machines to be created in a public subnet and get assigned a public IP.
Fixes #[HOSTEDCP-2203](https://issues.redhat.com/browse/HOSTEDCP-2203)
**Checklist**

HOSTEDCP-2203: Add support for public only AWS clusters

---

cmd/cluster/aws/create.go
test/e2e/e2e_test.go

In order to save on nat gateway costs, this change will switch the default configuration of AWS hosted clusters created for e2e tests to use public IPs for ec2 instances and communicate through the internet gateway.
Fixes #[HOSTEDCP-2203](https://issues.redhat.com//browse/HOSTEDCP-2203)
**Checklist**

HOSTEDCP-2203: Create e2e clusters with public IP instances only

---

.pre-commit-config.yaml

This PR allows multiple yaml definitions to be specified within a single yaml file in the pre-commit check for yaml syntax. The check defaults to only one yaml definition per yaml file without this PR.
Here's an example of what happens without this commit:
```
Check for merge conflict strings.........................................Passed
Check yaml syntax........................................................Failed
- hook id: check-yaml
- exit code: 1
expected a single document in the stream
in "cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_create_with_a_ure_marketplace_image.yaml", line 1, column 1
but found another document
in "cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_create_with_a_ure_marketplace_image.yaml", line 8, …
```

NO-JIRA: Allow multiple yaml def in a file for pre-commit

---

.ci-operator.yaml
Dockerfile
Dockerfile.control-plane
Dockerfile.dev
Dockerfile.e2e

This PR:
- Manually fixes the rebase issue with https://github.com/openshift/hypershift/pull/5237
- Updates the rest of our development Dockerfiles to use the same builder image
Fixes #
**Checklist**

OCPBUGS-45595: Updating ose-hypershift-container image to be consistent with ART for 4.19

---

support/konnectivityproxy/dialer.go

Before this commit, the konnectivity proxy dialer relied on the connectDirectlyToCloudAPIs boolean to determine whether it should connect directly to hostnames that matched the known cloud API suffixes. However, the resolver used by the dialer was always doing a control plane resolve of the hostnames with cloud API suffixes regardless of the connectDirectlyToCloudAPIs setting. This commit updates the behavior so that both dialer and resolver connect to cloud APIs in the same way.
Fixes # [OCPBUGS-44314](https://issues.redhat.com/browse/OCPBUGS-44314)
**Checklist**

OCPBUGS-44314: Consistently look up and dial cloud API hostnames

---

cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_availability_ones.yaml
cmd/nodepool/azure/create.go

- setting diskSotrageAccountType so that if the validation on the nodepool for this changes it will be caught in the e2e
Fixes #
**Checklist**

NO-JIRA: set diskStorageAccountType in aks e2e

---

docs/content/how-to/openstack/create-openstack-cluster.md
hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack.go
hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack_test.go

By default, OpenStack resources created by CAPI will be tagged (in the
OpenStack way) with `openshiftClusterID=<infraID>`.
`openshiftClusterID` is a well-known tag prefix in ShiftOnStack IPI.
Additional tags can be added via the `HostedCluster.Spec.Platform.OpenStack.Tags` field
when creating the HostedCluster with a given YAML file.

OSASINFRA-3685: openstack: tag CAPI resources with InfraID

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/storage/azure.go

This PR:
- removes the double reconciliation of the CSO CSI secrets for managed azure deployments. Previous to the managed identity work merging into the HyperShift repo, we were reconciling the CSO CSI secrets with the Cloud Provider information. Once the managed identity work was added, the reconciliation with the Cloud Provider information wasn't removed.
- adds the file path with the certificate name for the CSO CSI secret reconciliation for managed azure deployments.
Fixes ssue(s) this PR fixes :
Fixes # [OCPBUGS-46483](https://issues.redhat.com/browse/OCPBUGS-46483) …

OCPBUGS-46483: Correctly Reconcile CSO CSI Secrets for Managed Azure Deployments

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
hypershift-operator/controllers/hostedcluster/karpenter.go
karpenter-operator/controllers/karpenter/manifests.go
karpenter-operator/manifests/operator.go
support/releaseinfo/registryclient/client.go
support/util/imagemetadata.go

This pull request:
- fixes some codespelling errors
- gets the latest HCP into memory before we update the Valid Release Image status
Fixes [CNTRLPLANE-25](https://issues.redhat.com/browse/CNTRLPLANE-25)
**Checklist**

CNTRLPLANE-25: Fix valid release image update issue

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/network_policies.go

Using a hostname at NodePort service strategy is allowed by the api but the kubevirt provider breaks trying to check if it's an ipv4 or ipv6 to populate a network policy, this change skip that network policy because hostname would be an external address so no network policy is needed.
Fixes #OCPBUGS-46529
**Checklist**

OCPBUGS-46529: kubevirt, Don't break on hostname NodePort.Address

---

.tekton/hypershift-operator-main-pull-request.yaml

Due to capacity issues in s390x environment, we're instructed to stop building images on PR for s390x
**Checklist**

CNTRLPLANE-26: Disable building HO for s390x platform on PR

---

test/e2e/util/util.go

This is reverting a small change done in https://github.com/openshift/hypershift/pull/5168 in order to fix the Upgrade tests on E2E. `hostedCluster.Status.Version` is mirrored up from the CVO and doesn't propagate immediately, so we need to verify the image we pass to `WaitForImageRollout` is present in the status before we check any other thing.
https://github.com/openshift/hypershift/pull/5168/files#diff-cebde6b83b4b372162b2c6a22710a4ab0b1838576120535593a66a3a9bdfc170

NO-JIRA: Revert E2E test change which validates the CVO Image propagation

---

hypershift-operator/controllers/nodepool/nto.go
hypershift-operator/controllers/nodepool/nto_test.go

Fixes [OCPBUGS-46354](https://issues.redhat.com/browse/OCPBUGS-46354)
Observed errors:
```
{"level":"error","ts":"2024-12-07T12:38:02Z","msg":"Failed to reconcile NodePool","controller":"nodepool","controllerGroup":"hypershift.openshift.io","controllerKind":"NodePool","NodePool":{"name":"30734861-mynodepool","namespace":"master"},"namespace":"master","name":"30734861-mynodepool","reconcileID":"a994e171-39d8-4ebe-b36d-d5bf3b32f91c","error":"failed to reconcile NTO: failed to build mirror configs: configmap \"ignition-config-98-ibm-machineconfig-roks-30734861\" yaml document failed validation: error decoding config: no kind \"ImageDigestMirrorSet\" is registered for version \"config.openshift.io/v1\" in scheme …
```

OCPBUGS-46354: fix(ho): Add all supported config schemas for NodePool NTO reconcile

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go

This pull request gets the latest HCP into memory before we update the Valid Release Image status
Fixes #
**Checklist**

CNTRLPLANE-25: Get HCP before Valid Release Image status patch

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
control-plane-operator/controllers/hostedcontrolplane/testdata/oauth-openshift/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/oauth-openshift/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/oauth/component.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
test/e2e/util/oauth.go

This avoids the conflict between HCCO and CPO reconciling the same deployment. All HCP components reconciliation should be done in the CPO
Fixes #
**Checklist**

NO-JIRA: Move oauth kubeadminsecret hash annotation logic from HCCO to CPO

---

cmd/cluster/core/create.go

In many disconnected environments, the execution environment may not have access to the payload image. Adjust the multi-arch check logic to skip the check when the payload is inaccessible.
Fixes [OCPBUGS-47715](https://issues.redhat.com/browse/OCPBUGS-47715)
**Checklist**

OCPBUGS-47715: fix disconnected via CLI

---

Dockerfile.dev
Makefile
control-plane-pki-operator/certificates/conditions.go
karpenter-operator/controllers/karpenter/karpenter_controller.go
karpenter-operator/controllers/karpenter/machine_approver.go
karpenter-operator/controllers/karpenter/machine_approver_test.go
karpenter-operator/controllers/karpenter/manifests.go
karpenter-operator/main.go
karpenter-operator/manifests/operator.go

HOSTEDCP-2234: Karpenter auto machine approver

---

control-plane-operator/controllers/hostedcontrolplane/cloud/azure/providerconfig.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/storage/azure.go

Manual backport of https://github.com/openshift/hypershift/pull/5311
Fixes [OCPBUGS-46666](https://issues.redhat.com/browse/OCPBUGS-46666)
**Checklist**

[release-4.18] OCPBUGS-46666: Correctly Reconcile CSO CSI Secrets for Managed Azure Deployments

---

test/e2e/e2e_test.go

**What this PR does / why we need it**: This will allow us to set the azur marketplace settings on azure e2e which is what will be used in prod sector
Fixes # [CNTRLPLANE-68](https://issues.redhat.com/browse/CNTRLPLANE-68)
**Checklist**

CNTRLPLANE-68: add flags for setting azure marketplace images in e2e

---

control-plane-operator/controllers/hostedcontrolplane/storage/operator.go
control-plane-operator/controllers/hostedcontrolplane/storage/params.go

This is a manual cherrypick of:
- https://github.com/openshift/hypershift/pull/4904
Fixes OCPBUGS-45349
**Checklist**

[release-4.18] OCPBUGS-45349: CPO fails to reconcile the SecretProviderClass for CSO on ARO HCP

---

test/e2e/util/util.go

https://github.com/openshift/cluster-network-operator/pull/2612 broke our e2e because our assertions in `EnsureValidatingAdmissionPoliciesExists` make the assumption that the only VAPs in the guest cluster are ones that we create.
The PR refactors this check to:
* Not assume no other VAPs exist
* Not wait for VAPs to exist as this is called from `after()`, as in after the HostedCluster is fully deployed and the VAPs should already be created.  It is a bug if they are not created by the time the check runs.

NO-JIRA: test/e2e: improve VAP test assertions

---

support/util/imagemetadata.go
support/util/imagemetadata_test.go

**What this PR does / why we need it**: When an imageName is set with the SHA256 and the ICSP/IDMS does not contain a Tag but an ID, the reference image name is using the original name instead of the mirror one. This PR fixes that situation.
Fixes #[OCPBUGS-48152](https://issues.redhat.com/browse/OCPBUGS-48152)

OCPBUGS-48152: Fix mirror reference image name when ID is set

---

cmd/cluster/core/dump.go

help investigation CI failure on `ValidatingAdmissionPolicy` assertions

NO-JIRA: cmd: dump: include ValidatingAdmissionPolicies in guest cluster dump

---

docs/content/how-to/openstack/etcd-local-storage.md
docs/content/how-to/openstack/prerequisites.md

This PR documents how etcd can be put on LVM storage on the OpenStack platform.

OSASINFRA-3670: doc/openstack: etcd on LVM

---

control-plane-operator/controllers/hostedcontrolplane/cvo/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-version-operator/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-version-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/cvo/deployment.go

Most `rm` invocations already have `-f` but there a few that don't

OCPBUGS-48216: use rm -f in all CVO cmds for idempotency

---

test/e2e/util/util.go

OpenShiftPodSecurityAdmission feature gate is not enabled by default in 4.18. We need to stop EnsurePSANotPrivileged in 4.18.
https://github.com/openshift/api/blob/release-4.18/features/features.go
Fixes #
**Checklist**

NO-JIRA: Enforce EnsurePSANotPrivileged for 4.19 and later

---

.pre-commit-config.yaml

This commit adds `make lint-fix` to the pre-commit hook so imports are automatically sorted by gci before `make verify` is run in the pre-push hook.
Fixes #
**Checklist**

NO-JIRA: Add `make lint-fix` to pre-commit hook

---

docs/content/contribute/release-process.md

add a part to the doc to remind us to check that the correct version of the HO and e2e are being used on the new release branch after a release cut
Fixes #
**Checklist**

NO-JIRA: add information about checking HO and e2e are from main on latest release branch

---

control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/oauth.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go

The secrets/configmaps used to store TLS artifacts should have the same annotations as self-hosted version to match TLS registry. See https://github.com/openshift/enhancements/blob/master/enhancements/security/tls-artifacts-registry.md for more infotmation
Fixes #
**Checklist**

OCPBUGS-48506: Set ownership annotations for TLS artifacts

---

control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/daemonset.yaml

This PR pins `privileged` SCC for the `kubevirt-csi-node` in the `openshift-cluster-csi-drivers` namespace. Pinning ensures the workload explicitly uses the required SCC and prevents unintended security vulnerabilities.
This is part of the ongoing task to ensure SCC pinning for all workloads in platform namespaces .
**Which issue(s) this PR fixes:** 
Fixes [AUTH-482](https://issues.redhat.com/browse/AUTH-482) and [sippy test](https://sippy.dptools.openshift.org/sippy-ng/tests/4.19/analysis?test=%5Bsig-auth%5D%20all%20workloads%20in%20ns%2Fopenshift-cluster-csi-drivers%20must%20set%20the%20%27openshift.io%2Frequired-scc%27%20annotation&filters=%7B%22items%22%3A%5B%7B%22columnField%22%3A%22name%22%2C%22operatorValue%22%3A%22equals%22%2C%22value%22%3A%2 …

AUTH-482: set required-scc for openshift workloads

---

Makefile

This commit adds the GOWORK=off to the `clients` in the Makefile.
Fixes N/A
**Checklist**

NO-JIRA: Add GOWORK=off to clients in Makefile

---

api/hypershift/v1beta1/nodepool_types.go
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/AAA_ungated.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/OpenStack.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-Default.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-TechPreviewNoUpgrade.crd.yaml
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/nodepool_types.go

What this PR does / why we need it:
This PR allows the NodePool API to set ARM64 arch for deployments with None platform type.
Which issue(s) this PR fixes (optional, use fixes #<issue_number>(, fixes #<issue_number>, ...) format, where issue_number might be a GitHub issue, or a Jira story:
Fixes #[OCPBUGS-48510](https://issues.redhat.com/browse/OCPBUGS-48510)

OCPBUGS-48510: Allow ARM64 arch deployment on None platform type

---

cmd/infra/azure/create.go
control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/rbac.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go

This PR is part 4 of implementing workload identity for data plane components in managed Azure. Specifically this PR only includes changes to the CPO.
The PR for part 3 is - https://github.com/openshift/hypershift/pull/4587.
Fixes [HOSTEDCP-1542](https://issues.redhat.com/browse/HOSTEDCP-1542)
**Checklist**

HOSTEDCP-1542: Implement Workload Identity in Azure for Data Plane Components Part 4

---

cmd/infra/azure/create.go
control-plane-operator/controllers/hostedcontrolplane/storage/azure.go

- Correct ARO file csi driver cloud config and permissions.
Fixes # [OCPBUGS-48708](https://issues.redhat.com/browse/OCPBUGS-48708)
**Test record(Manually build the control plane operator image and replcaed in a live cluster verify it works)** 
https://jenkins-csb-openshift-qe-mastern.dno.corp.redhat.com/job/ocp-common/job/ginkgo-test/285274/console
```console
79 pass, 13 skip (46m1s)
```

OCPBUGS-48708: correct aro azureFile config and permissions

---

.golangci.yml
cmd/infra/aws/destroy.go
pkg/etcdcli/helpers.go
support/thirdparty/kubernetes/pkg/credentialprovider/config.go
support/thirdparty/library-go/pkg/image/registryclient/client.go
support/util/imagemetadata.go
test/e2e/nodepool_nto_constants.go
test/e2e/util/util.go

This PR:
- This commit enables unused and ineffassign in golangci-lint, which checks Go code for unused constants, variables, functions and types and ineffectual assignments respectively.
- Fixes the errrors found by those linters.
Fixes [HOSTEDCP-2176](https://issues.redhat.com/browse/HOSTEDCP-2176)
**Checklist**

HOSTEDCP-2176: Enable unused & ineffassign linters in golangci-lint

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/ingress/reconcile_test.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/ingress.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go

Remove some technical debt around the Ingress Floating IP reconcile for the OpenStack platform.

NO-JIRA: Remove OpenStack workaround for Ingress Floating IP

---

test/e2e/nodepool_kv_advanced_multinet_test.go

The multiple networks feature in the kubevirt platform has been introduced in 4.15, therefore we need to skip it for the e2e test running against v4.14 and below.
Need it order for https://github.com/openshift/hypershift/pull/5235 to pass CI.
Fixes # https://issues.redhat.com/browse/OCPBUGS-45559
**Checklist**

NO-JIRA: [kubevirt] Skip KubeVirtAdvancedMultinetTest for v4.14 and below

---

cmd/infra/azure/create.go

This PR adds the contributor role over VNET for Cloud Provider.
Fixes [OCPBUGS-48794](https://issues.redhat.com/browse/OCPBUGS-48794)
**Checklist**

OCPBUGS-48794: Adds contributor role over VNET for Cloud Provider

---

cmd/cluster/azure/create.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_availability_ones.yaml
cmd/infra/azure/create.go
control-plane-operator/controllers/hostedcontrolplane/cloud/azure/providerconfig.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go

This pull request removes client secret references for managed Azure since Workload identity is supported now.
Fixes [OCPBUGS-48688](https://issues.redhat.com/browse/OCPBUGS-48688)
**Checklist**

OCPBUGS-48688: Remove client secret references now Workload Identity is supported

---

cmd/cluster/azure/create.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_availability_ones.yaml
cmd/infra/azure/create.go
control-plane-operator/controllers/hostedcontrolplane/cloud/azure/providerconfig.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go

This is a manual backport of https://github.com/openshift/hypershift/pull/5455
Fixes #
**Checklist**

[release-4.18] OCPBUGS-48689: Remove client secret references now Workload Identity is supported

---

cmd/infra/aws/destroy_iam.go
cmd/infra/aws/ec2.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/karpenter.go
karpenter-operator/controllers/karpenter/karpenter_controller.go
karpenter-operator/controllers/karpenter/manifests.go
karpenter-operator/main.go
karpenter-operator/manifests/operator.go
test/e2e/assets/karpenter-nodepool.yaml
test/e2e/assets/karpenter-workloads.yaml
test/e2e/karpenter_test.go
test/e2e/util/util.go

https://github.com/openshift/hypershift/pull/5404 introduced e2e for karpenter
https://github.com/openshift/hypershift/pull/5461 reverted it because it was breaking periodics which run the HO without --tech-preview-no-upgrade
This PR re-enable the test with a check to only run when CI sets TECH_PREVIEW_NO_UPGRADE=true and the Hypershift Operator is installed with --tech-preview-no-upgrade
Fixes #
**Checklist**

PODAUTO-303: Re enable karpenter e2e

---

cmd/infra/azure/create.go

This PR assigns the appropriate roles for control plane identities where existing ARO HCP roles already exist for ARO HCP.
Fixes [CNTRLPLANE-173](https://issues.redhat.com/browse/CNTRLPLANE-173)
**Checklist**

CNTRLPLANE-173: Assign known ARO roles for CP IDs for ARO HCP

---

cmd/cluster/openstack/create.go
docs/content/how-to/openstack/hostedcluster.md
test/e2e/e2e_test.go
test/e2e/util/options.go

Allow the users to provide the DNS nameservers that will be used when
creating the OpenStack subnets.
In some environments where DNS forwarding is not enabled, the subnet
needs to have DNS nameservers for external resolution, otherwise the
Nodepools won't be able to e.g. reach the ignition endpoint.
This was already possible before by rendering the HostedCluster spec
first but now it's possible to do it via the CLI for a better UX, since
this option might be used by a majority of our customers.

OCPBUGS-48626: openstack: add DNS option to CLI

---

hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack.go

`metrics-bind-addr` was deprecated and is currently removed, we should
stop using it so we can bump the version of CAPI and CAPO.

OCPBUGS-49370: openstack: update CAPI provider deployment spec

---

api/hypershift/v1beta1/azure.go
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/AAA_ungated.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/nodepools.hypershift.openshift.io/OpenStack.yaml
client/applyconfiguration/hypershift/v1beta1/azurenodepoolplatform.go
cmd/cluster/azure/create.go
cmd/cluster/azure/create_test.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_create_with_a_ure_marketplace_image.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_availability_ones.yaml
cmd/infra/azure/create.go
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-Default.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/nodepools-TechPreviewNoUpgrade.crd.yaml
docs/content/reference/api.md
hypershift-operator/controllers/nodepool/azure.go
hypershift-operator/controllers/nodepool/azure_test.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/azure.go

This PR removes MachineIdentityID from the Azure HyperShift API, CLI, and NodePool controller. This field is not needed for ARO HCP.
Fixes [CNTRLPLANE-187](https://issues.redhat.com/browse/CNTRLPLANE-187)
**Checklist**

CNTRLPLANE-187: Remove MachineIdentityID from Azure HyperShift API

---

control-plane-operator/controllers/hostedcontrolplane/kas/config.go

This fix is required to unblock the payload jobs
Replicates https://github.com/openshift/cluster-kube-apiserver-operator/pull/1777/commits/dea2e4fb8faafda391789ed662916854f15b8dff

NO-JIRA: switch to resource.k8s.io/v1beta1 after kube 1.32 rebase

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/v2/cvo/deployment.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
ignition-server/controllers/local_ignitionprovider.go
support/util/imagemetadata.go
support/util/imagemetadata_test.go

After #5168, the release image passed to the CVO is an image with a digest (which is needed for offline). Because this doesn't always match the release image specified in the HostedCluster.spec.release.image field, code that relies on comparing the image in CVO status with what's in the spec is now not matching. One effect is that the Progressing condition remains set to "true" even if a HostedCluster has completed provisioning.
This PR makes the following changes in order to fix it:
- Adds code to the HyperShift operator to compare either the image in spec as is or converted to a digest with the image reported by the CVO in status.
- Removes the call to obtain the release image for a specific architecture when obtaining an image with digest for the …

OCPBUGS-48532: Fix IsProgressing condition in HostedClusters

---

cmd/infra/azure/create.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
hypershift-operator/controllers/hostedcluster/karpenter.go
test/e2e/karpenter_test.go

We should check if the assignServicePrincipal option has been set before assigning service principal roles using az cli. This causes a dependency on AZ cli when executing this command which can cause issues in CI.
Fixes #
**Checklist**

NO-JIRA: add assignServicePrincipal check before assignign roles to WI

---

Makefile
karpenter-operator/controllers/karpenter/assets/adjust-cel.sh
karpenter-operator/controllers/karpenter/assets/karpenter.k8s.aws_ec2nodeclasses.yaml
karpenter-operator/controllers/karpenter/karpenter_controller.go
karpenter-operator/manifests/operator.go

- Add ValidatingAdmissionPolicy for karpenter EC2NodeClass CRD to prevent updates to managed fields
- Relax CEL validations for EC2NodeClass CRD
- Default subnetSelectorTerms and securityGroupSelectorTerms if not set
Fixes #
**Checklist**

HOSTEDCP-2226: Add ValidatingAdmissionPolicy for karpenter EC2NodeClass CRD

---

control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/kas/config.go

Forgot to update CPOv2 code in https://github.com/openshift/hypershift/pull/5496

NO-JIRA: cpov2: switch to resource.k8s.io/v1beta1 after kube 1.32 rebase

---

control-plane-operator/controllers/hostedcontrolplane/konnectivity/params.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/params.go
support/config/deployment.go
support/config/probes.go

This PR adds readiness probe to Konnectivity agent on hosted user plane.
It is helpful to indicate pod readiness when the connection to Konnectivity server drops. In this case pod goes to "0/1 Running" status.
implementation: https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/485
Fixes #
**Checklist**

OCPBUGS-49611: Konnectivity: add agent readiness

---

.tekton/hypershift-release-414-pull-request.yaml
.tekton/hypershift-release-414-push.yaml
Dockerfile
go.mod

This PR fixes the broken `release-4.14` branch and incorporates:
-  #5158 and adds the required manual migration on top
- #5494 and bumps up go version to 1.20
**Checklist**

 [release-4.14] NO-JIRA: chore: update konflux references & bump up go version to 1.20

---

api/v1beta1/hostedcluster_conditions.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/oauth/config.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/idp_convert.go
docs/content/reference/api.md
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

Manual backport of #5037
- removed api change from vendor since we didn't vendor hypershift api in 4.
- SetStatusCondition does not return if the condition changed in 4.14 so we unconditionally update the new condition on each reconcile
**Checklist**

 [release-4.14] OCPBUGS-49405: add ValidIDPConfiguration condition to report IDP config issues

---

api/hypershift/v1beta1/azure.go
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AROHCPManagedIdentities.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AROHCPManagedIdentities.yaml
client/applyconfiguration/hypershift/v1beta1/managedidentity.go
cmd/cluster/azure/create.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_create_with_a_ure_marketplace_image.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_availability_ones.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
cmd/install/assets/hypershift_operator.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/secretproviderclass/secretproviderclass.go
control-plane-operator/controllers/hostedcontrolplane/secretproviderclass/secretproviderclass_test.go
control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/azure/config.go
control-plane-operator/controllers/hostedcontrolplane/v2/cno/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/storage/azure.go
docs/content/reference/api.md
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/azure.go

This PR:
- adds ObjectEncoding to the Azure API so one can specify how a secret is encoded
- adds the objectEncoding to SecretProviderClass params so the right decoding option can be used on the Azure Key Vault secret
Fixes #
**Checklist**

OCPBUGS-49686: Add ObjectEncoding to the Azure API and SecretProviderClass Reconciliation in the CPO

---

cmd/cluster/azure/create.go
cmd/infra/azure/create.go

A follow on to https://github.com/openshift/hypershift/pull/5469
We don't yet have built-in roles for the HCP components and that process might take a while.
In the meantime, we can exercise the limited permission set in custom roles that are manually created by the user before cluster creation.
The role names are
* `Azure Red Hat OpenShift Control Plane Operator Role` for the CPO
* `Azure Red Hat OpenShift NodePool Management Role` for CAPZ i.e. nodePoolManagement
Once these roles are built-in, we can safely assume the roles always exist and remove this flag.

CNTRLPLANE-172: cli: azure: allow assigning custom HCP roles

---

cmd/cluster/aws/create.go
cmd/cluster/core/create.go
cmd/infra/aws/create.go
cmd/infra/aws/ec2.go
cmd/infra/aws/proxyca.go
cmd/infra/aws/proxyconfig.go
cmd/util/sshkeys.go
cmd/util/util.go

Adds '--enable-secure-proxy' flag to 'hypershift create infra aws' and 'hypershift create cluster aws' commands.
The flag is similar to the existing '--enable-proxy' flag, except that it creates a proxy that exposes a ssl endpoint with custom serving certificate.
This is needed to automate testing of secure proxy use cases.
Fixes #[HOSTEDCP-2259](https://issues.redhat.com/browse/HOSTEDCP-2259)
**Checklist**

HOSTEDCP-2259: CLI: enable secure proxy creation

---

hypershift-operator/controllers/nodepool/kubevirt/kubevirt.go

If hostDevices.deviceName has multiple types, the generated hostDevices.name has duplicates.
when
```
apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
spec:
platform:
kubevirt:
hostDevices:
- count: 8
deviceName: nvidia.com/H20
- count: 4
deviceName: nvidia.com/NVSwitch
```
VirtualMachine
```
hostDevices:
- deviceName: nvidia.com/H20
name :hostdevice-1
- deviceName: nvidia.com/H20
name :hostdevice-2
- deviceName: nvidia.com/H20
name :hostdevice-3
- deviceName: nvidia.com/H20
name :hostdevice-4
- deviceName: nvidia.com/NVSwitch
name :hostdevice-1
- deviceName: nvidia.com/NVSwitch
name :hostdevice-2   
```
Fixes # https://issues.redhat.com/browse/OCPBUGS-49748
**Checklist**

OCPBUGS-49748: Duplicate hostDevices.name when hostDevices.deviceName has multiple types.

---

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/testdata/zz_fixture_TestReconcileOauthDeploymentNoChanges.yaml

When using the konnectivity-https-proxy sidecar to communicate through workers, the proxy dials any configured proxy directly and fails to connect if it cannot trust the proxy's serving certificate. This commit adds mounts for the trusted-ca-bundle-managed configmap to sidecar containers that run the konnectivity-https-proxy. The configmap contains the aggregate of .spec.additionalTrustBundle and
This fixes the issue of the ingress operator not becoming available when using a proxy with a custom certificate.
In addition it propagates any proxy environment variables that are set on the control plane operator to the konnectivity-https-proxy containers. This is needed when the management cluster itself requires a …

OCPBUGS-48619: Add HostedCluster additional trustbundles to konnectivity-https-proxy

---

control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-scheduler/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-scheduler/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-scheduler/deployment.yaml

**What this PR does / why we need it**: The scheduler's /livez endpoint is more appropriate for its liveness probe
Fixes #https://issues.redhat.com/browse/OCPBUGS-49791
**Checklist**

OCPBUGS-49791: Use /livez for kubernetes scheduler liveness probe

---

test/e2e/nodepool_mirrorconfigs_test.go

This was a bad copy paste but this test should not be skipped on
OpenStack.

NO-JIRA: e2e: don't skip mirrorconfigs on OSP

---

cmd/install/assets/hypershift_operator.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

fixes operator errors like:
> [operator-5cdcbcb4b7-4v2l2 operator] E0205 13:52:52.869331       1 reflector.go:158] "Unhandled Error" err="[sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:106](http://sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:106): Failed to watch *v1.SecretProviderClass: unknown (get [secretproviderclasses.secrets-store.csi.x-k8s.io](http://secretproviderclasses.secrets-store.csi.x-k8s.io/))" logger="UnhandledError"
Fixes #
**Checklist**

NO-JIRA: add watch permission to SecretProviderClass in ARO

---

api/hypershift/v1beta1/azure.go
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AROHCPManagedIdentities.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AROHCPManagedIdentities.yaml
client/applyconfiguration/hypershift/v1beta1/managedidentity.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_create_with_a_ure_marketplace_image.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_availability_ones.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
docs/content/reference/api.md
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/azure.go

This pull requests begins the phase 3 managed identity work for ARO HCP. This pull request:
- relaxes the API requirement to have a ClientID and CertificateName for any ManagedIdentity
- adds the CredentialsSecretName field which contains the name of the secret that contains the JSON format of a UserAssignedIdentityCredentials struct
Relaxing the previous API requirements should allow the HO to continue to work with phase 2 managed identity work as phase 3 work continues. In a later PR, ClientID and CertificateName will be removed and CredentialsSecretName will be required.
Fixes [CNTRLPLANE-109](https://issues.redhat.com/browse/CNTRLPLANE-109)
**Checklist**

CNTRLPLANE-109: Update Azure API for Phase 3 Managed Identity Work

---

control-plane-operator/controllers/hostedcontrolplane/scheduler/params.go
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-scheduler/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-scheduler/deployment.yaml

This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/5546

[release-4.18] OCPBUGS-49904: Use /livez for kubernetes scheduler liveness probe

---

Containerfile.control-plane
Containerfile.operator
Dockerfile
Dockerfile.control-plane

This PR aims to alleviate the memory issues that occur when building binaries due to memory exhaustion, likely caused by the AzureSDK imports.
Fixes #OCPBUGS-49609
**Checklist**

OCPBUGS-49609: Split binary builds

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws_test.go

specify cloud region in the AWS credentials profile for AssumeRoleWithWebIdentity passed to HCP operator roles (e.g. KAS kms-provider) when the HCP is deployed in a region that lies in the AWS govcloud partition. This is necessary because if the credentials don't specify a GovCloud partition in the profile, then a session is built pointing to the default non-GovCloud regions, and that client will be unable to see and authenticate to OIDC providers inside the GovCloud partition. See the ticket for specific error details and examples against the KubeAPIServer's kms-provider
Fixes #[CNTRLPLANE-221](https://issues.redhat.com//browse/CNTRLPLANE-221)
**Checklist**

CNTRLPLANE-221: specify region in AWS credentials for operator-roles

---

support/util/util.go

Honor proxy vars in the util insecure http client.
When replacing the default transport, we need to set the proxy field to net.http.ProxyFromEnvironment to honor proxy env vars. Otherwise, no proxy will be used if the *_PROXY env vars are set.
Here's the documentation of the `Proxy` field 
```go
// Proxy specifies a function to return a proxy for a given
// Request. If the function returns a non-nil error, the
// request is aborted with the provided error.
//
// The proxy type is determined by the URL scheme. "http",
// "https", "socks5", and "socks5h" are supported. If the scheme is empty,
// "http" is assumed.
// "socks5" is treated the same as "socks5h".
//
// If the proxy URL contains a userinfo subcomponent,
// the proxy request will pass the …
```

OCPBUGS-49913: Honor proxy vars in the util insecure http client

---

control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-controller-manager/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-scheduler/zz_fixture_TestControlPlaneComponents.yaml
support/config/featuregates.go

Follow on to #5566
Discovered that, while the FeatureGate cluster config within the guest cluster shows that `OpenshiftPodSecurityAdmission` feature gate is disabled, we do not use that for the feature gate configuration of components on the HCP.
In the guest cluster, we use the cluster-config-operator to set the FeatureGate status based on the feature set (the right thing to do).
For the HCP, we decode the feature gates ourselves from the vendored openshift/api (the wrong thing to do).  Our vendored o/api currently has `OpenshiftPodSecurityAdmission` in the Default FeatureSet so it is being set to true for the cluster-policy-controller running in the HCP.
This results in the `pod-security.kubernetes.io/enforce` being authoritatively set all the time, rendering the KAS config defaults …

OCPBUGS-45600: override OpenShiftPodSecurityAdmission featue gate to false for HCP components

---

karpenter-operator/controllers/karpenter/assets/adjust-cel.sh
karpenter-operator/controllers/karpenter/assets/karpenter.k8s.aws_ec2nodeclasses.yaml
karpenter-operator/controllers/karpenter/karpenter_controller.go
karpenter-operator/controllers/karpenter/karpenter_controller_test.go

In a hosted cluster with `autonode`, the role passed to the default `EC2NodeClass` that are given to instances/nodes are not required for instances to join the cluster. This PR relaxes the cel rule that requires the `role` field to be present in the EC2NodeClass custom resource and allows it to be changed.
Fixes https://issues.redhat.com/browse/PODAUTO-302
**Checklist**

PODAUTO-302: Relax cel rule for karpenter role to be required in an ec2NodeClass

---

docs/content/how-to/disaster-recovery/etcd-recovery.md

The outgoing line left the responsibility for the deletion ambiguous. Maybe the HyperShift operator had automated that deletion?  Maybe the admin had to manually delete, and the automation was just scoped to post-deletion recovery?  My incoming line is trying to make it clear that it's the latter, and that HyperShift is not involved in the Pod/PVC deletion that initiates recovery, even when `--enable-etcd-recovery` is true.
**Checklist**

NO-ISSUE: docs/content/how-to/disaster-recovery/etcd-recovery: Explicitly delegate to admin

---

karpenter-operator/controllers/karpenter/karpenter_controller.go
karpenter-operator/controllers/karpenter/karpenter_controller_test.go
karpenter-operator/main.go
test/e2e/karpenter_test.go

This commit implements supporting cascading deletion of karpenter provisioned nodes upon deletion of a hosted control plane. Also modifies the current Karpenter e2e test to test deletion of an HCP is not blocked by karpenter nodes, and adds a unit test.
Fixes https://issues.redhat.com/browse/PODAUTO-318
**Checklist**

PODAUTO-318: Implement HCP karpenter deletion

---

Containerfile.control-plane
Containerfile.operator
api/go.mod
go.mod
hack/tools/go.mod
hack/workspace/go.work
vendor/modules.txt

This PR 
- bumps Golang to 1.23 for the main go.mod, API go.mod, and hack/tools/go.mod
- updates the RHTAP Dockerfiles to Golang v1.23
N/A
**Checklist**

NO-JIRA: Bump Golang to 1.23

---

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go

this will ensure that clients build by these operators will point to the same AWS region that the HCP itself is deployed in when interacting with cloud resources.
This fixes an issue where HCP operators that use AssumeRoleWithWebIdentity credentials to interact with AWS cloud resources don't have the ability to see OIDC providers in the GovCloud partition, which means that these operators break when deployed in GovCloud.
Fixes #OCPBUGS-50578
**Checklist**

OCPBUGS-50578: add region to AWS creds passed to operators managed by CPO

---

.pre-commit-config.yaml
.tekton/control-plane-operator-4-14-pull-request.yaml
.tekton/control-plane-operator-4-14-push.yaml
Containerfile.control-plane
hack/tools/git-hooks/cpo-containerfiles-in-sync.sh

This PR separates the container files into:
- Containerfile.control-plane: For Konflux, using RH catalog/brew
- Dockerfile.control-plane: For ART/release-payload
To help developers avoid the situation where one changes one but not the other, this commit adds a git pre-commit hook that enforces the only differences to be in the "^FROM" lines.
In order to install this pre-commit hook, one can run:
pipx install pre-commit
pre-commit install
Then, any new commit that the developer attempts will have to conform to the new hook (and a couple more I added like no whitespace at the end). …

[release-4.14] OCPBUGS-47630: Separate CPO containerfiles

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/v2/cno/deployment.go
hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
karpenter-operator/controllers/karpenter/assets/adjust-cel.sh
support/azureutil/azureutil.go
support/azureutil/azureutil_test.go
support/config/constants.go

This PR adds an environment variable on the deployment of the following operators to specify the file path for the UserAssignedIdentityCredentials: ingress, image registry, and network.
Fixes [CNTRLPLANE-112](https://issues.redhat.com/browse/CNTRLPLANE-112)
**Checklist**

CNTRLPLANE-112: Add UserAssignedIdentityCredentials environment variable for OpenShift operators

---

control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
control-plane-operator/controllers/hostedcontrolplane/v2/assets/hosted-cluster-config-operator/role.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/oauth/component.go
control-plane-operator/controllers/hostedcontrolplane/v2/oauth/deployment.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
test/e2e/util/oauth.go

This fixes the oauth deployment not restarting after kubeadmin-secret is created in the guest cluster by the HCCO. The HCCO now annoates the secret in the HCP namespace once it creates the secret in the guest cluster to signal a restart of the oauth deployment.
Fixes #
**Checklist**

OCPBUGS-50606: Fix kubeadmin login failure

---

cmd/infra/azure/create.go

Currently, we don't return the dataplane identities if assignServicePricnipals is false this means that cluster creation will fail as dataplane identities will be missing
Fixes # [OCPBUGS-51039](https://issues.redhat.com/browse/OCPBUGS-51039)
**Checklist**

OCPBUGS-51039: return marshalled dataplane even if assignprincipals is false

---

api/hypershift/v1beta1/azure.go
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AAA_ungated.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AutoNodeKarpenter.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DisableClusterCapabilities.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DynamicResourceAllocation.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDC.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ImageStreamImportMode.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AAA_ungated.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AutoNodeKarpenter.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DisableClusterCapabilities.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DynamicResourceAllocation.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDC.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ImageStreamImportMode.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_create_with_a_ure_marketplace_image.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_availability_ones.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-Default.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-Default.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/azure.go

This PR adds omitempty to CredentialsSecretName for Azure HC API. Without this commit, HO installs are failing on the CS side for ARO HCP since MIv3 isn't enabled.
Fixes #
**Checklist**

NO-JIRA: Add omitempty to CredentialsSecretName 

---

control-plane-operator/controllers/hostedcontrolplane/mcs/params.go
hypershift-operator/controllers/nodepool/config.go
hypershift-operator/controllers/nodepool/token.go
support/backwardcompat/backwardcompat.go
support/backwardcompat/backwardcompat_test.go
support/util/util.go
support/util/util_test.go
test/e2e/create_cluster_test.go

- Skip the hashing of the `spec.configuration.image.imageStreamImportMode` field as older CPO versions don't see that field yet and if we hash it then the HO and CPO hashes will never match.
- Add a `CreateClusterWithImageConfiguration` e2e test that validates the cluster creation would fail without the hashing skipping 
>[!NOTE]
>First, I pushed the `CreateClusterWithImageConfiguration` test first without the fix to verify it's going to fail and catch the bug, and indeed it did.
>
>- [Failed Job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_hypershift/5651/pull-ci-openshift-hypershift-main-e2e-aws-4-18/1891765234188685312/artifacts/e2e-aws-4-18/hypershift-aws-run-e2e-external/artifacts/TestCrea …

OCPBUGS-50860: Skip hashing configuration.image.imageStreamImportMode

---

docs/content/contribute/contribute-docs.md
docs/content/contribute/index.md
docs/content/contribute/precommit-hook-help.md

This PR adds a precommit helpful tips documentation page to help other users quickly understand how to install, uninstall, and bypass the precommit hooks.
N/A
**Checklist**

NO-JIRA: Update-precommit-docs

---

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go

This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/5595
/assign openshift-ci-bot

[release-4.14] OCPBUGS-50700: add region to AWS creds passed to operators managed by CPO

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go

https://github.com/openshift/hypershift/pull/2278 added code for propagating the conditions on the `AWSEndpointService` up to the `HostedCluster`.  However, the `HostedClusterReconciler` does not watch the `AWSEndpointService` type and thus can miss updates to the conditions.
This PR adds `AWSEndpointService` to the `managedResources` that are watched by the `HostedClusterReconciler`.
cc @muraee

NO-JIRA: ho: watch AWSEndpointServices

---

control-plane-operator/controllers/hostedcontrolplane/etcd/params.go
control-plane-operator/controllers/hostedcontrolplane/pki/params.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/kas/reconcile.go
hypershift-operator/controllers/nodepool/haproxy.go
support/globalconfig/network.go
support/util/networking.go
support/util/util.go
support/util/util_test.go

The issue deploying IPv6 disconnected clusters happens on the validation of the KASEndpointSlice (https://github.com/openshift/hypershift/blob/main/control-plane-operator/hostedclusterconfigoperator/controllers/resources/kas/reconcile.go\#L32). Now that function supports IPv4/IPv6 addresses too, so the workflow is not modified but the validation and configuration of the Kubernetes endpointSlice
Fixes #[OCPBUGS-50692](https://issues.redhat.com//browse/OCPBUGS-50692)

OCPBUGS-50694: OCPBUGS-50692: Fix IsIPv4 function identifying also addresses instead of CIDRs

---

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/testdata/zz_fixture_TestReconcileOauthDeploymentNoChanges.yaml

cherry-picks 
- main https://github.com/openshift/hypershift/pull/5525 
- 4.18 https://github.com/openshift/hypershift/pull/5667
When using the konnectivity-https-proxy sidecar to communicate through workers, the proxy dials any configured proxy directly and fails to connect if it cannot trust the proxy's serving certificate. This commit adds mounts for the trusted-ca-bundle-managed configmap to sidecar containers that run the konnectivity-https-proxy. The configmap contains the aggregate of .spec.additionalTrustBundle and
This fixes the issue of the ingress operator not becoming available when using a proxy with a custom certificate.
In addition it propagates any proxy environment variables that are set on the control plane operator to the …

OCPBUGS-51098: 4.17 Add HostedCluster additional trustbundles to konnectivity-https-proxy

---

test/e2e/control_plane_upgrade_test.go
test/e2e/create_cluster_test.go
test/e2e/nodepool_test.go
test/e2e/util/util.go

The general idea of the fix is to detect the case where the HC image has been changed but that change has not yet propagated to HostedCluster status via ClusterVersion status.
The PR detects this by recording the CompletionTime of the latest rollout in the version history when WaitForImageRollout is first called, immediately after the image is changed on the HostedCluster.
As long as the latest rollout in the version history continues to match this recorded time, the update has not yet propagated through ClusterVersion and to the HostedCluster status. Once the propagation occurs, the latest entry in the version history will be Partial until the rollout completes, for which there is an existing block.
Changes:
* Ignore the latest entries in the version history if the `CompletionTime` was …

OCPBUGS-51007: test/e2e: fix WaitForImageRollout to actually wait on upgrade case

---

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go

This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/5595
/assign openshift-ci-bot

[release-4.17] OCPBUGS-50697: add region to AWS creds passed to operators managed by CPO

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
support/azureutil/azureutil.go
support/azureutil/azureutil_test.go

This PR enables image registry to use managed identity v3 
Part of [CNTRLPLANE-112](https://issues.redhat.com/browse/CNTRLPLANE-112)
**Checklist**

CNTRLPLANE-112: Enable image registry to use managed identity v3 

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
ignition-server/controllers/local_ignitionprovider.go
support/util/imagemetadata.go
support/util/imagemetadata_test.go

After #5168, the release image passed to the CVO is an image with a digest (which is needed for offline). Because this doesn't always match the release image specified in the HostedCluster.spec.release.image field, code that relies on comparing the image in CVO status with what's in the spec is now not matching. One effect is that the Progressing condition remains set to "true" even if a HostedCluster has completed provisioning.
This PR makes the following changes in order to fix it:
- Adds code to the HyperShift operator to compare either the image in spec as is or converted to a digest with the image reported by the CVO in status.
- Removes the call to obtain the release image for a specific architecture when obtaining an image with digest for the …

OCPBUGS-51339: [release-4.17] Fix IsProgressing condition in HostedClusters

---

docs/content/how-to/openstack/prerequisites.md

We are now using 1.23 so we need to update the doc or users will have trouble to build the binary.

NO-JIRA: doc: openstack: update go version

---

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go

This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/5595
/assign openshift-ci-bot

[release-4.16] OCPBUGS-50698: add region to AWS creds passed to operators managed by CPO

---

control-plane-operator/controllers/hostedcontrolplane/cloud/azure/providerconfig.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/storage/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/azure/config.go
control-plane-operator/controllers/hostedcontrolplane/v2/storage/azure.go

This pull request enables managed identity version 3 for azure disk csi driver for managed Azure HCP.
A part of [CNTRLPLANE-112](https://issues.redhat.com/browse/CNTRLPLANE-112)
**Checklist**

CNTRLPLANE-112: Enable MIv3 for azure disk csi driver

---

hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack.go
hypershift-operator/controllers/hostedcluster/internal/platform/openstack/openstack_test.go
hypershift-operator/controllers/hostedcluster/internal/platform/platform.go

ORC was added to the release payload in 4.19 so we don't want to
install it in 4.18.

OSASINFRA-3733: deploy ORC on release payload >= 4.19

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
control-plane-operator/controllers/hostedcontrolplane/v2/olm/catalogs/deployment.go
control-plane-operator/controllers/hostedcontrolplane/v2/olm/catalogs/imagestream.go
control-plane-operator/hostedclusterconfigoperator/cmd.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/olm/params.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
control-plane-operator/hostedclusterconfigoperator/operator/config.go
control-plane-operator/main.go
docs/content/contribute/index.md
support/controlplane-component/controlplane-component.go
support/controlplane-component/deployment.go
support/releaseinfo/registryclient/client.go
support/util/fakeimagemetadataprovider/fakeimagemetadataprovider.go

- We should use the registry overrides if provided when automatically retrieving the latest available catalog images, this can cause trouble when the pullsecret doesn't give access to the default redhat registry expected ie 'registry.redhat.io/redhat'
Fixes #
**Checklist**

OCPBUGS-49825: use registryOverrides when automaitcally retrieving catalog images for hosted control plane

---

.github/workflows/codespell.yml
.github/workflows/golangci-lint.yml
.github/workflows/make-verify.yml
.github/workflows/unit-test.yml
.testcoverage.yml
support/controlplane-component/controlplane-component.go

This PR enables an initial set of GitHub Action jobs including: codespell, golangci-lint, verify, and unit testing
A part of [CNTRLPLANE-244](https://issues.redhat.com/browse/CNTRLPLANE-244)
**Checklist**

CNTRLPLANE-244: Enable initial GitHub Action jobs

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
control-plane-operator/hostedclusterconfigoperator/cmd.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/olm/params.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
control-plane-operator/hostedclusterconfigoperator/operator/config.go
control-plane-operator/main.go
docs/content/contribute/index.md
support/releaseinfo/registryclient/client.go
support/util/fakeimagemetadataprovider/fakeimagemetadataprovider.go

Were changing to use registryOverrides when retrieving catalog images as some users may be mirroring to private registries
OCPBUGS-49825: add a new fakeImageMetaDataProvider for HCCO resources.go
Switch from passing in a fakeDigest func during the resource_test.go fror olmReconcile to using a fakeImageMetaDataProvider to simplify the code
Fixes # https://issues.redhat.com/browse/OCPBUGS-51375
**Checklist**

OCPBUGS-51375: use registryOverrides when automaitcally retrieving catalog images for hosted control plane

---

.github/workflows/golangci-lint.yml
.github/workflows/make-verify.yml
.github/workflows/sync-container-files.yaml

Minor updates to the GitHub Actions. This PR:
- adds the CPO container sync check to GitHub Actions
- disables caching for the make verify and golangci-lint GitHub Actions.Cache was enabled by default and was causing warning errors like - `Warning: Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2.`
N/A
**Checklist**

NO-JIRA: Add CPO container sync check to GitHub Actions

---

.tekton/control-plane-operator-main-pull-request.yaml
.tekton/control-plane-operator-main-push.yaml
control-plane-operator/controllers/hostedcontrolplane/cloud/azure/providerconfig.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/azure/config.go

This PR enables managed identity version 3 for cloud provider/cloud configuration manager for managed Azure HCP.
A part of [CNTRLPLANE-111](https://issues.redhat.com/browse/CNTRLPLANE-111)
**Checklist**

CNTRLPLANE-111: Enable MIv3 for CP/CCM in managed Azure HCP

---

.github/workflows/golangci-lint.yml

This PR removes the issues-exit flag for golangci-lint. If this flag is set, then the golangci-lint job will return as success even If there are errors.
Fixes #
**Checklist**

NO-JIRA: Remove issues-exit flag for golangci-lint

---

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/testdata/zz_fixture_TestReconcileOauthDeploymentNoChanges.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/oauth-openshift/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/oauth-openshift/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-apiserver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-oauth-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-oauth-apiserver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-apiserver/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/oauth-openshift/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-apiserver/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-oauth-apiserver/deployment.yaml

OCPBUGS-50523: Fix audit-logs container to properly handle SIGTERM

---

control-plane-operator/controllers/healthcheck/aws.go
control-plane-operator/controllers/healthcheck/healthcheck_controller.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/main.go

The cloud provider health check runs every time through the HCP reconcile loop and result in ~800k calls to `DescribeVpcEndpoints` per day in our CI.  This is 25-30% of our total AWS API call volume in our CI account and is contributing to API throttling.
xref
Add identity provider health check https://github.com/openshift/hypershift/pull/1913
Requeue HCP always https://github.com/openshift/hypershift/pull/2408
This PR refactors the health check into its own controller to achieve two goals:
1) Do health checks periodically, even HCP is not changing.  This is already done because with requeue the HCP as a hack to deal with unwatchable changes i.e. AWS LB stuff, however, I think we want to refactor this as well in a follow-on PR so we can stop requeuing the HCP on reconcile success.
2) …

OCPBUGS-52223: refactor aws identity health check into new controller

---

hypershift-operator/controllers/hostedcluster/internal/platform/platform.go

Here too we need to add a condition on when we want to pull ORC.
This was a miss from https://github.com/openshift/hypershift/pull/5710.

OSASINFRA-3733: (follow-up) deploy ORC on release payload >= 4.19

---

control-plane-operator/controllers/healthcheck/aws.go
control-plane-operator/controllers/healthcheck/healthcheck_controller.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/main.go

Manual pick of https://github.com/openshift/hypershift/pull/5751
Conflict was just import ordering in `main.go`

OCPBUGS-52417: [release-4.18] refactor aws identity health check into new controller

---

.dockerignore
Dockerfile.e2e

This PR speeds up the image builds by
* Exclude the `.git` directory in the `COPY . .` for all built images, which saves around 150MB of disk I/O
* Make the `hypershift-tests` image, built with `Dockerfile.e2e`, multi-stage so we don't commit the source tree, intermediate build files, and dnf cache to the final image that needs to be pushed to the CI registry.  This reduces the size of additional layers, on top of the base image, by 75% from ~4GB to ~1GB
Before
```
$ podman history 118e47b22af65211e283c950b65ecc569381cff570990ef03914af5b9fb568b6
ID            CREATED       CREATED BY                                     SIZE        COMMENT
118e47b22af6  2 hours ago   /bin/sh -c #(nop) LABEL "io.openshift.buil...  4.02GB      FROM image-registry.openshift-image-registry.svc:5000/ci-op-vlijyx …
```

NO-JIRA: speed up image builds

---

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-apiserver/deployment.yaml

Modify apply-bootstrap container to trap SIGTERM, and handle it correctly before exiting to ensure the container terminates within the specified grace period.
Fixes #
**Checklist**

OCPBUGS-50518: Kubernetes API Server apply-bootstrap container does not respect SIGTERM

---

test/e2e/nodepool_test.go

We don't need to call that function as it's already called where it's
needed, in control_plane_upgrade_test for example.

OCPBUGS-52419: e2e: don't call `WaitForImageRollout` in `executeNodePoolTest`

---

control-plane-operator/controllers/healthcheck/aws.go
control-plane-operator/controllers/healthcheck/healthcheck_controller.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/main.go

Manual pick of https://github.com/openshift/hypershift/pull/5770
Conflict was just changing context around the diff.

OCPBUGS-52425: [release-4.17] refactor aws identity health check into new controller

---

docs/content/how-to/azure/create-azure-cluster_on_aks.md

This commit removes the workload identity instruction for adding a federated ID for the service account openshift-image-registry:cluster-image-registry-operator.
N/A
**Checklist**

NO-JIRA: Remove WI step for cluster-image-registry-operator

---

control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/testdata/zz_fixture_TestReconcileOauthDeploymentNoChanges.yaml

Addresses issue with https://github.com/openshift/hypershift/pull/5667 which made the `managed-trust-bundle` required. However, this breaks folks who bring their own PKI.
https://ibm-argonauts.slack.com/archives/C01C8502FMM/p1741096684745729
Fixes #
https://issues.redhat.com/browse/OCPBUGS-52323
**Checklist**

OCPBUGS-52323: Make managed-trust-bundle optional

---

test/e2e/nodepool_test.go

Observing failures in `TestNodePool/HostedCluster0/Main/TestNTOPerformanceProfile` for 4.15 and 4.16 after #5771
This PR reverts #5771 and does a version-gated version of the same thing to avoid rebreaking Openstack.
cc @EmilienM

NO-JIRA: test/e2e: skip WaitForImageRollout in executeNodePoolTest on newer releases

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
control-plane-operator/controllers/hostedcontrolplane/testdata/cloud-controller-manager-aws/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/cloud-controller-manager-aws/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-image-registry-operator/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-image-registry-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/hosted-cluster-config-operator/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/hosted-cluster-config-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/ingress-operator/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/ingress-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_component.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_component_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/cloud-controller-manager-aws/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-image-registry-operator/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/ingress-operator/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/aws/component.go
control-plane-operator/controllers/hostedcontrolplane/v2/ingressoperator/component.go
control-plane-operator/controllers/hostedcontrolplane/v2/ingressoperator/deployment.go
control-plane-operator/controllers/hostedcontrolplane/v2/registryoperator/component.go
control-plane-operator/controllers/hostedcontrolplane/v2/registryoperator/deployment.go
support/controlplane-component/README.md
support/controlplane-component/builder.go
support/controlplane-component/controlplane-component.go
support/controlplane-component/defaults.go
support/controlplane-component/token-minter-container.go

This PR adds automation in CPOv2 that allows component to request a `token-minter` container to be injected programmatically instead of having it explicitly defined in the yaml manifest.
Fixes #
**Checklist**

NO-JIRA: CPOv2 token-minter abstraction

---

control-plane-operator/controllers/awsprivatelink/awsprivatelink_controller.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go

This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/5595
/assign openshift-ci-bot

[release-4.15] OCPBUGS-50699: add region to AWS creds passed to operators managed by CPO

---

Makefile
api/karpenter/v1beta1/karpenter_types.go
karpenter-operator/controllers/karpenter/karpenter_controller.go
karpenter-operator/controllers/nodeclass/ec2_nodeclass_controller.go
karpenter-operator/e2e/adjust-ec2nodeclass.sh
karpenter-operator/e2e/default_nodepool.yaml
karpenter-operator/e2e/upstream-e2e.sh
vendor/github.com/openshift/hypershift/api/karpenter/v1beta1/karpenter_types.go

This PR adds a script to run [upstream Karpenter core e2e tests](https://github.com/kubernetes-sigs/karpenter/tree/main/test) with AutoNode and hypershift. This will allow us to re-use tests and confirm that our karpenter-provider satisfies the basic/expected karpenter behaviour. See the JIRA issues or this relevant slack conversation for details on the test plan: https://redhat-internal.slack.com/archives/C02F1J9UJJD/p1739984424557259. This also allows an annotation `hypershift.openshift.io/karpenter-core-e2e-override` to be added to the `HostedCluster` object that allows the karpenter-operator to stop it's deletion in a guest cluster with AutoNode.
We need the annotation because the upstream tests try to recreate NodeClasses before every test, but …

PODAUTO-324: PODAUTO-325: Allow autonode to run upstream karpenter core e2e tests

---

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-apiserver/deployment.yaml

Cherry pick of #5475 on release-4.18.
#5475: Modify the apply-bootstrap container of kube-apiserver to
```release-note
```

[release-4.18] OCPBUGS-52878: Kubernetes API Server apply-bootstrap container does not respect SIGTERM

---

control-plane-operator/controllers/hostedcontrolplane/kas/kms/kms.go
control-plane-operator/controllers/hostedcontrolplane/v2/kas/kms/azure.go

This PR fixes the SecretProviderClass name for the volume related to the KMS MIv3 credentials. Previously it was set to the volume name instead of the SecretProviderClass name.
A part of [CNTRLPLANE-111](https://issues.redhat.com//browse/CNTRLPLANE-111)
**Checklist**

CNTRLPLANE-111: Fix Azure KMS SecretProviderClass volume name

---

docs/Dockerfile
docs/Makefile
docs/image-version.awk
docs/requirements.txt

Changes the containerized builds to:
* Use the same container runtime detection as the main repository makefile.
* Changes from the docker mkdocs-material image to a fedora-minimal based one.
* Introduces the usage of a volume for the site build not to pollute the repository
* Makes the containerized versions respect the versions in requirements.txt
* Bumps requirements.txt.
* Changes the build mode to --strict, to prevent warnings from creeping in.
Fixes #[CNTRLPLANE-325](https://issues.redhat.com//browse/CNTRLPLANE-325)
**Checklist**

CNTRLPLANE-325: rootless containerized builds

---

control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-controller-manager/service.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-route-controller-manager/service.yaml

While adding a new ControlPlaneComponent, I came across these 2 errors:
`{"level":"error","ts":"2025-03-13T15:45:22Z","msg":"Reconciler error","controller":"hostedcontrolplane","controllerGroup":"hypershift.openshift.io","controllerKind":"HostedControlPlane","HostedControlPlane":{"name":"my-hcp-cluster","namespace":"clusters-my-hcp-cluster"},"namespace":"clusters-my-hcp-cluster","name":"my-hcp-cluster","reconcileID":"2b7e0124-4ae6-42d2-b368-2d7cfc1252e5","error":"failed to update control plane: [...Service \"kube-controller-manager\" is invalid: spec.ipFamilyPolicy: Invalid value: \"PreferDualStack\": must be 'SingleStack' to release the secondary IP family, Service \"openshift-route-controller-manager\" is invalid: spec.ipFamilyPolicy: Invalid …

METAL-1240: Fix kube-controller-manager and openshift-route-controller-manager services' ipFamilies wrt PreferDualStack policy

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/v2/cno/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/cno/deployment.go
support/config/constants.go

This PR enables managed identity version 3 for cluster network operator (CNO) and cloud network configuration controller (CNCC) for managed azure.
Fixes [CNTRLPLANE-112](https://issues.redhat.com/browse/CNTRLPLANE-112)
**Checklist**

CNTRLPLANE-112: Enable MIv3 for CNO/CNCC on managed Azure

---

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/testdata/zz_fixture_TestReconcileOauthDeploymentNoChanges.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/oauth-openshift/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-oauth-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-apiserver/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/oauth-openshift/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-apiserver/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-oauth-apiserver/deployment.yaml

Cherry pick of #5491 on release-4.18.
#5491: Modify audit container for openshift-apiserver,
```release-note
```

[release-4.18] OCPBUGS-52982: Fix audit-logs container to properly handle SIGTERM

---

api/hypershift/v1beta1/openstack.go
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
client/applyconfiguration/hypershift/v1beta1/openstackplatformspec.go
cmd/cluster/openstack/create.go
cmd/cluster/openstack/create_test.go
cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_default_creation_flags.yaml
cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
docs/content/how-to/openstack/hostedcluster.md
docs/content/how-to/openstack/prerequisites.md
docs/content/reference/api.md
hypershift-operator/controllers/nodepool/openstack.go
hypershift-operator/controllers/nodepool/openstack/openstack.go
hypershift-operator/controllers/nodepool/openstack/openstack_test.go
test/e2e/e2e_test.go
test/e2e/util/options.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/openstack.go

- Revert of `OpenStackImageRetentionPolicy` for now. We have identified that the current code that was implemented isn't suitable for production.
We want to re-work it but in the meantime we just revert it.
- Added `ClusterImageName` function to encapsulate image name generation for a HostedCluster.
- Updated `reconcileOpenStackImageCR` and `ReconcileOpenStackImageSpec`
to use `ClusterImageName` instead of manually constructing image names.
- Use an image name that now contains the Hosted Cluster name in it so
it's unique and per Hosted Cluster. The OpenStack Glance image won't
be shared across Hosted Clusters and its lifecycle will be the same as
the HostedCluster using it (by default).

NO-JIRA: openstack: revert `OpenStackImageRetentionPolicy` + use a unique image name per Hosted Cluster

---

support/releaseinfo/registry_image_content_policies.go
support/releaseinfo/registry_image_content_policies_test.go

According to OCP IDMS, when the current mirror image is unavailable, the system should continue searching for an available mirror image.
Fixes # https://issues.redhat.com/browse/OCPBUGS-53050
**Checklist**

OCPBUGS-53050: Handle multiple mirror entries for source

---

.tekton/hypershift-operator-main-tag.yaml

Add a pipeline triggered by pushing tags to the repository that has an additional tekton task to tag the image with the git tag.
This will make it much easier to spot which version is running in which environment.
Fixes #[CNTRLPLANE-348](https://issues.redhat.com//browse/CNTRLPLANE-348)
**Checklist**

CNTRLPLANE-348: Konflux tagged releases

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go

This commit fixes the KMS Azure credentials mount path so that there is a / in between the path and credentials secret.
A part of [CNTRLPLANE-111](https://issues.redhat.com//browse/CNTRLPLANE-111)
**Checklist**

CNTRLPLANE-111: Fix KMS Azure credentials mount path

---

control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/assets/07_deployment-hypershift.yaml
control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator_test.go
control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/params.go
control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/testdata/zz_fixture_TestReconcileOperatorDeployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/csi-snapshot-controller-operator/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/csi-snapshot-controller-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/csi-snapshot-controller-operator/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/snapshotcontroller/deployment.go

Removed csi-snapshot-validation-webhook.
Webhook image is no longer used and will not be built on OCP 4.19+.
https://issues.redhat.com/browse/STOR-2281
**Checklist**

STOR-2281: Remove csi-snapshot-validation-webhook

---

cmd/infra/azure/create.go

This commit improves the error output messaging for Azure CLI role assignment commands. This should help with diagnosing issues with Azure.
N/A
**Checklist**

NO-JIRA: Improve error output msg for Azure CLI role cmds

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/olm/catalogs.go
control-plane-operator/controllers/hostedcontrolplane/v2/olm/catalogs/deployment.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/olm/params.go
support/catalogs/images.go
support/catalogs/images_test.go

This commit refactors the code that fetches the images to use for OLM catalogs into a common support package. It checks individual catalog images instead of assuming that all of them have the same tag available. It also introduces a cache for images so that every reconcile loop does not result in registry lookups.
Fixes #[OCPBUGS-53462](https://issues.redhat.com/browse/OCPBUGS-53462)
**Checklist**

OCPBUGS-53462: Check for availability of individual catalog images

---

control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oapi/deployment_test.go
control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-oauth-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-oauth-apiserver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-oauth-apiserver/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/oapi/deployment.go
control-plane-operator/controllers/hostedcontrolplane/v2/oauth_apiserver/component.go
control-plane-operator/controllers/hostedcontrolplane/v2/oauth_apiserver/deployment.go
support/util/util.go
support/util/util_test.go

ValidatingWebhooks installed in the data plane were not able to validate resources managed by the OpenShift oauth apiserver because the OpenShift oauth apiserver did not have a konnectivity-proxy. This commit adds the konnectivity-proxy sidecar to the openshift oauth apiserver deployment and uses the socks5 proxy given that the openshift-oauth-apiserver only needs to communicate with services inside the data plane.
Fixes #[OCPBUGS-52190](https://issues.redhat.com/browse/OCPBUGS-52190)
**Checklist**

OCPBUGS-52190: Add konnectivity-proxy sidecar to openshift-oauth-apiserver

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go

This commit changes the CPO to look for a stored Azure credential to reuse to authenticate with Azure. If there is no stored Azure credential, authenticate to Azure with UAMI and store the credentials.
Prior to this commit, the CPO was getting new credentials every reconcile; this led to an issue where the CPO would open too many filewatchers as NewUserAssignedIdentityCredential opens a new filewatcher on every call.
```
time=2025-03-06T18:58:45.994Z level=ERROR msg="failed to create file watcher" err="too many open files"
```
A part of [CNTRLPLANE-111](https://issues.redhat.com/browse/CNTRLPLANE-111)
**Checklist**

CNTRLPLANE-111: Authenticate to Azure only once in CPO

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/nodepool/capi.go
hypershift-operator/controllers/nodepool/capi_test.go

This enabled machineset preflights by default https://github.com/kubernetes-sigs/cluster-api/pull/11228
We want to disable this functionality in hcp because of the following reasons:
- MachineSetPreflightCheckControlPlaneIsStable
We currently don't express intent for a version via spec.version but via spec.release
- MachineSetPreflightCheckKubernetesVersionSkew
We preserve our ability to control our skew policy at a higher layer i.e. NodePool API
- MachineSetPreflightCheckKubeadmVersionSkew
We don't run kubeadmin at all.
Fixes #
**Checklist**

OCPBUGS-50915: Disable capi machineset preflights

---

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
control-plane-operator/controllers/hostedcontrolplane/kas/params.go
control-plane-operator/main.go
kas-bootstrap/kas_boostrap.go
kas-bootstrap/kas_boostrap_test.go
kas-bootstrap/main.go
test/e2e/control_plane_upgrade_test.go
test/e2e/util/util.go

kas-bootstrap is a tool to run the pre-required actions for bootstraping the kas during cluster creation (or upgrade).
It will apply some CRDs rendered by the cluster-config-operator and update the featureGate CR status by appending the git FeatureGate status.
It aims to alleviate the current bash scripts fragility, fix the fact we always replace instead of append the featureGate.status and include current and any upcoming changes to this logic with appropriate test coverage
Follow up:
Move the logic from kasContainerApplyBootstrap to kasContainerBootstrap and drop the former.
Add it to cpov2 …

OCPBUGS-46379: Kas bootstrap bin

---

control-plane-operator/controllers/hostedcontrolplane/manifests/azure.go

This commit removes the TODO comment above the AzureProviderConfig function. This ConfigMap is needed for the ignition configuration by the machine-config-operator (MCO).
Fixes #
**Checklist**

NO-JIRA: Remove TODO comment for AzureProviderConfig

---

cmd/infra/azure/create.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/rbac.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/rbac/reconcile.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go

This pull request:
- adds a role assignment for the CNCC over the VNET resource group for managed Azure, which is needed for CNCC to be able to read and write over items in the VNET resource group
- adds event get & create RBAC for the service account, cloud-network-config-controller, in the openshift-cloud-network-config-controller namespace
A part of [CNTRLPLANE-112](https://issues.redhat.com//browse/CNTRLPLANE-112)
**Checklist**

CNTRLPLANE-112: Fix CNCC RG Permissions & RBAC

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/nodepool/capi.go
hypershift-operator/controllers/nodepool/capi_test.go

Reverts openshift/hypershift#5653
This broke 4.14 payload jobs with `cluster-api` pod not able to start
```
invalid argument "MachineSetPreflightChecks=false" for "--feature-gates" flag: unrecognized feature gate: MachineSetPreflightChecks
```
https://testgrid.k8s.io/redhat-hypershift#4.14-aws-ovn
TRT SOP is to revert.
@stbenjam @neisw

NO-JIRA: Revert "OCPBUGS-50915: Disable capi machineset preflights"

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
control-plane-operator/controllers/hostedcontrolplane/storage/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/storage/azure.go
kas-bootstrap/main.go

This pull request enables managed identity version 3 for azure file csi driver for managed Azure HCP.
A part of [CNTRLPLANE-112](https://issues.redhat.com/browse/CNTRLPLANE-112)
**Checklist**

CNTRLPLANE-112: Enable MIv3 for azure file csi driver

---

cmd/nodepool/core/create.go
cmd/nodepool/core/create_test.go

This commit adds validation to ensure NodePool versions are compatible with the HostedCluster version:
- For 4.even versions, allows y-2 difference
- For 4.odd versions, allows y-1 difference
- NodePool version cannot be higher than control plane version
The validation is skipped in disconnected environments where registry access is not available.
**Jira story**
https://issues.redhat.com/browse/CNTRLPLANE-330
https://issues.redhat.com/browse/CNTRLPLANE-350
**Log**
```
➜  oc get hostedcluster -A              
NAMESPACE   NAME          VERSION                              KUBECONFIG                     PROGRESS    AVAILABLE   PROGRESSING   MESSAGE
clusters    liangli0320   4.19.0-0.nightly-2025-03-19-080024   liangli0320-admin-kubeconfig   Completed …
```

CNTRLPLANE-350: add NodePool minor version compatibility check

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/github.com/golang-jwt/jwt/v5/README.md
vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
vendor/github.com/golang-jwt/jwt/v5/parser.go
vendor/github.com/golang-jwt/jwt/v5/token.go
vendor/modules.txt

Need to bump the version due to OCPBUGS-53904
Fixes #OCPBUGS-53904
**Checklist**

OCPBUGS-53904: bump golang-jwt v4 and v5

---

.tekton/hypershift-operator-main-pull-request.yaml
.tekton/hypershift-operator-main-push.yaml

This commit temporarily comments out the ppc64le bits for the HO tekton files since there has been an ongoing issue being able to build for this architecture.
Fixes #
**Checklist**

NO-JIRA: Remove ppc64le from HO tekton files

---

control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
kas-bootstrap/kas_boostrap.go
kas-bootstrap/kas_boostrap_test.go
kas-bootstrap/main.go
kas-bootstrap/testdata/0000_10_config-operator_01_apiservers.crd.yaml
kas-bootstrap/testdata/0000_10_config-operator_01_featuregates.crd.yaml
kas-bootstrap/testdata/99_feature-gate.yaml
kas-bootstrap/testdata/hcco-clusterrole-binding.yaml

Follow up for https://github.com/openshift/hypershift/pull/5871
It aims to alleviate the current bash scripts fragility and cover existing and any upcoming changes to this logic with appropriate test coverage
Fixes #
**Checklist**

CNTRLPLANE-378: Move bootstrap apply bash into kas-bootstrap binary

---

cmd/cluster/azure/create_test.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_disabled_capabilities.yaml
cmd/cluster/core/create.go
cmd/cluster/core/create_test.go

Fixes #[ARO-15578](https://issues.redhat.com//browse/ARO-15578)
**Checklist**

ARO-15578: add disable cluster capabilities flag to cluster create cmd

---

control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-apiserver/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/kas/deployment.go

Follow up for:
https://github.com/openshift/hypershift/pull/5871
https://github.com/openshift/hypershift/pull/5937
Incorportate kas bootstrap into cpov2
Fixes #
**Checklist**

CNTRLPLANE-378: Run kas-bootstrap binary for cpov2

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/github.com/golang-jwt/jwt/v5/README.md
vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
vendor/github.com/golang-jwt/jwt/v5/parser.go
vendor/github.com/golang-jwt/jwt/v5/token.go
vendor/modules.txt

Need to bump the version due to OCPBUGS-53905
Fixes #OCPBUGS-53905
**Checklist**

OCPBUGS-53905: bump golang-jwt v4 and v5

---

test/e2e/util/options.go

Had a recent issue where new dev ran e2e locally against AWS infra without including an expirationDate tag causing orphaned resources

NO-JIRA: set default expriationDate tag in AWS if not set

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/github.com/golang-jwt/jwt/v5/README.md
vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
vendor/github.com/golang-jwt/jwt/v5/parser.go
vendor/github.com/golang-jwt/jwt/v5/token.go
vendor/modules.txt

Need to bump the version due to OCPBUGS-53903.
Fixes #OCPBUGS-53903
**Checklist**

OCPBUGS-53903: bump golang-jwt v4 and v5

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go

This commit ensures that annotations that are synced by the HostedCluster are removed from the HostedControlPlane when they are removed from the HostedCluster. Annotations that the HostedCluster reconciler does not know about are not removed.
Fixes #[OCPBUGS-53403](https://issues.redhat.com/browse/OCPBUGS-53403)
**Checklist**

OCPBUGS-53403: Remove synced annotations from HCP when they are removed from HC

---

hypershift-operator/controllers/platform/aws/controller.go

Follow on to https://github.com/openshift/hypershift/pull/5674
Previous PR added `AWSEndpointService` objects to the `HostedCluster` controller Watch, however, `enqueueHostedClustersFunc()` is unable to map to a `HostedCluster` to reconcile because the `AWSEndpointService` type does not have an explicit mapping method or the `HostedClusterAnnotation`.
This PR adds the `HostedClusterAnnotation` to the `AWSEndpointService` so that `handleDefault` can map it to a `HostedCluster`
https://github.com/openshift/hypershift/blob/dd7cb9264226444e5026d67575562b11a932aa38/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go#L4194-L4205

OCPBUGS-52984: annotate AWSEndpointServices with HostedClusterAnnotation

---

contrib/ci/dev-namespace-template.yaml

Needs to be created manually because:
Prior to OpenShift Container Platform 4.16, a long-lived service account API token secret was also generated for each service account that was created. Starting with OpenShift Container Platform 4.16, this service account API token secret is no longer created.
Related [Slack discussion](https://redhat-internal.slack.com/archives/G01QS0P2F6W/p1738329844270039?thread_ts=1738239053.859029&cid=G01QS0P2F6W)
With the new version of OpenShift, the Secret/Token is not created automatically.
**Checklist**

NO-JIRA: Create token Secret for dev cluster explicitly

---

api/scheduling/v1alpha1/clustersizingconfiguration_types.go
api/scheduling/v1alpha1/zz_generated.deepcopy.go
client/applyconfiguration/scheduling/v1alpha1/effects.go
cmd/install/assets/hypershift-operator/scheduling.hypershift.openshift.io_clustersizingconfigurations.yaml
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
hypershift-operator/controllers/scheduler/aws/dedicated_request_serving_nodes_test.go
hypershift-operator/controllers/scheduler/azure/controllers_test.go
hypershift-operator/controllers/scheduler/util/scheduler.go
hypershift-operator/controllers/scheduler/util/scheduler_test.go
vendor/github.com/openshift/hypershift/api/scheduling/v1alpha1/clustersizingconfiguration_types.go
vendor/github.com/openshift/hypershift/api/scheduling/v1alpha1/zz_generated.deepcopy.go

This PR changes the KASGoMemLimit to a string pointer type instead of a k8s api/resource Quantity pointer type and updates related unit tests.
Fixes #
**Checklist**

OCPBUGS-54439: Change KASGoMemLimit to a string pointer type

---

cmd/install/assets/assets.go
cmd/install/install.go
cmd/install/install_test.go
docs/content/how-to/install/index.md
docs/mkdocs.yml

This PR adds a new flag to the HO installation, limit-crd-install. This flag allows a user to limit what CAPI CRDs are installed per platform basis.
Fixes #
**Checklist**

OCPBUGS-13292: Add functionality to limit CAPI CRD installation on HO installation

---

Containerfile.control-plane
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go

This commit adds the label, LABEL io.openshift.hypershift .control-plane-operator-supports-kas-custom-kubeconfig=true, to the RHTAP CPO dockerfile as the CPO dockerfile was updated to include the label.
Fixes #
**Checklist**

NO-JIRA: Sync labels between CPO and RHTAP CPO dockerfile

---

hypershift-operator/controllers/nodepool/token.go
hypershift-operator/controllers/nodepool/token_test.go

If the reconcile loop runs more often than every 2 hours, the `IgnitionServerTokenExpirationTimestampAnnotation` annotation gets reset on the ignition token secrets, potentially preventing them from being cleaned up and causing a backup of secrets.
Fixes #OCPBUGS-54431
**Checklist**

OCPBUGS-54431: Don't set IgnitionServerTokenExpirationTimestampAnnotation if already set

---

control-plane-operator/controllers/hostedcontrolplane/cloud/openstack/providerconfig.go
control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/openstack/config.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go

cloud-credential-operator now supports syncing CA certs from the root credential secret to the generated credentials secrets. If necessary, CCO expects the CA cert to be provided in the `cacert` key and will place it in the same location in the generated secrets. Start doing the same in control-plane-operator, which allows us to significantly simplify the assets used in cluster-storage-operator and csi-operator.
Note that we are intentionally *not* changing how CA certs are managed for cluster-cloud-controller-manager-operator. There's a good reason for this, and a note is left inline to that effect.
/hold
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a …

OSASINFRA-3732: openstack: Sync CA cert to new key

---

cmd/cluster/aws/create_test.go
cmd/cluster/aws/testdata/zz_fixture_TestCreateCluster_minimal_with_KubeAPIServerDNSName.yaml
cmd/cluster/azure/create_test.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_KubeAPIServerDNSName.yaml
cmd/cluster/core/create.go
cmd/cluster/core/create_test.go

This PR includes the new flag --kas-dns-name, which enables the customer to create a HostedCluster directly to consume KubeAPIServerDNSName API
Fixes #[CNTRLPLANE-233](https://issues.redhat.com/browse/CNTRLPLANE-233)

CNTRLPLANE-233: Add --kas-dns-name CLI flag to consume KubeAPIServerDNSName API

---

test/e2e/util/util.go

Hold for https://github.com/openshift/hypershift/pull/5964 to merge.
Diff is large because I wrapped `EnsureImageRegistryCapabilityDisabled` in a `t.Run()`
cc @flavianmissi 
Run `/test e2e-aws-4-18` after dep merge and before moving out of draft.

ARO-15695: test/e2e: run EnsureImageRegistryCapabilityDisabled on 4.18

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator_test.go

Resolves permission errors in the CNO for patching servicemonitors and prometheusrules for non-OVN clusters.
Fixes #
https://issues.redhat.com/browse/OCPBUGS-54178
**Checklist**

OCPBUGS-54178: Add missing servicemonitors and prometheusrules permissions for non-OVN

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/manifests/pki.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go

Manual cherry-pick to resolve conflicts in #5573
The openshift controller manager operator syncs the CA bundle that was configured in the global proxy config into a configmap in the openshift-controller-manager namespace. This configmap is then used by the build controller to generate the CA that is mounted into builds for registry access. Because we don't run the controller manager operator in hypershift, this needs to be done by the HCCO. This code adds the reconciliation to the HCCO so that it puts the configmap in the right location.
Ref: https://github.com/openshift/cluster-openshift-controller-manager-operator/blob/08c64512c055ae246b3a14f6d1088d39988c44fe/pkg/operator/usercaobservation/user_ca_observation_controller.go#L80-L90
**Which issue(s) …

[release-4.16] OCPBUGS-49914: Reconcile proxy CA bundle into hosted cluster

---

control-plane-operator/controllers/hostedcontrolplane/pki/kas.go
control-plane-operator/controllers/hostedcontrolplane/pki/konnectivity.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/validations/ocpapiserver.go
hypershift-operator/controllers/hostedcluster/validations/ocpapiserver_test.go
support/pki/kas.go
support/pki/kas_test.go
test/util/pki.go
test/util/pki_test.go

This PR adds validation to ensure there are no conflicts between the SAN's of the user's APIServer NamedCertificates and the KubeAPIServer CPO certificates. This prevents potential issues with certificate SANs conflicts that could break the TLS trust chain between the nodes and the KAS
Fixes #[OCPBUGS-53261](https://issues.redhat.com/browse/OCPBUGS-53261)

OCPBUGS-53261: Add validation to avoid conflicts between KubeAPI server and NamedCertificates SANs

---

support/api/scheme.go
test/e2e/assets/karpenter-workloads.yaml
test/e2e/karpenter_test.go
test/e2e/util/eventually.go

This PR adds a new test to the karpenter e2e suite which upgrades the hcp and validates that karpenter nodes are drift and upgraded to the control-plane's new release image version. Also validates that any pods that were already scheduled to the old karpenter node, will be rescheduled to the new karpenter node.
Also this PR lowers the CPU of the tested workload to avoid them being unschedulable because of the small CPU allocation of `t3.large` instances.
Fixes: https://issues.redhat.com/browse/AUTOSCALE-44
**Checklist**

AUTOSCALE-44: add autonode karpenter drift hcp upgrade e2e test

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/github.com/golang-jwt/jwt/v5/MIGRATION_GUIDE.md
vendor/github.com/golang-jwt/jwt/v5/README.md
vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
vendor/github.com/golang-jwt/jwt/v5/ecdsa.go
vendor/github.com/golang-jwt/jwt/v5/ed25519.go
vendor/github.com/golang-jwt/jwt/v5/errors_go_other.go
vendor/github.com/golang-jwt/jwt/v5/hmac.go
vendor/github.com/golang-jwt/jwt/v5/none.go
vendor/github.com/golang-jwt/jwt/v5/parser.go
vendor/github.com/golang-jwt/jwt/v5/parser_option.go
vendor/github.com/golang-jwt/jwt/v5/rsa.go
vendor/github.com/golang-jwt/jwt/v5/rsa_pss.go
vendor/github.com/golang-jwt/jwt/v5/token.go
vendor/github.com/golang-jwt/jwt/v5/types.go
vendor/github.com/golang-jwt/jwt/v5/validator.go
vendor/modules.txt

Need to bump the version due to OCPBUGS-53898.
Fixes #OCPBUGS-53898
**Checklist**

OCPBUGS-53898: bump golang-jwt v4 and v5

---

go.mod
go.sum
vendor/modules.txt

This commit bumps CAPZ to v1.19.2 to include the patch for the memory leak related to NewBatchSpanProcessor. Incidentally, this also bumps CAPI to v1.9.6.
More details on the leak: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/5410 
N/A
**Checklist**

NO-JIRA: Bump CAPZ to v1.19.2

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/modules.txt

Need to bump the version due to OCPBUGS-53899.
Fixes #OCPBUGS-53899
**Checklist**

OCPBUGS-53899: bump golang-jwt v4

---

hypershift-operator/controllers/nodepool/openstack/openstack.go
hypershift-operator/controllers/nodepool/openstack/openstack_test.go

Avoids setting DisablePortSecurity by default to prevent failures when networks
are project-owned and the default Neutron policy won't allow explicit port security
options.

OCPBUGS-54763: openstack: set port security only if explicitly specified

---

control-plane-operator/controllers/hostedcontrolplane/kas/config.go
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/kas/config.go

Cherry pick of #5760 on release-4.18.
#5760: Set shutdown watch termination grace period on kas
```release-note
```

[release-4.18] OCPBUGS-53404: Set shutdown watch termination grace period on kube-apiserver

---

support/certs/tls.go
test/e2e/create_cluster_test.go
test/e2e/util/util.go
test/e2e/util/util_test.go

This PR addresses the customer use case of using a KAS custom serving certificate in combination with the `KubeAPIServerDNSName` API. This setup enables the user to access the new API custom DNS name using the custom certificate they provided.
Fixes #[CNTRLPLANE-217](https://issues.redhat.com/browse/CNTRLPLANE-217)
|Index|Status|Job|Info|
|---|---|---|---|
| 1 | 🟢 | [Link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/5968/pull-ci-openshift-hypershift-main-e2e-aws/1910379370497708032) | N/A|
| 2 | 🔴 | [Link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_hypershift/5968/pull-ci-openshift-hypershift-main-e2e-aws/1910424321671565312) |TestUpgradeControlPlane/Teardown |
| 3 | 🔴 | …

CNTRLPLANE-217: Add E2E to KubeAPIServerDNSName API to cover KAS custom certificate

---

api/karpenter/v1beta1/karpenter_types.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
karpenter-operator/controllers/karpenter/machine_approver_test.go
karpenter-operator/controllers/karpenter/manifests.go
karpenter-operator/controllers/karpenter/manifests_test.go
vendor/github.com/openshift/hypershift/api/karpenter/v1beta1/karpenter_types.go

Allows the karpenter-provider-aws image to be overriden by an HCP annotation.
~We need this in order to test/e2e our OpenShift karpenter-provider-aws image since it's not in the release payload yet.~ This is a helpful quality of life change to allow devs to test different aws-karpenter-provider versions with HyperShift autonode.
**Checklist**

AUTOSCALE-127: allow karpenter-provider-aws image to be overriden by hcp annotation

---

control-plane-operator/controllers/hostedcontrolplane/kas/kms/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/kas/kms/azure.go

This commit sets the Azure KMS configuration to the apiVersion, which is v2 by default.
Fixes [OCPBUGS-54916](https://issues.redhat.com/browse/OCPBUGS-54916)
**Checklist**

OCPBUGS-54916: Set Azure KMS Configuration to v2

---

cmd/nodepool/openstack/create.go

A follow-up from 59ca93668729a35abd6faecee145055720f06ecb
The CLI was mapping CLI options to a struct and the bool was False by
default so disable port security was false which was enabling port
security in the spec, which we try to avoid in this bug fix.

OCPBUGS-54763: openstack/cli: only set port security when specified

---

control-plane-operator/controllers/hostedcontrolplane/pki/ovn_control_plane_metrics.go

This commit updates the DNS names for ovn-kubernetes-control-plane from ovnkube-control-plane to ovn-kubernetes-control-plane. This is what is expected by the cluster network operator.
Fixes [OCPBUGS-54533](https://issues.redhat.com/browse/OCPBUGS-54533)
**Checklist**

OCPBUGS-54533: Update DNS names for ovn-kubernetes cp metrics

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/v2/cno/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/cno/deployment.go
support/config/constants.go

Reverts openshift/hypershift#5860
This PR:
- was originally introduced in https://github.com/openshift/hypershift/pull/5837
- It was previously reverted [here](https://github.com/openshift/hypershift/pull/5860) by @kyrtapz as the change affected CNCC on azure standalone. Example [here](https://sippy.dptools.openshift.org/sippy-ng/component_readiness/test_details?Aggregation=none&Architecture=amd64&Architecture=amd64&FeatureSet=techpreview&FeatureSet=techpreview&Installer=ipi&Installer=ipi&LayeredProduct=none&Network=ovn&Network=ovn&Platform=azure&Platform=azure&Procedure=none&Suite=serial&Suite=serial&Topology=ha&Topology=ha&Upgrade=none&Upgrade=none&baseEndTime=2025-03-17%2023%3A59%3A59&baseRelease=4.18&baseStartTime=2025-02-15%2000%3A00%3A00&capability=EgressIP&columnGroupBy=Architecture …

Revert "Revert "CNTRLPLANE-112: Enable MIv3 for CNO/CNCC on managed Azure""

---

test/e2e/util/util.go

https://github.com/openshift/hypershift/pull/6004 removed `csi-snapshot-webhook` from the excluded prefixes, however, the webhook is only removed back to 4.18.  4.16 and 4.17 still have it and it still needs to be excluded.
This is causing payload test failures.

NO-JIRA: version check csi-snapshot-webhook for EnsureSATokenNotMountedUnlessNecessary

---

api/hypershift/v1beta1/hostedcluster_types.go
control-plane-operator/controllers/hostedcontrolplane/kas/config.go
control-plane-operator/controllers/hostedcontrolplane/kas/params.go
control-plane-operator/controllers/hostedcontrolplane/v2/kas/config.go
control-plane-operator/controllers/hostedcontrolplane/v2/kas/params.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

Add support to override the --goaway-chance parameter for the kube-apiserver. The default will remain the previously hardcoded value of 0.
Fixes #https://issues.redhat.com/browse/OCPBUGS-54863
**Checklist**

OCPBUGS-54863: Add annotation to configure KAS goaway-chance

---

kas-bootstrap/kas_boostrap.go
test/e2e/util/util.go

This was introduced here https://github.com/openshift/hypershift/pull/5871 It shouldn't be needed now https://github.com/openshift/hypershift/pull/5937 is merged
Fixes #
**Checklist**

NO-JIRA: Remove kas from EnsureNoCrashingPods exceptions

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/v2/ingressoperator/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/ingressoperator/deployment.go
control-plane-operator/controllers/hostedcontrolplane/v2/registryoperator/deployment.go
support/azureutil/azureutil.go
support/azureutil/azureutil_test.go
support/config/constants.go

This PR:
- enables managed identity version 3 for ingress on managed azure, ARO HCP
- removes unneeded managed Azure environment variables now that all HO, HCP, and OpenShift operators support managed identity version 3
Fixes [CNTRLPLANE-112](https://issues.redhat.com/browse/CNTRLPLANE-112)
**Checklist**

CNTRLPLANE-112: Enable MIv3 for Ingress

---

test/e2e/karpenter_test.go

Fixes the test by grabbing the correct part of the string from node.Status.NodeInfo.OSImage that now points to the rhcos version. See https://github.com/openshift/release/pull/63681#issuecomment-2816838538 as to why we need this.
Fixes #
**Checklist**

AUTOSCALE-127: fix e2e autonode drift test

---

contrib/managed-azure/setup_etcd_kv.sh
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/kas/deployment.go
control-plane-operator/controllers/hostedcontrolplane/kas/kms/azure.go
control-plane-operator/controllers/hostedcontrolplane/kas/params.go
control-plane-operator/controllers/hostedcontrolplane/kas/secretencryption.go
control-plane-operator/controllers/hostedcontrolplane/manifests/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/kas/kms/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/kas/params.go
docs/content/how-to/azure/create-azure-cluster-with-options.md
docs/content/how-to/azure/scheduler.md
docs/mkdocs.yml
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
support/azureutil/azureutil.go
support/config/constants.go

This PR:
- updates Azure KMS implementation by updating the encryption configuration to only support v2 parameters
- have Azure KMS use it's own Azure authentication configuration; previously, it was reusing CP/CCM configuration
- reorders some of the Azure how-to pages in our docs
- adds a how-to section on setting up and verifying etcd encryption
Fixes [CNTRLPLANE-111](https://issues.redhat.com//browse/CNTRLPLANE-111)
**Notes to Reviewers**:
- The first commit contains the actual code changes. The other commits are docs related.
- CacheSize: ptr.To\[int32\]\(100\), was removed because it is not valid for v2
**Checklist**

CNTRLPLANE-111: Support KMSv2 encryption encryption for ARO HCP, with MIv3

---

test/e2e/e2e_test.go
test/e2e/util/options.go

This commit adds two e2e flags that will be needed to test the Azure KMS configuration in e2e-aks.
N/A
**Checklist**

NO-JIRA: Add e2e flags to test Azure KMS

---

hypershift-operator/controllers/nodepool/token.go
hypershift-operator/controllers/nodepool/token_test.go

This PR ensures that if the proxy set for a HostedCluster has a TrustedCA set, then the that CA will be included in the nodes ignition config. 
**Checklist**

OCPBUGS-44439: Add proxy trustedCA to ignition config

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

Ensures that the control-plane-operator service account contains a reference to the control plane pull secret.
Fixes #[OCPBUGS-55433](https://issues.redhat.com/browse/OCPBUGS-55433)
**Checklist**

OCPBUGS-55433: Add control plane pull secret reference to control-plane-operator SA

---

Containerfile.control-plane
Containerfile.operator
Dockerfile
Dockerfile.control-plane
Dockerfile.dev
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go

Adds a commented label to the CPO image that should be uncommented whenever we switch to using CPO v2 as the default. Uses that label (and annotation) to determine whether we should remediate expired certs from the hypershift operator.
We were previously using the HC version, assuming that 4.19 would default to CPOv2, but that won't be the case.
Fixes #[OCPBUGS-53206](https://issues.redhat.com/browse/OCPBUGS-53206)
**Checklist**

OCPBUGS-53206: Use a CPO image label to determine whether to run expired cert remediation

---

control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-apiserver/deployment.yaml

This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/6016.
Similar to what was implemented for OpenShift IPI, the liveness and readiness probes associated with the OpenShift apiserver are updated to use the /livez (for liveness probe) and /readyz (for readiness probe) endpoints instead of the /healthz endpoint.
Fixes #
https://issues.redhat.com/browse/OCPBUGS-55148
**Checklist**

[release-4.18] OCPBUGS-55148: Update OpenShift apiserver liveness and readiness probe endpoints to livez and readyz

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Preserve_existing_resources.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Private_apiserver_connectivity__proxy_apiserver_address_is_unset.yaml
control-plane-operator/controllers/hostedcontrolplane/ingressoperator/ingressoperator.go
control-plane-operator/controllers/hostedcontrolplane/kas/kms/aws.go
control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
control-plane-operator/controllers/hostedcontrolplane/oauth/params.go
control-plane-operator/controllers/hostedcontrolplane/olm/operator.go
control-plane-operator/controllers/hostedcontrolplane/olm/packageserver.go
control-plane-operator/controllers/hostedcontrolplane/olm/testdata/zz_fixture_TestReconcileCatalogOperatorDeployment_Preserve_existing_resources.yaml
control-plane-operator/controllers/hostedcontrolplane/olm/testdata/zz_fixture_TestReconcileOLMOperatorDeployment_Preserve_existing_resources.yaml
control-plane-operator/controllers/hostedcontrolplane/registryoperator/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/registryoperator/testdata/zz_fixture_TestReconcileDeployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/oauth-openshift/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-oauth-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/kas/kms/aws.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
support/controlplane-component/konnectivity-container.go
support/util/cloudprovidercreds.go
support/util/manifests.go

This is a manual cherry-pick of https://github.com/openshift/hypershift/pull/5897. 
The steady-state memory utilization of socks5 proxy, konnectivity proxy, http proxy, and token minter containers is approximately ~30Mi. This PR bumps `apiserver-token-minter`, `init-client-token-minter`, `client-token-minter`, `cloud-token-minter`, `token-minter`, `konnectivity-proxy`, `konnectivity-proxy-socks5`, `konnectivity-proxy-https`, `socks5-proxy`, `http-proxy` container requests to 30Mi to reflect this usage.  The total persistent (non-init container) memory increase per HCP is ~200Mi. …

[release-4.18] OCPBUGS-54737: Bump socks5 proxy, konnectivity proxy, http proxy, token minter memory requests

---

support/supportedversion/version.go
support/supportedversion/version_test.go
test/e2e/util/version.go

For supporting 4.20 after branch cut.  Wait for branch cut before merging.
/hold

NO-JIRA: bump HO supported version to 4.20

---

.golangci.yml
availability-prober/availability_prober.go
cmd/bastion/aws/create.go
cmd/bastion/aws/destroy.go
cmd/cluster/core/create.go
cmd/infra/aws/destroy.go
cmd/infra/aws/destroy_iam.go
cmd/infra/powervs/create.go
cmd/infra/powervs/destroy.go
cmd/install/install.go
control-plane-operator/controllers/hostedcontrolplane/kcm/deployment_test.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/main.go
dnsresolver/cmd.go
etcd-defrag/etcddefrag_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
hypershift-operator/controllers/nodepool/capi.go
hypershift-operator/controllers/nodepool/capi_test.go
hypershift-operator/main.go
ignition-server/controllers/local_ignitionprovider.go
konnectivity-https-proxy/cmd.go
pkg/etcdcli/etcdcli.go
support/config/deployment.go
support/releaseinfo/releaseinfo.go
support/thirdparty/kubernetes/pkg/credentialprovider/config.go
support/thirdparty/library-go/pkg/image/registryclient/client.go
support/upsert/loopdetector.go
test/e2e/util/node.go
test/e2e/util/oauth.go

This PR:
- enables the last default linter in golangci-lint: staticcheck
- fixes all the issues discovered by staticcheck
[CNTRLPLANE-265](https://issues.redhat.com//browse/CNTRLPLANE-265)
**Checklist**

CNTRLPLANE-265: Enable staticcheck linter in golangci-lint

---

.tekton/control-plane-operator-main-pull-request.yaml
.tekton/control-plane-operator-main-push.yaml
.tekton/hypershift-operator-main-pull-request.yaml
.tekton/hypershift-operator-main-push.yaml
Containerfile.control-plane
Containerfile.operator

Now that relaese-4.19 has branched out, we should only build main components until MCE is ready to start building mce-2.10.
Now that relaese-4.19 has branched out, we should only build main components until MCE is ready to start building mce-2.10.
Fixes #OCPBUGS-55357
**Checklist**

OCPBUGS-55357: Only build main branch components

---

support/util/imagemetadata.go
support/util/imagemetadata_test.go

The reference.Parse function tries to retrieve the whole entry string, but if the entry reference does not contain Namespace and Name but registry, it will return the Registry field as the Name which is not a good behavior. We added the proper changes to have this in consideration and return the right override. Also we covered it with the unit test to avoid regressions.
- Fixes [OCPBUGS-54483](https://issues.redhat.com/browse/OCPBUGS-54483)

OCPBUGS-54483: Add support for registry root entry only in the IDMS/ICSP

---

control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go
control-plane-operator/controllers/hostedcontrolplane/testdata/etcd/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/etcd/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/etcd/statefulset.yaml

Enables pprof in hosted etcd, similar to self-managed or not-hypershift openshift deployments (re-opened from previous [PR](https://github.com/openshift/hypershift/pull/2245) that staled out)
Fixes #[CNTRLPLANE-261](https://issues.redhat.com/browse/CNTRLPLANE-261)
**Checklist**

CNTRLPLANE-261: Enable pprof in hosted control plane etcd

---

cmd/install/assets/hypershift_operator.go
cmd/install/install.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
hypershift-operator/controllers/nodepool/nodepool_controller.go
support/releaseinfo/fake/fake.go
support/releaseinfo/testutils/testutils.go
support/util/resources.go
support/util/resources_test.go

This PR allows the HostedCluster to only watch platform specific resources based on what platforms installed in the HO. If the HO does not limit the platform CRDs installed, the HostedCluster watches all platform CRDs as it did before this PR.
[CNTRLPLANE-709](https://issues.redhat.com/browse/CNTRLPLANE-709)
**Checklist**

CNTRLPLANE-709: Add ability to limit platform specific resources managed by HostedCluster

---

control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-apiserver/deployment.yaml

- This blocks the creation of other containers specifically the bootstrap container until kas is ready.
Fixes #
**Checklist**

OCPBUGS-55504: Add postStart hook to kube-apiserver container

---

control-plane-operator/controllers/hostedcontrolplane/oapi/deployment.go
control-plane-operator/controllers/hostedcontrolplane/oapi/deployment_test.go
control-plane-operator/controllers/hostedcontrolplane/oapi/oauth_deployment.go
control-plane-operator/controllers/hostedcontrolplane/oapi/params.go
support/util/util.go
support/util/util_test.go

Backport PR https://github.com/openshift/hypershift/pull/6026 to release-4.15 manually.
Finished pre-merge testing for the PR, detail see https://issues.redhat.com/browse/OCPBUGS-55266?focusedId=27046163&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-27046163, looks good.

OCPBUGS-55266: [release-4.15] Add konnectivity-proxy sidecar to openshift-oauth-apiserver

---

cmd/cluster/agent/create_test.go
cmd/cluster/agent/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/aws/create_test.go
cmd/cluster/azure/create_test.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_complicated_invocation_from_bryan.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_KubeAPIServerDNSName.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_availability_ones.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_disabled_capabilities.yaml
cmd/cluster/core/create.go
cmd/cluster/core/create_test.go
cmd/cluster/kubevirt/create_test.go
cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_test_from_dvossel.yaml
cmd/cluster/none/create_test.go
cmd/cluster/none/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/openstack/create_test.go
cmd/cluster/powervs/create_test.go
cmd/cluster/powervs/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml

Enforces --name and --pull-secret flag requirements to Hypershift create cluster command since omitting them can lead to misconfigured deployments.
Fixes #[OCPBUGS-37323](https://issues.redhat.com/browse/OCPBUGS-37323)
[Original closed PR](https://github.com/openshift/hypershift/pull/5618)
**Checklist**

OCPBUGS-37323: MarkPersistentFlagRequired does not work since CLI refactoring

---

control-plane-operator/controllers/hostedcontrolplane/testdata/certified-operators-catalog/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/certified-operators-catalog/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/community-operators-catalog/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/community-operators-catalog/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/etcd/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/etcd/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/featuregate-generator/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/featuregate-generator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/olm-collect-profiles/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/olm-collect-profiles/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/redhat-marketplace-catalog/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/redhat-marketplace-catalog/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/redhat-operators-catalog/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/redhat-operators-catalog/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
support/controlplane-component/controlplane-component.go
support/controlplane-component/controlplane-component_test.go
support/controlplane-component/cronjob.go
support/controlplane-component/defaults.go
support/controlplane-component/deployment.go
support/controlplane-component/job.go
support/controlplane-component/statefulset.go
support/upsert/apply.go
test/e2e/util/util.go

This removes the usage of the legacy DeploymentConfig from cpov2 and moves all the PodTemplateSpec defaulting logic to the ControlPlaneComponent. This includes setting annotations, labels, isolation, colocation, spread, etc.
Fixes #
**Checklist**

CNTRLPLANE-269: Remove DeploymentConfig usage from cpov2

---

support/controlplane-component/job.go
support/controlplane-component/job_test.go

This fixes the issue of the controller failing to update ControlPlaneComponent status condition on older versions of openshift/k8s management clusters where the job controller doesn't set the reason and message fields in the Job conditions.
Fixes #
**Checklist**

OCPBUGS-55913: Fix Job status returning empty reason and message

---

control-plane-operator/controllers/hostedcontrolplane/v2/kas/auth.go
control-plane-operator/controllers/hostedcontrolplane/v2/kas/auth_test.go
control-plane-operator/controllers/hostedcontrolplane/v2/kas/auth_types.go

Fixes a bug where the serialization of the structured authentication configuration did not match what the Kubernetes API Server expected. This bug was caught by @xiuwang and verified with https://gcsweb-qe-private-deck-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/qe-private-deck/logs/periodic-ci-openshift-openshift-tests-private-release-4.19-amd64-nightly-aws-ipi-ovn-hypershift-guest-ext-oidc-f7/1920466811413860352/artifacts/aws-ipi-ovn-hypershift-guest-ext-oidc-f7/dump/artifacts/namespaces/clusters-399a60807bc2b200e257/core/pods/logs/kube-apiserver-56865d469f-q6mx8-kube-apiserver.log . For those without the ability to access this, when configuring the authentication spec to use an external OIDC provider the Kubernetes API Server would enter a …

NO-JIRA: cpov2: fix structured authentication configuration serialization

---

cmd/nodepool/core/create.go
cmd/nodepool/create.go
contrib/managed-azure/setup_aks_cluster.sh
docs/content/getting-started.md
docs/content/how-to/automated-machine-management/node-tuning.md
docs/content/how-to/aws/create-aws-hosted-cluster-arm-workers.md
docs/content/how-to/azure/create-azure-cluster-with-options.md
docs/content/how-to/azure/create-azure-cluster_on_aks.md
docs/content/how-to/kubevirt/create-kubevirt-cluster.md
docs/content/how-to/openstack/additional-ports.md
docs/content/how-to/openstack/az.md
docs/content/how-to/openstack/performance-tuning.md
product-cli/cmd/nodepool/create.go

This PR changes the `--node-count` flag to be renamed to `--replicas` so that it is consistent with what the term is called in the API.
Fixes #[CNTRLPLANE-645](https://issues.redhat.com/browse/CNTRLPLANE-645)
**Checklist**

CNTRLPLANE-645: Rename NodeCount flag to Replicas

---

support/util/imagemetadata.go
support/util/imagemetadata_test.go

Manual cherry pick of https://github.com/openshift/hypershift/pull/6100

[release-4.19] OCPBUGS-55693: Add support for registry root entry only in the IDMS/ICSP

---

.tekton/hypershift-cli-mce-29-push.yaml
.tekton/hypershift-release-mce-29-push.yaml
Containerfile.cli

For MCE 2.9 multi-arch build.
Fixes #OCPBUGS-56036
**Checklist**

OCPBUGS-56036: add multi-arch build for MCE 2.9

---

Containerfile.cli
Containerfile.control-plane
Containerfile.operator

For a time, there was no red hat catalog image that had go 1.23.6. Now that it is available, we need to use it.
Fixes #OCPBUGS-56205
**Checklist**

OCPBUGS-56205: Switch back to rh catalog

---

test/e2e/upgrade_hypershift_operator_test.go

This PR updates the "Upgrade HO operator" test by modifying the upgrade-invariant verification logic to require consistent success over a five-minute period.
This change ensures we catch scenarios where node rollout is delayed and the `MachineDeployment` generation changes after some time—cases that the previous implementation could miss.

NO-JIRA: Keep checking for rollouts during upgrade HO test for five minutes

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
hypershift-operator/main.go

The test was failing locally because it was not creating any configMaps. This PR adds a temp file to allow the test to always created openshift-config-managed-trusted-ca-bundle configmap and pass locally.
Fixes #
**Checklist**

NO-JIRA: Fix TestHostedClusterWatchesEverythingItCreates not working locally

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/params.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/reconcile.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
hypershift-operator/controllers/sharedingress/router.go
test/e2e/util/util.go

This PR removes more DeploymentConfig usage across our codebase by replacing directly with corev1 types.
Fixes #
**Checklist**

CNTRLPLANE-844: Remove DeploymentConfig usage

---

control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-controller-manager/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-controller-manager/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-controller-manager/config.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/ocm/testdata/zz_fixture_TestReconcileOpenShiftControllerManagerConfig_WithAllCapabilitiesEnabled.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/ocm/testdata/zz_fixture_TestReconcileOpenShiftControllerManagerConfig_WithImageRegistryCapabilityDisabled.yaml

OCM is being refactored to use library-go, which also means that the custom leader election lock name is not hard-coded in the executable any more and must be set in the config. And that is what this patch does.
Related to:
* https://issues.redhat.com/browse/WRKLDS-1676
* https://github.com/openshift/openshift-controller-manager/pull/378 
**Checklist**

WRKLDS-1676: ocm config: Update leaderElection.name

---

control-plane-operator/controllers/hostedcontrolplane/kas/config.go
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-apiserver/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/kas/config.go

Disables Pod Security Admission by setting the enforce policy to `privileged` for HyperShift hosted control planes.
We are not yet ready to roll out the PSA enforcement on `restricted`.
- Changes based on [OCPBUGS-45600](https://issues.redhat.com/browse/OCPBUGS-45600)
- [OCP issue](https://issues.redhat.com//browse/OCPBUGS-56773)
- [OCP PR](https://github.com/openshift/api/pull/2346)

OCPBUGS-56777: Disable PSA enforcement in 4.19 hosted cluster

---

shared-ingress/Containerfile

Now that UBI 10 is no longer in beta state, we should move to the GA version.
Fixes #[CNTRLPLANE-201](https://issues.redhat.com//browse/CNTRLPLANE-201)
**Checklist**

CNTRLPLANE-201: feat(shared-ingress): Bump ubi10 out of beta

---

.tekton/control-plane-operator-4-19-push.yaml

CPO might run on both arm64 and amd64. We need to build both in case we need to override in either.
Fixes #[CNTRLPLANE-831](https://issues.redhat.com//browse/CNTRLPLANE-831)
**Checklist**

CNTRLPLANE-831: feat(konflux): add arm64 builds to cpo pipeline

---

docs/content/how-to/aws/define-custom-kube-api-name.md

Small doc fix on `KubeAPIServerDNSName` field

NO-JIRA: Fix documentation field name for KubeAPIServerDNSName

---

control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-controller-manager/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/openshift-controller-manager/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/openshift-controller-manager/deployment.yaml

As OCM is being migrated to use `library-go`, further config changes are needed as `library-go` only supports  certain ways how to configure things. This change includes in particular:
* Update deployment.yaml to set --kubeconfig and --namespace.
* Define POD_NAME and POD_NAMESPACE env variables.
The current OCM implementation supports the given flags, but ignores them so that the service does not crash.
Blocks the following PR: https://github.com/openshift/openshift-controller-manager/pull/378

WRKLDS-1676: ocm: Make config compatible with library-go

---

api/hypershift/v1beta1/hostedcluster_conditions.go
api/hypershift/v1beta1/hostedcluster_types.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/recovery/recovery.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
docs/content/reference/api.md
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_conditions.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

This PR includes a new annotation and a new condition for the hosted clusters that has been restored using the HCP OADP plugin.
- Annotation: `hypershift.openshift.io/restored-from-backup`
- Condition: `HostedClusterRestoredFromBackup`
The annotation will be included by the plugin on restored clusters. The HC Controller bubbles down the annotation to the HCP and the HCCO triggers a procedure that makes sure the recovery is done properly through some concrete checks in the DataPlane side.
Once the HCCO detects `HostedClusterRestoredFromBackupAnnotation` annotation it begins the recovery actions and sets the new condition called HostedClusterRestoredFromBackup. 
It will stays on False until all the procedures and checks ends properly. After that the HCCO sets the new condition signaling the …

OCPBUGS-56430: Add DR operations after HC restoration

---

support/catalogs/images.go
support/util/imagemetadata.go

- Small fixes requested from https://github.com/openshift/hypershift/pull/6192. Includes:
- Set some constants
- Use a logger instead of `fmt.Println`

NO-JIRA: Follow up PR from #6192

---

test/e2e/control_plane_upgrade_test.go
test/e2e/e2e_test.go

For the `e2e-aws-upgrade` job, there is minor (y-stream) skew between `initial` and `latest` releases.
The current version checking code just uses the `latest` image for the version checks but, on `TestUpgradeControlPlane`, `inital` can be minor skew, which can result in checks not being gated properly pre-upgrade.
This PR sets the version to be that of `initial` then switches it to `latest` in `TestUpgradeControlPlane` after the initial rollout checks, but before the HCP upgrade begins.

OCPBUGS-56930: test/e2e: fix version gate checks on minor upgrade

---

konnectivity-https-proxy/cmd.go
konnectivity-https-proxy/cmd_test.go

When a HostedCluster is configured with a proxy URL such as http://user:pass@host, the authentication header was not getting forwarded by the konnectivity proxy to the user proxy, failing authentication. This commit adds code to send the proper header when a user and password is specified in the proxy URL.
Fixes #[OCPBUGS-42938](https://issues.redhat.com/browse/OCPBUGS-42938)
**Checklist**

OCPBUGS-42938: Support proxy authentication when user/pass is included in URL

---

control-plane-operator/controllers/hostedcontrolplane/v2/assets/assets.go
support/api/scheme.go

Introduces a new Scheme and YAML serializer that includes both RHOBS and CoreOS monitoring types when RHOBS is enabled. The new YAML serializer is only used to deserialize manifests for resources we apply.
Follow up to #6228
Fixes #[OCPBUGS-57125](https://issues.redhat.com/browse/OCPBUGS-57125)
**Checklist**

OCPBUGS-57125: Support deserializing monitoring manifests when RHOBS enabled

---

cmd/install/assets/hypershift_operator.go
control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/controller.yaml
control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/files/infra_role.yaml
control-plane-operator/controllers/hostedcontrolplane/csi/kubevirt/kubevirt.go
control-plane-operator/controllers/hostedcontrolplane/testdata/kubevirt-csi-controller/TechPreviewNoUpgrade/zz_fixture_TestControlPlaneComponents_kubevirt_csi_controller_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kubevirt-csi-controller/TechPreviewNoUpgrade/zz_fixture_TestControlPlaneComponents_kubevirt_csi_role.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kubevirt-csi-controller/zz_fixture_TestControlPlaneComponents_kubevirt_csi_controller_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kubevirt-csi-controller/zz_fixture_TestControlPlaneComponents_kubevirt_csi_role.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kubevirt-csi-controller/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kubevirt-csi-controller/infra_role.yaml
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

This is basically about adapting RBAC for this CSI driver upstream PR:
https://github.com/kubevirt/csi-driver/pull/138
So that we can safely consume this change in the openshift fork.
Fixes #
**Checklist**

CNV-61396: Sync RBAC for expansion support in kubevirt CSI driver

---

hypershift-operator/controllers/nodepool/aws.go
hypershift-operator/controllers/nodepool/aws_test.go

The HO aws creds are usually different from the workload account  where capacity reservation is created, which means it can't perform those validations.
Fixes #
**Checklist**

OCPBUGS-56861: Remove CapacityReservation validation that requires aws access

---

hypershift-operator/controllers/nodepool/apiserver-haproxy/haproxy.go
hypershift-operator/controllers/nodepool/apiserver-haproxy/haproxy_test.go
hypershift-operator/controllers/nodepool/apiserver-haproxy/testdata/zz_fixture_TestAPIServerHAProxyConfig_when_IBM_cloud_platform_it_should_use_livez_as_liveness_probe_endpoint.yaml
hypershift-operator/controllers/nodepool/apiserver-haproxy/testdata/zz_fixture_TestReconcileHAProxyIgnitionConfig_IBMCloud_cluster_uses_livez_for_liveness_probe_endpoint.yaml

**What this PR does / why we need it**: /livez is faster and more reliable than /version. We should prefer /livez/ping when possible.
Fixes #https://issues.redhat.com/browse/OCPBUGS-45265
**Checklist**

OCPBUGS-45265: Don't use /version for haproxy health checks

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

make sure the change of kubevirt platform would not cause aws and other platform failures

CNV-61396: set kubevirt cis rbac valid only for kubevirt platform

---

.golangci.yml
cmd/infra/powervs/create.go
cmd/install/assets/assets.go
cmd/install/assets/hypershift_operator_test.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/kas/auth.go
control-plane-operator/controllers/hostedcontrolplane/v2/kas/auth.go
control-plane-operator/hostedclusterconfigoperator/controllers/drainer/drainer.go
control-plane-pki-operator/certificatesigningcontroller/certificateloadingcontroller_test.go
hypershift-operator/controllers/manifests/controlplanepkioperator/manifests.go
hypershift-operator/controllers/nodepool/aws_test.go
hypershift-operator/controllers/nodepool/capi.go
hypershift-operator/controllers/nodepool/conditions.go
hypershift-operator/controllers/nodepool/config.go
hypershift-operator/controllers/nodepool/config_test.go
support/capabilities/management_cluster_capabilities.go
support/certs/tls.go
support/controlplane-component/controlplane-component_test.go
support/util/imagemetadata_test.go
support/util/util.go
test/e2e/util/util.go
test/integration/framework/hosted-cluster.go

This PR adds misspell linter to the list of enabled golanci-lint linters and fixes all the spelling mistakes.
N/A
**Checklist**

NO-JIRA: Add misspell to golangci-lint

---

control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-network-operator/TechPreviewNoUpgrade/zz_fixture_TestControlPlaneComponents_cluster_network_operator_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-network-operator/zz_fixture_TestControlPlaneComponents_cluster_network_operator_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/cno/deployment.go

The BGP feature added a new image to the payload, `metallb-frr`, since 4.19. This image is not used by default and has to be enabled through CNO config. For 4.19, tech-preview feature set needs to be enabled as of today but there are plans to promote it to the default feature set in a 4.19.z release.

CORENET-6094: CNO: add FRR-k8s image

---

hypershift-operator/controllers/nodepool/agent.go
hypershift-operator/controllers/nodepool/aws.go
hypershift-operator/controllers/nodepool/aws_test.go
hypershift-operator/controllers/nodepool/azure.go
hypershift-operator/controllers/nodepool/azure_test.go
hypershift-operator/controllers/nodepool/capi.go
hypershift-operator/controllers/nodepool/capi_test.go
hypershift-operator/controllers/nodepool/kubevirt.go
hypershift-operator/controllers/nodepool/openstack.go
hypershift-operator/controllers/nodepool/powervs.go
test/e2e/nodepool_autorepair_test.go
test/e2e/nodepool_day2_tags_test.go
test/e2e/nodepool_test.go

Currently changing the `resourceTags` field on the HostedCluster or `Tags` field on the NodePool will cause a rolling upgrade of all the nodes. This PR allows tags changes to be updated in-place.
Fixes #
**Checklist**

CNTRLPLANE-995: Support in-place update of AWS tags

---

hypershift-operator/controllers/hostedcluster/metrics/metrics.go
hypershift-operator/controllers/hostedcluster/metrics/metrics_test.go

It adds 2 metrics for Hosted Control Plane (HCP) on Azure.
For Managed HCP it adds metric: `hosted_cluster_managed_azure_info` with the following labels:
- _id
- name
- namespace
- location
- microsoft_subscription_id
- microsoft_resource_group_name
- microsoft_resource_type
- microsoft_resource_id
For not managed HCP it adds metric `hosted_cluster_azure_info` with the following labels:
- _id
- name
- namespace
- location
- microsoft_subscription_id
- microsoft_resource_group_name
The two metrics are mutually exsclusive.
Fixes #[CNTRLPLANE-902](https://issues.redhat.com//browse/CNTRLPLANE-902)
**Checklist**
- [x ] This change includes unit tests.

CNTRLPLANE-902:  New metrics for HCP Azure

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
support/globalconfig/authentication.go
support/globalconfig/authentication_test.go

Clean 4.19 backport of https://github.com/openshift/hypershift/pull/6227

[release-4.19] CNTRLPLANE-374: hcco: handle post-install creation of OIDC client secrets

---

hypershift-operator/controllers/nodepool/powervs.go

Recent changes in IBM PowerVS have introduced stricter validation on image names, disallowing the use of dots (.)
Attempting to import an image with a name like` 418.94.202501221327-0` results in the following error:
`Bad Request: 418.94.202501221327-0 is not a valid image name. the image name does not meet the resource naming standards.`
Due to this PowerVS Hypershift deployments are failing.
This PR resolves the above mentioned issue by replacing all dots with hyphens (-) in PowerVS image name.
Fixes # https://issues.redhat.com/browse/OCPBUGS-49812
**Checklist**

OCPBUGS-49812: Sanitize PowerVS image name to comply with updated naming standards

---

docs/content/how-to/aws/create-aws-hosted-cluster-autonode.md
docs/mkdocs.yml

Create Autonode deployment documentation to install HyperShift AutoNode feature (powered by Karpenter), controller and Karpenter operator, and hosted cluster with Karpenter support. A sample application is also added as example consuming Karpenter objects (NodePool) to scale OpenShift nodes.
Credits: this document is based in the original [guide][gdocs-guide] created by @enxebre, modified to run e2e manual feature validation in the development phase, addressing/documenting any known issue and caveat - the final version must remove any non-feature specific item (such as management cluster installation).
[gdocs-guide]: https://docs.google.com/document/d/1dnUX6TRi6eZns9dnbcqwAvVHo82vmeWAx17Wgf0D8qE/edit?tab=t.0#heading=h.evejrrs09c1b
**Which issue(s) …

HOSTEDCP-2253: doc/aws-autoNode: initial deployment guide

---

go.mod
support/releaseinfo/registryclient/client.go
support/thirdparty/oc/pkg/cli/image/manifest/README.md
support/thirdparty/oc/pkg/cli/image/manifest/manifest.go
support/util/imagemetadata.go

This PR tries to help resolve the intermittent issue seen [here](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.20-periodics-e2e-aks/1937299784293421056) by updating the copied `oc` third party code. The code was copied instead of called directly in order to avoid the go.mod changes that were required when calling the oc functions directly.
Part of [CNTRLPLANE-777](https://issues.redhat.com/browse/CNTRLPLANE-777)
**Checklist**

CNTRLPLANE-777: Update manifest.go to use latest oc committed code

---

Containerfile.control-plane
hack/tools/git-hooks/cpo-containerfiles-in-sync.sh

Since the Red Hat catalog go-toolset runs as a user with id = 1001, we need to make sure that the COPY instruction reflects that.
Fixes #
**Checklist**

ACM-21713: fix(konflux): go-toolset runs as default(1001)

---

konnectivity-https-proxy/cmd.go
konnectivity-https-proxy/cmd_test.go

It backports fix  for OCPBUGS-42938 to 4.19 stream
Original PR: https://github.com/openshift/hypershift/pull/6207

OCPBUGS-58335: Support proxy authentication when user/pass is included in URL

---

api/hypershift/v1beta1/hosted_controlplane.go
api/hypershift/v1beta1/hostedcluster_types.go
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AAA_ungated.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/AutoNodeKarpenter.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ClusterVersionOperatorConfiguration.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/DynamicResourceAllocation.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDC.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ExternalOIDCWithUIDAndExtraClaimMappings.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/ImageStreamImportMode.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/KMSEncryptionProvider.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedclusters.hypershift.openshift.io/OpenStack.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AAA_ungated.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/AutoNodeKarpenter.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ClusterVersionOperatorConfiguration.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/DynamicResourceAllocation.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDC.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ExternalOIDCWithUIDAndExtraClaimMappings.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/ImageStreamImportMode.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/KMSEncryptionProvider.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/NetworkDiagnosticsConfig.yaml
api/hypershift/v1beta1/zz_generated.featuregated-crd-manifests/hostedcontrolplanes.hypershift.openshift.io/OpenStack.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-Default.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedclusters-TechPreviewNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-CustomNoUpgrade.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-Default.crd.yaml
cmd/install/assets/hypershift-operator/zz_generated.crd-manifests/hostedcontrolplanes-TechPreviewNoUpgrade.crd.yaml
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hosted_controlplane.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

Increase MaxItems for ImageContentSources on
HostedControlPlaneSpec to match the number on HostedClusterSpec.
Also increase the MaxSize for mirrors to the same number,
number 25 is too limiting given the fact that standalone OpenShift
doesn't have any limit.
Fixes [OCPBUGS-57957](https://issues.redhat.com/browse/OCPBUGS-57957)
**Checklist**

OCPBUGS-57957: Increase MaxItems for Mirrors and ImageContentSources

---

control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_No_private_apiserver_connectivity__proxy_apiserver_address_is_set.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Preserve_existing_resources.yaml
control-plane-operator/controllers/hostedcontrolplane/cno/testdata/zz_fixture_TestReconcileDeployment_Private_apiserver_connectivity__proxy_apiserver_address_is_unset.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-network-operator/zz_fixture_TestControlPlaneComponents.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-network-operator/zz_fixture_TestControlPlaneComponents_TechPreviewNoUpgrade.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/cno/deployment.go

Manual backport of https://github.com/openshift/hypershift/pull/6290. 
Adds FRR image to both places building the CNO env vars.
Builds on https://github.com/openshift/hypershift/pull/6359.

OCPBUGS-57660: [release-4.19] CORENET-6094: CNO: add FRR-k8s image

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go

As the client secret name will be empty for public OIDC clients, HCCO should check if the secret ref name is the empty string before attempting to copy the secret.
This PR also adds proper unit tests for reconciling Auth OIDC clients. 
This PR is based on #6365 
Fixes #OCPBUGS-58149
**Checklist**

OCPBUGS-58149: fix(hcco): Don't fail for public OIDC clients with no client secret

---

support/controlplane-component/status.go

This is needed to make it work with 4.19 where the kas doesn't have a controlPlaneComponent resource
Fixes #
**Checklist**

OCPBUGS-58387: Add karpenter to skip api-server deps

---

support/pki/kas.go

PR #6114 backported code that did not include the service network DNS entries for the kube apiserver. This was ok in releases 4.17 and newer because in those releases a separate certificate is created to serve those service network DNS entries. However in 4.16 and older, there is only one serving certificate for the kube apiserver. This resulted in clients like ACM failing to communicate with the kube apiserver because they use the service network endpoint to install the klusterlet in the hosted cluster. This fix adds the missing entries back into the dns names of the KAS serving certificate. …

OCPBUGS-58506: [release-4.15] Add missing service network DNS entries to KAS cert

---

hypershift-operator/controlplaneoperator-overrides/assets/overrides.yaml

Applies the fix delivered with PRs #6393 and #6394 to to OCP versions 4.15.53, 4.15.54 and 4.16.43
Fixes #[OCPBUGS-58837](https://issues.redhat.com/browse/OCPBUGS-58837)
**Checklist**

OCPBUGS-58837: Override CPO image to apply KAS certificate hotfix

---

cmd/cluster/agent/create_test.go
cmd/cluster/agent/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/aws/create_test.go
cmd/cluster/aws/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/aws/testdata/zz_fixture_TestCreateCluster_minimal_with_KubeAPIServerDNSName.yaml
cmd/cluster/azure/create.go
cmd/cluster/azure/create_test.go
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_KubeAPIServerDNSName.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_availability_zones.yaml
cmd/cluster/azure/testdata/zz_fixture_TestCreateCluster_with_disabled_capabilities.yaml
cmd/cluster/core/create.go
cmd/cluster/core/create_test.go
cmd/cluster/kubevirt/create_test.go
cmd/cluster/kubevirt/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/none/create_test.go
cmd/cluster/none/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/openstack/create_test.go
cmd/cluster/openstack/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/cluster/powervs/create_test.go
cmd/cluster/powervs/testdata/zz_fixture_TestCreateCluster_minimal_flags_necessary_to_render.yaml
cmd/util/client.go
support/supportedversion/version.go
support/supportedversion/version_test.go
support/testutil/testutil.go

Updates the LookupDefaultOCPVersion function to use the multi-arch release API when a release stream is provided. This ensures consistency between when a release stream is provided and when it is not. We should also default to multi-arch whenever possible.
Fixes https://issues.redhat.com/browse/OCPBUGS-56701
**Checklist**

OCPBUGS-56701: Update the LookupDefaultOCPVersion function to use the multi-arch release API

---

.gitignore
.tekton/hypershift-operator-main-pull-request.yaml
.tekton/hypershift-operator-main-push.yaml
.tekton/hypershift-operator-main-tag.yaml
renovate.json

- Includes `renovate.json` in the root of the repo containing branchConcurrentLimit set to 10 in order to avoid flood the repository branches
- Include `dev/` folder to the gitIgnore
- https://docs.renovatebot.com/configuration-options/#branchconcurrentlimit
- https://konflux.pages.redhat.com/docs/users/patterns/keep-remote-pipelines-up-to-date.html#potential-drawbacks

CNTRLPLANE-1113: Add renovate configuration

---

.ci-operator.yaml
Containerfile.cli
Containerfile.control-plane
Containerfile.operator
Dockerfile
Dockerfile.control-plane
Dockerfile.dev
Dockerfile.e2e
api/go.mod
go.mod
hack/tools/go.mod
hack/workspace/go.work
vendor/modules.txt

This pull request cherry-picks https://github.com/openshift/hypershift/pull/6298 and updates the other Dockerfiles it missed
Fixes OCPBUGS-57742
**Checklist**

OCPBUGS-57742: Updating ose-hypershift-container image to be consistent with ART for 4.20

---

test/e2e/nodepool_machineconfig_test.go
test/e2e/util/eventually.go
test/e2e/util/util.go

The TestNTOMachineConfigGetsRolledOut and TestNTOMachineConfigAppliedInPlace tests 
were failing due to widespread Kubernetes API client rate limiting that prevented 
proper detection of NodePool configuration updates. This change addresses the 
persistent issue with more aggressive API call reduction:
- Increase polling intervals in WaitForNodePoolConfigUpdateComplete (1s→10s/15s)
- Extend timeouts for config update detection (1m→5m, 20m→25m) 
- Optimize DaemonSet and Node readiness polling intervals (1s→3s)
- Reduce global default polling frequency (1s→3s)
These changes significantly reduce concurrent API load across all tests and 
provide more time for rate limits to reset in overloaded test environments, 
improving test reliability without …

OCPBUGS-43824: fix(test): reduce API call frequency to prevent rate limiting in NTO machineconfig test

---

control-plane-operator/controllers/hostedcontrolplane/v2/cloud_controller_manager/azure/config.go
control-plane-operator/controllers/hostedcontrolplane/v2/cno/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/ingressoperator/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/kas/kms/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/registryoperator/azure.go
control-plane-operator/controllers/hostedcontrolplane/v2/storage/azure.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
support/config/constants.go
support/secretproviderclass/secretproviderclass.go
support/secretproviderclass/secretproviderclass_test.go

Overall, this PR removes code associated with Managed Identity v2. Specifically, this PR:
- updates the reconciliation of any SecretProviderClass CR to only use MIv3
- removes the ability to use ClientCertificate Authentication when reconciling the AzureClusterIdentity
- removes Azure constants associated with Managed Identity v2.
Fixes #
**Checklist**

OCPBUGS-59547: Remove code associated with Managed Identity v2 for ARO HCP for 4.19

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

otherwise we're going to keep hotlooping over the clusterrolebinding subject namespace
Fixes #
**Checklist**

NO-JIRA: unique clusterrole per hosted cluster for kubevirt CSI

---

test/e2e/util/util.go

Skips virt-launcher and console logger pods when checking for correct labels, tolerations, and TerminationMessagePolicy on HCP pods

NO-JIRA: test/e2e: skip kubevirt pods when checking labels, tolerations, and term msg policy

---

support/supportedversion/version.go

This PR ensures that `manifests.ConfigMap()` is correctly assigned to `supportedVersions` in the `GetSupportedOCPVersions()` function. This prevents the panic caused by `hypershift version` when retrieving the Server Version.
Fixes #[OCPBUGS-57316](https://issues.redhat.com/browse/OCPBUGS-57316)
Blocking #[CNTRLPLANE-262](https://issues.redhat.com/browse/CNTRLPLANE-262)
**Checklist**

OCPBUGS-57316: hypershift version in CLI returns panics for Server Version when HyperShift operator is deployed

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
support/globalconfig/authentication.go
support/globalconfig/authentication_test.go

Effectively, this is  back-port of two PRs: #6365 and #6367 .
This change does the following:
- Removes the secret defaulting logic for OIDC clients with no secret name.
- Adds unit tests for the reconcileAuthOIDC function.
The functionality originally intended by #6296 will be introduced in a different way in a separate PR. 
There's currently a draft PR for it on main #6375 
Fixes OCPBUGS-58683
**Checklist**

[release-4.19] OCPBUGS-58683:fix(hcco): Don't use a default OIDC client secret name when no secret name is provided 

---

.cursor/rules/code-formatting.mdc
.cursor/rules/git-commit-format.mdc
.gitlint
Makefile
docs/content/contribute/index.md

This PR:
- adds gitlint support for conventional commit enforcement
- updates the upstream contribute page to be more concise, improve readability and flow
- adds cursor rules for generating conventional commits
Fixes [CNTRLPLANE-1116](https://issues.redhat.com/browse/CNTRLPLANE-1116)
**Checklist**

CNTRLPLANE-1116: add gitlint support for conventional commit enforcement

---

.tekton/hypershift-shared-ingress-main-pull-request.yaml
.tekton/hypershift-shared-ingress-main-push.yaml

Add hermetic build support for the on-pr pipeline of the shared-ingress. This is necessary because the build is set to hermetic on push and without checking it properly on-pull-request, we might break the pipeline.
Fixes #[CNTRLPLANE-905](https://issues.redhat.com//browse/CNTRLPLANE-905)
**Checklist**

CNTRLPLANE-905: Fix hermetic pipelines for Shared ingress.

---

control-plane-operator/controllers/hostedcontrolplane/testdata/kube-controller-manager/TechPreviewNoUpgrade/zz_fixture_TestControlPlaneComponents_kube_controller_manager_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-controller-manager/zz_fixture_TestControlPlaneComponents_kube_controller_manager_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-controller-manager/deployment.yaml
test/e2e/util/client.go
test/e2e/util/util.go

1. Example of issue 1 - rate limiting in https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.20-periodics-e2e-aks/1947567107805810688
2. Example of issue 2 - KCM restarting during node cleanup - https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-hypershift-release-4.20-periodics-e2e-aks/1947478585400889344
Fixes #
**Checklist**

OCPBUGS-43824: Help fix flaky NTO tests

---

control-plane-operator/controllers/hostedcontrolplane/v2/ignitionserver/deployment.go
control-plane-operator/controllers/hostedcontrolplane/v2/ignitionserver/deployment_test.go

+ Enhance registry override to properly handle multiple mirrors
+ Add image availability verification and fallback mechanism
Fixes # OCPBUGS-54720
**Checklist**

Fix OCPBUGS-54720: HCP payload doesn't respect multiple

---

control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-collect-profiles.cronjob.yaml

All pods on the hosted control plane should have the terminationMessagePolicy set to FallbackToLogsOnError. This pod was missed because it is only sometimes present on in the HCP during the test run depending on its random cron schedule.
https://github.com/openshift/hypershift/pull/6291 merged yesterday and this is causing flakes in 4.19 tests.

NO-JIRA: fix: set terminationMessagePolicy to FallbackToLogsOnError for olm-collect-profiles

---

go.mod
support/util/imagemetadata.go
support/util/imagemetadata_test.go
support/util/util_test.go

Allows release images to utilize tags (instead of a shah) and still utilize the image and image metadata caches.
Fixes #OCPBUGS-53265
**Checklist**

OCPBUGS-53265: Use the image reference for the cache in the image metadata provider

---

api/hypershift/v1beta1/hostedcluster_types.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources_test.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
support/azureutil/azureutil.go
support/util/annotations.go
vendor/github.com/openshift/hypershift/api/hypershift/v1beta1/hostedcluster_types.go

Manual backport of #6375 
Fixes #[OCPSTRAT-2173](https://issues.redhat.com//browse/OCPSTRAT-2173)
**Checklist**

[release-4.19] OCPSTRAT-2173: feat(hcco): add support for hosted OIDC client secrets

---

cmd/infra/aws/destroy_iam.go

The current code just looks for the `infraID` anywhere an candiate OIDC Provider ARN.  This can lead to deletion of the wrong provider if the `infraID` is a substring of another cluster's `infraID`. For example, `test` and `test-2`.  If infra for `test` is destroyed, it might delete the provider for `test-2`.
This PR switches to an exact match on the `infraID` since we have the required information to do this.

NO-JIRA: fix(cmd): match infraID exactly on OIDC provider delete

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/kas/service.go
control-plane-operator/controllers/hostedcontrolplane/kas/service_test.go
control-plane-operator/controllers/hostedcontrolplane/oauth/service.go
control-plane-operator/controllers/hostedcontrolplane/oauth/service_test.go
control-plane-operator/controllers/hostedcontrolplane/v2/ignitionserver/service.go
control-plane-operator/controllers/hostedcontrolplane/v2/ignitionserver/service_test.go

When HCP contains router publish strategy for the
master services, IBM Cloud platform implementation will take care of the proper exposure of the
services, without using the actual cluster Router
(similar implementation to Azure). That is, CPO should not create any LoadBalancer or actual router deployment as part of reconciling the HCP.
The current change also makes the migration from NodePort services backward compatible, for existing clusters. That is, the NodePort services will remain as is
(they are not converted to regular ClusterIP services, resulting in permanently losing the reserved nodeports) allowing existing external clients (e.g. kubelet,
master proxy) to work as before, until they are also upgraded.
The expected behavior is to:
* Do not manage any ingress component (LB Svc, …

OCPBUGS-57450: Router publish strategy related changes for IBM Cloud platform

---

support/controlplane-component/defaults.go
support/controlplane-component/defaults_test.go

Without this, when there's no SCC as in ibm/aks, the etcd pod runs as root
Fixes #
**Checklist**

OCPBUGS-59959: Set explicit FSGroup and RunAsUser for etcd when there's no SCC

---

control-plane-operator/controllers/hostedcontrolplane/testdata/kube-controller-manager/TechPreviewNoUpgrade/zz_fixture_TestControlPlaneComponents_kube_controller_manager_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/kube-controller-manager/zz_fixture_TestControlPlaneComponents_kube_controller_manager_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/kube-controller-manager/deployment.yaml

selinux-warning-controller is an controller that emits warnings about Pods with wrong SELinux labels. It's opt-in upstream, because upstream clusters typically don't run with SELinux and it would be just waste of memory and CPU.
OpenShift need the controller running, because it has SELinux enabled, and it provides better UX for our users.
And we run e2e tests that expect the controller running, see [OCPBUGS-59886](https://issues.redhat.com/browse/OCPBUGS-59886).
A similar change has been done to standalone OCP: https://github.com/openshift/cluster-kube-controller-manager-operator/pull/834

OCPBUGS-59886: Add selinux-warning-controller to KCM

---

.tekton/control-plane-operator-4-16-pull-request.yaml
.tekton/control-plane-operator-4-16-push.yaml

We need to move to hermetic builds for Enterprise contract compliance (as well as bump outdated tekton tasks).
Fixes #[CNTRLPLANE-1231](https://issues.redhat.com//browse/CNTRLPLANE-1231)
**Checklist**

CNTRLPLANE-1231: Move CPO pipeline to hermetic builds

---

.tekton/control-plane-operator-4-15-pull-request.yaml
.tekton/control-plane-operator-4-15-push.yaml

We need to move to hermetic builds for Enterprise contract compliance (as well as bump outdated tekton tasks).
Fixes #[CNTRLPLANE-1232](https://issues.redhat.com//browse/CNTRLPLANE-1232)
**Checklist**

CNTRLPLANE-1232: Move CPO pipeline to hermetic builds

---

control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-image-registry-operator/TechPreviewNoUpgrade/zz_fixture_TestControlPlaneComponents_cluster_image_registry_operator_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-image-registry-operator/zz_fixture_TestControlPlaneComponents_cluster_image_registry_operator_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-storage-operator/TechPreviewNoUpgrade/zz_fixture_TestControlPlaneComponents_cluster_storage_operator_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-storage-operator/zz_fixture_TestControlPlaneComponents_cluster_storage_operator_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/featuregate-generator/TechPreviewNoUpgrade/zz_fixture_TestControlPlaneComponents_featuregate_generator_job.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/featuregate-generator/zz_fixture_TestControlPlaneComponents_featuregate_generator_job.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/olm-collect-profiles/TechPreviewNoUpgrade/zz_fixture_TestControlPlaneComponents_olm_collect_profiles_cronjob.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/olm-collect-profiles/zz_fixture_TestControlPlaneComponents_olm_collect_profiles_cronjob.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-image-registry-operator/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/cluster-storage-operator/deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/featuregate-generator/job.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/assets/olm-collect-profiles/cronjob.yaml
test/e2e/create_cluster_test.go
test/e2e/util/util.go

HCM is looking to export logs indexed on the app label but it is missing on a few HCP components.
The PR adds the app label to these components.
Components listed in the bug
```
olm-collect-profile
aws-ebs-csi-driver-operator
cluster-image-registry-operator
cluster-storage-operator
```
`aws-ebs-csi-driver-operator` is deployed by the CSO and the change will need to be made there in this PR
https://github.com/openshift/cluster-storage-operator/pull/603

OCPBUGS-60064: fix(OCPBUGS-60064): add missing app label to some components

---

docs/content/contribute/cpo-overrides.md
docs/mkdocs.yml
hypershift-operator/controlplaneoperator-overrides/assets/overrides.yaml
hypershift-operator/controlplaneoperator-overrides/assets/overrides_sample.yaml
hypershift-operator/controlplaneoperator-overrides/overrides.go
hypershift-operator/controlplaneoperator-overrides/overrides_test.go
support/util/util.go
test/e2e/util/options.go

Modifies the CPO override file format to allow specifying a platform for the overrides. The file should contain the lower case platform name and the list of version overrides for that platform.
This is needed to support CPO overrides that are specific to ARO deployments of the HyperShift operator and are different from the ROSA deployments.
Fixes #[CNTRLPLANE-1190](https://issues.redhat.com/browse/CNTRLPLANE-1190)
**Checklist**

CNTRLPLANE-1190: Support control plane overrides by platform

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
support/awsutil/errorcode.go
support/awsutil/sg.go
support/util/util.go

This fixes the issue where failing to update the tags annotation on the HCP, will cause the CPO to try to update the tags on the SG without day2 changes.
Fixes #
**Checklist**

CNTRLPLANE-995: Fix Default SG day2 tags feature being triggered without changes

---

support/globalconfig/imagecontentsource.go
support/globalconfig/imagecontentsource_test.go

If there are multiple ICSPs configured in the mgmt cluster, the List is not determinstic and the ICSPs can be returned in any order.  This can lead to redeployment of the CPO when reordering on the OPENSHIFT_IMG_OVERRIDES occurs.
This change sorts the ICSPs by name so that OPENSHIFT_IMG_OVERRIDES is deterministic.

OCPBUGS-57626: order ICSPs for determinism of OPENSHIFT_IMG_OVERRIDES

---

test/e2e/e2e_test.go
test/e2e/external_oidc_test.go
test/e2e/util/external_oidc.go
test/e2e/util/hypershift_framework.go
test/e2e/util/options.go
test/e2e/util/util.go

* Added external OIDC e2e test based on keycloak service
* Test passed in my local env
* This is a new test added with new parameters. It should not affect the existing test cases in the prow job.
* By default, the new external oidc case should be skipped due the the empty value of new parameter `e2e.external-oidc-provider`
```
=== RUN   TestExternalOIDC/Main
=== RUN   TestExternalOIDC/Main/[OCPFeatureGate:ExternalOIDC]_test_keycloak_external_OIDC
external_oidc_test.go:38: begin to test external OIDC keycloak
util.go:252: Waiting for kubeconfig to be published for HostedCluster e2e-clusters-rndq5/external-oidc-tqhpr
eventually.go:224: observed *v1beta1.HostedCluster e2e-clusters-rndq5/external-oidc-tqhpr valid at RV 153448 after 525ms: expected a kubeconfig reference in status …
```

NO-JIRA: test(e2e): add new test for external OIDC

---

hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
hypershift-operator/controllers/hostedcluster/security_context_uid.go
hypershift-operator/controllers/hostedcluster/security_context_uid_test.go

This is an iterative follow up for https://github.com/openshift/hypershift/pull/6520
Before this, uids would just grow sequentially forever
Fixes #
**Checklist**

OCPBUGS-60190: chore: Improve security context uid allocation to reuse released uids

---

control-plane-operator/controllers/hostedcontrolplane/kas/healthcheck.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller_test.go
test/e2e/nodepool_additionalTrustBundlePropagation_test.go

Follow up to #6504
Ensures that additionalTrustBundle reference is removed from HostedControlPlane when it has been removed from HostedCluster.
Fixes #[OCPBUGS-57336](https://issues.redhat.com/browse/OCPBUGS-57336)
**Checklist**

OCPBUGS-57336: fix(hostedcluster): remove additionalTrustBundle from hcp when removed from HostedCluster

---

test/e2e/e2e_test.go
test/e2e/external_oidc_test.go
test/e2e/util/external_oidc.go

Add e2e test for external OIDC ExternalOIDCWithUIDAndExtraClaimMappings feature set in HostedCluster
It is for the GA of external oidc ExternalOIDCWithUIDAndExtraClaimMappings 
The related periodical job in the prow is https://github.com/openshift/release/pull/67531
**Checklist**
** local test passed **
```
=== RUN   TestExternalOIDCTechPreview/Main
external_oidc_test.go:76: begin to test external OIDC with TechPreviewNoUpgrade enabled keycloak
...
external_oidc_test.go:86: selfSubjectReview &SelfSubjectReview{ObjectMeta:{      0 2025-08-11 17:36:01 +0800 CST <nil> <nil> map[] map[] [] [] []},Status:SelfSubjectReviewStatus{UserInfo:UserInfo{Username:oidc-user-test:keycloak-testuser-45@example.com,UID:testuid-89d38910-ff64-4c79-b38b-d0f345f19581-uidtest,Groups:[oidc-groups-test:keycloak-tes …
```

CNTRLPLANE-946: test(e2e): Add e2e test for ExternalOIDCWithUIDAndExtra feature set

---

.tekton/control-plane-operator-4-18-pull-request.yaml
.tekton/control-plane-operator-4-18-push.yaml

As part of the IC role, this is a chore task from konflux to be applied in release-4.18 tekton files. The changes includes:
- Followed https://github.com/openshift/hypershift/pull/6623
- Removing clamav update due to issues in version 0.3. More info here: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1755158159626709?thread_ts=1755003112.565669&cid=C04PZ7H0VA8

CNTRLPLANE-1269: chore(deps): update konflux references

---

contrib/konflux/cpo_4_19_stream.yaml
contrib/konflux/cpo_development_stream_template.yaml
contrib/konflux/ho_development_stream_template.yaml

This commit:
* Fixes the templates so that the PR for the pipelines is correctly created by konflux
* Adds a ProjectDevelopmentStream for CPO 4.19
Fixes #[CNTRLPLANE-1270](https://issues.redhat.com//browse/CNTRLPLANE-1270)
**Checklist**

CNTRLPLANE-1270: Fix ProjectDevelopmentStreamTemplates

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/recovery/recovery.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/recovery/recovery_test.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go

This PR include some fixes for the HCCO that will be triggered after a HostedCluster is restored:
- Use cpClient to update HCP status for restoration condition
- Get the STS pods before deletion to identify them properly
- Delete the PVCs from openshift-monitoring namespace
- Add comprehensive unit tests for RecoverMonitoringStack function which includes a concurrent test with 10 goroutines to verify thread-safety
- Use of AtomicBool to ensure we only hit the recovery once
- Image: `quay.io/jparrill/hypershift:OCPBUGS-56430-v53`
- ✅ Verified in ROSA Int
Fixes #[OCPBUGS-56430](https://issues.redhat.com/browse/OCPBUGS-56430)

OCPBUGS-56430: fix: Add recovery monitoring stack fixes

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
control-plane-operator/controllers/hostedcontrolplane/v2/ignitionserver/route.go
control-plane-operator/controllers/hostedcontrolplane/v2/router/component.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
support/util/expose.go
support/util/visibility.go

* Label the OAuth Route for admission by the private router only if the OAuth endpoint has hostname (external DNS). This fixes the case when KAS is exposed as LoadBalancer and OAuth via Route without specifying external DNS.
* In order to fix the previous point, label routes for admission by the private router independently from each other (previously, all routes were labeled based on KAS Route)
* Expose private HCP router service if the endpoint access is Private or any endpoint exposes Route with external DNS. (previously it took into account just KAS Route). This fixes the missing routerCanonicalHostname on OAuth Route when KAS has LoadBalancer strategy and OAuth has Route *with* external DNS.
* Add unit test for renconciling OAuth Service and …

OCPBUGS-56914: fix: Do not admit OAuth route by private router unless it has external DNS

---

.tekton/hypershift-cli-mce-210-pull-request.yaml
.tekton/hypershift-cli-mce-210-push.yaml
.tekton/hypershift-release-mce-210-pull-request.yaml
.tekton/hypershift-release-mce-210-push.yaml

This PR fixes the hypershift operator konflux EC violation for MCE 2.10
Fixes #https://issues.redhat.com/browse/OCPBUGS-60651
**Checklist**

OCPBUGS-60651: fix mce 2.10 Konflux EC violation

---

docs/content/labs/Dual/hostedcluster/hostedcluster.md
docs/content/labs/IPv4/hostedcluster/hostedcluster.md
docs/content/labs/IPv6/hostedcluster/hostedcluster.md

This PR remove the documentation's note about BM deployment with mandatory CPO override annotation.

NO-JIRA: fix(doc): remove note about mandatory annotation in BM deployment

---

control-plane-operator/controllers/hostedcontrolplane/cloud/azure/params.go
control-plane-operator/controllers/hostedcontrolplane/cno/clusternetworkoperator.go
control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
control-plane-operator/controllers/hostedcontrolplane/ignitionserver/ignitionserver.go
control-plane-operator/controllers/hostedcontrolplane/snapshotcontroller/operator.go
support/config/deployment.go

This was introduced in 4.20 via
https://github.com/openshift/hypershift/pull/6520
https://github.com/openshift/hypershift/pull/6612
And in 4.19 via
https://github.com/openshift/hypershift/pull/6592
This PR add some missing components for 4.19
Fixes #
**Checklist**

OCPBUGS-60100: fix: add dynamic security context uid to 4.19 missing components

---

hypershift-operator/controlplaneoperator-overrides/assets/overrides.yaml

Update overrides to point the CPO image at a version containing:
- Caching Azure KMS TokenCredential for ARO HCP
- Dynamic securityContext UID for missing 4.19 components
Fixes #
**Checklist**

NO-JIRA: Update-overrides for ARO HCP Fixes

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/registry/admissionpolicies.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/registry/admissionpolicies_test.go
control-plane-operator/hostedclusterconfigoperator/controllers/resources/resources.go

Fixes OCPBUGS-59194 by deleting the Image Registry ValidatingAdmissionPolicy (VAP) and its binding during HostedControlPlane deletion for ARO HCP clusters. This allows setting `managementState: Removed` to perform cloud resource cleanup.
- **Deletion during teardown**: When `HostedControlPlane.DeletionTimestamp` is set (and ARO HCP is detected), the controller:
- Deletes the `ValidatingAdmissionPolicyBinding` first, then the `ValidatingAdmissionPolicy`
- Ignores NotFound errors for idempotency
- **Normal operation remains enforced**: When not deleting, the policy continues to deny setting `managementState: Removed` for all users except `system:hosted-cluster-config`.
- **Reconciliation hook**: The main reconciliation loop for ARO HCP continues to call into the registry admission policy …

OCPBUGS-59194: fix(registry): delete ValidatingAdmissionPolicy and binding during HCP deletion for ARO cleanup

---

control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-storage-operator/TechPreviewNoUpgrade/zz_fixture_TestControlPlaneComponents_cluster_storage_operator_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/testdata/cluster-storage-operator/zz_fixture_TestControlPlaneComponents_cluster_storage_operator_deployment.yaml
control-plane-operator/controllers/hostedcontrolplane/v2/storage/envreplace.go

This is a fixup of cd6ef8ad6 where this replacement was missed.
The CI job `hypershift-aws-e2e-external` keeps failing, probably because the replacement does not work well without this reference in envreplace.go: 
```
- name: KUBE_RBAC_PROXY_CONTROL_PLANE_IMAGE
value: registry.build10.ci.openshift.org/ci-op-yxlifx2r/stable@sha256:6e23a1d8ce238f26b9816945b6b59ba49dae0590cff9ce0cd9715dfec413b74d
- name: TOOLS_IMAGE
value: registry.build10.ci.openshift.org/ci-op-yxlifx2r/stable@sha256:928d1c0675b4799d67406c6ab27c64525321dcc745ea3ad4d2049c4642757115
- name: VOLUME_DATA_SOURCE_VALIDATOR_IMAGE
value: quay.io/openshift/origin-volume-data-source-validator:latest
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-storage-operator/592/pul …

STOR-1064: fix(cpo): add missing image to env replacement

---

support/catalogs/images.go

v4.21 catalogs have a filesystem permissions error that are causing HCP to fail to deploy.
Temporarily use v4.20 catalogs until this is fixed.

OCPBUGS-61462: temporarily use v4.20 catalogs

---

konnectivity-https-proxy/cmd.go
konnectivity-https-proxy/cmd_test.go

Ensure that request URL scheme is set before calling the function to determine if the request should be proxied. Most of the time the URL on the reuqest does not have a scheme, which results in the request not being proxied when it should be.
This fixes a regression introduced by
https://github.com/openshift/hypershift/pull/6207
The line that was forcing the scheme did not get included in the refactored code:
https://github.com/openshift/hypershift/pull/6207/files#diff-3cac822ca922efb3139322e3504be609cdf661749116ceda0bb40100f66e7563L176
Fixes # …

OCPBUGS-61482: fix(proxy): ensure URLs have scheme before proxy resolution

---

test/e2e/util/util.go

PSA was disabled for 4.20 so don't check EnsurePSANotPrivileged
prereq for https://github.com/openshift/hypershift/pull/6830

fix(disable-psa): disable PSA check for 4.20

---

.tekton/hypershift-release-mce-210-push.yaml

In order to simplify Multi Cluster Engine HyperShift Operator image discovery in Quality Engineering verification, let's tag the built images in Konflux so it is always evident which is the latest build.
Fixes #[CNTRLPLANE-1397](https://issues.redhat.com//browse/CNTRLPLANE-1397)
**Checklist**

CNTRLPLANE-1397: feat(konflux): tag MCE HO images with latest

---

control-plane-operator/controllers/hostedcontrolplane/v2/assets/capi-provider/deployment.yaml
hypershift-operator/controllers/hostedcluster/internal/platform/aws/aws.go
hypershift-operator/controllers/hostedcluster/internal/platform/azure/azure.go
hypershift-operator/controllers/hostedcluster/testdata/capi-provider/zz_fixture_TestReconcileComponents.yaml
hypershift-operator/controllers/hostedcluster/testdata/capi-provider/zz_fixture_TestReconcileComponents_component.yaml

Fix capi-provider deployment replicas to be 1 for both AWS and Azure platforms.
- Remove unused replicas and deployment strategy from YAML template
- Update test fixtures to reflect single replica configuration
Fixes #
**Checklist**

OCPBUGS-61687: fix(capi-provider): use single replica deployment for aws and azure

---

test/e2e/autoscaling_test.go
test/e2e/util/util.go

Add additional verification step to ensure the autoscaler deployment has the correct balancing ignore label configuration and is ready before proceeding with workload generation.
This provides more comprehensive validation of autoscaling setup by checking both the NodePool condition and the actual deployment configuration.
Assisted-by: claude-3-5-sonnet-20241022 (via Cursor)
Fixes #OCPBUGS-61048

OCPBUGS-61048: test(e2e): add autoscaler deployment verification to autoscaling test

---

control-plane-operator/controllers/hostedcontrolplane/v2/ignitionserver/deployment.go
support/globalconfig/imagecontentsource.go
support/releaseinfo/registry_image_content_policies.go
support/util/imagemetadata.go
support/util/imagemetadata_test.go
support/util/util.go

This is manual cherry-pick of https://github.com/openshift/hypershift/pull/6803.
This is done manual due to build errors
/cherrypick release-4.18

[release-4.19] OCPBUGS-61677: resolve MIRRORED_RELEASE_IMAGE flapping

---

test/integration/control_plane_pki_operator.go

This test does not apply to the kubevirt platform, as it's a managed service side feature.
Fixes #
**Checklist**

OCPBUGS-61825: test(e2e,kubevirt): skip break-glass-credentials on kubevirt

---

control-plane-operator/controllers/hostedcontrolplane/ingress/router_test.go
hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
hypershift-operator/controllers/scheduler/aws/dedicated_request_serving_nodes.go
hypershift-operator/controllers/scheduler/aws/dedicated_request_serving_nodes_test.go

Backport of https://github.com/openshift/hypershift/pull/6823
* Add AWSLoadBalancerTargetNodesAnnotation to the list of mirrored annotations in reconcileHostedControlPlaneAnnotations. This enables AWS load balancer target node configurations set on HostedCluster resources to be properly propagated to their corresponding HostedControlPlane resources.
* Propagate osd-fleet-manager.openshift.io/paired-nodes label from
request-serving nodes and set it as
service.beta.kubernetes.io/aws-load-balancer-target-node-labels
annotation on HC.
Fixes …

[release-4.20] OCPBUGS-61066: fix: propagate AWSLoadBalancerTargetNodesAnnotation to HCP

---

test/e2e/control_plane_upgrade_test.go
test/e2e/create_cluster_test.go
test/e2e/util/util.go

The existing check does not work with the pruning behavior of kas-bootstrapper.  The only version assured to be in the FeatureGate status is the most recent Completed version in the ClusterVersion history i.e. the currently running version.
FeatureGate status pruning by `kas-bootstrap`
https://github.com/openshift/hypershift/blob/b8db9eda2b7852e1bf2f416b2c954e1ff12bddde/kas-bootstrap/kas_boostrap.go#L127-L131

OCPBUGS-61828: refactor FeatureGate status check

---

control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/reconcile.go

- Add allowPrivilegeEscalation: false to prevent privilege escalation
- Enable readOnlyRootFilesystem: true for immutable container filesystem
- Set runAsNonRoot: true to enforce non-root execution
- Drop all capabilities with capabilities.drop: [ALL]
- Fixes #[OCPBUGS-61438](https://issues.redhat.com/browse/OCPBUGS-61438)

OCPBUGS-61438: fix(security): harden konnectivity-agent DaemonSet security context

---

docs/content/how-to/ci/checking-ci.md
docs/mkdocs.yml

Add new documentation page explaining how to check CI job status, access artifacts, and debug common CI failures. Updates navigation in mkdocs.yml to include new CI section.
Fixes [CNTRLPLANE-1452](https://issues.redhat.com//browse/CNTRLPLANE-1452)
**Checklist**

CNTRLPLANE-1452: docs(ci): add documentation for checking CI status

---

control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller_test.go
support/controlplane-component/generic-adapter.go

Fix ignition server reconciliation deleting user-managed ignition server certificate secrets if the `disable-pki-reconciliation` annotation is present.
This prevented ignition server pods from starting up completely due to the missing secrets.
Fixes [OCPBUGS-61776](https://issues.redhat.com/browse/OCPBUGS-61776)
**Checklist**

OCPBUGS-61776: fix(ignition-server): Don't delete user-managed cert secrets

---

contrib/ci/dev-namespace-template.yaml

The indentation of the annotation on the dev token secret was wrong, causing the template creation to fail.
Now the secret is created correctly when applying the template.
**Checklist**

NO-JIRA: ci(dev-cluster): Fix dev token secret annotation

---

control-plane-operator/controllers/hostedcontrolplane/v2/capi_provider/component.go
hypershift-operator/controllers/hostedcluster/internal/platform/kubevirt/kubevirt.go
hypershift-operator/controllers/hostedcluster/testdata/capi-provider/zz_fixture_TestReconcileComponents.yaml

The CAPZ (Cluster API Provider Azure) pod was experiencing startup failures
with 'connection refused' errors when attempting to connect to the API server
before the cluster infrastructure was fully initialized.
This change adds `WaitForInfrastructureResource: true` to the availability prober
configuration for the capi-provider component, ensuring the init container waits
for the Infrastructure/cluster resource to be available with a populated
infrastructureName before allowing the CAPZ controller to start.
This `WaitForInfrastructureResource: true` setting requires the `svc-kubeconfig`
to be mounted into the deployment so the component can query the infrastructure resource.
This prevents the controller from attempting REST API discovery operations
before the control plane is ready to …

OCPBUGS-61936: fix(capi-provider): wait for infrastructure resource before startup

---

.claude/commands/jira-solve.md

This lets reviewers see the /jira-solve claude command that triggered execution
Fixes

NO-JIRA: chore(ai): let jira-solve show the executed command in the PR desc

---

.claude/commands/jira-solve.md

This change the spec to be more prescriptive on running make pre-commit before creating a PR
Fixes

NO-JIRA: chore(ai): ensure jira-solve run make pre-commit

---

test/e2e/util/util.go

All CSI operators are currently deployed with `readOnlyRootFilesystem=false` (since https://github.com/openshift/cluster-storage-operator/pull/564). However, while the other platform operators are explicitly whitelisted, OpenStack is not. Likewise, while most other controllers don't mount `/tmp`, the OpenStack providers are missing from *that* whitelist. Correct both oversights.
We also don't universally call the emptyDir mount "tmp-dir" (at least the csi-operator and cluster-storage-operator don't do this) so a reference to same is removed.
Fixes OCPBUGS-62172

OCPBUGS-62172: Add Manila, Cinder to list of pods allowed readOnlyRootFileSystem=false

---

.tekton/hypershift-operator-main-pull-request.yaml
.tekton/hypershift-operator-main-push.yaml
.tekton/hypershift-operator-main-tag.yaml
Containerfile.control-plane
Containerfile.operator

Update container base images in both Containerfile.control-plane and Containerfile.operator from registry.redhat.io RHEL9 ELS images to registry.access.redhat.com UBI9 minimal 9.4 for:
* Unauthenticated pulls
* Smaller sizes
* Fix Enterprise contract.
Also clean up COPY command formatting in Containerfile.operator for better readability.
Fixes: [KFLUXSPRT-5246](https://issues.redhat.com//browse/KFLUXSPRT-5246)

KFLUXSPRT-5246: update base images from RHEL9 ELS to UBI9 minimal 9.4

---

test/e2e/util/options.go

Annotation parsing on the `test-e2e` command fails when annotations have more than one `=` character on the value (e.g. `-e2e.annotations="hypershift.openshift.io/image-overrides=my-component=my-image"`)
Fixes [OCPBUGS-62324](https://issues.redhat.com/browse/OCPBUGS-62324)
- One liner fix for flag parsing.

OCPBUGS-62324: Fix test-e2e `annotations` flag parsing

---

docs/content/how-to/azure/azure-workload-identity-setup.md
docs/content/how-to/azure/create-self-managed-azure-cluster.md
docs/content/how-to/azure/setup-management-cluster.md
docs/mkdocs.yml

Add comprehensive guides for setting up self-managed Azure HostedClusters:
- Azure workload identity setup with OIDC issuer configuration
- Management cluster setup for HyperShift operator and ExternalDNS
- Self-managed HostedCluster creation with workload identity authentication
- Update mkdocs navigation to organize Azure docs by managed/self-managed
Fixes [CNTRLPLANE-1332](https://issues.redhat.com/browse/CNTRLPLANE-1332)
**Checklist**

CNTRLPLANE-1332: docs(azure): add self-managed cluster setup documentation

---

docs/content/how-to/azure/azure-workload-identity-setup.md

This PR corrects a spelling mistake in the documentation to improve clarity and professionalism.
A part of [CNTRLPLANE-1332](https://issues.redhat.com//browse/CNTRLPLANE-1332)
This is a simple documentation fix with no functional changes.

CNTRLPLANE-1332: docs(readme): correct spelling mistake

---

.ci-operator.yaml
Dockerfile
Dockerfile.control-plane
Dockerfile.dev
Dockerfile.e2e

This PR updates all HyperShift container base images to version 4.21 to align with the upcoming OpenShift release cycle. Specifically:
- Updates development and e2e builder images (Dockerfile, Dockerfile.dev, Dockerfile.e2e) to use 4.21 base images
- Updates the ose-hypershift-container image reference in Dockerfile.control-plane to be consistent with ART (Automated Release Tooling) for 4.21
- Updates CI operator configuration (.ci-operator.yaml) to reference the correct 4.21 image streams
These changes ensure that HyperShift development, testing, and production images are built on the latest OpenShift 4.21 base images with the most recent security updates and platform features.
Fixes OCPBUGS-62407
- All changes are version bumps in container image references
- No functional code changes …

OCPBUGS-62407: chore(build): update container images to 4.21

---

control-plane-operator/controllers/hostedcontrolplane/kas/config.go

- Fixes # https://issues.redhat.com/browse/OCPBUGS-62202, manually cherry-pick https://github.com/openshift/hypershift/pull/6855 since in 4.19.z the default CPO is still v1.
- To complement https://github.com/openshift/cluster-kube-apiserver-operator/pull/1761, we need to enable the `storage.k8s.io/v1beta1` when the VolumeAttributesClass gate is enabled.
The VolumeAttributesClass is not enabled by default upstream yet but we are intending to enable it downstream for testing and development of tech preview features.
**Local test passed**:
- Manually replace the CPO image with the fix commit build.
```console
$ oc get --raw /apis/storage.k8s.io/v1beta1 | jq .resources
[
{
"name": "volumeattributesclasses",
"singularName": "volumeattributesclass", …
```

[release-4.19] OCPBUGS-62202: Enable VolumeAttributesClass runtime config
